// BTS 3 새 교재 설계 데이터. k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
// 사진 번호 = public/img/scene-words/<번호>.webp · c로 시작 = scene-clips · gen: = 새로 만들 사진(gen/req-bts-03.json)
import { open, close, HELLO } from '../common.mjs';

const FAM = 'Unit 1', AGE = 'Unit 2', WHO = 'Unit 3';
const FINGER = ['Daddy finger, where are you?', 'Here I am! How do you do?', 'Mommy finger, where are you?', 'Here I am! How do you do?', 'Brother, sister, baby too!'];
const TWISTER = ['Father, mother, sister, brother,', 'hand in hand with one another.', '(Say it 3 times — faster and faster! 🏎️)'];
const twisterNote = ['원본 그대로의 잰말놀이. 1번 천천히 → 2번 보통 → 3번 빠르게', '틀려도 웃고 넘어가는 쪽입니다 — 입을 푸는 것이 목적'];

export const COURSE = {
  head: `<h1>BTS 3 새 교재 — 전 과 설계 시안 (My Family)</h1>
<p class="lead">사이트에 올라가 있는 BTS 3 원본 <b>226쪽</b>(11묶음)을 한 장씩 읽어 원고로 옮긴 뒤, 제안서의 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · 과 끝 «I can» · 다음 시간 예고)으로 다시 짰습니다. 위 단추로 과를 고르세요.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>배우는 <b>낱말(가족·머리·눈 색·나이)·문장(He/She is my…, has/have, I am … years old)·문법 범위는 원본 그대로</b>입니다. 교재 이름도 바꾸지 않습니다. 원본에 있던 오타·문법 오류·어긋난 사진은 고쳤습니다(과마다 목록).</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>권 전체를 <b>한나네 가족 이야기</b> 하나로 이었습니다 — 001 가족의 날 → 004 가족사진 속 할아버지·할머니 → 007 사촌 아기의 첫 돌잔치. 과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>, <b>⭕❌</b>, <b>Guess who</b>, <b>Your turn</b>, <b>I can ✅</b>, <b>다음 시간 예고</b>를 넣었습니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>사진은 <b>지금 사이트에 있는 640px 사진</b>을 자리 채움으로 넣었습니다. 점선 상자는 <b>맞는 사진이 없어 새로 만들 자리</b>입니다(한나네 가족처럼 여러 쪽에 같은 인물이 나와야 하는 장면 포함).</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>고친 문장 승인</b> — 과마다 «이 과에서 고친 것» 목록. 특히 003·REVIEW 의 <b>black eyes → brown eyes</b>(영어로 black eye 는 «멍든 눈»), 004 «have the same age → are the same age», 001·TEST 의 «Do you have any sisters? No» 인데 사진에 여자아이가 있던 문제.</li>
<li><b>aunt·uncle 한국어 뜻</b> — 원본은 aunt=이모, uncle=삼촌으로만 가르칩니다. 영어는 고모·숙모·외숙모도 모두 aunt 라서 «이모·고모» 로 넓혀 적었습니다. 원본 설명(aunt = 엄마의 여자 형제)을 그대로 둘지 결정해 주세요.</li>
<li><b>blonde / blond</b> — 원본은 «여자는 blonde, 남자는 blond» 로 가르칩니다. 지금 영어는 둘을 섞어 쓰는 경우가 많아 «둘 다 금발» 이라는 강사 메모를 붙였습니다. 이 구분을 계속 가르칠지.</li>
<li><b>«I am 63. I am old.»</b> — 원본 문장 그대로 두었습니다. 어린 학생이 할머니·할아버지를 «old» 라고 부르는 것을 연습할 때 무례하게 들릴 수 있다는 강사 메모만 달았습니다.</li>
<li><b>노래 곡조</b> — Family Finger Song 은 전래 동요 곡조입니다. 녹음 음원 저작권 확인.</li>
<li><b>인물 이름</b> — 원본의 Miss Gray(001), Mister Lee(004·007), Mister Bill·Mister Wood(목표 쪽)를 한 권 안에서 Miss Gray·Mister Lee 둘로 줄였습니다.</li>
<li><b>새로 만들 사진 37장</b> — 한나네 가족(아빠 검은 머리·엄마 갈색 머리·오빠·남동생), 이모 애나·삼촌 벤, 사촌 아기 첫 돌잔치는 같은 인물로 여러 장이 필요합니다(힉스필드 크레딧).</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '가족', unit: FAM, title: 'My Family', orig: 27,
    intro: '가족 낱말(father·mother·brother·sister·sibling·parents)과 «He/She is my …», «They are my parents», has / have 를 배웁니다. 이야기: 내일은 한나 학교의 «가족의 날»! 한나가 가족사진을 보여 줍니다.',
    fixed: ['오타 Auxilliary→Auxiliary', 'excited 뜻 «흥미진진한»→«신이 난» · elder «연장자»→«나이가 더 많은» · younger «더 젊은»→«더 어린»', '14쪽 «Do you have any sisters? — No» 인데 사진에 여자아이가 있음 → 형제만 있는 사진으로', '23쪽 이야기 질문 쪽에 답(5, ✗, brown)이 미리 적혀 있음 → 빈칸으로', '«He/She is my sibling» — sibling 뜻을 «형제/자매»로 한 번에 설명', '쉼표·물음표 앞 띄어쓰기 여러 곳'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-picnic', q: 'Who is in your family?', story: 'Tomorrow is Family Day at Hannah\'s school!', nt: '표지 + Big Question', n: ['수업을 질문으로 엽니다: 네 가족에는 누가 있니?', '끝날 때 이 질문에 «My family has …» 로 답하는 것이 목표입니다'] },
      ...open([['I can name my family.', '가족을 영어로 부를 수 있어요 — father, mother, brother, sister.'], ['I can say "He is my brother."', '«He/She is my …», «They are my parents.» 로 소개할 수 있어요.'], ['I can say "I have a brother."', 'has / have 로 가족이 있다고 말할 수 있어요.']]),
      { t: 'song', k: 'fix', title: 'Family Finger Song', lines: FINGER, img: 'gen:bts-03-fingers', src: 'Warm Up', nt: '손가락 가족 노래', n: ['손가락을 하나씩 세우며 부릅니다(엄지 = daddy, 검지 = mommy …)', '원본 가사를 화면에 맞게 줄였습니다(부를 때는 원래 가사 그대로) · 쉼표 앞 띄어쓰기 정리'] },
      { t: 'vocab', k: 'fix', hide: true, words: [['family', '가족', '16380'], ['father', '아버지', 'c7228'], ['mother', '어머니', 'c7237'], ['sister', '여자 형제(언니·누나·여동생)', 'c7229'], ['brother', '남자 형제(오빠·형·남동생)', 'c7263'], ['parents', '부모님', 'c7451']], src: 'Vocabulary 6쪽', nt: '낱말 — 뜻을 가리고 먼저 떠올리기', n: ['사진만 보고 영어로 먼저 말하게 합니다(인출 연습)', 'sister/brother 는 한국어로 나이·성별마다 다른 말이 있다는 것을 짚어 줍니다'] },
      { t: 'vocab', k: 'keep', words: [['family', '가족', '16380'], ['father', '아버지', 'c7228'], ['mother', '어머니', 'c7237'], ['sister', '여자 형제', 'c7229'], ['brother', '남자 형제', 'c7263'], ['sibling', '형제자매', '17038']], title: 'Words', src: '6쪽', nt: '낱말 — 뜻 공개', n: ['sibling = brother 와 sister 를 한 번에 부르는 말', '따라 말하기 2번 → 강사가 사진을 가리키면 학생이 말하기'] },
      { t: 'rule', k: 'new', title: 'Is or are?', left: { h: 'One person', ex: ['He **is** my father.', 'She **is** my sister.'] }, right: { h: 'Two or more', ex: ['They **are** my parents.', 'They **are** my brothers.'] }, q: 'When do we say "is"? When do we say "are"?', nt: '규칙 찾기', n: ['설명 전에 두 묶음을 보고 학생이 규칙을 먼저 말하게 합니다', '한 사람 → is, 여러 사람 → are'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'He is my brother.', head: ['who', 'is / are', 'my + family'], rows: [['He', 'is', 'my father. / my brother.'], ['She', 'is', 'my mother. / my sister.'], ['They', 'are', 'my parents. / my siblings.']], tip: 'my = 나의 · 한 사람 is, 여러 사람 are', src: 'Grammar 7·8쪽', nt: '문장 틀', n: ['원본의 Pronoun/Auxiliary Verb 용어는 강사 메모로 옮겼습니다'] },
      { t: 'qa', k: 'keep', img: '12080', q: 'Who is he?', a: 'He is my ___.', chips: ['father', 'mother', 'brother'], src: '9쪽', nt: '따라 말하기', n: ['아빠가 아이를 목말 태운 사진 — «He is my father.»'] },
      { t: 'qa', k: 'keep', img: '12166', q: 'Who is she?', a: 'She is my ___.', src: '10쪽', nt: '바꿔 말하기' },
      { t: 'qa', k: 'keep', img: 'c7451', q: 'Who are they?', a: 'They are my ___.', src: '11쪽', nt: 'they are' },
      { t: 'rule', k: 'fix', title: 'has or have?', left: { h: 'he / she', ex: ['He **has** a brother.', 'She **doesn\'t have** a sister.'] }, right: { h: 'I / you / they', ex: ['I **have** black hair.', 'They **don\'t have** white hair.'] }, q: 'Who says "has"? Who says "have"?', src: 'Grammar 12·13쪽', nt: '규칙 찾기 — has / have', n: ['he/she 뒤에는 has, I/you/they 뒤에는 have', 'doesn\'t have / don\'t have 는 «없다»'] },
      { t: 'qa', k: 'fix', img: '12151', q: 'Do you have any sisters?', a: "No, I don't. I have a ___.", chips: ['brother', 'sister'], src: '14쪽', nt: '❗ 사진 고침', n: ['원본: «No» 라고 답하는데 사진에 여자아이가 있었습니다 → 형제만 있는 사진으로', '«No, I don\'t.» 다음에 «바른 답» 한 문장 더 말하기'] },
      { t: 'vocab', k: 'fix', title: 'New words 📖', words: [['family day', '가족의 날', 'gen:bts-03-family-day'], ['excited', '신이 난', '12614'], ['elder', '나이가 더 많은', '16754'], ['younger', '더 어린', '17038'], ['black', '검은색', '13008'], ['brown', '갈색', '12368']], src: '16쪽', nt: '이야기 전 새 낱말', n: ['excited «흥미진진한» → «신이 난», elder «연장자» → «나이가 더 많은», younger «더 젊은» → «더 어린»으로 고쳤습니다'] },
      { t: 'story', k: 'fix', small: 'Story ①', title: 'Family Day', img: 'gen:bts-03-family-day', lines: [['Miss Gray', 'Tomorrow is Family Day!'], ['Hannah', "Yay! I'm so excited!"], ['Miss Gray', 'How many people are in your family?'], ['Hannah', 'There are five people in my family.']], src: '17쪽 Role-play', nt: '역할놀이 ①', n: ['강사 = Miss Gray, 학생 = Hannah → 두 번째는 역할을 바꿉니다'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: 'My family picture', img: 'gen:bts-03-hannah-family', lines: [['Hannah', 'I have a family picture here.'], ['Miss Gray', 'Let me see!'], ['Hannah', 'My father has black hair.'], ['Hannah', 'My mother has brown hair.']], src: '18·19쪽', nt: '역할놀이 ②', n: ['사진 속 사람을 손가락으로 짚으며 읽습니다'] },
      { t: 'story', k: 'fix', small: 'Story ③', title: 'My brothers', img: '12151', lines: [['Hannah', "I have two brothers. I don't have a sister."], ['Hannah', 'My elder brother has black hair.'], ['Hannah', 'My younger brother has brown hair.'], ['Miss Gray', 'What a nice family!']], src: '20·21쪽', nt: '역할놀이 ③', n: ['같은 사진을 한 번 더 — 이번엔 형제만 짚습니다', '마지막 줄 «What a nice family!» 는 새로 넣은 맞장구(칭찬하는 말 익히기)'] },
      { t: 'fill', k: 'fix', title: 'Questions', img: '16625', lines: ['How many people are in Hannah\'s family? — There are ___ people.', 'Does Hannah have a sister? — No, she ___.', 'What color is her younger brother\'s hair? — It is ___.'], src: '23쪽', nt: '이야기 질문', n: ['원본은 답(5, ✗, brown)이 쪽에 미리 적혀 있었습니다 → 빈칸으로'] },
      { t: 'ox', k: 'new', img: 'gen:bts-03-hannah-family', s: 'Hannah has a sister.', nt: '⭕❌ 몸으로 답하기', n: ['정답 ❌ → «No! She has two brothers.» 까지 말하면 성공'] },
      { t: 'guess', k: 'new', img: '16380', open: [0, 5], q: 'Who is in the picture?', chips: ['He is a father.', 'She is a mother.', 'They are brothers.'], nt: 'Guess who 타일', n: ['학생이 번호를 부르면 강사가 그 칸을 엽니다(시안은 1·6번이 열린 모습)', '맞힐 때마다 문장으로: «She is a mother.»'] },
      { t: 'scramble', k: 'keep', title: 'Unscramble!', items: [['ylmafi', '14178'], ['fetrha', 'c7228'], ['retrboh', 'c7263'], ['eormht', 'c7237']], src: '25쪽', nt: '글자 섞기', n: ['원본 네 낱말 그대로(family, father, brother, mother)', '맞힌 낱말로 문장 하나: «He is my father.»'] },
      { t: 'yourturn', k: 'new', img: '16625', title: 'Show me your family!', lines: ['There are ___ people in my family.', 'I have ___.', "I don't have ___."], chips: ['a brother', 'a sister', 'two brothers'], nt: '내 이야기 말하기', n: ['가족사진이 있으면 화면에 보여 주며 말하게 합니다', '따라 → 바꿔 → 내 말의 마지막 단계'] },
      ...close([['I can name my family.', 'father, mother, brother, sister'], ['I can say "He is my brother."', 'They are my parents.'], ['I can say "I have a brother."', "I have two brothers. I don't have a sister."]], { img: 'gen:bts-03-big-family', q: 'Is this a big family or a small family?', ko: '이 가족은 큰 가족일까, 작은 가족일까? (002에서 만나요)' }),
    ] },
  // ───────────────────────── 002
  { code: '002', tab: '큰·작은 가족', unit: FAM, title: 'My Family', orig: 23,
    intro: 'big / small family, child / children 과 «How many people are in your family?», «Do you have any brothers?» 를 배웁니다. 이야기: 윤아와 한나가 서로의 가족을 비교해요.',
    fixed: ['학습 목표가 001과 글자까지 같음 → 이 과의 내용(큰 가족·작은 가족·몇 명)으로', '«Do you have any  brothers?» 두 칸 띄어쓰기', 'Your turn «any brother or sister?» → «any brothers or sisters?»(any 뒤 복수)', '다섯 식구 사진의 얼굴을 이모지로 가린 사진 → 얼굴이 보이는 사진', '쉼표 앞 띄어쓰기'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-two-families', q: 'Is your family big or small?', story: 'Yoona has a small family. Hannah has a big family!', nt: '표지 + Big Question' },
      ...open([['I can say "I have a big family."', '큰 가족·작은 가족을 말할 수 있어요.'], ['I can count my family.', '«There are five people in my family.» 로 가족 수를 말해요.'], ['I can ask "Do you have any brothers?"', '형제자매가 있는지 묻고 답할 수 있어요.']], 'Lesson Goals (001과 같았음)'),
      { t: 'song', k: 'keep', title: 'Family Finger Song', lines: FINGER, img: 'gen:bts-03-fingers', src: 'Warm Up', nt: '손가락 가족 노래', n: ['001과 같은 노래 — 이번엔 학생이 먼저 부르고 강사가 따라 합니다'] },
      { t: 'vocab', k: 'new', hide: true, title: 'Remember? 🔒', words: [['father', '아버지', '12080'], ['mother', '어머니', '12166'], ['brother', '남자 형제', '12151'], ['sister', '여자 형제', '12054'], ['parents', '부모님', '18493'], ['sibling', '형제자매', '17038']], nt: '지난 시간 낱말 떠올리기', n: ['001 낱말을 다른 사진으로 다시 — 사진이 아니라 뜻을 떠올리게 합니다'] },
      { t: 'vocab', k: 'keep', words: [['small', '작은', '12227'], ['big', '큰', '12103'], ['child', '아이(한 명)', '12843'], ['children', '아이들(여럿)', '12274']], title: 'New words', src: 'Vocabulary 6쪽', nt: '새 낱말', n: ['child → children 은 s 가 붙지 않는 복수라는 것을 짚어 줍니다'] },
      { t: 'rule', k: 'fix', title: 'Big or small?', left: { h: 'Small family', ex: ['**2–4** people', 'She **has** a small family.'] }, right: { h: 'Big family', ex: ['**5 or more** people', 'They **have** a big family.'] }, q: 'Five people — big or small?', src: 'Grammar 7·8쪽', nt: '규칙 찾기', n: ['원본의 기준(2~4명 작은 가족, 5명 이상 큰 가족) 그대로'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'I have a big family.', head: ['who', 'has / have', 'a … family'], rows: [['He / She', 'has', 'a small family.'], ['I / You / They', 'have', 'a big family.']], tip: 'he·she 는 has · I·you·they 는 have', src: '8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'keep', img: 'gen:bts-03-couple', label: 'two people', q: 'Is it a big family?', a: "No. They are a couple. They don't have ___.", chips: ['children', 'parents'], src: '9쪽', nt: '작은 가족 ①', n: ['couple = 부부(두 사람) — 원본 설명 그대로'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-03-small-family', label: 'three people', q: 'Is it a small family?', a: 'Yes. I am the only ___.', chips: ['child', 'children'], src: '10쪽', nt: '작은 가족 ②', n: ['the only child = 외동'] },
      { t: 'count', k: 'fix', img: 'gen:bts-03-hannah-family', q: 'How many people are in Hannah\'s family?', a: 'There are ___ people. It is a ___ family.', chips: ['five', 'big', 'small'], src: '11쪽', nt: '세어 보기 ①', n: ['원본은 얼굴을 이모지로 가린 다섯 식구 사진 → 001의 한나네 가족으로 이어서'] },
      { t: 'count', k: 'keep', img: '16380', q: 'How many people are in this family?', a: 'There are ___ people.', src: '12쪽', nt: '세어 보기 ②', n: ['네 사람 → «It is a small family.» 까지 말하기'] },
      { t: 'rule', k: 'fix', title: 'Any brothers?', left: { h: 'Yes', ex: ['Do you have any sisters?', '→ **Yes, I do.**'] }, right: { h: 'No', ex: ['Do you have any brothers?', "→ **No, I don't.**"] }, q: 'Why do we say "sisters", not "sister"?', src: '13·14쪽', nt: '규칙 찾기 — any', n: ['any 뒤에는 여럿(-s)', '원본 «any  brothers» 두 칸 띄어쓰기 정리'] },
      { t: 'qa', k: 'keep', img: '12054', q: 'Do you have any sisters?', a: 'Yes, I ___. I have a sister.', src: '14쪽', nt: '예' },
      { t: 'qa', k: 'keep', img: '12843', q: 'Do you have any brothers?', a: "No, I ___. I am the only child.", src: '13쪽', nt: '아니오' },
      { t: 'story', k: 'new', small: 'Story', title: 'Big or small?', img: 'gen:bts-03-two-families', lines: [['Yoona', 'I have a small family.'], ['Hannah', 'I have a big family!'], ['Mango', 'I am the only mango! 🥭'], ['Yoona', 'Ha ha! Mango has a small family.']], nt: '이어지는 이야기', n: ['001의 한나가 윤아를 만납니다', 'Mango 줄은 웃음 포인트 — 학생이 Mango 역을 맡게 하세요'] },
      { t: 'fill', k: 'fix', title: 'Talk about his family', img: '18493', lines: ['There are ___ people in his family.', 'He has a ___ family.', 'He ___ a brother.'], chips: ['three', 'small', "doesn't have"], src: '16·17쪽', nt: '가족 이야기 빈칸', n: ['원본 세 쪽(몇 명·큰/작은·형제) → 한 사진으로 묶었습니다', '사진 속 주인공이 남자아이라 her → his'] },
      { t: 'count', k: 'new', img: 'gen:bts-03-big-family', q: 'How many people are in this family?', a: 'There are ___ people.', chips: ['four', 'six'], nt: '세어 보기 ③', n: ['001 예고 사진의 답 — 여섯 명 → «It is a big family!»'] },
      { t: 'ox', k: 'new', img: 'gen:bts-03-couple', s: 'They have a big family.', nt: '⭕❌', n: ['정답 ❌ → «No! They are a couple. They have a small family.»'] },
      { t: 'guess', k: 'new', img: '14178', open: [2, 6], q: 'How many children?', chips: ['There are four children.', 'It is a big family.'], nt: 'Guess who — 몇 명?', n: ['타일을 열 때마다 «How many …?» 로 물어야 합니다'] },
      { t: 'yourturn', k: 'fix', img: '16625', title: 'Your turn!', lines: ['How many people are in your family?', 'Do you have any brothers or sisters?', 'I have a ___ family.'], chips: ['big', 'small'], src: '22쪽 Your turn', nt: '내 가족 말하기', n: ['원본 «any brother or sister?» → «any brothers or sisters?»'] },
      ...close([['I can say "I have a big family."', 'I have a small family.'], ['I can count my family.', 'There are four people in my family.'], ['I can ask "Do you have any brothers?"', "No, I don't. I am the only child."]], { img: 'gen:bts-03-blue-eyes', q: 'What color are her eyes?', ko: '이 아기의 눈은 무슨 색일까요? (003에서 만나요)' }),
    ] },
  // ───────────────────────── 003
  { code: '003', tab: '머리·눈 색', unit: FAM, title: 'My Family', orig: 23,
    intro: '눈 색(blue·brown)과 머리 색(black·brown·blond) — «She has blue eyes and blonde hair.» 를 배웁니다. 이야기: 엄마는 검은 머리인데 딸은 금발이에요!',
    fixed: ['❗ «My father has black eyes» → brown eyes (영어 black eye = 멍든 눈)', '학습 목표가 001과 같음 → 머리·눈 색 말하기로', '문법 표 예문 끝 마침표 누락', 'blonde(여자)·blond(남자) 구분 — 지금은 섞어 쓴다는 강사 메모 추가', 'Your turn «What color are your eyes and hair?» — 문장은 맞음, 답 틀을 두 문장으로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-hair-colors', q: 'What color is your hair?', story: 'Black, brown, blond… Look at all the colors!', nt: '표지 + Big Question' },
      ...open([['I can say eye colors.', '눈 색을 말할 수 있어요 — blue, brown.'], ['I can say hair colors.', '머리 색을 말할 수 있어요 — black, brown, blond.'], ['I can say "She has blue eyes."', 'has / have 로 생김새를 말할 수 있어요.']], 'Lesson Goals (001과 같았음)'),
      { t: 'vocab', k: 'fix', hide: true, words: [['blue eyes', '파란 눈', 'gen:bts-03-blue-eyes'], ['brown eyes', '갈색 눈', 'gen:bts-03-brown-eyes'], ['black hair', '검은 머리', 'gen:bts-03-black-hair'], ['brown hair', '갈색 머리', '15564'], ['blond hair', '금발', 'gen:bts-03-blond-boy'], ['curly hair', '곱슬머리', '15315']], src: 'Vocabulary 6쪽', nt: '낱말 — 뜻 가리고 먼저', n: ['색 + eyes / hair 를 한 덩어리로 익힙니다', 'curly 는 008에 다시 나와 미리 한 번 보여 줍니다'] },
      { t: 'vocab', k: 'keep', title: 'Words', words: [['eyes', '눈', '12953'], ['hair', '머리카락', '13008'], ['blue', '파란색', 'gen:bts-03-blue-eyes'], ['brown', '갈색', '12368'], ['black', '검은색', 'gen:bts-03-black-hair'], ['blond', '금발의', 'gen:bts-03-blonde-girl']], src: '6쪽', nt: '낱말 — 뜻 공개' },
      { t: 'rule', k: 'fix', title: 'blonde or blond?', left: { h: 'girls / women', ex: ['She has **blonde** hair.'] }, right: { h: 'boys / men', ex: ['He has **blond** hair.'] }, q: 'What is different? Look at the last letter!', src: 'Grammar 7쪽', nt: '규칙 찾기 — 원본 규칙', n: ['원본 규칙 그대로 가르치되, 강사 메모: 지금 영어는 둘을 섞어 써도 틀리지 않습니다(사람이 정할 것 3번)'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'She has blue eyes.', head: ['who', 'has / have', 'color + eyes / hair'], rows: [['He / She', 'has', 'blue eyes.'], ['He / She', "doesn't have", 'black hair.'], ['I / They', 'have / don\'t have', 'brown eyes.']], tip: '눈·머리 색은 has / have', src: '8쪽', nt: '문장 틀', n: ['원본 표 예문 끝 마침표 누락 → 모두 붙였습니다'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-03-blue-eyes', label: 'baby', q: 'What color are her eyes?', a: 'She has ___ eyes and blonde hair.', chips: ['blue', 'brown'], src: '9쪽', nt: '따라 말하기' },
      { t: 'qa', k: 'keep', img: 'gen:bts-03-blond-boy', q: 'What color is his hair?', a: 'He has ___ hair.', src: '10쪽', nt: '바꿔 말하기' },
      { t: 'story', k: 'keep', small: 'Story', title: 'Like my mom?', img: 'gen:bts-03-mom-daughter', lines: [['Jane', 'This is my mom.'], ['Jane', "I don't have black hair like my mom."], ['Jane', 'I have blonde hair.'], ['Mango', 'Wow! Two different colors!']], src: '12쪽', nt: '엄마와 딸', n: ['원본 문장 그대로(Jane 이 말하는 사람)', 'like my mom = 엄마처럼'] },
      { t: 'fill', k: 'fix', title: 'Look at the family!', img: 'gen:bts-03-eyes-family', lines: ['My father has ___ eyes.', 'My mother has ___ hair.', 'I have ___ hair.'], chips: ['brown', 'blonde', 'black'], src: '13·14쪽', nt: '❗ 가족사진 빈칸', n: ['원본 «My father has black eyes» → **brown** eyes 로 고쳤습니다. 영어로 black eye 는 «멍든 눈» 입니다'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-03-dad-brown', q: 'Does he have black eyes?', a: "No, he doesn't. He has ___ eyes.", chips: ['brown', 'blue'], src: '15쪽', nt: '❗ black eyes 고침', n: ['원본 질문 «Does he have black eyes?» 는 «멍들었니?» 로 들립니다 → 「아니오」 답을 연습하는 함정 문제로 살렸습니다'] },
      { t: 'order', k: 'keep', img: 'gen:bts-03-blonde-girl', words: ['has', 'She', 'hair.', 'blonde'], src: '17쪽 Rearrange', nt: '순서 맞추기 ①' },
      { t: 'order', k: 'keep', img: 'gen:bts-03-dad-brown', words: ['eyes.', 'brown', 'He', 'has'], src: '18쪽 Rearrange', nt: '순서 맞추기 ②' },
      { t: 'order', k: 'keep', img: 'gen:bts-03-black-hair', words: ["doesn't", 'She', 'have', 'blonde', 'hair.'], src: '19쪽 Rearrange', nt: '순서 맞추기 ③', n: ['부정문 — doesn\'t have 가 한 덩어리'] },
      { t: 'ox', k: 'new', img: 'gen:bts-03-blond-boy', s: 'He has black hair.', nt: '⭕❌', n: ['정답 ❌ → «No! He has blond hair.»'] },
      { t: 'memory', k: 'new', items: ['gen:bts-03-blue-eyes', 'gen:bts-03-black-hair', 'gen:bts-03-blond-boy', '15315'], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ①', n: ['5초 보여 주고 다음 쪽으로'] },
      { t: 'memory', k: 'new', hidden: true, items: ['gen:bts-03-blue-eyes', 'gen:bts-03-black-hair', 'gen:bts-03-blond-boy', '15315'], q: 'Who has blond hair?', a: 'The ___ has blond hair.', nt: '기억 게임 ②', n: ['기억나는 대로: «The baby has blue eyes. The girl has black hair…»'] },
      { t: 'guess', k: 'new', img: 'gen:bts-03-hair-colors', open: [1, 4], q: 'Who has brown hair?', chips: ['She has brown hair.', 'He has black hair.', 'She has blonde hair.'], nt: 'Guess who — 머리 색', n: ['열린 칸의 머리 색을 문장으로 말해야 점수'] },
      { t: 'yourturn', k: 'fix', img: '19605', title: 'Look in the mirror!', lines: ['What color are your eyes?', 'I have ___ eyes.', 'I have ___ hair.'], chips: ['brown', 'black', 'blue'], src: '22쪽 Your turn', nt: '거울 보고 말하기', n: ['카메라를 거울처럼 보며 자기 눈·머리 색을 말합니다', '원본 한 질문(eyes and hair)을 답하기 쉽게 두 문장 틀로'] },
      ...close([['I can say eye colors.', 'I have brown eyes.'], ['I can say hair colors.', 'He has blond hair.'], ['I can say "She has blue eyes."', "She has blue eyes. She doesn't have black hair."]], { img: 'gen:bts-03-grandpa-game', q: 'How old is this grandpa?', ko: '게임하는 할아버지는 몇 살일까요? (004에서 만나요)' }),
    ] },
  // ───────────────────────── 004
  { code: '004', tab: '나이', unit: AGE, title: 'How Old Are You?', orig: 20,
    intro: 'grandfather·grandmother·grandparents 와 나이 말하기 «I am 12 years old.», «How old is he?» 를 배웁니다. 이야기: 한나가 미스터 리 선생님께 가족사진 속 할아버지·할머니를 소개해요.',
    fixed: ['❗ «Our parents have the same age» → are the same age (나이는 be 동사)', '«This is our family picture» → my family picture (한 사람이 말함)', '17쪽 이야기 질문 쪽에 답이 미리 적혀 있음 → 빈칸으로', '복습 쪽이 없음 → 과 끝 Your turn 추가', '목표의 문법 용어(Cardinal Number) → 강사 메모로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-grandpa-game', q: 'How old are you?', story: 'Grandpa is 69. And he loves video games!', nt: '표지 + Big Question', n: ['«할아버지도 게임을 해요!» — 웃음으로 시작'] },
      ...open([['I can say "I am 12 years old."', '내 나이를 말할 수 있어요.'], ['I can ask "How old is he?"', '다른 사람의 나이를 물을 수 있어요.'], ['I can name my grandparents.', 'grandfather, grandmother 를 말할 수 있어요.']]),
      { t: 'vocab', k: 'fix', hide: true, words: [['grandmother', '할머니', '12048'], ['grandfather', '할아버지', '16020'], ['grandparents', '조부모님', '18429']], src: 'Vocabulary 6쪽', nt: '낱말 — 뜻 가리고 먼저', n: ['grand + mother / father / parents — 앞말만 붙이면 된다는 것을 보여 줍니다'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'I am 12 years old.', head: ['who', 'am / is / are', 'age'], rows: [['I', 'am', '16 years old.'], ['He', 'is', '20 years old.'], ['They', 'are', '35 years old.']], tip: '나이는 has 가 아니라 am / is / are 로 말해요', src: 'Grammar 7·8쪽', nt: '문장 틀' },
      { t: 'rule', k: 'new', title: 'has or is?', left: { h: 'hair · eyes', ex: ['He **has** black hair.'] }, right: { h: 'age', ex: ['He **is** 20 years old.'] }, q: 'Can we say "He has 20 years"?', nt: '규칙 찾기 — 한국어와 다른 점', n: ['한국 학생이 자주 하는 실수 «I have 12 years» 를 미리 막습니다', '답: 안 돼요! 나이는 is'] },
      { t: 'qa', k: 'keep', img: '16124', q: 'How old is she?', a: 'She is ___ years old.', chips: ['sixty-eight', 'eight'], src: '9쪽', nt: '나이 묻기 ①' },
      { t: 'qa', k: 'keep', img: '12491', q: 'How old is he?', a: 'He is ___ years old.', chips: ['seventy', 'seven'], src: '10쪽', nt: '나이 묻기 ②' },
      { t: 'qa', k: 'keep', img: '18429', q: 'Who are they?', a: 'They are my ___.', src: '11쪽', nt: 'grandparents' },
      { t: 'vocab', k: 'keep', title: 'New words 📖', words: [['picture', '사진', '16625'], ['nice', '멋진, 좋은', '18557'], ['age', '나이', '18732']], src: '12쪽', nt: '이야기 전 새 낱말' },
      { t: 'story', k: 'fix', small: 'Story ①', title: 'My family picture', img: '16625', lines: [['Hannah', 'Mister Lee, this is my family picture.'], ['Mister Lee', 'What a nice picture! Who is he?'], ['Hannah', 'He is my grandfather. He is 69 years old.'], ['Hannah', 'My grandmother is 68 years old.']], src: '13쪽', nt: '역할놀이 ①', n: ['원본 «This is our family picture» → my (한나 혼자 말함)'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: 'The same age', img: 'gen:bts-03-tree', lines: [['Mister Lee', 'How old are your parents?'], ['Hannah', 'They are 41 years old.'], ['Hannah', 'My parents are the same age!'], ['Mister Lee', 'Wow!']], src: '14쪽', nt: '❗ 역할놀이 ②', n: ['원본 «have the same age» → **are** the same age (나이는 be 동사)'] },
      { t: 'story', k: 'keep', small: 'Story ③', title: 'My brothers', img: 'gen:bts-03-hannah-family', lines: [['Hannah', 'My elder brother is 14 years old.'], ['Hannah', 'My younger brother is 7 years old.'], ['Mister Lee', 'How old are you, Hannah?'], ['Hannah', 'I am 12 years old.']], src: '15쪽', nt: '역할놀이 ③', n: ['001 한나네 가족 사진으로 이어집니다'] },
      { t: 'fill', k: 'fix', title: 'Questions', img: '16020', lines: ['How old is Hannah\'s grandfather? — He is ___.', 'How old are her parents? — They are ___.', 'How old is Hannah? — She is ___.'], src: '17쪽', nt: '이야기 질문', n: ['원본은 답이 미리 적혀 있었습니다 → 빈칸으로'] },
      { t: 'match', k: 'keep', title: 'Match it!', left: ['12048', '16020', '18429', 'c7172'], right: ['grandparents', 'eleven years old', 'grandmother', 'grandfather'], src: '18쪽', nt: '짝 맞추기' },
      { t: 'ox', k: 'new', img: 'gen:bts-03-tree', s: 'Her grandmother is 69 years old.', nt: '⭕❌', n: ['정답 ❌ → «No! She is 68. Her grandfather is 69.» — 이야기를 기억해야 맞힙니다'] },
      { t: 'guess', k: 'new', img: '18429', open: [0, 8], q: 'Who is in the picture?', chips: ['They are grandparents.', 'He is a grandfather.', 'She is a grandmother.'], nt: 'Guess who', n: ['열 때마다 «Who is he?» «How old is she?» 로 묻습니다'] },
      { t: 'yourturn', k: 'new', img: 'c7192', title: 'Your turn!', lines: ['I am ___ years old.', 'My grandmother is ___ years old.', 'My grandfather is ___ years old.'], nt: '내 가족 나이 말하기', n: ['원본에 없던 복습 쪽 — 학생 가족의 실제 나이로 말합니다(모르면 «I don\'t know!» 도 정답)'] },
      ...close([['I can say "I am 12 years old."', 'I am 10 years old.'], ['I can ask "How old is he?"', 'How old is he? — He is 69.'], ['I can name my grandparents.', 'They are my grandparents.']], { img: 'gen:bts-03-twins', q: 'Who is older? 🤔', ko: '쌍둥이 중 누가 더 나이가 많을까요? (005에서 만나요)' }),
    ] },
  // ───────────────────────── 005
  { code: '005', tab: '나이 많은·어린', unit: AGE, title: 'How Old Are You?', orig: 22,
    intro: 'old / young, twins, baby / babies 와 «She is 9. She is young.» 을 배웁니다. 이야기: 한나 할머니가 «나는 마음만은 젊어!» 하고 춤을 춰요.',
    fixed: ['«1 year old» 와 «2 years old» — 단수·복수 규칙을 쪽으로 따로', '호박 옷 아기 쪽 «1 year old» 앞 문장 빠짐 → «The baby is 1 year old.»', '«I am 63. I am old.» — 원본 그대로, 강사 메모(사람이 정할 것 4번)', 'rearrange 쪽 칸 띄어쓰기'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-twins', q: 'Old or young?', story: 'Twins, babies and a dancing grandma!', nt: '표지 + Big Question' },
      ...open([['I can say old and young.', 'old(나이 많은)·young(어린)을 말할 수 있어요.'], ['I can say "one year old".', '1살은 year, 2살부터는 years 로 말해요.'], ['I can talk about twins and babies.', 'twins, baby, babies 를 말할 수 있어요.']]),
      { t: 'vocab', k: 'fix', hide: true, words: [['old', '나이가 많은', '13003'], ['young', '어린', '12026'], ['twins', '쌍둥이', 'gen:bts-03-twins'], ['baby', '아기', '16127'], ['babies', '아기들', 'gen:bts-03-babies']], src: 'Vocabulary 6쪽', nt: '낱말 — 뜻 가리고 먼저' },
      { t: 'rule', k: 'new', title: 'year or years?', left: { h: '1', ex: ['The baby is **1 year** old.'] }, right: { h: '2, 3, 4 …', ex: ['She is **2 years** old.', 'He is **9 years** old.'] }, q: 'When do we add "s"?', nt: '규칙 찾기', n: ['baby → babies 도 같은 규칙(하나 / 여럿)이라는 것을 함께 짚습니다'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'She is 9. She is young.', head: ['who', 'is', 'age + old / young'], rows: [['She', 'is', '9 years old. She is young.'], ['He', 'is', '68 years old. He is old.'], ['They', 'are', '8 years old. They are twins.']], tip: 'old = 나이 많은 · young = 어린', src: 'Grammar 7·8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'fix', img: '18559', q: 'Is she old or young?', a: 'She is 11 years old. She is ___.', chips: ['old', 'young'], src: '9쪽', nt: 'young', n: ['원본은 9살 소녀 사진 → 숫자 초가 보이는 11살 사진(나이를 사진에서 읽을 수 있게)'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-03-grandpa-game', label: '68', q: 'Is he old or young?', a: 'He is 68. He is ___.', src: '10쪽', nt: 'old', n: ['004 표지의 게임하는 할아버지가 다시 나옵니다'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-03-twins', label: '8', q: 'How old are they?', a: 'They are ___ years old. They are twins.', src: '10쪽', nt: 'twins', n: ['원본 문장 그대로 «They are __ years old. They are twins.»'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-03-pumpkin-baby', label: '1', q: 'How old is the baby?', a: 'The baby is 1 ___ old.', chips: ['year', 'years'], src: '13쪽', nt: '❗ 1 year old', n: ['원본은 «1 year old» 만 있고 주어가 빠짐 → «The baby is 1 year old.»', 'year / years 함정 칩'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-03-babies', label: '1 · 2', q: 'How old are the babies?', a: 'They are 1 and 2 ___ old.', src: '14쪽', nt: 'babies' },
      { t: 'story', k: 'new', small: 'Story', title: 'Grandma is young!', img: '19702', lines: [['Hannah', 'Grandma, you are 68. You are old!'], ['Grandma', 'No, no! I am young! Let\'s dance!'], ['Mango', 'Grandma is young at heart! 💃'], ['Hannah', 'Ha ha! Go, Grandma!']], nt: '이어지는 이야기', n: ['young at heart = 마음이 젊은 — 나이 많은 분께 «old» 라고만 하면 서운할 수 있다는 것을 웃으며 알려 줍니다'] },
      { t: 'fill', k: 'fix', title: 'Old or young?', lines: ['I am 63 years old. I am ___.', 'My grandfather is 77. He is ___.', 'My sister is 7. She is ___.'], chips: ['old', 'young'], src: '14·15·16쪽', nt: '빈칸', n: ['원본 세 쪽 → 한 쪽', '«I am 63. I am old.» 는 원본 문장 — 사람이 정할 것 4번'] },
      { t: 'order', k: 'keep', img: 'c7237', words: ['years old.', 'is', 'She', '35'], src: '19쪽 Rearrange', nt: '순서 맞추기 ①' },
      { t: 'order', k: 'keep', img: '16127', words: ['is', 'The', 'young.', 'baby'], src: '20쪽 Rearrange', nt: '순서 맞추기 ②' },
      { t: 'order', k: 'keep', img: '12048', words: ['years old.', 'is', 'grandmother', '83', 'My'], src: '21쪽 Rearrange', nt: '순서 맞추기 ③' },
      { t: 'ox', k: 'new', img: 'gen:bts-03-pumpkin-baby', s: 'The baby is old.', nt: '⭕❌', n: ['정답 ❌ → «No! The baby is young. The baby is 1 year old.»'] },
      { t: 'guess', k: 'new', img: '12274', open: [3, 5], q: 'Are they old or young?', chips: ['They are young.', 'They are children.', 'They are old.'], nt: 'Guess who', n: ['열 때마다 «Old or young?» — 아이들이 뛰노는 사진이라 답은 young'] },
      { t: 'yourturn', k: 'new', img: 'c7172', title: 'Your turn!', lines: ['I am ___ years old.', 'I am ___.', 'My ___ is old.'], chips: ['young', 'old', 'grandfather'], nt: '내 말로', n: ['손가락으로 나이를 보여 주며 말하기'] },
      ...close([['I can say old and young.', 'The baby is young.'], ['I can say "one year old".', 'The baby is 1 year old.'], ['I can talk about twins and babies.', 'They are twins.']], { img: 'gen:bts-03-family-album', q: 'Who is in the family album?', ko: '가족 앨범에는 누가 있을까요? (006에서 만나요)' }),
    ] },
  // ───────────────────────── 006
  { code: '006', tab: '나이·머리 복습', unit: AGE, title: 'How Old Are You?', orig: 16,
    intro: '나이와 머리 색을 한 번에 — «My grandmother is 70. She has white hair.» 가족 앨범을 넘기며 말합니다.',
    fixed: ['❗ «What color are their hair?» → What color **is** their hair? (hair 는 셀 수 없음)', '노래가 목표보다 앞에 있음 → 다른 과와 같은 순서로', '마지막 «sister 17» 쪽이 빈칸만 있음 → Your turn 으로', '«doesn\'t have much hair» 앞뒤 문장 정리'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-family-album', q: 'How old is everyone?', story: 'Hannah opens the family album. Look!', nt: '표지 + Big Question' },
      ...open([['I can say age and hair together.', '나이와 머리 색을 함께 말할 수 있어요.'], ['I can ask "What color is his hair?"', '머리 색을 물을 수 있어요.'], ['I can talk about my family album.', '가족 앨범을 보며 말할 수 있어요.']]),
      { t: 'vocab', k: 'new', hide: true, title: 'Remember? 🔒', words: [['old', '나이가 많은', '18451'], ['young', '어린', '12843'], ['grandmother', '할머니', '13003'], ['grandfather', '할아버지', '16020'], ['grandparents', '조부모님', '19411'], ['baby', '아기', '19011']], nt: '004·005 낱말 떠올리기', n: ['다른 사진으로 다시 — 간격 복습'] },
      { t: 'rule', k: 'new', title: 'is or has?', left: { h: 'is', ex: ['She **is** 70 years old.', 'She **is** old.'] }, right: { h: 'has', ex: ['She **has** white hair.', 'She **has** blue eyes.'] }, q: 'Age → is or has? Hair → is or has?', nt: '규칙 찾기', n: ['004 규칙의 복습 — 나이 is, 생김새 has'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'What color is her hair?', head: ['question', 'answer'], rows: [['How old is she?', 'She is 70 years old.'], ['What color is her hair?', 'She has white hair.'], ['What color is their hair?', 'They have white hair.']], tip: 'hair 는 하나로 세요 → What color **is** their hair?', src: '6쪽', nt: '❗ 문장 틀', n: ['원본 «What color are their hair?» → is (hair 는 셀 수 없는 낱말)'] },
      { t: 'fill', k: 'keep', title: 'is or has?', img: 'gen:bts-03-grandparents-bike', lines: ['My grandmother ___ 70 years old. She ___ white hair.', 'My grandfather ___ 71 years old. He ___ white hair.'], chips: ['is', 'has'], src: '7·8쪽', nt: '할머니·할아버지', n: ['원본 빈칸은 숫자가 아니라 is / has 입니다(원본 그대로)', '자전거 타는 흰머리 할머니·할아버지 — 원본 두 쪽을 한 사진으로'] },
      { t: 'fill', k: 'keep', title: 'My parents', img: 'gen:bts-03-parents', lines: ['My father ___ 38 years old. He ___ black hair.', 'My mother ___ 37 years old. She ___ brown hair.'], chips: ['is', 'has'], src: '9·10쪽', nt: '아빠·엄마' },
      { t: 'qa', k: 'fix', img: '16127', label: '1', q: 'How old is my baby brother?', a: "He is ___ year old. He doesn't have much hair.", src: '11쪽', nt: '아기 동생', n: ['doesn\'t have much hair = 머리카락이 별로 없다 — 아기 머리를 가리키며 웃고 넘어가는 쪽'] },
      { t: 'story', k: 'new', small: 'Story', title: 'Grandpa\'s hair', img: '18451', lines: [['Hannah', 'Grandpa, what color is your hair?'], ['Grandpa', 'It is white now.'], ['Hannah', 'Was it black?'], ['Grandpa', 'Yes! Just like your hair! 😄']], nt: '이어지는 이야기', n: ['Was it …? 는 새 문법이라 따라 읽기만(설명하지 않음)', '한나 = 검은 머리 → 004 이야기와 이어집니다'] },
      { t: 'ox', k: 'new', img: 'gen:bts-03-parents', s: 'Her father has blonde hair.', nt: '⭕❌', n: ['정답 ❌ → «No! He has black hair.»', 'blonde(여자)·blond(남자) 함정까지 짚을 수 있습니다'] },
      { t: 'guess', k: 'new', img: 'gen:bts-03-grandparents-bike', open: [2, 7], q: 'How old are they?', chips: ['They are old.', 'They have white hair.', 'They are young.'], nt: 'Guess who', n: ['자전거 타는 할머니·할아버지 — «old 인데 신나요!»'] },
      { t: 'yourturn', k: 'fix', img: 'c7229', label: '17', title: 'My sister', lines: ['My sister is ___ years old.', 'She has ___ hair.', 'She has ___ eyes.'], chips: ['17', 'brown', 'black'], src: '13쪽', nt: '빈칸 → 말하기', n: ['원본은 빈칸만 있던 쪽 → 사진을 보고 세 문장'] },
      { t: 'yourturn', k: 'new', img: '16625', title: 'Your family album', lines: ['My ___ is ___ years old.', 'He / She has ___ hair.'], chips: ['mother', 'father', 'grandmother'], nt: '내 가족 앨범', n: ['학생이 가족 한 명을 골라 나이 + 머리 색으로 소개'] },
      ...close([['I can say age and hair together.', 'She is 70. She has white hair.'], ['I can ask "What color is his hair?"', 'What color is his hair?'], ['I can talk about my family album.', 'My father is 38. He has black hair.']], { img: '15799', q: 'Who is he? Is he a father?', ko: '아이를 목말 태운 이 사람은 누구일까요? (007에서 만나요)' }),
    ] },
  // ───────────────────────── 007
  { code: '007', tab: '친척', unit: WHO, title: 'Who Is in Your Family?', orig: 24,
    intro: 'aunt·uncle·cousin 과 «He is my cousin.», «They are my cousins.», 누구의 무엇(’s)을 배웁니다. 이야기: 한나가 삼촌 댁에 사촌 아기의 첫 돌잔치에 가요!',
    fixed: ['aunt «이모»·uncle «삼촌» → «이모·고모 / 삼촌·외삼촌»(사람이 정할 것 2번)', '«aunt Anna·uncle Ben» → Aunt Anna·Uncle Ben (이름 앞 호칭은 대문자)', '«For me, she looks like her mom» → I think she looks like her mom.', 'Guessing game «aunt\'s baby» 문장 끝 마침표 누락', '목표 쪽 인물 «Mister Bill» → 이야기와 같은 Mister Lee'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-first-birthday', q: 'Who is in your big family?', story: 'Hannah\'s baby cousin is one year old today! 🎂', nt: '표지 + Big Question' },
      ...open([['I can name aunts, uncles and cousins.', 'aunt, uncle, cousin 을 말할 수 있어요.'], ['I can say "She is my cousin."', '«He/She is my cousin.», «They are my cousins.»'], ["I can say \"my mother's sister\".", '’s 로 «엄마의 여자 형제» 처럼 말할 수 있어요.']], 'Lesson Goals (Mister Bill)'),
      { t: 'song', k: 'fix', title: 'Tongue Twister', lines: TWISTER, img: 'gen:bts-03-hand-in-hand', src: 'Warm Up', nt: '잰말놀이', n: twisterNote },
      { t: 'vocab', k: 'fix', hide: true, words: [['aunt', '이모·고모', '17029'], ['uncle', '삼촌·외삼촌', '15799'], ['cousin', '사촌', '18005'], ['baby', '아기', '16127'], ['babies', '아기들', 'gen:bts-03-babies']], src: 'Vocabulary 6쪽', nt: '낱말 — 뜻 가리고 먼저', n: ['영어 aunt 는 이모·고모·숙모를 모두 가리킵니다 → 뜻을 넓혀 적었습니다'] },
      { t: 'rule', k: 'new', title: "Whose sister?", left: { h: 'aunt', ex: ["my mother's **sister**", "my father's **sister**"] }, right: { h: 'uncle', ex: ["my father's **brother**", "my mother's **brother**"] }, q: "What is my aunt's baby?", nt: "규칙 찾기 — 's", n: ["'s = ~의 · 답: my cousin!", '원본 설명(aunt = mother\'s sister, uncle = father\'s brother)을 넓혔습니다'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'She is my cousin.', head: ['who', 'is / are', 'my + family'], rows: [['He', 'is', 'my uncle. / my cousin.'], ['She', 'is', 'my aunt. / my cousin.'], ['They', 'are', 'my cousins.']], tip: '한 사람 cousin · 여럿 cousins', src: 'Grammar 7·8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'keep', img: '19296', q: 'Who is she?', a: "She is my ___. She is my father's sister.", chips: ['aunt', 'uncle'], src: '9쪽', nt: 'aunt' },
      { t: 'qa', k: 'keep', img: 'c7118', q: 'Who is he?', a: "He is my ___. He is my father's brother.", src: '10쪽', nt: 'uncle' },
      { t: 'qa', k: 'keep', img: '14178', q: 'Who are they?', a: 'They are my ___.', chips: ['cousin', 'cousins'], src: '11쪽', nt: 'cousins' },
      { t: 'vocab', k: 'keep', title: 'New words 📖', words: [['birthday', '생일', '12234'], ['cute', '귀여운', '12885'], ['only child', '외동', '12843']], src: '12쪽', nt: '이야기 전 새 낱말' },
      { t: 'story', k: 'fix', small: 'Story ①', title: "My cousin's birthday", img: 'gen:bts-03-first-birthday', lines: [['Hannah', "I'm going to my uncle's house."], ['Mister Lee', 'Why?'], ['Hannah', "It's my baby cousin's first birthday!"], ['Mister Lee', 'She is so cute!']], src: '13·14쪽', nt: '역할놀이 ①', n: ['first birthday = 첫 돌'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: 'Aunt Anna', img: 'gen:bts-03-aunt-anna', lines: [['Hannah', 'Her mother is Aunt Anna.'], ['Hannah', 'She has brown hair and gray eyes.'], ['Mister Lee', 'I think the baby looks like her mom.'], ['Hannah', 'Yes! She has gray eyes, too.']], src: '15쪽', nt: '역할놀이 ②', n: ['«aunt Anna» → Aunt Anna (대문자)', '«For me, she looks like…» → I think … looks like …'] },
      { t: 'story', k: 'fix', small: 'Story ③', title: 'Uncle Ben', img: 'gen:bts-03-uncle-ben', lines: [['Hannah', 'Her father is Uncle Ben.'], ['Hannah', "He is my father's brother."], ['Hannah', 'He has black hair and brown eyes.'], ['Hannah', 'My cousin is the only child.']], src: '16·17쪽', nt: '역할놀이 ③' },
      { t: 'fill', k: 'fix', title: 'Questions', img: 'gen:bts-03-uncle-ben', lines: ["Whose birthday is it? — It's her baby ___'s birthday.", "Who is Uncle Ben? — He is her father's ___.", 'What color are Aunt Anna\'s eyes? — They are ___.'], src: '18쪽', nt: '이야기 질문' },
      { t: 'fill', k: 'fix', title: 'Guessing game 🕵️', lines: ["I am your mother's sister's baby. — I am your ___.", "I am your father's brother. — I am your ___.", "I am your mother's sister. — I am your ___."], chips: ['aunt', 'uncle', 'cousin'], src: '20·21쪽 Guessing game', nt: '수수께끼', n: ['원본 «aunt\'s baby» 마침표 누락 → 정리', '강사가 수수께끼를 읽고 학생이 답합니다 → 다음엔 학생이 문제를 냅니다'] },
      { t: 'ox', k: 'new', img: '14178', s: 'They are my cousin.', nt: '⭕❌ 문법 함정', n: ['정답 ❌ → «They are my cousins!» — 여러 명이면 -s'] },
      { t: 'guess', k: 'new', img: '15799', open: [1, 6], q: 'Who is he?', chips: ['He is my uncle.', 'He is my cousin.', "He is my father's brother."], nt: 'Guess who', n: ['표지 예고의 답 — 목말 태운 사람은 아빠가 아니라 삼촌!'] },
      { t: 'yourturn', k: 'new', img: '17036', title: 'Your turn!', lines: ['Do you have any cousins?', 'I have ___ cousins.', 'My aunt / uncle has ___ hair.'], nt: '내 친척 말하기' },
      ...close([['I can name aunts, uncles and cousins.', 'He is my uncle.'], ['I can say "She is my cousin."', 'They are my cousins.'], ["I can say \"my mother's sister\".", "My aunt is my mother's sister."]], { img: 'gen:bts-03-cousins-slide', q: 'How old are the cousins?', ko: '미끄럼 타는 두 사촌은 몇 살일까요? (008에서 만나요)' }),
    ] },
  // ───────────────────────── 008
  { code: '008', tab: '친척 소개', unit: WHO, title: 'Who Is in Your Family?', orig: 15,
    intro: '친척의 나이·머리·눈 색을 한꺼번에 — «My aunt is 36. She has black hair and blue eyes.»',
    fixed: ['머리글 «BTS 8 / BIS 8» → BTS 3', '9·10쪽 «They have ___ hair» 인데 두 사촌 머리 색이 다름 → 같은 색 사진으로', '이모 사진에 눈이 안 보임 → 눈이 보이는 사진으로', '«What color are their hair and eyes?» → What color is their hair?(두 질문으로)'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-cousins-slide', q: 'Tell me about your cousins!', story: 'Hannah has lots of cousins. Let\'s meet them!', nt: '표지 + Big Question' },
      ...open([['I can talk about my aunt and uncle.', '이모·삼촌을 나이와 생김새로 소개할 수 있어요.'], ['I can talk about my cousins.', '사촌의 나이·머리 색을 말할 수 있어요.'], ['I can use and.', '«black hair **and** blue eyes» 로 이어 말해요.']]),
      { t: 'song', k: 'keep', title: 'Tongue Twister', lines: TWISTER, img: 'gen:bts-03-hand-in-hand', src: 'Warm Up', nt: '잰말놀이', n: twisterNote },
      { t: 'vocab', k: 'new', hide: true, title: 'Remember? 🔒', words: [['aunt', '이모·고모', '19296'], ['uncle', '삼촌', 'c7118'], ['cousin', '사촌', '18005'], ['cousins', '사촌들', '14178'], ['curly hair', '곱슬머리', '15315'], ['baby', '아기', '16127']], nt: '007 낱말 떠올리기' },
      { t: 'table', k: 'new', small: 'Pattern', title: 'She has black hair and blue eyes.', head: ['who', 'is + age', 'has + hair and eyes'], rows: [['My aunt', 'is 36.', 'She has black hair and blue eyes.'], ['My uncle', 'is 32.', 'He has brown curly hair.'], ['My cousins', 'are 9.', 'They have brown hair.']], tip: 'and 로 두 가지를 한 번에!', nt: '문장 틀' },
      { t: 'qa', k: 'fix', img: '18732', q: 'How old are my cousins?', a: 'They are ___ years old. They have brown hair.', chips: ['nine', 'ten'], src: '9·10쪽', nt: '❗ 사촌 둘', n: ['원본은 두 사촌 머리 색이 달라 «They have ___ hair» 가 성립하지 않았습니다 → 같은 나이·같은 머리 사진으로'] },
      { t: 'fill', k: 'fix', title: 'My aunt', img: 'gen:bts-03-aunt-36', lines: ['My aunt is ___ years old.', 'She has ___ hair and ___ eyes.'], chips: ['36', 'black', 'blue'], src: '11쪽', nt: '❗ 이모 소개', n: ['원본 사진은 눈이 보이지 않았습니다 → 눈이 보이는 사진으로'] },
      { t: 'fill', k: 'keep', title: 'My uncle', img: 'gen:bts-03-uncle-curly', lines: ['My uncle is ___ years old.', 'He has brown ___ hair.'], chips: ['32', 'curly'], src: '12쪽', nt: '삼촌 소개' },
      { t: 'yourturn', k: 'keep', img: 'gen:bts-03-lollipop', label: '4', title: 'My little cousin', lines: ['My cousin is ___ years old.', 'She has a big ___! 🍭'], chips: ['4', 'lollipop'], src: '13쪽', nt: '사촌 동생', n: ['원본의 막대사탕 사진 그대로 — lollipop 은 그림으로만'] },
      { t: 'story', k: 'new', small: 'Story', title: 'Too many cousins!', img: '14178', lines: [['Mango', 'Hannah, how many cousins do you have?'], ['Hannah', 'I have lots of cousins!'], ['Mango', 'Wow! Who is the youngest?'], ['Hannah', 'My baby cousin. She is 1 year old.']], nt: '이어지는 이야기', n: ['youngest = 가장 어린 — 따라 읽기만', '007 첫 돌 사촌이 다시 나옵니다'] },
      { t: 'ox', k: 'new', img: '18732', s: 'My cousins are 10 years old.', nt: '⭕❌', n: ['정답 ❌ → «No! They are 9 years old.» (케이크 초 9)'] },
      { t: 'match', k: 'new', title: 'Match it!', left: ['19296', '15799', '14178', '16127'], right: ['cousins', 'baby', 'aunt', 'uncle'], nt: '짝 맞추기' },
      { t: 'guess', k: 'new', img: 'gen:bts-03-uncle-curly', open: [0, 4], q: 'Who is he?', chips: ['He is my uncle.', 'He has curly hair.', 'He is 32.'], nt: 'Guess who', n: ['곱슬머리가 보이면 바로 «He has curly hair!»'] },
      { t: 'yourturn', k: 'fix', img: '17036', title: 'Talk about your family', lines: ['My ___ is ___ years old.', 'What color is his / her hair?', 'He / She has ___ hair and ___ eyes.'], src: '14쪽', nt: '내 친척 소개', n: ['원본 «What color are their hair and eyes?» → 두 질문으로 나눴습니다'] },
      ...close([['I can talk about my aunt and uncle.', 'My uncle is 32.'], ['I can talk about my cousins.', 'My cousins are 9 years old.'], ['I can use and.', 'She has black hair and blue eyes.']], { img: 'gen:bts-03-family-reunion', q: 'Can you find everyone?', ko: '가족 모임 사진에서 모두를 찾을 수 있을까요? (009에서 만나요)' }),
    ] },
  // ───────────────────────── 009
  { code: '009', tab: '가족 모임', unit: WHO, title: 'Who Is in Your Family?', orig: 17,
    intro: '가족 모임에서 친척을 하나씩 소개합니다. Unit 3 마무리 — 나이·머리 색·관계를 모두 섞어 말해요.',
    fixed: ['머리글 «Unit 1 008» → Unit 3 009', '삼촌 «black hair» 사진이 짙은 갈색으로 보임 → 검은 머리가 분명한 사진으로(사람이 정할 것)', 'rearrange «/My» 칸 띄어쓰기', '마지막 «cousin 17» 쪽이 빈칸만 있음 → Your turn'],
    slides: [
      { t: 'cover', k: 'new', img: '12284', q: 'Who is at the family party?', story: 'Everyone is here! Say "cheese"! 📸', nt: '표지 + Big Question' },
      ...open([['I can introduce my relatives.', '친척을 관계·나이·생김새로 소개할 수 있어요.'], ['I can ask "Who is she?"', '«Who is she? How old is she?» 로 물을 수 있어요.'], ['I can talk about my whole family.', '가족 전체를 이어서 말할 수 있어요.']]),
      { t: 'song', k: 'keep', title: 'Tongue Twister', lines: TWISTER, img: 'gen:bts-03-hand-in-hand', src: 'Warm Up', nt: '잰말놀이', n: twisterNote },
      { t: 'vocab', k: 'new', hide: true, title: 'Remember? 🔒', words: [['aunt', '이모·고모', '17029'], ['uncle', '삼촌', '15799'], ['cousin', '사촌', '18005'], ['grandparents', '조부모님', '18429'], ['twins', '쌍둥이', 'gen:bts-03-twins'], ['parents', '부모님', 'c7451']], nt: '권 전체 낱말 떠올리기' },
      { t: 'rule', k: 'new', title: 'Who? How old? What color?', left: { h: 'Question', ex: ['Who is she?', 'How old is she?', 'What color is her hair?'] }, right: { h: 'Answer', ex: ['She is my **aunt**.', 'She **is** 33.', 'She **has** brown hair.'] }, q: 'Which answers use "is"? Which use "has"?', nt: '규칙 찾기 — 세 질문', n: ['Unit 3 전체 질문을 한 쪽에 모았습니다'] },
      { t: 'fill', k: 'keep', title: 'My little cousin', img: 'gen:bts-03-cousin-3', lines: ['This is my cousin. She ___ 3 years old.', 'She ___ blonde hair.'], chips: ['is', 'are', 'has', 'have'], src: '7쪽', nt: '사촌 ①' },
      { t: 'fill', k: 'keep', title: 'My cousins', img: 'gen:bts-03-cousins-slide', lines: ['They are my cousins. They ___ 12 and 11 years old.', 'They ___ brown hair.'], chips: ['is', 'are', 'has', 'have'], src: '8쪽', nt: '사촌 ②', n: ['007 예고의 미끄럼 사진 — 답이 여기서 나옵니다'] },
      { t: 'fill', k: 'fix', title: 'Uncle Ben', img: 'gen:bts-03-uncle-34', lines: ['This is my uncle. He ___ 34 years old.', 'He ___ black hair.'], chips: ['is', 'are', 'has', 'have'], src: '9쪽', nt: '❗ 삼촌', n: ['원본 사진은 머리가 짙은 갈색으로 보여 «black hair» 와 맞지 않았습니다'] },
      { t: 'fill', k: 'keep', title: 'Aunt Anna', img: 'gen:bts-03-aunt-anna', lines: ['This is my aunt. She ___ 33 years old.', 'She ___ brown hair.'], chips: ['is', 'are', 'has', 'have'], src: '10쪽', nt: '이모' },
      { t: 'order', k: 'fix', img: 'gen:bts-03-aunt-blonde', words: ['blonde hair.', 'My aunt', 'has'], src: '12쪽 Rearrange', nt: '순서 맞추기 ①' },
      { t: 'order', k: 'fix', img: '12290', words: ['cousin', 'years old.', 'My', 'is', '7'], src: '13쪽 Rearrange', nt: '순서 맞추기 ②', n: ['원본 «/My» 띄어쓰기 정리'] },
      { t: 'order', k: 'keep', img: 'gen:bts-03-uncle-curly', words: ['uncle', 'has', 'brown hair.', 'My'], src: '14쪽 Rearrange', nt: '순서 맞추기 ③' },
      { t: 'story', k: 'new', small: 'Story', title: 'Say cheese!', img: 'gen:bts-03-family-reunion', lines: [['Grandpa', 'Is everyone here?'], ['Hannah', 'Yes! Aunt Anna, Uncle Ben and the baby!'], ['Mango', "Wait! Where's Mango? 🥭"], ['Hannah', "You're here, too! Say cheese!"]], nt: '이어지는 이야기 — 권 마무리', n: ['001 가족의 날부터 이어 온 이야기의 끝 — 모두 한 사진에'] },
      { t: 'ox', k: 'new', img: 'gen:bts-03-cousin-3', s: 'My cousin is old.', nt: '⭕❌', n: ['정답 ❌ → «No! She is young. She is 3 years old.»'] },
      { t: 'guess', k: 'new', img: 'gen:bts-03-family-reunion', open: [0, 3, 8], q: 'Who is it?', chips: ['She is my aunt.', 'He is my uncle.', 'They are my cousins.'], nt: 'Guess who — 가족 모임', n: ['열린 칸마다 관계 + 나이 + 머리 색까지 말하면 3점'] },
      { t: 'yourturn', k: 'fix', img: '18005', label: '17', title: 'My big cousin', lines: ['My cousin is ___ years old.', 'She has ___ hair.'], src: '16쪽', nt: '빈칸 → 말하기', n: ['원본은 빈칸만 있던 쪽'] },
      { t: 'yourturn', k: 'new', img: 'gen:bts-03-tree', title: 'My family tree 🌳', lines: ['This is my ___.', 'He / She is ___ years old.', 'He / She has ___ hair.'], nt: '내 가계도', n: ['학생이 가족 한 명씩 가리키며 세 문장 — Unit 1~3 전부를 씁니다'] },
      ...close([['I can introduce my relatives.', 'She is my aunt. She is 33.'], ['I can ask "Who is she?"', 'Who is she? How old is she?'], ['I can talk about my whole family.', 'My uncle has black hair.']], { img: 'gen:bts-03-family-reunion', q: 'Are you ready for the review?', ko: '가족 이야기 총정리! 복습에서 만나요' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 3 Review', orig: 22,
    intro: 'BTS 3 전체 복습. 게임판처럼 «스테이지» 를 깨며 넘어갑니다.',
    fixed: ['❗ «black eyes» 반복 → brown eyes', 'Unit 1·2 문제가 대부분이고 Unit 3 은 두 쪽뿐 → 세 단원을 고르게', '«1 year old» 앞 주어 누락', '쉼표 앞 띄어쓰기'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-03-family-reunion', q: 'How much do you remember?', story: '4 stages. Can you clear them all? ⭐', nt: '표지' },
      { t: 'song', k: 'keep', title: 'Tongue Twister', lines: TWISTER, img: 'gen:bts-03-hand-in-hand', src: 'Warm Up', nt: '잰말놀이', n: twisterNote },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 1 · My family 🔒', words: [['father', '아버지', '12080'], ['mother', '어머니', '15564'], ['brother', '남자 형제', 'c7263'], ['sister', '여자 형제', '12054'], ['parents', '부모님', '18493'], ['children', '아이들', '12274']], nt: '1단계 — 가족(001~003)' },
      { t: 'qa', k: 'keep', img: '12151', q: 'Do you have any sisters?', a: "No, I ___. I have a ___.", src: '6쪽', nt: '가족' },
      { t: 'count', k: 'keep', img: 'gen:bts-03-big-family', q: 'How many people are in this family?', a: 'There are ___ people. It is a ___ family.', src: '7쪽', nt: '큰 가족' },
      { t: 'qa', k: 'fix', img: 'gen:bts-03-brown-eyes', q: 'What color are her eyes?', a: 'She has ___ eyes.', chips: ['brown', 'black'], src: '9쪽', nt: '❗ 눈 색', n: ['원본 «black eyes» → brown eyes. black 칩은 일부러 남긴 함정'] },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 2 · How old? 🔒', words: [['grandmother', '할머니', '16124'], ['grandfather', '할아버지', '12491'], ['old', '나이가 많은', '13003'], ['young', '어린', '12026'], ['twins', '쌍둥이', 'gen:bts-03-twins'], ['baby', '아기', '19011']], nt: '2단계 — 나이(004~006)' },
      { t: 'qa', k: 'fix', img: 'gen:bts-03-pumpkin-baby', label: '1', q: 'How old is the baby?', a: 'The baby is 1 ___ old.', src: '13쪽', nt: '❗ year', n: ['원본은 주어가 빠짐 → The baby is …'] },
      { t: 'order', k: 'keep', img: '12048', words: ['old.', 'is', 'grandmother', 'My'], src: '14쪽', nt: '순서 맞추기' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 3 · Relatives 🔒', words: [['aunt', '이모·고모', '19296'], ['uncle', '삼촌', 'c7118'], ['cousin', '사촌', '18005'], ['cousins', '사촌들', '14178']], nt: '3단계 — 친척(007~009)' },
      { t: 'fill', k: 'new', title: 'Guessing game 🕵️', lines: ["I am your father's brother. — I am your ___.", "I am your aunt's baby. — I am your ___."], nt: '수수께끼', n: ['원본 복습에 Unit 3 이 두 쪽뿐이라 보강'] },
      { t: 'fill', k: 'keep', title: 'My aunt', img: 'gen:bts-03-aunt-36', lines: ['My aunt is ___ years old.', 'She has black hair and ___ eyes.'], src: '19쪽', nt: '친척 소개' },
      { t: 'ox', k: 'new', img: '19011', s: 'The baby is old.', nt: '⭕❌', n: ['정답 ❌ → «No! The baby is young.»'] },
      { t: 'guess', k: 'new', img: '12284', open: [], q: 'Stage 4 · Boss! Who is it?', chips: ['Who is she?', 'How old is he?', 'What color is her hair?'], nt: '4단계 — 보스 문제', n: ['타일을 열 때마다 질문 한 개 — 권 전체 질문 세 가지를 모두 씁니다'] },
      { t: 'yourturn', k: 'new', img: '16625', title: 'My whole family', lines: ['There are ___ people in my family.', 'My ___ is ___ years old.', 'He / She has ___ hair.'], nt: '권 전체 내 말로' },
      { t: 'ican', k: 'new', items: [['I can talk about my family.', 'I have a big family. I have two brothers.'], ['I can say how old people are.', 'My grandfather is 69. He is old.'], ['I can talk about my relatives.', "My aunt is my mother's sister."]], nt: 'BTS 3 전체 I can' },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 3 Unit Test', orig: 17,
    intro: '10문항 단원 시험. 화상수업에서 말로 보는 시험이라 문항마다 «말로 답하기» 를 기준으로 했습니다.',
    fixed: ['❗ 문항 4: «Do you have any sisters? — No» 인데 사진에 여자아이 → 형제만 있는 사진', '문항 7: 아기 사진에 «his eyes and hair» — 머리카락이 거의 없는 아기 → 눈·머리가 보이는 사진', '문항 9 rearrange 낱말 칸 띄어쓰기', 'General Information 쪽 → 시험지에서 뺐음'],
    slides: [
      { t: 'cover', k: 'new', img: '18792', q: 'Test time! You can do it! 💪', story: '10 questions · 1 point each', nt: '표지' },
      { t: 'scramble', k: 'keep', title: '1. Unscramble!', items: [['ylmafi', '12284'], ['fetrha', '12080'], ['retrboh', '12151'], ['eormht', '15564']], src: '문항 1', nt: '문항 1', n: ['원본 문항 1 그대로(family, father, brother, mother) — 001과 다른 사진으로'] },
      { t: 'qa', k: 'keep', img: '12080', title: '2.', q: 'Who is he?', a: 'He is my ___.', src: '문항 2', nt: '문항 2' },
      { t: 'qa', k: 'keep', img: '18493', title: '3.', q: 'Who are they?', a: 'They are my ___.', src: '문항 3', nt: '문항 3' },
      { t: 'qa', k: 'fix', img: '12151', title: '4.', q: 'Do you have any sisters?', a: "No, I ___.", src: '문항 4', nt: '문항 4', n: ['원본: 여자아이가 있는 사진에 «No» → 형제만 있는 사진'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-03-small-family', title: '5.', q: 'Is her family big or small?', a: 'She has a ___ family.', src: '문항 5', nt: '문항 5' },
      { t: 'count', k: 'keep', img: 'gen:bts-03-hannah-family', title: '6.', q: 'How many people are in the family?', a: 'There are ___ people.', src: '문항 6', nt: '문항 6' },
      { t: 'qa', k: 'fix', img: 'gen:bts-03-blond-boy', title: '7.', q: 'What color is his hair?', a: 'He has ___ hair.', src: '문항 7', nt: '문항 7', n: ['원본: 머리카락이 거의 없는 아기 사진 → 머리 색이 분명한 사진'] },
      { t: 'qa', k: 'keep', img: '16020', label: '62', title: '8.', q: 'How old is my grandfather?', a: 'He is ___ years old.', src: '문항 8', nt: '문항 8' },
      { t: 'order', k: 'fix', img: 'gen:bts-03-aunt-blonde', words: ['blonde hair.', 'My aunt', 'has'], src: '문항 9', nt: '문항 9', n: ['원본 칸 띄어쓰기 정리'] },
      { t: 'qa', k: 'keep', img: '16127', label: '1', title: '10.', q: 'How old is the baby?', a: 'The baby is 1 ___ old.', src: '문항 10', nt: '문항 10' },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–3', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['4–6', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['7–9', 'Great!', '거의 다 왔어요 — 하나만 더'], ['10 ⭐', 'Perfect!', 'BTS 4 로 출발! 🎉']], src: '점수표', nt: '점수표', n: ['점수마다 다음에 할 일을 함께'] },
      { t: 'next', k: 'new', img: 'gen:bts-03-food', q: 'What food do you like?', ko: 'BTS 4 는 «음식»! 제일 좋아하는 음식은 뭔가요?', nt: '다음 권 예고', n: ['BTS 4 (Food) 첫 장면 — 답은 다음 권 첫 질문으로 씁니다'] },
    ] },
  ],
};
