// BTS 12 새 교재 설계 데이터. k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
// 사진 번호 = photo-catalog.json · 'gen:…' = 새로 만들 사진(gen/req-bts-12.json)
import { open, close, HELLO } from '../common.mjs';
const USONG_2 = { t: 'song', k: 'new', small: "Let's sing! ♪ Farmer in the Dell", title: "How Do You Go to Work? 🚲", img: "gen:bts-12-song-go-to-work", nt: "출근 교통 노래(새로 지음)", n: ["곡조: The Farmer in the Dell (저작권 만료 곡) — 가사는 이 단원 낱말로 새로 지었습니다","'ride my bike'에서 자전거 페달 돌리기, 'takes the bus'에서 운전대 돌리며 'beep-beep' 경적 누르는 동작을 해요."], src: '새로 지음', lines: ["How do you go to work?","I ride my bike to work!","It takes me twenty minutes.","I ride my bike to work!","How does he go to work?","He takes the bus, beep-beep!","It takes him thirty minutes.","He takes the bus, beep-beep!"] };

const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3';

// ABC Job Song (원본 Warm-up) — 26줄이라 한 쪽에 안 들어가 두 쪽으로 나눔
const ABC1 = ['A, astronaut! B, ballerina!', 'C, conductor! D, doctor!', 'E, engineer! F, firefighter!', 'G, gardener! H, hairdresser!', 'I, illustrator! J, jockey!', 'K, karate instructor! L, librarian!', 'M, musician!'];
const ABC2 = ['N, nurse! O, optometrist!', 'P, pilot! Q, queen!', 'R, racecar driver! S, scientist!', 'T, teacher! U, umpire!', 'V, vet! W, waiter!', 'X, X-ray technician!', 'Y, yoga instructor! Z, zookeeper!'];
// Jobs song (원본 Goodbye Song 자리)
const JOBS = ['Firefighter, soccer player, teacher, doctor,', 'painter, chef, police officer, astronaut!', 'What do you want to be?', 'A doctor! I will help you get better.', 'A firefighter! I will save you.'];

export const COURSE = {
  head: `<h1>BTS 12 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트의 BTS 12 원본 <b>252쪽</b>(11묶음 — Jobs · Going to Work · I want to be · REVIEW · TEST)을 한 장씩 읽어 원고로 옮긴 뒤, BTS 1 시안과 같은 원칙(한 쪽 한 목표 · 가림→공개 · 규칙 찾기 · 이어지는 이야기 · ⭕❌ · Guess who · I can · 다음 시간 예고)으로 다시 짰습니다.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>직업·일터·교통수단 낱말, <b>work/works · need/use · my/his/their · drive/ride/take · may/might · It takes me … · want to be · like to · Do/Does …?</b> 범위는 원본 그대로입니다. 원본의 오타·문법 오류·어긋난 사진은 고쳤습니다(과마다 목록).</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>권 전체를 잇는 이야기 — <b>Lily·Sam</b>(001 «경찰관·제빵사가 될래») → <b>Rose·Toby</b>(004 부모님 출근길) → <b>Lily·Hannah</b>(007 «이제 제빵사 말고 의사가 될래!»). 과마다 표지 Big Question, 규칙 찾기, ⭕❌, Guess who, 내 이야기(Your turn), I can ✅, 다음 시간 예고.</div>
</div>
<div class="box warn"><b>⚠️ 사진</b><br>원본의 무서운 분장(얼굴 페인트 판토마임)·화난 권투 요리사 사진 7쪽은 모두 밝은 장면으로 바꿨습니다. 점선 상자는 새로 만들 사진입니다(39장).</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>고친 문장 승인</b> — 특히 002 «This is our mail truck» 말풍선(빈칸 답이 their 인데 말풍선이 our), 005 «I might drive the motorcycle» → ride, 007 Hannah 의 «either»(앞에서 경찰관이 되겠다고 한 적이 없음 — 문장을 뺐습니다), 008 portray 뜻 «그리다»(틀림) → «연기하다» 로 바꾸고 학생 문장은 «play a character».</li>
<li><b>ABC Job Song 의 «Q, queen»</b> — 직업이 아닙니다(원본 그대로 둠). 곡을 바꿀지 결정해 주세요. 원곡 출처·저작권도 확인이 필요합니다.</li>
<li><b>003 에는 원본 낱말표가 없었습니다</b>(6쪽 빠짐) — 본문 낱말로 새로 만들었습니다. 004·005·007·009 도 22쪽이 빠져 있습니다(마지막 쪽 번호 확인 필요).</li>
<li><b>이야기 이어 붙이기</b> — 008 의 Sam 이 «이제 화가가 되고 싶다» 는 새 대사(원본에 없음). 원하지 않으면 원본처럼 이야기 없이 둡니다.</li>
<li><b>TEST 는 시험</b>이라 ⭕❌·Guess who·이야기를 넣지 않았습니다(BTS 1 과 같은 방식).</li>
<li><b>새 사진 39장</b>(힉스필드 크레딧) — 점선 상자 자리.</li>
<li><b>새 단원 노래 1곡</b> — 노래가 없던 단원에 새로 지은 노래를 Hello Song 바로 뒤에 넣었습니다: Unit 2 «How Do You Go to Work?»(The Farmer in the Dell). 곡조는 모두 저작권이 끝난 동요(또는 손뼉·랩 챈트)이고 가사는 그 단원 낱말로 새로 썼습니다. <b>가사 승인</b>과 <b>녹음(반주·노래)</b>이 필요합니다 — 지금은 줄마다 🔊(기계 음성)로만 들을 수 있습니다.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '직업·일하는 곳', unit: U1, title: 'Jobs', orig: 27,
    intro: '직업과 일하는 곳, «Where does he work? — He works at the police station.» 이야기: Lily 와 Sam 이 학교에서 직업을 배우고, 커서 무엇이 되고 싶은지 이야기합니다.',
    fixed: ['«fire fighter / hair dresser» 띄어쓰기 → firefighter · hairdresser', 'teacher «선생» → 선생님 · jobs «일, 채용,» → 직업', '«Hello Sam! / Hello Lily!» 쉼표 → Hello, Sam!', 'catch «체포하다» → 잡다(아이 말투)', '«What does Sam want to be? Why does he want to be a ___?» 두 질문이 한 쪽에 → 빈칸 쪽으로 정리', '원본 목표의 «Possessive Adjectives» 는 002 내용 → 002 목표로 옮김'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-12-careerday', q: 'Who works in your city?', story: 'Sam and Lily are learning about jobs today!', nt: '표지 + Big Question', n: ['직업 옷을 입은 아이들 사진으로 «누가 누구일까?» 를 먼저 묻습니다', '끝에 학생이 «He works at the fire station.» 처럼 답하는 것이 목표입니다'] },
      ...open([['I can name jobs and places.', '직업과 일하는 곳을 영어로 말할 수 있어요.'], ['I can ask "Where does he work?"', '«어디에서 일해요?» 를 물을 수 있어요.'], ['I can say "She works at a bank."', 'work / works 를 알맞게 써요.']]),
      { t: 'song', k: 'fix', title: 'ABC Job Song (A–M)', lines: ABC1, img: '12477', src: 'Warm-up 5쪽', nt: '직업 알파벳 노래 ①', n: ['원본은 26줄이 한 쪽 → 두 쪽으로 나눔(002 에서 N–Z)', '글자를 부르면 학생이 직업을 외치는 메아리 놀이로'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Jobs 🔒', words: [['police officer', '경찰관', '13184'], ['teacher', '선생님', '12229'], ['firefighter', '소방관', '12972'], ['baker', '제빵사', '12793'], ['banker', '은행원', '17229'], ['mail carrier', '우체부', '14753'], ['hairdresser', '미용사', '15168'], ['office worker', '회사원', '12282']], src: 'Vocabulary 6쪽', nt: '직업 — 뜻 가리기', n: ['<del>fire fighter · hair dresser</del> → 한 낱말로 · <del>선생</del> → 선생님 · <del>빵 굽는 사람</del> → 제빵사 · <del>은행가</del> → 은행원', '사진만 보고 영어로 먼저 말하게 합니다'] },
      { t: 'vocab', k: 'keep', title: 'Jobs', words: [['police officer', '경찰관', '13184'], ['teacher', '선생님', '12229'], ['firefighter', '소방관', '12972'], ['baker', '제빵사', '12793'], ['banker', '은행원', '17229'], ['mail carrier', '우체부', '14753'], ['hairdresser', '미용사', '15168'], ['office worker', '회사원', '12282']], nt: '직업 — 공개', n: ['따라 말하기 2번 → 강사가 사진을 가리키면 학생이 말하기'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Where do they work? 🔒', words: [['police station', '경찰서', 'gen:bts-12-police-station'], ['school', '학교', '16456'], ['fire station', '소방서', 'gen:bts-12-fire-station'], ['bakery', '빵집', '12794'], ['bank', '은행', 'gen:bts-12-bank'], ['post office', '우체국', '19491'], ['hair salon', '미용실', 'gen:bts-12-salon'], ['office', '사무실', '12253']], src: 'Vocabulary 6쪽', nt: '일하는 곳 — 뜻 가리기', n: ['<del>헤어샵</del> → 미용실', '앞 쪽 직업과 짝을 지어 «police officer — police station» 처럼 말하게 합니다'] },
      { t: 'rule', k: 'new', title: 'work or works?', left: { h: 'I / you / they', ex: ['I **work** at a school.', 'They **work** at a bank.'] }, right: { h: 'he / she', ex: ['He **works** at a bakery.', 'She **works** in an office.'] }, q: 'When do we add "-s"?', nt: '규칙 찾기', n: ['설명 전에 두 묶음을 보고 학생이 «he·she 뒤에는 s» 를 먼저 찾게 합니다'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'Where does he work?', head: ['question', 'answer'], rows: [['Where do they work?', 'They work at the fire station.'], ['Where does he work?', 'He works at the police station.'], ['Where does she work?', 'She works in an office.']], src: 'Grammar 7·8쪽', nt: '문장 틀', n: ['원본의 Subject/Verb 용어 표 → 질문·답 짝으로', 'at + 건물(at the bank) · in + 안(in an office) — at 과 in 은 «외우기» 보다 예문으로 익힙니다'] },
      { t: 'qa', k: 'keep', img: '12848', title: 'Look at the city!', q: 'What buildings can you see in a city?', a: 'I can see a ___ and a ___.', chips: ['bank', 'school', 'bakery', 'police station'], src: '9쪽', nt: '도시 둘러보기', n: ['사진 속에서 찾을 수 없는 건물도 «우리 동네에 있는 것» 으로 말해도 됩니다'] },
      { t: 'qa', k: 'keep', img: '13184', title: 'Who is he?', q: 'Where does he work?', a: 'He is a ___. He works at the ___.', chips: ['police officer', 'police station'], src: '10쪽', nt: '경찰관' },
      { t: 'qa', k: 'fix', img: '20177', title: 'Who are they?', q: 'Where do they work?', a: 'They are ___. They work at the ___.', chips: ['firefighters', 'fire station'], src: '12쪽', nt: '소방관들', n: ['원본은 가만히 서 있는 사진 → 경보가 울려 소방차로 달려가는 장면으로'] },
      { t: 'qa', k: 'keep', img: '12337', title: 'Who is he?', q: 'Where does he work?', a: 'He is a ___. He works in a ___.', chips: ['baker', 'bakery'], src: '13쪽', nt: '제빵사' },
      { t: 'qa', k: 'keep', img: '18364', title: 'Who is he?', q: 'Where does he work?', a: 'He is a ___. He works at the ___.', chips: ['mail carrier', 'post office'], src: '14쪽', nt: '우체부' },
      { t: 'qa', k: 'fix', img: '18139', title: 'At the bank', q: 'Where does the banker work?', a: 'The banker works at a ___.', src: '15쪽', nt: '은행원', n: ['원본 «Who is she?» 는 사진 속 사람이 여럿 → «the banker» 로'] },
      { t: 'qa', k: 'fix', img: '18782', title: 'At the hair salon', q: 'Where does the hairdresser work?', a: 'The hairdresser works in a ___.', src: '16쪽', nt: '미용사', n: ['<del>hair dresser</del> → hairdresser · 웃는 손님 사진으로'] },
      { t: 'guess', k: 'new', img: '18570', open: [0, 4], q: 'Guess! What job is it?', chips: ['Is he a chef?', 'Is he a doctor?', 'Is he a firefighter?'], nt: 'Guess who 타일', n: ['타일을 열 때마다 «Is he a …?» 로 물어야 합니다', '정답은 여러 모자를 써 보는 학생 — «He wants to try many jobs!» 로 마무리'] },
      { t: 'ox', k: 'new', img: '12793', s: 'He is a banker. He works at a bank.', nt: '⭕❌ 몸으로 답하기', n: ['정답 ❌ → «No! He is a baker. He works in a bakery.» 까지 말하면 성공', 'baker/banker 처럼 소리가 비슷한 낱말을 일부러 헷갈리게 했습니다'] },
      { t: 'vocab', k: 'fix', title: 'New words', words: [['future', '미래', '12388'], ['catch', '잡다', '12569'], ['thieves', '도둑들', '15311']], src: '18쪽 New Words', nt: '이야기 낱말', n: ['<del>체포하다</del> → 잡다 · thieves 는 thief 의 복수'] },
      { t: 'story', k: 'fix', img: 'gen:bts-12-sam-lily', title: 'Lily and Sam ①', lines: [['Lily', 'Hello, Sam! How are you today?'], ['Sam', 'I am fine! We are learning about jobs in school.'], ['Lily', 'What job do you like? What do you want to be in the future?']], src: '19쪽 Role-play', nt: '이야기 ①', n: ['<del>Hello Sam!</del> → Hello, Sam!', '강사와 학생이 역할을 나눠 읽고, 두 번째는 바꿔 읽습니다'] },
      { t: 'story', k: 'keep', img: '15820', title: 'Lily and Sam ②', lines: [['Sam', 'I like many jobs. I think... I want to be a police officer.'], ['Sam', 'I want to catch thieves and help people. What about you?'], ['Lily', 'I want to be a baker. I want to make delicious cakes and cookies.']], src: '20쪽', nt: '이야기 ②', n: ['Lily 의 꿈(제빵사)을 기억해 두세요 — 007 에서 바뀝니다!'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ['What does Sam want to be? — He wants to be a ___.', 'Why? — He wants to catch ___ and help people.', 'What does Lily want to be? — She wants to be a ___.', 'Why? — She wants to make cakes and ___.'], chips: ['police officer', 'thieves', 'baker', 'cookies'], src: '21쪽', nt: '이야기 질문', n: ['원본은 질문만 네 줄 → 답 틀을 함께 주어 문장으로 답하게'] },
      { t: 'match', k: 'keep', title: 'Who are they?', left: ['13184', '12972', '12793', '12229'], right: ['baker', 'teacher', 'police officer', 'firefighter'], src: '24쪽 GAME', nt: '게임 ① 짝 맞추기', n: ['짝을 맞출 때마다 «Where does he work?» 에 답하기'] },
      { t: 'match', k: 'keep', title: 'Where do they work?', left: ['17229', '14753', '15168', '12282'], right: ['office worker', 'hairdresser', 'banker', 'mail carrier'], src: '25쪽 GAME', nt: '게임 ② 짝 맞추기' },
      { t: 'yourturn', k: 'new', img: '12080', title: 'Your family', lines: ['My mom is a ___. She works at ___.', 'My dad is a ___. He works in ___.'], chips: ['office', 'bank', 'school', 'hospital'], nt: '내 이야기', n: ['모르는 직업은 강사가 영어로 알려 줍니다', '«at home» 도 좋은 답입니다'] },
      ...close([['I can name jobs and places.', 'baker — bakery, banker — bank'], ['I can ask "Where does he work?"', 'Where does she work?'], ['I can say "She works at a bank."', 'He works at the fire station.']], { img: '16503', q: 'What does a firefighter need?', ko: '소방관에게는 무엇이 필요할까요? (002)' }),
    ] },
  // ───────────────────────── 002
  { code: '002', tab: '도구·누구의', unit: U1, title: 'Jobs', orig: 27,
    intro: '일에 필요한 도구 «He needs a hose.», 쓰는 것 «They use computers.», 누구의 차인지 «It\'s their fire truck.» 를 배웁니다.',
    fixed: ['<b>❗ «This is our mail truck» 말풍선 + 빈칸 «It\'s ___ mail truck.»</b> — 말풍선을 그대로 쓰면 답이 our 로 읽힘 → 말풍선을 빼고 사진만으로 their', '«Whose truck is it?» / «Whose truck is this?» 섞임 → Whose … is this? 로 통일', '«What is their job?» → What are their jobs?', '«She cuts ___.» → She cuts and styles hair.', '«He collects and delivers mail» 에 쓸 mail bag 사진이 없음 → 우편 가방이 보이는 사진', 'fire engine / fire truck 섞임 → 이 과는 fire truck(낱말표 표기)'],
    slides: [
      { t: 'cover', k: 'new', img: '16058', q: 'What does a firefighter need?', story: 'Every job needs special tools. Let\'s find them!', nt: '표지 + Big Question', n: ['불 속에서 강아지를 구해 나오는 소방관 — «무엇이 필요했을까?» 로 시작'] },
      ...open([['I can say what people need for work.', '일할 때 필요한 것을 말해요 — He needs a hose.'], ['I can say "They use computers."', '무엇을 쓰는지 말해요.'], ['I can say whose it is.', 'my · his · her · their 로 누구 것인지 말해요.']], 'Lesson Goals (001과 목표가 같았음)'),
      { t: 'song', k: 'fix', title: 'ABC Job Song (N–Z)', lines: ABC2, img: '12566', src: 'Warm-up 5쪽', nt: '직업 알파벳 노래 ②', n: ['001 에서 A–M, 이번에 N–Z', '«Q, queen» 은 직업이 아닙니다 — 원본 그대로(사람이 정할 것)'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Tools & actions 🔒', words: [['hose', '호스', '16503'], ['axe', '도끼', 'gen:bts-12-axe'], ['helmet', '헬멧', '12018'], ['hair dryer', '헤어드라이어', 'gen:bts-12-hairdryer'], ['comb', '빗', '15168'], ['collect', '모으다', 'gen:bts-12-collect'], ['deliver', '배달하다', '18364']], src: 'Vocabulary 6쪽', nt: '낱말 — 가림', n: ['<del>배달</del> → 배달하다(동사)', '도구는 «누가 쓸까?» 를 함께 묻습니다'] },
      { t: 'vocab', k: 'keep', title: 'Tools & actions', words: [['hose', '호스', '16503'], ['axe', '도끼', 'gen:bts-12-axe'], ['helmet', '헬멧', '12018'], ['hair dryer', '헤어드라이어', 'gen:bts-12-hairdryer'], ['comb', '빗', '15168'], ['collect', '모으다', 'gen:bts-12-collect'], ['deliver', '배달하다', '18364']], nt: '낱말 — 공개' },
      { t: 'rule', k: 'new', title: 'need or needs?', left: { h: 'I / you / they', ex: ['I **need** a hose.', 'They **use** computers.'] }, right: { h: 'he / she', ex: ['He **needs** an axe.', 'She **uses** a comb.'] }, q: 'Remember "work / works"? What is the same?', nt: '규칙 찾기', n: ['001 의 works 규칙이 need·use 에도 그대로라는 것을 학생이 찾게 합니다'] },
      { t: 'qa', k: 'fix', img: '12972', title: 'What is your job?', q: 'What do you do?', a: 'I am a ___. I fight fires and save people.', src: '9쪽', nt: '소방관 ①', n: ['<del>I fight fire</del> → I fight fires'] },
      { t: 'qa', k: 'keep', img: '16503', title: 'What do you need?', q: 'What do firefighters need?', a: 'We need a ___, an ___ and a ___.', chips: ['hose', 'axe', 'helmet'], src: '10쪽', nt: '소방관 ② 도구', n: ['an axe — 모음 앞의 an 을 여기서 한 번 짚습니다'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-hairdresser', title: 'What is her job?', q: 'What does she do?', a: 'She is a ___. She cuts and styles hair.', src: '11쪽', nt: '미용사 ①', n: ['<del>She cuts ___.</del> → 빈칸 답이 둘 이상이라 직업 쪽에 빈칸'] },
      { t: 'qa', k: 'keep', img: '15168', title: 'What does she need?', q: 'What does a hairdresser need?', a: 'She needs ___, a ___ and a hair dryer.', chips: ['scissors', 'comb'], src: '12쪽', nt: '미용사 ② 도구' },
      { t: 'qa', k: 'fix', img: '12282', title: 'What are their jobs?', q: 'Where do they work?', a: 'They are ___. They work in an ___.', chips: ['office workers', 'office'], src: '13쪽', nt: '회사원 ①', n: ['<del>What is their job?</del> → What are their jobs?'] },
      { t: 'qa', k: 'keep', img: '12587', title: 'What do they use?', q: 'What do office workers use?', a: 'They use ___.', src: '14쪽', nt: '회사원 ② 쓰는 것' },
      { t: 'qa', k: 'keep', img: '12229', title: 'What is her job?', q: 'What does she need?', a: 'She is a ___. She needs a board and ___.', chips: ['teacher', 'books'], src: '15쪽', nt: '선생님' },
      { t: 'qa', k: 'fix', img: '14753', title: 'What is his job?', q: 'What does he do? What does he use?', a: 'He ___ and delivers mail. He uses a mail ___.', chips: ['collects', 'bag'], src: '16·17쪽', nt: '우체부', n: ['원본 두 쪽 → 한 쪽으로 · 우편 가방이 잘 보이는 사진'] },
      { t: 'table', k: 'fix', small: 'Whose?', title: 'my · your · his · her', head: ['I', 'you', 'he', 'she', 'we', 'they'], rows: [['my', 'your', 'his', 'her', 'our', 'their']], tip: "It's her police car. = 그 경찰관의 차예요.", src: 'Grammar 8쪽 (P.A.)', nt: '누구의 — 표', n: ['원본 «P.A.(Possessive Adjectives)» 용어는 강사 메모로', '위아래로 짝을 짚으며 «I — my» 메아리 읽기'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-police-car', title: 'Whose car is this?', q: '"This is my police car."', a: "It's ___ police car.", chips: ['her', 'his', 'their'], src: '18쪽', nt: '누구의 ① her', n: ['경찰관이 «my» 라고 한 것을 학생은 «her» 로 바꿔 말합니다 — 이 과의 핵심 전환'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-mail-truck', title: 'Whose truck is this?', q: 'They are mail carriers.', a: "It's ___ mail truck.", chips: ['our', 'their', 'his'], src: '19쪽', nt: '❗ 누구의 ② their', n: ['원본 말풍선 «This is our mail truck» 이 빈칸 답을 our 로 보이게 함 → 말풍선을 빼고 사진으로만', '<del>Whose truck is it?</del> → Whose truck is this?'] },
      { t: 'qa', k: 'keep', img: '15459', title: 'Whose truck is this?', q: 'They are firefighters.', a: "It's ___ fire truck.", src: '20쪽', nt: '누구의 ③' },
      { t: 'qa', k: 'keep', img: '16097', title: 'Whose bus is this?', q: 'He is a bus driver.', a: "It's ___ bus.", src: '21쪽', nt: '누구의 ④ his' },
      { t: 'qa', k: 'keep', img: 'gen:bts-12-taxi-driver', title: 'Whose taxi is this?', q: 'He is a taxi driver.', a: "It's ___ taxi.", src: '22쪽', nt: '누구의 ⑤' },
      { t: 'story', k: 'new', img: 'gen:bts-12-axe', title: 'Mango at the fire station', lines: [['Mango', 'Wow! Whose truck is this?'], ['Jack', "It's our fire truck!"], ['Mango', 'What do you need for your job?'], ['Jack', 'I need a hose, an axe and a helmet.']], nt: '이야기', n: ['원본에는 대화가 없어 이 과 문장으로 짧은 인터뷰를 만들었습니다', 'Jack 은 003 에서 다시 만납니다(45살 소방관)']},
      { t: 'ox', k: 'new', img: '15459', s: "It's his fire truck.", nt: '⭕❌', n: ['정답 ❌ → «No! It\'s their fire truck.» (여러 명이니까)'] },
      { t: 'guess', k: 'new', img: '13141', open: [2, 6], q: 'Who are they? What do they drive?', chips: ['They are police officers.', 'They drive a police car.'], nt: 'Guess who', n: ['타일을 열며 «Are they …?» 로 묻기'] },
      { t: 'match', k: 'keep', title: 'What do they drive?', left: ['12972', '13184', 'gen:bts-12-taxi-driver', '16097'], right: ['taxi', 'bus', 'fire truck', 'police car'], src: '24·25쪽 GAME', nt: '게임 짝 맞추기', n: ['원본의 «teacher» 칸은 탈 것이 없어 짝이 안 맞음 → 버스 기사로 바꾸고, 선생님은 다음 쪽 수수께끼로'] },
      { t: 'fill', k: 'keep', img: '12647', title: 'Riddle! Who am I?', lines: ["I'm a teacher.", "I don't drive when I work.", 'I work at a ___.'], chips: ['school', 'bank'], src: '26쪽', nt: '수수께끼', n: ['강사가 다른 직업으로 수수께끼를 하나 더 내 봅니다'] },
      { t: 'yourturn', k: 'new', img: '12071', title: 'What do you use at school?', lines: ['I use a ___ and a ___.', 'This is my ___.', "That is my teacher's ___."], chips: ['pencil', 'book', 'desk'], nt: '내 이야기', n: ['학생이 물건을 카메라에 보여 주며 «This is my …» 로 말합니다'] },
      ...close([['I can say what people need for work.', 'She needs a comb and scissors.'], ['I can say "They use computers."', 'He uses a mail bag.'], ['I can say whose it is.', "It's their fire truck."]], { img: 'gen:bts-12-taxi-driver', q: 'Who is James? What does he drive?', ko: '제임스는 누구이고 무엇을 운전할까요? (003)' }),
    ] },
  // ───────────────────────── 003
  { code: '003', tab: '사람 소개하기', unit: U1, title: 'Jobs', orig: 21,
    intro: '한 사람을 이름·나이·직업·필요한 것·운전하는 것으로 소개합니다. «Her name is Donna. She is 30 years old. She is a police officer.»',
    fixed: ['원본 6쪽(낱말표)이 빠져 있음 → 본문 낱말로 새로 만듦', '«She needs a badge and handcuffs» 에 맞는 사진이 없음 → 배지를 보여 주는 경찰관 사진', '«Talk about her!» 빈 말풍선 쪽 → 틀 문장 4줄을 주어 끝까지 말하게', '«What is their job?» → What are their jobs?', '그리기 빈 칸(«What do they need?») → 화면 수업에 맞게 말하기로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-12-city-vehicles', q: 'Who drives what in the city?', story: 'Meet seven people and their jobs!', nt: '표지 + Big Question', n: ['택시·버스·경찰차·소방차가 한 길에 모인 장면 — 누가 무엇을 운전할까?'] },
      ...open([["I can talk about a person's job.", '다른 사람을 소개해요 — Her name is Donna. She is a police officer.'], ['I can say what they need and drive.', 'She needs a badge. He drives a bus.'], ["I can talk about my family's jobs.", '우리 가족의 직업을 말해요.']]),
      { t: 'vocab', k: 'new', hide: true, title: 'New words 🔒', words: [['taxi driver', '택시 기사', 'gen:bts-12-taxi-driver'], ['bus driver', '버스 기사', '16097'], ['badge', '배지', 'gen:bts-12-donna'], ['rolling pin', '밀대', '12292'], ['laptop', '노트북', '12042'], ['phone', '전화기', '12066']], nt: '이 과의 낱말', n: ['원본은 낱말표가 빠져 있었습니다 → 본문에 나오는 낱말을 모아 한 쪽으로(가림→공개)'] },
      { t: 'memory', k: 'fix', items: ['16097', '13184', '15168', '12972', '12282', '12793'], q: 'Who are they? Say their jobs!', src: '9쪽', nt: '사진 모음 — 직업 말하기', n: ['원본 9쪽 사진 모음 → 5초 보고 기억하기로', '<del>What is their job?</del> → What are their jobs?'] },
      { t: 'memory', k: 'new', hidden: true, items: ['16097', '13184', '15168', '12972', '12282', '12793'], q: 'Who is hiding? 🙈', a: 'A ___ and a ___ are hiding.', nt: '기억 게임', n: ['기억나는 직업을 말할 때마다 «Where does he work?» 한 번 더'] },
      { t: 'table', k: 'fix', small: 'Talk about him / her', title: 'His name is James.', rows: [['His / Her name is', '___.'], ['He / She is', '___ years old.'], ['He / She is a', '___.'], ['He / She needs / drives', '___.']], tip: '남자 → His … He · 여자 → Her … She', src: '10쪽', nt: '소개 틀', n: ['이 틀 네 줄로 이 과 끝까지 말합니다'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-12-taxi-driver', label: 'James · 41', title: 'Who is he?', q: 'Talk about him!', a: 'His name is James. He is 41. He is a ___. He drives a ___.', chips: ['taxi driver', 'taxi'], src: '10쪽', nt: '제임스' },
      { t: 'qa', k: 'keep', img: '16097', label: 'John · 39', title: 'Who is he?', q: 'Talk about him!', a: 'His name is John. He is 39. He is a ___. He drives a ___.', src: '11쪽', nt: '존' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-donna', label: 'Donna · 30', title: 'Who is she?', q: 'What does she need?', a: 'She is a ___. She needs a ___ and handcuffs.', chips: ['police officer', 'badge'], src: '12쪽', nt: '도나', n: ['원본 사진엔 배지가 안 보임 → 배지를 보여 주는 사진', '마지막에 «She drives a police car.» 까지 말하면 보너스'] },
      { t: 'yourturn', k: 'fix', img: 'gen:bts-12-hairdresser', title: 'Talk about her! (Gwen · 28)', lines: ['Her name is ___.', 'She is ___ years old.', 'She is a ___.', 'She needs a ___ and ___.'], chips: ['hairdresser', 'comb', 'scissors'], src: '13쪽', nt: '그웬', n: ['원본은 빈 말풍선 → 틀 네 줄로'] },
      { t: 'yourturn', k: 'fix', img: '12018', title: 'Talk about him! (Jack · 45)', lines: ['His name is ___.', 'He is ___ years old.', 'He is a ___.', 'He needs a ___ and an ___.'], chips: ['firefighter', 'hose', 'axe', 'helmet'], src: '14쪽', nt: '잭' },
      { t: 'yourturn', k: 'fix', img: 'gen:bts-12-gavin', title: 'Talk about him! (Gavin · 40)', lines: ['His name is ___.', 'He is ___ years old.', 'He is an ___.', 'He uses a ___ and a ___.'], chips: ['office worker', 'laptop', 'phone'], src: '15쪽', nt: '개빈', n: ['an office worker — 모음 앞 an'] },
      { t: 'yourturn', k: 'fix', img: 'gen:bts-12-luna', title: 'Talk about her! (Luna · 27)', lines: ['Her name is ___.', 'She is a ___.', 'She needs a ___.', 'She works in a ___.'], chips: ['baker', 'rolling pin', 'bakery'], src: '16쪽', nt: '루나' },
      { t: 'story', k: 'new', img: 'gen:bts-12-police-car', title: 'Mango meets Donna', lines: [['Mango', 'Hi! What is your job?'], ['Donna', "I'm a police officer."], ['Mango', 'What do you need?'], ['Donna', 'I need a badge and handcuffs.'], ['Mango', 'Wow! Do you drive a police car?'], ['Donna', 'Yes, I do!']], nt: '이야기', n: ['원본에는 대화가 없어 이 과 문장으로 짧은 인터뷰를 만들었습니다', '학생이 Mango 역할로 강사를 인터뷰합니다'] },
      { t: 'ox', k: 'new', img: '16097', s: 'John is a taxi driver.', nt: '⭕❌', n: ['정답 ❌ → «No! He is a bus driver. He drives a bus.»'] },
      { t: 'guess', k: 'new', img: '12972', open: [1, 5], q: 'Who is it? He needs a hose.', chips: ['Is he a firefighter?', 'Is he a baker?'], nt: 'Guess who', n: ['강사가 힌트 문장(He needs … / He drives …)을 하나씩 주고 학생이 맞힙니다'] },
      { t: 'order', k: 'new', img: '12292', words: ['needs', 'She', 'rolling pin', 'a'], nt: '순서 맞추기', n: ['정답: She needs a rolling pin.'] },
      { t: 'yourturn', k: 'fix', img: '12080', title: 'Talk about your father!', lines: ['My father is a ___.', 'He works at ___.', 'He needs / uses ___.'], src: '18쪽', nt: '우리 아빠', n: ['원본 그리기 칸 → 말하기로'] },
      { t: 'yourturn', k: 'fix', img: '12167', title: 'Talk about your mother!', lines: ['My mother is a ___.', 'She works at ___.', 'She needs / uses ___.'], src: '19쪽', nt: '우리 엄마' },
      ...close([["I can talk about a person's job.", 'His name is John. He is a bus driver.'], ['I can say what they need and drive.', 'She needs a badge. He drives a taxi.'], ["I can talk about my family's jobs.", 'My father is an office worker.']], { img: 'gen:bts-12-rush-hour', q: 'How do people go to work?', ko: '사람들은 어떻게 출근할까요? (004 Going to Work)' }),
    ] },
  // ───────────────────────── 004
  { code: '004', tab: '출근·교통', unit: U2, title: 'Going to Work', orig: 23,
    intro: '식당·가게·도서관에서 일하는 사람과 출근 방법 «He goes to work by bus. / She may take a taxi.» 이야기: Rose 가 Toby 에게 부모님 출근길을 이야기합니다.',
    fixed: ['<b>원본 10쪽 무서운 얼굴 페인트 판토마임 · 화난 권투 요리사 사진</b> → 식당의 즐거운 장면으로', '«What are Rose\'s parents job?» → What are Rose\'s parents\' jobs?', '«takes the taxi if it\'s raining» → takes a taxi when it rains', '«Hello Rose! / Hi Toby!» 쉼표', '«I ride a ___ to work» 와 «by ___» 가 한 쪽에 섞임 → 나눔', 'clerk «서기» → 점원 · cashier «출납원» → 계산원(가게 말)'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-12-rush-hour', q: 'How do people go to work?', story: "It's 8 a.m. The city is so busy!", nt: '표지 + Big Question' },
      ...open([['I can name places and jobs in town.', '식당·가게·도서관과 거기서 일하는 사람을 말해요.'], ['I can say how people go to work.', 'by bus, drive a car 처럼 출근 방법을 말해요.'], ['I can say "may" and "might".', '«~할지도 몰라요» 를 말해요.']]),
      USONG_2,
      { t: 'vocab', k: 'fix', hide: true, title: 'Places & jobs 🔒', words: [['restaurant', '식당', '16805'], ['waiter', '종업원', '16556'], ['chef', '요리사', '16722'], ['clerk', '점원', '17137'], ['cashier', '계산원', '16004'], ['grocery store', '식료품 가게', 'gen:bts-12-grocery'], ['clothing store', '옷 가게', '12856'], ['library', '도서관', '12401'], ['librarian', '사서', '12063']], src: 'Vocabulary 6쪽', nt: '낱말 — 가림', n: ['<del>레스토랑</del> → 식당 · <del>웨이터</del> → 종업원 · <del>서기</del> → 점원 · <del>출납원</del> → 계산원'] },
      { t: 'vocab', k: 'keep', title: 'Places & jobs', words: [['restaurant', '식당', '16805'], ['waiter', '종업원', '16556'], ['chef', '요리사', '16722'], ['clerk', '점원', '17137'], ['cashier', '계산원', '16004'], ['grocery store', '식료품 가게', 'gen:bts-12-grocery'], ['clothing store', '옷 가게', '12856'], ['library', '도서관', '12401'], ['librarian', '사서', '12063']], nt: '낱말 — 공개' },
      { t: 'vocab', k: 'fix', hide: true, title: 'How do they go? 🔒', words: [['train', '기차', '12583'], ['motorcycle', '오토바이', 'gen:bts-12-motorcycle'], ['taxi', '택시', '15763'], ['car', '자동차', '12135'], ['bus', '버스', '12354'], ['bicycle', '자전거', '12016'], ['subway', '지하철', '19259']], src: '16쪽 What is it?', nt: '탈것 — 가림', n: ['원본 16쪽 «What is it?» 사진 7장을 낱말 쪽으로'] },
      { t: 'rule', k: 'new', title: 'drive, ride or take?', left: { h: 'drive', ex: ['drive a **car**', 'drive a **bus**'] }, right: { h: 'ride / take', ex: ['ride a **bike** / a **motorcycle**', 'take the **bus** / the **subway**'] }, q: 'Which one do you "ride"?', nt: '규칙 찾기', n: ['운전대를 잡으면 drive, 올라타면 ride, 대중교통은 take 를 학생이 찾게 합니다'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'How does he go to work?', head: ['who', 'how'], rows: [['He goes to work', 'by bus / by car / by train.'], ['She may drive', 'her car to work.'], ['They might take', 'the subway.']], src: 'Grammar 7·8쪽', nt: '문장 틀', n: ['원본의 Modal Verb 용어는 강사 메모로', 'may · might = ~할지도 몰라요 · 걸어가면 walk to work · I ride a bike to work 도 함께'] },
      { t: 'qa', k: 'keep', img: '15243', title: 'Going to work!', q: 'How does he go to work?', a: 'He ___ to work.', chips: ['walks', 'drives'], src: '9쪽', nt: '출근길' },
      { t: 'qa', k: 'fix', img: '18793', title: 'Where are they?', q: 'Where are they?', a: 'They are at a ___.', src: '10쪽', nt: '❗ 식당 — 사진 교체', n: ['원본: 무서운 얼굴 페인트 판토마임 + 화난 권투 요리사 → 접시를 잔뜩 든 종업원에 친구들이 웃는 장면'] },
      { t: 'qa', k: 'keep', img: '16722', title: 'Who works at the restaurant?', q: 'What do you do?', a: 'I am a ___. I cook food.', src: '11쪽', nt: '요리사' },
      { t: 'qa', k: 'fix', img: '16351', title: 'Who works at the restaurant?', q: 'What do you do?', a: 'We are ___. We bring the food.', src: '11쪽', nt: '종업원들', n: ['원본은 waitress·waiter 한 쌍 → 낱말표의 waiter 로 통일(여러 명 waiters)'] },
      { t: 'qa', k: 'fix', img: '19310', title: 'Where is she?', q: 'Where is the girl?', a: 'She is in the ___.', src: '12쪽', nt: '도서관', n: ['책을 빌리는 아이 사진 — 사서가 함께 보여 다음 쪽으로 이어집니다'] },
      { t: 'qa', k: 'keep', img: '12063', title: 'Who works in the library?', q: 'What do you do?', a: "I am a ___. I work in the library. Don't be loud here!", src: '13쪽', nt: '사서' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-grocery', title: 'What is her job?', q: 'Where does she work?', a: 'She is a ___. She works at a ___.', chips: ['clerk', 'grocery store'], src: '14쪽', nt: '점원 ①' },
      { t: 'qa', k: 'keep', img: '17137', title: 'Clerks work at many stores!', q: 'Where do you work?', a: 'I am a ___. I work at a clothing store.', src: '15쪽', nt: '점원 ②', n: ['원본의 drug store(약국) 점원도 함께 말해 봅니다'] },
      { t: 'qa', k: 'fix', img: 'c7264', title: 'How does she go to work?', q: 'How does she go to work?', a: 'She rides a ___ to work.', src: '17쪽', nt: '자전거로', n: ['원본은 «I ride a ___» 와 «I go to work by ___» 가 한 쪽 → 나눔(by car 는 표·게임에서)'] },
      { t: 'table', k: 'keep', small: 'New words', title: 'Words in the story', rows: [['excellent', '아주 훌륭한'], ['often', '자주'], ['sometimes', '가끔']], src: '18쪽 New Words', nt: '이야기 낱말', n: ['often(자주) > sometimes(가끔) — 손가락 수로 얼마나 자주인지 보여 주기'] },
      { t: 'story', k: 'fix', img: 'gen:bts-12-rose-toby', title: 'Rose and Toby ①', lines: [['Toby', 'Hello, Rose! Where do your parents work?'], ['Rose', 'Hi, Toby! My mother is a banker. She works in the bank.'], ['Rose', 'My father is a chef. He works at the restaurant.']], src: '19쪽 Role-play', nt: '이야기 ①', n: ['<del>Hello Rose! / Hi Toby!</del> → 쉼표'] },
      { t: 'story', k: 'fix', img: '15763', title: 'Rose and Toby ②', lines: [['Toby', 'They have excellent jobs! How do they go to work?'], ['Rose', 'My father may drive his car or take the bus to work.'], ['Rose', 'My mother often walks to work. She sometimes takes a taxi when it rains.']], src: '20쪽', nt: '이야기 ②', n: ['<del>takes the taxi if it\'s raining</del> → takes a taxi when it rains'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ["What are Rose's parents' jobs? — Her mother is a ___. Her father is a ___.", 'Where does her father work? — At the ___.', 'How does her mother go to work? — She often ___.'], chips: ['banker', 'chef', 'restaurant', 'walks'], src: '21쪽', nt: '이야기 질문', n: ["<del>What are Rose's parents job?</del> → parents' jobs?"] },
      { t: 'ox', k: 'new', img: '16722', s: "Rose's father is a banker.", nt: '⭕❌', n: ['정답 ❌ → «No! He is a chef. Her mother is a banker.»'] },
      { t: 'guess', k: 'new', img: '19259', open: [0, 3], q: 'How does he go to work?', chips: ['Does he take the bus?', 'Does he take the subway?'], nt: 'Guess — 무엇을 타고 갈까?', n: ['타일을 열며 «Does he take …?» 로 묻기'] },
      { t: 'match', k: 'new', title: 'What is it?', left: ['12583', '12016', '15763', '19259'], right: ['taxi', 'subway', 'train', 'bicycle'], nt: '짝 맞추기' },
      { t: 'yourturn', k: 'new', img: '12080', title: 'How do your parents go to work?', lines: ['My mom ___ to work.', 'My dad goes to work by ___.', 'Sometimes they might ___.'], chips: ['walks', 'car', 'bus', 'take a taxi'], nt: '내 이야기' },
      ...close([['I can name places and jobs in town.', 'A chef works at a restaurant.'], ['I can say how people go to work.', 'She takes the bus to work.'], ['I can say "may" and "might".', 'He may drive his car.']], { img: '18490', q: 'How long does it take?', ko: '출근하는 데 얼마나 걸릴까요? (005)' }),
    ] },
  // ───────────────────────── 005
  { code: '005', tab: '걸리는 시간', unit: U2, title: 'Going to Work', orig: 23,
    intro: '«It takes me 20 minutes. / It might take her 5 to 8 minutes.» 사진을 보고 누가 무엇을 타고 얼마나 걸리는지 말하는 Picture Talk 과.',
    fixed: ['<b>«I might drive the motorcycle»</b> → ride the motorcycle', '«He ___ taxi to work» → He takes a taxi · «He ___ bike» → rides his bike', '«I don\'t ___ the police car» — 답이 drive 인데 앞 과 표에 drive 가 없던 문제 → 004 규칙 쪽에서 먼저 익힘', '«I may ride a ___ or ___ to work»(taxi/bus) → take a taxi or a bus', '자전거 탄 사람 사진이 여자인데 문장은 He → She 로', '«__:__» 빈칸 모양 통일 → ___'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-12-megaphone-host', q: 'How long does it take?', story: "It's Picture Talk time! Look and talk!", nt: '표지 + Big Question', n: ['메가폰을 든 진행자 — 원본 Picture Talk 의 머리띠 진행자를 밝은 사진으로'] },
      ...open([['I can say how people go to work.', 'He goes to work by train.'], ['I can say "It takes me 20 minutes."', '걸리는 시간을 말해요.'], ['I can guess with "might".', 'It might take her 5 minutes.']]),
      USONG_2,
      { t: 'vocab', k: 'new', hide: true, title: 'Remember? 🔒', words: [['chef', '요리사', '12422'], ['librarian', '사서', '19423'], ['banker', '은행원', '18139'], ['hairdresser', '미용사', '16072'], ['police officer', '경찰관', '18020'], ['waiter', '종업원', '16556']], nt: '지난 낱말 떠올리기', n: ['004 낱말을 다른 사진으로 — 오늘 Picture Talk 에 나올 사람들입니다'] },
      { t: 'rule', k: 'new', title: 'me · her · him · them', left: { h: 'I', ex: ['It takes **me** 20 minutes.'] }, right: { h: 'she / he / they', ex: ['It takes **her** 5 minutes.', 'It might take **them** 8 minutes.'] }, q: 'I → me. She → ? He → ? They → ?', nt: '규칙 찾기', n: ['I→me, she→her, he→him, they→them 짝을 학생이 채우게 합니다'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'It takes me 20 minutes.', head: ['it', 'takes', 'who', 'how long'], rows: [['It', 'takes', 'me / you', '20 minutes.'], ['It', 'takes', 'him / her', '1 hour.'], ['It', 'may / might take', 'them', '5 to 8 minutes.']], src: 'Grammar 7·8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'keep', img: '16818', title: 'Picture Talk', q: 'How do they go to work?', a: 'They go to work by ___.', chips: ['train', 'subway'], src: '9쪽', nt: '기차' },
      { t: 'qa', k: 'keep', img: '12354', title: 'Picture Talk', q: 'How does he go to work?', a: 'He takes the ___ to work.', src: '10쪽', nt: '버스' },
      { t: 'qa', k: 'fix', img: '18020', label: 'police officer', title: 'How does he go to work?', q: '"I don\'t drive my police car to work."', a: 'I go to work by ___.', chips: ['train', 'car'], src: '11쪽', nt: '경찰관', n: ['원본은 한 문장에 빈칸 둘 → 앞 문장은 말풍선으로 주고 빈칸 하나'] },
      { t: 'qa', k: 'fix', img: '16072', label: 'hairdresser', title: 'How does she go?', q: 'How do you go to work?', a: 'I may take a ___ or a ___ to work.', chips: ['taxi', 'bus'], src: '12쪽', nt: '미용사 — may', n: ['<del>I may ride a ___ or ___</del> → take a taxi or a bus'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-motorcycle', label: 'librarian', title: 'How does she go?', q: 'How do you go to work?', a: 'I might ride my ___ today!', src: '13쪽', nt: '❗ 사서 — ride', n: ['<del>I might drive the motorcycle</del> → ride(오토바이는 ride)', '책을 싣고 오토바이를 타는 사서 — 웃음 포인트'] },
      { t: 'qa', k: 'keep', img: '12606', label: 'banker', title: 'How does she go?', q: 'How do you go to work?', a: 'I might drive my ___ today.', src: '14쪽', nt: '은행원 — might' },
      { t: 'qa', k: 'fix', img: '18837', label: 'chef', title: 'What time?', q: 'I walk to work at 8:15 a.m. It takes me 20 minutes.', a: 'I get there at ___ a.m.', chips: ['8:35', '8:20'], src: '15쪽', nt: '요리사 — 시간 계산', n: ['8:15 + 20분 = 8:35 — 손가락으로 세어 보게 합니다'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-waitress', label: 'waitress · 5–8 min', title: 'How does she go?', q: 'How does she go to work?', a: 'She ___ the bus to work. It might take her 5 to 8 minutes.', src: '16쪽', nt: '종업원 — 버스' },
      { t: 'qa', k: 'fix', img: '15763', label: 'waiter · 10–15 min', title: 'How does he go?', q: 'How does he go to work?', a: 'He ___ a taxi to work. It might take him 10 to 15 minutes.', src: '17쪽', nt: '종업원 — 택시', n: ['<del>He ___ taxi</del> → takes a taxi'] },
      { t: 'qa', k: 'fix', img: '16121', label: 'clerk · 10–15 min', title: 'How does she go?', q: 'How does she go to work?', a: 'She ___ her bike to work. It might take her 10 to 15 minutes.', src: '18쪽', nt: '점원 — 자전거', n: ['원본은 여자 사진에 He → She · <del>___ bike</del> → rides her bike'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-scooter-baker', label: 'baker · ⏱ 15 min', title: 'How does she go?', q: 'How does she go to work? How long does it take?', a: 'She rides a ___. It takes her ___ minutes.', src: '20쪽', nt: '제빵사 — 스쿠터', n: ['원본 «00:15» 타이머 → 사진 이름표로'] },
      { t: 'story', k: 'new', img: 'c5033', title: 'Mango is late!', lines: [['Mango', "Oh no! I'm late for school!"], ['Teacher', 'How do you go to school, Mango?'], ['Mango', 'I walk. It takes me 30 minutes!'], ['Teacher', 'You might take the bus next time!']], nt: '이야기', n: ['이 과 문장으로 짧은 이야기를 만들었습니다 — Mango 역은 학생이', '«How long does it take you?» 를 학생이 강사에게 되물어 봅니다'] },
      { t: 'ox', k: 'new', img: 'gen:bts-12-scooter-baker', s: 'She drives a car to work.', nt: '⭕❌', n: ['정답 ❌ → «No! She rides a scooter.»'] },
      { t: 'guess', k: 'new', img: '19259', open: [1, 7], q: 'How does he go to work?', chips: ['He takes the subway.', 'It might take him 20 minutes.'], nt: 'Guess', n: ['맞힌 뒤 «How long might it take him?» 까지 짐작해서 말하기'] },
      { t: 'order', k: 'new', img: '12354', words: ['takes', 'It', 'him', '10 minutes'], nt: '순서 맞추기', n: ['정답: It takes him 10 minutes.'] },
      { t: 'yourturn', k: 'new', img: '12071', title: 'How do you go to school?', lines: ['I ___ to school.', 'It takes me ___ minutes.', 'Sometimes I might ___.'], chips: ['walk', 'take the bus', 'ride my bike'], nt: '내 이야기' },
      ...close([['I can say how people go to work.', 'She rides her bike to work.'], ['I can say "It takes me 20 minutes."', 'It takes me 10 minutes.'], ['I can guess with "might".', 'It might take him 15 minutes.']], { img: 'gen:bts-12-father-car', q: 'How does your father go to work?', ko: '우리 아빠는 어떻게 출근할까요? (006)' }),
    ] },
  // ───────────────────────── 006
  { code: '006', tab: '우리 가족 출근길', unit: U2, title: 'Going to Work', orig: 15,
    intro: '우리 가족이 몇 시에, 무엇을 타고, 얼마나 걸려 가는지 말합니다. 이야기: Jane 이 아빠·엄마·자기의 아침을 소개합니다.',
    fixed: ['«I think, it may take her…» 쉼표 → I think it may take her…', '바늘 없는 시계 그림 → 시각이 보이는 시계', '«5-8 minutes» → 5 to 8 minutes(읽는 대로)', '원본에 낱말표가 없음(004 낱말 사용) → 떠올리기 표로', '나를 소개하는 빈 쪽(«I\'m a ___. I go to ___ by ___.») → 틀 문장으로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-12-father-car', q: 'How does your family go to work?', story: "Good morning! Let's meet Jane's family.", nt: '표지 + Big Question' },
      ...open([["I can talk about my parents' jobs.", '부모님 직업을 말해요.'], ['I can say what time they go.', '몇 시에 가는지 말해요 — at 8:00 a.m.'], ['I can say how long it takes.', 'It takes him 15 minutes.']]),
      USONG_2,
      { t: 'story', k: 'fix', img: 'gen:bts-12-father-car', title: "Jane's father", lines: [['Teacher', "What is your father's job?"], ['Jane', 'My father is an office worker.'], ['Jane', 'He always drives his car to work at 8:00 a.m. It takes him 15 minutes.']], src: '9쪽', nt: '이야기 ① 아빠', n: ['원본은 «I» 가 말하는 쪽 → 인물 Jane 으로 이야기처럼'] },
      { t: 'story', k: 'fix', img: 'gen:bts-12-mother-bus', title: "Jane's mother", lines: [['Teacher', 'What about your mother?'], ['Jane', 'My mother is a teacher. She takes the bus to work at 8:10 a.m.'], ['Jane', 'I think it may take her 5 to 10 minutes.']], src: '10쪽', nt: '이야기 ② 엄마', n: ['<del>I think, it may</del> → I think it may'] },
      { t: 'story', k: 'fix', img: '12071', title: 'And Jane?', lines: [['Teacher', 'What about you?'], ['Jane', "Well, I'm a student. I walk to school at 8:40 a.m."], ['Jane', 'It takes me 5 to 8 minutes.']], src: '11쪽', nt: '이야기 ③ 나' },
      { t: 'qa', k: 'fix', img: '12010', title: 'What time is it?', q: "What time does Jane's father go to work?", a: 'He goes to work at ___ a.m.', chips: ['8:00', '8:10', '8:40'], src: '9쪽', nt: '시계 읽기', n: ['원본 시계는 바늘이 없었음 → 바늘이 보이는 시계, 시각은 이야기에서 찾기'] },
      { t: 'fill', k: 'new', title: 'Questions', lines: ["Jane's father goes to work by ___.", 'It takes him ___ minutes.', "Jane's mother ___ the bus.", 'Jane walks to ___.'], chips: ['car', '15', 'takes', 'school'], nt: '이야기 질문' },
      { t: 'ox', k: 'new', img: '12071', s: 'Jane takes the bus to school.', nt: '⭕❌', n: ['정답 ❌ → «No! She walks to school.»'] },
      { t: 'guess', k: 'new', img: '15243', open: [0, 4], q: 'Who is he? How does he go to work?', chips: ['Is he an office worker?', 'Does he walk to work?'], nt: 'Guess who' },
      { t: 'match', k: 'new', title: 'How do they go?', left: ['c7191', '12354', '12071', '16121'], right: ['walks', 'rides a bike', 'drives a car', 'takes the bus'], nt: '짝 맞추기', n: ['짝마다 «It might take him/her … minutes.» 를 덧붙이면 보너스'] },
      { t: 'yourturn', k: 'fix', img: '12080', title: 'My father', lines: ['My father is a ___.', 'He goes to work by ___ at ___.', 'It may take him ___ minutes.'], src: '12쪽', nt: '내 이야기 ① 아빠' },
      { t: 'yourturn', k: 'fix', img: '12167', title: 'My mother', lines: ['My mother is a ___.', 'She goes to work by ___ at ___.', 'It may take her ___ minutes.'], src: '13쪽', nt: '내 이야기 ② 엄마' },
      { t: 'yourturn', k: 'fix', img: '16456', title: 'And you?', lines: ["I'm a ___.", 'I go to ___ by ___.', 'It takes me ___ minutes.'], chips: ['student', 'school', 'bus', 'on foot'], src: '14쪽', nt: '내 이야기 ③ 나', n: ['걸어가면 «I walk to school» — by 없이'] },
      ...close([["I can talk about my parents' jobs.", 'My mother is a teacher.'], ['I can say what time they go.', 'He goes to work at 8:00 a.m.'], ['I can say how long it takes.', 'It takes her 10 minutes.']], { img: '12388', q: 'What do you want to be in the future?', ko: '커서 무엇이 되고 싶나요? (007 I want to be)' }),
    ] },
  // ───────────────────────── 007
  { code: '007', tab: 'want to be', unit: U3, title: 'I want to be', orig: 23,
    intro: '«What do you want to be? — I want to be a doctor. Why? — I want to help sick people.» 이야기: Lily 가 이제 제빵사 말고 의사가 되고 싶대요!',
    fixed: ['«activites» 오타 → activities', '«help the sick people» → help sick people', '«Being a doctor is a good job but it is very hard» → Being a doctor is a great job, but it is very difficult(새 낱말 difficult 를 쓰도록)', '<b>Hannah «I\'m not going to be a police officer, either…»</b> — Hannah 는 경찰관이 되겠다고 한 적이 없음 → 문장 뺌', '«Sport stars» → sports stars · «What is their job?» → What are their jobs?', '«You can see me in movies» (배우 두 명) → see us'],
    slides: [
      { t: 'cover', k: 'new', img: '18570', q: 'What do you want to be in the future?', story: 'Lily has big news for Hannah!', nt: '표지 + Big Question', n: ['요리사 모자·의사 가운·소방관 헬멧을 차례로 써 보는 학생 — 나는 무엇을 써 볼까?'] },
      ...open([['I can say "I want to be a doctor."', '커서 되고 싶은 것을 말해요.'], ['I can ask "Why?"', '왜 그 직업이 되고 싶은지 물어요.'], ['I can name more jobs.', 'doctor, nurse, scientist, singer, actor …']]),
      { t: 'song', k: 'fix', title: 'Jobs Song', lines: JOBS, img: '18672', src: 'Goodbye Song 자리의 Jobs song', nt: '직업 노래', n: ['<del>I will make you get better</del> → help you get better', '화면에 맞게 5줄로 — teacher 절(«Let\'s learn something fun!»)과 soccer player 절(«Let\'s shoot the ball!»)은 강사가 이어 부릅니다 · «I want to be» 는 강사가 앞에서 부르고 학생이 직업을 외치는 메아리로', '원본은 과 끝에 부름 → want to be 를 배우는 이 과에서 먼저 불러 문장을 귀에 익힘'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Jobs & places 🔒', words: [['hospital', '병원', '17106'], ['doctor', '의사', '12381'], ['nurse', '간호사', '13134'], ['scientist', '과학자', '12502'], ['singer', '가수', '16261'], ['actor', '배우', '12540'], ['actress', '(여자) 배우', 'gen:bts-12-actress'], ['sports star', '스포츠 스타', '16215']], src: 'Vocabulary 6쪽', nt: '낱말 — 가림', n: ['<del>여배우</del> → (여자) 배우'] },
      { t: 'vocab', k: 'keep', title: 'Jobs & places', words: [['hospital', '병원', '17106'], ['doctor', '의사', '12381'], ['nurse', '간호사', '13134'], ['scientist', '과학자', '12502'], ['singer', '가수', '16261'], ['actor', '배우', '12540'], ['actress', '(여자) 배우', 'gen:bts-12-actress'], ['sports star', '스포츠 스타', '16215']], nt: '낱말 — 공개' },
      { t: 'rule', k: 'new', title: 'want or wants?', left: { h: 'I / you / they', ex: ['I **want** to be a nurse.', 'They **want** to be singers.'] }, right: { h: 'he / she', ex: ['He **wants** to be a doctor.', 'She **wants** to be an actress.'] }, q: 'Do you see the "-s" again?', nt: '규칙 찾기', n: ['works · needs 에 이어 세 번째 «-s» — 학생이 먼저 알아채게'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'What do you want to be?', head: ['question', 'answer'], rows: [['What do you want to be?', 'I want to be a doctor.'], ['What does she want to be?', 'She wants to be a singer.'], ['Why do you want to be a doctor?', 'I want to help sick people.']], src: 'Grammar 7·8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'keep', img: '12388', title: 'Your dream', q: 'What do you want to be in the future?', a: 'I want to be a ___.', src: '9쪽', nt: '장래 희망', n: ['원본 무지개 가발 진행자 사진 → 우주비행사 헬멧을 쓴 아이'] },
      { t: 'qa', k: 'keep', img: '14086', title: 'Where are they?', q: 'Where are they?', a: 'They are in the ___.', src: '10쪽', nt: '병원' },
      { t: 'qa', k: 'keep', img: '12188', title: 'Who works in the hospital?', q: 'What do you do?', a: 'I am a ___. I help sick people.', src: '11쪽', nt: '의사' },
      { t: 'qa', k: 'keep', img: 'c7066', title: 'Who works in the hospital?', q: 'What do you do?', a: 'I am a ___. I help the doctor.', src: '11쪽', nt: '간호사' },
      { t: 'qa', k: 'fix', img: '12315', title: 'What is my job?', q: 'What do I do?', a: 'I am a ___. I do experiments.', src: '12쪽', nt: '과학자', n: ['기뻐서 두 팔을 번쩍 든 과학자 — «실험이 성공했나 봐!»'] },
      { t: 'qa', k: 'keep', img: '16261', title: 'What is her job?', q: 'Do you like to sing?', a: 'I am a ___. I love to sing!', src: '13쪽', nt: '가수' },
      { t: 'qa', k: 'fix', img: '16830', title: 'What are their jobs?', q: 'Where can you see them?', a: 'We are ___. You can see us in movies and on TV.', src: '14쪽', nt: '배우들', n: ['<del>You can see me</del> → see us(두 명)'] },
      { t: 'qa', k: 'fix', img: '16208', title: 'What is my job?', q: 'What do I play?', a: 'I am a sports ___. I play ___.', chips: ['star', 'soccer', 'baseball'], src: '15쪽', nt: '스포츠 스타', n: ['<del>Sport stars</del> → sports stars'] },
      { t: 'vocab', k: 'keep', title: 'New words', words: [['sick', '아픈', '12260'], ['librarian', '사서', '12063'], ['difficult', '어려운', '18527']], src: '18쪽 New Words', nt: '이야기 낱말' },
      { t: 'story', k: 'fix', img: 'gen:bts-12-hannah-lily', title: 'Lily and Hannah ①', lines: [['Lily', "Hey, Hannah! Guess what? I don't want to be a baker anymore!"], ['Hannah', 'Really? Why not?'], ['Lily', 'I want to be a doctor. I want to help sick people.']], src: '19쪽 Role-play', nt: '이야기 ①', n: ['001 에서 Lily 는 제빵사가 되고 싶었죠? — 먼저 물어봅니다', '<del>help the sick people</del> → help sick people'] },
      { t: 'story', k: 'fix', img: '12381', title: 'Lily and Hannah ②', lines: [['Hannah', 'Being a doctor is a great job, but it is very difficult. Can you do it?'], ['Lily', 'Of course! I am going to work hard and study a lot!']], src: '20쪽', nt: '이야기 ②', n: ['<del>a good job but it is very hard</del> → a great job, but it is very difficult'] },
      { t: 'story', k: 'fix', img: '19310', title: 'Lily and Hannah ③', lines: [['Hannah', 'I want to be a librarian.'], ['Lily', 'Why do you want to be a librarian?'], ['Hannah', 'Well, I think it is going to be fun. I like books!']], src: '20쪽', nt: '이야기 ③', n: ['<del>I\'m not going to be a police officer, either…</del> → Hannah 는 경찰관 이야기를 한 적이 없어 뺐습니다'] },
      { t: 'fill', k: 'keep', title: 'Questions', lines: ['What does Lily want to be now? — She wants to be a ___.', 'Why? — She wants to help ___ people.', 'What does Hannah want to be? — She wants to be a ___.', 'Why? — She likes ___.'], chips: ['doctor', 'sick', 'librarian', 'books'], src: '21쪽', nt: '이야기 질문' },
      { t: 'ox', k: 'new', img: 'gen:bts-12-hannah-lily', s: 'Lily wants to be a baker now.', nt: '⭕❌', n: ['정답 ❌ → «No! She wants to be a doctor now.»'] },
      { t: 'guess', k: 'new', img: '12540', open: [1, 6], q: 'What is the job?', chips: ['Is it a singer?', 'Is it an actor?'], nt: 'Guess who', n: ['무대 의상이 조금씩 보일 때마다 «Is it a/an …?» 으로 묻기 — a/an 연습'] },
      { t: 'yourturn', k: 'new', img: '18611', title: 'My dream', lines: ['I want to be a ___.', 'I want to ___.'], chips: ['help people', 'sing', 'play soccer', 'do experiments'], nt: '내 이야기', n: ['«Why?» 를 강사가 꼭 묻고 학생이 둘째 줄로 답합니다'] },
      ...close([['I can say "I want to be a doctor."', 'I want to be a scientist.'], ['I can ask "Why?"', 'Why do you want to be a singer?'], ['I can name more jobs.', 'nurse, actor, sports star …']], { img: '19905', q: 'What does she like to do?', ko: '이 아이는 무엇을 좋아할까요? (008)' }),
    ] },
  // ───────────────────────── 008
  { code: '008', tab: 'like to', unit: U3, title: 'I want to be', orig: 22,
    intro: '«I like to draw and paint. I want to be an artist.» 좋아하는 것과 장래 희망을 잇습니다. «I don\'t want to be a writer.»',
    fixed: ['<b>portray «그리다»</b> — 뜻이 틀림(연기하다) → 학생 문장은 쉬운 «play a character»', '«What are their job?» → What are their jobs?', '«I play guitar. I play violin.» → the guitar · the violin', '원본 우는 아이(도서관) 사진 → 글쓰기를 싫어하는 아이의 밝은 사진', '«I like to draw and paint ___» 빈칸 자리 → 직업 빈칸으로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-12-paint-toddler', q: 'What do you like to do?', story: 'What you like can be your job one day!', nt: '표지 + Big Question', n: ['물감 범벅이 된 아이 — «이 아이는 무엇을 좋아할까?»'] },
      ...open([['I can say "I like to draw."', '좋아하는 것을 like to 로 말해요.'], ['I can say "I want to be an artist."', 'a / an 을 알맞게 붙여요.'], ["I can say what I don't want to be.", "I don't want to be a writer."]]),
      { t: 'vocab', k: 'fix', hide: true, title: 'Jobs 🔒', words: [['artist', '화가·예술가', '12783'], ['musician', '음악가', '12656'], ['writer', '작가', '12741'], ['actress', '(여자) 배우', 'gen:bts-12-actress'], ['character', '등장인물', '18655'], ['play (a role)', '연기하다', 'c7183'], ['scientist', '과학자', 'c5034'], ['sports star', '스포츠 스타', '15516']], src: 'Vocabulary 6쪽', nt: '낱말 — 가림', n: ['<del>portray 그리다</del> → 뜻이 틀림 · 학생 문장은 «play a character(인물을 연기하다)»', '<del>캐릭터</del> → 등장인물'] },
      { t: 'vocab', k: 'keep', title: 'Jobs', words: [['artist', '화가·예술가', '12783'], ['musician', '음악가', '12656'], ['writer', '작가', '12741'], ['actress', '(여자) 배우', 'gen:bts-12-actress'], ['character', '등장인물', '18655'], ['play (a role)', '연기하다', 'c7183'], ['scientist', '과학자', 'c5034'], ['sports star', '스포츠 스타', '15516']], nt: '낱말 — 공개' },
      { t: 'rule', k: 'new', title: 'a or an?', left: { h: 'a', ex: ['a **s**inger', 'a **ch**ef', 'a **w**riter'] }, right: { h: 'an', ex: ['an **a**rtist', 'an **a**ctor', 'an **a**ctress'] }, q: 'When do we say "an"?', nt: '규칙 찾기', n: ['a·e·i·o·u 소리로 시작하면 an — 학생이 먼저 찾게'] },
      { t: 'qa', k: 'fix', img: '12783', title: 'What is my job?', q: 'What do I do?', a: "I'm an ___. I draw and paint pictures. My job is fun!", src: '9쪽', nt: '화가' },
      { t: 'qa', k: 'fix', img: '12470', title: 'What are their jobs?', q: 'What do they play?', a: 'We are ___. I play the guitar. I play the violin.', src: '10쪽', nt: '음악가들', n: ['<del>What are their job?</del> → jobs · <del>play guitar</del> → the guitar'] },
      { t: 'qa', k: 'keep', img: '14760', title: 'What is her job?', q: 'What does she do?', a: "I'm a ___. I write books and stories. I like my job.", src: '11쪽', nt: '작가' },
      { t: 'qa', k: 'keep', img: 'gen:bts-12-hairbrush-singer', title: 'What does she want to be?', q: 'What does she like to do?', a: 'I like to sing! I want to be a ___.', src: '12쪽', nt: '가수가 되고 싶어', n: ['빗을 마이크처럼 쥐고 노래하는 아이 — 따라 해 보기'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-12-kid-chef', title: 'What does he want to be?', q: 'What does he like to do?', a: 'I like to cook food! I want to be a ___.', src: '13쪽', nt: '요리사가 되고 싶어' },
      { t: 'qa', k: 'fix', img: '17033', title: 'What does she want to be?', q: 'What does she like to do?', a: 'I like to draw and paint. I want to be an ___.', src: '14쪽', nt: '화가가 되고 싶어', n: ['원본은 빈칸이 둘(무엇을 그리나 + 직업) → 직업 하나로'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-kid-actress', title: 'What does she want to be?', q: 'What does she like to do?', a: 'I like to play a character. I want to be an ___.', src: '15쪽', nt: '배우가 되고 싶어', n: ['<del>I like to portray a character</del> → play a character'] },
      { t: 'qa', k: 'fix', img: '17179', title: 'What does he want to be?', q: 'What does he like to do?', a: 'I like to play the ___. I want to be a ___.', chips: ['guitar', 'musician'], src: '16쪽', nt: '음악가가 되고 싶어' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-no-writing', title: 'Does he want to be a writer?', q: 'What does he say?', a: "I don't like to write stories. I don't want to be a ___.", src: '17쪽', nt: '되고 싶지 않아', n: ['원본은 도서관에서 우는 아이 → 텅 빈 공책 앞에서 고개를 젓는 아이(밝게)'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-12-kids-lab', title: 'What do they want to be?', q: 'What do they like to do?', a: 'We like to do science experiments. We want to be ___.', src: '18쪽', nt: '과학자가 되고 싶어' },
      { t: 'qa', k: 'keep', img: '15516', title: 'What does she want to be?', q: 'What does she like to do?', a: 'I like to ___. I want to be a sports star.', chips: ['play soccer', 'sing'], src: '19쪽', nt: '스포츠 스타' },
      { t: 'story', k: 'new', img: '14998', title: 'Talent show day!', lines: [['Teacher', 'Sam, what do you like to do?'], ['Sam', 'I like to draw and paint!'], ['Teacher', 'Do you still want to be a police officer?'], ['Sam', 'Hmm... I want to be an artist now!']], nt: '이야기', n: ['001 에서 경찰관이 되고 싶던 Sam — 꿈은 바뀌어도 괜찮다는 이야기', '원본에는 없는 새 대사입니다(사람이 정할 것)'] },
      { t: 'ox', k: 'new', img: 'gen:bts-12-no-writing', s: 'He likes to write stories.', nt: '⭕❌', n: ["정답 ❌ → «No! He doesn't like to write stories.»"] },
      { t: 'guess', k: 'new', img: '15160', open: [0, 8], q: 'What does this child like to do?', chips: ['Does she like to paint?', 'Does she like to sing?'], nt: 'Guess', n: ['타일마다 «Does she like to …?» — 009 의 Does 질문을 미리 맛봅니다'] },
      { t: 'match', k: 'new', title: 'Who is it?', left: ['12783', '12656', '14760', '16261'], right: ['writer', 'singer', 'artist', 'musician'], nt: '짝 맞추기' },
      { t: 'yourturn', k: 'fix', img: '18672', title: 'Do you want to be …?', lines: ['Do you want to be a / an ___?', "Yes, I do. / No, I don't.", 'Why? / Why not?'], chips: ['artist', 'musician', 'writer', 'singer', 'chef', 'actor', 'scientist', 'sports star'], src: '20·21쪽 GAME', nt: '게임 — 서로 묻기', n: ['강사와 학생이 번갈아 묻습니다. «Why not?» 에는 «I don\'t like to …» 로 답하기'] },
      ...close([['I can say "I like to draw."', 'I like to cook.'], ['I can say "I want to be an artist."', 'I want to be an actor.'], ["I can say what I don't want to be.", "I don't want to be a writer."]], { img: 'gen:bts-12-kids-band', q: 'What can they do?', ko: '이 친구들은 무엇을 할 수 있을까요? (009)' }),
    ] },
  // ───────────────────────── 009
  { code: '009', tab: 'Do you want to be?', unit: U3, title: 'I want to be', orig: 23,
    intro: '«Does she want to be a chef? — No, she doesn\'t. She wants to be a dancer.» «I want to be a singer because I love music.»',
    fixed: ['<b>원본 9·18~21쪽 무서운 얼굴 페인트 판토마임 사진 4쪽</b> → 밝은 사진으로', '«We can play piano and guitar» → the piano and the guitar', '문법 표 «Yes, + I want to be» 짝이 어긋남 → Yes, I do. / No, she doesn\'t.', '✓✗ 표시만 있고 답 문장이 없던 쪽 → 답 틀 추가', 'dancer «춤추는 사람» → 무용수'],
    slides: [
      { t: 'cover', k: 'new', img: '18672', q: 'What can you do? What do you want to be?', story: "It's your turn to dream big!", nt: '표지 + Big Question' },
      ...open([['I can ask "Do you want to be …?"', '«~가 되고 싶어?» 를 물어요.'], ["I can answer \"No, she doesn't.\"", '아니라고 답하고 바르게 고쳐 말해요.'], ['I can say why with "because".', 'because 로 이유를 말해요.']]),
      { t: 'vocab', k: 'fix', hide: true, title: 'Jobs 🔒', words: [['artist', '화가', '16041'], ['police officer', '경찰관', '18020'], ['musician', '음악가', '12486'], ['singer', '가수', 'c7211'], ['dancer', '무용수', '16073'], ['doctor', '의사', '10010']], src: 'Vocabulary 6쪽', nt: '낱말 — 가림', n: ['<del>춤추는 사람</del> → 무용수'] },
      { t: 'vocab', k: 'keep', title: 'Jobs', words: [['artist', '화가', '16041'], ['police officer', '경찰관', '18020'], ['musician', '음악가', '12486'], ['singer', '가수', 'c7211'], ['dancer', '무용수', '16073'], ['doctor', '의사', '10010']], nt: '낱말 — 공개' },
      { t: 'rule', k: 'fix', title: 'Yes or no?', left: { h: 'Yes', ex: ['Does she want to be a doctor?', '→ **Yes, she does.**'] }, right: { h: 'No', ex: ['Does he want to be a chef?', "→ **No, he doesn't.**", 'He wants to be a firefighter.'] }, q: 'After "No", what do we say next?', src: 'Grammar 7·8쪽', nt: '규칙 찾기', n: ['원본 표는 «Yes, + I want to be» 로 짝이 어긋남 → Yes, she does.'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'Do you want to be a chef?', head: ['question', 'yes', 'no'], rows: [['Do you want to be a chef?', 'Yes, I do.', "No, I don't."], ['Does she want to be a chef?', 'Yes, she does.', "No, she doesn't."], ['Do they want to be artists?', 'Yes, they do.', "No, they don't."]], tip: 'he / she → Does … ? · doesn\'t', nt: '문장 틀' },
      { t: 'qa', k: 'fix', img: '16271', title: 'Your turn!', q: 'What do you like to do?', a: 'I like to ___. I want to be an ___.', chips: ['draw', 'artist'], src: '9·10쪽', nt: '좋아하는 것 → 꿈', n: ['원본 9쪽 판토마임 사진 → 그림 그리는 아이'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-12-kid-police-run', title: 'What can you do?', q: 'What do you want to be?', a: 'I can run fast. I want to be a ___. I want to catch thieves.', src: '11쪽', nt: '경찰관', n: ['001 의 catch thieves 가 다시 나옵니다'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-kids-band', title: 'What can they do?', q: 'What do they want to be?', a: 'We can play the piano and the guitar. We want to be ___.', src: '12쪽', nt: '음악가', n: ['<del>play piano and guitar</del> → the piano and the guitar'] },
      { t: 'qa', k: 'keep', img: '18531', title: 'What can she do?', q: 'What does she want to be?', a: 'She can ___. She wants to be a ___.', chips: ['sing', 'singer'], src: '13쪽', nt: '가수' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-dancer-girl', title: 'Does she want to be a chef?', q: 'Does she want to be a chef?', a: "No, she doesn't. She wants to be a ___.", src: '14쪽', nt: '무용수', n: ['원본은 ✓✗ 표시만 → 답 문장 틀'] },
      { t: 'qa', k: 'fix', img: '18427', title: 'Does he want to be a firefighter?', q: 'Does he want to be a firefighter?', a: "No, he ___. He wants to be a police ___.", chips: ["doesn't", 'officer'], src: '15쪽', nt: '경찰관', n: ['돋보기로 발자국을 찾는 꼬마 탐정 — «경찰관이 되고 싶어!»'] },
      { t: 'qa', k: 'fix', img: '14086', title: 'Does she like to help people?', q: 'What does she want to be?', a: 'Yes, she ___. She wants to be a ___.', chips: ['does', 'doctor', 'nurse'], src: '16쪽', nt: '의사·간호사', n: ['아이 무릎에 밴드를 붙여 주는 사진 — doctor 도 nurse 도 정답으로 인정'] },
      { t: 'qa', k: 'keep', img: '16041', title: 'Do they like to draw and paint?', q: 'What do they want to be?', a: 'Yes, they ___. They want to be ___.', chips: ['do', 'artists'], src: '17쪽', nt: '화가들' },
      { t: 'story', k: 'new', img: '14998', title: 'Show and Tell', lines: [['Teacher', 'Jane, what can you do?'], ['Jane', 'I can sing and dance!'], ['Teacher', 'What do you want to be?'], ['Jane', 'I want to be a singer because I love music!']], nt: '이야기', n: ['because 를 처음 쓰는 쪽 — 이유를 한 번에 말하는 법', '역할을 바꿔 학생이 Jane 이 되어 자기 이야기로 바꿉니다'] },
      { t: 'ox', k: 'new', img: '16041', s: 'They want to be doctors.', nt: '⭕❌', n: ["정답 ❌ → «No, they don't. They want to be artists.»"] },
      { t: 'guess', k: 'new', img: '18611', open: [0, 5], q: 'What does he want to be?', chips: ['Does he want to be a pilot?', 'Does he want to be a chef?'], nt: 'Guess who', n: ['Does he …? 로 물어야 타일이 열립니다'] },
      { t: 'memory', k: 'new', items: ['12783', '12656', '16261', '16073', '12381', '13184'], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ① 보기' },
      { t: 'memory', k: 'new', hidden: true, items: ['12783', '12656', '16261', '16073', '12381', '13184'], q: 'Which jobs are hiding?', a: 'I remember a ___ and a ___.', nt: '기억 게임 ② 말하기', n: ['기억한 직업마다 «Do you want to be a …?» 를 강사가 되묻습니다'] },
      { t: 'yourturn', k: 'fix', img: 'gen:bts-12-megaphone-host', title: 'Your turn! ①', lines: ['What can you do? — I can ___.', 'What do you like to do? — I like to ___.'], src: '18·19쪽', nt: '내 이야기 ①', n: ['원본 판토마임 사진 쪽 → 밝은 진행자 사진'] },
      { t: 'yourturn', k: 'fix', img: '12614', title: 'Your turn! ②', lines: ['I want to be a ___ because ___.', "I don't want to be a ___ because ___."], chips: ['I like to …', 'I love …', "I don't like to …"], src: '20·21쪽', nt: '내 이야기 ②' },
      ...close([['I can ask "Do you want to be …?"', 'Does he want to be a chef?'], ["I can answer \"No, she doesn't.\"", "No, she doesn't. She wants to be a dancer."], ['I can say why with "because".', 'I want to be a vet because I love animals.']], { img: 'gen:bts-12-review-cover', q: 'Are you ready for the big review?', ko: '직업 박사가 될 준비 됐나요? (REVIEW)' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 12 Review', orig: 33,
    intro: 'BTS 12 전체 복습. 직업·도구·출근길·꿈 네 스테이지를 깨고 보스 문제로 끝냅니다.',
    fixed: ['원본은 각 과 쪽을 그대로 다시 붙인 모음(같은 사진 반복) → 스테이지마다 낱말 떠올리기 + 다른 사진', '원본에 있던 «This is our mail truck» 말풍선 문제 · «I might drive the motorcycle» 가 그대로 반복 → 고친 문장으로', '판토마임 사진 쪽 → 밝은 사진으로', '«What is their job?» → What are their jobs?'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-12-review-cover', q: 'How many jobs do you know now?', story: '4 stages + a boss. Can you clear them all? ⭐', nt: '표지' },
      { t: 'song', k: 'fix', title: 'ABC Job Song (A–M)', lines: ABC1, img: '12566', src: 'Warm-up', nt: '알파벳 노래로 시작', n: ['학생이 직업을 외치고 강사가 글자를 부르는 순서로 바꿔도 좋습니다'] },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 1 · Jobs 🔒', words: [['police officer', '경찰관', '13141'], ['firefighter', '소방관', '12018'], ['mail carrier', '우체부', '18364'], ['banker', '은행원', '18139'], ['hairdresser', '미용사', '16056'], ['baker', '제빵사', '15743'], ['teacher', '선생님', '14396'], ['office worker', '회사원', '12282']], nt: '1단계 — 직업 떠올리기' },
      { t: 'qa', k: 'fix', img: '13141', title: 'Who are they?', q: 'Where do they work?', a: 'They are ___. They work at the ___.', src: '6쪽', nt: '001 경찰관' },
      { t: 'qa', k: 'keep', img: '14753', title: 'Who is he?', q: 'Where does he work?', a: 'He is a ___. He works at the ___.', src: '8쪽', nt: '001 우체부' },
      { t: 'qa', k: 'keep', img: '20177', title: 'What do they need?', q: 'What do firefighters need?', a: 'They need a ___, an ___ and a ___.', src: '11쪽', nt: '002 도구' },
      { t: 'qa', k: 'fix', img: '12587', title: 'What do they use?', q: 'What do office workers use?', a: 'They use ___.', src: '13쪽', nt: '002 쓰는 것' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-police-car', title: 'Whose car is this?', q: '"This is my police car."', a: "It's ___ police car.", src: '15쪽', nt: '002 누구의' },
      { t: 'qa', k: 'keep', img: '15763', title: 'Whose taxi is this?', q: 'He is a taxi driver.', a: "It's ___ taxi.", src: '17쪽', nt: '002 누구의' },
      { t: 'yourturn', k: 'fix', img: 'gen:bts-12-donna', title: 'Stage 2 · Talk about her! (Donna · 30)', lines: ['Her name is ___.', 'She is a ___.', 'She needs a ___ and handcuffs.', 'She drives a ___.'], src: '18쪽', nt: '2단계 — 003 사람 소개' },
      { t: 'yourturn', k: 'fix', img: 'gen:bts-12-luna', title: 'Talk about her! (Luna · 27)', lines: ['Her name is ___.', 'She is a ___.', 'She needs a ___.'], src: '20쪽', nt: '003 사람 소개' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 3 · Going to work 🔒', words: [['train', '기차', '16818'], ['motorcycle', '오토바이', 'gen:bts-12-motorcycle'], ['taxi', '택시', '15763'], ['car', '자동차', '12606'], ['bus', '버스', '16553'], ['bicycle', '자전거', '12350'], ['subway', '지하철', 'c7001']], nt: '3단계 — 탈것 떠올리기' },
      { t: 'qa', k: 'fix', img: '16351', title: 'Who works at the restaurant?', q: 'Who works at a restaurant?', a: 'A ___ and a ___ work at a restaurant.', chips: ['chef', 'waiter'], src: '21쪽', nt: '004 식당', n: ['원본 판토마임 사진 → 종업원 사진'] },
      { t: 'qa', k: 'fix', img: '16004', title: 'Where does the cashier work?', q: 'Where does the cashier work?', a: 'The cashier works at a ___.', src: '22쪽', nt: '004 가게' },
      { t: 'qa', k: 'fix', img: '18020', label: 'police officer', title: 'How does he go?', q: '"I don\'t drive my police car to work."', a: 'I go to work by ___.', src: '23쪽', nt: '005 Picture Talk' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-motorcycle', label: 'librarian', title: 'How does she go?', q: 'How do you go to work?', a: 'I might ___ my motorcycle today!', src: '24쪽', nt: '005 ride' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-waitress', label: 'waitress · 5–8 min', title: 'How does she go?', q: 'How long might it take her?', a: 'She takes the ___. It might take her ___ to ___ minutes.', src: '25쪽', nt: '005 걸리는 시간' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-father-car', title: "Jane's father", q: 'How does he go to work?', a: 'He ___ his car to work. It takes him ___ minutes.', chips: ['drives', '15'], src: '26쪽', nt: '006 우리 가족' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 4 · Dream jobs 🔒', words: [['scientist', '과학자', '12315'], ['musician', '음악가', '16717'], ['singer', '가수', '13279'], ['actress', '(여자) 배우', 'gen:bts-12-actress'], ['dancer', '무용수', '15175'], ['artist', '화가', '12783'], ['doctor', '의사', '12913'], ['writer', '작가', '16342']], nt: '4단계 — 꿈 직업 떠올리기' },
      { t: 'qa', k: 'keep', img: '12502', title: 'What is my job?', q: 'What do I do?', a: 'I am a ___. I do experiments.', src: '27쪽', nt: '007 과학자' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-kid-chef', title: 'What does he want to be?', q: 'What does he like to do?', a: 'I like to ___. I want to be a chef.', src: '29쪽', nt: '008 like to' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-kid-actress', title: 'What does she want to be?', q: 'What does she like to do?', a: 'I like to play a character. I want to be an ___.', src: '30쪽', nt: '008 an actress', n: ['<del>portray</del> → play a character'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-12-dancer-girl', title: 'Does she want to be a chef?', q: 'Does she want to be a chef?', a: "No, she ___. She wants to be a ___.", src: '31쪽', nt: '009 Does …?' },
      { t: 'story', k: 'new', img: '12021', title: 'Our friends', lines: [['Sam', 'Now I want to be an artist!'], ['Lily', 'I want to be a doctor now!'], ['Rose', 'My father is a chef. He may drive his car to work.'], ['Hannah', 'I want to be a librarian. I like books!']], nt: '이야기 모아 보기', n: ['권 전체 인물이 한 번씩 — «Who said it?» 로 맞히기', 'Sam 은 001 에서 경찰관 → 008 에서 화가로 꿈이 바뀌었죠'] },
      { t: 'ox', k: 'new', img: 'gen:bts-12-hannah-lily', s: 'Hannah wants to be a doctor.', nt: '⭕❌', n: ['정답 ❌ → «No! Lily wants to be a doctor. Hannah wants to be a librarian.»'] },
      { t: 'guess', k: 'new', img: '18570', open: [], q: 'Boss! Who is it? What does he want to be?', chips: ['Does he want to be a chef?', 'What does he need?', 'Where does he work?'], nt: '보스 문제', n: ['타일 하나 열 때마다 질문 하나 — 001~009 질문을 다 써 보게 합니다'] },
      { t: 'song', k: 'fix', title: 'Jobs Song', lines: JOBS, img: '18672', src: 'Goodbye Song 자리', nt: '직업 노래', n: ['<del>make you get better</del> → help you get better'] },
      { t: 'ican', k: 'new', items: [['I can talk about jobs and places.', 'She is a baker. She works in a bakery.'], ['I can say how people go to work.', 'He takes the bus. It takes him 10 minutes.'], ['I can talk about my dream job.', 'I want to be a scientist because I like experiments.']], nt: 'BTS 12 전체 I can' },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 12 Unit Test', orig: 15,
    intro: '10문항 단원 시험. 화상수업에서 말로 보는 시험이라 «말로 답하기» 를 기준으로 했습니다.',
    fixed: ['문항 7 «What\'s their job?» (두 명) → What are their jobs?', '문항 4·5 «00:08 / 00:10» 타이머 → 사진 이름표 «⏱ 8 minutes»', '문항 3 원본 사진(요리사 모자 + 스쿠터)의 직업이 헷갈림 → 제빵사 사진', '문항 6 성별이 불분명한 사진에 «her» → 여자 화가 사진'],
    slides: [
      { t: 'cover', k: 'new', img: '12614', q: 'Test time! You can do it! 💪', story: '10 questions · 1 point each', nt: '표지' },
      { t: 'qa', k: 'keep', img: 'gen:bts-12-hairdresser', title: '1.', q: "What's her job? Where does she work?", a: 'She is a ___. She works in a ___.', src: '문항 1', nt: '문항 1' },
      { t: 'qa', k: 'keep', img: '12018', title: '2.', q: "What's his job? What does he need?", a: 'He is a ___. He needs an ___, a ___ and a ___.', src: '문항 2', nt: '문항 2' },
      { t: 'qa', k: 'fix', img: 'gen:bts-12-scooter-baker', title: '3.', q: "What's her job? How does she go to work?", a: 'She is a ___. She rides a ___ to work.', src: '문항 3', nt: '문항 3' },
      { t: 'qa', k: 'fix', img: '16818', label: '⏱ 8 minutes', title: '4.', q: 'How do they go to work? How long might it take them?', a: 'They take the ___. It might take them ___ minutes.', src: '문항 4', nt: '문항 4' },
      { t: 'qa', k: 'fix', img: '12354', label: '⏱ 10 minutes', title: '5.', q: 'How does he go to work? How long might it take him?', a: 'He takes the ___. It might take him ___ minutes.', src: '문항 5', nt: '문항 5' },
      { t: 'qa', k: 'fix', img: '18037', title: '6.', q: "What's her job? What does she do?", a: 'She is an ___. She draws and ___ pictures.', src: '문항 6', nt: '문항 6' },
      { t: 'qa', k: 'fix', img: '12913', title: '7.', q: 'What are their jobs? What do they do?', a: 'They are ___. They help sick people.', src: '문항 7', nt: '문항 7', n: ["<del>What's their job?</del> → What are their jobs?"] },
      { t: 'match', k: 'keep', title: '8. What are their jobs?', left: ['12502', '16261', '12656'], right: ['singer', 'musician', 'scientist'], src: '문항 8', nt: '문항 8' },
      { t: 'yourturn', k: 'keep', img: '12080', title: '9.', lines: ['How do your parents go to work?', 'My mom ___. My dad ___.'], src: '문항 9', nt: '문항 9 — 자유 답' },
      { t: 'yourturn', k: 'keep', img: '12388', title: '10.', lines: ['What do you want to be in the future? Why?', 'I want to be a ___ because ___.'], src: '문항 10', nt: '문항 10 — 자유 답' },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–3', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['4–6', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['7–9', 'Great job!', 'Your turn 쪽을 한 번 더'], ['10', 'Excellent! 🎓', 'BTS 13 으로!']], src: '축하 쪽', nt: '점수 확인', n: ['원본 졸업모자 불도그 축하 쪽 → 점수와 다음 할 일'] },
      { t: 'next', k: 'new', img: 'gen:bts-12-next13', q: 'What did you do yesterday?', ko: '어제 무엇을 했나요? — 다음 책 BTS 13 «Yesterday and Today»', nt: '다음 권 예고', n: ['BTS 13 은 과거 시제(어제와 오늘) — 답은 다음 권 첫 시간에'] },
    ] },
  ],
};

// 강사 메모가 따로 없는 쪽에 쪽 종류별 기본 사용법을 채웁니다
const NOTE = {
  cover: ['사진을 보여 주고 Big Question 을 먼저 묻습니다 — 답은 과 끝에서 다시 확인'],
  vocab: ['따라 말하기 2번 → 강사가 사진을 가리키면 학생이 영어로 말하기'],
  qa: ['사진을 먼저 보고 질문 → 빈칸을 채워 문장 전체로 답하게 합니다(한 낱말 답 금지)', '맞히면 같은 틀로 학생이 강사에게 되묻기'],
  table: ['표를 위에서 아래로 메아리 읽기 → 가린 칸을 학생이 채우기'],
  match: ['짝을 맞출 때마다 그 낱말로 문장 하나 말하기'],
  yourturn: ['틀 문장으로 «내 이야기» 를 말합니다 — 빈칸은 자유롭게, 모르는 낱말은 강사가 알려 줌'],
  story: ['강사와 학생이 역할을 나눠 읽고, 두 번째는 역할을 바꿉니다'],
  fill: ['이야기를 다시 보지 않고 먼저 답해 봅니다 → 막히면 이야기 쪽으로 돌아가 확인'],
  guess: ['타일을 하나씩 열며 질문 문장으로 맞히기'],
  memory: ['5초 보여 주고 다음 쪽으로 넘깁니다'],
};
for (const l of COURSE.lessons) for (const s of l.slides) if (!s.n && NOTE[s.t]) s.n = NOTE[s.t];
