// BTS 2 새 교재 설계 데이터. k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
// 사진 번호 = scene-words/<번호>.webp · c 로 시작하면 scene-clips · gen: 은 새로 만들 사진($T/gen/req-bts-02.json)
import { open, close, HELLO } from '../common.mjs';
const USONG_2 = { t: 'song', k: 'new', small: "Let's sing! ♪ Mary Had a Little Lamb", title: "Big and Small Zoo 🦁", img: "gen:bts-02-song-big-small-zoo", nt: "동물 크기 노래(새로 지음)", n: ["곡조: Mary Had a Little Lamb (저작권 만료 곡) — 가사는 이 단원 낱말로 새로 지었습니다","big에서 두 팔을 크게 벌리고, small에서 손가락을 모으고, long에서 양손을 옆으로 쭉 뻗어요."], src: '새로 지음', lines: ["The hippo is big, big, big,","Big, big, big! Big, big, big!","The hippo is big, big, big,","And the monkeys are small!","Is the snake long? Yes, it is!","Long and thin! Long and thin!","Is it blue? No, it isn't!","The snake is long and green!"] };
const USONG_3 = { t: 'song', k: 'new', small: "Let's sing! ♪ Farmer in the Dell", title: "Is and Has Song 👦", img: "gen:bts-02-song-is-and-has", nt: "생김새 노래(새로 지음)", n: ["곡조: The Farmer in the Dell (저작권 만료 곡) — 가사는 이 단원 낱말로 새로 지었습니다","tall에서 손을 머리 위로 높이 올리고, hair에서 머리카락을, eyes에서 눈을 가리켜요."], src: '새로 지음', lines: ["He is tall, he is tall,","He has brown eyes, too!","Is he tall? Yes, he is!","He is tall, he is tall!","She has red hair, red hair,","She has red hair, red hair,","Does she have black hair? No!","She has red hair, red hair!"] };

const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3';
const SONG_NOTE = ['원본은 과마다 같은 유튜브 «Shapes Song»(QR 코드)을 틀었습니다 → 저작권·QR 문제로 화면판에서는 자체 챈트로 바꿨습니다', '손가락으로 도형을 허공에 그리며 부릅니다(원은 빙글, 세모는 꼭짓점 세 번)'];
const CHANT = ['Circle, circle, round and round.', 'Square, square, four sides, look!', 'Triangle, triangle, three sides, look!', 'Rectangle, rectangle, long and flat.', 'Heart and star, heart and star!', 'Shapes, shapes, here they are!'];

export const COURSE = {
  head: `<h1>BTS 2 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트에 올라가 있는 BTS 2 원본 <b>256쪽</b>(11묶음)을 한 장씩 읽어 원고로 옮긴 뒤, 제안서의 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · 과 끝 «I can» · 다음 시간 예고)으로 다시 짰습니다. 단원 1 도형·색깔, 단원 2 크기·모양 형용사, 단원 3 사람의 키·머리·눈 입니다. 위 단추로 과를 고르세요.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>배우는 <b>낱말·문장·문법 범위는 원본 그대로</b>입니다(도형 6 · 색 10 · 형용사 big/small/long/short/thin/thick/tall/fat · hair/eyes · has/doesn't have · Yes, it is / No, it isn't). 원본의 오타·문법 오류·어긋난 사진은 고쳤습니다(과마다 목록).</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>, <b>⭕❌</b>, <b>Guess who 타일</b>, <b>기억 게임·순서 맞추기·짝짓기</b>, <b>내 이야기 말하기</b>, <b>I can ✅</b>, <b>다음 시간 예고</b>. 등장인물은 권 전체에서 <b>윤아(Yoona)·캐런(Karen)·망고(Mango)</b> 가 이어 나오고, 원본 역할극 인물(Ben·Mr. Brodie·Sam·Mom·Mrs. Smith)은 그대로 살렸습니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>원본 007·009·REVIEW·TEST 의 <b>«fat / thin» 사진이 실제 사람의 몸(배 나온 남자·크롭탑 여자)</b>이라 아이 교재에 맞지 않아, fat/thin 은 <b>고양이·강아지</b>로 가르치도록 바꿨습니다. 점선 상자는 <b>맞는 사진이 없어 새로 만들어야 하는 자리</b>(39장)입니다. 나머지는 지금 사이트에 있는 사진으로 자리를 채웠습니다.</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>fat / thin 을 사람 대신 동물로</b> — 원본은 사람 몸으로 가르쳤습니다(배 나온 남자·크롭탑 여자 사진, 009 «Are you fat or thin?» 질문). 새 교재는 고양이·강아지로 바꾸고 학생에게 몸을 묻는 질문은 뺐습니다. 이 방향을 승인해 주세요.</li>
<li><b>«The ball is circle.» 류 고침</b> — 원본은 «be + 도형 명사»(The ball is circle / The pizza is triangle)를 가르쳤는데 영어로 틀린 문장입니다. «The ball is round.» · «It's a circle.» 로 바꿨습니다. <b>round</b> 가 새 낱말로 하나 늘어납니다.</li>
<li><b>blond / blonde 구분</b> — 원본은 009 에서야 설명하고 007·008 에서는 섞어 썼습니다. 008 첫머리로 규칙을 앞당겼습니다. 아예 blonde 하나로 통일할지 결정해 주세요.</li>
<li><b>tall · black · white · brown · gray · pink</b> — 원본 본문에 계속 나오는데 낱말표에는 없었습니다. 해당 과 낱말표에 넣었습니다(범위가 조금 늘어남).</li>
<li><b>Shapes Song</b> — 원본은 과마다 같은 유튜브 곡(QR). 자체 챈트로 바꿨습니다 — 녹음 필요.</li>
<li><b>005 원본 18쪽 누락</b> — 사이트 묶음에 Slide18 파일이 없습니다(17 다음 19). 빠진 쪽 내용을 확인해 주세요.</li>
<li><b>새로 만들 사진 39장</b> — 점선 상자 자리(힉스필드 크레딧).</li>
<li><b>새 단원 노래 2곡</b> — 노래가 없던 단원에 새로 지은 노래를 Hello Song 바로 뒤에 넣었습니다: Unit 2 «Big and Small Zoo»(Mary Had a Little Lamb) · Unit 3 «Is and Has Song»(The Farmer in the Dell). 곡조는 모두 저작권이 끝난 동요(또는 손뼉·랩 챈트)이고 가사는 그 단원 낱말로 새로 썼습니다. <b>가사 승인</b>과 <b>녹음(반주·노래)</b>이 필요합니다 — 지금은 줄마다 🔊(기계 음성)로만 들을 수 있습니다.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '도형', unit: U1, title: 'Shapes and Colors', orig: 19,
    intro: '도형 이름(circle·square·triangle·rectangle·heart·star)과 «The circle is green. / It\'s a green circle.» 두 가지 말하기를 배웁니다. 이야기: 벤의 첫 수업, 브로디 선생님이 도형을 들고 왔어요.',
    fixed: ['❗ 낱말표 square 뜻 «광장» → «정사각형»', '❗ «The ball is ___ (circle)» · «The pizza is ___ (triangle)» — be + 도형 명사는 틀린 영어 → «The ball is round.» · «It\'s a circle.»', '목표에 있는 rectangle 이 낱말표에 없었음 → 넣음 · heart-shaped «하트» → heart', 'excited 뜻 «흥분한» → «신이 난»', '«Hi , my name is» · «.Today» 띄어쓰기', '낱말표에 도형과 물건(ball·pizza·present)이 섞여 있음 → 도형 / 물건 두 쪽으로 나눔', 'General Information 쪽 때문에 쪽 번호가 하나씩 밀림(목표가 «Page 3»)'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-02-cover-shapes', q: 'What shapes can you see?', story: "It's Ben's first class. Mr. Brodie has a surprise!", nt: '표지 + Big Question', n: ['«어떤 도형이 보이니?» 로 엽니다 — 끝날 때 영어로 답하는 것이 목표', '교실에서 동그라미·네모 모양 물건을 먼저 찾아보게 해도 좋습니다'] },
      ...open([['I can name shapes.', '도형 이름을 말할 수 있어요 — circle, square, triangle.'], ['I can say "The circle is green."', '도형이 무슨 색인지 말할 수 있어요.'], ['I can say "It\'s a green circle."', '색과 도형을 한 번에 말할 수 있어요.']], 'Lesson Goals (Page 3)'),
      { t: 'vocab', k: 'fix', hide: true, title: 'Shapes 🔒', words: [['circle', '원', '18728'], ['square', '정사각형', '18729'], ['triangle', '삼각형', '16105'], ['rectangle', '직사각형', '15654'], ['heart', '하트', '12630'], ['star', '별', '17101']], src: 'Vocabulary 5쪽', nt: '도형 — 뜻 가리고 먼저 말하기', n: ['사진만 보고 영어로 먼저 말하게 합니다(인출 연습)', '<del>광장</del> → 정사각형 · rectangle 을 낱말표에 넣었습니다(목표에만 있었음)'] },
      { t: 'vocab', k: 'keep', title: 'Shapes', words: [['circle', '원', '18728'], ['square', '정사각형', '18729'], ['triangle', '삼각형', '16105'], ['rectangle', '직사각형', '15654'], ['heart', '하트', '12630'], ['star', '별', '17101']], nt: '도형 — 뜻 공개', n: ['따라 말하기 2번 → 강사가 손가락으로 허공에 그리면 학생이 이름 말하기'] },
      { t: 'vocab', k: 'fix', small: 'Vocabulary', title: 'Things', cols: 4, words: [['ball', '공', '12553'], ['pizza', '피자', '12668'], ['present', '선물', '13192'], ['balloon', '풍선', '16631']], src: 'Vocabulary 5쪽', nt: '물건 낱말', n: ['원본은 도형과 물건이 한 표에 섞여 있었음 → 따로 떼었습니다', '다음 쪽들에서 «이 물건은 무슨 모양?» 으로 씁니다'] },
      { t: 'song', k: 'new', title: 'Shape Chant', lines: CHANT, img: 'gen:bts-02-shape-song', src: 'Shapes Song', nt: '도형 챈트', n: SONG_NOTE },
      { t: 'rule', k: 'fix', title: 'Two ways to say it', left: { h: 'The ___ is + color', ex: ['The circle is **green**.', 'The car is **blue**.'] }, right: { h: 'a + color + ___', ex: ['It is a **green** circle.', 'It is a **blue** car.'] }, q: 'Where does the color go?', src: 'Grammar 6쪽', nt: '규칙 찾기 — 색의 자리', n: ['원본 «Predicative / Attributive» 용어는 강사 메모로만', '두 줄을 보고 «색이 뒤에 / 앞에» 를 학생이 먼저 찾게 합니다'] },
      { t: 'qa', k: 'fix', img: '12553', title: 'What is it?', q: 'What shape is the ball?', a: "It's a ball. The ball is ___.", chips: ['round', 'square'], src: '8쪽', nt: '❗ 공은 round', n: ['원본: «The ball is ___(circle)» — 틀린 영어 → The ball is **round**.', 'round 는 새 낱말로 한 번만 알려 줍니다'] },
      { t: 'qa', k: 'fix', img: '12668', title: 'Yummy!', q: 'What shape is the pizza?', a: "It's a ___! 🍕", src: '9쪽', nt: '❗ 모양 = It\'s a …', n: ['원본: «The pizza is ___(triangle)» + 조각 사진 → 둥근 피자 사진으로 «It\'s a circle.»', '조각을 잘라 보이면 «Now it\'s a triangle!» 까지 — 웃음 포인트'] },
      { t: 'qa', k: 'fix', img: 'c7190', title: 'Look!', q: 'What shape are they?', a: 'They are ___.', src: '10·11쪽', nt: '하트 — 여러 개', n: ['원본 선물(square)·하트 풍선 두 쪽을 하트 한 쪽으로 — 여러 개는 They are hearts.'] },
      { t: 'vocab', k: 'fix', small: 'New word', title: 'excited', cols: 1, words: [['excited', '신이 난', '12614']], src: 'Role-play New Words', nt: '이야기 낱말', n: ['<del>흥분한</del> → 신이 난', '학생이 «I\'m excited!» 를 몸으로 표현(두 팔 들고 점프)'] },
      { t: 'story', k: 'fix', img: 'gen:bts-02-ben-circle', title: "Ben's First Class", lines: [['Teacher', 'Hi, Ben! How are you?'], ['Ben', "I'm excited for the class!"], ['Teacher', "Great! Let's talk about shapes. What is it?"], ['Ben', "It's a circle!"], ['Teacher', 'What color is the circle?'], ['Ben', "It's orange. It's an orange circle!"]], src: '13·14쪽 Role-play', nt: '이야기 역할놀이', n: ['강사 = Mr. Brodie, 학생 = Ben. 두 번째는 역할을 바꿉니다', '마지막 두 줄이 오늘의 두 문장(The circle is orange. / an orange circle)'] },
      { t: 'fill', k: 'keep', title: 'Questions', lines: ["What's his name? — His name is ___.", 'What shape is it? — It is a ___.', 'What color is the circle? — The circle is ___.'], src: '15쪽', nt: '이야기 질문', n: ['앞 쪽을 다시 보지 않고 기억으로 답하기'] },
      { t: 'guess', k: 'new', img: '12364', open: [0, 4], q: 'What is it? What color is it?', chips: ["It's a ball.", 'The ball is orange.', "It's round."], nt: 'Guess it! 타일', n: ['학생이 번호를 부르면 그 칸을 엽니다(시안은 1·5번 열림)', '맞힐 때 문장으로: «It\'s an orange ball.»'] },
      { t: 'ox', k: 'new', img: '18729', s: 'It is a red triangle.', nt: '⭕❌', n: ['정답 ❌ → «No! It is a red square.» 까지 말하면 성공'] },
      { t: 'memory', k: 'new', title: 'Look for 10 seconds!', items: ['c7128', 'c7366', 'c7086', 'c7096', '12630', '17101'], q: 'Look! Say the shapes.', a: 'Then close your eyes!', nt: '기억 게임 — 보기', n: ['10초 보고 눈을 감게 합니다. 다음 쪽에서 번호로 묻습니다'] },
      { t: 'memory', k: 'new', title: 'What was it?', items: ['c7128', 'c7366', 'c7086', 'c7096', '12630', '17101'], hidden: true, q: 'Number 3 is a ___.', a: 'Number 6 is a ___.', nt: '기억 게임 — 떠올리기', n: ['강사가 번호를 부르면 학생이 도형 이름을 말합니다'] },
      { t: 'match', k: 'fix', title: 'Match and name them!', left: ['c7128', '17101', 'c7086', 'c7190'], right: ['star', 'heart', 'circle', 'triangle'], src: '16쪽 Game', nt: '짝 맞추기', n: ['원본 사진 5장 중 «보라색 장식 공 = circle» 은 보기에 따라 답이 둘 → 답이 하나인 사진으로', '짝을 맞출 때마다 «It\'s a star.» 로 말하기'] },
      { t: 'yourturn', k: 'new', img: '12690', title: 'Shape hunt!', lines: ['Look around your room!', 'I see a ___.', 'The ___ is ___.'], chips: ['circle', 'square', 'rectangle', 'red', 'blue'], nt: '내 방에서 도형 찾기', n: ['화상수업: 방 안 물건을 카메라에 들고 와 말하기(시계 = circle, 창문 = rectangle)', '따라→바꿔→내 말의 마지막 단계'] },
      ...close([['I can name shapes.', 'circle, square, triangle, rectangle, heart, star'], ['I can say "The circle is green."', 'The circle is orange.'], ['I can say "It\'s a green circle."', "It's an orange circle."]], { img: '16238', q: 'How many colors are in a rainbow?', ko: '무지개에는 몇 가지 색이 있을까요? (다음 시간)' }),
    ] },
  // ───────────────────────── 002
  { code: '002', tab: '색깔', unit: U1, title: 'Shapes and Colors', orig: 20,
    intro: '색 이름을 배우고 «What color is the rose? — The rose is red.» 로 묻고 답합니다. 이야기: 윤아와 망고가 색깔 찾기 놀이를 합니다.',
    fixed: ['낱말표 뜻이 들쭉날쭉(빨간 · 주황색 · 노랑 · 푸른 · 녹색) → 모두 «○○색» 으로 통일', 'black 은 목표에만, white·brown 은 본문에만 있고 낱말표에 없음 → 낱말표에 넣음', '❗ 13쪽 «What color is the T-shirt? It\'s a shirt. The shirt is …» — T-shirt / shirt 가 섞임 → T-shirt 로 통일', '15·16쪽 «It is an ___. The ___ is ___.» — 빈칸만 있고 물건이 안 보임 → 사진과 낱말을 보여 줌', '17쪽 «Read and encircle» 는 동그라미 치기라 화상수업에서 쓰기 어려움 → 짝짓기로', '목표·Hello Song 띄어쓰기'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-02-cover-colors', q: 'What is your favorite color?', story: 'Yoona and Mango go on a color hunt!', nt: '표지 + Big Question' },
      ...open([['I can name colors.', '색 이름을 말할 수 있어요.'], ['I can ask "What color is it?"', '«무슨 색이야?» 하고 물을 수 있어요.'], ['I can say "The rose is red."', '물건이 무슨 색인지 말할 수 있어요.']]),
      { t: 'vocab', k: 'fix', hide: true, title: 'Colors 🔒', words: [['red', '빨간색', '12682'], ['orange', '주황색', '12364'], ['yellow', '노란색', '12538'], ['green', '초록색', 'c7117'], ['blue', '파란색', 'c7142'], ['purple', '보라색', '16134'], ['black', '검은색', '12066'], ['white', '흰색', '12037']], src: 'Vocabulary 5쪽', nt: '색 — 뜻 가리고 먼저 말하기', n: ['뜻을 «○○색» 으로 통일(원본: 빨간 · 노랑 · 푸른 · 녹색 이 섞임)', 'black·white 는 원본 본문에 나오는데 낱말표에 없었습니다'] },
      { t: 'vocab', k: 'keep', title: 'Colors', words: [['red', '빨간색', '12682'], ['orange', '주황색', '12364'], ['yellow', '노란색', '12538'], ['green', '초록색', 'c7117'], ['blue', '파란색', 'c7142'], ['purple', '보라색', '16134'], ['black', '검은색', '12066'], ['white', '흰색', '12037']], nt: '색 — 뜻 공개', n: ['강사가 색을 말하면 학생이 방 안에서 그 색 물건을 찾아 들어 보이기'] },
      { t: 'rule', k: 'new', title: 'Ask and answer', left: { h: 'Question', ex: ['What color is the **rose**?', 'What color is the **car**?'] }, right: { h: 'Answer', ex: ['The **rose** is red.', 'The **car** is blue.'] }, q: 'Which word comes back in the answer?', nt: '규칙 찾기', n: ['질문의 물건 이름이 답의 맨 앞에 다시 온다는 것을 학생이 찾게 합니다'] },
      { t: 'qa', k: 'keep', img: '16238', title: 'Rainbow!', q: 'What are the colors of the rainbow?', a: 'They are red, orange, yellow, green, blue, indigo and violet.', src: '8쪽', nt: '무지개', n: ['indigo(남색)·violet(보라)은 무지개에서만 한 번 — 외우지 않아도 됩니다', '손가락으로 무지개를 따라 그리며 색을 차례로 말하기'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-yellow-phone', title: 'Ring, ring!', q: 'What color is the telephone?', a: 'The telephone is ___.', src: '9쪽', nt: '전화기' },
      { t: 'qa', k: 'keep', img: '16106', q: 'What color is the rose?', a: 'The rose is ___.', src: '10쪽', nt: '장미' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-blue-car', q: 'What color is the car?', a: 'The car is ___.', src: '11쪽', nt: '자동차' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-green-snake', title: 'Hiss! 🐍', q: 'What color is the snake?', a: 'I am a ___ snake!', src: '12쪽', nt: '뱀이 말해요', n: ['뱀이 되어 «I am a green snake!» 를 쉿쉿 소리로 — 아이들이 좋아하는 쪽'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-white-tshirt', q: 'What color is the T-shirt?', a: 'The T-shirt is ___.', src: '13쪽', nt: '❗ T-shirt 통일', n: ['원본: «What color is the T-shirt? It\'s a shirt. The shirt is …» → T-shirt 하나로'] },
      { t: 'story', k: 'fix', img: 'gen:bts-02-apple-bag', title: 'Color Hunt', lines: [['Mango', 'Yoona, look! What is it?'], ['Yoona', "It's an apple."], ['Mango', 'What color is the apple?'], ['Yoona', 'The apple is red.'], ['Mango', 'And what color is your bag?'], ['Yoona', 'My bag is orange!']], src: '15·16쪽', nt: '이야기 — 색깔 찾기', n: ['원본 15·16쪽 «It is an ___. The ___ is ___.» 두 쪽을 이야기로 이었습니다', 'an apple — a/an 은 다음 시간에 규칙으로 배웁니다(지금은 소리로만)'] },
      { t: 'ox', k: 'new', img: '16108', s: 'The toy car is green.', nt: '⭕❌', n: ['정답 ❌ → «No! The toy car is purple.»'] },
      { t: 'guess', k: 'new', img: '16136', open: [2, 6], q: 'What is it? What color is it?', chips: ["It's a watermelon.", "It's red and green."], nt: 'Guess it! 타일', n: ['가장자리 칸부터 열면 초록 껍질만 보여 헷갈립니다 — 그게 재미', 'watermelon 은 외우지 않아도 됩니다(색 말하기가 목표)'] },
      { t: 'memory', k: 'new', title: 'Look for 10 seconds!', items: ['12682', '12538', '16106', 'c7117', 'c7142', '16134'], q: 'Look at the colors!', a: 'Then close your eyes!', nt: '기억 게임 — 보기' },
      { t: 'memory', k: 'new', title: 'What color was it?', items: ['12682', '12538', '16106', 'c7117', 'c7142', '16134'], hidden: true, q: 'Number 2 is ___.', a: 'Number 5 is ___.', nt: '기억 게임 — 떠올리기', n: ['번호를 부르면 색으로 답합니다. 맞히면 그 칸을 공개'] },
      { t: 'match', k: 'fix', title: 'What color is it?', left: ['c7207', '12630', 'c7165', 'c5002'], right: ['green', 'brown', 'purple', 'yellow'], src: '17쪽 Read and encircle', nt: '짝 맞추기', n: ['원본 «동그라미 치기» → 화상수업에서 말로 하는 짝짓기로', '짝마다 문장: «The teddy bear is brown.» (brown 새 낱말)'] },
      { t: 'yourturn', k: 'fix', img: '12319', title: 'My colors', lines: ['My favorite color is ___.', 'My ___ is ___.'], chips: ['bag', 'pencil', 'T-shirt', 'red', 'blue'], src: '14쪽 Your Turn', nt: '내 이야기', n: ['책상 위 물건 하나를 들고 «My pencil is yellow.»', '좋아하는 색을 서로 묻기: «What is your favorite color?»'] },
      ...close([['I can name colors.', 'red, orange, yellow, green, blue, purple'], ['I can ask "What color is it?"', 'What color is the rose?'], ['I can say "The rose is red."', 'The car is blue.']], { img: '17101', q: 'Is it a star? Is it yellow?', ko: '색과 도형을 한 번에 말해요 — a yellow star (다음 시간)' }),
    ] },
  // ───────────────────────── 003
  { code: '003', tab: '색 + 도형', unit: U1, title: 'Shapes and Colors', orig: 16,
    intro: '«It\'s a blue square. / It\'s an orange triangle.» — 색과 도형을 한 번에, 그리고 a / an 을 고릅니다. 이야기: 윤아가 선생님께 도형을 보여 줍니다.',
    fixed: ['7쪽 «What is the color of the triangle?» → What color is the triangle? (8쪽과 같은 모양으로)', '12쪽 보기 «yellowcircle · redrectangle · greenheart» 띄어쓰기', '11쪽 철자 빈칸이 같은 쪽 그림 이름을 거의 다 보여 줌 → 사진 없이 글자만', 'a / an 을 쓰는데 규칙 설명이 없었음 → 규칙 찾기 쪽', '목표·쉼표 띄어쓰기'],
    slides: [
      { t: 'cover', k: 'new', img: '16548', q: 'What shapes and colors can you draw?', story: 'Yoona shows her shapes to the teacher.', nt: '표지 + Big Question', n: ['수업 시작 1분 동안 종이에 도형 3개를 색칠해 두게 하면 끝의 Your turn 에 씁니다'] },
      ...open([['I can say "It\'s a blue square."', '색과 도형을 한 번에 말할 수 있어요.'], ['I can use a and an.', 'a 와 an 을 골라 쓸 수 있어요 — an orange triangle.'], ['I can find a mistake.', '틀린 말을 찾아 고쳐 말할 수 있어요.']]),
      { t: 'vocab', k: 'new', hide: true, title: 'Remember? 🔒', words: [['circle', '원', 'c7128'], ['square', '정사각형', 'c7366'], ['triangle', '삼각형', 'c7086'], ['rectangle', '직사각형', 'c7096'], ['heart', '하트', 'c7190'], ['star', '별', '17101']], nt: '지난 낱말 떠올리기', n: ['001 과 다른 사진으로 — 사진을 외운 것이 아니라 뜻을 떠올리게'] },
      { t: 'rule', k: 'new', title: 'a or an?', left: { h: 'a', ex: ['a **b**lue circle', 'a **g**reen square'] }, right: { h: 'an', ex: ['an **o**range triangle', 'an **a**pple'] }, q: 'Listen to the first sound. When do we say "an"?', nt: '규칙 찾기 — a / an', n: ['원본은 an orange 를 쓰면서 규칙이 없었습니다', '모음 소리(아·에·이·오·우)로 시작하면 an — 학생이 먼저 말하게'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-orange-triangle', q: 'What color is the triangle?', a: "It's an ___ triangle.", src: '7쪽', nt: 'an orange', n: ['<del>What is the color of the triangle?</del> → What color is the triangle?'] },
      { t: 'story', k: 'fix', img: 'gen:bts-02-yoona-square', title: "Yoona's Square", lines: [['Teacher', 'Hi, Yoona. What is this?'], ['Yoona', "It's a square."], ['Teacher', 'What color is the square?'], ['Yoona', "The square is blue. It's a blue square."]], src: '8쪽 Mini Talk', nt: '이야기 — 미니 토크', n: ['강사 = 선생님, 학생 = 윤아', '두 번째 판: 학생이 자기 도형을 들고 윤아 자리에서 말하기'] },
      { t: 'order', k: 'fix', img: '12630', words: ['heart.', 'a', "It's", 'yellow'], src: '10쪽', nt: '순서 맞추기', n: ['정답: It\'s a yellow heart. — 색이 도형 앞', '원본 «It\'s a ___ heart.» 빈칸을 순서 맞추기로'] },
      { t: 'order', k: 'fix', img: 'c7366', words: ['square.', 'red', "It's", 'a'], src: '9쪽', nt: '순서 맞추기', n: ['정답: It\'s a red square.'] },
      { t: 'fill', k: 'keep', title: 'Fill in the letters!', lines: ["It's a yel_ow st_r.", "It's a gr__n squ_re.", "It's a r_d tr__ngl_."], src: '11쪽', nt: '철자 채우기', n: ['빈 글자를 말로 채우고 전체 문장을 읽기', '원본은 같은 쪽 그림에 답이 보여 → 글자만 남겼습니다'] },
      { t: 'ox', k: 'fix', img: '17101', title: 'Find the mistake!', s: "It's a yellow circle.", src: '12쪽 Cross out the mistake', nt: '틀린 것 찾기 1', n: ['정답 ❌ → «No! It\'s a yellow star.»', '원본 보기 <del>yellowcircle</del> 띄어쓰기'] },
      { t: 'ox', k: 'fix', img: 'c7366', title: 'Find the mistake!', s: "It's a red square.", src: '12쪽', nt: '틀린 것 찾기 2', n: ['정답 ⭕ — 늘 틀린 것만 나오지 않게 한 번은 맞는 문장'] },
      { t: 'match', k: 'fix', title: 'a or an?', left: ['16108', '12364', '12630', 'c7366'], right: ['an orange ball', 'a yellow heart', 'a red square', 'a purple car'], src: '13쪽 Match and name', nt: '짝 맞추기 + a/an', n: ['원본 «Match and name them» 을 a/an 연습으로'] },
      { t: 'guess', k: 'new', img: 'c7190', open: [1, 5], q: 'What shape are they? What color?', chips: ['They are hearts.', 'They are red and pink.'], nt: 'Guess it! 타일', n: ['여러 개면 They are … — 002 의 They 를 다시'] },
      { t: 'memory', k: 'new', title: 'Remember the colors!', items: ['c7128', '16631', '12538', '16106', 'c7142', 'c7096'], q: 'Look! Close your eyes. What is number 2?', a: "It's a green balloon.", nt: '기억 게임', n: ['10초 보고 눈을 감게 한 뒤 번호로 묻습니다. 답은 색 + 물건으로'] },
      { t: 'yourturn', k: 'new', img: '12690', title: 'Show me!', lines: ['Find something in your room!', "It's a ___ ___.", "It's an ___ ___."], chips: ['orange', 'red', 'blue', 'circle', 'square'], nt: '내 물건으로 말하기', n: ['표지 때 그린 도형이나 방 안 물건을 들고 «It\'s a blue rectangle.»', 'an 이 필요한 물건(orange)을 찾으면 보너스'] },
      ...close([['I can say "It\'s a blue square."', "It's a red square."], ['I can use a and an.', "It's an orange triangle."], ['I can find a mistake.', "No! It's a yellow star."]], { img: '12103', q: 'Which one is big? Which one is small?', ko: 'Unit 2 — 크다·작다 (다음 시간)' }),
    ] },
  // ───────────────────────── 004
  { code: '004', tab: '크기·길이', unit: U2, title: 'Adjectives', orig: 36,
    intro: 'big·small·long·short·thin·thick 과 «The elephant is big.» · «The snake is long and thin.» 을 배웁니다. 이야기: 캐런은 코끼리가 제일 좋대요. 그런데 코끼리는 날 수 있을까?',
    fixed: ['thin 뜻 «얇은» → «가는·마른» · 역할극 fly 뜻 «파리» → «날다» · adorable «홀딱 반할 만한» → «사랑스러운»', '❗ 역할극 «My favorite animal is elephant!» → is the elephant · «I thought elephants fly with their big ears» (시제 오류) → «Can elephants fly with their big ears?»', '«you\'re funny» 문장 첫 글자 대문자', '16·17쪽 tall 이 낱말표 없이 나옴 → 새 낱말로 알려 줌(007 에서 다시)', '15쪽 «Is it long and thin?» 과 앞 두 쪽이 같은 사진·같은 답 반복 → 한 쪽으로', '목표의 «Coordinating adjectives» 용어 → 강사 메모로', '19쪽 파란(navy) 하트에 «It\'s blu_» — navy 와 blue 가 어긋남 → 뺌'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-02-cover-big-small', q: 'Is it big or small?', story: 'Karen loves elephants. Can elephants fly?', nt: '표지 + Big Question' },
      ...open([['I can say big, small, long and short.', '크다·작다·길다·짧다를 말할 수 있어요.'], ['I can say "The elephant is big."', '동물·물건이 어떤지 말할 수 있어요.'], ['I can say "The snake is long and thin."', '두 가지를 and 로 이어 말할 수 있어요.']], 'Lesson Goals (용어 나열이었음)'),
      USONG_2,
      { t: 'vocab', k: 'fix', hide: true, title: 'Adjectives 🔒', words: [['big', '큰', 'c7185'], ['small', '작은', '16311'], ['long', '긴', '12004'], ['short', '짧은', '12306'], ['thin', '가는·마른', 'gen:bts-02-green-snake'], ['thick', '두꺼운', '12023']], src: 'Vocabulary 5쪽', nt: '형용사 — 뜻 가리고 먼저 말하기', n: ['<del>얇은</del> → 가는·마른(thin 은 뱀·사람·동물에 씀)', '손동작 약속: big = 두 팔 크게, small = 손가락 조금, long = 두 손 벌리기'] },
      { t: 'vocab', k: 'keep', title: 'Adjectives', words: [['big', '큰', 'c7185'], ['small', '작은', '16311'], ['long', '긴', '12004'], ['short', '짧은', '12306'], ['thin', '가는·마른', 'gen:bts-02-green-snake'], ['thick', '두꺼운', '12023']], nt: '형용사 — 뜻 공개', n: ['강사가 손동작만 하면 학생이 낱말 말하기(반대로도)'] },
      { t: 'rule', k: 'new', title: 'Opposites!', left: { h: 'big · long · thick', ex: ['The elephant is **big**.', 'The bench is **long**.'] }, right: { h: 'small · short · thin', ex: ['The mouse is **small**.', 'The pencil is **short**.'] }, q: 'Find the opposite pairs!', nt: '규칙 찾기 — 반대말', n: ['세 쌍(big/small · long/short · thick/thin)을 학생이 짝지어 말하게'] },
      { t: 'table', k: 'fix', title: 'The elephant is big.', head: ['what', 'is', 'how'], rows: [['The elephant', 'is', 'big.'], ['The mouse', 'is', 'small.'], ['The snake', 'is', 'long and thin.']], tip: 'is 뒤에 «어떤지» 를 말해요 · 두 가지면 and 로 이어요', src: 'Grammar 6쪽', nt: '문장 틀', n: ['원본 Subject / Linking verb / Adjective 용어는 강사 메모로만'] },
      { t: 'qa', k: 'keep', img: '16080', title: 'Big or small?', q: 'Is the elephant big or small?', a: 'The elephant is ___.', src: '7·8쪽', nt: '코끼리' },
      { t: 'qa', k: 'keep', img: 'c7144', title: 'Big or small?', q: 'Is the hamster big or small?', a: 'The hamster is ___.', src: '9·10쪽', nt: '햄스터' },
      { t: 'ox', k: 'new', img: '12103', s: 'The dog is big.', nt: '⭕❌ — 비교', n: ['원본 11쪽 «코끼리와 햄스터 비교» 를 몸으로 답하기로', '정답 ❌ → «No! The dog is small. The elephant is big.»'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-green-snake', title: 'Hiss!', q: 'Is the snake long and thin?', a: 'Yes! The snake is long and ___.', src: '12~15쪽', nt: 'long and thin', n: ['원본 4쪽(long? / thin? / long and thin?)이 같은 사진·같은 답 → 한 쪽으로 모음'] },
      { t: 'qa', k: 'fix', img: '12520', title: 'Wow!', q: 'Is the giraffe tall?', a: 'Yes, the giraffe is ___.', src: '16·17쪽', nt: 'tall (새 낱말)', n: ['원본은 tall 을 낱말표 없이 씀 → 여기서 «키가 큰» 으로 한 번 알려 줍니다(007 에서 사람에게 다시)'] },
      { t: 'fill', k: 'keep', title: 'Shapes and sizes', img: 'gen:bts-02-shape-sizes', lines: ['The rectangle is long and ___.', 'The circle is ___.', 'The square is ___.'], chips: ['big', 'small', 'thin'], src: '18쪽', nt: '도형 + 크기', n: ['001~003 의 도형을 크기로 다시 말하기 — 단원 1과 2를 잇는 쪽'] },
      { t: 'order', k: 'fix', img: '15194', words: ['gray.', 'big', 'The elephant', 'is', 'and'], src: '23쪽', nt: '두 가지 — 순서 맞추기', n: ['정답: The elephant is big and gray.'] },
      { t: 'order', k: 'fix', img: 'gen:bts-02-cardinal', words: ['red.', 'small', 'The bird', 'and', 'is'], src: '24쪽', nt: '두 가지 — 순서 맞추기', n: ['정답: The bird is small and red.'] },
      { t: 'fill', k: 'fix', title: 'Size and color', lines: ['The square is big and ___. (주황색)', 'The rectangle is ___ and ___. (길다 · 초록색)', 'The triangle is ___ and ___. (작다 · 파란색)'], src: '20~22쪽', nt: '크기 + 색', n: ['원본 세 쪽을 한 쪽에. 괄호 속 한국어 힌트를 영어로 바꿔 문장을 완성해 소리 내어 읽기', '<del>or__ge</del> 철자 빈칸 → 낱말 빈칸으로'] },
      { t: 'vocab', k: 'fix', small: 'New words', title: 'Before the story', cols: 4, words: [['wings', '날개', '15353'], ['heavy', '무거운', '12466'], ['fly', '날다', '16809'], ['adorable', '사랑스러운', '12885']], src: 'Role-play New Words', nt: '이야기 낱말', n: ['<del>파리</del> → 날다 · <del>홀딱 반할 만한</del> → 사랑스러운'] },
      { t: 'story', k: 'fix', img: 'gen:bts-02-elephant-ears', title: 'Can Elephants Fly?', lines: [['Yoona', 'What is your favorite animal?'], ['Karen', 'My favorite animal is the elephant!'], ['Yoona', 'Can elephants fly with their big ears?'], ['Karen', "No! They don't have wings. They are too heavy."], ['Yoona', 'Ha ha! But they are adorable.']], src: '28·29쪽 Role-play', nt: '이야기 (1)', n: ['<del>is elephant</del> → is the elephant · 원본 «I thought elephants fly with their big ears» 는 시제가 틀리고 길어 → 질문으로 바꿨습니다', '강사 = 캐런, 학생 = 윤아 — 두 번째는 바꿔서'] },
      { t: 'story', k: 'fix', img: '19426', title: 'Can Elephants Fly? (2)', lines: [['Yoona', 'What color is the elephant? Is it pink?'], ['Karen', "No, it isn't. It's gray."], ['Mango', 'A pink elephant? Only in my dreams! 🐘']], src: '29쪽', nt: '이야기 (2)', n: ['망고의 마지막 대사가 웃음 포인트 — «Is it pink?» 에 학생이 먼저 «No!» 하게'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ['Who likes elephants? — ___ likes elephants.', "Can elephants fly? — No, they ___.", "What color is the elephant? — It's ___."], src: '30쪽', nt: '이야기 질문', n: ['원본 «What\'s her name?» 은 누구를 묻는지 불분명(둘 다 여자) → «Who likes elephants?»'] },
      { t: 'guess', k: 'new', img: '15593', open: [0, 1], q: 'What is it? Is it tall?', chips: ["It's a bird.", 'Yes, it is tall.', 'It is small.'], nt: 'Guess it! 타일', n: ['목이 긴 타조 — 위쪽 칸만 보면 기린인지 새인지 헷갈려 재미있습니다'] },
      { t: 'memory', k: 'new', title: 'Look for 10 seconds!', items: ['c7144', '12520', 'c7185', '16311'], q: 'Big or small? Look!', a: 'Then close your eyes!', nt: '기억 게임 — 보기' },
      { t: 'memory', k: 'new', title: 'Which one?', items: ['c7144', '12520', 'c7185', '16311'], hidden: true, q: 'Which animal is tall?', a: 'Number ___! The ___ is tall.', nt: '기억 게임 — 떠올리기', n: ['«작은 동물은 몇 번?» 도 물어 형용사로 떠올리게'] },
      { t: 'match', k: 'new', title: 'Match the words!', left: ['12004', '12306', '12023', '16311'], right: ['short', 'small', 'long', 'thick'], nt: '짝 맞추기', n: ['짝마다 «The bench is long.» 처럼 문장으로'] },
      { t: 'yourturn', k: 'fix', img: '15799', title: 'Are you big or small?', lines: ['Are you big or small?', 'I am ___.', 'My ___ is big.'], chips: ['small', 'big', 'dad', 'mom'], src: '25·26쪽 Your Turn', nt: '내 이야기', n: ['어깨 위 아이 사진 — 아이는 small, 삼촌은 big', '가족 중 누가 big 인지 말하기'] },
      ...close([['I can say big, small, long and short.', 'The mouse is small.'], ['I can say "The elephant is big."', 'The giraffe is tall.'], ['I can say "The snake is long and thin."', 'The bird is small and red.']], { img: 'gen:bts-02-white-tiger', q: 'Is the tiger blue?', ko: '호랑이가 파란색일까요? «Yes, it is. / No, it isn\'t.» (다음 시간)' }),
    ] },
  // ───────────────────────── 005
  { code: '005', tab: 'Yes / No', unit: U2, title: 'Adjectives', orig: 19,
    intro: '«Is the snake long? — Yes, it is. / No, it isn\'t.» 로 묻고 답합니다. 이야기: 망고가 동물을 하나 생각했어요. 질문으로 맞혀 보세요!',
    fixed: ['8쪽 «long,thin and green» 쉼표 띄어쓰기', '16쪽 풍선이 의자 위 풍선이라 «Is the balloon small?» 답이 애매 → 작은 풍선 사진', '13·14쪽 공룡 두 쪽(색·크기)이 같은 사진 → 질문 한 쪽 + ⭕❌ 한 쪽', '낱말표가 004 와 글자까지 같음 → 다른 사진으로 떠올리기', '⚠️ 원본 18쪽 파일이 사이트에 없음(17 다음 19) — 내용 확인 필요'],
    slides: [
      { t: 'cover', k: 'new', img: '17171', q: 'Is the tiger blue?', story: 'Mango is thinking of an animal. Can you guess?', nt: '표지 + Big Question', n: ['학생이 «No!» 를 외치며 시작하는 질문 — 오늘은 Yes/No 로 답하는 과'] },
      ...open([['I can ask "Is the snake long?"', '«~은 ~하니?» 하고 물을 수 있어요.'], ['I can say "Yes, it is."', '맞으면 Yes, it is. 로 답해요.'], ['I can say "No, it isn\'t."', '아니면 No, it isn\'t. 하고 바르게 고쳐 말해요.']]),
      USONG_2,
      { t: 'vocab', k: 'fix', hide: true, title: 'Remember? 🔒', words: [['big', '큰', '15194'], ['small', '작은', '12227'], ['long', '긴', '18100'], ['short', '짧은', '12306'], ['thin', '가는·마른', 'gen:bts-02-thin-dog'], ['thick', '두꺼운', '13133']], src: 'Vocabulary 5쪽 (004와 같았음)', nt: '지난 낱말 떠올리기', n: ['대부분 004 와 다른 사진 — 사진이 아니라 뜻을 떠올리게 합니다'] },
      { t: 'rule', k: 'new', title: 'Yes or no?', left: { h: 'Yes', ex: ['Is the snake **long**?', '→ **Yes, it is.**'] }, right: { h: 'No', ex: ['Is the snake **blue**?', "→ **No, it isn't.** It is green."] }, q: 'After "No", what do we say next?', src: '9쪽 Let\'s practice', nt: '규칙 찾기', n: ["«No» 다음에 바른 답을 한 번 더 말한다는 것을 학생이 찾게", "isn't = is not"] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-green-snake', title: 'Picture Talk!', q: 'What do you see?', a: 'I see a snake. It is long, thin and ___.', src: '7·8쪽', nt: '사진 보고 말하기', n: ['<del>long,thin</del> → long, thin'] },
      { t: 'qa', k: 'keep', img: '12058', q: 'Is the apple green?', a: "No, it ___. It is ___.", src: '12쪽', nt: '아니에요' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-panda', q: 'Is the panda small?', a: "___, it isn't. It is ___.", src: '12쪽', nt: '아니에요' },
      { t: 'qa', k: 'keep', img: '12037', q: 'Is the rabbit white?', a: 'Yes, ___ ___.', src: '12쪽', nt: '맞아요' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-ant', q: 'Is the ant small?', a: 'Yes, it is. The ant is ___.', src: '12쪽', nt: '맞아요', n: ['원본 12쪽 네 문장을 사진과 함께 한 쪽씩'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-dinosaur', title: 'Roar!', q: 'Is the dinosaur yellow?', a: "No, it isn't. It is ___.", src: '13쪽', nt: '공룡 색' },
      { t: 'ox', k: 'fix', img: 'gen:bts-02-dinosaur', s: 'The dinosaur is small.', src: '14쪽', nt: '⭕❌', n: ['원본 «Is the dinosaur big? Yes, it is.» → 몸으로 답하기', '정답 ❌ → «No, it isn\'t. It is big!»'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-white-tiger', q: 'Is the tiger blue?', a: "No, it isn't. It is ___ and black.", src: '15쪽', nt: '호랑이', n: ['원본 «Is the tiger long? Yes, it is.» 까지 이어서 한 번 더 묻기'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-pink-balloon', q: 'Is the balloon pink? Is it big?', a: "Yes, it is. No, it ___. It is small.", src: '16쪽', nt: '❗ 두 질문', n: ['원본 사진은 풍선 크기가 애매 → 한눈에 작은 풍선 사진으로'] },
      { t: 'guess', k: 'new', img: 'c7380', open: [0, 8], q: 'Is it a bird? Is it green?', chips: ['Yes, it is.', "No, it isn't."], nt: 'Guess it! — 질문으로 열기', n: ['학생이 Yes/No 질문을 해야 타일을 엽니다 — 오늘 문장을 게임 속에서 계속 쓰게'] },
      { t: 'story', k: 'new', img: '15194', title: "Mango's Guessing Game", lines: [['Mango', "I'm thinking of an animal. Ask me!"], ['Yoona', 'Is it big?'], ['Mango', 'Yes, it is.'], ['Yoona', 'Is it gray? Is it an elephant?'], ['Mango', 'Yes, it is! You win! 🎉']], nt: '이야기 — 스무고개', n: ['다음 쪽에서 학생이 직접 문제를 냅니다'] },
      { t: 'yourturn', k: 'new', img: '15836', title: 'Your guessing game!', lines: ['Think of an animal!', 'Is it big?', 'Is it long?', 'Is it ___?'], chips: ['Yes, it is.', "No, it isn't."], nt: '내가 문제 내기', n: ['한 번은 강사가, 한 번은 학생이 동물을 생각하고 상대가 묻기', '질문 3개 안에 맞히면 성공'] },
      { t: 'scramble', k: 'new', title: 'Unscramble!', items: [['gib', 'c7185'], ['llmas', '16311'], ['gnol', '12004'], ['niht', 'gen:bts-02-thin-dog']], nt: '낱말 퍼즐', n: ['정답: big · small · long · thin', '맞힌 낱말로 «Is it …?» 질문 하나 만들기'] },
      ...close([['I can ask "Is the snake long?"', 'Is the panda small?'], ['I can say "Yes, it is."', 'Yes, it is.'], ['I can say "No, it isn\'t."', "No, it isn't. It is big."]], { img: 'gen:bts-02-cover-zoo', q: 'What animals do you see at the zoo?', ko: '동물원에 가요! (다음 시간)' }),
    ] },
  // ───────────────────────── 006
  { code: '006', tab: '동물원', unit: U2, title: 'Adjectives', orig: 27,
    intro: '동물원 동물(lion·giraffe·zebra·parrot·monkey·hippo·bear)을 색과 크기로 말하고, 여러 마리는 «The monkeys are small.» 처럼 are 로 말합니다. 이야기: 윤아·캐런·망고의 동물원 나들이.',
    fixed: ['❗ 15쪽 «The elephant is (tall / big)» — 둘 다 맞아 선택이 안 됨 → «big or small?»', '12쪽 짝짓기에 black and white / yellow / big / tall 이 동물마다 둘 이상 맞음 → 답이 하나인 짝으로', '20쪽 «th__,» 철자 빈칸 · 21쪽 «w_it_» → 보기 정리', '낱말표에 hippo·zebra·parrot 만 새로 있고 lion·monkey·bear 는 없음 → 모두 넣음', '22쪽 «The monkeys are» — 여러 마리 are 를 규칙 없이 씀 → 규칙 찾기 쪽', '7쪽 머리 장식(Idea Zone) 강아지 캐릭터 사진은 동물원과 무관 → 표지로 대체'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-02-cover-zoo', q: 'What animals do you see at the zoo?', story: 'Yoona, Karen and Mango go to the zoo!', nt: '표지 + Big Question' },
      ...open([['I can name zoo animals.', '동물원 동물 이름을 말할 수 있어요.'], ['I can say "The lion is yellow."', '동물의 색과 크기를 말할 수 있어요.'], ['I can say "The monkeys are small."', '여러 마리는 are 로 말할 수 있어요.']]),
      USONG_2,
      { t: 'vocab', k: 'fix', hide: true, title: 'Zoo animals 🔒', words: [['lion', '사자', 'c7435'], ['giraffe', '기린', '12520'], ['elephant', '코끼리', 'c7185'], ['zebra', '얼룩말', 'gen:bts-02-zebra'], ['parrot', '앵무새', 'c7380'], ['monkey', '원숭이', 'c7344'], ['hippo', '하마', 'gen:bts-02-hippos'], ['bear', '곰', 'c7385']], src: 'Vocabulary 5쪽', nt: '동물 — 뜻 가리고 먼저 말하기', n: ['원본 낱말표는 hippo·zebra·parrot 셋뿐 → 본문에 나오는 동물을 모두'] },
      { t: 'vocab', k: 'keep', title: 'Zoo animals', words: [['lion', '사자', 'c7435'], ['giraffe', '기린', '12520'], ['elephant', '코끼리', 'c7185'], ['zebra', '얼룩말', 'gen:bts-02-zebra'], ['parrot', '앵무새', 'c7380'], ['monkey', '원숭이', 'c7344'], ['hippo', '하마', 'gen:bts-02-hippos'], ['bear', '곰', 'c7385']], nt: '동물 — 뜻 공개', n: ['동물 흉내(소리·동작)를 하면 다른 사람이 이름 말하기'] },
      { t: 'rule', k: 'new', title: 'is or are?', left: { h: 'one', ex: ['The monkey **is** small.', 'The hippo **is** big.'] }, right: { h: 'two or more', ex: ['The monkeys **are** small.', 'The hippos **are** big.'] }, q: 'One animal or many? Is or are?', nt: '규칙 찾기 — is / are', n: ['원본 22·24쪽이 규칙 없이 are 를 씀 → 먼저 규칙을 찾게', '낱말 끝 -s 와 are 가 짝이라는 것까지'] },
      { t: 'match', k: 'fix', title: 'Match the animals!', left: ['c7435', 'gen:bts-02-zebra', 'c7380', '12520'], right: ['tall', 'green and red', 'yellow', 'black and white'], src: '12쪽 Match', nt: '짝 맞추기', n: ['원본 보기(big·tall 등)는 동물마다 답이 둘 이상 → 답이 하나인 짝으로'] },
      { t: 'qa', k: 'keep', img: 'c7435', q: 'What color is the lion?', a: 'The lion is ___.', chips: ['yellow', 'blue'], src: '13쪽', nt: '사자' },
      { t: 'qa', k: 'keep', img: 'c7380', q: 'Is the parrot big or small?', a: 'The parrot is ___.', src: '14쪽', nt: '앵무새' },
      { t: 'qa', k: 'fix', img: 'c7185', q: 'Is the elephant big or small?', a: 'The elephant is ___.', src: '15쪽', nt: '❗ 코끼리', n: ['원본 보기 (tall / big) 는 둘 다 맞음 → big / small'] },
      { t: 'qa', k: 'keep', img: '12520', q: 'Is the giraffe short or tall?', a: 'The giraffe is ___.', src: '16쪽', nt: '기린' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-zebra', q: 'What color is the zebra?', a: 'The zebra is black and ___.', src: '17쪽', nt: '얼룩말' },
      { t: 'qa', k: 'fix', img: 'c7385', title: 'What animals do you see?', q: 'What do you see?', a: 'I see a ___. It is big and ___.', src: '18·21쪽', nt: '곰', n: ['원본 «The bear is b_g and w_it_.» 를 사진 보고 말하기로'] },
      { t: 'fill', k: 'fix', title: 'Fill in the letters!', lines: ['The snake is l_ng, th_n and gr__n.', 'The bear is b_g and wh_t_.'], src: '20·21쪽', nt: '철자 채우기', n: ['<del>th__,</del> → th_n · 쉼표 정리'] },
      { t: 'qa', k: 'keep', img: '15172', title: 'Talk about the animals!', q: 'Are the monkeys big or small?', a: 'The monkeys are ___.', src: '22쪽', nt: '여러 마리 — are' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-chickadee', q: 'Is the bird big or small?', a: 'The bird is ___.', src: '23쪽', nt: '작은 새' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-hippos', q: 'What are they?', a: 'They are hippos. The hippos are ___.', src: '24쪽', nt: '여러 마리 — are' },
      { t: 'ox', k: 'new', img: '19466', s: 'The zebras are black and white.', nt: '⭕❌', n: ['정답 ⭕ — 여러 마리라 are', '«The elephants are small.» 로 한 번 더 물으면 ❌'] },
      { t: 'guess', k: 'new', img: 'c7344', open: [4], q: 'What animal is it?', chips: ['Is it big?', 'Is it a monkey?', 'It is small.'], nt: 'Guess who 타일', n: ['005 의 Yes/No 질문으로 타일을 여는 게임 — 복습을 겸합니다'] },
      { t: 'story', k: 'new', img: '15836', title: 'At the Zoo', lines: [['Karen', 'Look, Yoona! What animals do you see?'], ['Yoona', 'I see a lion. The lion is yellow.'], ['Mango', 'I see two hippos. They are big!'], ['Karen', 'And the parrot is small and green.'], ['Yoona', 'This zoo is so fun!']], nt: '이야기 — 동물원 나들이', n: ['004 의 윤아·캐런이 이어서 나옵니다', '읽고 나서 «누가 무엇을 봤지?» 짧게 묻기'] },
      { t: 'memory', k: 'new', title: 'Look for 10 seconds!', items: ['c7435', 'c7380', '15172', 'c7385', 'gen:bts-02-zebra', 'gen:bts-02-hippos'], q: 'Look at the animals!', a: 'Then close your eyes!', nt: '기억 게임 — 보기' },
      { t: 'memory', k: 'new', title: 'What was it?', items: ['c7435', 'c7380', '15172', 'c7385', 'gen:bts-02-zebra', 'gen:bts-02-hippos'], hidden: true, q: 'Number 4 is a ___.', a: 'Number 3? They are ___.', nt: '기억 게임 — 떠올리기', n: ['3번은 원숭이 여러 마리 → «They are monkeys.» 로 are 연습'] },
      { t: 'yourturn', k: 'new', img: '19402', title: 'My favorite zoo animal', lines: ['My favorite animal is the ___.', 'It is ___ and ___.'], chips: ['big', 'small', 'tall', 'long', 'gray'], nt: '내 이야기', n: ['좋아하는 동물을 두 형용사로 소개하기 — 004 의 and 문장을 다시'] },
      ...close([['I can name zoo animals.', 'lion, giraffe, zebra, parrot, hippo'], ['I can say "The lion is yellow."', 'The zebra is black and white.'], ['I can say "The monkeys are small."', 'The hippos are big.']], { img: 'gen:bts-02-new-teacher', q: 'Who is she? What color is her hair?', ko: 'Unit 3 — 사람의 키·머리·눈 (다음 시간)' }),
    ] },
  // ───────────────────────── 007
  { code: '007', tab: '사람 묘사', unit: U3, title: 'People and Adjectives', orig: 28,
    intro: 'tall·short·blonde·gray 와 hair·eyes, «She has red hair. / I don\'t have blue eyes.» 를 배웁니다. 이야기: 샘에게 새 선생님이 생겼어요. 엄마에게 선생님을 설명합니다.',
    fixed: ['❗ 낱말표 tall «긴» → «키가 큰» · fat «지방» → «뚱뚱한» · both «양자 모두» → «둘 다»', '❗ 14·15쪽 fat/thin 사진이 실제 사람의 몸(배 나온 남자·크롭탑 여자) → 고양이·강아지로', '❗ 25쪽 동양인 남자 사진에 다른 사람의 파란 눈 사진을 붙여 «He has blue eyes» → 한 사람 사진으로', '11쪽 «What color are the teacher\'s eyes.?» 부호 · 23쪽 «eyes..» · 15쪽 마침표 누락', '목표의 «Blonde hair color misinterpreted as yellow» 는 학생용 목표가 아님 → 강사 메모로', '6·7쪽 Transitive verb / Direct object 용어 → 강사 메모로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-02-new-teacher', q: 'Who is the new teacher? What does she look like?', story: 'Sam has a new teacher. He tells his mom about her.', nt: '표지 + Big Question' },
      ...open([['I can say "He is tall."', '사람의 키를 말할 수 있어요 — tall, short.'], ['I can say "She has red hair."', '머리와 눈 색을 has 로 말할 수 있어요.'], ['I can say "I don\'t have blue eyes."', '«없어요» 를 don\'t have 로 말할 수 있어요.']], 'Lesson Goals (용어 나열이었음)'),
      USONG_3,
      { t: 'vocab', k: 'fix', hide: true, title: 'People words 🔒', words: [['tall', '키가 큰', 'gen:bts-02-dad-tall'], ['short', '키가 작은', '21242'], ['fat', '뚱뚱한', 'gen:bts-02-fat-cat'], ['thin', '마른', 'gen:bts-02-thin-dog'], ['blonde', '금발의', 'gen:bts-02-karen'], ['gray', '회색의', '13003'], ['hair', '머리카락', '13008'], ['eyes', '눈', '12953']], src: 'Vocabulary 5쪽', nt: '낱말 — 뜻 가리고 먼저 말하기', n: ['<del>긴</del> → 키가 큰 · <del>지방</del> → 뚱뚱한', 'fat/thin 은 동물 사진으로 — 친구의 몸을 두고 말하지 않도록 강사가 함께 약속'] },
      { t: 'vocab', k: 'keep', title: 'People words', words: [['tall', '키가 큰', 'gen:bts-02-dad-tall'], ['short', '키가 작은', '21242'], ['fat', '뚱뚱한', 'gen:bts-02-fat-cat'], ['thin', '마른', 'gen:bts-02-thin-dog'], ['blonde', '금발의', 'gen:bts-02-karen'], ['gray', '회색의', '13003'], ['hair', '머리카락', '13008'], ['eyes', '눈', '12953']], nt: '낱말 — 뜻 공개', n: ['blonde 는 노란색(yellow)이 아니라 «금발» — 원본 목표의 주의점을 여기서 말로'] },
      { t: 'rule', k: 'new', title: 'has or have?', left: { h: 'I · you · they → have', ex: ['I **have** brown eyes.', 'They **have** black hair.'] }, right: { h: 'he · she → has', ex: ['She **has** red hair.', 'He **has** blue eyes.'] }, q: 'When do we say "has"?', nt: '규칙 찾기 — has / have', n: ['원본은 has 를 쓰면서 have 와 비교가 없었음 → 두 묶음을 보고 학생이 먼저'] },
      { t: 'table', k: 'fix', title: 'She has red hair.', head: ['who', 'has', 'what'], rows: [['She', 'has', 'red hair.'], ['He', 'has', 'two eyes.'], ['I', "don't have", 'blonde hair.']], tip: 'hair 는 하나로(hairs ✕) · eyes 는 둘이라 -s', src: 'Grammar 6·7쪽', nt: '문장 틀', n: ['원본 Transitive verb / Direct object 용어는 강사 메모로만'] },
      { t: 'story', k: 'keep', img: 'gen:bts-02-mom-brown', title: 'My New Teacher', lines: [['Sam', 'Mom, I have a new teacher!'], ['Mom', "Really? What's her name?"], ['Sam', 'Mrs. Smith. She has blonde hair and blue eyes.'], ['Mom', "I don't have blonde hair. I have brown hair and brown eyes."]], src: '9·10쪽 Mini Talk', nt: '이야기 — 샘과 엄마', n: ['강사 = 엄마, 학생 = 샘. 두 번째는 바꿔서', 'I don\'t have … 가 오늘의 새 문장'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ["What color are Mom's eyes? — They are ___.", "What color is Mom's hair? — It is ___.", "What color are the teacher's eyes? — They are ___."], src: '11쪽', nt: '이야기 질문', n: ['<del>eyes.?</del> 부호 정리'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-dad-tall', q: 'Who is tall?', a: 'He is tall. She is ___.', src: '12·13쪽', nt: 'tall / short' },
      { t: 'order', k: 'fix', img: '21242', words: ['is', 'He', 'short', 'boy.', 'a'], src: '13쪽', nt: '순서 맞추기', n: ['정답: He is a short boy. — 003 의 «a + 색 + 물건» 과 같은 자리'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-fat-cat', title: 'Fat or thin?', q: 'Is the cat fat or thin?', a: 'The cat is ___.', src: '14쪽', nt: '❗ 사진 교체', n: ['원본: 배 나온 남자 사진 «He is a fat man.» → 동글동글한 고양이로'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-thin-dog', title: 'Fat or thin?', q: 'Is the dog fat or thin?', a: 'The dog is ___.', src: '15쪽', nt: '❗ 사진 교체', n: ['원본: 크롭탑 여자 사진 «She is a thin woman» → 날씬한 강아지로'] },
      { t: 'qa', k: 'keep', img: '13008', q: 'What is it?', a: "It's ___.", src: '16쪽', nt: 'hair' },
      { t: 'qa', k: 'keep', img: '19020', q: 'What color is her hair?', a: 'She has ___ hair.', src: '17쪽', nt: '빨간 머리' },
      { t: 'qa', k: 'keep', img: 'c7123', q: 'What color is her hair?', a: 'She has ___ hair.', chips: ['black', 'red'], src: '18쪽', nt: '검은 머리' },
      { t: 'qa', k: 'keep', img: '12953', q: 'What are they?', a: 'They are ___.', src: '20쪽', nt: 'eyes' },
      { t: 'count', k: 'fix', img: '12885', q: 'How many eyes does the kitten have?', a: 'It has ___ eyes.', src: '21쪽', nt: '눈이 몇 개?', n: ['원본 «How many eyes do you have?» → 눈 큰 고양이로 한 번 더(웃음)', '다음에 «I have two eyes.» 로 자기 눈도'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-green-eyes', q: 'What color are his eyes?', a: 'He has ___ eyes.', src: '22쪽', nt: '초록 눈' },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-baby-blue', q: 'What color are the baby\'s eyes?', a: 'The baby has ___ eyes.', src: '23쪽', nt: '파란 눈', n: ['<del>eyes..</del> 마침표'] },
      { t: 'qa', k: 'fix', img: '13003', q: 'What color is her hair?', a: 'She has ___ hair.', src: '24쪽', nt: '회색 머리', n: ['원본 24쪽 «gray eyes» 사진 대신 회색 머리 — gray 를 더 알아보기 쉬운 사진으로'] },
      { t: 'guess', k: 'fix', img: '20118', open: [0, 1, 2], q: 'Who is he?', chips: ['He is a man.', 'He is tall.', 'He has brown hair.', 'He has blue eyes.'], src: '25쪽', nt: '❗ Guess who', n: ['원본: 남자 사진에 다른 사람의 파란 눈을 오려 붙임 → 한 사람 사진', '위 줄(머리)부터 열고 문장 하나마다 한 칸씩'] },
      { t: 'ox', k: 'new', img: 'c7137', s: 'He has blonde hair.', nt: '⭕❌', n: ['정답 ❌ → «No! He has black hair.» (수염 사진 — beard 는 말하지 않아도 됩니다)'] },
      { t: 'yourturn', k: 'new', img: '16089', title: 'About me', lines: ['I am ___.', 'I have ___ hair.', 'I have ___ eyes.', "I don't have ___ hair."], chips: ['tall', 'short', 'black', 'brown', 'blonde'], nt: '내 이야기', n: ['거울이나 화면 속 내 모습을 보며 말하기', '마지막 줄 don\'t have 가 오늘의 핵심'] },
      ...close([['I can say "He is tall."', 'He is tall. She is short.'], ['I can say "She has red hair."', 'She has red hair.'], ['I can say "I don\'t have blue eyes."', "I don't have blue eyes."]], { img: 'gen:bts-02-cover-friends', q: 'Who has blonde hair?', ko: '친구들의 머리와 눈을 설명해요 (다음 시간)' }),
    ] },
  // ───────────────────────── 008
  { code: '008', tab: '누구일까?', unit: U3, title: 'People and Adjectives', orig: 24,
    intro: '본 사람을 «I see a boy. He has blond hair.» 로 말하고, «Who has …?» 에 답합니다. blond(남자) / blonde(여자) 규칙도 배웁니다. 이야기: 밥과 제인 중 누가 금발일까?',
    fixed: ['blond / blonde 를 섞어 쓰고(008) 규칙은 009 에 나옴 → 이 과 앞으로 당김', '10쪽 «She is a girl..» 마침표 · 13쪽 «They are ___ eyes.» 반복', '❗ 20쪽 빨간 머리 사진이 어둡고 무서운 분위기 → 밝은 사진', '19쪽 «She ___ brown hair and ___ eyes.» 빈칸 두 개가 한 문장에서 답을 흐림 → 두 문장으로', '14쪽 걸음마 아기 사진 쪽은 15쪽과 같은 내용 → 합침'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-02-cover-friends', q: 'Who has blonde hair? Who has black hair?', story: 'Yoona describes her friends. Can you guess who?', nt: '표지 + Big Question' },
      ...open([['I can say who I see.', '본 사람을 말할 수 있어요 — I see a boy.'], ['I can describe hair and eyes.', '머리와 눈 색을 설명할 수 있어요.'], ['I can say "She doesn\'t have red hair."', '없는 것도 말할 수 있어요.']]),
      USONG_3,
      { t: 'vocab', k: 'new', hide: true, title: 'Remember? 🔒', words: [['tall', '키가 큰', 'c7319'], ['short', '키가 작은', 'gen:bts-02-blond-boy'], ['blonde', '금발의', 'gen:bts-02-new-teacher'], ['brown', '갈색의', '12368'], ['black', '검은색의', 'gen:bts-02-black-hair-girl'], ['eyes', '눈', 'gen:bts-02-green-eyes']], nt: '지난 낱말 떠올리기' },
      { t: 'rule', k: 'fix', title: 'blond or blonde?', left: { h: 'boys · men', ex: ['He has **blond** hair.', 'Both boys have **blond** hair.'] }, right: { h: 'girls · women', ex: ['She has **blonde** hair.', 'Jane has **blonde** hair.'] }, q: 'Listen! Do they sound the same?', src: '009 6쪽 규칙을 앞당김', nt: '규칙 찾기 — blond / blonde', n: ['소리는 같고 글자만 다릅니다 — 말할 때는 신경 쓰지 않아도 된다고 안심시키기', '원본은 이 과에서 둘을 섞어 쓰고 규칙은 다음 과에 있었습니다'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-mom-brown', title: 'Picture Talk!', q: 'Who is she?', a: 'She is a woman. She has ___ hair.', src: '8·9쪽', nt: '갈색 머리', n: ['007 이야기의 샘 엄마 — 인물이 이어집니다'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-black-hair-girl', q: 'Who is she?', a: 'She is a girl. She has ___ hair and black ___.', src: '10쪽', nt: '검은 머리', n: ['<del>girl..</del> 마침표'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-blond-boy', q: 'Who is he?', a: 'He is a ___. He has ___ hair and ___ eyes.', chips: ['boy', 'blond', 'blue'], src: '11·16쪽', nt: '금발 소년' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-new-teacher', q: 'Who is she?', a: 'She is a woman. She is tall and she has ___ hair.', src: '12쪽', nt: '금발 여자', n: ['007 의 새 선생님 Mrs. Smith — 학생이 알아보면 칭찬'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-baby-blue', q: 'What are they?', a: 'They are eyes. They are ___.', src: '13쪽', nt: '파란 눈', n: ['원본 «They are ___. They are ___ eyes.» → 답이 한 번에 보이도록 정리'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-dad-tall', q: 'Who are they?', a: 'He is a man. He is ___. She is a girl. She is ___.', src: '14·15쪽', nt: '키 비교', n: ['원본 두 쪽(아기 · 남자와 소년)을 한 쪽으로'] },
      { t: 'story', k: 'fix', img: 'gen:bts-02-bob-jane', title: 'Bob and Jane', lines: [['Bob', 'I have black hair and black eyes.'], ['Jane', 'I have blonde hair and blue eyes.'], ['Mango', 'Who has blonde hair and blue eyes?'], ['Yoona', "Jane has blonde hair and blue eyes. Bob doesn't have blonde hair."]], src: '17·18쪽', nt: '이야기 — 누가 금발?', n: ['원본 «a boy and a girl» 에 이름을 붙여 권 전체 인물(Bob·Jane)과 이음', '마지막 줄 doesn\'t have 가 핵심'] },
      { t: 'table', k: 'fix', title: 'has / doesn\'t have', head: ['who', 'has / doesn\'t have', 'what'], rows: [['Jane', 'has', 'blonde hair.'], ['Bob', "doesn't have", 'blond hair.'], ['She', "doesn't have", 'brown hair.']], tip: "he · she 는 doesn't have", src: '18·19쪽', nt: '문장 틀', n: ['원본 19쪽 한 문장의 빈칸 두 개 → 두 줄로 나눔'] },
      { t: 'qa', k: 'fix', img: '19020', q: 'Does she have red hair?', a: 'Yes, she has ___ hair.', src: '20쪽', nt: '❗ 사진 교체', n: ['원본: 어둡고 무서운 분위기의 사진 → 밝은 사진', '«Who is tall and has red hair?» 는 009 에서 다시'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-blond-twins', q: 'Who has blond hair?', a: 'Both boys have ___ hair.', src: '21쪽', nt: 'both — 둘 다', n: ['both «둘 다» (원본 뜻 «양자 모두» → 쉬운 말로)'] },
      { t: 'ox', k: 'new', img: 'gen:bts-02-black-hair-girl', s: 'She has blonde hair.', nt: '⭕❌', n: ['정답 ❌ → «No! She doesn\'t have blonde hair. She has black hair.»'] },
      { t: 'guess', k: 'new', img: '15315', open: [1], q: 'Is it a boy or a girl?', chips: ['She is a girl.', 'She has ___ hair.'], nt: 'Guess who 타일', n: ['머리 칸 → 얼굴 칸 순으로 열며 한 칸마다 문장 하나'] },
      { t: 'memory', k: 'new', title: 'Look for 10 seconds!', items: ['gen:bts-02-blond-boy', 'gen:bts-02-black-hair-girl', '19020', '13003'], q: 'Look at their hair!', a: 'Then close your eyes!', nt: '기억 게임 — 보기' },
      { t: 'memory', k: 'new', title: 'Who has it?', items: ['gen:bts-02-blond-boy', 'gen:bts-02-black-hair-girl', '19020', '13003'], hidden: true, q: 'Who has gray hair?', a: 'Number ___ has gray hair.', nt: '기억 게임 — 떠올리기', n: ['«Who has …?» 로 묻고 번호로 답하기 — 오늘의 질문을 게임으로'] },
      { t: 'yourturn', k: 'new', img: '12088', title: 'Tell me about a friend!', lines: ['My friend is a ___.', 'He / She has ___ hair.', 'He / She has ___ eyes.'], chips: ['boy', 'girl', 'black', 'brown'], nt: '내 이야기 — 친구 소개', n: ['강사가 맞히기: 학생이 반 친구 한 명을 설명하면 강사가 «Is it …?» 로 묻기'] },
      ...close([['I can say who I see.', 'I see a boy.'], ['I can describe hair and eyes.', 'He has blond hair and blue eyes.'], ['I can say "She doesn\'t have red hair."', "Bob doesn't have blonde hair."]], { img: 'gen:bts-02-karen', q: 'Can you talk about yourself?', ko: '나를 소개해요 — 키·머리·눈 (다음 시간)' }),
    ] },
  // ───────────────────────── 009
  { code: '009', tab: '나를 소개', unit: U3, title: 'People and Adjectives', orig: 26,
    intro: '«Is he tall? · Does she have black hair?» 로 묻고 답하고, 나를 4문장으로 소개합니다. 이야기: 캐런이 자기를 소개해요. 이제 내 차례!',
    fixed: ['❗ 10·11쪽 fat/thin 이 007 의 사람 몸 사진을 다시 씀 → 고양이·강아지', '❗ «Are you fat or thin?» 을 학생에게 직접 물음 → 뺌(아이 몸에 대한 질문)', '«What colors are your eyes?» → What color are your eyes?', '❗ 24쪽 Review 가 004 의 코끼리 문장(«The elephant is big.»)을 그대로 씀 → 이 단원 문장으로', '13~21쪽 «Talk to your teacher» 질문 9쪽이 사진 한 장씩 → 한 쪽에 모아 대화로', '6쪽 blond/blonde 규칙은 008 로 앞당김'],
    slides: [
      { t: 'cover', k: 'new', img: '12290', q: 'Can you describe yourself?', story: 'Karen tells us about herself. Then it\'s your turn!', nt: '표지 + Big Question' },
      ...open([['I can ask "Is he tall?"', '«키가 크니?» 하고 물을 수 있어요.'], ['I can ask "Does she have black hair?"', '«~이 있니?» 하고 물을 수 있어요.'], ['I can talk about myself.', '나를 4문장으로 소개할 수 있어요.']]),
      USONG_3,
      { t: 'vocab', k: 'new', hide: true, title: 'Unit 3 words 🔒', words: [['tall', '키가 큰', 'c7319'], ['short', '키가 작은', '21242'], ['fat', '뚱뚱한', 'gen:bts-02-fat-cat'], ['thin', '마른', 'gen:bts-02-thin-dog'], ['blond', '금발의 (남자)', 'gen:bts-02-blond-twins'], ['blonde', '금발의 (여자)', 'gen:bts-02-new-teacher'], ['hair', '머리카락', '15315'], ['eyes', '눈', '12953']], nt: '단원 낱말 떠올리기' },
      { t: 'rule', k: 'new', title: 'Is … ? or Does … have … ?', left: { h: 'Is he / she …?', ex: ['Is he **tall**?', "→ Yes, he is. / No, he isn't."] }, right: { h: 'Does he / she have …?', ex: ['Does she have **black hair**?', '→ Yes, she has black hair.'] }, q: 'Tall, short → Is? Hair, eyes → ?', nt: '규칙 찾기 — 두 가지 질문', n: ['어떤지(tall·short)는 Is, 가진 것(hair·eyes)은 Does … have — 학생이 먼저 가르게'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-fat-cat', q: 'Is the cat thin?', a: "No, it isn't. It is ___.", src: '10쪽', nt: '❗ 사진 교체', n: ['원본: 007 의 사람 몸 사진 «Is he thin? No, he isn\'t. He is ___.» → 고양이'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-thin-dog', q: 'Is the dog thin?', a: '___, it is.', src: '11쪽', nt: '❗ 사진 교체', n: ['원본: 크롭탑 여자 사진 → 강아지'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-black-hair-girl', q: 'Does she have black hair?', a: 'Yes, she has ___ hair.', src: '12쪽', nt: 'Does she have …?' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-black-hair-girl', q: 'Does she have blue eyes?', a: "No, she doesn't have blue eyes. She has ___ eyes.", src: '12쪽', nt: "doesn't have" },
      { t: 'discuss', k: 'fix', title: 'Talk to your teacher!', qs: ['Hello! What is your name?', 'Are you a boy or a girl?', 'Are you tall or short?', 'Do you have black hair?', 'What color are your eyes?'], chips: ['My name is ___.', 'I am ___.', 'Yes, I do. / No, I don\'t.', 'I have ___ eyes.'], src: '13~21쪽', nt: '강사와 묻고 답하기', n: ['원본 9쪽을 한 쪽에 — 질문을 번갈아: 강사가 묻고, 그다음 학생이 같은 질문으로 강사에게', '<del>What colors are your eyes?</del> → What color · «Are you fat or thin?» 은 뺐습니다'] },
      { t: 'story', k: 'fix', img: 'gen:bts-02-karen', title: 'Hi, I\'m Karen!', lines: [['Karen', "Hi! I'm Karen. I am a girl."], ['Karen', 'I am short and thin.'], ['Karen', 'I have blonde hair and brown eyes.'], ['Mango', 'Nice to meet you, Karen! 🥭']], src: '22쪽 Karen says', nt: '이야기 — 캐런의 자기소개', n: ['004·006 의 캐런이 자기를 소개합니다 — 다음 쪽 Your turn 의 본보기'] },
      { t: 'fill', k: 'new', title: 'Questions', lines: ["Is Karen a boy? — No, she ___.", 'Is Karen tall? — No, she is ___.', 'What color is her hair? — She has ___ hair.'], nt: '이야기 질문' },
      { t: 'ox', k: 'new', img: 'gen:bts-02-blond-twins', s: 'Both boys have black hair.', nt: '⭕❌', n: ['정답 ❌ → «No! Both boys have blond hair.»'] },
      { t: 'guess', k: 'new', img: '12048', open: [0, 1, 2], q: 'Who is it?', chips: ['She is a woman.', 'She has gray hair.', 'Is she tall?'], nt: 'Guess who 타일', n: ['머리가 보이는 윗줄부터 — 할머니라는 것을 맞히면 grandmother 는 BTS 3 에서!'] },
      { t: 'match', k: 'new', title: 'Who is it?', left: ['19020', 'gen:bts-02-blond-boy', '13003', 'c7123'], right: ['She has gray hair.', 'She has black hair.', 'He has blond hair.', 'She has red hair.'], nt: '짝 맞추기', n: ['짝마다 문장 읽기 — he / she 와 blond / blonde 를 함께 확인'] },
      { t: 'order', k: 'new', img: 'gen:bts-02-baby-blue', words: ['has', 'The baby', 'eyes.', 'blue'], nt: '순서 맞추기', n: ['정답: The baby has blue eyes.'] },
      { t: 'memory', k: 'new', title: 'Look for 10 seconds!', items: ['c7319', 'gen:bts-02-fat-cat', 'gen:bts-02-karen', 'gen:bts-02-green-eyes'], q: 'Look! Remember them.', a: 'Then close your eyes!', nt: '기억 게임 — 보기' },
      { t: 'memory', k: 'new', title: 'Who is it?', items: ['c7319', 'gen:bts-02-fat-cat', 'gen:bts-02-karen', 'gen:bts-02-green-eyes'], hidden: true, q: 'Number 3 — Does she have blonde hair?', a: '___, she has ___ hair.', nt: '기억 게임 — 떠올리기', n: ['번호를 부르고 «Does …?» / «Is …?» 로 묻기'] },
      { t: 'yourturn', k: 'keep', img: 'gen:bts-02-karen', title: 'Talk about yourself!', lines: ['I am a ___.', 'I am ___ and ___.', 'I have ___ hair and ___ eyes.'], chips: ['boy', 'girl', 'tall', 'short', 'black', 'brown'], src: '23쪽', nt: '내 이야기 — 4문장 소개', n: ['캐런처럼 4문장 — 이 단원의 도착점', '«thin / fat» 은 쓰지 않아도 됩니다(칩에서 뺐습니다)'] },
      { t: 'yourturn', k: 'new', img: '15347', title: 'Draw and tell!', lines: ['Draw your best friend!', 'My friend has ___ hair.', 'My friend is ___.'], nt: '그리고 말하기(선택)', n: ['시간이 남으면 1분 그리기 — 그림을 보여 주며 설명'] },
      { t: 'table', k: 'fix', small: 'Review', title: 'Unit 3 in one table', head: ['who', 'verb', 'how / what'], rows: [['He', 'is', 'tall.'], ['She', 'has', 'red hair.'], ['I', "don't have", 'blue eyes.']], tip: '어떤지 → is · 가진 것 → has / have', src: '24쪽 Review', nt: '❗ 단원 정리', n: ['원본 24쪽은 004 의 코끼리 문장을 그대로 붙여 넣음 → 이 단원 문장으로'] },
      ...close([['I can ask "Is he tall?"', "Is he tall? — No, he isn't."], ['I can ask "Does she have black hair?"', 'Does she have blue eyes?'], ['I can talk about myself.', 'I am a girl. I have black hair.']], { img: '19033', q: 'Are you ready for the BTS 2 review?', ko: '다음 시간은 BTS 2 복습 — 준비됐나요?' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 2 Review', orig: 24,
    intro: 'BTS 2 전체 복습. 게임판처럼 «스테이지» 3개와 보스 문제를 깨며 넘어갑니다.',
    fixed: ['❗ 5·6쪽 «The ball is circle / pizza is triangle» 이 그대로 복습에 나옴 → 001 과 같은 문장으로 고침', '❗ 20·21쪽 fat/thin 사람 몸 사진 → 고양이·강아지', '10쪽 «What color is The car?» 대문자 · 19쪽 «girl..»', '11쪽 색+도형 빈칸이 003 복사 → 순서 맞추기로', '23쪽 빈 쪽 → 뺌'],
    slides: [
      { t: 'cover', k: 'new', img: '19033', q: 'How much do you remember?', story: '3 stages and a boss. Can you clear them all? ⭐', nt: '표지', n: ['스테이지를 깰 때마다 별을 줍니다(화상수업: 화면에 별 스티커)'] },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 1 · Shapes 🔒', words: [['circle', '원', '18728'], ['square', '정사각형', '18729'], ['triangle', '삼각형', 'c7086'], ['rectangle', '직사각형', 'c7096'], ['heart', '하트', '12630'], ['star', '별', '17101']], nt: '1단계 — 도형(001~003)' },
      { t: 'qa', k: 'fix', img: '12553', q: 'What shape is the ball?', a: 'The ball is ___.', chips: ['round', 'square'], src: '5쪽', nt: '❗ round', n: ['원본 «The ball is circle» → round (001 과 같게)'] },
      { t: 'qa', k: 'fix', img: '12668', q: 'What shape is the pizza?', a: "It's a ___.", src: '6쪽', nt: '❗ It\'s a …' },
      { t: 'qa', k: 'keep', img: '16238', q: 'What are the colors of the rainbow?', a: 'They are red, ___, yellow, ___, blue, indigo and violet.', src: '8쪽', nt: '무지개' },
      { t: 'qa', k: 'keep', img: '16106', q: 'What color is the rose?', a: 'The rose is ___.', src: '9쪽', nt: '색' },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-blue-car', q: 'What color is the car?', a: 'The car is ___.', src: '10쪽', nt: '색', n: ['<del>The car</del> 대문자 → the car'] },
      { t: 'order', k: 'fix', img: '12630', words: ['heart.', 'yellow', "It's", 'a'], src: '7·11쪽', nt: '색 + 도형', n: ['정답: It\'s a yellow heart.'] },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 2 · Adjectives 🔒', words: [['big', '큰', '15194'], ['small', '작은', '16311'], ['long', '긴', '12004'], ['short', '짧은', '12306'], ['thin', '가는·마른', 'gen:bts-02-green-snake'], ['thick', '두꺼운', '12023']], nt: '2단계 — 형용사(004~006)' },
      { t: 'qa', k: 'fix', img: '16080', q: 'Which one is big? Which one is small?', a: 'The elephant is ___. The mouse is ___.', src: '12쪽', nt: '크다·작다', n: ['원본 코끼리·햄스터 비교를 한 사진으로'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-cardinal', q: 'Is the bird big?', a: "No, it isn't. It is small and ___.", src: '15쪽', nt: '두 가지' },
      { t: 'qa', k: 'keep', img: 'gen:bts-02-panda', q: 'Is the panda small?', a: "No, ___ ___. It is big.", src: '16쪽', nt: 'Yes / No' },
      { t: 'match', k: 'keep', title: 'Zoo animals', left: ['c7435', '12520', 'c7185', 'gen:bts-02-zebra'], right: ['tall', 'black and white', 'yellow', 'big'], src: '17쪽', nt: '짝 맞추기' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 3 · People 🔒', words: [['tall', '키가 큰', 'c7319'], ['blonde', '금발의', 'gen:bts-02-new-teacher'], ['gray', '회색의', '13003'], ['hair', '머리카락', '13008'], ['eyes', '눈', '12953'], ['fat', '뚱뚱한', 'gen:bts-02-fat-cat']], nt: '3단계 — 사람(007~009)' },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-black-hair-girl', q: 'Who is she?', a: 'She is a girl. She has ___ hair and ___ eyes.', src: '19쪽', nt: '머리·눈', n: ['<del>girl..</del> 마침표'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-thin-dog', q: 'Is the dog thin?', a: '___, it is.', src: '20·21쪽', nt: '❗ 사진 교체', n: ['원본: 사람 몸 사진 두 장 → 강아지'] },
      { t: 'guess', k: 'new', img: 'gen:bts-02-blond-boy', open: [], q: 'Boss! Who is it?', chips: ['Is it a boy?', 'Does he have blond hair?', 'Is he tall?'], nt: '보스 문제', n: ['타일을 열 때마다 질문 하나 — 001~009 질문을 모두 쓰게 됩니다', '마지막 정답: «He is a boy. He has blond hair and blue eyes.»'] },
      { t: 'yourturn', k: 'keep', img: '12071', title: 'Talk about yourself!', lines: ['I am a ___.', 'I am ___ and ___.', 'I have ___ hair and ___ eyes.'], src: '22쪽', nt: '내 이야기' },
      { t: 'ican', k: 'new', items: [['I can talk about shapes and colors.', "It's an orange triangle."], ['I can talk about animals.', 'The giraffe is tall.'], ['I can talk about people.', 'She has blonde hair and blue eyes.']], nt: 'BTS 2 전체 I can' },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 2 Unit Test', orig: 17,
    intro: '10문항 단원 시험. 화상수업에서 말로 보는 시험이라 문항마다 «말로 답하기» 를 기준으로 했습니다.',
    fixed: ['❗ 문항 4 «Is the woman thin?» — 크롭탑 여자 사진 → 강아지', '❗ 문항 10 «What color is her hair and eyes?» — 수 일치 → 두 부분으로 나눠 말하기', '문항 7·9 «your hair / your eyes» 에 손가락질하는 남자 사진 → 자기 이야기 칸으로', '문항 3 «Tell me about the shape.» 답 칸만 있음 → 색+도형 틀 제시', 'General Information 쪽 때문에 쪽 번호가 하나씩 어긋남 → 뺌'],
    slides: [
      { t: 'cover', k: 'new', img: '18792', q: 'Test time! You can do it! 💪', story: '10 questions · 1 point each', nt: '표지' },
      { t: 'qa', k: 'fix', img: 'c7096', title: '1.', q: 'What shape is it?', a: "It's a ___.", src: '문항 1', nt: '문항 1 — 도형', n: ['원본 주황 직사각형 그림 → 사진'] },
      { t: 'qa', k: 'keep', img: 'c7282', title: '2.', q: 'What color is the rabbit?', a: 'The rabbit is ___.', src: '문항 2', nt: '문항 2 — 색' },
      { t: 'qa', k: 'fix', img: '18728', title: '3.', q: 'Tell me about the shape.', a: "It's a ___ ___.", src: '문항 3', nt: '문항 3 — 색 + 도형', n: ['원본 파란 원 → 빨간 원 사진(답: It\'s a red circle.)'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-thin-dog', title: '4.', q: 'Is the dog thin?', a: '___, it is.', src: '문항 4', nt: '❗ 문항 4', n: ['원본: 크롭탑 여자 사진 → 강아지'] },
      { t: 'qa', k: 'keep', img: '12520', title: '5.', q: 'Is the giraffe short?', a: "No, it ___. It is ___.", src: '문항 5', nt: '문항 5' },
      { t: 'qa', k: 'keep', img: 'c7123', title: '6.', q: 'What color is her hair?', a: 'She has ___ hair.', src: '문항 6', nt: '문항 6' },
      { t: 'yourturn', k: 'fix', img: '12071', title: '7. What color is your hair?', lines: ['I have ___ hair.'], src: '문항 7', nt: '문항 7 — 자유 답', n: ['원본 손가락질 남자 사진 → 학생 자신이 답하는 칸'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-green-eyes', title: '8.', q: 'What color are his eyes?', a: 'He has ___ eyes.', src: '문항 8', nt: '문항 8' },
      { t: 'yourturn', k: 'fix', img: '16089', title: '9. What color are your eyes?', lines: ['I have ___ eyes.'], src: '문항 9', nt: '문항 9 — 자유 답' },
      { t: 'qa', k: 'fix', img: 'gen:bts-02-new-teacher', title: '10.', q: 'Tell me about her hair and eyes.', a: 'She has ___ hair and ___ eyes.', src: '문항 10', nt: '❗ 문항 10', n: ['<del>What color is her hair and eyes?</del> → 수 일치가 어긋남 → «Tell me about …» 로'] },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–3', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['4–6', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['7–9', 'Great!', '거의 다 왔어요 — 하나만 더'], ['10 ⭐', 'Perfect!', 'BTS 3 로 출발! 🎉']], src: '점수표', nt: '점수표', n: ['점수마다 다음에 할 일을 함께 적었습니다'] },
      { t: 'next', k: 'new', img: '18031', q: 'Who is in your family?', ko: 'BTS 3 — 우리 가족을 소개해요!', nt: '다음 권 예고', n: ['BTS 3 첫 과 «My family» 를 미리 보여 주고 끝냅니다'] },
    ] },
  ],
};
