// BTS 32 새 교재 설계 데이터 — 나쁜 습관 · 서로 다름 · 명절 · 스트레스 (Level 8 토론)
// k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
// 사진 번호 = photo-catalog.json · gen:bts-32-* = 새로 만들 사진(gen/req-bts-32.json)
import { open, close } from '../common.mjs';

const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3', U4 = 'Unit 4', RV = 'Review';
const G = k => 'gen:bts-32-' + k;
const CHANT = (song, swap) => ['⚠️ 원본 노래: «' + song + '» — 가사를 옮기지 않고 이 과 낱말로 새로 쓴 챈트입니다', '손뼉 박자에 맞춰 두 번 — 두 번째는 학생이 낱말을 바꿔 부릅니다(' + swap + ')'];
const DISC = ['정답이 없는 토론 — «I think … because …» 로 이유까지 말하게 합니다', '한 학생이 답하면 다른 학생에게 «Do you agree?» 로 넘깁니다'];

const G1 = [['I can name bad habits.', '나쁜 습관을 영어로 말할 수 있어요 — nail biting, being late, stress eating.'], ['I can say how serious a habit is.', '습관이 얼마나 심각한지 말할 수 있어요 — Nail biting is milder than smoking.'], ['I can politely help a friend break a bad habit.', '친구가 나쁜 습관을 고치도록 공손하게 말할 수 있어요 — If you slept more, you would feel better.']];
const G2 = [['I can describe how people look.', '겉모습을 말할 수 있어요 — She is tall and has curly hair.'], ['I can describe personality traits.', '성격을 말할 수 있어요 — He is helpful and confident.'], ['I can say how I am different from my friends.', '친구들과 내가 어떻게 다른지 말할 수 있어요.']];
const G3 = [['I can talk about the holidays I celebrate.', '우리 가족이 지내는 명절을 말할 수 있어요.'], ['I can describe holiday traditions and customs.', '명절 전통과 풍습을 설명할 수 있어요 — In Spain, people eat 12 grapes at midnight.'], ['I can give my opinion about Christmas.', '«크리스마스가 너무 상업적이 됐을까?» 에 내 생각을 말할 수 있어요.']];
const G4 = [['I can talk about situations that cause stress.', '스트레스를 주는 상황을 말할 수 있어요 — heavy workloads, traffic jams.'], ['I can say how I cope with stress.', '스트레스를 어떻게 푸는지 말할 수 있어요 — I listen to music.'], ["I can give advice with should and shouldn't.", "should / shouldn't 로 조언할 수 있어요 — You should set goals."]];
const GR = [['I can talk about bad habits.', '나쁜 습관과 고치는 방법을 말할 수 있어요.'], ['I can describe people and holidays.', '사람의 겉모습·성격과 명절 풍습을 말할 수 있어요.'], ['I can talk about stress and how to cope.', '스트레스와 푸는 방법을 말할 수 있어요.']];

export const COURSE = {
  head: `<h1>BTS 32 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트에 올라가 있는 BTS 32 원본 <b>132쪽</b>(6묶음)을 원고로 옮기고 원본 사진으로 확인한 뒤, BTS 1 과 같은 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · 과 끝 «I can» · 다음 시간 예고)으로 다시 짰습니다. 이 권은 <b>Level 8 토론 권</b>입니다 — 나쁜 습관과 게임 중독(Bad Habits) → 겉모습·성격, 하인스 워드 이야기(Being Different) → 세계의 명절 풍습과 크리스마스(Holidays) → 스트레스와 푸는 법(Stress) → 복습 → 시험. 문법은 <b>Wh- 질문 · Yes/No 질문</b>으로 의견을 묻고 답하는 데 쓰고, 과마다 한 가지(비교 milder · is/has · 공손한 조언 would · should/shouldn't)를 «규칙 찾기» 로 짚습니다.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>원본의 <b>낱말·키워드·토론 질문·읽기 글(게임 중독 · 하인스 워드 · 스페인·그리스·필리핀·노르웨이 풍습 · 크리스마스 · 카를로스 곤) · 활동 상황(친구의 나쁜 습관 · 전학생 · 낡은 옷 · 염색 설득 · 과학 과제 · 상사 · 교통 체증)</b>은 그대로입니다. 틀린 한국어 뜻(30곳 넘게)·문법·오래된 사실만 고쳤고, 같은 질문이 쪽마다 반복되던 키워드 쪽은 표·짝 맞추기·기억 게임으로 묶었습니다.</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>, <b>⭕❌</b>, <b>Guess who 타일</b>, <b>짝·기억 게임</b>, <b>Yoona 와 Jay 의 이어지는 이야기</b>(새벽 2시 게임 습관 → 염색 설득 → 크리스마스 파티 준비 → 시험 스트레스 → 복습에서 해결), <b>내 말로(Your turn)</b>, <b>I can ✅</b>, <b>다음 시간 예고</b>.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>점선 상자(«새 사진 생성 중»)는 맞는 사진이 없어 새로 만드는 자리입니다(이 권 요청 <b>35장</b> — 새벽 2시에 엄마에게 들킨 게이머, 토스트를 물고 교문으로 뛰는 아이, 자정에 포도를 볼 가득 문 가족, 양파로 아이 머리를 톡톡 치는 그리스 아빠, 사무실 한가운데서 요가 나무 자세를 하는 아빠처럼 «와!» 또는 «풉!» 하고 볼 장면 위주). 원본의 담배 연기·술병 사진은 아이 교재에 맞게 순한 장면으로 바꿨고, 실존 인물(하인스 워드·카를로스 곤)은 얼굴 사진 대신 경기·공장 장면으로 바꿨습니다.</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>고친 뜻 승인</b> — 원본 한국어 뜻이 틀린 곳: Stress Eating «스트레스를 받는»→스트레스성 폭식 · Continuum «연속»→정도를 나타낸 선 · Intensity «강렬»→강도 · Institutes «기관»→학원 · Starve to death «배고파 죽을 것 같아»→굶어 죽다 · Collapsed «무너졌다»→쓰러졌다 · Fat «지방»→뚱뚱한 · Fit «적당한»→몸이 탄탄한 · Fair «공정한»→(피부가) 흰 · Rosy «낙관적»→발그레한 · Tan «태우다»→햇볕에 그을린 · <b>Bald «용감한»→대머리의</b> · Straight «직진»→곧은 생머리 · Sociable «진화적인»→사교적인 · Persistent «지속성 있는»→끈기 있는 · Encouraging «격려»→힘을 북돋아 주는 · Quarrelsome «다툼»→걸핏하면 다투는 · Rude «거친»→무례한 · Drafted «초안»→(선수로) 뽑혔다 · Celebrity «명성»→유명인 · Accent «강세»→말투 · Bullies «괴롭힘»→괴롭히는 아이들 · Practical (joke) «실용적인»→짓궂은 장난 · Stroke «때리기»→(시계가) 땡 치는 소리 · Represent «대표»→나타내다 · Host «주인»→(파티를) 열다 · Competitions «경쟁»→대회 · Circumstances «상황»→여건 · Squeeze «압착»→꽉 쥐다 · Fairly «공정하게»→꽤 · Demanding «요구하는»→힘이 많이 드는.</li>
<li><b>오래된 사실·사실 오류</b> — ① 001 셧다운제: 원본은 «자정~오전 6시 16세 미만 PC방 출입 금지» 라고 현재형으로 적었는데, 실제 제도는 <b>심야 온라인 게임 접속 제한</b>이었고 <b>2021년 폐지</b>됐습니다 → 과거형 + «2021년에 끝났다» 로 고쳤습니다. ② 001 «2014년 게임 매출 815억 달러» — 오래된 숫자라 «in 2014» 를 살려 과거형으로. ③ 004 하인스 워드: «has played for the Steelers since 1998» → <b>1998~2011년 선수, 2012년 은퇴</b>로. ④ 010 카를로스 곤: 원본 «두 회사가 합병했다(merged)» → 실제로는 <b>1999년 제휴(alliance)</b>라 «joined together» 로 고쳤습니다. 또 곤은 <b>2018년 일본에서 체포되고 2019년 해외로 도주</b>한 인물이라, «바쁘게 일한 CEO» 롤모델 예시로 둘지 다른 인물로 바꿀지 정해 주세요(시안은 원본 글을 과거형으로 두었습니다).</li>
<li><b>아이 교재에 맞지 않는 소재</b> — 001 «Excessive Drinking(지나친 음주)» 낱말과 흡연 사진, «아기가 굶어 죽었다 · 50시간 게임 뒤 숨졌다» 는 원본 글 그대로 두되 사진은 순하게 바꿨습니다. 초등 반에서는 이 두 문단을 강사가 건너뛸지.</li>
<li><b>몸을 묘사하는 낱말</b> — 004 skinny · overweight 는 표에 두고 ⚠️ 표시(«남에게 쓰면 무례하다» 는 강사 메모)를, fat 은 표에서 빼고 말로만 다루게 했습니다. gigantic(원본 키 낱말)은 사람에게 쓰지 않는 말이라 표에서 뺐습니다(very tall 은 말로). 이렇게 둘지.</li>
<li><b>원본 쪽 순서</b> — 004 하인스 워드 이야기는 원본 15쪽(고등학교·NFL)이 16쪽(탄생·어린 시절)보다 앞에 있어 이야기 순서로 바꿨습니다. 004 «Hines Ward Helping Hands Foundation» 이 지금도 활동하는지 확인이 필요합니다.</li>
<li><b>마치는 노래</b> — 원본 «Bad Habits»(가사 오류: Eat lot of chocolates · Be sad always) · «Everyone Is Different» · «Jingle Bells». 가사를 옮기지 않고 새 챈트로 바꿨습니다(곡조는 자체 녹음 권장). 010 은 원본에 노래가 없어 챈트를 넣지 않았습니다.</li>
<li><b>새로 만들 사진 35장</b> — 점선 자리(힉스필드 크레딧).</li>
</ol></div>`,
  lessons: [
  // ───────────────────────── 001 Bad Habits
  { code: '001', tab: '나쁜 습관', unit: U1, title: 'Bad Habits', orig: 28,
    intro: '나쁜 습관 — 스트레스성 폭식·도박·손톱 물어뜯기·지각·전자기기 과다 사용을 말하고, 가벼운 것부터 심각한 것까지 줄 세웁니다. 읽기: 게임 중독의 상황·문제·해결책. 이야기: 새벽 2시까지 게임하는 Jay 에게 Yoona 가 공손하게 말해요.',
    fixed: ['표지 권 번호 <del>Bubble Tea Speaking 30</del> → 32', '<del>Stress Eating 스트레스를 받는</del> → 스트레스성 폭식 · <del>Continuum 연속</del> → 정도를 나타낸 선 · <del>Intensity 강렬</del> → 강도', '<del>Institutes 기관</del> → 학원 · <del>Starve to death 배고파 죽을 것 같아</del> → 굶어 죽다 · <del>Collapsed 무너졌다</del> → 쓰러졌다', '<del>earn up to $15,000 per month games</del> → per month · <del>played on online game at a internet café</del> → played an online game at an internet café · <del>In-many other</del> → In many other · <del>died in internet café</del> → in internet cafés', '셧다운제 설명을 과거형으로 + 2021년 폐지 사실 추가(사람이 정할 것 2번)', '토론 5번 <del>Do you laws that regulate…</del> → Do you think laws that regulate…', '<del>Have you ever drunk coffee?</del>(어린 학생에게 권하는 듯 들림) → Have you ever tasted coffee?', '노래 <del>Eat lot of chocolates · Be sad always</del>(슬픔은 습관이 아님) → 새 챈트', '담배 연기·술병 사진 → 순한 장면'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-habits'), q: 'Why is it so hard to stop a bad habit?', story: "It's 2 a.m. Jay is still playing a game on his phone. Uh-oh — here comes Mom!", nt: '표지 + Big Question', n: ['불 켜진 방에서 들킨 게이머 장면으로 웃으며 시작 — «What is his bad habit?»', '끝날 때 «It is hard to stop because …» 로 답하는 것이 목표'] },
      ...open(G1, 'Lesson Goals (Wh- Questions · Yes/No Questions · Grammar from Level 1–7)'),
      { t: 'discuss', k: 'keep', title: 'Warm up', img: '17258', qs: ['What bad habits do people have?', "Why can't they stop?", 'Do you have a bad habit? A little one is OK!'], chips: ['People often …', 'because …'], src: '4쪽 Warm up', nt: '생각 말하기', n: ['원본 두 질문 + 세 번째는 «작은 습관이면 괜찮아요» 로 부담 없이', '사진: 밤늦게 화면 앞에서 과자를 먹는 십대'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Bad habits 🔒', cols: 4, words: [['stress eating', '스트레스성 폭식', G('stress-eating')], ['gambling', '도박', G('gambling')], ['addiction', '중독', '14642'], ['nail biting', '손톱 물어뜯기', '16813'], ['heavy drinking', '지나친 음주', G('drinking')], ['being late', '지각하기', G('being-late')], ['smoking', '흡연', '17195'], ['too much gadget use', '기기 과다 사용', G('gadgets')]], src: '3·5쪽 Vocabulary + 7~13쪽 Keywords', nt: '낱말 — 뜻 가리기', n: ['<del>Stress Eating 스트레스를 받는</del> → 스트레스성 폭식 · <del>Being Late 늦음</del> → 지각하기', '키워드 쪽에만 있던 smoking·excessive use of gadgets 를 낱말표에 합쳤습니다', '사진만 보고 영어로 먼저 말하게 한 뒤 다음 쪽에서 공개'] },
      { t: 'vocab', k: 'keep', title: 'Bad habits', cols: 4, words: [['stress eating', '스트레스성 폭식', G('stress-eating')], ['gambling', '도박', G('gambling')], ['addiction', '중독', '14642'], ['nail biting', '손톱 물어뜯기', '16813'], ['heavy drinking', '지나친 음주', G('drinking')], ['being late', '지각하기', G('being-late')], ['smoking', '흡연', '17195'], ['too much gadget use', '기기 과다 사용', G('gadgets')]], nt: '뜻 공개', n: ['강사가 사진을 가리키면 학생이 «This is …» 로 말하기', '흡연 사진은 원본 담배 연기 대신 «폐 모형을 보여 주는 의사» 로'] },
      { t: 'match', k: 'new', title: 'What is the habit?', left: ['18716', '17269', '18354', '16174'], right: ['waking up late', 'nail biting', 'eating too much sugar', 'too much gadget use'], nt: '짝 맞추기', n: ['정답: 1-B(축구 보며 손톱 무는 아이) · 2-D(밤늦게 게임) · 3-C(도넛) · 4-A(늦잠)', '맞힌 뒤 «He has a bad habit. He …» 로 한 문장'] },
      { t: 'discuss', k: 'fix', title: 'Talk about it!', img: '17262', qs: ['Who do you know with this bad habit?', 'Why do people have this habit?', 'Which bad habit is the hardest to stop?'], chips: ['My … has this habit.', 'I think it is because …'], src: '7~13쪽 Keywords (Talk about it!)', nt: '키워드 토론', n: ['원본은 습관 7개마다 같은 두 질문을 한 쪽씩 반복 → 앞 낱말 쪽을 다시 띄워 사진을 가리키며 돌아가며 묻습니다', '세 번째 질문(가장 고치기 힘든 습관)은 다음 쪽 «중독» 으로 넘어가는 다리'] },
      { t: 'read', k: 'keep', title: 'Keyword: Addiction', img: G('coffee'), paras: ["An **addiction** is a behavior that someone can't stop doing, even though they know it is wrong.", 'Some addictions are **mild** (not very harmful), while others are **severe** (very harmful).'], gloss: [['behavior', '행동'], ['harmful', '해로운']], src: '13쪽 Keyword Addiction', nt: '읽기 — 중독이란?', n: ['원본 문장 그대로', '사진: 커피잔 세 개를 한꺼번에 든 졸린 회사원 — «Is this mild or severe?»'] },
      { t: 'discuss', k: 'fix', title: 'Think about it!', img: '18326', qs: ['Caffeine and smoking are common addictions. Which is worse?', 'Do you know anyone addicted to caffeine? How many cups a day?', 'Why do some people drink so much coffee?'], chips: ['I think … is worse because …'], src: '14쪽 Keyword Addiction', nt: '카페인 토론', n: ['원본 «Look at the pictures of two common addictions» 는 흡연 사진이 있어야 성립 → 사진 없이도 되게 두 중독 이름을 문장에 넣었습니다', '<del>Have you ever drunk coffee?</del> → tasted(어린 학생에게 권하는 듯 들리지 않게)'] },
      { t: 'read', k: 'fix', small: 'Keyword: Continuum', title: 'Mild ↔ Severe 📏', img: G('continuum'), paras: ['A **continuum** is a chart that measures the **intensity** of different things.', 'The mildest things go on the left, while the most severe ones go on the right.', 'Decide where each bad habit goes with your teacher.'], gloss: [['continuum', '정도를 나타낸 선'], ['intensity', '강도']], src: '15쪽 Keyword Continuum', nt: '연속선 만들기', n: ['<del>Continuum 연속</del> → 정도를 나타낸 선 · <del>Intensity 강렬</del> → 강도', '원본: 사진 7장을 Mild↔Severe 선에 놓기 → 화상수업에서는 학생이 습관 이름을 1(가벼움)~7(심각함) 번호로 말합니다'] },
      { t: 'rule', k: 'new', title: 'milder or more severe?', left: { h: 'short word → -er / -est', ex: ['mild → **milder** → **the mildest**', 'Nail biting is **milder** than smoking.'] }, right: { h: 'long word → more / the most', ex: ['severe → **more severe** → **the most severe**', 'Gambling is **more severe** than being late.'] }, q: 'Why do we say "milder" but "more severe"?', nt: '규칙 찾기 — 비교', n: ['연속선을 말로 옮기려면 비교 표현이 필요합니다 — 원본 «the mildest / the most severe» 에서 규칙을 찾게', '짧은 말은 -er, 긴 말은 more(Level 1~7 문법 복습)'] },
      { t: 'yourturn', k: 'new', title: 'My continuum', img: '13306', lines: ['___ is the mildest bad habit.', '___ is milder than ___.', '___ is the most severe because ___.'], chips: ['nail biting', 'being late', 'stress eating', 'smoking', 'gambling'], nt: '내 말로 — 줄 세우기', n: ['정답이 없습니다 — 친구와 순서가 다르면 «Why?» 로 토론', '비교 문장 세 개를 꼭 완성하게'] },
      { t: 'table', k: 'fix', small: 'Story words', title: 'Before we read 📖', head: ['word', '뜻', 'word', '뜻'], rows: [['institute', '학원', 'revenue', '매출·수입'], ['competition', '경쟁', 'estimated', '추정되는'], ['intense', '치열한', 'social problem', '사회 문제'], ['internet café', 'PC방', 'starve to death', '굶어 죽다']], src: '16·17쪽 Story Time words', nt: '읽기 낱말', n: ['<del>Institutes 기관</del> → 학원 · <del>Intense 심한</del> → 치열한 · <del>Starve to death 배고파 죽을 것 같아</del> → 굶어 죽다', 'obsessively·virtual·collapsed·socializing·proposed·treatment·regulates 는 읽기 글 아래 뜻풀이로 옮겼습니다'] },
      { t: 'read', k: 'keep', small: 'Game Addiction: The Situation', title: 'So much studying ①', img: G('pc-bang'), paras: ['Students do a lot of studying. They spend many hours every day going to school and various learning **institutes**.', 'They study so hard because **competition** for a place at top universities is **intense**.', "Because of this, students don't have a lot of time for sports. When they do have free time, many choose to play **online games**."], src: '18쪽 Story Time', nt: '읽기 ① 상황', n: ['원본 문장 그대로(한 문단을 세 덩이로)', '«Why don\'t students have time for sports?» 로 확인'] },
      { t: 'read', k: 'fix', small: 'Game Addiction: The Situation', title: 'Big business ②', img: '16796', paras: ['Online gaming is very popular. **Game arcades** are almost everywhere you look in big cities.', 'Gaming is also big business. International video game **revenue** was **estimated** to be $81.5 billion in 2014.', 'Some professional gamers have become celebrities. The highest-paid players can earn up to $15,000 per month!'], src: '18쪽 Story Time', nt: '읽기 ② 큰 사업', n: ['<del>per month games</del> → per month · 2014년 숫자는 과거형으로(사람이 정할 것 2번)', '마지막 문장 «Many children now grow up with dreams of being a professional gamer» 는 다음 질문으로: «Do you want to be a pro gamer?»'] },
      { t: 'read', k: 'fix', small: 'Game Addiction: The Problem', title: 'A dark side ③', img: '17269', paras: ['But there is a dark side. Many doctors and scientists say that gaming addiction is a big **social problem**.', 'In 2010, a baby **starved to death** while her parents **obsessively** played an online game at an internet café.'], gloss: [['obsessively', '집착하듯이'], ['social problem', '사회 문제']], src: '19쪽 The Problem', nt: '읽기 ③ 문제', n: ['<del>played on online game at a internet café</del> → played an online game at an internet café', '⚠️ 무거운 사례 — 초등 반이면 강사가 요약만(사람이 정할 것 3번)'] },
      { t: 'read', k: 'fix', small: 'Game Addiction: The Problem', title: 'Wasted time ④', img: '16862', paras: ['In other cases, people have **collapsed** and died in internet cafés after playing games for 50 hours or more.', 'Many other young people waste time playing games. They could spend that time studying, exercising, **socializing** with real people, or just relaxing.'], gloss: [['collapse', '쓰러지다'], ['socialize', '사람들과 어울리다']], src: '19쪽 The Problem', nt: '읽기 ④ 잃는 시간', n: ['<del>In-many other</del> → In many other · <del>in internet café</del> → in internet cafés · <del>Collapsed 무너졌다</del> → 쓰러졌다', '사진은 «대신 할 수 있는 일»(친구와 수다) — «What could they do instead?»'] },
      { t: 'read', k: 'fix', small: 'Possible Solutions', title: 'Hospitals and classes ⑤', img: '18224', paras: ['The South Korean government knew about the problem and **proposed** several solutions.', 'First, it paid a lot of money to set up hospitals that **treat** game addiction. There, game addicts could get special **treatment**.', 'Schools also offered classes about the dangers of gaming addiction.'], gloss: [['propose', '제안하다'], ['treatment', '치료']], src: '20쪽 Possible Solutions', nt: '읽기 ⑤ 해결책', n: ['원본 현재형 → 과거형(아래 법이 2021년에 끝나 한 이야기로 맞춤)', '<del>game addicts can be cured</del> → could get special treatment(«완치» 는 과장)'] },
      { t: 'read', k: 'fix', small: 'Possible Solutions', title: 'A new law ⑥', img: '13074', paras: ['In 2011, Korea made a law that **regulated** online games: from midnight to 6 a.m., children under 16 could not play.', 'Many people opposed it. **Critics** said families should decide for themselves. In 2021, the law ended.'], gloss: [['regulate', '규제하다'], ['critic', '비판하는 사람']], src: '20쪽 Possible Solutions', nt: '읽기 ⑥ 셧다운제', n: ['원본은 «PC방 출입 금지» 를 현재형으로 → 실제 제도(심야 게임 접속 제한)·2021년 폐지로 고침 — 사람이 정할 것 2번', '<del>12 a.m. To 6a.m.</del> → from midnight to 6 a.m.'] },
      { t: 'ox', k: 'new', img: '12238', s: 'Everyone agreed with the new law.', nt: '⭕❌', n: ['정답 ❌ → «No! Many people opposed it.»', '이유 두 가지(가족의 자유 · 부모 신분증)까지 말하면 성공'] },
      { t: 'discuss', k: 'keep', title: 'Discussion ①', img: '12174', qs: ['What is computer game addiction?', 'Why do you think so many people are addicted to gaming?', 'Do you know anyone who you think plays too many video games? If you do, have you ever talked to them about it?'], src: '21쪽 Discussion 1~3', nt: '토론 ①', n: DISC },
      { t: 'discuss', k: 'fix', title: 'Discussion ②', img: '17150', qs: ['What negative effects does gaming addiction have on people?', 'What is the right way to stop people from becoming addicted to gaming?', 'Do you think laws that regulate internet cafés are the right way to do it?'], src: '21쪽 Discussion 4·5', nt: '토론 ②', n: ['<del>Do you laws that regulate…</del> → Do you think laws that regulate…', '5번은 두 질문으로 나눴습니다'] },
      { t: 'story', k: 'new', img: G('yawn'), title: 'Yoona and Jay: 2 a.m. again', lines: [['Yoona', 'Jay, you look so tired! What happened?'], ['Jay', 'I played games on my phone until 2 a.m. again.'], ['Yoona', 'Oh no! If you slept more, you would feel much better.'], ['Jay', "You're right. But it's so hard to stop!"], ['Mango', 'Try this: leave your phone in the kitchen at night! 📱']], nt: '이어지는 이야기 ①', n: ['권 전체를 잇는 Yoona·Jay 이야기 — 이 습관은 Review 에서 해결됩니다', '«If you slept more, you would …» — 다음 쪽 «공손하게 말하기» 의 본보기'] },
      { t: 'rule', k: 'new', title: 'Rude or polite?', left: { h: 'Rude 😠', ex: ['Stop biting your nails!', 'You are always late!'] }, right: { h: 'Polite 😊', ex: ['If you stopped biting your nails, they **would** look nicer.', "Why don't you try setting an alarm?"] }, q: 'Which one would you like to hear from a friend? Why?', nt: '규칙 찾기 — 공손하게', n: ['원본 활동 «Tell them politely how their life would be better» 에 필요한 말투를 먼저 비교', 'If + 과거형, would + 동사원형 — 용어 대신 «부드럽게 말하는 틀» 로'] },
      { t: 'yourturn', k: 'fix', title: 'Try it! Help a friend', img: '18146', lines: ["I'm a little worried about you because you ___.", 'If you stopped ___, you would ___.', "Why don't you try ___?"], chips: ['bite your nails', 'feel healthier', 'sleep better', 'setting an alarm'], src: '22~25쪽 Activity Time (Try it!)', nt: '역할극 — 공손하게 말리기', n: ['원본 4쪽(손톱 · 밤늦은 태블릿 · 흡연 친구)을 한 쪽 틀로 — 강사가 그 인물을 연기하고 학생이 말립니다', '두 번째는 역할을 바꿔 학생이 나쁜 습관 인물이 됩니다(Have fun!)'] },
      { t: 'guess', k: 'new', img: G('guess-tablet'), open: [4], q: 'What bad habit does this person have?', chips: ['Is it late at night?', 'Is he hiding?', 'He uses his tablet too much!'], nt: 'Guess who 타일', n: ['정답: 이불 속에서 밤늦게 태블릿(excessive use of gadgets)', '타일을 열 때마다 Yes/No 질문 한 개 — 이 과 문법(Yes/No questions)'] },
      { t: 'song', k: 'fix', title: 'Bad Habits Chant 🎵', img: G('chant-habits'), lines: ['Wake up late? Run, run, run!', "Bite your nails? That's no fun!", 'Too much candy, too much screen —', 'Break the habit, keep it clean!'], src: '27쪽 Bad Habits (song)', nt: '마치는 챈트', n: CHANT('Bad Habits', 'candy → coffee, screen → games') },
      ...close(G1, { img: G('next-different'), q: 'Why does she look so different?', ko: '왜 저 친구만 달라 보일까요? 다음 시간 — Being Different!' }),
    ] },
  // ───────────────────────── 004 Being Different
  { code: '004', tab: '서로 다름', unit: U2, title: 'Being Different', orig: 24,
    intro: '겉모습(체격·키·피부·머리)과 성격(좋은 점·나쁜 점)을 말합니다. 읽기: 한국에서 태어난 미식축구 스타 하인스 워드. 활동: 전학생·낡은 옷·염색 설득. 이야기: Yoona 가 염색하고 싶어 부모님을 설득해요.',
    fixed: ['<del>Overweight 중량 초과</del> → 과체중인 · <del>Fat 지방</del> → 뚱뚱한 · <del>Fit 적당한</del> → 몸이 탄탄한 · <del>muscular 근육질</del> → 근육질의', '<del>Fair 공정한</del> → (피부가) 흰 · <del>Rosy 낙관적</del> → 발그레한 · <del>Tan 태우다</del> → 햇볕에 그을린', '<del>Bald 용감한</del> → 대머리의 · <del>Straight 직진</del> → 곧은 생머리', '<del>Encouraging 격려</del> → 힘을 북돋아 주는 · <del>Sociable 진화적인</del> → 사교적인 · <del>Persistent 지속성 있는</del> → 끈기 있는', '<del>Rude 거친</del> → 무례한 · <del>Self-centered 자기 중심</del> → 자기만 생각하는 · <del>Quarrelsome 다툼</del> → 걸핏하면 다투는', '<del>Drafted 초안</del> → (선수로) 뽑혔다 · <del>celebrity 명성</del> → 유명인 · <del>Accent 강세</del> → 말투 · <del>Bullies 괴롭힘</del> → 괴롭히는 아이들 · <del>Practical 실용적인</del> → (practical joke) 짓궂은 장난 · <del>Argument 논의</del> → 주장', 'gigantic(사람에게 안 씀) → very tall', '하인스 워드 이야기 쪽 순서(15·16쪽) 뒤바뀜 → 이야기 순서로 · <del>has played for the Steelers since 1998</del> → played from 1998 to 2011 · <del>more then</del> → more than', '<del>dying your hair</del> → dyeing your hair'],
    slides: [
      { t: 'cover', k: 'new', img: G('next-different'), q: 'How are you different from your friends?', story: 'Every person is unique. Even twins are a little bit different!', nt: '표지 + Big Question', n: ['지난 시간 예고 사진 그대로 — «Why does she look so different?» 에 먼저 답하게', '끝날 때 «I am different because …» 로 말하는 것이 목표'] },
      ...open(G2, 'Lesson Goals (Physical Characteristics · Personality Traits)'),
      { t: 'discuss', k: 'fix', title: 'Warm up', img: '19020', qs: ['Every person is unique. How are you different from your friends?', 'Physical characteristics are how you look on the outside. How do these twins look different?'], chips: ['One twin has …', 'The other twin has …'], src: '4·6쪽 Warm up + Physical Characteristics', nt: '생각 말하기', n: ['원본 6쪽 설명(«Except for identical twins, everyone looks a little bit different») 을 쌍둥이 사진 질문으로', '곱슬 빨강 머리·주근깨 vs 곧은 검은 머리 — 다음 쪽 낱말이 사진에 다 있습니다'] },
      { t: 'table', k: 'fix', small: 'Keywords: Physical characteristics', title: 'Build & height', head: ['Build 💪', '뜻', 'Height 📏', '뜻'], rows: [['slim', '날씬한', 'short', '키가 작은'], ['skinny', '깡마른 ⚠️', 'tall', '키가 큰'], ['fit / muscular', '탄탄한 / 근육질의', 'petite', '작고 아담한'], ['overweight', '과체중인 ⚠️', 'average height', '보통 키']], src: '7·8쪽 Build · Height', nt: '낱말 ① 체격·키', n: ['<del>Overweight 중량 초과</del> → 과체중인 · <del>Fat 지방</del> → 뚱뚱한 · <del>Fit 적당한</del> → 몸이 탄탄한', '<del>Gigantic</del>(건물·동물에 쓰는 말) → very tall — 사람이 정할 것 4번', '몸 사진 대신 표로 — 몸매를 비교하는 사진은 놀림거리가 되기 쉽습니다', '⚠️ 표시(skinny·overweight·fat)는 남에게 쓰면 무례한 말 — 나를 말하거나 이야기 속 인물에만 쓰게 짚습니다(fat 은 표에서 빼고 말로만)'] },
      { t: 'table', k: 'fix', small: 'Keywords: Physical characteristics', title: 'Complexion & hair', head: ['Complexion 🙂', '뜻', 'Hair 💇', '뜻'], rows: [['dark / light', '어두운 / 밝은', 'straight / curly', '생머리 / 곱슬'], ['fair / pale', '흰 / 창백한', 'permed', '파마한'], ['rosy / tan', '발그레한 / 그을린', 'bald', '대머리의'], ['freckles', '주근깨', 'blond', '금발의']], src: '9·10쪽 Complexion · Hair', nt: '낱말 ② 피부·머리', n: ['<del>Fair 공정한</del> → (피부가) 흰 · <del>Rosy 낙관적</del> → 발그레한 · <del>Tan 태우다</del> → 햇볕에 그을린', '<del>Bald 용감한</del> → 대머리의 · <del>Straight 직진</del> → 곧은 생머리', '강사가 뜻 칸을 손으로 가리고 영어→한국어 먼저 맞히기'] },
      { t: 'rule', k: 'new', title: 'is or has?', left: { h: 'is + describing word', ex: ['She **is** tall and slim.', 'He **is** tan.'] }, right: { h: 'has + a thing', ex: ['She **has** curly hair.', 'He **has** freckles.'] }, q: 'When do we say "is"? When do we say "has"?', nt: '규칙 찾기', n: ['겉모습을 말할 때 가장 많이 틀리는 곳: «She is curly hair.» ✘', '«몸 전체 모습 = is · 가진 것(머리·주근깨) = has» 를 학생이 찾게'] },
      { t: 'guess', k: 'new', img: '19020', open: [0, 5], q: 'Describe the twins!', chips: ['One twin has curly red hair.', 'She has freckles.', 'Her sister has straight black hair.'], nt: 'Guess who — 묘사하기', n: ['타일을 열 때마다 보이는 것을 is/has 문장으로 — 다 열면 두 쌍둥이의 다른 점 세 가지'] },
      { t: 'yourturn', k: 'keep', title: 'Think about it!', img: '21347', lines: ['My build: I am ___.', 'My height: I am ___.', 'My hair: I have ___ hair.', 'My friend and I are different because ___.'], chips: ['fit', 'average height', 'straight', 'short'], src: '7~10쪽 Think about it!', nt: '내 말로 — 나의 겉모습', n: ['원본 네 쪽의 «What is your … characteristic? How are they similar to your friends?» 를 한 쪽으로', '사진: 오빠와 지문을 비교하는 아이 — «Even our fingerprints are different!»'] },
      { t: 'vocab', k: 'fix', hide: true, small: 'Keywords: Personality traits', title: 'Positive traits 👍🔒', cols: 4, words: [['helpful', '도움이 되는', '12393'], ['humble', '겸손한', G('humble')], ['confident', '자신감 있는', '16908'], ['encouraging', '힘을 북돋아 주는', '12937'], ['optimistic', '낙관적인', G('optimistic')], ['sociable', '사교적인', '15597'], ['persistent', '끈기 있는', '21210']], src: '11·12쪽 Personality Traits', nt: '낱말 ③ 좋은 성격 — 가리기', n: ["원본 11쪽 설명(«A person's personality traits are found inside them. They make up your character.») 을 강사가 읽고 시작", '<del>Encouraging 격려</del> → 힘을 북돋아 주는 · <del>Sociable 진화적인</del> → 사교적인 · <del>Persistent 지속성 있는</del> → 끈기 있는', 'persistent: 같은 나무를 계속 쪼는 딱따구리 — 웃음 포인트'] },
      { t: 'vocab', k: 'keep', small: 'Keywords: Personality traits', title: 'Positive traits 👍', cols: 4, words: [['helpful', '도움이 되는', '12393'], ['humble', '겸손한', G('humble')], ['confident', '자신감 있는', '16908'], ['encouraging', '힘을 북돋아 주는', '12937'], ['optimistic', '낙관적인', G('optimistic')], ['sociable', '사교적인', '15597'], ['persistent', '끈기 있는', '21210']], nt: '뜻 공개', n: ['원본 질문 «What positive personality traits do you have? Describe your personality.» 를 바로 묻습니다'] },
      { t: 'table', k: 'fix', small: 'Keywords: Personality traits', title: 'Negative traits 👎', head: ['trait', '뜻', 'Example'], rows: [['rude', '무례한', 'He never says "thanks."'], ['arrogant', '거만한', 'She thinks she is the best.'], ['lazy', '게으른', 'He never does chores.'], ['self-centered', '자기만 생각하는', 'He only talks about himself.']], src: '13쪽 Negative Traits', nt: '낱말 ④ 나쁜 성격', n: ['<del>Rude 거친</del> → 무례한 · <del>Self-centered 자기 중심</del> → 자기만 생각하는 · <del>Quarrelsome 다툼</del> → 걸핏하면 다투는', '뜻을 사진 대신 «행동 예문» 으로 — 사람 얼굴에 나쁜 성격 딱지를 붙이지 않게', 'lazy·dishonest·quarrelsome·unfriendly 는 강사가 행동 예문과 함께 말로 덧붙입니다(«He never does chores.» «She often tells lies.» «She argues all the time.»)', '원본 질문 «What negative traits do you have?» 는 «한 가지만, 고치고 싶은 것» 으로 부드럽게'] },
      { t: 'match', k: 'new', title: 'Which trait is it?', left: ['15608', '16667', '12308', '14568'], right: ['sociable', 'persistent', 'confident', 'helpful'], nt: '짝 맞추기', n: ['정답: 1-B(비 오는 날 암벽을 계속 오름) · 2-D(무거운 상자를 들어 줌) · 3-A(친구와 수다) · 4-C(당당한 발표)', '앞 낱말 쪽과 다른 사진 — 사진이 아니라 뜻을 떠올리게'] },
      { t: 'ox', k: 'new', img: '12006', s: 'A humble person always talks about how great they are.', nt: '⭕❌', n: ['정답 ❌ → «No! That person is arrogant. A humble person doesn\'t show off.»'] },
      { t: 'read', k: 'fix', small: 'Story Time: Finding Football', title: 'Hines Ward ①', img: '12036', paras: ['Hines Ward is a famous Korean-American football player. He **is recognized** as one of the best players in the sport. However, success was not easy for him.', 'He was born in Seoul in 1976. His father was an African-American U.S. soldier, and his mother was Korean. A year later, the family moved to Atlanta, Georgia, in the USA.'], gloss: [['recognize', '인정하다'], ['soldier', '군인']], src: '16쪽 Finding Football', nt: '읽기 ① 태어남', n: ['원본 16쪽 = 이야기의 시작(원본은 15쪽과 순서가 뒤바뀜)', '실존 인물 얼굴 사진 대신 아이를 감싸는 엄마 사진'] },
      { t: 'read', k: 'fix', small: 'Story Time: Finding Football', title: 'Hines Ward ②', img: G('football'), paras: ["When Hines was two, his father left. His mother raised him alone, but she couldn't speak English well.", "At school, he didn't **fit in**, and kids **made fun of** him. In high school he found football, and his coach **pushed** him to succeed."], gloss: [['fit in', '어울리다'], ['make fun of', '놀리다']], src: '16·15쪽', nt: '읽기 ② 어린 시절·미식축구', n: ['<del>didn\'t fit in with either group</del> → 두 무리를 풀어 썼습니다(뜻이 분명하게)', '«How did he feel at school?» — 다음 쪽 활동(전학생)과 이어집니다'] },
      { t: 'read', k: 'fix', small: 'The Hines Ward Story', title: 'Hines Ward ③', img: G('ward-kids'), paras: ['In 1998, he **was drafted** into the NFL. He played for the Pittsburgh Steelers until 2011 and won two Super Bowls.', 'In 2006, he visited Korea to help **biracial** children. His charity gives them free classes and sports.'], gloss: [['draft', '(선수로) 뽑다'], ['biracial', '부모의 인종이 서로 다른']], src: '15·17쪽', nt: '읽기 ③ 스타가 되어 한국으로', n: ['<del>has played … since 1998</del> → until 2011(2012년 은퇴) · <del>more then</del> → more than — 사람이 정할 것 3번', '원본 «Ward wants Koreans to accept these children, just like they accepted a celebrity like him» 은 다음 토론 6번에서 말로'] },
      { t: 'discuss', k: 'keep', title: 'Discussion ①', img: '16209', qs: ['Who is Hines Ward?', 'What made his childhood so difficult? How do you think he managed it?', 'How did Ward succeed in life? How do you think he did it?'], src: '18쪽 Discussion 1~3', nt: '토론 ①', n: DISC },
      { t: 'discuss', k: 'fix', title: 'Discussion ②', img: '12595', qs: ["What do you think is Ward's greatest achievement?", 'What did Ward do in Korea in 2006? Why do you think this was important to him?', "Do you think Ward's charity will help raise awareness about children like him? How will it help their lives?"], src: '18쪽 Discussion 4~6', nt: '토론 ②', n: ['<del>children like ward</del> → children like him', '«accept» — 한국 사회가 다문화 친구를 받아들이는 방법으로 넓혀 이야기'] },
      { t: 'read', k: 'fix', small: 'Activity Time', title: 'The new girl 🎒', img: G('new-girl'), paras: ['A new girl from another country joins your class. She seems nice, but she is very shy. Some students make fun of her **accent**.', 'Later, you hear the class **bullies** talking about playing a **practical joke** on her. You know she will be very embarrassed.', '💬 What do you do?'], gloss: [['accent', '말투'], ['practical joke', '짓궂은 장난']], src: '19쪽 Activity Time', nt: '상황 ① 전학생', n: ['<del>Accent 강세</del> → 말투 · <del>Bullies 괴롭힘</del> → 괴롭히는 아이들 · <del>Practical 실용적인</del> → 짓궂은 장난', '«I would …» 로 답하게 — 하인스 워드의 학교생활과 이어서'] },
      { t: 'read', k: 'fix', small: 'Activity Time', title: 'The worn-out shirt 👕', img: G('worn-shirt'), paras: ['You are in the park with your family. You are wearing a **worn-out** old shirt that your older brother or sister **handed down** to you.', 'You play with some kids and have fun. But after a while, you hear them whispering about how badly you are dressed.', '💬 What do you do?'], gloss: [['worn-out', '낡아 해진'], ['hand down', '물려주다']], src: '20쪽 Activity Time', nt: '상황 ② 낡은 옷', n: ['<del>older sibling</del> → older brother or sister(쉬운 말)', '정답 없음 — «Would you say something? Would you leave?»'] },
      { t: 'story', k: 'fix', img: G('dye-hair'), title: 'Yoona and Jay: Pink hair!', lines: [['Yoona', 'Look! Mina dyed her hair pink. So unique!'], ['Jay', 'Cool! Do you want pink hair?'], ['Yoona', 'Yes! But my parents said no.'], ['Mango', '**Convince** them with a good **argument**! 🥭']], src: '21쪽 Activity Time (dye your hair)', nt: '이어지는 이야기 ②', n: ['원본 상황 ③(친구가 염색 → 나도 하고 싶지만 부모님 반대)을 Yoona 의 이야기로', '<del>Argument 논의</del> → (설득하는) 주장 · Convince 설득하다'] },
      { t: 'yourturn', k: 'fix', title: 'Convince your parents!', img: '18171', lines: ['I want to dye my hair because ___.', 'It would make me feel ___.', 'I promise I will ___.'], chips: ['unique', 'confident', 'keep my grades up'], src: '21쪽 Activity Time', nt: '내 말로 — 설득하기', n: ['강사가 «부모님» 역을 맡아 «No!» 로 버티고 학생은 이유 세 개로 설득', '<del>dying your hair</del> → dyeing(철자) — 마지막 질문은 원본 그대로'] },
      { t: 'song', k: 'fix', title: 'Everyone Is Different 🎵', img: '12079', lines: ['Tall or short, curly or straight,', "Every person's different — and that's great!", 'Shy or sociable, quiet or loud,', 'Being different makes me proud!'], src: '23쪽 (song)', nt: '마치는 챈트', n: CHANT('Everyone Is Different', 'curly → blond, quiet → humble') },
      ...close(G2, { img: G('cover-grapes'), q: 'Why is this family eating grapes at midnight?', ko: '왜 한밤중에 포도를 먹을까요? 다음 시간 — Holidays!' }),
    ] },
  // ───────────────────────── 007 Holidays
  { code: '007', tab: '명절 풍습', unit: U3, title: 'Holidays', orig: 23,
    intro: '우리 명절과 세계의 새해·크리스마스 풍습(스페인 포도 12알 · 그리스 양파 · 필리핀 별 등 · 노르웨이 빗자루)을 말하고, 파티 준비를 이야기합니다. 읽기: 크리스마스는 너무 상업적이 됐을까? 이야기: Yoona 와 Jay 가 크리스마스 파티를 열어요.',
    fixed: ['<del>stroke 때리기</del> → (시계가) 땡 치는 소리 · <del>represent 대표</del> → 나타내다 · <del>host 주인</del> → (파티를) 열다 · <del>competitions 경쟁</del> → 대회 · <del>centuries 수세기</del> → 수백 년', "<del>New Year's Even</del> → New Year's Eve · 괄호·쉼표 띄어쓰기(«lantern)has», «Christmas .»)", '13쪽 머리글이 «BAD HABITS», 19쪽 머리글이 «Unit 1» → Holidays', '<del>Did you ever host a party?</del> → Have you ever hosted a party?', '<del>the most famous Christian tradition</del> → Christmas tradition · <del>tuined</del> → ruined', '<del>December 25\'*</del> 등 서수 표기 깨짐 → December 25th', '노래 «Jingle Bells» 가사 → 새 챈트'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-grapes'), q: 'What holiday traditions does your family have?', story: 'At midnight, the clock strikes twelve — and everyone stuffs grapes into their mouths! Why?', nt: '표지 + Big Question', n: ['볼 가득 포도를 문 가족 — 지난 시간 예고의 답을 먼저 짐작하게', '끝날 때 우리 집 명절 풍습을 영어로 소개하는 것이 목표'] },
      ...open(G3, 'Lesson Goals (Traditions · Customs)'),
      { t: 'discuss', k: 'keep', title: 'Warm up', img: '15269', qs: ['What holidays do you celebrate with your family?', 'Are holidays fun? Why?'], chips: ['We celebrate …', 'On Chuseok, we …'], src: '4쪽 Warm up', nt: '생각 말하기', n: ['사진: 추석 송편 빚는 가족 — «What are they doing? What holiday is it?»'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Holiday words 🔒', cols: 4, words: [['celebrate', '축하하다·(명절을) 지내다', '12837'], ['tradition', '전통', '12526'], ['custom', '풍습', '12377'], ['symbol', '상징', '15603'], ['lantern', '등, 초롱', '18054'], ['host', '(파티를) 열다', '12216'], ['preparations', '준비', '16826'], ['competition', '대회', '19033']], src: '5쪽 Vocabulary', nt: '낱말 — 뜻 가리기', n: ['<del>host 주인</del> → (파티를) 열다 · <del>competitions 경쟁</del> → 대회', 'customary·stroke·represent·rebirth·tapping·iconic·communities·centuries 는 읽기 글 아래 뜻풀이로'] },
      { t: 'vocab', k: 'keep', title: 'Holiday words', cols: 4, words: [['celebrate', '축하하다·(명절을) 지내다', '12837'], ['tradition', '전통', '12526'], ['custom', '풍습', '12377'], ['symbol', '상징', '15603'], ['lantern', '등, 초롱', '18054'], ['host', '(파티를) 열다', '12216'], ['preparations', '준비', '16826'], ['competition', '대회', '19033']], nt: '뜻 공개', n: ['symbol: 평화의 상징 비둘기 — «What is a symbol of Korea?»'] },
      { t: 'discuss', k: 'keep', title: 'Starter questions', img: '18053', qs: ['On what holidays does your school close? Why does everyone in your country think those are important days?', 'Which holiday is your favorite? Why?', "Are there any holidays you don't like or don't care about?"], src: '6쪽 Starter Questions', nt: '시작 토론', n: DISC },
      { t: 'read', k: 'fix', small: 'Traditions and Customs · New Year', title: 'Spain 🇪🇸', img: '18883', paras: ["It is **customary** to eat 12 grapes, one at each **stroke** of the clock at midnight on New Year's Eve.", 'Each grape **represents** good luck for one month of the coming year.', '💭 What do you think about this?'], gloss: [['customary', '늘 하는(관습적인)'], ['stroke', '(시계가) 땡 치는 소리']], src: '7쪽', nt: '풍습 ① 스페인', n: ['<del>stroke 때리기</del> → 치는 소리 · <del>represent 대표</del> → 나타내다', '시계 종소리에 맞춰 강사가 «Bong!» — 학생이 손가락으로 포도 먹는 흉내 12번'] },
      { t: 'read', k: 'fix', small: 'Traditions and Customs · New Year', title: 'Greece 🇬🇷', img: G('greece-onion'), paras: ["In Greece, an onion is traditionally hung on the front door on New Year's Eve. It is a **symbol** of **rebirth** in the new year.", "On New Year's Day, parents wake their children by **tapping** them on the head with the onion!", '💭 What do you think about this?'], gloss: [['rebirth', '새로 태어남'], ['tap', '톡톡 두드리다']], src: '8쪽', nt: '풍습 ② 그리스', n: ["<del>New Year's Even</del> → New Year's Eve", '웃음 포인트 — «Would you like to wake up like this?»'] },
      { t: 'read', k: 'fix', small: 'Traditions and Customs · Christmas', title: 'The Philippines 🇵🇭', img: G('parol'), paras: ['The **parol**, a star-shaped **lantern**, has become an **iconic** symbol of the Filipino Christmas.', 'Many **communities**, such as villages, schools, and groups, hold **competitions** to see who can make the best parol.', '💭 What do you think about this?'], gloss: [['iconic', '대표적인'], ['community', '마을·모임']], src: '9쪽', nt: '풍습 ③ 필리핀', n: ['<del>lantern)has</del> → lantern, has · <del>Christmas .</del> 띄어쓰기', '필리핀 선생님이면 «Did you make a parol?» 를 선생님께 물어보게'] },
      { t: 'read', k: 'fix', small: 'Traditions and Customs · Christmas', title: 'Norway 🇳🇴', img: G('norway-broom'), paras: ['**Centuries** ago, people believed that witches and **evil spirits** came out on Christmas Eve looking for brooms to ride.', "Today, many people still hide their brooms so they won't be stolen! 💭 What do you think?"], gloss: [['century', '백 년'], ['evil spirit', '나쁜 귀신']], src: '10쪽', nt: '풍습 ④ 노르웨이', n: ['원본 첫 문장 «It\'s a tradition that…» 은 무엇의 전통인지 앞말이 없어 «This tradition» 으로', '<del>to stop them from being stolen</del> → so they won\'t be stolen(쉬운 말)'] },
      { t: 'match', k: 'new', title: 'Which country?', left: ['16134', '16875', '13088', '15267'], right: ['Norway', 'Spain', 'the Philippines', 'Greece'], nt: '짝 맞추기', n: ['정답: 1-B(포도) · 2-D(양파) · 3-C(등) · 4-A(빗자루)', '맞힌 뒤 «In Spain, people …» 로 한 문장'] },
      { t: 'ox', k: 'new', img: '14580', s: 'In Norway, people put their brooms outside on Christmas Eve.', nt: '⭕❌', n: ['정답 ❌ → «No! They hide their brooms in the safest place.»'] },
      { t: 'guess', k: 'new', img: G('guess-seollal'), open: [4], q: 'What holiday is it? What custom is it?', chips: ['Are they wearing hanbok?', 'Is it Chuseok?', 'It is Seollal! They are doing sebae.'], nt: 'Guess who 타일', n: ['정답: 설날 세배 — 할머니·할아버지께 절하고 세뱃돈 봉투를 받는 장면', '타일을 열 때마다 Yes/No 질문 한 개 → 다음 쪽 «우리나라 명절 풍습» 토론으로 이어집니다'] },
      { t: 'discuss', k: 'fix', title: 'Traditions and customs', img: '18360', qs: ['What traditions and customs does your country have on holidays?', 'Which Korean holiday custom would surprise foreigners? Why?'], chips: ['On Seollal, we …', 'It would surprise them because …'], src: '11쪽 Traditions and Customs', nt: '우리 풍습 소개', n: ['원본 질문 + 두 번째는 방금 배운 «세계 풍습» 을 거꾸로 — 외국 친구에게 우리 풍습 소개하기'] },
      { t: 'discuss', k: 'fix', small: 'Keyword: Preparations', title: 'Getting ready for a party 🎈', img: '15323', qs: ['How do you prepare for a party?', 'Have you ever hosted a party at home? What was it like?', 'How do people send invitations?'], src: '12쪽 Preparations', nt: '파티 준비 토론', n: ['<del>Did you ever host a party</del> → Have you ever hosted a party', '원본 머리글 «BAD HABITS» → Holidays'] },
      { t: 'story', k: 'new', img: '12216', title: "Yoona and Jay: Let's host a party!", lines: [['Jay', "Yoona, let's host a Christmas party!"], ['Yoona', 'Great idea! What preparations do we need?'], ['Jay', 'We need decorations, snacks, and invitations.'], ['Yoona', "I'll send the invitations by text message."], ['Mango', "And I'll bring twelve grapes — for good luck! 🍇"]], nt: '이어지는 이야기 ③', n: ['preparations · host · invitations 를 한 장면에', 'Mango 의 포도 — 스페인 풍습을 기억하는지 확인'] },
      { t: 'read', k: 'fix', small: 'Story Time', title: 'The Christmas holiday 🎄', img: '17188', paras: ['Christmas is an important Christian holiday. It is celebrated around the world every December 25th. **Originally**, it was a holy day that celebrated the birth of Jesus Christ.', 'Many people go to church on Christmas Eve or Christmas Day. Most people also visit relatives, cook a special dinner, and **exchange** gifts.'], gloss: [['originally', '원래'], ['exchange', '주고받다']], src: '14쪽 The Christmas Holiday Tradition', nt: '읽기 ① 크리스마스', n: ["<del>December 25'*·24%·25\"</del> 깨진 서수 → 25th", '<del>luxurious</del> → special(쉬운 말) · «Both days are public holidays» 는 강사가 말로'] },
      { t: 'read', k: 'fix', small: 'Story Time: Has Christmas become too commercial?', title: 'Presents, presents! 🎁', img: '12506', paras: ['Gift-giving is now the most famous Christmas tradition. Families spend lots of money on presents, and December is the busiest month for stores and shopping websites.', "Factories around the world work overtime in the fall, **producing** Christmas cards and **decorations**. Many of them are in China, which isn't even a Christian country."], gloss: [['produce', '생산하다'], ['decoration', '장식품']], src: '15쪽', nt: '읽기 ② 선물', n: ['<del>the most famous Christian tradition</del> → Christmas tradition', '«Who is happy about this? Who is upset?» 로 다음 쪽 예고'] },
      { t: 'read', k: 'fix', small: 'Story Time: Has Christmas become too commercial?', title: 'Ads everywhere 📺', img: '13092', paras: ['Another feature of Christmas is **seemingly** endless advertising. Months before the holiday, store windows are filled with Santa Clauses and decorations.', 'TV and radio ads remind **consumers** to buy presents. This is good news for businesses. Still, many people say the focus on **profit** has **ruined** the holiday.'], gloss: [['seemingly', '겉보기에'], ['consumer', '소비자']], src: '15쪽', nt: '읽기 ③ 광고', n: ['<del>tuined</del> → ruined', 'profit·ruined 가 이 글의 결론 — «Do you agree?»'] },
      { t: 'discuss', k: 'keep', title: 'Discussion ①', img: '16837', qs: ['What does Christmas represent? What does it mean to you?', 'How do most Christians celebrate Christmas?', 'According to the article, how has Christmas become commercialized?'], src: '16쪽 Discussion 1~3', nt: '토론 ①', n: DISC },
      { t: 'discuss', k: 'keep', title: 'Discussion ②', img: '16904', qs: ['Do you agree that Christmas is too commercial? Why or why not?', 'Do you think any Korean holidays are also becoming commercialized? Why or why not?'], chips: ['I agree because …', 'On Chuseok, people buy …'], src: '16쪽 Discussion 4·5', nt: '토론 ②', n: DISC },
      { t: 'memory', k: 'fix', title: 'Look and talk 📸', items: ['15254', G('noise-horns'), '13092', '12994'], q: 'What holiday is it? What custom is it? Is it too commercial?', a: 'I think it is ___.', src: '17~20쪽 Activity Time (Caroling · Making noise · Christmas discounts · Giving gifts)', nt: '사진 보고 말하기', n: ['원본 네 쪽(같은 질문 4개 반복) → 한 쪽 사진 네 장. 강사가 번호를 부르면 학생이 네 질문에 차례로 답', '원본 «70% OFF» 광고 그림(글자) → 쇼핑몰 사진'] },
      { t: 'song', k: 'fix', title: 'Holiday Chant ❄️', img: '15736', lines: ['Grapes at midnight, twelve bells ring,', 'Onions knocking — what a thing!', 'Stars that glow and brooms that hide —', 'Holidays bring joy worldwide!'], src: '22쪽 Jingle Bells', nt: '마치는 챈트', n: CHANT('Jingle Bells', 'grapes → stars, ring → sing') },
      ...close(G3, { img: G('cover-stress'), q: 'Why is she so stressed?', ko: '이 친구는 왜 이렇게 스트레스를 받았을까요? 다음 시간 — Stress!' }),
    ] },
  // ───────────────────────── 010 Stress
  { code: '010', tab: '스트레스', unit: U4, title: 'Stress', orig: 29,
    intro: '스트레스를 주는 상황(만원 지하철·궂은 날씨·많은 일·시험·교통 체증·괴롭힘)과 푸는 방법(심호흡·대화·목표·음악·스트레스 볼·명상)을 말하고, should/shouldn\'t 로 조언합니다. 읽기: «7-Eleven» 이라 불린 CEO 카를로스 곤. 이야기: 시험 셋을 앞둔 Jay.',
    fixed: ['<del>stressed 스트레스</del> → 스트레스를 받은 · <del>circumstances 상황</del> → 여건 · <del>crowded 가득 차서</del> → 붐비는 · <del>squeeze 압착</del> → 꽉 쥐다', '<del>assigns 할당하다</del> → (숙제를) 내주다 · <del>fairly 공정하게</del> → 꽤 · <del>demanding 요구하는</del> → 힘이 많이 드는 · <del>Profitable 이익의</del> → 이익을 내는', '<del>he files at least 200,000 kilometers</del> → flew · <del>billlon</del> → billion', "<del>How do you think this person handle stress?</del> → How do you think he handled stress?", '<del>there is a heavy traffic</del> → there is heavy traffic', '<del>cope up with stress</del> → cope with stress', '«두 회사가 합병(merged)» → 제휴(사실 고침 — 사람이 정할 것 2번)'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-stress'), q: 'What do you do when you are stressed?', story: 'Three tests, two projects, and one very messy desk… AAAH!', nt: '표지 + Big Question', n: ['원본 «책 더미 속 머리가 치솟은 학생» 장면을 더 신나게 — 지난 시간 예고 사진 그대로', '끝날 때 «When I am stressed, I …» 로 답하는 것이 목표'] },
      ...open(G4, 'Lesson Goals (Wh- Questions · Yes/No Questions · Should)'),
      { t: 'discuss', k: 'keep', title: 'Warm up', img: '16866', qs: ['When do you feel stressed?', 'What do you do when you are stressed?'], chips: ['I feel stressed when …', 'I usually …'], src: '4쪽 Warm up', nt: '생각 말하기', n: ['두 질문에 짧게 — 과 끝에서 같은 질문에 더 길게 답하는지 비교'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Stress words 🔒', cols: 4, words: [['stressed', '스트레스를 받은', '13306'], ['crowded', '붐비는', '16818'], ['heavy workload', '많은 일(업무량)', '15738'], ['traffic jam', '교통 체증', '16708'], ['bullying', '괴롭힘', G('bullying')], ['cope', '대처하다·이겨 내다', '21148'], ['strategy', '방법·전략', '14026']], src: '5쪽 Vocabulary', nt: '낱말 — 뜻 가리기', n: ['<del>stressed 스트레스</del> → 스트레스를 받은 · <del>crowded 가득 차서</del> → 붐비는', 'situation·circumstances 는 다음 읽기에서, assign·fairly 는 활동 상황에서'] },
      { t: 'vocab', k: 'keep', title: 'Stress words', cols: 4, words: [['stressed', '스트레스를 받은', '13306'], ['crowded', '붐비는', '16818'], ['heavy workload', '많은 일(업무량)', '15738'], ['traffic jam', '교통 체증', '16708'], ['bullying', '괴롭힘', G('bullying')], ['cope', '대처하다·이겨 내다', '21148'], ['strategy', '방법·전략', '14026']], nt: '뜻 공개', n: ['cope: 바람개비로 천천히 숨 쉬는 법을 배우는 아이들 — «How are they coping?»'] },
      { t: 'read', k: 'keep', small: 'Keywords', title: 'Situations and circumstances', img: '17192', paras: ['Each day, every person finds themselves in many different **situations**. Situations are caused by **circumstances**.', "Some of these we can control, while others we can't."], gloss: [['situation', '상황'], ['circumstances', '여건·사정']], src: '6쪽 Situations and circumstances', nt: '읽기 — 상황과 여건', n: ['<del>circumstances 상황</del> → 여건 — situation 과 같은 뜻으로 적혀 있어 차이가 사라졌던 곳', '«Can you control a traffic jam?» 로 다음 표 예고'] },
      { t: 'table', k: 'fix', small: 'Think about it!', title: 'Can you control it? 🤔', head: ['Circumstance', 'Can I control it?', 'What can I do?'], rows: [['bad weather', 'Yes / No', '___'], ['heavy workloads', 'Yes / No', '___'], ['a traffic jam', 'Yes / No', '___'], ['bullying', 'Yes / No', '___']], src: '7~12쪽 Keywords (Think about it!)', nt: '표로 생각하기', n: ['원본 6쪽이 같은 세 질문을 사진마다 반복 → 한 표로 모아 줄마다 답하기', '괴롭힘 줄은 «Tell a teacher or a parent.» 를 꼭 짚습니다', 'a crowded subway·preparing for tests 는 다음 기억 게임 사진으로 이어서 묻습니다'] },
      { t: 'memory', k: 'new', title: 'Stressful situations', items: ['16818', '16596', '15738', '17259', '13349', G('bullying')], q: 'Look for 10 seconds! Which situations did you see?', a: 'I saw ___ and ___.', nt: '기억 게임', n: ['10초 보여 주고 가리기 → 본 상황마다 «Can you control it?» 한 번 더'] },
      { t: 'ox', k: 'new', img: G('rain'), s: 'We can control the weather.', nt: '⭕❌', n: ["정답 ❌ → «No, we can't. But we can bring an umbrella!» — 못 바꾸는 여건과 바꿀 수 있는 행동 가르기"] },
      { t: 'discuss', k: 'keep', title: 'What can you do?', img: '16545', qs: ['Imagine you are in one of these situations. What can you do to make the situation better?', 'Which situation is the most stressful for you? Why?'], src: '7~12쪽 Think about it! 3번', nt: '해결 방법 토론', n: ['원본 3번 질문 + 두 번째는 «가장 스트레스 받는 상황» 으로 넓힘'] },
      { t: 'read', k: 'keep', small: 'Keyword', title: 'Cope 💆', img: '18414', paras: ['Many people have different ways of **coping** with stress.', 'How do you cope with it? Do you have a special **strategy**?'], src: '13쪽 Keyword Cope', nt: '읽기 — 푸는 방법', n: ['원본 문장 그대로 — 학생 답을 듣고 다음 쪽 낱말로'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Ways to cope 🔒', cols: 3, words: [['take a deep breath', '숨을 깊게 들이쉬다', '12774'], ['talk to your family and friends', '가족·친구와 이야기하다', '16862'], ['set goals', '목표를 세우다', '15815'], ['listen to music', '음악을 듣다', '15661'], ['squeeze a stress ball', '스트레스 볼을 꽉 쥐다', G('stress-ball')], ['meditate', '명상하다', '16702']], src: '14~20쪽 Keywords', nt: '낱말 — 푸는 방법 가리기', n: ['<del>squeeze 압착</del> → 꽉 쥐다 · <del>set goals 목표 설정</del> → 목표를 세우다(동사로)', '원본 한 쪽에 하나씩 7쪽 → 가림·공개 두 쪽'] },
      { t: 'vocab', k: 'keep', title: 'Ways to cope', cols: 3, words: [['take a deep breath', '숨을 깊게 들이쉬다', '12774'], ['talk to your family and friends', '가족·친구와 이야기하다', '16862'], ['set goals', '목표를 세우다', '15815'], ['listen to music', '음악을 듣다', '15661'], ['squeeze a stress ball', '스트레스 볼을 꽉 쥐다', G('stress-ball')], ['meditate', '명상하다', '16702']], nt: '뜻 공개', n: ['강사가 동작을 하면 학생이 영어로 — 몸으로 기억(TPR)'] },
      { t: 'discuss', k: 'fix', title: 'Think about it!', img: '18675', qs: ['How do these activities help to relieve stress?', 'Do you do any of these to cope with stress? Which one works best for you?'], chips: ['It helps because …', 'I usually …'], src: '14~20쪽 Think about it!', nt: '푸는 방법 토론', n: ['원본 «Look at the objects and activities above» → 사진이 앞 쪽에 있어 «these activities» 로', '두 번째 질문에 «Which one works best?» 를 더했습니다'] },
      { t: 'guess', k: 'new', img: G('guess-cope'), open: [4], q: 'How is he coping with stress?', chips: ['Is he at work?', 'Is he meditating?', 'He is doing yoga at work!'], nt: 'Guess who 타일', n: ['정답: 사무실 한가운데서 요가 나무 자세 — 웃음 포인트', '타일마다 Yes/No 질문 한 개'] },
      { t: 'table', k: 'fix', small: 'Story words', title: 'Before we read 📖', head: ['word', '뜻', 'word', '뜻'], rows: [['CEO', '최고 경영자', 'profitable', '이익을 내는'], ['electric car', '전기차', 'expand', '넓히다(키우다)'], ['debt', '빚', 'demanding', '힘이 많이 드는']], src: '21쪽 Story Time words', nt: '읽기 낱말', n: ['<del>Profitable 이익의</del> → 이익을 내는 · <del>Demanding 요구하는</del> → 힘이 많이 드는'] },
      { t: 'read', k: 'fix', small: 'Story Time: The "7-Eleven" CEO', title: 'Carlos Ghosn ①', img: '15096', paras: ['Running a car company is hard. CEOs have to make millions of good cars that people like to drive.', 'Carlos Ghosn was born in Brazil and grew up in France. He became the **CEO** of Nissan in Japan in 2001 and of Renault in France in 2005.'], src: '22쪽', nt: '읽기 ① 두 회사의 CEO', n: ['원본 현재형(«is actually the CEO») → 과거형', '<del>after the two companies merged</del> → 1999년 제휴(joined together) — 사람이 정할 것 2번'] },
      { t: 'read', k: 'fix', small: 'Story Time: The "7-Eleven" CEO', title: 'Carlos Ghosn ②', img: G('car-factory'), paras: ["In 2001, Nissan was in trouble. The company was over $20 billion in **debt**, and its cars weren't selling well.", 'Mr. Ghosn changed a lot of things, and after only three years, Nissan was **profitable** again. He worked to **expand** the company around the world and to develop new electric cars.'], src: '23쪽', nt: '읽기 ② 회사를 살리다', n: ['<del>billlon</del> → billion · <del>its cars weren\'t selling well,</del> 쉼표 → 마침표', '«How did he save Nissan?» 로 확인'] },
      { t: 'read', k: 'fix', small: 'Story Time: The "7-Eleven" CEO', title: 'Carlos Ghosn ③', img: '12769', paras: ['His job was very **demanding**. He spent so many hours at work that people in Japan called him "7-Eleven" — he was always working.', 'His companies had offices and factories around the world, so he flew at least 200,000 kilometers every year. He also speaks at least four languages: French, Portuguese, English, and Japanese.'], src: '23쪽', nt: '읽기 ③ 늘 일하는 사람', n: ['<del>he files at least 200,000 kilometers</del> → flew', '«7-Eleven» = 아침 7시부터 밤 11시까지 — 편의점 이름에서 온 별명을 강사가 설명'] },
      { t: 'discuss', k: 'fix', title: 'Discussion', img: '14829', qs: ["How was Mr. Ghosn's job difficult?", 'Very busy people can have problems at home. What problems could stress cause in a family?', 'How do you think he handled stress? Use your imagination!'], src: '24쪽 Discussion', nt: '토론', n: ['<del>How do you think this person handle stress?</del> → he handled stress', ...DISC] },
      { t: 'rule', k: 'new', title: "should or shouldn't?", left: { h: 'should 👍 a good idea', ex: ['You **should** start the project early.', 'You **should** ask your boss for more time.'] }, right: { h: "shouldn't 👎 a bad idea", ex: ["You **shouldn't** wait until the last minute.", "You **shouldn't** drive too fast in traffic."] }, q: 'Look at the word after should. Is it "start" or "starts"?', src: '4쪽 Lesson Goals (Should)', nt: '규칙 찾기 — should', n: ['원본 목표의 «Should» 를 다음 활동 전에 — should 뒤에는 늘 동사원형', '예문은 다음 세 상황에서 그대로 쓸 수 있게 골랐습니다'] },
      { t: 'read', k: 'fix', small: 'Activity Time', title: 'Situation 1: A big project 🔬', img: '18628', paras: ['Your teacher **assigns** a difficult science project. It is due in three weeks.', "You are **fairly** interested in the topic, but you don't know very much about it. You don't want to do the whole project at the last minute.", "💬 What should you do? What shouldn't you do?"], gloss: [['assign', '(숙제를) 내주다'], ['fairly', '꽤']], src: '25쪽 Activity Time', nt: '상황 ① 과학 과제', n: ['<del>assigns 할당하다</del> → 내주다 · <del>fairly 공정하게</del> → 꽤', '«You should … / You shouldn\'t …» 두 문장씩'] },
      { t: 'read', k: 'fix', small: 'Activity Time', title: 'Situations 2 & 3 💼', img: '21045', paras: ['2. Your boss asked you to finish all your projects this week, but you need more time.', '3. You are late for a meeting, and unfortunately there is heavy traffic.', "💬 What should you do? What shouldn't you do?"], src: '26·27쪽 Activity Time', nt: '상황 ②③ 일·교통 체증', n: ['<del>there is a heavy traffic</del> → there is heavy traffic', '두 상황을 한 쪽에 — 학생이 번호를 골라 답합니다'] },
      { t: 'story', k: 'new', img: G('jay-exam'), title: 'Yoona and Jay: Three tests!', lines: [['Jay', "I have three tests tomorrow. I'm so stressed!"], ['Yoona', 'Take a deep breath, Jay. You should make a study plan.'], ['Jay', 'Good idea. What else should I do?'], ['Yoona', "You shouldn't play games until 2 a.m.! 😉"], ['Mango', 'Here, squeeze my stress ball! 🥭']], nt: '이어지는 이야기 ④', n: ['001 의 «새벽 2시 게임 습관» 이 다시 등장 — 나쁜 습관이 스트레스로 이어짐', 'should / shouldn\'t 를 이야기 속에서 한 번 더'] },
      { t: 'yourturn', k: 'new', title: 'My stress plan', img: '15815', lines: ['I feel stressed when ___.', 'When I am stressed, I ___.', 'A stressed friend should ___.', "He or she shouldn't ___."], chips: ['listen to music', 'set goals', 'stay up late'], nt: '내 말로', n: ['표지 질문(«What do you do when you are stressed?») 에 이제 네 문장으로 답합니다'] },
      ...close(G4, { img: G('cover-review'), q: 'Can you remember all four topics?', ko: '나쁜 습관 · 다름 · 명절 · 스트레스 — 다음 시간은 BTS 32 Review!' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: RV, title: 'BTS 32 Review', orig: 18,
    intro: '네 과 복습 — 나쁜 습관 → 서로 다름 → 명절 → 스트레스. 원본처럼 과마다 «낱말을 문장으로 말하기» 를 하되, 낱말은 가려 떠올리고 문장 틀을 주었습니다. 마지막에 Yoona 와 Jay 이야기가 마무리됩니다.',
    fixed: ['원본 복습 14쪽이 모두 «USE THE WORD/PHRASE IN A SENTENCE» 한 가지 → 과마다 «가림 낱말 → 내 문장» 두 쪽 + 게임', '원본 «HSE THE WORD» 제목 글자 깨짐(OCR 아님, 그림 글자) 확인 — 새 교재는 글자로', '«cope up with» 같은 틀린 표현 대신 문장 틀 제공', '원본 복습에 명절 쪽이 한 쪽뿐 → 풍습 낱말을 더해 균형'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-review'), q: 'Which topic was the most interesting for you?', story: "Bad habits, being different, holidays, and stress — let's look back at BTS 32!", nt: '표지 + Big Question', n: ['네 과 중 가장 재밌던 주제를 이유와 함께 — 복습의 방향을 학생이 정합니다'] },
      ...open(GR, 'Review Goals'),
      { t: 'vocab', k: 'fix', small: 'Stage 1', hide: true, title: 'Bad habits 🔒', cols: 4, words: [['stress eating', '스트레스성 폭식', G('stress-eating')], ['gambling addiction', '도박 중독', G('gambling')], ['nail biting', '손톱 물어뜯기', '17262'], ['smoking', '흡연', '19342'], ['excessive drinking', '지나친 음주', G('drinking')], ['being late', '지각하기', '16234'], ['excessive use of gadgets', '전자기기를 너무 많이 쓰기', '17258'], ['addiction', '중독', '14642']], src: '3~6쪽 Bad Habits', nt: '1단계 낱말', n: ['원본 복습 사진(술자리·담배 연기) 대신 001 과 겹치지 않는 사진 위주'] },
      { t: 'yourturn', k: 'fix', small: 'Stage 1', title: 'Use it in a sentence!', img: '18716', lines: ['___ is a bad habit because ___.', '___ is milder than ___.', 'If my friend stopped ___, he or she would ___.'], chips: ['nail biting', 'being late', 'feel healthier'], src: '3~6쪽 USE THE WORD/PHRASE IN A SENTENCE', nt: '1단계 문장 말하기', n: ['001 의 세 가지 틀(이유 · 비교 · 공손한 조언)로 낱말을 문장에 넣기'] },
      { t: 'vocab', k: 'fix', small: 'Stage 2', hide: true, title: 'Being different 🔒', cols: 3, words: [['build', '체격', '15571'], ['height', '키', '12821'], ['complexion', '피부(색)', '15417'], ['hair', '머리카락', '15315'], ['positive traits', '좋은 성격', '16469'], ['negative traits', '나쁜 성격', '14849']], src: '7~9쪽 Being Different', nt: '2단계 낱말', n: ['height: 키가 다른 건물들 — 사람 대신 건물로 웃으며', 'negative traits: 골목에서 소리치는 이웃(quarrelsome)'] },
      { t: 'yourturn', k: 'fix', small: 'Stage 2', title: 'Use it in a sentence!', img: '19120', lines: ['I have ___ hair and I am ___.', 'One of my positive traits is ___.'], chips: ['curly', 'tall', 'persistent'], src: '7~9쪽 USE THE WORD/PHRASE IN A SENTENCE', nt: '2단계 문장 말하기', n: ['is / has 규칙을 다시 — «I have curly hair. I am tall.»', '나쁜 성격은 «고치고 싶은 것 하나» 로만'] },
      { t: 'vocab', k: 'fix', small: 'Stage 3', hide: true, title: 'Holidays 🔒', cols: 3, words: [['tradition', '전통', '12391'], ['preparation', '준비', '15323'], ['custom', '풍습', '19061'], ['celebrate', '축하하다·(명절을) 지내다', '16904'], ['lantern', '등, 초롱', '12963'], ['symbol', '상징', G('greece-onion')]], src: '10쪽 Holidays', nt: '3단계 낱말', n: ['원본 복습 명절 쪽(tradition · preparation) 한 쪽뿐 → 풍습 낱말 넷을 더했습니다', 'symbol: 그리스 양파 사진 — «What is it a symbol of?»(rebirth)'] },
      { t: 'yourturn', k: 'fix', small: 'Stage 3', title: 'Use it in a sentence!', img: '18053', lines: ['My favorite holiday tradition is ___.', 'I think Christmas is / isn\'t too commercial because ___.'], chips: ['making songpyeon', 'giving presents'], src: '10쪽 USE THE WORD/PHRASE IN A SENTENCE', nt: '3단계 문장 말하기', n: ['007 의 토론 결론을 한 문장씩'] },
      { t: 'ox', k: 'new', small: 'Stage 3', img: '18883', s: 'In Greece, people eat 12 grapes at midnight.', nt: '⭕❌', n: ['정답 ❌ → «No! People in Spain eat 12 grapes. In Greece, they hang an onion on the door.»'] },
      { t: 'vocab', k: 'fix', small: 'Stage 4', hide: true, title: 'Stress 🔒', cols: 4, words: [['situation', '상황', '17368'], ['crowded subway', '붐비는 지하철', '16819'], ['bad weather', '궂은 날씨', '16545'], ['heavy workloads', '많은 일', '14930'], ['prepare for tests', '시험을 준비하다', '17259'], ['traffic jam', '교통 체증', '17270'], ['bullying', '괴롭힘', G('bullying')], ['cope', '대처하다', '12774']], src: '11~16쪽 Stress', nt: '4단계 낱말', n: ['crowded subway 는 원본 사진이 만원 전동차 — 비슷한 «꽉 찬 버스» 사진이라 강사가 «subway or bus?» 로 확인'] },
      { t: 'yourturn', k: 'fix', small: 'Stage 4', title: 'Use it in a sentence!', img: '16862', lines: ['I get stressed when ___.', 'To cope with stress, I ___.', "You should ___. You shouldn't ___."], chips: ['talk to my family and friends', 'set goals', 'listen to music', 'squeeze a stress ball'], src: '11~16쪽 USE THE WORD/PHRASE IN A SENTENCE', nt: '4단계 문장 말하기', n: ['원본 15·16쪽 푸는 방법 네 가지를 칩으로', '<del>cope up with</del> → cope with'] },
      { t: 'guess', k: 'new', img: G('cover-habits'), open: [1, 7], q: 'Stage 5 · Boss! What is his bad habit? How can you help him?', chips: ['Is it late at night?', 'Is his mom angry?', 'If you slept more, you would …'], nt: '5단계 — 보스 문제', n: ['001 표지 사진 — 타일을 열 때마다 질문 한 개, 다 열면 공손한 조언 한 문장으로 마무리'] },
      { t: 'story', k: 'new', img: '16469', title: 'Yoona and Jay: Good news!', lines: [['Jay', "Yoona, guess what? I don't play games until 2 a.m. anymore!"], ['Yoona', 'Wow! You look so much happier, Jay.'], ['Jay', 'Thanks! You helped me politely. You are so encouraging.'], ['Mango', "And I'm the most sociable mango in the world! 🥭"]], nt: '이어지는 이야기 ⑤ (마지막)', n: ['001 의 습관이 해결되며 권 전체 이야기가 끝납니다', 'encouraging · sociable(004 낱말)이 한 장면에'] },
      { t: 'ican', k: 'new', items: [['I can talk about bad habits.', 'Nail biting is milder than smoking.'], ['I can describe people and holidays.', 'She has curly hair. In Spain, people eat 12 grapes.'], ['I can talk about stress and how to cope.', 'You should take a deep breath.']], nt: 'BTS 32 전체 I can', n: ['별 1~3개 스스로 칠하기 — 별이 적은 줄이 시험 전 다시 볼 과'] },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래', n: ['<del>Goodbye,goodbye</del> → Goodbye, goodbye'] },
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 32 Unit Test', orig: 10,
    intro: '13문항 단원 시험(원본 «Answer the questions and explain»). 화상수업에서 말로 보는 시험이라 문항마다 «이유까지 두 문장 이상» 을 기준으로 했습니다.',
    fixed: ['1번 <del>Names 3 bad habits</del> → Name three bad habits', '3번 <del>Which thing do you hope that you will never do?</del> → Which bad habit do you hope you will never have?', '4~6번은 대상이 없어(«the bad habit», «their») 뜻이 모호 → «someone with a bad habit» 으로', 'General Information · Class Rules 쪽 → 시험지에서 뺐음'],
    slides: [
      { t: 'cover', k: 'new', img: '12751', q: 'Test time! You can do it! 💪', story: '13 questions · 1 point each · Answer and explain!', nt: '표지', n: ['원본 첫 쪽 «Answer the questions and explain» — 답 + 이유를 말해야 1점'] },
      { t: 'discuss', k: 'fix', img: '17262', title: 'Questions 1–3', qs: ['Name three bad habits. Why do you think people have these bad habits?', 'Do you think that some habits are always bad?', 'Which bad habit do you hope you will never have?'], src: '문항 1~3', nt: '문항 1~3 · 나쁜 습관', n: ['<del>Names 3 bad habits</del> → Name three bad habits', '3번 원본 «Which thing …» 은 무엇을 묻는지 모호 → bad habit 으로'] },
      { t: 'discuss', k: 'fix', img: '18146', title: 'Questions 4–6', qs: ['Think of someone with a bad habit. How is the bad habit harmful to him or her?', 'Why would breaking the habit make his or her life better?', 'What can he or she do to break the habit? How can you help?'], src: '문항 4~6', nt: '문항 4~6 · 습관 고치기', n: ['원본은 대상 없이 «the bad habit» — 한 사람을 떠올리게 바꿨습니다', '공손한 조언(If you …, you would …)으로 답하면 만점'] },
      { t: 'discuss', k: 'keep', img: '19020', title: 'Question 7', qs: ['What are your physical characteristics? Talk about your build, height, complexion, and hair.', 'How are they similar to your family and friends? How are they different?'], src: '문항 7', nt: '문항 7 · 겉모습', n: ['한 문항 두 부분 — 둘 다 답해야 1점', 'is / has 를 바르게 쓰는지 확인'] },
      { t: 'discuss', k: 'keep', img: '19120', title: 'Question 8', qs: ['Is your personality similar to most of your family and friends? Give examples of why it is or isn\'t.'], chips: ['My personality is similar because …', "It's different because …"], src: '문항 8', nt: '문항 8 · 성격', n: ['성격 낱말(positive / negative traits)을 두 개 이상 쓰면 만점'] },
      { t: 'discuss', k: 'keep', img: '15269', title: 'Questions 9–10', qs: ['What traditions and customs does your family practice? What are your favorites?', 'What customs from other places do you think should be included in your country?'], src: '문항 9·10', nt: '문항 9·10 · 명절', n: ['10번은 007 세계 풍습(포도·양파·별 등·빗자루) 중 하나를 골라 이유와 함께'] },
      { t: 'discuss', k: 'keep', img: '17192', title: 'Questions 11–13', qs: ['When do you feel stressed every day?', 'What do you think is the most stressful part of your life?', 'Does life have to be stressful for you to be successful? What do you think?'], src: '문항 11~13', nt: '문항 11~13 · 스트레스', n: ['13번은 010 카를로스 곤 이야기와 이어서 — 정답 없음, 이유가 있으면 1점'] },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–4', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['5–8', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['9–12', 'Great!', '거의 다 왔어요 — 하나만 더'], ['13 ⭐', 'Perfect!', 'BTS 33 으로 출발! 🎉']], src: '10쪽 Good Job', nt: '점수표', n: ['원본 «Good Job» 쪽 → 점수마다 다음에 할 일을 적은 표로'] },
      { t: 'next', k: 'new', img: G('next-games'), q: 'Do you like to play computer games? What types of games do you like?', ko: '다음 권 BTS 33 — Computer Games(컴퓨터 게임)로 시작해요!', nt: '다음 권 예고', n: ['BTS 33 001 «Computer Games» 의 첫 질문을 미리 — 001 에서 배운 «게임 중독» 과도 이어집니다', '답은 다음 권 첫 시간에 씁니다'] },
    ] },
  ],
};
