// BTS 30 새 교재 설계 데이터. k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
// 사진 번호 = photo-catalog.json · gen:bts-30-* = 새로 만들 사진(gen/req-bts-30.json)
import { open, close } from '../common.mjs';

const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3', U4 = 'Unit 4';
const G = (x) => 'gen:bts-30-' + x;

const G1 = [['I can talk about living abroad.', '해외에서 사는 것에 대해 말할 수 있어요 — I would like to live abroad because …'], ['I can ask Yes/No and Wh- questions.', 'Yes/No 질문과 Wh- 질문을 할 수 있어요 — Have you ever traveled abroad? What was it like?'], ['I can give pros and cons.', '좋은 점과 나쁜 점을 말할 수 있어요 — One advantage is … One disadvantage is …']];
const G2 = [['I can talk about my free time.', '여가 시간에 무엇을 하는지 말할 수 있어요 — In my free time, I usually …'], ['I can give a reason with so and because.', 'so·because 로 이유를 말할 수 있어요 — I\'m a social person, so I like to hang out.'], ['I can compromise with my friends.', '친구들과 서로 양보해 계획을 정할 수 있어요 — Let\'s do both!']];
const G3 = [['I can talk about my talents and skills.', '내 재능과 기술을 말할 수 있어요 — I\'m good at math. I have a talent for art.'], ['I can say what a job involves.', '어떤 직업이 무슨 일을 하는지 말할 수 있어요 — A vet takes care of sick animals.'], ['I can give my opinion and a reason.', '내 생각과 이유를 말할 수 있어요 — I don\'t agree, because …']];
const G4 = [['I can name things in space.', '우주에 있는 것들을 말할 수 있어요 — planets, stars, satellites, space probes.'], ['I can say "I would rather …"', '둘 중 하나를 골라 말할 수 있어요 — I would rather be an astronomer.'], ['I can talk about space tourism.', '우주 관광에 대한 생각을 말할 수 있어요 — I think it is a good idea because …']];

export const COURSE = {
  head: `<h1>BTS 30 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트의 BTS 30 원본 <b>137쪽</b>(6묶음: 001-003 · 004-006 · 007-009 · 010-012 · Review · Test)을 한 장씩 읽고, 제안서 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · «I can» · 다음 시간 예고)으로 다시 짰습니다. Level 8(Bubble Tea) 마지막 권 가운데 하나로, 주제는 <b>나의 세계와 미래</b> — ① 해외 생활(Yes/No · Wh- 질문) ② 여가 시간과 양보(so · because) ③ 나의 진로(재능과 기술) ④ 우주 탐사(I would rather … · 우주 관광 찬반).</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>배우는 <b>낱말·질문·문법 범위와 원본 글 9편</b>(Lyka·Mark 의 해외 생활, 운동·친구·공부·쉼 네 학생의 여가, Joe·Joo Young 의 진로, Dennis Tito 의 우주 관광)과 원본 설명글(오해, 양보, 뇌, 재능, 우주비행사·천문학자, 아폴로·허블·보이저·국제우주정거장), 역할극 세 장면, 복습 낱말 38개, 시험 20문항은 그대로입니다. 원본의 오타·문법 오류·사실 오류·틀린 뜻·아이에게 맞지 않는 사진은 고쳤습니다(과마다 목록).</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>(Yes/No·Wh- · so/because · talent/skill · would rather), <b>⭕❌</b>, <b>Guess who</b>(사진 조각 맞히기), <b>짝 맞추기·기억 게임·낱말 퍼즐·순서 맞추기</b>, 원본 글마다 <b>낱말 확인</b>, Yoona·Jay 가 이어 가는 <b>짧은 대화</b>, <b>내 말로</b>, <b>I can ✅</b>, <b>다음 시간 예고</b>를 넣었습니다. 원본 역할극(주말 계획)은 계획표를 채우며 서로 양보하는 활동으로 바꿨습니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>사진은 지금 사이트의 사진을 자리 채움으로 넣었고, 점선 상자(«새 사진 생성 중»)는 새로 만들 사진 <b>25장</b>(gen/req-bts-30.json)입니다. 원본에서 <b>아이 교재에 맞지 않는 사진</b>(Try it 의 전쟁터 폐허·무장 군인, 난민촌, 목에 링을 찬 카얀족 여성을 구경거리로 보여 주는 쪽, 술잔을 든 어른들의 파티)과 <b>상표가 크게 보이는 사진</b>(디즈니랜드 성, 넷플릭스 화면)은 모두 바꿨습니다. 원본은 거의 모든 인물 사진이 정장 차림 어른 → 또래 학생 사진으로.</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>원본의 사실 오류(010-012 Dennis Tito)</b> — ① «He returned to earth on April 28, 2001» 은 틀립니다(4월 28일에 <u>출발</u>, 5월 6일에 귀환) → «He flew into space on April 28, 2001, and came back on May 6.» ② «orbited the earth for 7 days» → 약 8일(7일 22시간)이라 «almost 8 days». ③ «Since 2001, six other wealthy space tourists …» 는 2009년까지의 이야기 → «By 2009, six more space tourists had …». ④ «In the future, private companies may send rockets full of tourists» 는 이미 현실(2021년부터 민간 회사가 관광객을 우주로 보냄) → «Today, private companies also send tourists into space.» ⑤ Apollo 제목 «(1967–1972)» 와 본문 «ran from 1961 to 1972» 가 어긋남 → 1961–1972 로 통일. 모두 승인 필요.</li>
<li><b>과학적 근거가 약한 내용(007-009)</b> — 원본 «Scientists think that left-brained people are better at logical thinking … right-brained people … more creative» 는 «좌뇌형·우뇌형 성격» 이라는 널리 퍼진 속설로, 뇌과학 연구는 이를 뒷받침하지 않습니다. 새 교재는 «Some people say …» 로 바꾸고 강사 메모에 «속설» 이라고 적었습니다. 시험 12번(«left-brained or right-brained?»)도 «more logical or more creative?» 로. 원본 문장을 살릴지.</li>
<li><b>원본 사진 교체</b> — 001-003 Try it: 시리아 전쟁터 폐허·무장 군인, 난민 캠프(«Is it in the city or the country?»), 카얀족 여성 사진(«Talk about the people») → 네팔 산골 마을·전통 축제·성 관광 사진. 디즈니랜드 성(상표) → 일반 성. 004-006: 술잔 든 어른 파티 → 공원의 또래 친구들, «NETFLIX» 화면 → 게임하는 아이. 원본 사진을 살릴지.</li>
<li><b>역할극 날짜·날씨(004-006)</b> — 원본 «Saturday, September 6, 2019»(실제는 금요일), «Saturday, January 6, 2020»(실제는 월요일), «Sunday, December 1, 2019 … hot and muggy, 29°C»(12월 한국 날씨와 안 맞음), 역할극 1 «four of your friends» 인데 5명 중 4명의 바람만 적힘, 역할극 3 «far in the future» → 날짜를 «Saturday/Sunday» 로만 두고 역할극 2 는 «a hot summer Sunday», 역할극 1 은 «three friends»(모두 4명)로 고쳤습니다. 이대로 둘지.</li>
<li><b>Review 순서·머리글</b> — 원본 Review 는 Space → Abroad → Career → (머리글이 «My Career» 로 잘못 붙은) Free time 순입니다 → 단원 순서(Abroad · Free time · Career · Space)로 바꾸고 머리글을 고쳤습니다. «volunteer» 는 단원 본문에 한 번도 안 나오는 낱말이라 복습 목록에서 뺄지 결정 필요(새 교재는 남겨 두고 뜻을 적었습니다).</li>
<li><b>틀린 뜻</b> — abroad «널리» → 해외에(서) · rigorous «엄밀한» → 격렬한·힘든 · involve «감다» → (일이) …을 포함하다 · heritage «세습 재산» → (문화) 유산 · accents «발음» → 억양·말투 · flexible 은 원본 뜻 «융통성 있는» 이 맞는데 Review 사진이 요가(몸이 유연한)라 뜻과 사진이 어긋났습니다 → 사진 교체.</li>
<li><b>원본 중복 쪽</b> — 001-003 Try it 세 장 사진 쪽(뉴질랜드 루핀 꽃밭·베트남 계단식 논·노르웨이 베르겐)이 두 번(25·26쪽) 들어 있어 하나로 줄였습니다(짝 맞추기로).</li>
<li><b>새로 만들 사진 25장</b>(힉스필드 크레딧) — 표지 4 · 이야기 인물(Lyka·Mark·Joo Young) · 오해·양보·여가 장면 · 직업(만화가·고생물학자·고고학자) · 우주(인공위성·탐사선·달 착륙·허블·보이저·우주 관광) · BTS 31 예고. Dennis Tito 쪽은 실존 인물을 닮게 만들지 않도록 로켓 발사·우주정거장 창문 장면으로만 요청했습니다.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001-003
  { code: '001-003', tab: '해외 생활', unit: U1, title: 'Living Abroad', orig: 27,
    intro: '해외에서 사는 것에 대해 Yes/No 질문과 Wh- 질문으로 묻고 답합니다. 이야기: 해외에서 살고 싶은 Lyka(한국)와 자기 나라를 더 여행하고 싶은 Mark(미국).',
    fixed: ['뜻 «abroad 널리» → 해외에(서) · «accents 발음» → 억양·말투 · «heritage 세습 재산» → (문화) 유산 · «foreign 외국» → 외국의 · «respectful 존경하는» → 예의 바른', 'Lyka: «Of course I enjoy» → Of course, I enjoy · «between cultures, It\'s hard» → between cultures. It\'s hard · «talking te them I can» → talking to them, I can', 'Mark: «diverse heritage, My country» → my country · «the northeastern U.S. There are» → the northeastern U.S., there are · «The other remarkable thing about America are» → is', 'Think about it: «"there isn\'t much diversity In Korea?"» → 따옴표 안에 물음표가 들어간 것 정리 · «Why doesn\'t Mark want,to» → want to', 'Try it: 전쟁터 폐허·난민촌·카얀족 사진 → 아이에게 맞는 사진 · 디즈니랜드 성(상표) → 일반 성 · 중복 사진 쪽 한 장 삭제'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-abroad'), q: 'Would you like to live in a foreign country?', story: 'Lyka wants to live abroad. Mark wants to stay in his own country. What about you?', nt: '표지 + Big Question', n: ['공항 창밖 비행기를 보는 아이 사진 — «Where is he going?» 로 시작', '원본 Big Question 을 그대로 표지 질문으로 — 끝에 «I would / wouldn\'t like to live abroad because ___» 로 답하는 것이 목표'] },
      ...open(G1),
      { t: 'qa', k: 'keep', img: '12740', title: 'Warm up', q: 'What is your country most famous for?', a: 'Korea is famous for ___.', chips: ['K-pop', 'kimchi', 'Hangeul', 'taekwondo'], src: 'Warm Up', nt: '몸풀기 질문', n: ['원본 질문 그대로 — 세계 국기가 꽂힌 지구본 사진으로', '두 개 이상 말하게: «Korea is famous for K-pop and kimchi.»'] },
      { t: 'vocab', k: 'fix', title: 'New words 📖', cols: 3, words: [['abroad', '해외에(서)', '12746'], ['culture', '문화', '12595'], ['beliefs', '믿음·신념', '21377'], ['values', '가치관', '21176'], ['traditions', '전통', '12526'], ['misunderstanding', '오해', '14879']], src: 'Vocabulary', nt: '낱말 6개', n: ['<del>널리</del> → 해외에(서) — 원본 뜻이 틀렸습니다(abroad = 외국에서)', '사진을 가리고 영어만 보여 준 뒤 한 장씩 공개'] },
      { t: 'discuss', k: 'keep', img: '18649', title: 'Big Question 🌏', qs: ['Would you like to live in a foreign country? Why or why not?', 'Have you ever traveled abroad? What was it like?', 'What countries do you think are interesting? Would you like to travel there in the future?'], src: 'Big Question · Questions', nt: 'Big Question', n: ['원본 두 쪽(Big Question · 질문 넷)을 한 쪽으로', '첫 문장은 Yes/No 질문, 둘째는 Wh- 질문 — 다음 쪽 규칙 찾기의 예문으로 다시 씁니다'] },
      { t: 'discuss', k: 'keep', img: '17236', title: 'Starter questions', qs: ['Why do so many university students study abroad?', 'Would you like to study abroad someday?', 'Do you think you will ever live abroad for more than one year? Why or why not?'], src: 'Starter Questions', nt: '시작 질문', n: ['외국에서 온 학생을 반기는 교실 사진 — «How does she feel?» 를 먼저'] },
      { t: 'read', k: 'keep', img: G('misunderstanding'), small: 'Keyword', title: 'Misunderstanding 🤔', paras: ['If people from different countries don\'t understand each other\'s cultures, it can cause a **misunderstanding**.', 'How might you misunderstand a foreigner?'], gloss: [['cause', '일으키다'], ['foreigner', '외국인']], src: 'Keywords: Misunderstanding', nt: '핵심어 — 오해', n: ['인사로 허리를 숙이는 아이와 하이파이브를 하려는 아이가 엇갈려 웃는 사진 — 그림만 보고 «What happened?» 부터', '예: 한국은 두 손으로 물건을 주고받지만 한 손으로 주는 나라도 많아요'] },
      { t: 'discuss', k: 'keep', img: '14879', title: 'Talk about it', qs: ['Did you ever have a cultural misunderstanding? What happened?', 'Why do you think people from different cultures misunderstand each other?'], src: 'Talk about it', nt: '이야기해 보기', n: ['경험이 없으면 «I saw …» 로 본 것·들은 것을 말해도 됩니다'] },
      { t: 'rule', k: 'new', title: 'Two kinds of questions', left: { h: 'Yes/No questions', ex: ['**Have** you ever traveled abroad?', '**Would** you like to live abroad?', '**Do** you think …?'] }, right: { h: 'Wh- questions', ex: ['**What** was it like?', '**Why** do students study abroad?', '**How** might you misunderstand a foreigner?'] }, q: 'Which questions can you answer with just "Yes" or "No"?', nt: '규칙 찾기', n: ['원본 목표 «Wh- questions · Yes/No questions» 를 학생이 스스로 찾게', '규칙: Yes/No 질문은 조동사(Have·Would·Do)로 시작 → Yes/No 로 답 · Wh- 질문은 이유·방법·내용을 말해야 합니다', '좋은 대화는 Yes/No 다음에 Wh- 를 이어 묻기: «Have you been to Japan? — Yes. — What was it like?»'] },
      { t: 'guess', k: 'new', img: '18955', open: [1, 6], q: 'Where in the world is it?', chips: ['Is it in Asia?', 'Is it hot there?', 'Is it very old?'], nt: 'Guess who — 어디일까?', n: ['정답: Egypt(이집트 피라미드)', '학생이 Yes/No 질문으로 물어야 타일을 엽니다 — 방금 찾은 규칙을 게임 안에서 계속 쓰게'] },
      { t: 'read', k: 'fix', img: G('lyka'), small: "Lyka's Story ①", title: 'I Want to Live Abroad', paras: ['I am pretty sure that I want to live abroad when I grow up. Of course, I enjoy living in my own country, South Korea. I\'m comfortable with the culture here.', 'I think most Koreans are **respectful** and **hardworking** people. My **foreign** friends all seem to like it very much. They say the people are friendly, and they really like the food.'], gloss: [['respectful', '예의 바른'], ['hardworking', '부지런한'], ['foreign', '외국의']], src: "Lyka's Story (1)", nt: 'Lyka ①', n: ['<del>Of course I enjoy</del> → Of course, I enjoy', '<del>존경하는</del> → 예의 바른(남을 존중하는) · <del>외국</del> → 외국의(형용사)'] },
      { t: 'read', k: 'keep', img: '19358', small: "Lyka's Story ②", title: 'Not Much Diversity?', paras: ['Still, one thing I heard my foreign friends say about my country is that there isn\'t much **diversity**.', 'For example, although it\'s true that people in Jeolla-do and Gangwon-do speak with different **accents** and eat **slightly** different foods, it feels like everyone in Korea is pretty similar.'], gloss: [['diversity', '다양성'], ['accents', '억양·말투'], ['slightly', '조금']], src: "Lyka's Story (1)", nt: 'Lyka ②', n: ['<del>발음</del> → 억양·말투(accent) — 사투리 이야기라 억양이 맞습니다', '«우리 동네 말투는 어때?» 로 학생 경험과 잇기'] },
      { t: 'read', k: 'fix', img: '17223', small: "Lyka's Story ③", title: 'Different Is Fascinating', paras: ['Therefore, I know that if I want to meet many different kinds of people in my life, I will have to travel abroad. I already have foreign friends, so I know that people in other countries are different.', 'Besides speaking different languages, I think it\'s **fascinating** how people are different. There are so many differences between cultures. It\'s hard to think of just one to talk about.'], src: "Lyka's Story (2)", nt: 'Lyka ③', n: ['<del>between cultures, It\'s hard</del> → between cultures. It\'s hard(쉼표로 두 문장을 이은 것 정리)'] },
      { t: 'read', k: 'fix', img: '17014', small: "Lyka's Story ④", title: 'Everyone Is Better Off', paras: ['Still, I can say that I enjoy the stories that foreigners tell me. Also, by talking to them, I can **inform** them about life in Korea and help them understand my own culture. In my opinion, this makes everyone **better off**.', 'If I travel abroad, I know I\'ll be able to see some cool **sights**, but the best part will be meeting people and hearing stories.'], gloss: [['inform', '알려 주다'], ['better off', '(전보다) 더 나은'], ['sights', '명소']], src: "Lyka's Story (2)", nt: 'Lyka ④', n: ['<del>talking te them I can</del> → talking to them, I can', 'better off = be in a better position(원본 뜻풀이) — «모두에게 좋은 일»'] },
      { t: 'fill', k: 'new', title: "Lyka's words ✏️", lines: ['Lyka thinks most Koreans are ___ and hardworking.', 'People in Gangwon-do speak with a different ___.', 'Lyka thinks cultural differences are ___.', 'Talking to foreigners makes everyone better ___.'], chips: ['respectful', 'accent', 'fascinating', 'off'], nt: '낱말 확인', n: ['원본 Lyka 낱말 쪽(Respectful … Better off)을 문장 속에서 다시 쓰게', '답: respectful · accent · fascinating · off'] },
      { t: 'read', k: 'fix', img: G('mark'), small: "Mark's Story ①", title: 'A Big, Diverse Country', paras: ['I live in the USA. Because of its **immense** size and diverse **heritage**, my country has one of the most **complex** cultural **identities** in the world. Our country has many very different places and people.', 'For example, in the northeastern U.S., there are forests and many large cities. In different areas, there are plains, tall mountains, and deserts.'], src: "Mark's Story (1)", nt: 'Mark ①', n: ['<del>diverse heritage, My country</del> → my country · <del>the northeastern U.S. There are</del> → the northeastern U.S., there are', '<del>세습 재산</del> → (문화) 유산'] },
      { t: 'read', k: 'keep', img: '17185', small: "Mark's Story ②", title: 'Snow and Palm Trees', paras: ['Northern areas get lots of snow, while in places like Florida and Southern California, it is warm all year and there are even palm trees.', 'I love traveling around the country with my family. Everywhere I go, there are new things to see.'], gloss: [['northern', '북쪽의'], ['palm tree', '야자나무']], src: "Mark's Story (1)", nt: 'Mark ②', n: ['«while» = 반면에 — 두 곳을 비교하는 말', '«Korea has … while …» 로 한국 날씨도 비교해 보기'] },
      { t: 'read', k: 'fix', img: '14591', small: "Mark's Story ③", title: 'A Nation of Immigrants', paras: ['The other **remarkable** thing about America is the many different kinds of Americans you\'ll meet. Depending on **geography**, people in different places lead all sorts of different lifestyles.', 'America is a nation of **immigrants** who came from all over the world. Different groups have different **traditions** and cultures.'], gloss: [['remarkable', '놀라운'], ['immigrants', '이민자']], src: "Mark's Story (2)", nt: 'Mark ③', n: ['<del>The other remarkable thing about America are</del> → is(주어는 thing 하나)', '<del>지리학</del> → 지리(여기서는 학문이 아니라 땅의 모양)'] },
      { t: 'read', k: 'keep', img: '21091', small: "Mark's Story ④", title: 'Happy Here for Now', paras: ['I think I could spend the rest of my life learning about American culture. That\'s why, when I travel, I want to keep going places in my own country.', 'Someday I may want to travel abroad, but for now, I\'m happy here.'], gloss: [['the rest of my life', '남은 평생'], ['for now', '지금은']], src: "Mark's Story (2)", nt: 'Mark ④', n: ['Lyka 와 반대 생각 — «Who are you more like, Lyka or Mark?» 로 넘어가기'] },
      { t: 'fill', k: 'new', title: "Mark's words ✏️", lines: ['The USA is very, very big. It has an ___ size.', 'America is a nation of ___ from all over the world.', 'People live in different ways depending on ___.'], chips: ['immense', 'immigrants', 'geography'], nt: '낱말 확인', n: ['원본 Mark 낱말 쪽(immense … traditions)을 문장 속에서 다시', '답: immense · immigrants · geography'] },
      { t: 'ox', k: 'new', img: G('mark'), s: 'Mark wants to live abroad right now.', nt: '⭕❌', n: ['정답 ❌ → «No. For now, he wants to travel in his own country.»', '틀린 문장을 고쳐 말해야 점수'] },
      { t: 'discuss', k: 'fix', title: 'Think about it! ①', qs: ['How does Lyka describe Korea? What does she like about it?', 'What does Lyka mean when she says, "There isn\'t much diversity in Korea"? Do you agree with her?', 'According to Mark, in what ways is the USA a diverse country?'], src: 'Think about it!', nt: '생각해 보기 ①', n: ['<del>"there isn\'t much diversity In Korea?"</del> → 물음표를 따옴표 밖으로, 대소문자 정리'] },
      { t: 'discuss', k: 'fix', title: 'Think about it! ②', qs: ['Why doesn\'t Mark want to travel abroad? Do you think he is making a good decision?', 'After reading these stories, do you think you want to live abroad in the future? Has your opinion changed?'], src: 'Think about it!', nt: '생각해 보기 ②', n: ['<del>want,to</del> → want to', '처음(Big Question)의 내 대답과 지금 대답을 비교'] },
      { t: 'story', k: 'new', img: '19390', title: 'Yoona and Jay', lines: [['Yoona', 'I want to live abroad someday, like Lyka.'], ['Jay', 'Really? Why?'], ['Yoona', 'I want to meet many different kinds of people.'], ['Jay', 'I think I\'m more like Mark. I want to travel around my own country first.'], ['Yoona', 'That sounds fun, too! Where would you go first?']], nt: '우리 이야기', n: ['이번 권 네 과를 Yoona·Jay 가 이어 갑니다', '역할을 바꿔 두 번 읽고, 마지막 줄을 자기 답으로 바꿔 말하기'] },
      { t: 'match', k: 'fix', title: 'Where in the world? 🗺️', left: ['15219', '14602', '15358', '17185'], right: ['Egypt', 'Indonesia', 'the USA', 'Japan'], src: 'Try it (pictures)', nt: '짝 맞추기', n: ['정답: 1-Indonesia(발리) · 2-Japan(후지산) · 3-Egypt(피라미드) · 4-the USA(캘리포니아)', '원본의 같은 사진 쪽 두 장(루핀 꽃밭·계단식 논·베르겐)이 겹쳐 하나로 줄이고 짝 맞추기로 바꿨습니다', '맞힌 뒤 «What is the geography like there?»'] },
      { t: 'qa', k: 'fix', img: '15579', title: 'Try it! ①', q: 'Is it in the city or the country? What is the geography like?', a: 'It is in the ___. There are ___.', chips: ['mountains', 'stone houses'], src: 'Try it', nt: 'Try it ① 지리', n: ['원본 사진(난민 캠프) → 네팔 산골 마을 사진 — 질문은 원본 그대로'] },
      { t: 'qa', k: 'fix', img: '17039', title: 'Try it! ②', q: 'Do you think this would be an interesting place to visit? Why or why not?', a: 'I think it would be ___ because ___.', src: 'Try it', nt: 'Try it ② 가 보고 싶은 곳', n: ['원본 디즈니랜드 성(상표) → 성 앞 관광객 사진', '원본 «Use the internet to find pictures» 는 수업 뒤 과제로 — 다음 시간 첫 질문에 씁니다'] },
      { t: 'table', k: 'fix', small: 'Activity', title: 'Living abroad: pros and cons', head: ['Advantages 👍', 'Disadvantages 👎'], rows: [['You can learn a new language.', 'You may miss your family.'], ['___', '___'], ['___', '___'], ['___', '___']], src: 'Activity (4 pros and 4 cons)', nt: '좋은 점·나쁜 점', n: ['원본: 장점 4 · 단점 4 — 첫 줄은 예시로 채워 두고 나머지 셋씩 말하게', '예: meet new people · try new food / feel lonely · a hard language'] },
      { t: 'yourturn', k: 'new', img: G('cover-abroad'), title: 'My answer', lines: ['I would / wouldn\'t like to live abroad because ___.', 'One advantage of living abroad is ___.', 'One disadvantage is ___.'], nt: '내 말로', n: ['Big Question 에 내 답으로 돌아오기 — 표지와 같은 질문'] },
      ...close(G1, { img: G('cover-freetime'), q: 'What do you do in your free time?', ko: '다음 시간 — 여가 시간! 친구마다 좋아하는 것이 다르면 어떻게 할까?' }),
    ] },
  // ───────────────────────── 004-006
  { code: '004-006', tab: '여가 시간', unit: U2, title: 'My Free Time', orig: 23,
    intro: '여가 시간에 하는 일을 so · because 로 이유와 함께 말하고, 친구마다 바라는 것이 다를 때 서로 양보(compromise)해 계획을 정합니다. 운동·친구·공부·쉼, 네 학생의 이야기.',
    fixed: ['뜻 «rigorous 엄밀한» → 격렬한·힘든 · «flexible 융통성 있는·유연성 있는» → 융통성 있는(여기서는 마음이 유연한)', '시작 질문 «Do you wish you have more free time?» → had · «Whom do you spend it with?» → Who do you spend it with?', '운동 학생 «tiding my mountain bike» → riding(OCR 확인)', '역할극 날짜·요일·날씨가 맞지 않는 것 정리(«사람이 정할 것» 참고) · 역할극 1 «four of your friends» → three friends', '어른 파티(술잔) 사진 · «NETFLIX» 화면 사진 → 또래 학생 사진'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-freetime'), q: 'What do you do in your free time?', story: 'Four students spend their free time in four very different ways. Which one are you like?', nt: '표지 + Big Question', n: ['트램펄린에서 뛰어오르는 친구들 — «Do you like this? Why?»', '끝에 «In my free time, I ___ because ___» 로 말하는 것이 목표'] },
      ...open(G2),
      { t: 'qa', k: 'keep', img: '12461', title: 'Warm up', q: 'Name 3 things you do in your free time and explain why you like them.', a: 'In my free time, I ___ because ___.', src: 'Warm Up', nt: '몸풀기 질문', n: ['<del>explain why do you like it</del> → explain why you like them(셋이니 them · 간접의문문 어순)'] },
      { t: 'vocab', k: 'fix', title: 'New words 📖', cols: 3, words: [['compromise', '(서로) 양보하다', '17234'], ['flexible', '융통성 있는', G('flexible')], ['intellectual', '지적인', '18615'], ['leisure', '여가', '12461'], ['rigorous', '격렬한·힘든', '21253'], ['lifting weights', '역기 들기', '13078']], src: 'Vocabulary', nt: '낱말 6개', n: ['<del>엄밀한</del> → 격렬한·힘든(운동 이야기) · <del>융통성 있는·유연성 있는</del> → 융통성 있는 — 여기서는 몸이 아니라 마음이 유연한'] },
      { t: 'discuss', k: 'fix', img: '12055', title: 'Starter questions', qs: ['How much free time do you have? When do you usually have it? What\'s your favorite thing to do?', 'Where do you usually spend your free time? Who do you spend it with?', 'Do you wish you had more free time? Why or why not?'], src: 'Starter Questions', nt: '시작 질문', n: ['<del>Do you wish you have</del> → had(바람은 과거형) · Whom → Who(말할 때 자연스럽게)', '질문 다섯을 네 줄로 묶었습니다'] },
      { t: 'read', k: 'keep', img: G('compromise'), small: 'Keyword', title: 'Compromise 🤝', paras: ['When two people want two different things that they can\'t both have, they **compromise**. Then both of them are **satisfied**.', 'Learning to compromise is very important for children.'], gloss: [['both', '둘 다'], ['satisfied', '만족한']], src: 'Keywords: Compromise', nt: '핵심어 — 양보', n: ['<del>that that they can\'t</del> → that they can\'t(겹친 낱말)', '축구공과 보드게임을 든 남매가 새끼손가락을 거는 사진 — «What did they decide?»'] },
      { t: 'discuss', k: 'keep', img: '15414', title: 'Talk about it', qs: ['When have you had to compromise with someone?', 'Is compromising easy or difficult for you? Are you flexible?'], src: 'Talk about it', nt: '이야기해 보기', n: ['형제·친구와 TV·게임 차례를 정한 경험부터'] },
      { t: 'rule', k: 'new', title: 'so or because?', left: { h: 'reason → so → result', ex: ['I\'m a very social person, **so** I always want to socialize.', 'I\'m tired, **so** I take a nap.'] }, right: { h: 'result → because → reason', ex: ['Working out is important **because** I can\'t exercise while studying.', 'I read a lot **because** I love new ideas.'] }, q: 'Where does the reason go — after so or after because?', nt: '규칙 찾기', n: ['네 학생 글에 so·since 가 들어 있습니다 — 읽기 전에 규칙부터', 'since 는 because 와 같은 뜻(원본 운동 학생 글)'] },
      { t: 'read', k: 'fix', img: G('exercise-bike'), small: 'Free time · Exercise', title: 'I Need a Good Workout 🚵', paras: ['In my free time, it\'s very important to get a good workout. I prefer **rigorous** activities like riding my mountain bike off-road or **lifting weights**.', 'I study hard for school, and since I can\'t exercise while studying, working out is very important. It keeps my body strong, helps me stay focused, and helps me get a good night\'s sleep.'], src: 'Keywords (Exercise)', nt: '읽기 ① 운동', n: ['<del>tiding</del> → riding', '원본 사진(헬스장 어른) → 진흙길을 달리는 산악자전거 학생'] },
      { t: 'read', k: 'fix', img: G('social-teens'), small: 'Free time · Friends', title: 'I Love Seeing My Friends 👫', paras: ['Whenever I have free time, the most important thing is seeing my friends. I\'m a very social person, so I always want to **socialize**.', 'Sometimes my friends and I like to play soccer, which is great because it\'s fun and good exercise, too. However, often we just like to **hang out** together at the mall or at the park. We just talk and spend time together.'], gloss: [['socialize', '사람들과 어울리다'], ['hang out', '함께 놀다']], src: 'Keywords (Social)', nt: '읽기 ② 친구', n: ['원본 사진(술잔 든 어른들의 옥상 파티) → 공원에서 아이스크림을 먹는 또래 친구들'] },
      { t: 'read', k: 'keep', img: '12495', small: 'Free time · Learning', title: 'I Love New Ideas 📚', paras: ['I\'m always trying to become more intelligent by learning new ideas and facts. I\'m a very **intellectual** person, so I spend my free time trying to gather new knowledge.', 'I love reading books and newspaper articles that teach me about new topics. Of course, I try to find ones that are more interesting and exciting than my schoolwork.'], gloss: [['gather', '모으다'], ['knowledge', '지식']], src: 'Keywords (Intellectual)', nt: '읽기 ③ 공부', n: ['«so» 문장을 찾아 이유와 결과를 나눠 보기'] },
      { t: 'read', k: 'fix', img: '12174', small: 'Free time · Relaxing', title: 'I Just Want to Relax 😌', paras: ['When I\'m not busy with schoolwork, the most important thing is just to relax and relieve stress. I think the best way to do this is to forget about my work as much as possible, which is why I usually just relax and have **leisure** time.', 'Sometimes I play video games, watch TV, read a book, or even take a nap.'], gloss: [['relieve stress', '스트레스를 풀다'], ['take a nap', '낮잠을 자다']], src: 'Keywords (Leisure)', nt: '읽기 ④ 쉼', n: ['원본 사진(«NETFLIX» 글자가 크게 보이는 화면) → 게임하는 아이 사진'] },
      { t: 'match', k: 'new', title: 'Who is it? 🧩', left: [G('exercise-bike'), G('social-teens'), '12495', '12174'], right: ['leisure', 'exercise', 'intellectual', 'social'], nt: '짝 맞추기', n: ['정답: 1-exercise · 2-social · 3-intellectual · 4-leisure', '맞힌 뒤 «She\'s an intellectual person, so she …» 로'] },
      { t: 'discuss', k: 'fix', title: 'Discussion questions', qs: ['How do the different people spend their free time? In what ways are the activities different?', 'Which category of free time activities is the most important to you? Which is the least important?', 'How could you combine exercise and social time? Is it possible to combine all four into one activity?'], src: 'Discussion Questions 1–4', nt: '토론 질문', n: ['원본 3·4번(합치기 두 문항)을 한 줄로 · 예시 «For example» 문장은 강사가 말로', '답의 예: play soccer with friends = exercise + social'] },
      { t: 'guess', k: 'new', img: '15708', open: [0, 8], q: 'What are they doing?', chips: ['Is it a sport?', 'Is it cold there?', 'Do they need skates?'], nt: 'Guess who — 무엇을 할까?', n: ['정답: ice skating(스케이트) — 역할극 3 «눈 오는 날» 로 이어집니다', 'Yes/No 질문으로 물어야 타일을 엽니다'] },
      { t: 'ox', k: 'new', img: '12495', s: 'The intellectual student reads only her schoolbooks.', nt: '⭕❌', n: ['정답 ❌ → «No. She tries to find books that are more interesting than her schoolwork.»'] },
      { t: 'story', k: 'new', img: '12351', title: 'Yoona and Jay', lines: [['Jay', 'Let\'s play soccer this Saturday!'], ['Yoona', 'Hmm… I want to see the new movie.'], ['Jay', 'We can\'t do both… or can we?'], ['Yoona', 'Let\'s play soccer in the morning, so we can see the movie after lunch!'], ['Jay', 'Great! That\'s a good compromise.']], nt: '우리 이야기', n: ['양보의 모범 — 역할극 1 바로 앞에서 «이렇게 정하면 돼요» 를 보여 줍니다', 'so 가 들어간 줄을 찾기'] },
      { t: 'read', k: 'fix', img: '18710', small: 'Role-play 1 · Saturday', title: 'Soccer or a Movie? ⚽🎬', paras: ['Your friends have different ideas. Help them agree by compromising!', '**14:00–19:00** (5 hours) · cloudy, 16°C. You are with three friends. Two of them want to play soccer in the park. You and one other friend want to see the new movie with your favorite actor. The movie is 2 hours long, and the park is 30 minutes from the cinema. Everyone will be hungry at dinner time.'], src: 'Role-play (intro · Free Time 1)', nt: '역할극 1', n: ['<del>Saturday, September 6, 2019</del>(그날은 금요일) → Saturday · <del>four of your friends</del>(바람이 넷 중 셋만 적힘) → three friends', '원본 소개 쪽 «Your friends have different ideas …» 를 첫 줄로 합쳤습니다'] },
      { t: 'table', k: 'new', small: 'Role-play 1', title: 'Our plan for Saturday', head: ['Time', 'What will we do?'], rows: [['14:00 – ___', '___'], ['___ – ___', '___'], ['___ – 19:00', 'Have dinner together'], ['Why is it a good compromise?', 'Because ___']], nt: '계획표', n: ['5시간 안에 축구 + 영화(2시간) + 이동(30분) + 저녁이 다 들어가게', '예시: 14:00–15:30 soccer · 16:00–18:00 movie · 18:00–19:00 dinner'] },
      { t: 'read', k: 'fix', img: G('water-park'), small: 'Role-play 2 · Sunday', title: 'Ocean World or the Mall? 🌊🛍️', paras: ['**11:00–18:00** (7 hours) · a hot summer Sunday, 29°C ☀️', 'You and your 3 friends were all given money by your parents to do something fun. The weather is hot and muggy. Two of your friends want to go to Ocean World, but you want to go shopping at the mall. What do you decide?'], src: 'Role-play (Free Time 2)', nt: '역할극 2 상황', n: ['원본 상황 글 그대로 — 날짜만 고쳤습니다(다음 쪽 메모)'] },
      { t: 'yourturn', k: 'fix', img: G('water-park'), title: 'Role-play 2 · Our plan', lines: ['First, we will ___.', 'Then we will ___, so ___.', 'It\'s a good compromise because ___.'], chips: ['cool off', 'go shopping'], src: 'Role-play (Free Time 2)', nt: '역할극 2 계획', n: ['<del>Sunday, December 1, 2019 · hot and muggy</del>(12월과 날씨가 안 맞음) → a hot summer Sunday', '원본 «6 hours» 는 11~18시(7시간)와 안 맞아 7 hours 로', '원본 사진(수족관 터널) → 물놀이 공원 — Ocean World 는 워터파크입니다'] },
      { t: 'yourturn', k: 'fix', img: '12967', title: 'Role-play 3 · Snowy day ❄️', lines: ['09:00–18:00 · a cold, snowy Saturday, -5°C. What do you want to do with your friends?', 'In the morning, we will ___ because ___.', 'In the afternoon, we will ___, so ___.'], src: 'Role-play (Free Time 3)', nt: '역할극 3', n: ['<del>Saturday, January 6, 2020 · far in the future</del> → a cold, snowy Saturday', '원본 빈 그림 칸 → 눈싸움 사진 · because 와 so 를 한 번씩 쓰게'] },
      { t: 'yourturn', k: 'new', img: '12021', title: 'My free time', lines: ['In my free time, I usually ___.', 'I like it because ___.', 'I\'m a(n) ___ person, so ___.', 'I can be flexible. For example, ___.'], chips: ['social', 'active', 'intellectual', 'relaxed'], nt: '내 말로', n: ['네 학생 가운데 누구와 닮았는지 말하며 마무리'] },
      ...close(G2, { img: G('cover-career'), q: 'What job do you want to have?', ko: '다음 시간 — 나의 진로! 내 재능으로 어떤 일을 할 수 있을까?' }),
    ] },
  // ───────────────────────── 007-009
  { code: '007-009', tab: '나의 진로', unit: U3, title: 'My Career', orig: 26,
    intro: '내 재능과 기술을 말하고, 여러 직업이 무슨 일을 하는지 알아봅니다. 이야기: 수학을 좋아하는 Joe 와 창의력이 중요하다는 Joo Young.',
    fixed: ['뜻 «involuntary functions 비자발적 기능» → 저절로 일어나는 기능 · «involve 감다» → (일이) …을 포함하다·…을 하게 되다', '«Scientists think that left-brained people …» 은 과학적 근거가 약한 속설 → Some people say … (강사 메모 · «사람이 정할 것»)', 'Joo Young: «Steven Hawking» → Stephen Hawking', 'Try it: «What skills to people need» → do people need', '직업 쪽 «How do the people use logic …» → How do people use …', 'Warm up «highly paid.» → 물음표 없는 지시문 정리'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-career'), q: 'What job do you want to have?', story: 'Joe loves math. Joo Young loves art and music. What are you good at?', nt: '표지 + Big Question', n: ['여러 직업 옷을 입고 장난스럽게 서 있는 아이들 — «Who is who?»', '끝에 «I\'m good at ___, so I could be a ___» 로 말하는 것이 목표'] },
      ...open(G3),
      { t: 'qa', k: 'fix', img: '12566', title: 'Warm up', q: 'Name 3 jobs that you think are highly paid. Why?', a: 'I think ___ are highly paid because ___.', src: 'Warm Up', nt: '몸풀기 질문', n: ['highly paid = 돈을 많이 받는 · 틀린 답이 없는 질문 — 이유를 꼭 붙이게'] },
      { t: 'vocab', k: 'fix', title: 'New words 📖', cols: 3, words: [['involuntary functions', '저절로 일어나는 기능', '18039'], ['logic', '논리', '21217'], ['involve', '(일을) 포함하다', '17332'], ['archaeologist', '고고학자', G('archaeologist')], ['sculptor', '조각가', '15690'], ['veterinarian', '수의사', '13369']], src: 'Vocabulary', nt: '낱말 6개', n: ['<del>비자발적 기능</del> → 저절로 일어나는 기능(심장 박동·숨쉬기) · <del>감다</del> → (일이) 포함하다 — What does the job involve? = 그 일은 무엇을 하나요?'] },
      { t: 'discuss', k: 'keep', img: '18672', title: 'Big Question 💭', qs: ['What do you like to do? What job do you want to have?', 'What skills do you have? How can you use them in your career?'], src: 'Big Question · Different People, different stories', nt: 'Big Question', n: ['원본 두 쪽의 질문을 한 쪽으로', '생각 풍선(로켓·기타·붓)이 뜬 아이 사진 — «What is she thinking about?»'] },
      { t: 'read', k: 'keep', img: '12815', small: 'Keyword', title: 'Brain 🧠', paras: ['The **brain** is the body\'s control center. It controls your thoughts and feelings and the movement of your muscles.', 'It also handles **involuntary functions** like heartbeat and breathing.'], gloss: [['control center', '조종실'], ['heartbeat', '심장 박동']], src: 'Keywords: Brain', nt: '핵심어 — 뇌', n: ['«Can you stop your heart?» — 저절로 일어나는 기능을 몸으로 느끼게'] },
      { t: 'read', k: 'fix', img: G('brain-sides'), small: 'Keyword', title: 'Talented 🎨🔢', paras: ['Different people are **talented** in different fields.', 'Some people say that "left-brained" people are better at logical thinking. They are very organized and often good at math. "Right-brained" people are thought to be more creative. They may be better at things like art and music.'], gloss: [['field', '분야'], ['organized', '정리를 잘하는'], ['creative', '창의적인']], src: 'Keywords: Talented', nt: '핵심어 — 재능', n: ['원본 «Scientists think that …» → Some people say that … — 좌뇌형·우뇌형은 뇌과학이 뒷받침하지 않는 속설입니다(«사람이 정할 것»)', '강사 멘트: «사실 우리는 두 쪽 뇌를 함께 써요. 그래서 수학도 미술도 연습하면 늘어요!»'] },
      { t: 'discuss', k: 'fix', img: '18067', title: 'Talk about it', qs: ['What are your best subjects in school?', 'What are your hobbies?', 'Do you think you are more logical or more creative? Why?'], src: 'Talk about it', nt: '이야기해 보기', n: ['원본 3번 «left-brained or right-brained?» → more logical or more creative? (속설을 사실처럼 묻지 않게)'] },
      { t: 'rule', k: 'new', title: 'Talent or skill?', left: { h: 'talent — 타고난 재주', ex: ['I have a natural **talent** for math.', 'She **is talented** in music.'] }, right: { h: 'skill — 연습해서 얻는 능력', ex: ['I **practice** to improve my drawing **skills**.', 'Engineers use math **skills** every day.'] }, q: 'Which one can you get by practicing?', nt: '규칙 찾기', n: ['시험 11번 «What is the difference between talent and skill?» 을 미리 — 답: skill 은 연습으로 늘어요', 'Joe 도 «I\'m successful because I study a lot» — 재능 + 노력'] },
      { t: 'read', k: 'keep', img: '18369', small: "Joe's Story ①", title: 'Math Is My Language', paras: ['Math is my best subject in school. Often, my test scores are the best in my class. My teacher tells me that I have a **natural talent** for mathematics.', 'I see numbers as a language, and I am able to learn it very quickly. Of course, this doesn\'t mean that I don\'t work hard. I\'m successful at math because I study a lot.'], gloss: [['natural talent', '타고난 재능'], ['successful', '잘하는·성공한']], src: "Joe's Story", nt: 'Joe ①', n: ['«because» 문장 찾기 — 재능 + 노력'] },
      { t: 'read', k: 'keep', img: '12857', small: "Joe's Story ②", title: 'So Much Math in Computers', paras: ['I have some hobbies in my personal life, but I don\'t think I\'m that creative. I really enjoy learning about computers, and that means both playing games and learning how they work. There\'s so much math in computers!', 'I really hope I can use math in my career. I even feel that if I don\'t, it will be a big waste of my talent.'], gloss: [['personal life', '개인 생활'], ['a waste of', '…의 낭비']], src: "Joe's Story", nt: 'Joe ②', n: ['<del>leaming</del> → learning(OCR 확인)'] },
      { t: 'read', k: 'keep', img: '13202', small: "Joe's Story ③", title: 'A Satisfying Career', paras: ['Fortunately, I\'m interested in many careers where I can use math every day. I think I could be a scientist, an engineer, or a computer programmer.', 'Then I can have a **satisfying career** doing something that I am really good at. Plus, I can spend my time **following directions** without having to be that creative.'], gloss: [['satisfying', '만족스러운'], ['following directions', '지시를 따르기']], src: "Joe's Story", nt: 'Joe ③', n: ['<del>Plus I can</del> → Plus, I can', '«Do you agree with Joe?» — 다음 Joo Young 이야기로 이어 가기'] },
      { t: 'read', k: 'keep', img: G('jooyoung'), small: "Joo Young's Story ①", title: 'I Love Art and Music', paras: ['I am good at math in school too, although it\'s not my best subject.', 'My favorite subjects are definitely art and music, because they give me the chance to use my **creative skills**.'], gloss: [['definitely', '단연코·확실히'], ['chance', '기회']], src: "Joo Young's Story (1)", nt: 'Joo Young ①', n: ['Joe 와 같은 점(수학을 잘함)과 다른 점(가장 좋아하는 과목)을 먼저 짚기'] },
      { t: 'read', k: 'keep', img: '12076', small: "Joo Young's Story ②", title: 'I Want to Be a Writer', paras: ['I understand Joe\'s arguments, and I can understand why some people might want to work a job where they just follow directions and solve problems.', 'The creativity involved in painting a picture or writing a story is difficult for many people to achieve. I know that well because my personal ambition is to be a writer.'], gloss: [['achieve', '이루다'], ['ambition', '꿈·포부']], src: "Joo Young's Story (1)", nt: 'Joo Young ②', n: ['«involved in» — 이번 낱말 involve 가 글 속에서 나옵니다'] },
      { t: 'read', k: 'fix', img: '17208', small: "Joo Young's Story ③", title: 'Everyone Needs Creativity', paras: ['However, I don\'t really agree with Joe. I don\'t think that anyone can be successful without being creative in some way.', 'Famous scientists like Einstein and Stephen Hawking used their creativity to imagine solutions to very complicated math problems.'], src: "Joo Young's Story (2)", nt: 'Joo Young ③', n: ['<del>Steven Hawking</del> → Stephen Hawking', '«However» — 여기서부터 Joe 와 생각이 갈립니다'] },
      { t: 'read', k: 'keep', img: G('jooyoung'), small: "Joo Young's Story ④", title: 'Maybe an Engineer?', paras: ['Today, many engineers use complex math and their creativity to design **dynamic** new products.', 'Now that I think about it, being an engineer might not be such a bad job for me after all!'], gloss: [['dynamic', '활기찬·역동적인'], ['after all', '결국']], src: "Joo Young's Story (2)", nt: 'Joo Young ④', n: ['마지막 줄의 반전 — Joo Young 의 생각이 어떻게 바뀌었나?'] },
      { t: 'discuss', k: 'keep', title: 'Questions ①', qs: ['What are Joe\'s talents? What is he good at?', 'How does Joe want to use his talents in the future?', 'What does Joe think he isn\'t good at? Why does he think so?'], src: 'Questions 1–3', nt: '질문 ①', n: ['답을 말한 뒤 글로 돌아가 찾아 확인'] },
      { t: 'discuss', k: 'keep', title: 'Questions ②', qs: ['How are Joo Young and Joe similar?', 'How does Joo Young disagree with Joe? What evidence does she use to support her argument?', 'Do you think it\'s possible to be successful without being creative? Why or why not?'], src: 'Questions 4–6', nt: '질문 ②', n: ['evidence = 근거(아인슈타인·호킹·엔지니어)'] },
      { t: 'ox', k: 'new', img: G('jooyoung'), s: 'Joo Young thinks people can be successful without being creative.', nt: '⭕❌', n: ['정답 ❌ → «No. She thinks everyone needs to be creative in some way.»'] },
      { t: 'story', k: 'new', img: '19352', title: 'Yoona and Jay', lines: [['Yoona', 'Jay, you\'re so good at drawing!'], ['Jay', 'Thanks! But I\'m not good at math.'], ['Yoona', 'You can practice. Skills get better with practice.'], ['Jay', 'That\'s true. Maybe I could be a cartoonist someday.'], ['Yoona', 'A cartoonist needs creative skills and hard work!']], nt: '우리 이야기', n: ['talent/skill 규칙을 대화로 다시 — 다음 쪽 «만화가» 로 이어집니다'] },
      { t: 'qa', k: 'keep', img: G('cartoonist'), label: 'Try it! · cartoonist', title: 'Job detective 🔍', q: 'What does the job involve? What kind of training do you need? How do they use creative skills?', a: 'A cartoonist ___. They need ___.', src: 'Try it · cartoonist', nt: '직업 ① 만화가', n: ['원본 직업 쪽 질문 셋 그대로 — 강사가 세 질문을 차례로', '<del>What skills to people need</del> → do people need(Try it 머리 쪽)'] },
      { t: 'guess', k: 'new', img: G('paleontologist'), open: [2, 7], q: 'What is her job?', chips: ['Does she work outside?', 'Does she study dinosaurs?', 'Is she a scientist?'], nt: 'Guess who — 무슨 직업?', n: ['정답: paleontologist(고생물학자) — 공룡 뼈를 발굴', '고고학자(archaeologist)와 헷갈리게 두었다가 다음 쪽에서 비교'] },
      { t: 'table', k: 'fix', small: 'Try it!', title: 'Paleontologist or archaeologist?', head: ['', 'paleontologist 🦖', 'archaeologist 🏺'], rows: [['What do they study?', 'dinosaurs and fossils', 'old tools and pots from long ago'], ['Where do they work?', 'at a dig site, in a lab', 'at a dig site, in a museum'], ['Logic or creativity?', 'Both! ___', 'Both! ___']], src: 'Try it · paleontologist · archaeologist', nt: '두 직업 비교', n: ['원본은 직업마다 같은 질문 셋이라 헷갈리기 쉬운 두 직업을 표로 비교했습니다', '한 줄 정리: 공룡·화석 → paleontologist · 옛사람의 물건 → archaeologist'] },
      { t: 'qa', k: 'keep', img: '15844', label: 'Try it! · veterinarian', title: 'Job detective 🔍', q: 'What does a veterinarian do? How many years do you have to go to school? How do they use logic and reasoning skills?', a: 'A vet ___. They use logic to ___.', src: 'Try it · veterinarian', nt: '직업 ② 수의사', n: ['<del>How do the people use</del> → How do they use', '답의 예: 우리나라 수의대는 6년'] },
      { t: 'memory', k: 'new', items: ['13174', '12779', '13202', '15690'], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ① 보기', n: ['원본 직업 쪽의 나머지 넷(사진가·건축가·프로그래머·조각가)', '5초 보여 주고 다음 쪽으로'] },
      { t: 'memory', k: 'new', hidden: true, items: ['13174', '12779', '13202', '15690'], q: 'What jobs did you see?', a: 'I saw a ___. A ___ uses ___ skills.', nt: '기억 게임 ② 말하기', n: ['기억한 직업마다 «uses logic / creative skills» 를 붙여 말하기'] },
      { t: 'yourturn', k: 'new', img: '18181', title: 'My career', lines: ['I\'m good at ___.', 'I have a talent for ___, and I want to improve my ___ skills.', 'I could be a(n) ___ because ___.', 'This job involves ___.'], chips: ['math', 'drawing', 'music', 'science'], nt: '내 말로', n: ['Big Question 에 내 답으로 — talent · skill · involve 를 한 번씩'] },
      ...close(G3, { img: G('cover-space'), q: 'Would you like to travel to space?', ko: '다음 시간 — 우주 탐사! 돈을 내고 우주에 간 첫 관광객은 누구일까?' }),
    ] },
  // ───────────────────────── 010-012
  { code: '010-012', tab: '우주 탐사', unit: U4, title: 'Exploring Space', orig: 27,
    intro: '우주에 있는 것들을 말하고 «I would rather …» 로 골라 말합니다. 이야기: 첫 우주 관광객 Dennis Tito. 아폴로·허블·보이저·국제우주정거장을 알아봅니다.',
    fixed: ['Tito: «returned to earth on April 28, 2001» → 4월 28일 출발 · 5월 6일 귀환 · «orbited the earth for 7 days» → almost 8 days · «Since 2001, six other …» → By 2009 · «private companies may send …» → 이미 현실(«사람이 정할 것»)', 'Tito: «every year more companies start that want to make money off of it» → more and more companies want to make money from it', 'Apollo 제목 «(1967–1972)» → 본문과 같게 1961–1972', 'Voyager «dupiter» → Jupiter(OCR 확인)', '뜻 «determined 단호한» → 굳게 결심한', 'Forming an Opinion «April 20012» → April 2001'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-space'), q: 'Would you like to travel to space?', story: 'In 2001, a man paid $20 million to fly into space. Would you do it?', nt: '표지 + Big Question', n: ['창밖으로 지구가 보이는 우주선 안에서 둥둥 떠다니며 웃는 관광객들', '끝에 «I would / wouldn\'t be a space tourist because ___» 로 말하는 것이 목표'] },
      ...open(G4),
      { t: 'qa', k: 'keep', img: '13364', title: 'Warm up', q: 'What can you see in space? Give 5 and describe each!', a: 'I can see the ___. It is ___.', chips: ['the Moon', 'stars', 'planets'], src: 'Warm Up', nt: '몸풀기 질문', n: ['다섯 개를 모두 «It is …» 로 설명하게'] },
      { t: 'vocab', k: 'fix', title: 'New words ① 📖', cols: 5, words: [['artificial', '인공의', '14029'], ['astronauts', '우주비행사', '16822'], ['astronomers', '천문학자', '14764'], ['planets', '행성', '18724'], ['satellites', '(인공)위성', G('satellite')]], src: 'Vocabulary', nt: '낱말 ① 5개', n: ['astronaut(가는 사람) · astronomer(보는 사람) — 다음 쪽 규칙 찾기에서 다시'] },
      { t: 'vocab', k: 'fix', title: 'New words ② 📖', cols: 5, words: [['fulfill a dream', '꿈을 이루다', '18181'], ['determined', '굳게 결심한', '17199'], ['professional', '전문적인·직업인', '12492'], ['industry', '산업', '13043'], ['intergovernmental treaties', '정부 간 조약', '14451']], src: 'Vocabulary', nt: '낱말 ② 5개', n: ['<del>단호한</del> → 굳게 결심한(Determined to visit space = 우주에 꼭 가겠다고 마음먹고)', '원본 «fulfill his dream» → 낱말 카드는 fulfill a dream(글 속에서 his 로 다시 만납니다)'] },
      { t: 'discuss', k: 'keep', img: '19384', title: 'Big Question 🚀', qs: ['What do scientists do in space?', 'Have you seen science fiction movies set in space?', 'Have you studied about space in school? What did you learn?'], src: 'Big Question · Starter Questions 1', nt: 'Big Question', n: ['과학소설 책을 읽는 아이 사진 — «What is on the cover?»'] },
      { t: 'discuss', k: 'keep', img: '18833', title: 'Starter questions', qs: ['Why do humans send rockets into space? What do satellites do today?', 'Do you want to go to space? Do you think astronauts have interesting jobs?', 'Some people think countries waste money sending rockets to space. What do you think?'], src: 'Starter Questions', nt: '시작 질문', n: ['원본 다섯 문항 — 1번은 앞 쪽(Big Question)에, 4번 «What do you think humans will do in space in the future?» 는 마지막 «내 말로» 에서', '«What functions do satellites have» → What do satellites do(쉬운 말)'] },
      { t: 'read', k: 'keep', img: '19028', small: 'Keyword', title: 'Astronauts and Astronomers 🔭', paras: ['**Astronauts** study space by going there. They fly into space and conduct experiments to learn about it.', '**Astronomers** look at space through telescopes and study it from a distance.'], gloss: [['conduct experiments', '실험을 하다'], ['from a distance', '멀리서']], src: 'Keywords', nt: '핵심어', n: ['사진: 우주정거장에서 떠다니는 물방울로 실험하는 우주비행사'] },
      { t: 'rule', k: 'new', title: 'Would you rather …?', left: { h: 'Question', ex: ['**Would you rather** be an astronaut **or** an astronomer?', '**Would you rather** go to the Moon **or** to Mars?'] }, right: { h: 'Answer', ex: ['**I would rather** be an astronomer **because** it\'s safer.', '**I\'d rather** go to Mars. It sounds exciting!'] }, q: 'What comes after "I would rather"?', nt: '규칙 찾기', n: ['원본 질문 «Would you rather be an astronaut or an astronomer? Why?» 에서 규칙을 뽑았습니다', '규칙: would rather + 동사원형(be·go) — 이유(because)를 꼭 붙이기'] },
      { t: 'qa', k: 'keep', img: '16742', title: 'Your choice', q: 'Would you rather be an astronaut or an astronomer? Why?', a: 'I would rather be an ___ because ___.', chips: ['exciting', 'safe'], src: 'Would you rather …?', nt: '골라 말하기', n: ['원본 질문 그대로 — 방금 찾은 규칙으로 답하기'] },
      { t: 'table', k: 'fix', small: 'Things in space', title: 'Natural or artificial?', head: ['Natural 🌙', 'Artificial (man-made) 🛰️'], rows: [['the Moon', 'a space satellite'], ['___', '___'], ['___', '___']], tip: 'the Moon · planets · stars · a space probe · a space station — 어느 쪽일까요? (UFO 는? 아무도 몰라요!)', src: 'Things in Space', nt: '자연 · 인공', n: ['원본 «Some objects in space are natural, while others are artificial (man-made)» 를 표로', '답: planets · stars → natural / a space probe · a space station → artificial'] },
      { t: 'guess', k: 'new', img: '18724', open: [3, 4], q: 'What is it?', chips: ['Is it a planet?', 'Does it have rings?', 'Is it natural?'], nt: 'Guess who — 무엇일까?', n: ['정답: Saturn(토성)과 목성 — 고리가 보이면 바로 맞힙니다'] },
      { t: 'qa', k: 'keep', img: G('space-probe'), label: 'Things in space', title: 'What does it do?', q: 'Look at the object and say what you know about it. What does it do?', a: 'It is a ___. It ___.', chips: ['takes pictures', 'studies planets'], src: 'Things in Space (probe · satellite)', nt: '우주 물체', n: ['원본 물체 쪽(위성·달·행성·탐사선·UFO·별)의 질문 그대로 — 탐사선 사진으로 한 번 더'] },
      { t: 'read', k: 'fix', img: G('rocket-launch'), small: 'Dennis Tito ①', title: 'The First Space Tourist', paras: ['In 2001, Dennis Tito became the world\'s first **space tourist**. Mr. Tito is an American engineer and businessman. He is a very wealthy millionaire with a large fortune.', 'After a long career as an engineer designing airplanes, Mr. Tito wanted to **fulfill his dream** of flying in space, even though he wasn\'t an astronaut.'], gloss: [['wealthy', '부유한'], ['fortune', '재산'], ['even though', '비록 …이지만']], src: 'Dennis Tito (1)', nt: 'Tito ①', n: ['실존 인물이라 얼굴 사진 대신 로켓 발사 장면으로(«사람이 정할 것»)'] },
      { t: 'read', k: 'fix', img: '16822', small: 'Dennis Tito ②', title: 'Eight Days in Space', paras: ['**Determined** to visit space, Mr. Tito paid the Russian government $20 million of his own money to fly into space on a Russian rocket. He flew into space on April 28, 2001.', 'In space, Mr. Tito visited the International Space Station and orbited the earth for almost 8 days. He also did some science experiments that he said were helpful to his engineering company. He came back to earth on May 6.'], src: 'Dennis Tito (2)', nt: 'Tito ②', n: ['<del>He returned to earth on April 28, 2001</del> → 4월 28일은 출발한 날 · 귀환은 5월 6일', '<del>for 7 days</del> → almost 8 days(7일 22시간)'] },
      { t: 'read', k: 'fix', img: G('space-tourist'), small: 'Dennis Tito ③', title: 'A New Industry', paras: ['Before Mr. Tito\'s flight, only **professional** astronauts chosen by countries had ever flown in space. His flight created a new **industry**: space tourism.', 'By 2009, six more wealthy space tourists had paid Russia $20–35 million each to fly in space. Today, private companies also send tourists into space.'], gloss: [['chosen by', '…에게 뽑힌'], ['private company', '민간 회사']], src: 'Dennis Tito (3)', nt: 'Tito ③', n: ['<del>Since 2001, six other …</del>(2009년까지의 숫자) → By 2009, six more … had …', '원본 다음 쪽 «In the future, private companies may send rockets …» 는 이미 일어난 일 → Today, private companies also send …(«사람이 정할 것»)'] },
      { t: 'read', k: 'fix', img: '18163', small: 'Dennis Tito ④', title: 'An Exciting Idea?', paras: ['Space tourism is still very new, and flying in space is still very expensive.', 'However, more and more companies want to make money from it. For many people, this is an exciting idea.'], gloss: [['expensive', '비싼']], src: 'Dennis Tito (4)', nt: 'Tito ④', n: ['<del>every year more companies start that want to make money off of it</del> → more and more companies want to make money from it'] },
      { t: 'read', k: 'fix', img: '19028', small: 'Dennis Tito ⑤', title: 'Not Everyone Is Happy', paras: ['However, not everyone is happy about space tourism. Before Mr. Tito\'s flight, many astronauts and scientists at NASA refused to help with his training.', 'They thought space travel should be for scientific research, not for profit.'], gloss: [['refuse', '거절하다'], ['profit', '이익(돈벌이)']], src: 'Dennis Tito (4)', nt: 'Tito ⑤', n: ['원본 «the idea of a space tourist was insulting» 은 뜻이 어려워 «research, not for profit» 이유만 남겼습니다(강사가 말로 보충 가능)', '다음 쪽 찬반 질문의 근거가 됩니다'] },
      { t: 'discuss', k: 'fix', title: 'Forming an opinion ①', qs: ['What did Dennis Tito do in April 2001?', 'Why did he want to fly in space?', 'How did Mr. Tito fulfill his dream? What did he do before his flight?'], src: 'Forming an Opinion 1–3', nt: '질문 ①', n: ['<del>April 20012</del> → April 2001'] },
      { t: 'discuss', k: 'keep', title: 'Forming an opinion ②', qs: ['Why did some astronauts and scientists disapprove of Mr. Tito\'s space flight?', 'Do you think space tourism is a good idea? Why or why not?', 'If you were very rich, would you be a space tourist? Why or why not?'], src: 'Forming an Opinion 4–6', nt: '질문 ②', n: ['찬반을 반으로 나눠 한 가지씩 이유 말하기'] },
      { t: 'ox', k: 'new', img: G('rocket-launch'), s: 'Dennis Tito was a professional astronaut chosen by his country.', nt: '⭕❌', n: ['정답 ❌ → «No. He was an engineer and businessman. He paid for his trip.»'] },
      { t: 'story', k: 'new', img: '18181', title: 'Yoona and Jay', lines: [['Jay', 'If I were very rich, I would be a space tourist!'], ['Yoona', 'Really? It costs millions of dollars.'], ['Jay', 'I know, but I could see the Earth from space!'], ['Yoona', 'I would rather be an astronomer. I can see the stars from the ground.'], ['Jay', 'Then let\'s look at the stars together tonight!']], nt: '우리 이야기', n: ['If I were … · would rather 를 대화로 다시', 'Yoona(해외)·Jay(국내) 의 1과 성격이 이어집니다'] },
      { t: 'read', k: 'fix', img: G('moon-landing'), small: 'Space history · Apollo', title: 'The Apollo Program (1961–1972) 🌕', paras: ['The Apollo program was NASA\'s third human spaceflight program. It landed the first humans on the Moon from 1969 to 1972.', 'Apollo ran from 1961 to 1972, with the first crewed flight in 1968.'], gloss: [['land', '착륙시키다'], ['crewed', '사람이 탄']], src: 'The Apollo Program', nt: '역사 ① 아폴로', n: ['<del>제목 (1967–1972)</del> → 본문과 같게 1961–1972', '원본 «carried out by the National Aeronautics and Space Administration (NASA), which accomplished …» 는 긴 문장이라 둘로 나눴습니다'] },
      { t: 'read', k: 'keep', img: G('hubble'), small: 'Space history · Hubble', title: 'The Hubble Space Telescope 🔭', paras: ['The Hubble Space Telescope was launched into low Earth orbit in 1990, and it is still working today.', 'It was not the first space telescope, but it is one of the largest. It is an important research tool for astronomers.'], gloss: [['launch', '쏘아 올리다'], ['research tool', '연구 도구']], src: 'The Hubble Space Telescope', nt: '역사 ② 허블', n: ['원본 «most versatile … a public relations boon for astronomy» 는 어려운 말이라 «an important research tool for astronomers» 로 줄였습니다'] },
      { t: 'read', k: 'fix', img: G('voyager'), small: 'Space history · Voyager', title: 'The Voyager Program 🛰️', paras: ['The Voyager program uses two robotic **space probes**, Voyager 1 and Voyager 2, to study the outer Solar System.', 'The probes were launched in 1977, when Jupiter, Saturn, Uranus and Neptune were lined up in a good way for the trip.'], gloss: [['outer', '바깥쪽의'], ['lined up', '줄지어 있는']], src: 'The Voyager Program', nt: '역사 ③ 보이저', n: ['<del>dupiter</del> → Jupiter', '«to take advantage of a favorable alignment» → 쉬운 말로 풀었습니다'] },
      { t: 'read', k: 'keep', img: '16822', small: 'Space history · ISS', title: 'The International Space Station 🌍', paras: ['The International Space Station (ISS) is a space station in low Earth orbit. It was first launched in 1998.', 'It is a joint project of five space agencies: NASA, Roscosmos, JAXA, ESA, and CSA. Who owns and uses the station is decided by **intergovernmental treaties** and agreements.'], gloss: [['joint project', '공동 사업'], ['agency', '기관']], src: 'The International Space Station', nt: '역사 ④ 국제우주정거장', n: ['원본 «ISS programme» 영국식 철자 → 문장을 줄이며 뺐습니다', '«Which agency is from Japan?» — JAXA'] },
      { t: 'match', k: 'new', title: 'Space history 🧩', left: [G('moon-landing'), G('hubble'), G('voyager'), '16822'], right: ['Voyager', 'the ISS', 'Apollo', 'Hubble'], nt: '짝 맞추기', n: ['정답: 1-Apollo · 2-Hubble · 3-Voyager · 4-the ISS', '맞힌 뒤 «When was it launched?»'] },
      { t: 'yourturn', k: 'new', img: '19262', title: 'My space future', lines: ['In the future, I think humans will ___ in space.', 'I would rather go to ___ because ___.', 'Space tourism is / isn\'t a good idea because ___.'], nt: '내 말로', n: ['원본 시작 질문 4번 «What do you think humans will do in space in the future?» 를 여기서'] },
      ...close(G4, { img: '12430', q: 'Can you remember all four units?', ko: '다음 시간 — 복습! 해외 생활·여가·진로·우주 낱말을 모두 문장으로 말해 봐요.' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 30 Review', orig: 23,
    intro: '네 단원 낱말 38개를 사진으로 떠올리고 한 문장씩 만들어 말합니다. 단원마다 게임이 하나씩.',
    fixed: ['원본 순서 Space → Abroad → Career → Free time → 단원 순서(Abroad · Free time · Career · Space)로', 'Free time 낱말 쪽 머리글이 «My Career» 로 잘못 붙은 것(18~22쪽) 정리', 'flexible 사진(요가) → 뜻(융통성 있는)에 맞는 사진', '어른·사무실 사진 위주 → 또래 학생 사진'],
    slides: [
      { t: 'cover', k: 'new', img: '12430', q: 'Can you use every word in a sentence?', story: 'Four units, one big adventure — let\'s review!', nt: '표지', n: ['원본 Review 는 모든 쪽이 «USE THE WORD/PHRASE IN A SENTENCE» 한 가지 — 그 목표를 표지 질문으로'] },
      { t: 'vocab', k: 'fix', title: 'Unit 1 · Living Abroad', cols: 5, words: [['travel', '여행하다', '12309'], ['abroad', '해외에(서)', '12746'], ['foreign', '외국의', '19390'], ['misunderstanding', '오해', G('misunderstanding')], ['hardworking', '부지런한', '19111'], ['accent', '억양·말투', '17014'], ['heritage', '(문화) 유산', '18481'], ['culture', '문화', '12595'], ['traditions', '전통', '12526'], ['immigrants', '이민자', '14591']], src: 'Review (Abroad)', nt: '1단원 낱말 10', n: ['원본 10쪽을 한 쪽 10칸으로 — 사진을 가리키면 낱말을 말하고, 그다음 문장으로'] },
      { t: 'yourturn', k: 'keep', img: '18649', title: 'Use it in a sentence!', lines: ['I want to travel ___ someday.', 'My ___ friend speaks with a different accent.', 'Now you! Choose a word: ___.'], chips: ['abroad', 'foreign'], src: 'Review · USE THE WORD IN A SENTENCE', nt: '1단원 문장 만들기', n: ['원본 지시 그대로 — 빈칸 셋은 몸풀기, 마지막 줄은 학생이 낱말을 골라 자기 문장'] },
      { t: 'ox', k: 'new', img: '18955', s: 'Mark wants to travel abroad now because the USA is boring.', nt: '1단원 ⭕❌', n: ['정답 ❌ → «No. He wants to travel in his own country because the USA is so diverse.»'] },
      { t: 'vocab', k: 'fix', title: 'Unit 2 · My Free Time', cols: 5, words: [['free time', '여가 시간', '12461'], ['opinion', '의견', '18492'], ['satisfied', '만족한', '14536'], ['socialize', '어울리다', '12021'], ['hang out', '함께 놀다', '13092'], ['exercise', '운동(하다)', '12385'], ['intellectual', '지적인', '18615'], ['compromise', '양보하다', '17234'], ['flexible', '융통성 있는', G('flexible')], ['leisure', '여가', '12174']], src: 'Review (Free time — 원본 머리글 «My Career»)', nt: '2단원 낱말 10', n: ['원본 머리글이 «My Career» 로 잘못 붙어 있던 쪽들', '<del>flexible 요가 사진</del>(몸이 유연한) → 뜻(융통성 있는)에 맞는 사진'] },
      { t: 'yourturn', k: 'keep', img: '12055', title: 'Use it in a sentence!', lines: ['On weekends, I like to ___ with my friends.', 'We couldn\'t agree, so we made a ___.', 'Now you! Choose a word: ___.'], chips: ['hang out', 'compromise'], src: 'Review · USE THE WORD IN A SENTENCE', nt: '2단원 문장 만들기' },
      { t: 'order', k: 'new', img: '17234', words: ['compromise', 'Let\'s', 'make', 'a'], nt: '2단원 순서 맞추기', n: ['정답: Let\'s make a compromise.'] },
      { t: 'vocab', k: 'fix', title: 'Unit 3 · My Career', cols: 5, words: [['creative', '창의적인', '12076'], ['skills', '기술·능력', '18586'], ['natural talent', '타고난 재능', '19451'], ['training', '훈련·교육', '15134'], ['involve', '포함하다', '17332'], ['volunteer', '자원봉사(하다)', '16359'], ['following directions', '지시를 따르기', '18859'], ['dynamic', '활기찬', '21273'], ['control', '조종하다·다스리다', '12815'], ['career', '직업·진로', '12566']], src: 'Review (Career)', nt: '3단원 낱말 10', n: ['volunteer 는 단원 글에 안 나오는 낱말입니다(«사람이 정할 것»)'] },
      { t: 'yourturn', k: 'keep', img: '18067', title: 'Use it in a sentence!', lines: ['An artist needs to be very ___.', 'I practice every day to improve my ___.', 'Now you! Choose a word: ___.'], chips: ['creative', 'skills'], src: 'Review · USE THE WORD IN A SENTENCE', nt: '3단원 문장 만들기' },
      { t: 'match', k: 'new', title: 'Who does this job? 🧩', left: ['13369', '15690', '13174', '12779'], right: ['sculptor', 'architect', 'veterinarian', 'photographer'], nt: '3단원 짝 맞추기', n: ['정답: 1-veterinarian · 2-sculptor · 3-photographer · 4-architect'] },
      { t: 'vocab', k: 'fix', title: 'Unit 4 · Exploring Space', cols: 4, words: [['waste money', '돈을 낭비하다', '17226'], ['conduct', '(실험을) 하다', '19028'], ['experiment', '실험', '17314'], ['explore', '탐험하다', '18071'], ['natural', '자연의', '12487'], ['artificial', '인공의', '14029'], ['satellites', '위성', G('satellite')], ['space tourist', '우주 관광객', G('space-tourist')]], src: 'Review (Space)', nt: '4단원 낱말 8', n: ['원본 Review 맨 앞(Space)을 단원 순서에 맞게 맨 뒤로'] },
      { t: 'yourturn', k: 'keep', img: '19028', title: 'Use it in a sentence!', lines: ['Astronauts ___ experiments in space.', 'The Moon is ___, but a satellite is artificial.', 'Now you! Choose a word: ___.'], chips: ['conduct', 'natural'], src: 'Review · USE THE WORD IN A SENTENCE', nt: '4단원 문장 만들기' },
      { t: 'scramble', k: 'new', items: [['tnelsap', '18724'], ['tuasontra', '16822'], ['lorxepe', '18071']], nt: '4단원 낱말 퍼즐', n: ['정답: planets · astronaut · explore'] },
      { t: 'guess', k: 'new', img: '18163', open: [0, 5], q: 'Who is it? Where is he?', chips: ['Is he a tourist?', 'Is he in space?', 'Is he doing an experiment?'], nt: 'Guess who — 복습 보스', n: ['정답: an astronaut in a space station, doing an experiment', '네 단원 질문(Yes/No)을 다 섞어 묻기'] },
      { t: 'discuss', k: 'new', img: '18672', title: 'Four Big Questions', qs: ['Would you like to live in a foreign country? Why or why not?', 'What do you do in your free time?', 'What job do you want to have?', 'Would you rather be an astronaut or an astronomer?'], nt: '네 Big Question', n: ['단원 표지 질문 넷 — 처음 대답과 지금 대답을 비교'] },
      ...close([['I can talk about living abroad and my free time.', '해외 생활과 여가 시간을 말할 수 있어요 — I want to live abroad. In my free time, I hang out with friends.'], ['I can talk about my talents and my career.', '내 재능과 진로를 말할 수 있어요 — I have a talent for art, so I could be a cartoonist.'], ['I can talk about space.', '우주에 대해 말할 수 있어요 — I would rather be an astronomer.']], { img: '14998', q: 'Are you ready for the test?', ko: '다음 시간 — 시험! 20문항을 말로 답해요. 할 수 있어요!' }),
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 30 Unit Test', orig: 11,
    intro: '20문항 말하기 시험. 원본 지시 «Answer the questions and explain» 그대로 — 대답 + 이유를 기준으로 합니다.',
    fixed: ['1 «Space» 대문자 정리', '2 «What is the importance of exploring the space?» → Why is it important to explore space?', '3 «How would Astronauts survive in Mars mission?» → How would astronauts survive on a mission to Mars?', '7 «University» → university', '8 «Tell me a situation … Misunderstanding Issue with a friend.» → Tell me about a time when you had a misunderstanding with a friend.', '10 «on here Earth» → on Earth', '11 «between Talent and skill.» → talent and skill?', '12 «left-brained or right-brained» → more logical or more creative(속설)', '14·15 «How do the people use …» → How do people use …', '16 «Whom» → Who', '18 «effects of good exercise to our body» → How does good exercise help our body?'],
    slides: [
      { t: 'cover', k: 'new', img: '19111', q: 'Test time! You can do it! 💪', story: '20 questions · Answer and explain!', nt: '표지', n: ['원본 지시 «Answer the questions and explain» — 한 문장 대답 + 이유 한 문장이 기준'] },
      { t: 'table', k: 'new', small: 'How to answer', title: 'Answer + explain', head: ['Step', 'Example'], rows: [['1. Answer', 'I would like to go to Mars.'], ['2. Explain', 'Because I want to see the red planet.'], ['3. Add more', 'I could also do experiments there.']], tip: '모든 문항에 1·2 번은 꼭! 3 번까지 하면 ⭐', nt: '대답 방법', n: ['시험 전에 한 번 함께 연습'] },
      { t: 'discuss', k: 'fix', img: '18833', small: 'Space', title: 'Questions 1–3', qs: ['1. If you could travel in space, where would you like to go?', '2. Why is it important to explore space?', '3. How would astronauts survive on a mission to Mars?'], src: 'Test 1–3', nt: '문항 1–3', n: ['<del>where in Space</del> → where · <del>the importance of exploring the space</del> → Why is it important to explore space? · <del>survive in Mars mission</del> → on a mission to Mars'] },
      { t: 'discuss', k: 'keep', img: '14764', small: 'Space · Abroad', title: 'Questions 4–6', qs: ['4. What is the difference between astronauts and astronomers?', '5. Would you rather be an astronaut or an astronomer? Why?', '6. Would you like to live in a foreign country? Why or why not?'], src: 'Test 4–6', nt: '문항 4–6' },
      { t: 'discuss', k: 'fix', img: '17236', small: 'Abroad', title: 'Questions 7–9', qs: ['7. Why do many university students prefer to study abroad?', '8. Tell me about a time when you had a misunderstanding with a friend.', '9. Why do people from different cultures misunderstand each other?'], src: 'Test 7–9', nt: '문항 7–9', n: ['<del>University</del> → university · <del>Tell me a situation … Misunderstanding Issue</del> → Tell me about a time when …'] },
      { t: 'discuss', k: 'fix', img: '12815', small: 'Career', title: 'Questions 10–12', qs: ['10. What controls all the functions of our body on Earth?', '11. What is the difference between talent and skill?', '12. Do you think you are more logical or more creative? Why?'], src: 'Test 10–12', nt: '문항 10–12', n: ['<del>on here Earth</del> → on Earth · 12번 <del>left-brained or right-brained</del> → more logical or more creative(속설)'] },
      { t: 'discuss', k: 'fix', img: '12076', small: 'Career', title: 'Questions 13–15', qs: ['13. Is it possible to be successful without being creative?', '14. How do people use logic and reasoning skills at work?', '15. How do people use creative skills at work?'], src: 'Test 13–15', nt: '문항 13–15', n: ['<del>How do the people use … Creative skills</del> → How do people use … creative skills'] },
      { t: 'discuss', k: 'fix', img: '12021', small: 'Free time', title: 'Questions 16–18', qs: ['16. Where do you usually spend your free time? Who do you spend it with?', '17. When have you had to compromise with someone?', '18. How does good exercise help our body?'], src: 'Test 16–18', nt: '문항 16–18', n: ['<del>Whom</del> → Who · <del>What are the effects of good exercise to our body?</del> → How does good exercise help our body?'] },
      { t: 'discuss', k: 'keep', img: '12351', small: 'Free time', title: 'Questions 19–20', qs: ['19. How do you hang out with your friends?', '20. How could you combine exercise and social time?'], src: 'Test 19–20', nt: '문항 19–20' },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–8', 'Good try!', '틀린 단원을 한 번 더 복습해요'], ['9–14', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['15–19', 'Great!', '거의 다 왔어요 — 이유를 더 길게'], ['20 ⭐', 'Perfect!', 'BTS 31 로 출발! 🎉']], src: '점수표 (Congratulations)', nt: '점수표', n: ['점수마다 다음에 할 일을 적어 «점수로 끝나지 않게»'] },
      ...close([['I can answer questions and explain why.', '질문에 답하고 이유를 말할 수 있어요 — I think so because …'], ['I can talk about my world.', '해외 생활·여가 시간을 말할 수 있어요.'], ['I can talk about my future.', '진로와 우주를 말할 수 있어요.']], { img: G('bts31-movies'), q: 'What is the best movie you have ever seen?', ko: 'BTS 31 예고 — 영화관에 가요! 동물·교복·반장 선거 이야기도 기다려요.' }),
    ] },
  ],
};
