// BTS 29 새 교재 설계 데이터 — 영웅·롤모델 · 돈 · 친구 · 거짓말 (Level 8 토론)
// k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
import { open, close } from '../common.mjs';
const USONG_3 = { t: 'song', k: 'new', small: "Let's sing! ♪ Rap chant", title: "Lend and Borrow 🤝", img: "gen:bts-29-song-lend-borrow", nt: "빌려주기·빌리기 랩(새로 지음)", n: ["곡조: Rap chant (4 beats) — 멜로디 없이 4박으로 읊는 챈트, 가사는 이 단원 낱말로 새로 지었습니다","lend에서 펜을 화면 밖으로 내밀고, borrow에서 끌어당기는 동작으로 방향 익히기"], src: '새로 지음', lines: ["I lend my pen to Jay, to Jay!","Jay borrows my pen today!","I get it back, so I trust my friend.","Good friends are important to me!","Can you keep a secret? Yes, I can!","An embarrassing secret? I would not tell!","You lend a book to me, I borrow it from you.","That's what friends do — I trust you!"] };
const USONG_4 = { t: 'song', k: 'new', small: "Let's sing! ♪ Clap chant", title: "Have You Ever Told a Lie? 🤥", img: "gen:bts-29-song-honest-friends", nt: "정직 챈트(새로 지음)", n: ["곡조: Clap chant (4 beats) — 멜로디 없이 4박으로 읊는 챈트, 가사는 이 단원 낱말로 새로 지었습니다","Have you ever?에서 상대를 가리키고, honest에서 손을 가슴에 얹는 동작"], src: '새로 지음', lines: ["Have you ever told a lie?","Have you ever cheated? Why?","Honest friends tell the truth,","We can trust them, me and you!","Dishonest people lie and cheat,","Their rumors spread from street to street.","In a hard spot, what would you do?","I would be honest! How about you?"] };

const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3', U4 = 'Unit 4', RV = 'Review';
const G = k => 'gen:bts-29-' + k;
const CHANT = (song, swap) => ['⚠️ 원본 노래: «' + song + '» — 가사를 옮기지 않고 이 과 문장으로 새로 쓴 챈트입니다', '손뼉 박자에 맞춰 두 번 — 두 번째는 학생이 빈 말을 바꿔 부릅니다(' + swap + ')'];
const DISC = ['정답이 없는 토론 — «I agree / I disagree because …» 로 이유까지', '한 학생이 답하면 다른 학생에게 «Do you agree?» 로 넘깁니다'];

export const COURSE = {
  head: `<h1>BTS 29 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트에 올라가 있는 BTS 29 원본 <b>105쪽</b>(5묶음)을 한 장씩 읽고, BTS 1 과 같은 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · 과 끝 «I can» · 다음 시간 예고)으로 다시 짰습니다. 이 권은 <b>Level 8 토론 권</b>입니다 — 내가 존경하는 사람(Heroes) → 돈과 행복(Money) → 친구·믿음·비밀(Friends) → 정직과 거짓말(Lying) → 복습(Review). 문법은 새로 배우기보다 <b>Wh- 질문 · Yes/No 질문 · «Have you ever …?» · «Would you …?»</b> 로 의견을 묻고 답하는 데 씁니다.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>원본의 <b>낱말·토론 질문·읽기 글(Jack·Sunny·Jason·Naomi·Sue·Jim·Claire·Ryan)은 그대로</b>입니다. 틀린 한국어 뜻과 문법만 고쳤고, 긴 질문 목록은 한 쪽에 3~5개씩 나눴습니다.</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>, <b>⭕❌</b>, <b>Guess who 타일</b>, <b>짝·순서·기억 게임</b>, <b>Yoona 와 Jay 의 이어지는 이야기</b>(과마다 한 장면), <b>내 말로(Your turn)</b>, <b>I can ✅</b>, <b>다음 시간 예고</b>.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>점선 상자(«새 사진 생성 중»)는 맞는 사진이 없어 새로 만드는 자리입니다(이 권 요청 26장 — 무대 위 록스타 꿈, 요트 여행, 바가지 쓴 운동화, 망친 저녁밥처럼 «와!» 또는 «앗!» 하고 볼 장면 위주). 원본의 실존 인물 얼굴 사진(가수 등)은 빼고, 에디슨·타이거 우즈는 전구 실험·골프 장면 사진으로 바꿨습니다.</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>고친 뜻 승인</b> — 원본 한국어 뜻이 틀린 곳: admire «감탄하다»→존경하다, spend «보내다»→(돈을) 쓰다, allowance «허용»→용돈, bargain «흥정하다»→싸게 잘 산 것, ripped off «사기당한»→바가지 쓴, average «평균»→평범한, fancy «공상»→멋진, rent «임대»→빌리다, save «저장하기»→저축하다, institute «학회»→학원, cheated «속이는»→부정행위를 했다, crossed «교차»→(길을) 건넜다, spread «퍼지다»→퍼뜨리다, destroy «멸하다»→망가뜨리다, damage «손해»→해치다.</li>
<li><b>001 Tiger Woods 사실 고침</b> — 원본 «has won 13 of golf's major championships» → 2019년 우승으로 <b>15회</b>입니다. 숫자를 고쳤는데, 사생활 논란이 있는 인물이라 «롤모델» 예시로 둘지 다른 운동선수로 바꿀지.</li>
<li><b>001 «web browsing» 활동</b> — 수업 중 인터넷 검색을 시킬지(화상수업이면 숙제로).</li>
<li><b>007 Jim 의 이야기 «500 dollars»</b> — 4학년이 빌려준 돈으로는 큰 금액이라 «50 dollars» 로 줄일지. 시안은 원본 그대로 두었습니다.</li>
<li><b>010 민감한 질문</b> — «빨간불에 길을 건넌 적 있나요?», «소문의 피해자가 된 적 있나요?» 는 학생이 원하지 않으면 답하지 않아도 된다고 강사 메모를 달았습니다. 초등 반에서 둘지.</li>
<li><b>마치는 노래</b> — 원본 «Everyday Heroes» · 돈 노래 · «Friends, friends 1 2 3» · «Who Took the Cookie (Tommy broke the cookie jar)». 저작권 확인 전까지 가사를 새로 쓴 챈트로 바꿨습니다(곡조는 자체 녹음 권장). 007 은 쪽 수가 넘쳐 챈트를 뺐습니다.</li>
<li><b>새로 만들 사진 26장</b> — 점선 자리(힉스필드 크레딧).</li>

<li><b>새 단원 노래 2곡</b> — 노래가 없던 단원에 새로 지은 노래를 Hello Song 바로 뒤에 넣었습니다: Unit 3 «Lend and Borrow»(Rap chant (4 beats)) · Unit 4 «Have You Ever Told a Lie?»(Clap chant (4 beats)). 곡조는 모두 저작권이 끝난 동요(또는 손뼉·랩 챈트)이고 가사는 그 단원 낱말로 새로 썼습니다. <b>가사 승인</b>과 <b>녹음(반주·노래)</b>이 필요합니다 — 지금은 줄마다 🔊(기계 음성)로만 들을 수 있습니다.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '영웅', unit: U1, title: 'Heroes', orig: 25,
    intro: '내가 존경하는 사람 — 가족·학교·유명인 중 누구를 닮고 싶은지, 좋은 롤모델은 어떤 사람인지 말합니다. 읽기: Jack 의 영웅(에디슨·타이거 우즈)과 Sunny 의 영웅(의사 아빠)!',
    fixed: ['<del>Admire 감탄하다</del> → 존경하다 · <del>Respect 존경</del> → 존경하다(동사로 통일)', '<del>Unselfish 이기적인지 않은</del> → 이기적이지 않은', '<del>inspired with</del> → inspired by (3곳)', '<del>What kind of people has inspired you?</del> → have inspired you', '<del>described 설명된</del> → (~라고) 불리는 · <del>developed 개발</del> → 개발했다', '<del>Thanks to him.</del> → Thanks to him, we have electric lights!(문장 완성)', 'Tiger Woods <del>13 of golf\'s major championships</del> → 15(사실 고침 — 사람이 정할 것 2번)', '<del>Are they living or dead?</del> → Is the person alive today?', '실존 인물 얼굴 사진(에디슨·타이거 우즈) → 전구 실험·골프 장면 사진'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-heroes'), q: 'Who is your hero?', story: 'Everyone has a hero. Some heroes wear capes. Some heroes wear lab coats. Who do you want to be like?', nt: '표지 + Big Question', n: ['망토를 두른 아이가 소방관·의사·과학자 포스터 앞에서 포즈 — «영웅은 가까이에 있다»', '끝날 때 «My hero is … because …» 로 답하는 것이 목표'] },
      ...open([['I can talk about people I admire.', '내가 존경하는 사람에 대해 말할 수 있어요.'], ['I can describe a good role model.', '좋은 롤모델이 어떤 사람인지 말할 수 있어요.'], ['I can ask and answer Wh- and Yes/No questions.', 'Wh- 질문과 Yes/No 질문을 묻고 답할 수 있어요.']], 'Lesson Goals (Wh- Questions · Yes/No Questions)'),
      { t: 'discuss', k: 'keep', title: 'Warm up', img: G('rockstar-kid'), qs: ['Do you want to be like someone?', 'Who is it?', 'Why do you want to be like him or her?'], chips: ['I want to be like …', 'because he/she is …'], src: '5쪽 Warm up', nt: '생각 말하기', n: ['원본 «Why do you want to be like him?» → him or her(여자 영웅도)', '사진: 빗자루 기타를 든 꼬마 록스타 — «Who does he want to be like?» 로 웃으며 시작'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Hero words 🔒', cols: 4, words: [['hero', '영웅', '15459'], ['role model', '본받고 싶은 사람', G('rolemodel')], ['personal', '개인적인, 나만의', '12080'], ['famous', '유명한', '18934'], ['admire', '존경하다', '15187'], ['respect', '존경하다', '12348'], ['inspire', '영감을 주다', '15490'], ['successful', '성공한', '15743']], src: '4·6쪽 Vocabulary', nt: '낱말 ① (가림→공개)', n: ['<del>Admire 감탄하다</del> → 존경하다 · <del>Respect 존경</del> → 존경하다', '가린 채 사진만 보고 먼저 말하게 → 공개'] },
      { t: 'read', k: 'keep', title: 'Keyword: Admire', img: G('admire'), paras: ['"I really admire Johnny. He is very talented, humble, and hard-working. He became very successful. I respect him."'], gloss: [['talented', '재능 있는'], ['humble', '겸손한']], src: '7쪽 Keyword Admire', nt: '읽기 — 존경하는 사람', n: ['<del>talented, humble and hard working</del> → talented, humble, and hard-working', '«Why does the speaker admire Johnny?» 로 이유 세 가지 찾기'] },
      { t: 'vocab', k: 'fix', title: 'A good role model is…', cols: 4, words: [['unselfish', '이기적이지 않은', '14245'], ['generous', '너그러운', '15428'], ['humble', '겸손한', '14725'], ['trustworthy', '믿을 수 있는', '18638'], ['easygoing', '느긋한, 마음이 편한', '12684'], ['honest', '정직한', '18467'], ['hardworking', '열심히 일하는', '17178']], src: '8쪽 Good Role Model', nt: '낱말 ② 성격', n: ['<del>Unselfish 이기적인지 않은</del> → 이기적이지 않은 · <del>관대한</del> → 너그러운(쉬운 말)', '원본 질문 «What kinds of people do you admire?» 를 이 쪽에서 바로 묻습니다'] },
      { t: 'match', k: 'new', title: 'Match it!', left: ['15428', '18638', '17178', '14725'], right: ['humble', 'generous', 'hardworking', 'trustworthy'], nt: '짝 맞추기 게임', n: ['짝마다 한 문장: «A good role model is generous.»'] },
      { t: 'discuss', k: 'keep', title: 'Who do you admire?', img: '12284', qs: ['Do you admire anyone in your family? Why?', 'Do you admire anyone at your school? Why?', 'Do you admire any famous people? Why?'], chips: ['I admire …'], src: '8·9쪽', nt: '생각 말하기', n: ['앞 쪽 성격 낱말을 이유에 넣어 말하게(«because she is generous»)', '원본 «at your school/workplace» → 학생 반은 school, 성인 반은 workplace 로 바꿔 묻기'] },
      { t: 'rule', k: 'new', title: 'Yes/No or Wh-?', left: { h: 'Yes/No question', ex: ['**Do** you admire anyone?', '→ Yes, I do. / No, I don\'t.'] }, right: { h: 'Wh- question', ex: ['**Who** do you admire?', '→ I admire my mom.'] }, q: 'Which question needs a longer answer? Why?', nt: '규칙 찾기 — 질문 두 종류', n: ['Yes/No 질문은 Do 로 시작 → 예/아니요, Wh- 질문은 Who·Why·What 으로 시작 → 내용으로 답', '이어서 학생끼리 Yes/No 하나 + Wh- 하나씩 묻기'] },
      { t: 'read', k: 'fix', title: 'Keyword: Inspire', img: '15277', paras: ['"My friend Jana inspires me. She works really hard and is very successful in school. Still, she\'s not selfish. If I have a question or a problem, she always helps me out.', 'I try to be more like her, so I work hard, too."'], gloss: [['inspire', '영감을 주다'], ['selfish', '이기적인']], src: '10쪽 Keyword Inspire', nt: '읽기 — 나에게 영감을 주는 친구', n: ['«What does Jana do when a friend has a problem?» → She helps them out.'] },
      { t: 'discuss', k: 'fix', title: 'Who inspires you?', img: '15490', qs: ['What kind of people have inspired you? How?', 'What can you do to be more like them?', 'Are you inspired by your parents or friends? Why?'], chips: ['I am inspired by …'], src: '11·12쪽', nt: '생각 말하기', n: ['<del>What kind of people has inspired you?</del> → have', '<del>inspired with</del> → inspired by', '원본 질문 6개를 셋으로 묶음 — «Why do you want to be like them?» · celebrities 는 이어 묻기로'] },
      { t: 'table', k: 'fix', small: 'New words', title: 'Words in the story', head: ['word', '뜻', 'word', '뜻'], rows: [['inventor', '발명가', 'devices', '기기, 장치'], ['described as', '~라고 불리는', 'experiments', '실험'], ['developed', '개발했다', 'athletes', '운동선수'], ['golfer', '골프 선수', 'regarded as', '~로 여겨지는']], src: '13쪽 New words', nt: '이야기 전 새 낱말', n: ['<del>Inventor 발명자</del> → 발명가 · <del>described 설명된</del> → ~라고 불리는 · <del>developed 개발</del> → 개발했다', '«regarded as» 는 원본에 없던 낱말 — 글에 나와서 더했습니다'] },
      { t: 'read', k: 'fix', title: "Jack's Story (1)", img: '15331', paras: ['My hero is Thomas Edison. He was an American inventor and businessman. He has been described as America\'s greatest inventor. He developed many devices, like the electric light bulb.', 'Thanks to him, we have electric lights! His first successful test of the light bulb was on October 22, 1879.'], gloss: [['light bulb', '전구']], src: "14쪽 Jack's Story", nt: '읽기 — Jack ① 에디슨', n: ['<del>Thanks to him.</del> → 문장 완성', '실존 인물 얼굴 사진 → 전구 실험 장면'] },
      { t: 'read', k: 'fix', title: "Jack's Story (2)", img: '13340', paras: ['My second hero is Tiger Woods, a famous golfer. He is talented, and he worked very hard. He is widely regarded as one of the greatest golfers of all time.', 'He became a professional golfer in 1996, when he was only 20. He has won 15 major championships. He has inspired many young people to play golf.'], src: "15쪽 Jack's Story", nt: '읽기 — Jack ② 타이거 우즈', n: ['<del>the youths</del> → young people', '사람이 정할 것 2번 — 인물 선택'] },
      { t: 'fill', k: 'fix', title: "Tiger's numbers", img: '13394', lines: ['Tiger became a professional golfer in ___.', 'He was only ___ years old.', 'He has won ___ major championships.'], chips: ['1996', '20', '15', '1879'], src: "15쪽 Jack's Story", nt: '빈칸 — 글 속 숫자', n: ['답: 1996 · 20 · 15 (1879 는 에디슨의 전구 — 헷갈리기 칩)', '<del>13 of golf\'s major championships</del> → 15(2019년 마스터스 우승 반영)', '앞 쪽 글을 가리고 기억으로 채웁니다 — 마지막에 «He is a true role model.» 에 동의하는지 묻기'] },
      { t: 'guess', k: 'new', img: '19204', open: [0, 4], q: 'What did Edison develop?', chips: ['a telephone', 'a light bulb', 'a golf ball'], nt: 'Guess it 타일', n: ['학생이 번호를 부르면 칸을 엽니다', '맞히면: «Thanks to Edison, we have light bulbs!»'] },
      { t: 'read', k: 'fix', title: "Sunny's Story", img: G('doctor-dad'), paras: ['My hero is my father. He is a doctor, and he helps sick people every day. He works hard, but he always has time for our family. He is my role model.', 'Famous people can be heroes, too. But I don\'t know them personally. I know my father, so he is my real hero.'], gloss: [['personally', '직접, 개인적으로']], src: "16·17쪽 Sunny's Story", nt: '읽기 — Sunny 의 영웅', n: ['원본 두 쪽 글을 한 쪽으로 — 문장은 원본 그대로', '«Why is Sunny\'s father a real hero?»'] },
      { t: 'ox', k: 'new', img: '12080', s: 'Sunny\'s hero is a famous singer.', nt: '⭕❌', n: ['정답 ❌ → «No! Sunny\'s hero is Sunny\'s father. He is a doctor.»'] },
      { t: 'discuss', k: 'keep', title: 'DISCUSSION', img: '16287', qs: ['Who are Jack\'s heroes? Who is Sunny\'s hero?', 'Is it better to have a famous hero or a personal hero? Why?', 'Do you agree with Jack or with Sunny?', 'What makes someone a hero?'], chips: ['I agree with …', 'because …'], src: '18쪽 DISCUSSION', nt: '토론', n: DISC },
      { t: 'story', k: 'new', small: 'Story', title: 'Yoona and Jay: My hero', img: G('hero-poster'), lines: [['Yoona', 'Jay, who is your hero?'], ['Jay', 'Mango! He is brave and generous.'], ['Yoona', 'Really? He ate all your cookies!'], ['Jay', 'OK… brave, but not generous! 😅']], nt: '이어지는 이야기 ①', n: ['이 권 내내 나오는 Yoona·Jay·Mango — 이 과 낱말(brave · generous)로만', '«Is Mango a good role model?» 로 웃으며 토론'] },
      { t: 'discuss', k: 'fix', title: 'Find a role model', img: '19424', qs: ['Who is the person? Is the person alive today?', 'What did the person do?', 'Why do many people admire this person?', 'Would you like to be like this person? Why?'], src: '19쪽 Web browsing', nt: '조사 발표', n: ['<del>Are they living or dead?</del> → Is the person alive today?', '화상수업이면 숙제로 조사 → 다음 시간 첫 5분 발표(사람이 정할 것 3번)'] },
      { t: 'yourturn', k: 'fix', img: G('cover-heroes'), title: 'My greatest hero', lines: ['My greatest hero is ___.', 'I admire him/her because he/she is ___.', 'To be like him/her, I will ___.'], chips: ['generous', 'humble', 'honest'], src: '20쪽 My greatest Hero', nt: '내 말로', n: ['원본 빈 공책 쪽 → 말할 틀 + 성격 낱말 칩'] },
      { t: 'song', k: 'new', title: 'My Hero (chant)', lines: ['Who is your hero? Tell me, who?', 'My hero is kind and honest, too!', 'She works so hard, she helps me out.', 'That is what a hero is about!'], img: '15459', src: '25쪽 Closing Song', nt: '마치는 챈트', n: CHANT('Everyday Heroes', 'She → He, kind → brave') },
      ...close([['I can talk about people I admire.', 'I admire my mom because she is generous.'], ['I can describe a good role model.', 'A good role model is honest and humble.'], ['I can ask and answer Wh- and Yes/No questions.', 'Who is your hero? / Do you admire him? — Yes, I do.']], { img: G('cover-money'), q: 'Do you want to be rich when you grow up?', ko: '커서 부자가 되고 싶나요? (다음 시간)' }),
    ] },
  // ───────────────────────── 004
  { code: '004', tab: '돈', unit: U2, title: 'Money', orig: 21,
    intro: '돈 이야기 — 용돈을 얼마나 받고 어디에 쓰는지, 싸게 잘 산 것(bargain)과 바가지 쓴 것(ripped off), 그리고 «돈으로 행복을 살 수 있을까?» 를 토론합니다. 읽기: 부자가 되고 싶은 Jason vs 보람 있는 일이 먼저인 Naomi!',
    fixed: ['<del>Spend 보내다</del> → (돈을) 쓰다 · <del>Allowance 허용</del> → 용돈', '<del>Bargain 흥정하다</del> → 싸게 잘 산 것 · <del>Ripped off 사기당한</del> → 바가지 쓴', '<del>Average 평균</del> → 평범한 · <del>Fancy 공상</del> → 멋진 · <del>Rent 임대</del> → 빌리다 · <del>save 저장하기</del> → 저축하다', 'Naomi 글 <del>businessman or CEO</del> → businessperson or CEO · <del>Job</del> → job(대문자) · <del>ail</del> → all', '<del>1M dollars</del> → one million dollars'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-money'), q: 'Can money buy happiness?', story: 'A boy counts coins from his piggy bank. Will he spend them or save them?', nt: '표지 + Big Question', n: ['돼지저금통을 깨고 동전 더미 앞에서 고민하는 아이', '끝에 «I think money can/can\'t buy happiness because …» 로 답하게'] },
      ...open([['I can talk about spending and saving money.', '돈을 쓰고 모으는 것에 대해 말할 수 있어요.'], ['I can talk about bargains and being ripped off.', '싸게 잘 산 것과 바가지 쓴 것에 대해 말할 수 있어요.'], ['I can give my opinion about money and happiness.', '돈과 행복에 대한 내 생각을 말할 수 있어요.']], 'Lesson Goals (spend · allowance · bargain · ripped off)'),
      { t: 'discuss', k: 'keep', title: 'Warm up', img: '18068', qs: ['How much money do you have?', 'Do you want to be rich when you grow up?', 'What will you do with your money?'], chips: ['I have …', 'I want to …'], src: '4쪽 Warm up', nt: '생각 말하기', n: ['첫 질문은 «in your wallet / piggy bank» 로 가볍게 — 액수를 꼭 말하지 않아도 됩니다'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Money words 🔒', cols: 3, words: [['spend', '(돈을) 쓰다', '13289'], ['allowance', '용돈', G('allowance')], ['buy', '사다', '12369'], ['expensive', '비싼', '12455'], ['bargain', '싸게 잘 산 것', '18746'], ['ripped off', '바가지 쓴', G('rippedoff')]], src: '5쪽 Vocabulary', nt: '낱말 (가림→공개)', n: ['<del>Spend 보내다</del> · <del>Allowance 허용</del> · <del>Bargain 흥정하다</del> · <del>Ripped off 사기당한</del> → 이 쪽의 뜻으로', 'ripped off 는 속된 말 — «I paid too much.» 와 같은 뜻이라고 함께 알려 줍니다'] },
      { t: 'discuss', k: 'keep', title: 'Spend & allowance', img: '13289', qs: ['What things do you buy every week?', 'How much money do you spend every week?', 'Do you get a weekly allowance? How much do you get?'], chips: ['I buy …', 'I spend about …', 'I get …'], src: '6·7쪽 Keyword', nt: '생각 말하기 ①', n: ['액수를 말하기 싫으면 «a little / a lot» 으로 답해도 됩니다'] },
      { t: 'discuss', k: 'keep', title: 'Buy & expensive', img: '19336', qs: ['When you ask your mom to buy something, what does she say?', 'What is the most expensive thing you have ever bought?', 'Were you happy with it?'], chips: ['She says …', 'The most expensive thing was …'], src: '8·9쪽 Keyword', nt: '생각 말하기 ②' },
      { t: 'rule', k: 'fix', title: 'Bargain or ripped off?', left: { h: 'A bargain 😀', ex: ['a nice thing', 'for a **very cheap** price'] }, right: { h: 'Ripped off 😡', ex: ['a **very expensive** thing', 'that **breaks** or is **not useful**'] }, q: 'What is the best bargain you have ever found? Have you ever been ripped off? How did it feel?', src: '10·11쪽 Keyword', nt: '규칙 찾기 — 두 낱말 비교', n: ['원본 두 쪽 설명을 한 쪽에 나란히', '원본 «it\'s overpriced» 도 함께: 너무 비싸다 = overpriced'] },
      { t: 'ox', k: 'new', img: '18746', s: 'Shoes for half price are a bargain.', nt: '⭕❌', n: ['정답 ⭕ → «Yes! Half price is a bargain.» · 이어서 «What if they break the next day?» → «I got ripped off!»'] },
      { t: 'read', k: 'fix', title: "Jason's Story (1)", img: '15558', paras: ['I want to be rich when I grow up. People with average jobs don\'t have much money. I think rich people are happier. They can have nice cars, fancy clothes, and luxurious apartments. They can also take vacations abroad.'], gloss: [['average', '평범한'], ['fancy', '멋진, 화려한'], ['luxurious', '호화로운'], ['abroad', '해외로']], src: "13쪽 Jason's Story", nt: '읽기 — Jason ①', n: ['<del>Average 평균</del> · <del>Fancy 공상</del> → 이 쪽의 뜻', '«Why does Jason think rich people are happier?»'] },
      { t: 'read', k: 'fix', title: "Jason's Story (2)", img: '15243', paras: ['I will get a good education and become a businessman. I will work long hours, but the earnings will be worth it. I will drive high-priced cars and wear expensive suits. I will pay people to clean my house.'], gloss: [['earnings', '번 돈, 수입'], ['worth it', '그럴 만한 가치가 있는'], ['suits', '정장']], src: "14쪽 Jason's Story", nt: '읽기 — Jason ②', n: ['<del>Earning 수입</del> → earnings(번 돈)'] },
      { t: 'read', k: 'fix', title: "Jason's Story (3)", img: G('sailboat'), paras: ['On vacation, I will rent a sailboat and sail to a tropical island. My life will be exciting, and I will have a comfortable home. But I won\'t spend all my money. I will save some of it in the bank.'], gloss: [['rent', '빌리다'], ['save', '저축하다'], ['comfortable', '편안한']], src: "14쪽 Jason's Story", nt: '읽기 — Jason ③', n: ['<del>Rent 임대</del> · <del>save 저장하기</del> → 이 쪽의 뜻'] },
      { t: 'order', k: 'new', img: '12693', words: ['I will', 'some of', 'my money', 'save', 'in the bank.'], nt: '문장 순서 게임', n: ['답: I will save some of my money in the bank.'] },
      { t: 'read', k: 'fix', title: "Naomi's Story (1)", img: '18249', paras: ['Money is important to everyone. We need money to afford a comfortable house, food, and good schools. But I don\'t need to be very rich.', 'A businessperson or a CEO works all the time, doing boring and difficult work. I don\'t want that life.'], gloss: [['afford', '(돈이 있어서) ~을 살 수 있다']], src: "15쪽 Naomi's Story", nt: '읽기 — Naomi ①', n: ['<del>businessman or CEO</del> → businessperson or CEO', '<del>ail</del> → all'] },
      { t: 'read', k: 'fix', title: "Naomi's Story (2)", img: '18037', paras: ['I want an enjoyable and rewarding job. I want to be an artist, a writer, or a teacher. I could be creative or help people learn. I can take the subway instead of driving a nice car. For me, a rewarding job is the most important thing.'], gloss: [['rewarding', '보람 있는'], ['creative', '창의적인'], ['instead of', '~대신에']], src: "16쪽 Naomi's Story", nt: '읽기 — Naomi ②', n: ['<del>Job</del> → job(대문자 3곳)'] },
      { t: 'discuss', k: 'keep', title: 'DISCUSSION', img: '15822', qs: ['What does Jason want? What does Naomi want?', 'Who do you agree with? Why?', 'Is it better to be rich or to be happy?', 'Can money buy happiness?'], chips: ['I agree with …', 'I think …'], src: '17쪽 DISCUSSION', nt: '토론', n: DISC.concat(['원본 질문 6개 중 넷 — 나머지 둘은 복습 과에서']) },
      { t: 'story', k: 'new', small: 'Story', title: 'Yoona and Jay: New sneakers', img: G('sneakers'), lines: [['Jay', 'Look! I bought these sneakers for 100 dollars!'], ['Yoona', 'Wow, they\'re shiny! Oh no… one shoe is broken!'], ['Mango', 'The same shoes are 30 dollars at the market.'], ['Jay', 'Oh no! I got ripped off! 😭'], ['Yoona', 'Next time, look for a bargain!']], nt: '이어지는 이야기 ②', n: ['이 과 낱말(ripped off · bargain)이 이야기 속에서', '«How did Jay feel?» 로 이어 묻기'] },
      { t: 'guess', k: 'new', img: '14639', open: [2, 7], q: 'What is it?', chips: ['a sailboat', 'a sports car', 'a bike'], nt: 'Guess it 타일', n: ['맞히면: «It is very expensive. Would you buy it?»'] },
      { t: 'yourturn', k: 'fix', img: '15822', title: 'One million dollars!', lines: ['Pretend that you have one million dollars!', 'First, I would buy ___.', 'I would save ___ in the bank.'], chips: ['a house', 'a car', 'a laptop', 'a new phone'], src: '18·19쪽 Try it', nt: '내 말로', n: ['<del>1M dollars</del> → one million dollars', '원본 그림(휴대폰·노트북·집·차·자전거·옷) 중 넷을 칩으로 — 자전거·옷은 강사가 말로 더하기'] },
      { t: 'song', k: 'new', title: 'Spend or Save? (chant)', lines: ['Coins in my pocket, what will I do?', 'Spend a little, save some, too!', 'A bargain makes me very glad.', 'Ripped off? Oh no, that\'s bad!'], img: '12693', src: '21쪽 Closing Song', nt: '마치는 챈트', n: CHANT('원본 돈 노래', 'glad → happy, bad → sad') },
      ...close([['I can talk about spending and saving money.', 'I spend my allowance on snacks.'], ['I can talk about bargains and being ripped off.', 'Half price is a bargain!'], ['I can give my opinion about money and happiness.', 'I think money can\'t buy happiness.']], { img: G('cover-friends'), q: 'How are your friends important to you?', ko: '친구는 왜 소중할까요? (다음 시간)' }),
    ] },
  // ───────────────────────── 007
  { code: '007', tab: '친구', unit: U3, title: 'Friends', orig: 18,
    intro: '친구 이야기 — 친구에게 무엇을 빌려줄 수 있는지(믿음), 누구에게 비밀을 말하는지, 곤란한 상황에서 어떻게 할지 말합니다. 읽기: 너그러운 Sue vs 조심스러운 Jim!',
    fixed: ['<del>secretive 비밀스런</del> → 비밀이 많은 · <del>institute 학회</del> → 학원', '<del>betrayed 배신</del> → 배신했다 · <del>excuses 변명</del> → 핑계(쉬운 말)', 'Jim 글 <del>He said they he would pay me back 3 days later.</del> → He said that he would pay me back three days later.', '«What do you do?» 상황 세 개를 한 쪽에 나란히'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-friends'), q: 'How are your friends important to you?', story: 'Two friends share one umbrella in the rain. Who would you share your umbrella with?', nt: '표지 + Big Question', n: ['빗속에서 우산 하나를 나눠 쓰며 뛰어가는 두 친구'] },
      ...open([['I can talk about my friends.', '내 친구들에 대해 말할 수 있어요.'], ['I can talk about trust, lending, and secrets.', '믿음·빌려주기·비밀에 대해 말할 수 있어요.'], ['I can say what I would do.', '어떤 상황에서 내가 어떻게 할지 말할 수 있어요.']], 'Lesson Goals (trust · lend · secretive)'),
      USONG_3,
      { t: 'discuss', k: 'keep', title: 'Warm up', img: '12021', qs: ['How are your friends important to you?', 'How many friends do you have?', 'Where did you meet them?'], chips: ['I have …', 'I met them at …'], src: '4·6쪽', nt: '생각 말하기' },
      { t: 'vocab', k: 'fix', hide: true, title: 'Friend words 🔒', cols: 3, words: [['trust', '믿다; 믿음', '18638'], ['lend', '빌려주다', G('lend-phone')], ['borrow', '빌리다', '19310'], ['secret', '비밀', '19630'], ['secretive', '비밀이 많은', G('secretive')], ['embarrassing', '창피한', G('embarrassing')]], src: '5쪽 Vocabulary', nt: '낱말 (가림→공개)', n: ['<del>secretive 비밀스런</del> → 비밀이 많은 · <del>부끄러운</del> → 창피한', 'borrow 는 원본 이야기 낱말 — lend 와 짝으로 앞당겼습니다'] },
      { t: 'rule', k: 'new', title: 'Lend or borrow?', left: { h: 'lend = give for a short time', ex: ['I **lend** my pen **to** Jay.', '(내가 빌려준다 ➡️)'] }, right: { h: 'borrow = take for a short time', ex: ['Jay **borrows** my pen.', '(Jay 가 빌린다 ⬅️)'] }, q: 'Who has the pen at the end? Who gets it back?', nt: '규칙 찾기 — lend / borrow', n: ['방향이 반대 — lend ➡️ 주는 쪽, borrow ⬅️ 받는 쪽', '이어서 «Can I borrow your eraser?» / «Sure, I can lend it to you.»'] },
      { t: 'discuss', k: 'keep', title: 'Keyword: Trust', img: '12391', qs: ['How many friends would you lend an eraser to? 10 dollars?', 'How many friends would you lend your phone to for a day?', 'How many friends would you talk to about family problems?'], chips: ['All of them', 'Only one or two', 'None'], src: '7쪽 Keyword Trust', nt: '생각 말하기 — 믿음 사다리', n: ['원본 목록 «1. Lend an eraser? …» 를 완전한 질문으로', '아래로 갈수록 숫자가 줄어드는지 — «Why?» 로 믿음 이야기'] },
      { t: 'discuss', k: 'keep', title: 'How secretive are you?', img: '19630', qs: ['Who do you tell secrets to?', 'Does your best friend know all of your secrets?', 'If you make a new friend, how long does it take you to tell them secrets?'], chips: ['I tell …', 'It takes about …'], src: '8쪽 Keyword Secretive', nt: '생각 말하기 — 비밀', n: ['원본 안내 그대로: «You don\'t have to tell the teacher your secrets!» — 비밀 내용은 말하지 않습니다'] },
      { t: 'read', k: 'fix', title: "Sue's Story", img: '18131', paras: ['I am friendly and outgoing. I have many friends from school and from my institutes. I think friends should be generous. I let my friends borrow my pens and books, and sometimes money for snacks.', 'Once, I lent my phone to a close friend. She was very grateful, and we became closer. I make friends by being generous.'], gloss: [['outgoing', '외향적인'], ['institute', '학원'], ['grateful', '고마워하는']], src: "10쪽 Sue's Story", nt: '읽기 — Sue', n: ['<del>institute 학회</del> → 학원', '«How does Sue make friends?» → By being generous.'] },
      { t: 'read', k: 'fix', title: "Jim's Story", img: '18618', paras: ['I trust my friends, but I am careful with new friends. In fourth grade, a new boy joined my soccer team. He borrowed 500 dollars from me. He said that he would pay me back three days later.', 'But he didn\'t pay me back. He only made excuses. He betrayed my trust. Now I am careful.'], gloss: [['excuses', '핑계'], ['betrayed', '배신했다']], src: "11쪽 Jim's Story", nt: '읽기 — Jim', n: ['<del>He said they he would pay me back 3 days later.</del> → that · three', '500 dollars 는 원본 그대로(사람이 정할 것 4번)'] },
      { t: 'ox', k: 'new', img: G('excuses'), s: "Jim's new friend paid him back three days later.", nt: '⭕❌', n: ['정답 ❌ → «No! He didn\'t pay him back. He made excuses.»'] },
      { t: 'discuss', k: 'keep', title: 'DISCUSSION', img: '12259', qs: ['What does Sue think about friends? What about Jim?', 'Who do you agree with, Sue or Jim? Why?', 'Would you lend money to a new friend?'], chips: ['I agree with …'], src: '12쪽 DISCUSSION', nt: '토론', n: DISC },
      { t: 'discuss', k: 'fix', title: 'What would you do?', img: '16401', qs: ['A new girl wants to borrow one of your two new pens.', 'Your best friend tells you an embarrassing secret about another friend.', 'Your friend still hasn\'t paid back the 100 dollars you lent him.'], chips: ['I would …'], src: '13~15쪽 What do you do?', nt: '상황 토론', n: ['원본 세 쪽을 한 쪽에 — 상황 설명은 짧게 줄였고 원본 세부(«내일 그 친구를 만난다» · «지난주에 빌려줬다»)는 강사가 말로 덧붙입니다', '«What do you do?» → «What would you do?»(가정 상황)'] },
      { t: 'guess', k: 'new', img: '17231', open: [0, 5], q: 'Who are they?', chips: ['best friends', 'strangers', 'teammates'], nt: 'Guess who 타일', n: ['맞히면: «They are best friends. They trust each other.»'] },
      { t: 'story', k: 'new', small: 'Story', title: 'Yoona and Jay: Can I borrow…?', img: '16401', lines: [['Jay', 'Yoona, can I borrow your pen?'], ['Yoona', 'Sure! I can lend it to you. But please give it back.'], ['Mango', 'Can I borrow your cookies?'], ['Yoona', 'No, Mango! You never give cookies back! 😂']], nt: '이어지는 이야기 ③', n: ['lend / borrow 를 이야기 속에서 — 쿠키는 «빌려» 줄 수 없다는 농담'] },
      { t: 'yourturn', k: 'new', img: G('cover-friends'), title: 'My best friend', lines: ['My best friend is ___.', 'We met at ___.', 'I trust him/her because ___.', 'I would lend him/her my ___.'], chips: ['school', 'my institute', 'honest', 'kind'], nt: '내 말로' },
      ...close([['I can talk about my friends.', 'I met my best friend at school.'], ['I can talk about trust, lending, and secrets.', 'I would lend my phone to my best friend.'], ['I can say what I would do.', 'I would tell her the truth.']], { img: G('cover-lying'), q: 'Are you an honest person?', ko: '나는 정직한 사람일까요? (다음 시간)' }),
    ] },
  // ───────────────────────── 010
  { code: '010', tab: '거짓말', unit: U4, title: 'Lying', orig: 19,
    intro: '정직과 거짓말 — «Have you ever …?» 로 경험을 묻고, 소문과 선의의 거짓말(white lie)에 대해 토론합니다. 읽기: 시험 때 거짓말로 더 혼난 Claire vs 할머니를 위한 거짓말을 한 Ryan!',
    fixed: ['<del>Lying 거짓말</del> → 거짓말하기 · 중복된 honest 한 칸 정리', '<del>cheated 속이는</del> → 부정행위를 했다 · <del>crossed 교차</del> → (길을) 건넜다 · <del>spread 퍼지다</del> → 퍼뜨리다', '<del>destroy 멸하다</del> → 망가뜨리다 · <del>damage 손해</del> → 해치다 · <del>suspicious</del> → 의심하는', 'Claire 글 <del>When I was in fourth grade. I was sitting…</del> → 한 문장으로', 'Ryan 글 <del>It\'s yummy grandma.</del> → "It\'s yummy, Grandma."', '<del>word-of mouth</del> → word of mouth · <del>more change then you thought</del> → than', '민감한 질문(빨간불·소문 피해)은 «답하지 않아도 돼요» 강사 메모'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-lying'), q: 'Is telling the truth always the easiest thing?', story: 'The cookie jar is broken. Crumbs are on the dog\'s nose. Who did it?', nt: '표지 + Big Question', n: ['깨진 쿠키 단지 옆에서 입가에 부스러기를 묻힌 강아지가 딴청 — «Who is lying?»'] },
      ...open([['I can talk about honesty and lies.', '정직과 거짓말에 대해 말할 수 있어요.'], ['I can ask «Have you ever …?»', '«~해 본 적 있어요?» 를 묻고 답할 수 있어요.'], ['I can say what I would do in a hard situation.', '곤란한 상황에서 내가 어떻게 할지 말할 수 있어요.']], 'Lesson Goals (Wh- · Yes/No · Would you …?)'),
      USONG_4,
      { t: 'discuss', k: 'keep', title: 'Warm up', img: '14956', qs: ['Are you an honest person?', 'Is telling the truth always the easiest thing?', 'Why do you think people tell lies?'], chips: ['I think …', 'People lie because …'], src: '4쪽 Warm up', nt: '생각 말하기' },
      { t: 'vocab', k: 'fix', hide: true, title: 'Honesty words 🔒', cols: 4, words: [['lie', '거짓말(하다)', '15805'], ['honest', '정직한', '18467'], ['dishonest', '정직하지 않은', G('cheat')], ['cheat', '부정행위를 하다', G('cheat')], ['cross the street', '길을 건너다', '17170'], ['spread', '퍼뜨리다', G('rumor')], ['rumor', '소문', G('rumor')], ['victim', '피해자', '14326']], src: '5쪽 Vocabulary', nt: '낱말 (가림→공개)', n: ['<del>Lying 거짓말</del> → lie · <del>cheated 속이는</del> · <del>crossed 교차</del> · <del>spread 퍼지다</del> · <del>희생자</del> → 피해자', '같은 사진을 두 칸이 나눠 씁니다(dishonest·cheat / spread·rumor) — 짝 낱말'] },
      { t: 'discuss', k: 'keep', title: 'Keyword: Lie', img: '15805', qs: ['Can you remember a lie that you told? What was it?', 'Has someone ever called you a liar? What did you do?', 'Who have you lied to before? Did you feel bad after you lied?'], chips: ['I once told …', 'I felt …'], src: '6·7쪽 Keyword Lie', nt: '생각 말하기 — 거짓말', n: ['자기 이야기가 부담스러우면 «someone I know» 로 바꿔 말해도 됩니다'] },
      { t: 'rule', k: 'fix', title: 'Honest or dishonest?', left: { h: 'Honest people 😇', ex: ['always tell the truth.', 'You can **trust** them.'] }, right: { h: 'Dishonest people 😈', ex: ['may **lie**, **cheat**,', 'and **break** promises.'] }, q: 'Who makes a better friend? Why?', src: '8쪽 Honest / Dishonest', nt: '규칙 찾기 — 두 사람 비교', n: ['원본 설명 두 문장을 두 칸으로'] },
      { t: 'table', k: 'fix', small: 'Have you ever…?', title: 'Have you ever…?', head: ['Have you ever…?', 'Answer'], rows: [['cheated at a game?', 'Yes, I have.'], ['crossed the street on a red light?', 'No, I haven\'t.'], ['lied to your mom?', 'Yes, I have.'], ['broken a promise to a friend?', 'No, I haven\'t.']], src: '8쪽 Have you ever…', nt: '경험 묻기', n: ['<del>crossing light</del> → light(쉬운 말)', '⚠️ 답하고 싶지 않은 학생은 넘어가도 됩니다(사람이 정할 것 5번)', 'Yes 면 «What happened?» 로 한 번 더', 'Have you ever + 과거분사(cheated · crossed · lied · broken) — 표의 답은 예시'] },
      { t: 'read', k: 'fix', title: 'Keyword: Rumor', img: '18076', paras: ['Rumors are false stories about other people. Rumors can spread quickly by word of mouth, or even over the Internet or through text messages. Rumors can be very harmful to people.', 'Have you ever helped spread a rumor about someone? Have you ever been the victim of a rumor?'], gloss: [['false', '사실이 아닌'], ['word of mouth', '입소문'], ['harmful', '해로운']], src: '9쪽 Keyword Rumor', nt: '읽기 + 질문', n: ['<del>word-of mouth</del> → word of mouth', '⚠️ 두 번째 질문은 답하지 않아도 됩니다'] },
      { t: 'read', k: 'fix', title: "Claire's Story (1)", img: '16682', paras: ['I think honesty is the most important trait. When I was in fourth grade, I was sitting next to my friend during a test. I copied her answers. When the teacher asked me, I lied.'], gloss: [['trait', '성격, 특성'], ['copied', '베꼈다']], src: "11쪽 Claire's Story", nt: '읽기 — Claire ①', n: ['<del>When I was in fourth grade. I was sitting…</del> → 한 문장으로'] },
      { t: 'read', k: 'fix', title: "Claire's Story (2)", img: G('teacher-suspicious'), paras: ['The teacher was suspicious because we had the same wrong answer. She called my mom. I was in more trouble for lying, and my friend was in trouble, too.', 'Not being honest was a huge mistake. In the future, I will always be honest.'], gloss: [['suspicious', '의심하는'], ['huge', '아주 큰']], src: "11·12쪽 Claire's Story", nt: '읽기 — Claire ②', n: ['<del>I know that I will always need to be honest</del> → I will always be honest(뜻 그대로 짧게)', '«Why was Claire in more trouble?» → Because she lied.'] },
      { t: 'read', k: 'fix', title: "Ryan's Story (1)", img: '17164', paras: ['Lying is usually bad. It can damage or destroy friendships. But I think white lies are sometimes OK.', 'Last year, I visited my grandma in the countryside. She made a traditional dinner for me, but it was overcooked. It was disgusting!'], gloss: [['damage', '해치다'], ['destroy', '망가뜨리다'], ['white lies', '선의의 거짓말'], ['disgusting', '역겨운, 너무 맛없는']], src: "13쪽 Ryan's Story", nt: '읽기 — Ryan ①', n: ['<del>damage 손해</del> · <del>destroy 멸하다</del> → 동사 뜻으로'] },
      { t: 'read', k: 'fix', title: "Ryan's Story (2)", img: G('grandma-dinner'), paras: ['But I said, "It\'s yummy, Grandma." She smiled. I don\'t always tell the truth if it hurts someone\'s feelings.'], gloss: [['hurts someone\'s feelings', '마음을 아프게 하다']], src: "14쪽 Ryan's Story", nt: '읽기 — Ryan ②', n: ['<del>It\'s yummy grandma.</del> → "It\'s yummy, Grandma."(쉼표·대문자)'] },
      { t: 'ox', k: 'new', img: G('grandma-dinner'), s: "Ryan told his grandma that the dinner was disgusting.", nt: '⭕❌', n: ['정답 ❌ → «No! He said, "It\'s yummy, Grandma." It was a white lie.»'] },
      { t: 'discuss', k: 'keep', title: 'DISCUSSION', img: '16124', qs: ['Why was Claire\'s lie a huge mistake?', 'Why did Ryan tell a white lie?', 'Are white lies OK? Why or why not?', 'Who do you agree with, Claire or Ryan?'], chips: ['I agree with …', 'White lies are …'], src: '15쪽 DISCUSSION', nt: '토론', n: DISC },
      { t: 'discuss', k: 'fix', title: 'What would you do?', img: G('dress'), qs: ['Your mom wants to wear an old, out-of-fashion dress to a dinner date. She asks you, "How do I look?"', 'Your friend copied your homework. He asks you to lie to the teacher for him.'], chips: ['I would say …', 'I would tell the truth.'], src: '16·17쪽 What do you do?', nt: '상황 토론 ①', n: ['원본 긴 설명을 두 문장씩으로 줄였습니다', '«Would you tell a white lie?» 로 이어 묻기'] },
      { t: 'yourturn', k: 'fix', img: G('change'), title: 'Too much change!', lines: ['You buy something for 10 dollars at a stationery store.', 'You pay, but the clerk gives you more change than you thought.', 'I would ___ because ___.'], chips: ['give it back', 'keep it', 'tell the clerk'], src: '18쪽 What do you do?', nt: '상황 토론 ② — 내 말로', n: ['<del>more change then you thought</del> → than', '<del>expensive-</del> 끊긴 문장 정리'] },
      { t: 'guess', k: 'new', img: '18826', open: [3, 6], q: 'Who broke the cookie jar?', chips: ['the dog', 'the cat', 'Mango'], nt: 'Guess who 타일', n: ['원본 마치는 노래(쿠키 단지) 대신 — 맞히면 «Was it you? Tell the truth!»'] },
      { t: 'story', k: 'new', small: 'Story', title: 'Yoona and Jay: My new haircut', img: G('haircut'), lines: [['Yoona', 'Jay, look at my new haircut! Do you like it?'], ['Jay', 'Um… it\'s… great!'], ['Mango', 'Jay, is that a white lie? 🤔'], ['Jay', 'Well… it\'s short, but you look happy!'], ['Yoona', 'Ha ha! Thanks for being honest!']], nt: '이어지는 이야기 ④', n: ['선의의 거짓말 vs 정직하면서 친절하게 — «What would you say?»'] },
      ...close([['I can talk about honesty and lies.', 'Honest people always tell the truth.'], ['I can ask «Have you ever …?»', 'Have you ever lied to your mom? — No, I haven\'t.'], ['I can say what I would do in a hard situation.', 'I would give the change back.']], { img: G('cover-review'), q: 'Who is your best friend? Why?', ko: '가장 친한 친구는 누구? 왜? (다음 시간 — 복습)' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: RV, title: 'BTS 29 Review', orig: 22,
    intro: '네 과 복습 — 영웅 → 돈 → 친구 → 거짓말. 과마다 낱말을 가려 떠올리고, 핵심 토론 질문을 다시 묻고, 게임으로 마무리합니다.',
    fixed: ['<del>Lend you cell phone</del> → Lend your cell phone', '<del>inspired with</del> → inspired by', '원본 복습 20쪽(각 과 토론 쪽 반복)을 과마다 «낱말 → 토론 → 게임» 세 쪽으로 묶음'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-review'), q: 'Who is your best friend? Talk about him or her.', story: 'Heroes, money, friends, and honesty — let\'s look back at BTS 29!', nt: '표지 + Big Question', n: ['원본 Warm Up 질문 그대로 — 두 친구가 어깨동무한 장면'] },
      ...open([['I can talk about heroes and role models.', '영웅과 롤모델에 대해 말할 수 있어요.'], ['I can talk about money and friends.', '돈과 친구에 대해 말할 수 있어요.'], ['I can talk about honesty.', '정직에 대해 말할 수 있어요.']], 'Review Goals'),
      { t: 'discuss', k: 'keep', title: 'Warm up', img: '18463', qs: ['Who is your best friend?', 'Where did you meet?', 'What do you like about him or her?'], chips: ['My best friend is …', 'He/She is …'], src: '4쪽 Warm Up', nt: '생각 말하기' },
      { t: 'vocab', k: 'keep', small: 'Stage 1', hide: true, title: 'Heroes 🔒', cols: 4, words: [['admire', '존경하다', '12761'], ['respect', '존경하다', 'c7032'], ['inspire', '영감을 주다', '15490'], ['role model', '본받고 싶은 사람', '18538'], ['generous', '너그러운', '12391'], ['trustworthy', '믿을 수 있는', '17166'], ['hardworking', '열심히 일하는', '12149'], ['humble', '겸손한', '14725']], nt: '001 낱말 다시', n: ['가린 채 사진만 보고 말하기 → 공개'] },
      { t: 'discuss', k: 'fix', small: 'Stage 1', title: 'Heroes', img: '12284', qs: ['What kinds of people do you admire?', 'Do you admire anyone in your family? Why?', 'Are you inspired by your friends? Why or why not?'], chips: ['I admire …', 'because …'], src: '5~8쪽', nt: '001 토론 다시', n: ['<del>inspired with</del> → inspired by'] },
      { t: 'guess', k: 'new', small: 'Stage 1', img: '13394', open: [1, 4], q: 'Whose hero plays this sport?', chips: ["Jack's", "Sunny's", "Jason's"], nt: 'Guess 타일', n: ['답: Jack\'s (Tiger Woods — 골프)'] },
      { t: 'vocab', k: 'keep', small: 'Stage 2', hide: true, title: 'Money 🔒', cols: 3, words: [['spend', '(돈을) 쓰다', '16004'], ['buy', '사다', '12883'], ['expensive', '비싼', '19336'], ['bargain', '싸게 잘 산 것', '12797'], ['save', '저축하다', '18138'], ['earn', '(돈을) 벌다', '18134']], nt: '004 낱말 다시' },
      { t: 'discuss', k: 'keep', small: 'Stage 2', title: 'Money', img: '18068', qs: ['What things do you buy every week?', 'What is the best bargain you have ever found?', 'Have you ever been ripped off? How did it feel?'], chips: ['I buy …', 'I got …'], src: '9~14쪽', nt: '004 토론 다시' },
      { t: 'ox', k: 'new', small: 'Stage 2', img: '18746', s: 'Naomi wants to be very rich.', nt: '⭕❌', n: ['정답 ❌ → «No! Jason wants to be rich. Naomi wants a rewarding job.»'] },
      { t: 'vocab', k: 'keep', small: 'Stage 3', hide: true, title: 'Friends 🔒', cols: 3, words: [['friends', '친구들', '12007'], ['trust', '믿다', '18638'], ['lend', '빌려주다', '16401'], ['borrow', '빌리다', '14828'], ['promise', '약속', '21047'], ['secret', '비밀', '19630']], nt: '007 낱말 다시' },
      { t: 'discuss', k: 'fix', small: 'Stage 3', title: 'Friends', img: '12021', qs: ['Where did you meet your friends?', 'Would you lend your cell phone to a friend for one day?', 'Who do you tell secrets to?'], chips: ['I met them at …', 'I would / wouldn\'t …'], src: '15~18쪽', nt: '007 토론 다시', n: ['<del>Lend you cell phone</del> → your'] },
      { t: 'match', k: 'new', small: 'Stage 3', title: 'Match it!', left: ['18131', G('excuses'), '18463', '19630'], right: ['best friends', 'a secret', 'Sue', 'Jim'], nt: '짝 맞추기', n: ['짝마다 한 문장: «Sue is generous.» / «Jim is careful.»'] },
      { t: 'vocab', k: 'keep', small: 'Stage 4', hide: true, title: 'Honesty 🔒', cols: 3, words: [['honest', '정직한', '19412'], ['lie', '거짓말(하다)', '15805'], ['cheat', '부정행위를 하다', G('cheat')], ['rumor', '소문', G('rumor')], ['white lie', '선의의 거짓말', G('grandma-dinner')], ['victim', '피해자', '14326']], nt: '010 낱말 다시' },
      { t: 'discuss', k: 'keep', small: 'Stage 4', title: 'Honesty', img: '14956', qs: ['Are you an honest person?', 'Have you ever broken a promise to a friend?', 'Are white lies OK? Why or why not?'], chips: ['Yes, I have. / No, I haven\'t.', 'I think …'], src: '19~21쪽', nt: '010 토론 다시' },
      { t: 'rule', k: 'new', small: 'Stage 4', title: 'Claire or Ryan?', left: { h: 'Claire 😢', ex: ['She **lied** to the teacher.', 'She was in **more trouble**.'] }, right: { h: 'Ryan 😊', ex: ['He told a **white lie**.', 'His grandma **smiled**.'] }, q: 'Which lie was worse? Why?', nt: '두 이야기 비교' },
      { t: 'memory', k: 'new', title: 'Memory game', items: ['13340', '12693', '18638', '18826', '15331', '16401'], q: 'Look for 10 seconds! Which pictures did you see?', a: 'I saw ___ and ___.', nt: '기억 게임', n: ['10초 보고 가리기 → 본 사진마다 그 과 문장 하나(«Thanks to Edison, we have light bulbs!»)'] },
      { t: 'story', k: 'new', small: 'Story', title: 'Yoona and Jay: Our hero', img: '12259', lines: [['Jay', 'Yoona, you are honest and generous.'], ['Yoona', 'Thanks! You are a trustworthy friend.'], ['Mango', 'And I am the cookie hero! 🍪'], ['Jay', 'No, Mango. The cookie thief! 😂']], nt: '이어지는 이야기 ⑤ (마지막)', n: ['네 과 낱말(generous · honest · trustworthy)이 한 장면에', '«Who is your hero in this class?» 로 마무리'] },
      { t: 'yourturn', k: 'new', img: G('cover-review'), title: 'My BTS 29 answers', lines: ['My hero is ___ because ___.', 'I think money ___ buy happiness.', 'I think white lies are ___.'], chips: ['can', 'can\'t', 'OK', 'not OK'], nt: '내 말로 — 네 과 한 문장씩' },
      { t: 'song', k: 'new', title: 'Tell the Truth (chant)', lines: ['Who broke the cookie jar? Was it you?', 'Tell the truth, and I\'ll trust you, too!', 'Honest friends are good to know.', 'Tell the truth wherever you go!'], img: '18826', src: '22쪽 Closing Song', nt: '마치는 챈트', n: CHANT('Who Took the Cookie (Tommy broke the cookie jar)', 'you → me, know → show') },
      ...close([['I can talk about heroes and role models.', 'My hero is my father. He is hardworking.'], ['I can talk about money and friends.', 'I would lend my pen to a new friend.'], ['I can talk about honesty.', 'Honest people always tell the truth.']], { img: G('next-abroad'), q: 'Would you like to live in another country?', ko: '다른 나라에서 살아 보고 싶나요? (BTS 30 — Living Abroad)' }),
    ] },
  ],
};
