// BTS 25 새 교재 설계 데이터 — 발명과 기술 · 삶을 편하게 · 생각과 아이디어 (Level 7)
// k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
import { open, close, HELLO } from '../common.mjs';

const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3';
const G = k => 'gen:bts-25-' + k;

// 과마다 반복되는 원본 문법 쪽(7~9쪽 Active and Passive Voice) — 표현을 바꿔 가며 짧게
const PASSIVE_RULE = (src) => ({ t: 'rule', k: 'fix', title: 'Who does it? What gets done?', left: { h: 'Active 🙋 (the doer first)', ex: ['Lisa **mails** a letter.', 'Lisa **mailed** a letter.'] }, right: { h: 'Passive 📦 (the thing first)', ex: ['A letter **is mailed** by Lisa.', 'A letter **was mailed** by Lisa.'] }, q: 'What two words make the passive? Where does "Lisa" go?', src, nt: '규칙 찾기 — 능동·수동', n: ['원본 7~9쪽의 Active/Passive 설명(용어·정의 문장)을 두 묶음 예문으로 줄였습니다 — 학생이 «be + 과거분사» 와 «by 사람» 을 먼저 찾게 합니다', '강사용: Active voice = 주어가 행동, Passive voice = 주어가 행동을 받음'] });
const PASSIVE_TABLE = (src) => ({ t: 'table', k: 'fix', small: 'Pattern', title: 'Active → Passive', head: ['time', 'active', 'passive'], rows: [['now', 'Lisa **mails** it.', 'It **is mailed**.'], ['now (-ing)', 'Lisa **is mailing** it.', 'It **is being mailed**.'], ['past', 'Lisa **mailed** it.', 'It **was mailed**.'], ['future', 'Lisa **will mail** it.', 'It **will be mailed**.']] , src, nt: '문장 틀 — 네 가지 때', n: ['원본 9쪽 표(Present·Continuous·Past·Future)를 그대로 두고 «by Lisa» 는 생략해 표를 한눈에', '한 줄씩 강사가 능동을 말하면 학생이 수동으로 바꿔 말하기'] });
const SUFFIX_RULE = (src) => ({ t: 'rule', k: 'fix', title: 'Same word, new job!', left: { h: 'Base word', ex: ['**forget** · **use**', '**persuade** · **create**'] }, right: { h: '+ suffix', ex: ['forget**ful** · use**ful**', 'persua**sion** · crea**tion**'] }, q: 'What happens to the word when we add -ful or -ion?', src, nt: '규칙 찾기 — 접미사', n: ['원본 Suffix 설명 쪽(오타 <del>FUNTION</del>)을 두 묶음 예문으로 — 학생이 «뒤에 붙이면 낱말의 역할이 바뀐다» 를 먼저 말하게', '강사용: -ful = 형용사, -ion/-sion/-tion = 명사'] });
const SUFFIX_TABLE = (src) => ({ t: 'table', k: 'keep', small: 'Pattern', title: 'create → creative → creativity', head: ['job', 'word', 'sentence'], rows: [['describing word', 'creative', 'She is a very **creative** artist.'], ['action word', 'create', 'I tried to **create** a new design.'], ['thing word', 'creativity', 'He showed his **creativity** in painting.']], tip: '같은 뿌리 낱말도 문장 속 자리에 따라 모양이 바뀌어요', src, nt: '문장 틀 — 한 뿌리 세 모양', n: ['원본 예문 세 줄 그대로 · <del>That man has shown</del> → He showed(짧게)'] });
const IF_RULE = (src) => ({ t: 'rule', k: 'new', title: 'Real or imagined?', left: { h: 'Real 🌞', ex: ['I **have** a stapler, so I **can** staple my papers.'] }, right: { h: 'Imagined 💭', ex: ["If I **didn't have** a stapler, I **would** use tape.", 'If I **had** a robot, it **would** do my homework.'] }, q: 'In the imagined sentence, what comes after "If"? What comes before the verb?', src, nt: '규칙 찾기 — 가정법', n: ['원본 목표의 «Subjunctive mood» 를 이 권 이야기(006 스테이플러 · 003 지나의 스마트폰) 문장으로 보여 줍니다', 'If + 과거형 → would + 동사원형. 용어는 강사 메모로만'] });
const CHANT = (src) => ({ t: 'song', k: 'fix', title: 'Inventors Chant', lines: ['Who made the light? Who made it bright?', 'Somebody thought, and it turned out right!', 'Wheels and wings and a phone to call —', 'Ideas are the best inventions of all!'], img: '18028', src, nt: '마무리 챈트', n: ['원본 노래: Inventors and Inventions — 가사 저작권 문제로 자체 챈트로 바꿨습니다', '손뼉 4박에 맞춰 두 번: 한 번은 강사와, 한 번은 학생 혼자'] });

export const COURSE = {
  head: `<h1>BTS 25 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트에 올라가 있는 BTS 25 원본 <b>248쪽</b>(11묶음, Level 7)을 읽고, BTS 1 과 같은 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · 과 끝 «I can» · 다음 시간 예고)으로 다시 짰습니다. 이 권의 주제는 <b>발명과 기술</b>입니다 — 소통 기술(편지→스마트폰) → 삶을 편하게 하는 발명(자동·효율) → 생각이 큰 사람들(창의·직관·설득·열정). 문법은 원본 그대로 <b>능동태·수동태</b>, <b>가정법(If I didn't have…, I would…)</b>, <b>접미사(-ful, -ion)</b>.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>배우는 <b>낱말·문장·문법 범위는 원본 그대로</b>입니다. 원본 역할놀이 인물(Michael·Zander / Nate·Carmel / Junry·Roel)과 읽기 인물(Gina · Ella)을 그대로 살리고, 복습·시험에서 다시 등장시켰습니다. 원본 7~9쪽 능동·수동 문법 쪽은 과마다 같은 내용이 반복돼 있어, 규칙 찾기 → 표 → 바꿔 말하기로 과마다 한 단계씩 나눠 실었습니다.</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>, <b>⭕❌</b>, <b>Guess who / Guess what 타일</b>, <b>기억·순서·짝짓기·글자 조각 게임</b>, <b>내 말로(Your turn)</b>, <b>I can ✅</b>, <b>다음 시간 예고</b>. 원본의 짧은 읽기(지나·Simple Inventions·엘라)는 <b>read</b> 쪽 + 낱말 뜻(gloss)으로 옮겼습니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>점선 상자(«새 사진 생성 중»)는 맞는 사진이 없어 새로 만드는 자리입니다(이 권 40장 요청). 실존 인물(피카소·모차르트·롤링·호킹·스탠 리·저커버그·빌 게이츠 등)은 <b>얼굴 사진을 쓰지 않고</b> 그 사람의 일(그림·피아노·책·우주·만화 영웅·컴퓨터)을 보여 주는 사진 + 글자 단서로 «Guess who» 를 합니다. 원본의 «지도를 보며 운전하는 손» 사진은 운전 중 휴대폰 사용이라 쓰지 않았습니다.</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>고친 뜻 승인</b> — 원본 한국어 뜻이 문맥과 다른 곳: obsolete «오래된»→구식의, feature «특색»→기능, application «신청»→앱, advanced «향상된»→첨단의, staple «스테이플»→스테이플러로 찍다, tape «줄자»→테이프, hold together «함께 잡다»→한데 붙어 있다, properly «적합하게»→올바르게, prodigy «비범»→신동, area «지역»→분야, athlete «육상경기선수»→운동선수, set of standards «표준세트»→정해진 기준, professional «직업적인»→프로의, compose «짓다»→작곡하다, essay «수필»→글, introduction «소개»→서론.</li>
<li><b>사실 확인이 필요한 원본 문장</b> — ① 002 «Ancient Chinese and Koreans … printing press almost 2000 years ago»(목판 인쇄는 약 1,300년 전, 금속활자는 고려 13세기) → 시안은 «long before Gutenberg» 로 바꿨습니다. ② 008 «Bill Gates — Richest man in the world»(지금은 사실이 아님) → «one of the richest people» 로. ③ 008 «Larry Page and Sergey Brin never finished university»(둘 다 학사는 마쳤고 대학원을 그만둠) → «left their studies at Stanford» 로. ④ 007 스티븐 호킹 쪽이 현재형(I study… I have…)인데 2018년에 세상을 떠났습니다 → 과거형으로.</li>
<li><b>인용 표기</b> — 006 «Technology is a useful servant, but a dangerous master» 의 출처 표기 <del>Christian Louis Lange</del> → Christian Lous Lange(노벨평화상 수상자 이름 철자). 007 피카소 인용 <del>artiste</del> → artists.</li>
<li><b>실존 인물 사진</b> — 원본은 유명인 얼굴 사진을 썼습니다. 시안은 얼굴 없이 «한 일» 사진으로 바꿨습니다. 원본 사진을 계속 쓸지(초상권·사용권) 결정이 필요합니다.</li>
<li><b>마무리 노래</b> — 원본 «Inventors and Inventions»(라이트 형제·에디슨·벤츠·베어드·풀턴) 가사는 옮기지 않고 자체 챈트로 바꿨습니다. 원곡을 쓸지 저작권 확인이 필요합니다.</li>
<li><b>007 역할놀이 «professor»</b> — 초등·중등 학생 대상이라 our teacher 로 바꿨습니다. 원본을 살릴지.</li>
<li><b>REVIEW·TEST 쪽 수</b> — 원본 REVIEW 는 앞 과 쪽을 그대로 다시 실은 것이라, 시안은 같은 내용을 새 사진·게임으로 바꿔 복습합니다.</li>
<li><b>새로 만들 사진 40장</b> — 점선 자리(힉스필드 크레딧). 특히 삐삐·전신기·벨크로·온도조절기·우물·교정테이프처럼 사이트 사진에 없는 옛 물건.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '소통 기술', unit: U1, title: 'Ways to Communicate', orig: 25,
    intro: '편지에서 스마트폰까지, 사람들이 서로 소통해 온 방법을 봅니다. 새 문법은 능동·수동(Active/Passive). 이야기: 마이클이 새 스마트폰을 자랑하는데 잰더는 아직 모르겠다고 합니다.',
    fixed: ['<del>obsolete 오래된</del> → 구식의', '<del>It has a camera and you send text messages</del> → you can send (앞뒤 문장과 같은 can 으로)', '<del>What features of this device was mentioned?</del> → What features were mentioned?', '빈칸 정답(stamp · face to face · hang · Finding time)이 같은 쪽 아래에 적혀 있던 것 → 칩으로 섞어 보여 주기', 'Discovery Zone 5쪽(공중전화·귓속말·삐삐·화상회의·마임) → 사진 타일 + 질문 한 쪽씩으로 정리'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-001'), q: 'How do people talk to each other?', story: 'Michael has a new phone. Zander is not so sure…', nt: '표지 + Big Question', n: ['«사람은 몇 가지 방법으로 서로 말을 주고받을까?» 로 엽니다 — 끝에 학생이 가장 좋아하는 방법을 이유와 함께 말하는 것이 목표', '표지 속 종이컵 전화로 «이것도 발명일까?» 를 먼저 묻습니다'] },
      ...open([['I can talk about ways to communicate.', '소통하는 여러 방법을 말할 수 있어요.'], ['I can change a sentence into the passive.', '문장을 수동태로 바꿔 말할 수 있어요 — The letter was written by me.'], ['I can say how I hang out with my friends.', '친구들과 어떻게 노는지 말할 수 있어요.']], 'Lesson Goals (Computer technology · Communication · Active/Passive)'),
      { t: 'qa', k: 'keep', img: 'c7421', small: 'Warm up', title: 'One useful invention', q: 'Think of one useful invention. How does it help you?', a: 'The ___ helps me ___.', chips: ['phone', 'bike', 'fridge'], src: '5쪽 Warm Up', nt: '몸풀기', n: ['원본 질문 그대로 · 답 틀을 붙였습니다', '두 개 이상 말하면 칭찬 — «It helps me» 뒤에 동사원형'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Technology words 🔒', cols: 4, words: [['technology', '과학기술', '12356'], ['social media', '소셜 미디어', '19453'], ['the internet', '인터넷', '19273'], ['communication satellite', '통신위성', G('satellite')], ['communicate', '소통하다', '16862'], ['face to face', '얼굴을 마주 보고', '12308'], ['simplify', '더 간단하게 하다', '12261'], ['obsolete', '구식의', '15596']], src: '6쪽 Vocabulary', nt: '낱말 — 뜻 가리고', n: ['뜻을 가린 채 사진만 보고 먼저 말하게 한 뒤 공개', '<del>obsolete 오래된</del> → 구식의(쓰지 않게 된)', '원본의 communication · social networking sites · accomplish(해내다) 는 강사가 예문으로: «Phones help us accomplish many things.» (social networking sites 는 003 읽기에서 다시)'] },
      { t: 'vocab', k: 'fix', title: 'Useful expressions', cols: 3, words: [['take it with me', '가지고 다니다', '12261'], ['hang out', '같이 놀다', '19453'], ['find time', '시간을 내다', '16862']], src: '6쪽 Idioms', nt: '표현 세 개', n: ['원본 «take (something) with me / hang out / finding time» — 문장 속에서 쓰는 모양으로', '각각 «I take my phone with me.» 처럼 한 문장씩'] },
      PASSIVE_RULE('7·8쪽 Grammar'),
      { t: 'fill', k: 'fix', img: '18419', title: 'Old but still used?', lines: ["I don't need much technology. Just a pen, paper, an envelope and a ___.", 'She ___ letters to her family and friends.', 'Do people still write letters nowadays?'], chips: ['stamp', 'writes', 'phone'], src: '10쪽', nt: '빈칸 — 편지', n: ['원본은 정답이 같은 쪽 아래에 보임 → 칩으로(함정 phone 포함)', '마지막 질문은 학생 의견으로'] },
      { t: 'fill', k: 'fix', img: '12021', title: 'Face to face', lines: ['They like to communicate ___.', 'They like to ___ out together.', '___ time to meet up with friends is not easy!'], chips: ['face to face', 'hang', 'Finding'], src: '11쪽', nt: '빈칸 — 친구 만나기', n: ['끝에 «How do you hang out with your friends?» 를 물어 내 말로'] },
      { t: 'guess', k: 'new', img: G('phone-booth'), open: [0, 4], q: 'What is it? Who uses it in the movies?', chips: ['a phone booth', 'a mailbox', 'an elevator'], src: '12쪽 Discovery Zone', nt: 'Guess what — 공중전화', n: ['타일을 열 때마다 «Is it a …?» 로 묻기', '정답 phone booth — 원본 «슈퍼히어로가 옷을 갈아입는 곳» 농담을 살렸습니다'] },
      { t: 'match', k: 'fix', title: 'Discovery Zone', left: ['19630', G('pager'), '12042', G('mime')], right: ['miming', 'a video conference', 'whispering', 'a pager'], src: '13~16쪽 Discovery Zone', nt: '짝짓기 — 네 가지 방법', n: ['원본 4쪽(귓속말·삐삐·화상회의·마임)을 한 쪽 짝짓기로', '짝을 맞출 때마다 원본 질문 하나씩: «How do you use it?» «Have you tried this?»'] },
      { t: 'qa', k: 'keep', img: G('mime'), title: 'Can you understand this?', q: 'She is miming. What is she saying?', a: 'I think she is saying ___.', chips: ['I am hungry.', 'Call me!', "It's cold."], src: '16쪽', nt: '마임 놀이', n: ['강사가 직접 마임을 하고 학생이 맞힌 뒤, 학생 차례', '말없이도 소통할 수 있다는 것을 몸으로 느끼게'] },
      { t: 'vocab', k: 'keep', title: 'Role-play words', cols: 4, words: [['features', '기능들', '14366'], ['outdated', '구식의', 'c7501'], ['download', '내려받다', 'c7465'], ['device', '기기', '16087']], src: '17쪽', nt: '역할놀이 낱말' },
      { t: 'story', k: 'fix', small: 'Story ①', title: "Michael's new phone", img: 'c7472', lines: [['Michael', 'Hey, Zander. Look! I have a new smartphone!'], ['Zander', "That's nice! What features does it have?"], ['Michael', 'It has tons of features!'], ['Zander', 'Like? Can you call people with it, like my telephone at home?'], ['Michael', 'Of course! Your telephone is outdated.']], src: '18쪽 Role-play', nt: '이야기 ① 역할놀이', n: ['강사가 Michael, 학생이 Zander → 두 번째는 바꿔서', '<del>with that like my telephone</del> → with it, like my telephone(쉼표)'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: "Michael's new phone", img: G('michael-zander'), lines: [['Michael', 'It has a camera, and you can send text messages.'], ['Michael', "You can download games, too. It's like a portable computer!"], ['Zander', "I still don't get it. I'll just buy one tomorrow."], ['Michael', "Better bring a lot of money. It's expensive!"]], src: '18·19쪽 Role-play', nt: '이야기 ②', n: ['<del>you send text messages</del> → you can send', '마지막 대사는 크게 과장해서 — 웃음 포인트'] },
      { t: 'ox', k: 'new', img: '13330', s: 'Zander thinks his telephone at home is outdated.', nt: '⭕❌ 이야기 확인', n: ['정답 ❌ → «No! Michael says Zander\'s telephone is outdated.» 까지'] },
      { t: 'discuss', k: 'fix', img: '19085', title: 'Talk about the story', qs: ['What device did Michael show Zander?', 'What features were mentioned?', 'Why will Zander buy a smartphone?', 'What good features does your smartphone have?'], chips: ['a camera', 'text messages', 'games'], src: '20쪽 Discussion', nt: '이야기 질문', n: ['<del>What features of this device was mentioned</del> → What features were mentioned', '마지막 질문은 스마트폰이 없는 학생은 «I want a phone with …» 로'] },
      { t: 'order', k: 'new', img: '12428', words: ['The', 'letter', 'was', 'written', 'by', 'my', 'grandma.'], nt: '순서 맞추기 — 수동태', n: ['정답: The letter was written by my grandma. — was + written 의 자리를 다시 확인'] },
      { t: 'yourturn', k: 'keep', img: '12021', title: 'Your turn!', lines: ['How do you usually communicate with your friends?', 'What is your favorite way to communicate? Why?'], chips: ['texting', 'video calls', 'face to face'], src: '21쪽 Questions Edition', nt: '내 말로', n: ['«I usually … because …» 로 두 문장 이상'] },
      ...close([['I can talk about ways to communicate.', '소통하는 여러 방법을 말할 수 있어요.'], ['I can change a sentence into the passive.', '문장을 수동태로 바꿔 말할 수 있어요.'], ['I can say how I hang out with my friends.', '친구들과 어떻게 노는지 말할 수 있어요.']], { img: G('cover-002'), q: 'Who invented the first printing press?', ko: '다음 시간: 인쇄기부터 인터넷까지 — 큰 발명들의 이야기' }),
    ] },

  // ───────────────────────── 002
  { code: '002', tab: '큰 발명들', unit: U1, title: 'From Printing to Phones', orig: 25,
    intro: '인쇄기 → 전신기 → 편지 → 전화 → 인터넷 → 스마트폰. 발명마다 «누가·언제» 를 수동태로 말해 봅니다(The telephone was invented by …).',
    fixed: ['<del>into the the passive voice</del> → into the passive voice', '<del>Sunny send the message yesterday</del> → Sunny sent', '<del>everything has by ___</del> → everything had to be written by hand', '<del>It let\'s users … and uses many other</del> → It lets users … and use many other', '«Ancient Chinese and Koreans … almost 2000 years ago» → long before Gutenberg (사실 확인 필요 — 끝 목록)', '«Too much information! Just chill» 쉬어 가기 쪽 → 기억 게임으로'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-002'), q: 'Which invention changed the world?', story: 'From the printing press to the internet!', nt: '표지 + Big Question', n: ['«세상을 가장 많이 바꾼 발명은?» — 과 끝에 학생이 하나를 골라 이유를 말하는 것이 목표'] },
      ...open([['I can say who invented something and when.', '누가 언제 발명했는지 말할 수 있어요.'], ['I can use the passive voice in the past.', '과거 수동태를 쓸 수 있어요 — It was invented in 1876.'], ['I can talk about my smartphone.', '내 스마트폰에 대해 말할 수 있어요.']], 'Lesson Goals (Inventions · Active/Passive)'),
      { t: 'qa', k: 'keep', img: '18411', small: 'Picture talk', title: 'Then and now', q: 'What can you see? Which phone is newer?', a: 'The ___ is newer. The ___ is older.', src: '5쪽 Picture Talk', nt: '그림 이야기', n: ['할머니·손자의 옛 전화 vs 스마트폰 — 오늘 과 전체의 «그때와 지금» 을 엽니다'] },
      PASSIVE_TABLE('7~9쪽 Grammar'),
      { t: 'fill', k: 'fix', title: 'Pop-up! Change it into the passive.', lines: ['Sunny sent the message yesterday. → The message ___ by Sunny yesterday.', 'Rob will take the phone to the office. → The phone ___ to the office by Rob.', 'The thief snatched the phone. → The phone ___ by the thief.', 'She teaches English. → English ___ by her.', 'He is writing a letter. → A letter ___ by him.'], src: '10쪽 Pop-up', nt: '바꿔 말하기 — 다섯 문장', n: ['<del>into the the passive voice</del> · <del>Sunny send</del> → sent', '정답: was sent · will be taken · was snatched · is taught · is being written', '원본 6번 «Who wrote this letter?» → By whom was this letter written? 는 어려워 강사 도전 문제로만'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Great inventions 🔒', cols: 3, words: [['printing press', '인쇄기', '16480'], ['telegraph', '전신기', G('telegraph')], ['telephone', '전화기', '15196'], ['the internet', '인터넷', '17162'], ['smartphone', '스마트폰', '12261'], ['applications (apps)', '앱', '14366']], src: '12~19쪽', nt: '발명 이름 — 뜻 가리고', n: ['사진만 보고 먼저 이름 말하기 → 공개'] },
      { t: 'fill', k: 'fix', img: '21065', title: 'The printing press', lines: ['Gutenberg ___ the printing press in the 1400s.', 'He used metal type, not wooden blocks.', 'Before that, everything had to be ___.'], chips: ['developed', 'written by hand'], src: '12쪽', nt: '빈칸 — 인쇄기', n: ['<del>everything has by ___</del> → had to be written by hand', '❗ «almost 2000 years ago» 는 사실 확인이 필요해 «long before Gutenberg» 로 바꿨습니다(끝 목록)', '발명은 discover 가 아니라 develop/invent 라고 짚어 줍니다'] },
      { t: 'qa', k: 'keep', img: G('telegraph'), title: 'The telegraph', q: 'Samuel Morse invented it in 1844. How did it send messages?', a: 'It used ___ code — dots and dashes.', chips: ['Morse'], src: '13쪽', nt: '전신기', n: ['강사가 책상을 «톡 톡—» 두드려 모스 부호로 SOS(··· --- ···) 를 보여 줍니다', '«The telegraph was invented by Samuel Morse.» 로 수동태 한 번'] },
      { t: 'story', k: 'fix', small: 'Telephone', title: 'The first phone call', img: '15196', lines: [['Narrator', 'On March 10, 1876, Alexander Graham Bell made the first phone call.'], ['Bell', 'Mr. Watson, come here. I want to see you!'], ['Watson', 'I can hear you! It works!']], src: '15쪽', nt: '짧은 장면 — 첫 전화', n: ['원본 설명 문장 + 벨의 첫 통화 문장을 짧은 장면으로', '«Why do we say "hello" on the phone?» 로 이어 묻기'] },
      { t: 'ox', k: 'new', img: '19756', s: 'People never write letters to pen pals anymore.', src: '14쪽 Mail', nt: '⭕❌ 편지', n: ['정답 ❌(의견이 갈려도 좋음) → «Some people still write to pen pals.»', '원본 펜팔 퀴즈 쪽을 몸으로 답하기로'] },
      { t: 'qa', k: 'keep', img: '17162', title: 'The internet', q: 'The internet was invented by scientists in the 1960s. It was first used for science. How do you use it? Can you live without it?', a: 'I use it to ___. I can / can\'t live without it.', src: '16쪽', nt: '인터넷', n: ['원본 문장 그대로 · 수동태 두 번(was invented · was used)을 짚어 줍니다'] },
      { t: 'fill', k: 'fix', img: '19453', title: 'Smartphones', lines: ['A smartphone is a ___.', 'It lets users call, send text messages and use many other ___, or "apps."', 'You can do ___ with this device!'], chips: ['device', 'applications', 'almost everything'], src: '17쪽', nt: '빈칸 — 스마트폰', n: ['<del>It let\'s … and uses</del> → It lets … and use', '마지막 줄 느낌표로 과장해서 읽기'] },
      { t: 'guess', k: 'new', img: G('smartwatch'), open: [2, 6], q: 'What is it? What can it do?', chips: ['a smart watch', 'wireless earphones', 'Wi-Fi'], src: '19쪽 Other inventions', nt: 'Guess what — 다른 발명', n: ['원본 WiFi · 무선 이어폰 · 스마트워치 쪽을 타일 맞히기로', '맞히면 «It was invented to …» 로 말해 보기(정답 없음 — 생각 말하기)'] },
      { t: 'memory', k: 'fix', title: 'Too much information? Memory game!', items: ['16480', G('telegraph'), '15196', '19756', '17162', '12261'], hidden: 3, q: 'Look for 10 seconds. Which invention is gone?', a: 'The telephone!', src: '11쪽 «Just chill»', nt: '기억 게임', n: ['원본 «Too much information! Just chill» 쉬어 가기 쪽 → 오늘 발명 6개 기억 게임', '사라진 것을 말할 때 «It was invented by Bell.» 까지'] },
      { t: 'discuss', k: 'keep', img: '12261', title: 'Do you have a smartphone?', qs: ['What features does it have? A camera? A flashlight?', 'What brand is it?', 'What is your dream smartphone like?'], src: '18쪽', nt: '내 스마트폰', n: ['원본 질문 그대로 · 없으면 가족의 폰으로'] },
      { t: 'yourturn', k: 'keep', img: '19431', title: 'Your turn!', lines: ['Which invention do you use most?', 'Which is the most important? Why?', 'Which is used the least now?'], chips: ['the internet', 'smartphones', 'the telegraph'], src: '20쪽 Discussion', nt: '내 말로', n: ['세 번째 답에서 수동태 한 번: «The telegraph is not used anymore.»'] },
      ...close([['I can say who invented something and when.', '누가 언제 발명했는지 말할 수 있어요.'], ['I can use the passive voice in the past.', '과거 수동태를 쓸 수 있어요.'], ['I can talk about my smartphone.', '내 스마트폰에 대해 말할 수 있어요.']], { img: G('silly-shoes'), q: 'Umbrellas… for your shoes? Is it useful or useless?', ko: '다음 시간: 지나의 스마트폰 이야기 + 쓸모없는(!) 발명품들' }),
    ] },

  // ───────────────────────── 003
  { code: '003', tab: '가장 중요한 발명', unit: U1, title: "Gina's Smartphone", orig: 23,
    intro: '지나가 «스마트폰이 가장 중요한 발명» 이라고 발표합니다. 가정법(If I didn\'t have …, I would …)으로 «없다면?» 을 말해 보고, 웃기고 쓸모없는 발명품도 구경합니다.',
    fixed: ["<del>its definitely</del> → it's definitely", '<del>I use it for some purposes - do my homework, play games and to communicate</del> → I use it for many purposes: doing homework, playing games and communicating', '<del>feature 특색</del> → 기능 · <del>application 신청</del> → 앱', '«Pointless inventions» 6쪽 → Guess 타일 + ⭕❌ 로 줄임'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-003'), q: 'What is the best invention ever?', story: 'Gina says it is her phone. Do you agree?', nt: '표지 + Big Question', n: ['표지(걸어 다니는 침낭!)로 웃으며 시작 — «쓸모 있는 발명 vs 쓸모없는 발명»'] },
      ...open([['I can explain why an invention is important.', '발명이 왜 중요한지 설명할 수 있어요.'], ["I can say what I would do without something.", '무엇이 없다면 어떻게 할지 말할 수 있어요 — If I didn\'t have a phone, I would …'], ['I can tell useful and useless inventions apart.', '쓸모 있는 발명과 쓸모없는 발명을 구별할 수 있어요.']], 'Lesson Goals (Communication · Subjunctive mood)'),
      { t: 'qa', k: 'keep', img: '17043', small: 'Give it a try', title: 'Everyone has one!', q: 'Look! What is everyone doing? Is it good or bad?', a: 'Everyone is ___. I think it is ___ because ___.', src: '5쪽 Give it a try', nt: '몸풀기', n: ['모두 휴대폰을 보는 거리 — 의견을 둘로 나눠 말하게'] },
      { t: 'vocab', k: 'fix', hide: true, title: "Gina's words 🔒", cols: 4, words: [['various', '여러 가지의', '16087'], ['purpose', '목적', '16910'], ['feature', '기능', '14366'], ['application', '앱', '12261'], ['video conference', '화상 회의', '12042'], ['online chat', '온라인 채팅', '15768'], ['access', '접속하다', '19273'], ['bulky', '부피가 큰', '15596']], src: '6쪽 Vocabulary', nt: '낱말 — 뜻 가리고', n: ['<del>feature 특색</del> → 기능 · <del>application 신청</del> → 앱(이 이야기에서는 휴대폰 앱)'] },
      { t: 'read', k: 'fix', small: "Gina's speech ①", title: "Gina's Smartphone", img: G('gina'), paras: ["Hi, everyone! I'm Gina, and I'm here to talk about my smartphone. I would like to tell you that it's definitely the most important invention ever!", 'I use it for many purposes: doing my homework, playing games and communicating with people. It has many features that help me communicate.'], gloss: [['definitely', '틀림없이'], ['purposes', '목적']], src: '7쪽 Story', nt: '읽기 ①', n: ["<del>its definitely</del> → it's · <del>for some purposes - do …, play … and to communicate</del> → 모양을 맞춰(-ing) 고쳤습니다", '강사 1번 → 학생 1번 소리 내어 읽기'] },
      { t: 'read', k: 'fix', small: "Gina's speech ②", title: "Gina's Smartphone", img: '17162', paras: ['I use it to access the internet, download apps and visit social networking sites. I chat with friends online or have video conferences.', "I don't know what I would do without it. A computer would be too bulky to carry. I would have to use a telephone or send letters!"], gloss: [['bulky', '부피가 큰']], src: '7·8쪽 Story', nt: '읽기 ②', n: ['원본 긴 문장을 둘로 나눴습니다', '밑줄 문장 «I don\'t know what I would do without …» 이 오늘 가정법의 출발점'] },
      { t: 'fill', k: 'keep', img: G('gina'), title: 'Questions', lines: ['What is the most important invention for Gina? — Her ___.', 'What can she do with it? — She can ___ the internet.', 'Why would a computer be hard to use? — It is too ___ to carry.'], chips: ['smartphone', 'access', 'bulky', 'cheap'], src: '9쪽 Follow-up', nt: '이야기 질문', n: ['cheap 은 함정 칩'] },
      IF_RULE('Lesson Goals (Subjunctive mood)'),
      { t: 'order', k: 'new', img: '18073', words: ['If', 'I', "didn't", 'have', 'a phone,', 'I', 'would', 'send', 'letters.'], nt: '순서 맞추기 — 가정법', n: ['정답: If I didn\'t have a phone, I would send letters. — 쉼표 자리 확인'] },
      { t: 'guess', k: 'fix', img: '21284', open: [0, 8], q: 'A training kit for… what? What does it do?', chips: ['a fish tank', 'a fish training kit', 'a toy boat'], src: '10쪽 Pointless inventions', nt: 'Guess what — 물고기 훈련 키트', n: ['원본 «Fish Training Kit»(금붕어 축구) — 타일을 열며 무엇인지 맞히기', '맞힌 뒤 «Is it useful or useless? Why?»'] },
      { t: 'match', k: 'fix', title: 'Silly inventions!', left: [G('silly-shoes'), '12825', G('sleeping-bag'), G('car-desk')], right: ['a walking sleeping bag', 'shoe umbrellas', 'a car desk', 'a butter stick'], src: '10~13쪽 Pointless inventions', nt: '짝짓기 — 쓸모없는 발명', n: ['원본 6개 중 4개(Screen Privacy·Fish kit 은 앞뒤 쪽에서)', '짝을 맞출 때마다 «Would you use it? Why or why not?»'] },
      { t: 'ox', k: 'new', img: G('car-desk'), s: 'A car desk is a safe way to work while you drive.', src: '12쪽', nt: '⭕❌ 차 책상', n: ['정답 ❌ → «No! You shouldn\'t work while you drive. It\'s dangerous.»'] },
      { t: 'discuss', k: 'keep', img: '18191', small: "Let's get serious, buddy!", title: 'Best and worst', qs: ['What do you think is the best invention?', 'What would you do without it?', 'What is the worst invention? Why?'], chips: ['If I didn\'t have ___, I would ___.'], src: '14·15쪽', nt: '진지하게 말하기', n: ['원본 «Let\'s get serious, buddy!» 그대로 — 두 번째 질문을 가정법 틀로'] },
      { t: 'yourturn', k: 'new', img: '12005', title: 'Your turn! Be like Gina.', lines: ['The most important invention for me is ___.', 'I use it for ___ and ___.', "If I didn't have it, I would ___."], nt: '내 말로 — 1분 발표', n: ['지나처럼 1분 발표 — 세 줄을 다 말하면 박수'] },
      CHANT('마지막 쪽 노래'),
      ...close([['I can explain why an invention is important.', '발명이 왜 중요한지 설명할 수 있어요.'], ['I can say what I would do without something.', '무엇이 없다면 어떻게 할지 말할 수 있어요.'], ['I can tell useful and useless inventions apart.', '쓸모 있는 발명과 쓸모없는 발명을 구별할 수 있어요.']], { img: '14171', q: 'Who is cleaning the house? A robot?!', ko: '다음 시간: Unit 2 — 삶을 편하게 해 주는 발명' }),
    ] },

  // ───────────────────────── 004
  { code: '004', tab: '자동·효율', unit: U2, title: 'Automatic and Efficient', orig: 30,
    intro: '세탁기·전자레인지·로봇청소기처럼 «자동(automatic)» 이고 «효율적인(efficient)» 발명을 봅니다. 이야기: 카멜이 손빨래를 하고 녹초가 됐어요!',
    fixed: ['<del>advanced 향상된</del> → 첨단의 · <del>stapler 호치키스</del> → 스테이플러(상표 이름 대신)', '<del>We don\'t need to have to work very hard</del> → We don\'t have to work very hard', '지도 vs GPS 쪽 원본 사진(운전하며 휴대폰을 든 손) → 차 대시보드 GPS 사진으로(안전)', '«Things that are automatic» 6쪽 → 두 개씩 비교하는 쪽으로 묶음', 'Activity(우물·선풍기·에어컨·부채) 빈 표 → 말할 틀을 넣은 표'],
    slides: [
      { t: 'cover', k: 'new', img: '14171', q: 'Which machine saves you time?', story: 'Carmel looks so tired! Why?', nt: '표지 + Big Question', n: ['로봇청소기에 올라탄 고양이 — «이 기계는 무엇을 대신해 줄까?»'] },
      ...open([['I can tell if a machine is automatic.', '기계가 자동인지 아닌지 말할 수 있어요.'], ['I can say why a machine is efficient.', '기계가 왜 효율적인지 말할 수 있어요 — It saves time and effort.'], ['I can compare two ways of doing a job.', '같은 일을 하는 두 방법을 비교할 수 있어요.']], 'Lesson Goals (Inventions and Science · Active/Passive)'),
      { t: 'qa', k: 'keep', img: '19431', small: 'Warm up', title: '10-second challenge!', q: 'Name as many inventions as you can in 10 seconds. Go!', a: 'phone, ___, ___, ___ …', src: '5쪽 Warm Up', nt: '10초 도전', n: ['강사가 초를 세고 학생이 말한 개수를 세어 줍니다 — 과 끝에 한 번 더 해서 늘었는지'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Easy-life words 🔒', cols: 4, words: [['efficient', '효율적인', '14738'], ['manual', '손으로 하는', '18074'], ['automatic', '자동의', '14171'], ['temperature', '온도', G('thermostat')], ['convenient', '편리한', '15552'], ['advanced', '첨단의', '18191'], ['effort', '노력, 수고', '15395'], ['save time', '시간을 아끼다', '12999']], src: '6쪽 Vocabulary', nt: '낱말 — 뜻 가리고', n: ['<del>advanced 향상된</del> → 첨단의', 'manual ↔ automatic 은 짝으로 기억'] },
      PASSIVE_RULE('7·8쪽 Grammar'),
      { t: 'fill', k: 'fix', img: '14738', title: 'Efficient technology', lines: ['Washing machines save a lot of time and ___.', "We don't ___ to work very hard.", 'We only have to push the ___.'], chips: ['effort', 'have', 'button'], src: '10쪽', nt: '빈칸 — 세탁기', n: ['<del>We don\'t need to have to work</del> → We don\'t have to work', '끝에 «Do you have a washing machine at home?»'] },
      { t: 'match', k: 'fix', title: 'Efficient helpers', left: ['15552', G('rice-cooker'), '12446', '14171'], right: ['a remote control', 'a robot vacuum', 'a microwave', 'a rice cooker'], src: '11·12쪽', nt: '짝짓기 — 효율적인 기계', n: ['짝을 맞출 때마다 «It saves time because …» 한 문장'] },
      { t: 'qa', k: 'keep', img: G('thermostat'), title: 'The thermostat', q: 'The thermostat is automatic. After you set it, it keeps your house at the right temperature. Do you have one?', a: 'Yes, we do. / No, we don\'t. We use ___.', src: '13쪽', nt: '자동 ① 온도조절기', n: ['원본 설명 그대로 · «After you set it» 의 순서를 손으로 보여 줍니다'] },
      { t: 'table', k: 'fix', small: 'Compare', title: 'Which one is automatic?', head: ['this', 'or this?', 'automatic?'], rows: [['🧹 a broom', '🤖 a robot vacuum', 'the robot vacuum'], ['🪣 a water dipper', '🚿 a shower', 'the shower'], ['🔥 a stove', '📦 a microwave', 'the microwave'], ['🗺️ a paper map', '🧭 GPS', 'GPS']], src: '14~18쪽', nt: '둘씩 비교 — 자동', n: ['원본 5쪽(로봇청소기·샤워/바가지·전자레인지/가스레인지·지도/GPS)을 한 표로', '오른쪽 칸을 가리고 학생이 먼저 답하게', '원본 질문을 줄마다: «How do you use it?» «Which do you use at home?» «What do you usually cook in the microwave?»'] },
      { t: 'qa', k: 'fix', img: '12999', title: 'Map or GPS?', q: 'Which one is more efficient when you drive?', a: '___ is more efficient. Drivers shouldn\'t look at a map.', src: '18쪽', nt: '지도 vs GPS', n: ['❗ 원본 사진(운전하며 휴대폰을 든 손)은 위험 행동이라 대시보드 GPS 사진으로 바꿨습니다', '안전 이야기로 이어가기'] },
      { t: 'ox', k: 'keep', img: '12697', s: 'Scissors are useful, and they are automatic.', src: '19쪽', nt: '⭕❌ 가위', n: ['정답 ❌ → 원본 문장 «Scissors are useful, but they\'re not automatic.»'] },
      { t: 'vocab', k: 'keep', title: 'Role-play words', cols: 4, words: [['exhausted', '녹초가 된', '13341'], ['automatic', '자동의', '14738'], ['efficient', '효율적인', '12999'], ['affordable', '값이 적당한', '12338']], src: '20쪽', nt: '역할놀이 낱말' },
      { t: 'story', k: 'fix', small: 'Story ①', title: "Carmel's laundry day", img: G('carmel-laundry'), lines: [['Nate', 'Carmel, you look exhausted. Did you exercise at the gym?'], ['Carmel', 'No, Nate. I did the laundry.'], ['Nate', 'What? Are you serious?'], ['Carmel', 'Yeah! I washed all the clothes by hand.'], ['Nate', "Don't you have a washing machine?"]], src: '21쪽 Role-play', nt: '이야기 ① 역할놀이', n: ['<del>Don\'t you have the washing machine</del> → a washing machine', '강사가 Nate, 학생이 Carmel(지친 목소리로)'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: "Carmel's laundry day", img: '14738', lines: [['Carmel', "We don't have one yet. It's automatic, right?"], ['Nate', "You're right. It's very efficient. It saves time and effort."], ['Carmel', 'Cool. Can I borrow yours?'], ['Nate', 'Uhm… You can buy one for a very affordable price!'], ['Carmel', "Okay. I'll buy one next month."]], src: '21·22쪽 Role-play', nt: '이야기 ②', n: ['원본 16줄 → 핵심 10줄로(건조기 대화는 다음 쪽 질문으로)', '«Can I borrow yours?» 에서 멈추고 Nate 가 뭐라 할지 예측하게'] },
      { t: 'discuss', k: 'fix', img: G('carmel-laundry'), title: 'Talk about the story', qs: ['Why did Carmel look exhausted?', "What doesn't Nate's washing machine have?", 'When will Carmel buy one?', 'What features would you add?'], src: '23쪽 Discussion', nt: '이야기 질문', n: ['두 번째 답: «It doesn\'t have a dryer.» — 원본 대화의 건조기 부분'] },
      { t: 'guess', k: 'new', img: '14171', open: [1, 7], q: 'What is it? Is it automatic?', chips: ['a microwave', 'a robot vacuum', 'an electric fan'], nt: 'Guess what 타일', n: ['열 때마다 «Is it a …?»', '맞히면 수동태로: «The floor is cleaned by the robot.»'] },
      { t: 'scramble', k: 'new', title: 'Unscramble!', items: [['t-a-i-c-u-t-o-m-a', '14738'], ['f-i-e-f-i-c-n-e-t', '12999'], ['n-u-a-a-m-l', '18074'], ['e-l-d-f-r-a-a-b-o-f', '12338']], nt: '글자 조각 맞추기', n: ['정답 automatic · efficient · manual · affordable — 맞히면 사진으로 문장 하나'] },
      { t: 'table', k: 'fix', small: 'Activity', title: 'Automatic or not?', head: ['invention', 'automatic?', 'How does it make life easier?'], rows: [['💧 a well', '___', 'It gives us ___.'], ['🌀 an electric fan', '___', 'It keeps us ___.'], ['❄️ an air conditioner', '___', 'It ___ the room.'], ['🪭 a hand fan', '___', 'We have to ___ it.']], src: '24~26쪽 Activity', nt: '표 채우기 — 자동인가?', n: ['원본 빈 표에 말할 틀을 넣었습니다', '정답 예: well ✗ · electric fan ✓(켜면 혼자 돎) · air conditioner ✓ · hand fan ✗'] },
      { t: 'yourturn', k: 'new', img: '19027', title: 'Your turn!', lines: ['What machine at home saves you the most time?', 'Is it automatic? How does it help you?'], nt: '내 말로', n: ['«The ___ saves me the most time. It\'s automatic, so …»'] },
      ...close([['I can tell if a machine is automatic.', '기계가 자동인지 아닌지 말할 수 있어요.'], ['I can say why a machine is efficient.', '기계가 왜 효율적인지 말할 수 있어요.'], ['I can compare two ways of doing a job.', '같은 일을 하는 두 방법을 비교할 수 있어요.']], { img: G('cover-005'), q: 'Zipper or buttons — which is faster?', ko: '다음 시간: 작지만 대단한 발명 — 지퍼·벨크로·스테이플러' }),
    ] },

  // ───────────────────────── 005
  { code: '005', tab: '작은 발명', unit: U2, title: 'Simple Inventions', orig: 22,
    intro: '지퍼·벨크로·스테이플러·밥솥·리모컨 — 작고 흔하지만 «알아줄 만한» 발명들. 누가·언제 만들었는지 수동태로 말합니다(It was invented in 1941).',
    fixed: ['<del>Robert Adier</del> → Robert Adler', '<del>birds chirps</del> → birds\' chirps', '<del>protecting itself from burn out</del> → keeping the rice from burning', '빈칸 정답(invented · better · easier / patented · sticky seeds)이 같은 쪽에 보이던 것 → 칩으로 섞음', '«Making Connections» 4쪽 → 기억 게임 + 질문 한 쪽'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-005'), q: 'What small invention do you use?', story: 'Zip! Rip! Click! Small things matter.', nt: '표지 + Big Question', n: ['지퍼로 빨리 입기 경주 — «아주 작은 발명도 삶을 바꿀까?»'] },
      ...open([['I can explain how a simple invention works.', '간단한 발명이 어떻게 작동하는지 설명할 수 있어요.'], ['I can say when something was invented.', '언제 발명되었는지 말할 수 있어요 — It was invented in 1941.'], ['I can imagine life without an invention.', '어떤 발명이 없는 삶을 상상해 말할 수 있어요.']], 'Lesson Goals (Inventions and Science · Active/Passive)'),
      { t: 'qa', k: 'keep', img: '16585', small: 'Picture talk', title: 'Simple but great', q: "They're simple inventions, but they're worth recognizing. What are they?", a: 'They are ___ and ___.', src: '5쪽 Picture Talk', nt: '그림 이야기', n: ['원본 문장 그대로 — «worth recognizing = 알아줄 만한»'] },
      PASSIVE_TABLE('7~9쪽 Grammar'),
      { t: 'vocab', k: 'fix', hide: true, title: 'Simple inventions 🔒', cols: 3, words: [['zipper', '지퍼', '15834'], ['velcro', '벨크로(찍찍이)', G('velcro')], ['sticky seeds', '달라붙는 씨앗', G('velcro')], ['stapler', '스테이플러', '15731'], ['rice cooker', '전기밥솥', G('rice-cooker')], ['remote control', '리모컨', '13232']], src: '6쪽 Vocabulary', nt: '낱말 — 뜻 가리고', n: ['<del>velcro 찍찍이</del> → 벨크로(찍찍이) · <del>stapler 호치키스</del> → 스테이플러'] },
      { t: 'fill', k: 'fix', img: '15834', title: 'The zipper', lines: ['The zipper was ___ in the late 1800s.', 'Gideon Sundback redesigned it and made it ___.', 'People liked zippers because they looked neat, and they were faster and ___ to use than buttons.'], chips: ['easier', 'better', 'invented'], src: '10쪽', nt: '빈칸 — 지퍼', n: ['<del>1800\'s</del> → 1800s', '정답 invented · better · easier'] },
      { t: 'fill', k: 'fix', img: G('velcro'), title: 'Velcro', lines: ['Velcro was ___ in 1941 by George de Mestral.', 'He got the idea from plants with ___.', 'He ___ velcro and began to sell it in the 1950s.'], chips: ['patented', 'sticky seeds', 'invented'], src: '11쪽', nt: '빈칸 — 벨크로', n: ['끝에 원본 질문: «Which is more useful, the zipper or velcro?»', 'patent = 특허를 받다'] },
      { t: 'ox', k: 'keep', img: '15731', s: 'The first stapler was made for the King of France.', src: '12쪽', nt: '⭕❌ 스테이플러', n: ['정답 ⭕ — 18세기 프랑스 왕을 위해', '이어서 «How is it better than paper clips?»'] },
      { t: 'qa', k: 'fix', img: G('rice-cooker'), title: 'The rice cooker', q: 'Why did people like the rice cooker?', a: 'It was easier than using a ___. It keeps rice from ___.', src: '13쪽', nt: '밥솥', n: ['<del>protecting itself from burn out</del> → keeping the rice from burning', '«Does your family often use a rice cooker?»'] },
      { t: 'story', k: 'fix', small: 'Remote control', title: 'Who changed the channel?!', img: '13232', lines: [['Narrator', 'The remote control was invented by Robert Adler in 1956.'], ['Narrator', 'It had only four buttons, and it used sound waves.'], ['Dad', "Hey! Who changed the channel? I didn't touch it!"], ['Kid', "It was the birds, Dad! Their chirps changed the channel!"]], src: '14쪽', nt: '짧은 장면 — 첫 리모컨', n: ['<del>Adier</del> → Adler · <del>birds chirps</del> → birds\' chirps', '원본 «새소리가 채널을 바꿨다» 사실을 웃긴 장면으로'] },
      { t: 'guess', k: 'fix', img: '19429', open: [0, 4], q: 'Who invented it? What is it?', chips: ['the telephone', 'the light bulb', 'Thomas Edison', 'Alexander Graham Bell'], src: '16쪽 Making Connections', nt: 'Guess who — 전구', n: ['원본 «Who invented it?» 를 타일 맞히기로', '맞히면 수동태로: «The light bulb was invented by Edison.»'] },
      { t: 'memory', k: 'fix', title: 'Making Connections', items: ['12824', '18086', G('phone-holder'), G('correction-tape'), '15834', '15731'], hidden: 4, q: 'Look for 10 seconds. What is missing?', a: 'The correction tape!', src: '16~19쪽', nt: '기억 게임', n: ['원본 네 쪽(전구·청소기·휴대폰 거치대·수정테이프) + 오늘 발명 둘', '사라진 것을 맞힌 뒤 «Do you still use it nowadays?»'] },
      { t: 'discuss', k: 'keep', img: G('correction-tape'), title: 'Making Connections', qs: ['How did these inventions make life easier?', 'What could happen if they were not invented?', 'Do you still use correction tape nowadays?'], chips: ['If there were no ___, we would ___.'], src: '15·19쪽', nt: '연결해서 생각하기', n: ['두 번째 질문은 가정법 틀 칩으로'] },
      { t: 'order', k: 'new', img: '12446', words: ['The', 'remote', 'control', 'was', 'invented', 'in', '1956.'], nt: '순서 맞추기', n: ['정답: The remote control was invented in 1956.'] },
      { t: 'yourturn', k: 'new', img: '12596', title: 'Your turn!', lines: ['What small invention do you use every day?', 'How does it make your life easier?', 'What would you do without it?'], nt: '내 말로', n: ['세 줄을 이어 말하면 성공'] },
      ...close([['I can explain how a simple invention works.', '간단한 발명이 어떻게 작동하는지 설명할 수 있어요.'], ['I can say when something was invented.', '언제 발명되었는지 말할 수 있어요.'], ['I can imagine life without an invention.', '어떤 발명이 없는 삶을 상상해 말할 수 있어요.']], { img: G('cover-006'), q: 'What would school be like without scissors or staplers?', ko: '다음 시간: 학교 속 간단한 발명 이야기' }),
    ] },

  // ───────────────────────── 006
  { code: '006', tab: '학교 속 발명', unit: U2, title: 'Inventions at School', orig: 18,
    intro: '읽기 «Simple Inventions»: 스테이플러와 가위가 없다면? 가정법을 제대로 연습하고, 나에게 가장 중요한 발명 세 가지를 발표합니다.',
    fixed: ['<del>If we didn\'t have it</del> → them(가위는 복수) · <del>two difficult</del> → too difficult', '<del>staple 스테이플</del> → 스테이플러로 찍다 · <del>tape 줄자</del> → 테이프 · <del>hold together 함께 잡다</del> → 한데 붙어 있다 · <del>properly 적합하게</del> → 올바르게', '<del>why are they important</del> → why they are important', '인용 출처 <del>Christian Louis Lange</del> → Christian Lous Lange'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-006'), q: 'Which school tool do you need most?', story: 'Snip, snip! Click, click!', nt: '표지 + Big Question' },
      ...open([['I can talk about inventions I use at school.', '학교에서 쓰는 발명품을 말할 수 있어요.'], ["I can say \"If I didn't have …, I would …\".", '«…이 없다면 …할 거예요» 를 말할 수 있어요.'], ['I can give a short talk about three inventions.', '발명품 세 가지로 짧게 발표할 수 있어요.']], 'Lesson Goals (Inventions and Science · Subjunctive mood)'),
      { t: 'table', k: 'fix', small: 'Pop-up!', title: 'Three inventions I often use', head: ['invention', 'How do you use it?'], rows: [['1. ___', 'I use it to ___.'], ['2. ___', 'I use it to ___.'], ['3. ___', 'I use it to ___.']], src: '5쪽 Pop-up', nt: '표 — 자주 쓰는 발명 세 가지', n: ['앞 과에서 배운 발명 중에서 고르게'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Story words 🔒', cols: 4, words: [['staple', '스테이플러로 찍다', '15731'], ['in addition', '게다가', '16910'], ['tape', '테이프', '12596'], ['hold together', '한데 붙어 있다', '18508'], ['blade cutter', '커터칼', 'c7171'], ['risky', '위험한', G('cover-006')], ['properly', '올바르게', '12697'], ['efficient', '효율적인', '15731']], src: '6쪽 Vocabulary', nt: '낱말 — 뜻 가리고', n: ['원본 뜻 네 개를 고쳤습니다(위 fixed)', 'risky 는 표지 사진(가위를 조심히)으로'] },
      { t: 'read', k: 'fix', small: 'Story ①', title: 'Simple Inventions', img: '15731', paras: ['Simple inventions make school life much easier. I think the stapler is very efficient. I staple my homework, and my teachers staple our tests. In addition, staples are cheap.', "If I didn't have a stapler, I would have to use paper clips or tape. That would take longer, and my papers wouldn't hold together as well."], gloss: [['hold together', '한데 붙어 있다']], src: '7쪽 Story', nt: '읽기 ① — 스테이플러', n: ['긴 한 문장을 두 문장으로 나눴습니다', '가정법 문장 «If I didn\'t have …, I would …» 에 밑줄'] },
      { t: 'read', k: 'fix', small: 'Story ②', title: 'Simple Inventions', img: 'c7171', paras: ["Scissors are also very helpful. Students use them to cut things. If we didn't have them, we would have to cut paper with a knife or a blade cutter.", 'That would be too difficult and risky. We could hurt ourselves or others if we were careless. All inventions are useful. People just need to use them properly to make their lives easier.'], gloss: [['careless', '조심하지 않는'], ['properly', '올바르게']], src: '7·8쪽 Story', nt: '읽기 ② — 가위', n: ['<del>have it</del> → them · <del>two difficult</del> → too difficult · <del>we can hurt … if we are</del> → could … were(가정법 맞춤)'] },
      { t: 'fill', k: 'keep', img: 'c7171', title: 'Questions', lines: ['What inventions does the writer talk about? — The ___ and ___.', 'What would the writer use without a stapler? — Paper clips or ___.', 'Why is a blade cutter risky? — We could ___ ourselves.'], chips: ['stapler', 'scissors', 'tape', 'hurt', 'glue'], src: '9쪽 Follow-up', nt: '이야기 질문', n: ['glue 는 함정 칩'] },
      IF_RULE('Lesson Goals (Subjunctive mood)'),
      { t: 'match', k: 'new', title: "If I didn't have …", left: ['15731', '12697', '12446', '15552'], right: ['I would cut paper with a knife.', 'I would get up to change the channel.', 'I would heat food on the stove.', 'I would use paper clips.'], nt: '짝짓기 — 가정법', n: ['사진(없는 것) ↔ 대신 할 일 — «If I didn\'t have a stapler, I would use paper clips.» 로 이어 말하기'] },
      { t: 'ox', k: 'new', img: '12596', s: 'The writer thinks all inventions are dangerous.', nt: '⭕❌ 이야기 확인', n: ['정답 ❌ → «No! All inventions are useful. We just need to use them properly.»'] },
      { t: 'guess', k: 'new', img: '15731', open: [3, 5], q: 'What school tool is it?', chips: ['a stapler', 'a pair of scissors', 'tape'], nt: 'Guess what 타일', n: ['맞히면 «If I didn\'t have it, I would …» 로 한 문장'] },
      { t: 'yourturn', k: 'fix', img: '16910', small: 'Give it a try', title: 'My three most important inventions', lines: ['The three most important inventions I use are ___, ___ and ___.', 'They are important to me because ___.', 'Without them, I would have to ___.'], src: '10쪽 Give it a try', nt: '내 말로 — 발표', n: ['<del>why are they important</del> → why they are important', '1분 발표 — 끝나면 친구(강사)가 질문 하나'] },
      { t: 'discuss', k: 'fix', img: '18191', small: 'Quote of the Day', title: '"Technology is a useful servant, but a dangerous master."', qs: ['— Christian Lous Lange', 'What does this mean?', 'When can technology be a "master"?'], chips: ['servant 하인', 'master 주인'], src: '11쪽 Quote of the Day', nt: '오늘의 명언', n: ['<del>Christian Louis Lange</del> → Lous(노벨평화상 수상자 이름)', '예: 휴대폰을 너무 오래 쓰면 기술이 «주인» 이 된다'] },
      ...close([['I can talk about inventions I use at school.', '학교에서 쓰는 발명품을 말할 수 있어요.'], ["I can say \"If I didn't have …, I would …\".", '«…이 없다면 …할 거예요» 를 말할 수 있어요.'], ['I can give a short talk about three inventions.', '발명품 세 가지로 짧게 발표할 수 있어요.']], { img: G('cover-007'), q: 'Who is the most creative person you know?', ko: '다음 시간: Unit 3 — 생각이 큰 사람들' }),
    ] },

  // ───────────────────────── 007
  { code: '007', tab: '창의·설득', unit: U3, title: 'Great Thinkers', orig: 25,
    intro: '상상력 있는(imaginative) · 직관적인(intuitive) · 설득력 있는(persuasive) · 열정적인(passionate) 사람들. 접미사로 낱말 모양 바꾸기(create → creation). 이야기: 준리가 로엘의 글쓰기를 도와줘요.',
    fixed: ['<del>FUNTION</del> → FUNCTION', '<del>compose 짓다</del> → 작곡하다 · <del>essay 수필</del> → 글 · <del>introduction 소개</del> → 서론', '<del>Our professor told us</del> → Our teacher(학생 대상) · <del>Essay has three parts</del> → An essay has', '<del>no time</del> → in no time(금방)', '<del>Good artists copy, great artiste steal</del> → great artists steal', '호킹 쪽 현재형(I study … I have …) → 과거형(2018년 별세)'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-007'), q: 'Who is the smartest person in the world?', story: 'Roel has an essay due tomorrow!', nt: '표지 + Big Question', n: ['원본 Warm Up 질문을 Big Question 으로'] },
      ...open([['I can describe people with -ive and -ful words.', '-ive · -ful 낱말로 사람을 묘사할 수 있어요.'], ['I can change a word with a suffix.', '접미사로 낱말 모양을 바꿀 수 있어요 — create → creation.'], ['I can give my opinion in a persuasive way.', '내 의견을 설득력 있게 말할 수 있어요.']], 'Lesson Goals (Suffixes · Active/Passive)'),
      { t: 'vocab', k: 'fix', hide: true, title: 'Great-mind words 🔒', cols: 4, words: [['imagine', '상상하다', '12397'], ['intuitive', '직관적인', '12265'], ['persuasive', '설득력 있는', '21337'], ['argue', '주장하다', '18339'], ['opinion', '의견', '18339'], ['passionate', '열정적인', '12783'], ['compose', '작곡하다', '13176'], ['unique', '독특한', G('red-tulip')]], src: '6쪽 Vocabulary', nt: '낱말 — 뜻 가리고', n: ['<del>compose 짓다</del> → 작곡하다(음악)'] },
      SUFFIX_RULE('7쪽 Suffix'),
      SUFFIX_TABLE('8쪽 Suffix'),
      { t: 'fill', k: 'fix', img: '12397', title: 'Imaginative people', lines: ['These people have great ___.', 'They are creative and can ___ interesting thoughts and ideas.'], chips: ['imagination', 'imagine', 'imaginative'], src: '9쪽', nt: '빈칸 — 상상력', n: ['같은 뿌리 세 칩 중 자리에 맞는 모양 고르기 — 오늘 접미사 연습'] },
      { t: 'fill', k: 'fix', img: '12265', title: 'Intuitive people', lines: ['These people have deep ___.', 'They look at ___ and think of various ___ very quickly.'], chips: ['intuition', 'problems', 'solutions'], src: '10쪽', nt: '빈칸 — 직관', n: ['<del>intuitions</del> → intuition(보통 셀 수 없는 뜻으로)'] },
      { t: 'fill', k: 'fix', img: '21337', title: 'Persuasive people', lines: ['These people are good at ___ their opinions.', 'They are good speakers, and they can ___ you very easily.', 'That means you will probably ___ what they say.'], chips: ['arguing', 'persuade', 'believe'], src: '11쪽', nt: '빈칸 — 설득', n: ["<del>you will likely believe what they're saying</del> → you will probably believe what they say"] },
      { t: 'fill', k: 'keep', img: '12783', title: 'Passionate people', lines: ['___ people have a lot of ___ for what they do.', 'They work hard without expecting anything in return.', 'They never give up!'], chips: ['Passionate', 'passion'], src: '12쪽', nt: '빈칸 — 열정', n: ['<del>passion in what they do</del> → passion for'] },
      { t: 'vocab', k: 'fix', title: 'Role-play words', cols: 4, words: [['essay', '글(과제)', '18508'], ['introduction', '서론', 'c7018'], ['conclusion', '결론', '20169' ], ['deadline', '마감 날', 'c7018']], src: '13쪽', nt: '역할놀이 낱말', n: ['<del>essay 수필 · introduction 소개</del> → 글 · 서론'] },
      { t: 'story', k: 'fix', small: 'Story ①', title: "Roel's essay", img: G('junry-roel'), lines: [['Junry', 'Roel, did you finish it already?'], ['Roel', "Huh? I don't get it."], ['Junry', 'Our teacher told us to write an essay about the most passionate person we know.'], ['Roel', "I'm not that creative in writing. Can you help me out?"], ['Junry', 'Sure. An essay has three parts: the introduction, the body and the conclusion.']], src: '14쪽 Role-play', nt: '이야기 ① 역할놀이', n: ['<del>professor</del> → teacher · <del>make an essay about the most passionate people</del> → write an essay about the most passionate person', '<del>Essay has</del> → An essay has'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: "Roel's essay", img: 'c7018', lines: [['Roel', 'How should I start the introduction?'], ['Junry', 'A question is a good way to start. Hurry — the deadline is tomorrow!'], ['Roel', "Don't worry. I can finish it in no time!"]], src: '14·15쪽 Role-play', nt: '이야기 ②', n: ['원본 서론·설득 어조 대화를 줄였습니다(«Should I make a persuasive tone?» 는 강사가 추가 질문으로 — <del>make</del> → use a persuasive tone)', '원본의 «누가 가장 열정적인가(Nelson Mandela · Mahatma Gandhi)» 는 다음 쪽 토론·008 인물 쪽에서'] },
      { t: 'discuss', k: 'fix', img: G('junry-roel'), title: 'Talk about the story', qs: ['What did the teacher tell them to do?', 'What are the three parts of an essay?', 'Who is the most passionate person you know?'], chips: ['introduction', 'body', 'conclusion'], src: '16쪽 Discussion', nt: '이야기 질문', n: ['마지막 질문은 «I think ___ is the most passionate because …»'] },
      { t: 'ox', k: 'new', img: 'c7018', s: 'The essay is due next week.', nt: '⭕❌ 이야기 확인', n: ['정답 ❌ → «No! The deadline is tomorrow.»'] },
      { t: 'guess', k: 'fix', img: '12783', open: [0, 8], q: '"Good artists copy; great artists steal." Who said it?', chips: ['Pablo Picasso', 'Mozart', 'Stan Lee'], src: '17쪽 Activity', nt: 'Guess who — 화가', n: ['<del>artiste</del> → artists', '실존 인물 얼굴 대신 «그리는 모습» 사진으로 맞히기', '뜻 풀이: 따라 하기에서 시작해 자기 것으로 만든다'] },
      { t: 'guess', k: 'fix', img: '13176', open: [2, 6], q: '"I composed more than 600 pieces of music." Who am I?', chips: ['Mozart', 'Picasso', 'J.K. Rowling'], src: '18쪽 Activity', nt: 'Guess who — 작곡가', n: ['<del>I just composed 600 pieces. Wasn\'t I busy?</del> → 과거 사실 문장으로', '맞히면 수동태로: «Many pieces were composed by Mozart.»'] },
      { t: 'match', k: 'fix', title: 'Who did what?', left: [G('wizard-book'), G('black-hole'), '12783', '13176'], right: ['painted pictures', 'wrote the Harry Potter books', 'composed music', 'studied black holes'], src: '17~20쪽 Activity', nt: '짝짓기 — 네 사람의 일', n: ['피카소·모차르트·J.K. 롤링·스티븐 호킹을 «한 일» 로 짝짓기', '❗ 호킹 쪽 원본 현재형(I study … I have ALS) → 과거형으로: «He studied black holes. He used a computer to talk.»', '롤링 쪽 원본 질문 «Did you read them or watch them?» 과 호킹 쪽 «Have you heard of the Ice Bucket Challenge?» 는 짝짓기 뒤 묻기'] },
      { t: 'yourturn', k: 'new', img: '18339', title: 'Your turn! Be persuasive.', lines: ['I think ___ is the best invention.', 'First, ___. Second, ___.', 'So you should agree with me!'], nt: '내 말로 — 설득하기', n: ['30초 설득 연설 — 강사는 «I\'m not sure…» 로 한 번 반박'] },
      ...close([['I can describe people with -ive and -ful words.', '-ive · -ful 낱말로 사람을 묘사할 수 있어요.'], ['I can change a word with a suffix.', '접미사로 낱말 모양을 바꿀 수 있어요.'], ['I can give my opinion in a persuasive way.', '내 의견을 설득력 있게 말할 수 있어요.']], { img: G('cover-008'), q: 'One red umbrella in a sea of black. What makes it special?', ko: '다음 시간: 세상에 하나뿐인(unique) 생각을 한 사람들' }),
    ] },

  // ───────────────────────── 008
  { code: '008', tab: '독특한 사람들', unit: U3, title: 'Unique Minds', orig: 22,
    intro: '«unique = 세상에 하나뿐인». 구글·페이스북·마이크로소프트를 만든 사람, 건축가, 첼리스트, 만화 영웅을 만든 사람 — 무엇이 그들을 특별하게 했을까?',
    fixed: ['<del>never finished university</del> → left their studies at Stanford (사실 확인 — 끝 목록)', "<del>What's another search engine do you use</del> → What other search engine do you use", '<del>Richest man in the world</del> → one of the richest people in the world (지금은 사실이 아님)', '<del>French American cellist</del> → a cellist born in Paris to Chinese parents', '실존 인물 얼굴 사진 → «한 일» 사진 + 글자 단서'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-008'), q: 'What makes you unique?', story: 'One red umbrella among black ones!', nt: '표지 + Big Question', n: ['«나를 특별하게 하는 것은?» — 과 끝에 학생이 자기만의 점 하나를 말하는 것이 목표'] },
      ...open([['I can explain what "unique" means.', 'unique 의 뜻을 설명할 수 있어요.'], ['I can talk about people with great minds.', '생각이 큰 사람들에 대해 말할 수 있어요.'], ['I can say which great mind I would like to meet.', '만나고 싶은 사람과 그 이유를 말할 수 있어요.']], 'Lesson Goals (Suffixes · Active/Passive)'),
      { t: 'qa', k: 'keep', img: G('red-tulip'), small: 'Picture talk', title: 'Spot it!', q: 'Which one is different? How is it different?', a: 'The ___ one is different because ___.', src: '5쪽 Picture Talk', nt: '그림 이야기', n: ['노란 튤립 속 빨간 튤립 한 송이 — 오늘의 낱말 unique 로 이어집니다'] },
      { t: 'rule', k: 'fix', title: 'What does "unique" mean?', left: { h: 'Not unique', ex: ['There are **many** like it.', 'Every pencil in the box is **the same**.'] }, right: { h: 'Unique ⭐', ex: ['It is **one of a kind**.', '**No other** thing is exactly like it.'] }, q: 'Are you unique? Why?', src: '6쪽', nt: '규칙 찾기 — unique', n: ['원본 설명 «A unique thing is one of a kind … Every person is unique.» 를 두 묶음으로', '마지막 질문 답: «Yes! Every person is unique.»'] },
      PASSIVE_RULE('7·8쪽 Grammar'),
      { t: 'story', k: 'fix', small: 'Great minds ①', title: 'Google', img: '19273', lines: [['Teacher', 'Larry Page and Sergey Brin met at Stanford.'], ['Teacher', 'They left their studies to start Google.'], ['Student', 'Now it is the most popular search engine!']], src: '10쪽', nt: '위대한 생각 ① — 구글', n: ['❗ <del>never finished university</del> → left their studies(둘 다 학사는 마침 — 끝 목록)', "<del>What's another search engine do you use</del> → What other search engine do you use"] },
      { t: 'guess', k: 'fix', img: G('wavy-building'), open: [0, 4], q: 'He tried three jobs before he studied this. What is his job?', chips: ['an architect', 'a chef', 'a pilot'], src: '11쪽', nt: 'Guess who — 건축가', n: ['캐나다 출신 건축가 프랭크 게리 — 얼굴 대신 물결 모양 건물로', '맞히면: «The concert hall was designed by Frank Gehry.»'] },
      { t: 'story', k: 'fix', small: 'Great minds ②', title: 'A child prodigy', img: G('cellist-kid'), lines: [['Teacher', 'Yo-Yo Ma is a famous cellist. He was born in Paris to Chinese parents.'], ['Teacher', 'He was a child prodigy, like Mozart.'], ['Teacher', 'At the age of seven, he played for the president of the United States!'], ['Student', 'Wow! What were you doing at seven?']], src: '12쪽', nt: '위대한 생각 ② — 첼리스트', n: ['<del>French American</del> → 파리에서 중국계 부모에게서 태어남(사실대로)', '마지막 대사로 학생에게 «일곱 살 때 나는?» 묻기'] },
      { t: 'guess', k: 'fix', img: '16287', open: [2, 6], q: 'He created Spider-Man and the Hulk. Who is he?', chips: ['Stan Lee', 'Bill Gates', 'Frank Gehry'], src: '13쪽', nt: 'Guess who — 만화 영웅을 만든 사람', n: ['영화 속 깜짝 출연(cameo) 이야기로 웃음', '맞히면: «Spider-Man was created by Stan Lee.»'] },
      { t: 'ox', k: 'keep', img: '19453', s: 'Mark Zuckerberg made Facebook blue because it is the best color he can see.', src: '14쪽', nt: '⭕❌ 저커버그', n: ['정답 ⭕ — 적록색약이라 파랑이 가장 잘 보인다고', '«Do you think his fashion is simple? Why?»'] },
      { t: 'qa', k: 'fix', img: '12586', title: 'Bill Gates', q: 'He started Microsoft. How much money does he make?', a: 'He makes about ___ dollars every second!', chips: ['250'], src: '15쪽', nt: '빌 게이츠', n: ['❗ <del>Richest man in the world</del> → one of the richest people(지금은 사실이 아님)', '«$250 per second ≈ $20 million a day» — 수동태로: «Microsoft was started by Bill Gates.»'] },
      { t: 'memory', k: 'new', title: 'Who made it?', items: ['19273', G('wavy-building'), G('cellist-kid'), '16287', '19453', '12586'], hidden: 5, q: 'Look for 10 seconds. What is gone?', a: 'The computer! Microsoft was started by Bill Gates.', nt: '기억 게임', n: ['사라진 것을 맞히면 수동태 문장으로 누가 만들었는지'] },
      { t: 'discuss', k: 'fix', img: '18171', small: 'More great minds', title: 'Nelson Mandela · Mahatma Gandhi · Oprah Winfrey', qs: ['What do you know about them?', 'How is each person unique?', 'Who is the most passionate? The most persuasive?'], src: '16~18쪽 More people', nt: '더 알아보기', n: ['원본 인물 쪽 셋을 한 쪽 질문으로 — 모르면 강사가 한 줄씩 소개'] },
      { t: 'yourturn', k: 'keep', img: '12005', title: 'Your turn!', lines: ['Which great mind are you most like? Why?', 'If you could meet one of them, who would you meet?', 'What would you ask?'], chips: ['If I could meet ___, I would ask ___.'], src: '19쪽 More questions', nt: '내 말로', n: ['두 번째·세 번째 질문은 가정법 틀로'] },
      ...close([['I can explain what "unique" means.', 'unique 의 뜻을 설명할 수 있어요.'], ['I can talk about people with great minds.', '생각이 큰 사람들에 대해 말할 수 있어요.'], ['I can say which great mind I would like to meet.', '만나고 싶은 사람과 그 이유를 말할 수 있어요.']], { img: G('cover-009'), q: 'What will Ella be in the future?', ko: '다음 시간: 엘라의 발표 — 나의 꿈과 재능' }),
    ] },

  // ───────────────────────── 009
  { code: '009', tab: '나의 재능', unit: U3, title: "Ella's Speech", orig: 23,
    intro: '엘라가 영어 수업에서 발표합니다. 잘하는 과목·취미·꿈(엔지니어? 건축가?). 나도 «잘하는 것·하고 싶은 것·꿈의 직업» 을 말해 봅니다.',
    fixed: ['<del>I\'m still in some areas</del> → I\'m still exploring some areas (빠진 낱말)', '<del>on my own then when I do then in class</del> → on my own than when I do them in class', '<del>these stuff</del> → this stuff · <del>there\'s a lot of things</del> → there are a lot of things', '<del>prodigy 비범</del> → 신동 · <del>area 지역</del> → 분야 · <del>athlete 육상경기선수</del> → 운동선수 · <del>set of standards 표준세트</del> → 정해진 기준 · <del>professional 직업적인</del> → 프로의', '«Explain» 사진 6쪽(하나만 다른 것) → Guess·O/X 게임으로'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-009'), q: 'What are you good at?', story: 'Ella gives a speech to her class.', nt: '표지 + Big Question' },
      ...open([['I can talk about my strengths.', '내가 잘하는 것을 말할 수 있어요.'], ['I can talk about my dream job.', '꿈의 직업을 말할 수 있어요.'], ['I can explain what makes something unique.', '무엇이 특별한지 설명할 수 있어요.']], 'Lesson Goals (Suffixes · Subjunctive mood)'),
      { t: 'vocab', k: 'fix', hide: true, title: "Ella's words 🔒", cols: 4, words: [['prodigy', '신동', G('cellist-kid')], ['area', '분야', '16738'], ['athlete', '운동선수', '12785'], ['professional', '프로의', '12656'], ['on my own', '혼자 힘으로', G('ella-models')], ['set of standards', '정해진 기준', '18420'], ['design', '설계하다', '12902'], ['outstanding', '뛰어난', '12005']], src: '5쪽 Vocabulary', nt: '낱말 — 뜻 가리고', n: ['원본 뜻 다섯 개를 문맥에 맞게 고쳤습니다(위 fixed)'] },
      SUFFIX_RULE('6쪽 Suffix'),
      { t: 'read', k: 'fix', small: "Ella's speech ①", title: 'My Future', img: G('ella-speech'), paras: ["I'm not sure I'll be famous one day, but I dream about it. Many famous people started practicing when they were young. They were called prodigies.", "I'm interested in many things, and I'm still exploring. My best subjects are math and science. My test scores are usually outstanding."], gloss: [['exploring', '알아보는 중인']], src: '7쪽 Story ①', nt: '읽기 ① — 잘하는 과목', n: ["<del>I'm still in some areas</del> → I'm still exploring some areas(원본에 낱말이 빠짐)", '«They were called prodigies.» 수동태 짚기'] },
      { t: 'read', k: 'fix', small: "Ella's speech ②", title: 'My Future', img: '12656', paras: ["My performance in gym class is average. I don't think I'll ever be an athlete. In music class, I can play the guitar, but I don't think I'll be a professional guitarist.", 'My grades in other subjects are okay, but my social studies grade is a little low.'], gloss: [['average', '보통의'], ['grade', '성적']], src: '8쪽 Story ①', nt: '읽기 ② — 약한 과목', n: ['엘라가 약한 것도 솔직하게 말한다는 점을 짚어 줍니다'] },
      { t: 'read', k: 'fix', small: "Ella's speech ③", title: 'My Future', img: G('ella-models'), paras: ["I'm very creative. At home, I paint and build models! I enjoy them more on my own than in class, because I don't need to follow a set of standards.", "I'm good at math, so I could be an engineer or an architect. Engineers build machines, and architects design buildings. Maybe I can design toys, too!"], gloss: [['architect', '건축가']], src: '9·10쪽 Story ②', nt: '읽기 ③ — 꿈', n: ['<del>then … then</del> → than … them · <del>these stuff</del> → this stuff · <del>there\'s a lot</del> → there are', '<del>architects design models</del> → design buildings(건축가의 일)'] },
      { t: 'fill', k: 'keep', img: G('ella-speech'), title: 'Questions', lines: ["Ella's best subjects: ___ and science.", 'At home, she paints and builds ___.', 'She could be an ___ or an architect.'], chips: ['math', 'models', 'engineer', 'athlete'], src: '11쪽 Follow-up', nt: '이야기 질문', n: ['athlete 는 함정 칩(엘라는 운동선수는 아니라고 함)'] },
      { t: 'ox', k: 'new', img: '12785', s: 'Ella thinks she will be a great athlete.', nt: '⭕❌ 이야기 확인', n: ['정답 ❌ → «No! Her gym class performance is average.»'] },
      { t: 'discuss', k: 'keep', img: '12902', title: 'Think about Ella', qs: ['What does she like to do outside school?', 'What jobs could she have in the future?', 'How could being an architect or an engineer let her do both math and design?'], src: '12쪽 Follow-up', nt: '생각 질문', n: ['마지막 질문은 어려우면 «Architects use math and design.» 틀을 줍니다'] },
      { t: 'guess', k: 'fix', img: G('odd-ball'), open: [0, 4, 8], q: 'Which one is unique? Explain!', chips: ["It's unique because it's the only ___ one."], src: '13~18쪽 Explain', nt: 'Guess — 하나만 다른 것', n: ['원본 «Explain» 6쪽(파란 공·빨간 큐브·빨간 튤립·파란 폰·켜진 전구·깎은 연필)을 타일 게임 하나 + 짝짓기로', '«It\'s unique because it\'s the only …» 로 말하기'] },
      { t: 'match', k: 'fix', title: 'Explain! Why is it unique?', left: [G('red-tulip'), G('odd-bulb'), G('odd-pencil'), G('odd-ball')], right: ["It's the only one that is lit.", "It's the only sharpened one.", "It's the only blue one.", "It's the only red one."], src: '13~18쪽 Explain', nt: '짝짓기 — 특별한 이유', n: ['사진 ↔ «the only …» 이유 짝짓기'] },
      { t: 'scramble', k: 'new', title: 'Dream jobs!', items: [['e-g-n-i-e-n-r-e', '16477'], ['c-t-i-r-a-h-t-e-c', '12779'], ['s-i-c-t-n-t-i-e-s', '12502'], ['h-e-a-l-t-t-e', '12785']], nt: '글자 조각 맞추기 — 직업', n: ['정답 engineer · architect · scientist · athlete — 맞히면 «I want to be … because …»'] },
      { t: 'yourturn', k: 'keep', img: '15815', title: 'Questions for you!', lines: ['What are you good at?', 'What do you like to do?', "What's your dream job? Why?"], chips: ["I'm good at ___.", 'I like to ___.', 'I want to be ___.'], src: '19쪽', nt: '내 말로 — 나의 발표', n: ['엘라처럼 세 줄 발표 — 약한 것도 하나 말해 보기'] },
      CHANT('마지막 쪽 노래'),
      ...close([['I can talk about my strengths.', '내가 잘하는 것을 말할 수 있어요.'], ['I can talk about my dream job.', '꿈의 직업을 말할 수 있어요.'], ['I can explain what makes something unique.', '무엇이 특별한지 설명할 수 있어요.']], { img: G('cover-review'), q: 'Can you remember all the inventions?', ko: '다음 시간: BTS 25 복습 — 발명 박물관 여행' }),
    ] },

  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'The Invention Museum', orig: 26,
    intro: '세 단원을 «발명 박물관» 세 방으로 돌며 복습합니다: ① 소통 기술 방 ② 편한 삶 방 ③ 큰 생각 방. 원본 복습 쪽을 새 사진·게임으로 바꿨습니다.',
    fixed: ['원본은 앞 과 쪽을 그대로 다시 실음 → 같은 내용을 새 사진·게임으로(복습은 일부러 다른 사진)', '앞 과에서 고친 오류(Adler · passion for · artists steal 등)를 복습에서도 고친 모양으로', '운전 중 지도 사진 → 대시보드 GPS'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-review'), q: 'Welcome to the Invention Museum!', story: 'Three rooms. Can you finish the tour?', nt: '표지', n: ['박물관 세 방 = 세 단원. 방마다 게임을 통과하면 도장'] },
      ...open([['I can talk about inventions and how they help us.', '발명과 그 쓸모를 말할 수 있어요.'], ['I can use the passive and "If I didn\'t have …".', '수동태와 가정법을 쓸 수 있어요.'], ['I can describe great minds.', '생각이 큰 사람들을 묘사할 수 있어요.']], 'Review Goals'),
      { t: 'fill', k: 'fix', small: 'Room 1 · Communication', title: 'Remember?', img: '13261', lines: ['She writes letters to her family. She needs a pen, paper, an envelope and a ___.', 'They like to talk ___ and hang out together.'], chips: ['stamp', 'face to face'], src: '1·2쪽', nt: '빈칸 복습', n: ['001 편지·친구 쪽 — 다른 사진으로'] },
      { t: 'match', k: 'fix', small: 'Room 1', title: 'Match the invention!', left: ['16619', G('telegraph'), '20013', '19273'], right: ['the internet', 'the printing press', 'the telegraph', 'the telephone'], src: '3~5쪽', nt: '짝짓기', n: ['맞힐 때마다 수동태: «The telegraph was invented by Samuel Morse.»'] },
      { t: 'order', k: 'new', small: 'Room 1', img: '16480', words: ['The', 'printing', 'press', 'was', 'developed', 'by', 'Gutenberg.'], nt: '순서 맞추기', n: ['정답: The printing press was developed by Gutenberg.'] },
      { t: 'ox', k: 'fix', small: 'Room 1', img: '19630', s: 'Whispering is a good way to talk to a big group.', src: '2쪽', nt: '⭕❌', n: ['정답 ❌ → «No! Whispering is for one person. It\'s quiet.»'] },
      { t: 'story', k: 'new', small: 'Room 1', title: 'Michael and Gina', img: '18076', lines: [['Michael', 'Gina, I heard your speech!'], ['Gina', "Thanks! I'd be lost without my phone."], ['Michael', 'Zander finally bought one!'], ['Gina', 'Did he bring a lot of money?']], nt: '이어지는 이야기 — 인물이 만나요', n: ['001·003 인물이 만나는 새 장면 — 앞 이야기를 기억해야 웃을 수 있습니다'] },
      { t: 'table', k: 'fix', small: 'Room 2 · Easy life', title: 'Automatic or manual?', head: ['invention', 'automatic / manual', 'It helps us …'], rows: [['a robot vacuum', '___', 'clean the floor.'], ['a hand fan', '___', 'cool down.'], ['GPS', '___', 'find the way.'], ['a pair of scissors', '___', 'cut paper.']], src: '6~8쪽', nt: '표 채우기', n: ['정답 automatic · manual · automatic · manual'] },
      { t: 'guess', k: 'new', small: 'Room 2', img: G('velcro'), open: [1, 7], q: 'What is it? Where did the idea come from?', chips: ['velcro', 'sticky seeds', 'It was invented in 1941.'], nt: 'Guess what', n: ['005 벨크로 복습 — 아이디어의 출처(달라붙는 씨앗)까지'] },
      { t: 'story', k: 'new', small: 'Room 2', title: 'Carmel is back!', img: '16405', lines: [['Nate', 'Carmel! You look great today.'], ['Carmel', 'I bought a washing machine! My clothes are washed for me.'], ['Carmel', "If I didn't have it, I'd be exhausted again!"]], nt: '이어지는 이야기 — 카멜의 결말', n: ['004 이야기의 뒷이야기 — 수동태(are washed) + 가정법을 한 장면에'] },
      { t: 'fill', k: 'fix', small: 'Room 2', title: 'Quote of the Day', img: '18191', lines: ['"Technology is a useful ___, but a dangerous ___."', 'I agree / disagree because ___.'], chips: ['servant', 'master'], src: '9쪽', nt: '명언 복습', n: ['006 명언 — 빈칸 뒤 내 생각까지'] },
      { t: 'vocab', k: 'fix', hide: true, small: 'Room 3 · Great minds', title: 'Who is it? 🔒', cols: 4, words: [['imaginative', '상상력이 풍부한', '12397'], ['intuitive', '직관적인', '12265'], ['persuasive', '설득력 있는', '16400'], ['passionate', '열정적인', '14668']], src: '10·11쪽', nt: '낱말 — 뜻 가리고', n: ['뜻 대신 «이런 사람은 무엇을 잘할까?» 를 먼저 말하게'] },
      { t: 'fill', k: 'fix', small: 'Room 3', title: 'Suffix swap!', lines: ['She is very ___. (create)', 'He has a great ___. (imagine)', 'Thank you! That was very ___. (use)'], chips: ['creative', 'imagination', 'useful'], nt: '접미사 복습', n: ['괄호 속 뿌리 낱말을 문장 자리에 맞게 바꾸기'] },
      { t: 'memory', k: 'new', small: 'Room 3', title: 'Who made it?', items: ['12783', G('wizard-book'), '16287', '19453', G('wavy-building'), '19273'], hidden: 2, q: 'Look for 10 seconds. What is gone?', a: 'The superheroes! They were created by Stan Lee.', nt: '기억 게임', n: ['008 인물들 — 사라진 것을 수동태 문장으로'] },
      { t: 'ox', k: 'fix', small: 'Room 3', img: G('odd-bulb'), s: 'This light bulb is unique because it is the only one that is not lit.', src: '16쪽', nt: '⭕❌ unique', n: ['정답 ❌ → «It\'s the only one that IS lit.»'] },
      { t: 'yourturn', k: 'new', small: 'Room 3', img: '15815', title: 'Last room!', lines: ['What makes you unique?', 'Which great mind would you like to meet? Why?', 'What would you invent?'], chips: ['If I could invent anything, I would invent ___.'], nt: '내 말로 — 마지막 방', n: ['세 방을 다 돌면 박물관 도장 완성'] },
      ...close([['I can talk about inventions and how they help us.', '발명과 그 쓸모를 말할 수 있어요.'], ['I can use the passive and "If I didn\'t have …".', '수동태와 가정법을 쓸 수 있어요.'], ['I can describe great minds.', '생각이 큰 사람들을 묘사할 수 있어요.']], { img: G('cover-test'), q: 'Are you ready for the test?', ko: '다음 시간: BTS 25 단원 시험' }),
    ] },

  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 25 Unit Test', orig: 9,
    intro: '10문항 + 마지막 질문. 모두 «말로 답하는» 문항입니다. 두 문장 이상(이유 포함)으로 답하면 1점.',
    fixed: ['<del>What do you do without it?</del> → What would you do without it?', '<del>everyday</del> → every day (마지막 질문)', '8번 실존 인물 얼굴 사진 → «한 일» 사진 + 글자 단서'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-test'), q: 'Test time! You can do it! 💪', story: '10 questions · Answer in full sentences!', nt: '표지' },
      { t: 'discuss', k: 'keep', img: '18073', title: '1–3. Communication', qs: ['1. How does he communicate?', '2. What is the best way to communicate with people? Why?', '3. Do you like to write letters? Why or why not?'], src: '문항 1~3', nt: '문항 1~3', n: ['원본 세 쪽(전화하는 사람 · 가장 좋은 방법 · 글쓰기)을 한 쪽에', '한 문항씩 가리고 차례로 묻습니다'] },
      { t: 'qa', k: 'keep', img: '14171', title: '4.', q: 'How is this technology automatic?', a: 'It ___ by itself. It saves ___.', src: '문항 4', nt: '문항 4 — 로봇청소기' },
      { t: 'discuss', k: 'keep', img: '12076', title: '5–7. Minds and ideas', qs: ['5. Who in your family is creative? Why?', '6. What does "intuition" mean? When can we use it?', '7. What can a persuasive person do when she speaks?'], src: '문항 5~7', nt: '문항 5~7' },
      { t: 'qa', k: 'fix', img: '19453', title: '8.', q: 'He created a social networking site, and he likes blue. Who is he? What did he create?', a: 'He is ___. He created ___.', src: '문항 8', nt: '문항 8', n: ['원본 얼굴 사진 → 소셜 미디어 사진 + 글자 단서(정답 Mark Zuckerberg · Facebook)'] },
      { t: 'discuss', k: 'fix', img: '19431', title: '9–10. Best inventions', qs: ['9. What is the best invention ever? What would you do without it?', '10. What other features would you add to smartphones?'], src: '문항 9·10', nt: '문항 9·10', n: ['<del>What do you do without it?</del> → What would you do without it?'] },
      { t: 'yourturn', k: 'fix', img: '18543', title: 'Final question', lines: ['What would you like to invent to help you every day?', 'How would it work?'], src: '마지막 쪽', nt: '마지막 질문', n: ['<del>everyday</del> → every day', '발명품 이름을 지어 주면 보너스 점수'] },
      { t: 'table', k: 'new', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–3', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['4–6', 'Good job!', '이유(because)까지 말해 봐요'], ['7–9', 'Great!', '수동태·가정법을 한 번 더'], ['10 ⭐', 'Congratulations!', 'BTS 26 으로 출발! 🎉']], nt: '점수표', n: ['점수마다 다음 할 일을 함께'] },
      { t: 'next', k: 'new', img: G('next-26'), q: 'Where do polar bears live? Why can camels live in the desert?', ko: 'BTS 26 은 «동물과 서식지» — 다음 권에서 만나요!', nt: '다음 권 예고', n: ['BTS 26 첫 과(Animals in their habitats) 예고'] },
    ] },
  ],
};

