// BTS 33 새 교재 설계 데이터. k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
// 사진 번호 = photo-catalog.json · gen:bts-33-* = 새로 만들 사진(gen/req-bts-33.json)
import { open, close } from '../common.mjs';

const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3', U4 = 'Unit 4';
const G = (x) => 'gen:bts-33-' + x;

// 원본은 노래 쪽이 없고 Warm up 이 사진 질문뿐 → 단원마다 주제 챈트(자체 가사)
const CH1 = { t: 'song', k: 'new', title: 'Game On Chant 🎮', img: G('chant-games'), lines: ['Build a city, stack the blocks,', 'Solve a puzzle, beat the clock!', 'Play with friends across the sea —', 'Just one more level, then homework for me!'], nt: '게임 챈트', n: ['자체 가사 — strategy(Build a city) · puzzle · 온라인 멀티플레이 · level 이 한 번씩 나옵니다', '마지막 줄은 «게임 시간 조절» 토론으로 이어지는 복선'] };
const CH2 = { t: 'song', k: 'new', title: 'Make a Hit Chant 🎤', img: G('chant-music'), lines: ['Hum the melody, tap the beat,', 'Write the lyrics, move your feet!', 'Shoot a music video, play it on the radio —', 'Now it\'s a hit! Everybody, go!'], nt: '음악 챈트', n: ['자체 가사 — melody · rhythm(beat) · lyrics · music video · hit 을 노래로 먼저', '원본 읽기의 «Kung Fu Fighting» 가사는 옮기지 않았습니다(저작권)'] };
const CH3 = { t: 'song', k: 'new', title: 'Good Sport Chant ⚽', img: '15516', lines: ['Pass the ball and play as a team,', 'There is no I in the word «team»!', 'Win or lose, shake hands and smile —', 'A good sport plays with style!'], nt: '스포츠 챈트', n: ['자체 가사 — teamwork · sportsmanship 핵심 문장 «There is no I in team» 을 노래로'] };
const CH4 = { t: 'song', k: 'new', title: 'Ride the City Chant 🚇', img: G('chant-transport'), lines: ['Take the bus — it costs less.', 'Take a taxi — it\'s comfortable, yes!', 'Take the subway, fast and far,', 'But beep, beep! I\'m stuck in a car!'], nt: '교통 챈트', n: ['자체 가사 — cost · comfort · 교통수단 비교와 traffic jam 을 노래로'] };

const G1 = [['I can talk about kinds of computer games.', '컴퓨터 게임 종류를 말할 수 있어요 — strategy, first-person shooter, puzzle.'], ['I can ask and answer Wh- and Yes/No questions.', 'Wh- 질문과 Yes/No 질문을 주고받을 수 있어요.'], ['I can give my opinion about games.', '게임에 대한 내 생각을 말할 수 있어요 — I think puzzle games make us smarter.']];
const G2 = [['I can talk about songs and music videos.', '노래와 뮤직비디오를 말할 수 있어요 — melody, rhythm, lyrics.'], ['I can ask "Would you rather …?"', '«…하는 게 더 좋아, 아니면 …?» 를 물을 수 있어요.'], ['I can tell how a song becomes a hit.', '노래가 어떻게 히트곡이 되는지 말할 수 있어요.']];
const G3 = [['I can talk about teamwork and sportsmanship.', '팀워크와 스포츠맨십을 말할 수 있어요.'], ['I can say what players should and shouldn\'t do.', '선수가 해야 할 일과 하면 안 되는 일을 말할 수 있어요 — Players shouldn\'t fight.'], ['I can say how I would feel in a game.', '경기 상황에서 내 기분을 말할 수 있어요.']];
const G4 = [['I can compare kinds of transportation.', '교통수단을 비교할 수 있어요 — cost, comfort, convenience.'], ['I can use more … than and as … as.', '비교하는 말을 할 수 있어요 — Taxis are more comfortable than buses.'], ['I can talk about traffic problems in a city.', '도시의 교통 문제를 말할 수 있어요 — traffic jams, smog.']];

export const COURSE = {
  head: `<h1>BTS 33 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트의 BTS 33 원본 <b>155쪽</b>(6묶음: 001~003 · 004~006 · 007~009 · 010~012 · Review · Test)을 한 장씩 읽고, 제안서 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · «I can» · 다음 시간 예고)으로 다시 짰습니다. 레벨 8 — 주제는 <b>우리가 즐기는 세상</b>: ① 컴퓨터 게임 ② 대중음악 ③ 프로 스포츠 ④ 대중교통. 문법은 원본 그대로 Wh- 질문 · Yes/No 질문 · 1~7단계 문법 복습이고, 과마다 한 가지를 «규칙 찾기» 로 세웠습니다(Wh-/Yes-No · Would you rather · should/shouldn't · more … than / as … as).</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>원본의 <b>낱말·키워드 글·생각 질문·읽기 글 전부</b>(StarCraft in Asia · Eve · The Strange World of Show Business · One-hit Wonders · Brawls in American Baseball · Transportation in Beijing and Los Angeles · Unique Transportation)와 롤플레이 세 상황, Review 의 낱말 40개, Test 20문항을 모두 담았습니다. 원본의 오타·문법 오류·어색한 뜻·도시 이름이 뒤섞인 글(Beijing ↔ Seoul)·사진과 안 맞는 문제는 고쳤습니다(과마다 목록).</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>, <b>⭕❌</b>, <b>Guess who</b>(사진 조각 맞히기), <b>기억 게임·짝 맞추기·순서 맞추기·단어 섞기</b>, 네 과를 잇는 <b>Yoona 와 Jay 의 이야기</b>(게임 대회 → 학교 밴드 → 축구 준결승 → 지하철 견학), <b>I can ✅</b>, <b>다음 시간 예고</b>를 넣었습니다. «와!» 가 나오는 실사 사진(e스포츠 경기장의 함성·꽃가루 날리는 콘서트·헤딩 슛·자기부상열차·인력거·시클로)을 새로 요청했습니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>점선 상자(«새 사진 생성 중»)는 새로 만들 사진 <b>40장</b>(gen/req-bts-33.json)입니다. 원본의 <b>실존 인물 사진</b>(Guess who 의 가수 PSY, 경기 중 실제 축구 선수들), <b>총·군인·복면에 방망이</b> 사진, 뜻과 안 맞는 사진(«strategy» 에 퍼즐 조각, «semifinals» 에 달리기 출발, «public transportation» 에 자동차 정체, «rapid transit» 에 고속철, «stand still» 에 요가)은 모두 바꿨습니다.</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>원본의 사실 확인</b> — ① 001~003 Eve(김시윤, 2011년 7월 Slayers 입단)·«프로 12팀»·«수억 원 연봉»·«관중 10만 명 이상, 어떤 프로 경기보다 많다» 는 2010년대 초 기준이라 지금과 다릅니다. 새 교재는 «In the 2000s and 2010s …» 처럼 과거 이야기로 두었습니다. ② 004~006 Mariah Carey 예시 «다른 작곡가 곡은 쓰지 않는다» 는 사실과 다릅니다(공동 작곡이 많음) → «She writes many of her own songs» 로 줄였습니다. ③ 010~012 베이징 지하철 수치(23개 노선·세계 2위 길이)와 LA 승객 수는 2019년 무렵 자료입니다 → «about» 을 붙였고, 최신 수치로 바꿀지 결정이 필요합니다.</li>
<li><b>한쪽 성별 고정관념 문장</b> — 001~003 «video games just seem to be more exciting to boys than girls» 는 원본 필자의 단정이라 «Some people think …» 로 바꿔 토론 질문으로 돌렸습니다. 이대로 둘지.</li>
<li><b>폭력 표현 수위</b> — FPS 설명 «shoots guns … to kill enemies», 낱말 violent 의 뜻 «…죽이다», 야구 난투 «punching and wrestling» 은 초등~중등 화상수업이라 «tag/defeat enemies», «fight» 로 순화했습니다. 원문 그대로 가야 한다면 알려 주세요.</li>
<li><b>원본 사진 교체</b> — 실존 인물(PSY · 실제 축구 선수), 총·군인·복면 사진, 뜻과 안 맞는 Review 사진 12장 → 새 사진으로. 원본 사진을 살릴지.</li>
<li><b>노래 저작권</b> — 원본에는 노래 쪽이 없고, 004~006 에 «Kung Fu Fighting» 음원 링크가 있었습니다. 가사는 옮기지 않고 «들어 보고 왜 히트했을까?» 질문만 남겼습니다(음원 재생 여부는 강사 판단). 단원마다 새 챈트 4편을 넣었습니다.</li>
<li><b>글 제목과 내용이 어긋난 곳</b> — 010~012 제목은 «Transportation in Seoul and Los Angeles» 인데 글은 Beijing 이고, 뒤쪽에 «Seoul» 이 두 번 섞여 있었습니다 → 전부 Beijing 으로 맞췄습니다. 서울 버전을 원했던 것인지 확인이 필요합니다.</li>
<li><b>새로 만들 사진 40장</b>(힉스필드 크레딧) — 표지·이야기 인물·Guess who·원본 사진 교체·원본에 없던 탈것(자기부상열차·모노레일·인력거·시클로·수상버스).</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001-003
  { code: '001-003', tab: '컴퓨터 게임', unit: U1, title: 'Computer Games', orig: 28,
    intro: '게임 종류(strategy · first-person shooter · MMO · puzzle)를 배우고 Wh-/Yes-No 질문으로 서로의 게임 습관을 묻습니다. 읽기: 아시아의 StarCraft 열풍과 첫 여성 프로게이머 Eve. 이야기: Yoona 와 Jay 가 학교 게임 대회에 나갑니다.',
    fixed: ['뜻 «좌절» → 좌절감을 주는 · «파괴» → 파괴하는 · «가상 현실» → 가상 세계 · «정체» → 정체성 · «인칭 슈터» → 1인칭 슈팅 게임 · «레벨» → 게임의 한 단계', '«Why do like them?» · «Why do think so?» → Why do you like them? / Why do you think so?', '«Chess is strategy game» → Chess is a strategy game · «other player\'s armies» → other players\' armies', '«MMO games that do not contain a role playing component» → role-playing', '«one of the most wired continent» → continents · «popular around the country» → around the region', '«as a pretty face» 비판 문장 → «only because of her looks» 로 쉽게 · «amateur- they want» 구두점 정리', 'gloss «valuable = worth money» → 소중한(팀에 큰 도움이 되는) · amateur tournament 깨진 뜻풀이 정리', '«Try it: … this same» → this game', '폭력 표현 «kill enemies» → defeat enemies(순화)', 'General Information 쪽 삭제(강사 메모로)'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-esports'), q: 'Why do thousands of people watch other people play games?', story: 'Yoona and Jay enter the school game tournament! 🎮', nt: '표지 + Big Question', n: ['경기장 스크린 앞에서 환호하는 관중 사진 — «Have you ever watched a game match?» 를 먼저', '끝날 때 «I think people watch games because ___» 로 말하는 것이 목표'] },
      ...open(G1, 'Lesson Goals (Unit 1)'),
      CH1,
      { t: 'discuss', k: 'fix', img: '17267', small: 'Warm up', title: 'Let\'s talk about games', qs: ['What is your favorite platform — computers, smartphones or consoles?', 'How much time do you spend playing games? When do you play?', 'Are games a waste of time or a good way to relieve stress?'], src: 'Starter Questions', nt: '준비 질문', n: ['원본 질문 4개 중 3개 — «favorite game and why» 는 이야기 뒤 내 차례에서', '원본 사진(콘솔·태블릿·컴퓨터)과 같은 뜻의 사진'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Game words 🎮', words: [['platform', '플랫폼(게임기·기계)', '15293'], ['strategy', '전략', '16272'], ['frustrating', '좌절감을 주는', '19420'], ['destroying', '파괴하는', '18850'], ['armies', '군대', G('toy-armies')], ['weapons', '무기', '20273']], src: 'Vocabulary', nt: '게임 낱말 ① — 뜻 가리기', n: ['사진만 보고 영어로 먼저', '<del>좌절</del> → 좌절감을 주는 · <del>파괴</del> → 파괴하는(-ing 형)', '원본 군인·총 사진 → 장난감 병정 · 박물관 갑옷 무기(아이 수업)'] },
      { t: 'vocab', k: 'fix', title: 'Game words 🎮', words: [['platform', '플랫폼(게임기·기계)', '15293'], ['strategy', '전략', '16272'], ['frustrating', '좌절감을 주는', '19420'], ['destroying', '파괴하는', '18850'], ['armies', '군대', G('toy-armies')], ['weapons', '무기', '20273']], nt: '뜻 공개', n: ['destroying: 블록 탑이 무너지는 순간 — «Was it frustrating?» 로 두 낱말을 잇기'] },
      { t: 'vocab', k: 'fix', title: 'More game words 🌐', words: [['level', '(게임의) 한 단계', '12108'], ['virtual world', '가상 세계', G('virtual-world')], ['identity', '정체성·다른 나', '21013'], ['first-person shooter', '1인칭 슈팅 게임', G('gaming-headset')], ['puzzle games', '퍼즐 게임', '17260']], src: 'Vocabulary (2)', nt: '게임 낱말 ②', n: ['<del>가상 현실</del> → 가상 세계 · <del>정체</del> → 정체성 · <del>인칭 슈터</del> → 1인칭 슈팅 게임', '원본 «Level 5» 층 표지판 사진은 뜻이 달라(건물 층) 바꿨습니다'] },
      { t: 'rule', k: 'fix', title: 'Wh- or Yes/No?', left: { h: 'Wh- question → new information', ex: ['**What** is your favorite game?', '**When** do you play games?', '**Why** do you like it?'] }, right: { h: 'Yes/No question → yes or no', ex: ['**Do** you play puzzle games?', '**Is** chess a strategy game?', '**Have** you ever played online?'] }, q: 'Which questions can you answer with just "Yes" or "No"? What comes first in each one?', src: 'Grammar: Wh- questions · Yes/No questions', nt: '규칙 찾기', n: ['원본 목표의 문법 두 가지를 한 쪽에서 비교', 'Yes/No 질문은 Do · Is · Have 로 시작 — 학생이 먼저 찾게'] },
      { t: 'read', k: 'fix', img: '14026', small: 'Keyword', title: 'Strategy Games ♟️', paras: ['In strategy games, players build buildings, cities and armies. They win by destroying the other players\' armies and cities.', 'Chess is a strategy game, too. Some people find strategy games boring or frustrating.'], gloss: [['win by', '~해서 이기다']], src: 'Keyword: Strategy games', nt: '키워드 ① 전략 게임', n: ['<del>Chess is strategy game</del> → Chess is a strategy game · <del>other player\'s</del> → other players\''] },
      { t: 'discuss', k: 'keep', img: '15010', small: 'Think about it', title: 'Strategy games', qs: ['What strategy games are popular in your country?', 'Do you like them? Why or why not?'], src: 'Think about it (strategy)', nt: '생각 질문 ①' },
      { t: 'read', k: 'fix', img: G('gaming-headset'), small: 'Keyword', title: 'First-Person Shooter 🎯', paras: ['In a first-person shooter (FPS), the player controls one character and moves around a level.', 'The character uses tools and weapons to defeat enemies.', 'It is called "first-person" because the player sees the game through the character\'s eyes.'], gloss: [['defeat', '물리치다'], ['through … eyes', '~의 눈으로']], src: 'Keyword: FPS', nt: '키워드 ② FPS', n: ['원본 «shoots guns … to kill enemies» → defeat enemies 로 순화(사람이 정할 것 3)'] },
      { t: 'discuss', k: 'keep', img: '12174', small: 'Think about it', title: 'FPS games', qs: ['What FPS games do you know? Are they fun or exciting?', 'Some adults say FPS games are too violent. Do you agree? What do your parents say?'], src: 'Think about it (FPS)', nt: '생각 질문 ②' },
      { t: 'read', k: 'fix', img: G('virtual-world'), small: 'Keyword', title: 'Massively Multiplayer Online (MMO) 🌍', paras: ['An MMO game connects thousands of players, usually through the Internet.', 'They play together in a virtual world that keeps going even when you log off.', 'Some MMO games do not have a role-playing part.'], gloss: [['log off', '접속을 끝내다'], ['role-playing', '역할 놀이']], src: 'Keyword: MMO', nt: '키워드 ③ MMO', n: ['persistent virtual world → «a virtual world that keeps going» 로 풀어 씀', '<del>role playing component</del> → role-playing part'] },
      { t: 'discuss', k: 'keep', img: '21013', small: 'Think about it', title: 'MMO games', qs: ['Do you know any massively multiplayer online games?', 'Is it fun to have a different identity online? Why?'], src: 'Think about it (MMO)', nt: '생각 질문 ③' },
      { t: 'discuss', k: 'fix', img: '17260', small: 'Keyword · Puzzle games', title: 'Puzzle Games 🧩', qs: ['Puzzle games are especially popular on smartphones. Do you play them?', 'When do you play them? Why do you like them?', 'Do puzzle games make you smarter, or are they a waste of time? Why do you think so?'], src: 'Keyword: Puzzle games + Think about it', nt: '키워드 ④ 퍼즐', n: ['<del>Why do like</del> → Why do you like · <del>Why do think so</del> → Why do you think so'] },
      { t: 'match', k: 'new', title: 'Which kind of game?', left: ['16272', G('gaming-headset'), G('virtual-world'), '17260'], right: ['puzzle game', 'strategy game', 'MMO game', 'first-person shooter'], nt: '짝 맞추기', n: ['정답: 1-B · 2-D · 3-C · 4-A', '맞힌 뒤 Yes/No 질문 하나씩 — «Do you play it?»'] },
      { t: 'story', k: 'new', img: G('yoona-jay'), title: 'Yoona and Jay ①', lines: [['Yoona', 'Jay! The school game tournament is on Friday.'], ['Jay', 'What game is it?'], ['Yoona', 'A strategy game. We build a city and protect it.'], ['Jay', 'Cool! Can we be a team?']], nt: '이야기 ① — 네 과를 잇는 두 친구', n: ['Wh- 질문(What) 과 Yes/No 질문(Can we)이 한 번씩'] },
      { t: 'story', k: 'new', img: '18850', title: 'Yoona and Jay ②', lines: [['Jay', 'Oh no! They destroyed our walls again!'], ['Yoona', 'This is so frustrating!'], ['Jay', 'Let\'s try a new strategy. You build, and I protect.'], ['Yoona', 'Good idea. Teamwork!']], nt: '이야기 ② 연습', n: ['destroying · frustrating · strategy 를 이야기 속에서 다시', 'Teamwork 는 Unit 3 복선'] },
      { t: 'story', k: 'new', img: G('esports-crowd'), title: 'Yoona and Jay ③', lines: [['Teacher', 'And the winner is… Yoona and Jay!'], ['Jay', 'We did it! Did you hear the crowd?'], ['Yoona', 'Yes! Now I know why people watch games.']], nt: '이야기 ③ 우승', n: ['표지 Big Question 으로 돌아가기 — «Why do people watch games?»'] },
      { t: 'ox', k: 'new', img: G('yoona-jay'), s: 'Yoona and Jay played a puzzle game in the tournament.', nt: '⭕❌', n: ['정답 ❌ → «No. They played a strategy game.»'] },
      { t: 'read', k: 'fix', img: G('internet-cafe'), small: 'Let\'s read', title: 'StarCraft in Asia ①', paras: ['Asia is one of the most wired continents. Almost everyone has Internet access.', 'Many people play computer games to relieve stress.', 'In the 2000s, StarCraft by Blizzard became a runaway hit across the region.'], gloss: [['wired', '인터넷이 잘 연결된'], ['runaway hit', '폭발적인 인기작']], src: 'StarCraft in Asia', nt: '읽기 ① StarCraft (1)', n: ['<del>continent</del> → continents · <del>around the country</del> → across the region'] },
      { t: 'read', k: 'fix', img: G('esports-crowd'), small: 'Let\'s read', title: 'StarCraft in Asia ②', paras: ['StarCraft is a strategy game about three tribes of space aliens. People praised its graphics, story and game play.', 'Millions spent hours in Internet cafés. More than 100,000 fans came to some live tournaments!'], gloss: [['praised', '칭찬했다'], ['live tournament', '현장 대회']], src: 'StarCraft in Asia', nt: '읽기 ① StarCraft (2)', n: ['«replay it for hours» → spent hours', '프로 12팀·수억 원 연봉 문장은 강사 메모로 — 옛 자료(사람이 정할 것 1)'] },
      { t: 'read', k: 'fix', img: G('female-gamer'), small: 'Let\'s read', title: 'Is StarCraft only for boys?', paras: ['Most StarCraft fans were male. Some people think games are more exciting to boys. Is that true?', 'In July 2011, Kim Shi-Yoon became the first female professional StarCraft gamer. She was called "Eve" and joined the Slayers team.'], gloss: [['female', '여성의'], ['professional', '프로의']], src: 'Is StarCraft only for boys?', nt: '읽기 ② Eve', n: ['«more exciting to boys than girls» 단정 → «Some people think … Is that true?»(사람이 정할 것 2)'] },
      { t: 'read', k: 'fix', img: '12122', small: 'Let\'s read', title: 'A Team Sport', paras: ['Some critics said she was chosen only because of her looks. Her team said that was unfair.', 'They wanted to train an amateur into a star. They also hoped to encourage more girls to play.'], gloss: [['critics', '비판하는 사람들'], ['amateur', '아마추어(취미로 하는 사람)'], ['encourage', '용기를 주다']], src: 'StarCraft: A Team Sport', nt: '읽기 ③ 팀의 선택', n: ['«as a pretty face» → only because of her looks · «amateur- they want» 구두점 정리', 'gloss «valuable = worth money» 는 뜻이 달라 뺐습니다'] },
      { t: 'discuss', k: 'fix', img: G('esports-crowd'), title: 'Let\'s discuss', qs: ['Why was StarCraft so popular in Asia?', 'How can game companies make money besides selling games?', 'Will Eve\'s career make more girls interested in games? Why?'], src: 'Discussion', nt: '토론', n: ['원본 «Why is it more popular with boys?» 는 두 번째 읽기 쪽 질문으로 옮겼습니다'] },
      { t: 'guess', k: 'new', img: '15526', open: [2], q: 'Where are they? What are they doing?', chips: ['Is it a game event?', 'Are they fans?', 'Is it a real sword?'], nt: 'Guess who 타일', n: ['정답: a fan event(팬 행사) — 게임·영화 캐릭터 옷을 입은 팬', '원본 gloss «fan event» 를 사진으로'] },
      { t: 'yourturn', k: 'fix', img: '15568', title: 'Try it! My favorite game', lines: ['My favorite game is ___. It is a ___ game.', 'I play it on ___. It is single-player / multiplayer.', 'I enjoy it because ___.'], chips: ['strategy', 'puzzle', 'my smartphone'], src: 'Try it', nt: '내 말로', n: ['원본 «this same» → this game', '친구에게 Wh- 질문 하나, Yes/No 질문 하나 더 묻기'] },
      ...close(G1, { img: G('cover-concert'), q: 'What makes a song a hit?', ko: '어떤 노래가 히트곡이 될까? 다음 시간엔 대중음악 이야기!' }),
    ] },
  // ───────────────────────── 004-006
  { code: '004-006', tab: '대중음악', unit: U2, title: 'Popular Music', orig: 31,
    intro: '노래의 두 요소 melody·rhythm, 가사, 뮤직비디오, 히트곡을 배우고 «Would you rather …?» 로 취향을 묻습니다. 읽기: 쇼 비즈니스의 세계와 «원 히트 원더». 이야기: Yoona 와 Jay 가 학교 장기자랑에 밴드로 나갑니다.',
    fixed: ['Guess who 의 실존 가수(PSY) 사진 → 조명 속 가수 실루엣 · «a lot a famous and catchy songs» → a lot of famous, catchy songs', '뜻 «본질적인» → 꼭 필요한 · «평범한» → 그저 그런 · «판촉» → 홍보용 · «동반하다» → 함께하다 · «장치» → 수단 · «음악한곡» → 음악 한 곡', '목표 «promotion» ↔ 낱말 «promotional» 통일', '«a nice melody and but has mediocre lyrics» · «has a meaningful lyrics» → but has mediocre lyrics / has meaningful lyrics', '«How Music videos help the sales of Music recordings.» → How do music videos help sell music?', '«What hit songs you always listen to nowadays?» → What hit songs do you listen to these days?', '«live out to their dream» → live out their dream · gloss «music career» 뜻풀이 교체 · «sing along» 뜻 불일치 정리', '«Give three artist» → three artists · «Include the flowing facts» → the following facts', 'Mariah Carey 예시 «doesn\'t use anything by other songwriters» · «best selling recording» → She writes many of her own songs / best-selling recording artists', '«made a lot of money off of» → made a lot of money from'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-concert'), q: 'What makes a song a hit?', story: 'Yoona and Jay start a school band! 🎸', nt: '표지 + Big Question', n: ['꽃가루 날리는 콘서트 사진 — «How do you feel at a concert?» 를 먼저', '끝날 때 «A song becomes a hit when ___» 로 말하는 것이 목표'] },
      ...open(G2, 'Lesson Goals (Unit 2)'),
      CH2,
      { t: 'guess', k: 'fix', img: G('singer-silhouette'), open: [4], q: 'Can you guess who? Clue: a famous singer with lots of catchy songs.', chips: ['Is it a man or a woman?', 'Does the singer dance?', 'Is it a group?'], src: 'Warm up (Guess who)', nt: 'Guess who 타일', n: ['원본은 실존 가수(PSY) 사진 → 실루엣 사진으로 바꾸고 학생이 좋아하는 가수를 떠올리게', '<del>a lot a famous and catchy songs</del> → lots of catchy songs'] },
      { t: 'discuss', k: 'keep', img: '13082', small: 'Warm up', title: 'My music', qs: ['What are your favorite songs and artists? Why?', 'Do you like the song or the music video more?', 'Do your friends like the same music as you?', 'Do you want to be a famous singer?'], src: 'Starter Questions', nt: '준비 질문' },
      { t: 'vocab', k: 'fix', hide: true, title: 'Music words 🎵', words: [['melody', '멜로디(가락)', '13176'], ['rhythm', '리듬(박자)', G('drum-kids')], ['essential', '꼭 필요한', '13123'], ['instrument', '악기', '12470'], ['mediocre', '그저 그런', G('mediocre-song')], ['lyrics', '가사', G('writing-lyrics')]], src: 'Vocabulary', nt: '음악 낱말 ① — 뜻 가리기', n: ['<del>본질적인</del> → 꼭 필요한 · <del>평범한</del> → 그저 그런'] },
      { t: 'vocab', k: 'fix', title: 'Music words 🎵', words: [['melody', '멜로디(가락)', '13176'], ['rhythm', '리듬(박자)', G('drum-kids')], ['essential', '꼭 필요한', '13123'], ['instrument', '악기', '12470'], ['mediocre', '그저 그런', G('mediocre-song')], ['lyrics', '가사', G('writing-lyrics')]], nt: '뜻 공개', n: ['mediocre: 노래를 듣고 어깨를 으쓱하는 친구들 — «So-so»'] },
      { t: 'vocab', k: 'fix', title: 'Music video words 🎬', words: [['promotional', '홍보용의', '18763'], ['purpose', '목적', G('music-video-shoot')], ['accompany', '함께하다', '12648'], ['device', '수단·도구', '16624'], ['piece of music', '음악 한 곡', '17009']], src: 'Vocabulary (2)', nt: '뮤직비디오 낱말', n: ['<del>판촉</del> → 홍보용의 · <del>동반하다</del> → 함께하다 · <del>장치</del> → 수단 · <del>음악한곡</del> → 음악 한 곡'] },
      { t: 'read', k: 'fix', img: '12656', small: 'Keyword', title: 'Melody and Rhythm 🎼', paras: ['Melody and rhythm are two essential parts of music.', 'The melody is the part the artist sings or plays with a lead instrument.', 'A song also needs a rhythm to keep the time.'], gloss: [['lead instrument', '가락을 맡는 악기'], ['keep the time', '박자를 맞추다']], src: 'Keyword: Melody and Rhythm', nt: '키워드 ① 멜로디와 리듬', n: ['원본 악기 사진 5장(드럼·색소폰·키보드·손북·우쿨렐레) → 다음 쪽 게임으로'] },
      { t: 'memory', k: 'fix', title: 'Melody or rhythm?', items: [G('drum-kids'), '13176', '13005', '17009', '12656', '12470'], q: 'Which instrument was missing? Does it play the melody or the rhythm?', a: 'The ___ was missing. It plays the ___.', src: 'Which play the melody? Which play the rhythm?', nt: '기억 게임', n: ['10초 보고 가린 뒤 하나를 빼고 다시', '드럼 → rhythm · 피아노·바이올린 → melody · 기타 → 둘 다(강사가 짚기)', '원본의 색소폰·손북·우쿨렐레 사진은 강사가 말로 덧붙이기'] },
      { t: 'rule', k: 'fix', title: 'Would you rather …?', left: { h: 'Question', ex: ['**Would you rather** listen to a song with a nice melody **or** a song with meaningful lyrics?', '**Would you rather** watch the music video **or** just listen?'] }, right: { h: 'Answer', ex: ['**I\'d rather** listen to a nice melody.', '**I\'d rather** just listen **because** I can study at the same time.'] }, q: 'What comes after "Would you rather"? How do we answer?', src: 'Would you rather … (melody vs lyrics)', nt: '규칙 찾기', n: ['원본 질문을 고쳐 예문으로: <del>a nice melody and but has mediocre lyrics</del> · <del>a meaningful lyrics</del>', 'would rather 뒤는 동사원형 — 답은 I\'d rather + because'] },
      { t: 'read', k: 'fix', img: G('music-video-shoot'), small: 'Keyword', title: 'Music Videos 📹', paras: ['A music video is a short film that goes with a piece of music.', 'It can have a promotional or an artistic purpose.', 'It is a marketing device. It helps sell music.'], gloss: [['artistic', '예술적인'], ['marketing', '홍보·판매']], src: 'Keyword: Music Video', nt: '키워드 ② 뮤직비디오', n: ['accompany → goes with 로 쉽게 풀어 씀(낱말 쪽에서 accompany 를 이미 배움)'] },
      { t: 'discuss', k: 'fix', img: '15487', small: 'Think about it', title: 'Music videos', qs: ['What is your favorite music video ever?', 'Can a music video help a song become a hit?', 'How do music videos help sell music?', 'Have you seen a music video that has nothing to do with the song?'], src: 'Opinion (Music videos)', nt: '생각 질문', n: ['<del>How Music videos help the sales of Music recordings.</del> → How do music videos help sell music?'] },
      { t: 'read', k: 'fix', img: G('radio-dj'), small: 'Keyword', title: 'Hits 🔥', paras: ['A hit is a new song that becomes very popular.', 'You hear it everywhere: on the car radio, in supermarkets, in restaurants and so on.', 'Many hit songs have a music video.'], src: 'Keyword: Hit', nt: '키워드 ③ 히트곡', n: ['«etc.» → and so on'] },
      { t: 'discuss', k: 'fix', img: '18698', small: 'Think about it', title: 'Hit songs', qs: ['What are your favorite hits?', 'How do songs become hits?', 'Do you still listen to hits from two years ago?', 'What hit songs do you listen to these days?'], src: 'Opinion (Hits)', nt: '생각 질문', n: ['<del>What hit songs you always listen to nowadays?</del> → What hit songs do you listen to these days?'] },
      { t: 'story', k: 'new', img: G('band-garage'), title: 'Yoona and Jay ①', lines: [['Yoona', 'Jay, let\'s play in the school talent show!'], ['Jay', 'I can play the drums. I keep the rhythm.'], ['Yoona', 'And I can sing the melody. But we need lyrics!']], nt: '이야기 ①', n: ['rhythm · melody · lyrics 를 이야기 속에서 다시'] },
      { t: 'story', k: 'new', img: G('talent-show'), title: 'Yoona and Jay ②', lines: [['Jay', 'Would you rather sing a new song or an old hit?'], ['Yoona', 'I\'d rather sing our own song!'], ['Mango', 'Everybody is singing along! 🥭'], ['Jay', 'Wow, is this our first hit?']], nt: '이야기 ② 장기자랑', n: ['Would you rather 질문과 답 · sing along 을 이야기 속에서'] },
      { t: 'ox', k: 'new', img: G('band-garage'), s: 'Jay sings the melody, and Yoona plays the drums.', nt: '⭕❌', n: ['정답 ❌ → «No. Yoona sings the melody, and Jay plays the drums.»'] },
      { t: 'read', k: 'fix', img: G('talent-show'), small: 'Let\'s read', title: 'The Strange World of Show Business', paras: ['Millions of children dream of success. Many boys and girls dream of a band that hits it big.', 'But only about 1 in 16,000 will live out their dream.', 'They practice hard and develop their musical talents. The hardest part is making it big.'], gloss: [['show business', '연예계'], ['live out a dream', '꿈을 이루다'], ['hit it big / make it big', '크게 성공하다']], src: 'The Strange World of Show Business', nt: '읽기 ① 쇼 비즈니스', n: ['<del>live out to their dream</del> → live out their dream'] },
      { t: 'order', k: 'fix', img: G('talent-agent'), title: 'Scoring the big hit', words: ['It becomes a hit!', 'You meet a record company.', 'Your song plays on the radio.', 'A talent agent discovers you.', 'You record a song or an album.'], src: 'Scoring the big hit', nt: '순서 맞추기', n: ['원본 6단계 화살표 그림을 문장 순서 맞추기로 — 섞어 두었습니다', '정답: discovers you → meet a record company → record a song → plays on the radio → becomes a hit', '마지막 «Your music career begins» 는 강사가 덧붙이기 · gloss «music career» 뜻풀이 교체'] },
      { t: 'read', k: 'fix', img: G('disco-70s'), small: 'Let\'s read', title: 'One-hit Wonders ⭐', paras: ['Some singers have one big hit, and then people forget them. They are one-hit wonders.', 'In 1974, Carl Douglas, a Jamaican singer, released "Kung Fu Fighting." People still sing along to it, but none of his other songs became hits.'], gloss: [['released', '(노래를) 냈다'], ['sing along', '따라 부르다']], src: 'One-hit Wonders', nt: '읽기 ② 원 히트 원더', n: ['«It was featured in movies, TV shows and commercials» 는 강사가 말로', '노래 가사는 옮기지 않았습니다 — 음원은 강사 판단(사람이 정할 것 5)'] },
      { t: 'discuss', k: 'fix', img: '19346', title: 'Let\'s discuss', qs: ['Why is it so hard to succeed in show business?', 'What was your favorite artist\'s first hit? How have they changed?', 'Why do you think "Kung Fu Fighting" became a hit?', 'Can you think of a one-hit wonder in Korea?'], src: 'Discussion', nt: '토론', n: ['원본 «made a lot of money off of» 질문은 «How do you think Carl Douglas feels?» 로 강사가 이어서'] },
      { t: 'table', k: 'fix', small: 'Try it!', title: 'Three artists I like', head: ['Solo (International)', 'Solo (Local)', 'Group'], rows: [['___', '___', '___'], ['___', '___', '___'], ['___', '___', '___']], tip: '칸마다 가수 이름을 하나씩 — 다 채우면 가장 좋아하는 한 명을 골라 소개해요.', src: 'Try it (Give three artists)', nt: '가수 표', n: ['<del>Give three artist</del> → three artists'] },
      { t: 'yourturn', k: 'fix', img: '17268', title: 'Make an artist bio 📝', lines: ['___ is a solo artist / a group from ___.', 'They started recording in ___. Their style is ___.', 'They are popular with ___. They have won ___.'], chips: ['pop', 'ballad', 'teenagers'], src: 'Try it (bio · Mariah Carey example · template)', nt: '내 말로 — 가수 소개', n: ['<del>Include the flowing facts</del> → the following facts', '예시 Mariah Carey 글의 사실 오류는 강사 메모로(사람이 정할 것 1)'] },
      ...close(G2, { img: G('cover-sports'), q: 'Would you rather play sports or watch them?', ko: '운동은 직접 할래, 볼래? 다음 시간엔 프로 스포츠 이야기!' }),
    ] },
  // ───────────────────────── 007-009
  { code: '007-009', tab: '프로 스포츠', unit: U3, title: 'Professional Sports', orig: 30,
    intro: '팀워크와 스포츠맨십을 배우고 should/shouldn\'t 로 «좋은 선수가 할 일» 을 말합니다. 읽기: 미국 야구의 벤치 클리어링과 새 규칙. 롤플레이: 억울한 판정·거친 상대·주전 경쟁. 이야기: Yoona 와 Jay 의 축구 준결승.',
    fixed: ['경기 중 실존 축구 선수 사진 → 넘어진 상대를 일으켜 주는 어린이 선수 사진', '뜻 «증명하다» → 보여 주다 · «운동가정신» → 스포츠맨십(정정당당함) · «패널티» → 벌칙·페널티킥', '«Baseball is very popular in Asian» → in Asia · gloss violent «…kill» → 폭력적인(순화)', '«Are fights had for the game?» → bad · «new tule» → new rule', '«Diane was ejected was from the team» → was ejected from the team · «no intentions to provoke my own teacher» → no intention of provoking', '«purpose» 예문은 이 과 낱말이 아니라 Unit 2 복습으로 옮김', '롤플레이 «what, were they like.» → What would you do? · Situation 3 «left fielder» 뜻 풀어 씀', '«punching and wrestling» → fighting(순화)'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-sports'), q: 'What makes a great player — skill or sportsmanship?', story: 'Yoona and Jay play in the soccer semifinals! ⚽', nt: '표지 + Big Question', n: ['헤딩 슛 순간 사진 — «What sport is it? Is it exciting?» 를 먼저', '끝날 때 «A great player should ___» 로 말하는 것이 목표'] },
      ...open(G3, 'Lesson Goals (Unit 3)'),
      CH3,
      { t: 'discuss', k: 'keep', img: '12492', small: 'Warm up', title: 'Let\'s talk about sports', qs: ['What would it be like to be a professional athlete?', 'What sports do you like to play or watch?', 'How do athletes get so good? Is it stressful?', 'What is the best part and the worst part of being an athlete?'], src: 'Starter Questions', nt: '준비 질문' },
      { t: 'vocab', k: 'fix', hide: true, title: 'Sports words 🏅', words: [['teamwork', '팀워크', '12122'], ['individual', '개인', '17245'], ['achievements', '업적·이룬 것', '18282'], ['demonstrate', '보여 주다', '16725'], ['sportsmanship', '스포츠맨십(정정당당함)', G('help-opponent')], ['semifinals', '준결승', G('semifinal-win')], ['foul', '반칙', '20272'], ['penalty', '벌칙·페널티킥', '20235']], src: 'Vocabulary', nt: '스포츠 낱말 — 뜻 가리기', n: ['<del>증명하다</del> → 보여 주다 · <del>운동가정신</del> → 스포츠맨십 · <del>패널티</del> → 벌칙·페널티킥', '원본 «semifinals» 달리기 출발 사진은 뜻이 달라 바꿨습니다'] },
      { t: 'vocab', k: 'fix', title: 'Sports words 🏅', words: [['teamwork', '팀워크', '12122'], ['individual', '개인', '17245'], ['achievements', '업적·이룬 것', '18282'], ['demonstrate', '보여 주다', '16725'], ['sportsmanship', '스포츠맨십(정정당당함)', G('help-opponent')], ['semifinals', '준결승', G('semifinal-win')], ['foul', '반칙', '20272'], ['penalty', '벌칙·페널티킥', '20235']], nt: '뜻 공개', n: ['foul(반칙) → penalty(벌칙) 순서로 이어 말하기'] },
      { t: 'read', k: 'fix', img: '21388', small: 'Keyword', title: 'Teamwork 🤝', paras: ['In team sports, players need to work together.', 'If all the players only try to get individual achievements, the team won\'t win many games.', 'Good players demonstrate good teamwork.'], src: 'Keyword: Teamwork', nt: '키워드 ① 팀워크' },
      { t: 'discuss', k: 'keep', img: '12122', small: 'Think about it', title: 'Teamwork', qs: ['What does "There\'s no I in team" mean?', 'Some sports need more teamwork than others. Can you give examples?', 'What are the advantages of working alone?'], src: 'Think about it (Teamwork)', nt: '생각 질문 ①', n: ['«use teamwork in two sentences» 는 내 차례 쪽에서'] },
      { t: 'read', k: 'fix', img: G('help-opponent'), small: 'Keyword', title: 'Sportsmanship 🙌', paras: ['Good sportsmanship means following the rules and having a good attitude.', 'It also means showing respect to your opponents.'], gloss: [['attitude', '태도'], ['opponent', '상대 선수']], src: 'Keyword: Sportsmanship', nt: '키워드 ② 스포츠맨십', n: ['원본 실존 선수 사진 → 어린이 선수 사진(사람이 정할 것 4)'] },
      { t: 'rule', k: 'new', title: 'should or shouldn\'t?', left: { h: 'Good sportsmanship ✅', ex: ['Players **should** follow the rules.', 'You **should** shake hands after the game.'] }, right: { h: 'Poor sportsmanship ❌', ex: ['Players **shouldn\'t** fight.', 'You **shouldn\'t** yell at the referee.'] }, q: 'What comes after should? How do we make it negative?', nt: '규칙 찾기 (1~7단계 문법 복습)', n: ['원본 «examples of poor sportsmanship» 질문을 문법으로', 'should + 동사원형 · shouldn\'t = should not'] },
      { t: 'discuss', k: 'keep', img: '14434', small: 'Think about it', title: 'Sportsmanship', qs: ['How do players show good sportsmanship?', 'What does a coach mean by "Be a good sport"?', 'What are some examples of poor sportsmanship?', 'How important is sportsmanship in sports?'], src: 'Think about it (Sportsmanship)', nt: '생각 질문 ②' },
      { t: 'story', k: 'new', img: G('semifinal-win'), title: 'Yoona and Jay ①', lines: [['Jay', 'It\'s the semifinals! Are you nervous?'], ['Yoona', 'A little. Their team plays rough.'], ['Jay', 'Remember: we should play as a team.']], nt: '이야기 ①', n: ['semifinals · should 를 이야기 속에서'] },
      { t: 'story', k: 'new', img: '20235', title: 'Yoona and Jay ②', lines: [['Teacher', 'Foul! Penalty kick for the other team.'], ['Jay', 'What? That\'s not fair!'], ['Yoona', 'Jay, we shouldn\'t yell. Let\'s be good sports.'], ['Jay', 'You\'re right. Let\'s win it back!']], nt: '이야기 ② 페널티', n: ['foul · penalty · be a good sport'] },
      { t: 'ox', k: 'new', img: '20235', s: 'Yoona told Jay to yell at the referee.', nt: '⭕❌', n: ['정답 ❌ → «No. She said, "We shouldn\'t yell."»'] },
      { t: 'guess', k: 'new', img: G('help-opponent'), open: [0], q: 'What is happening? Is it good sportsmanship?', chips: ['Did someone fall?', 'Are they on the same team?', 'Is he helping?'], nt: 'Guess who 타일', n: ['정답: 상대 선수를 일으켜 주는 장면 — 표지 Big Question 으로'] },
      { t: 'read', k: 'fix', img: G('benches-clear'), small: 'Let\'s read', title: 'Brawls in American Baseball ⚾', paras: ['Baseball is very popular in Asia. Families root for their teams together.', 'In the USA, games sometimes get violent, and players from both teams fight.', 'Players who fight are ejected and can be suspended for up to a week.'], gloss: [['root for', '응원하다'], ['ejected', '퇴장당한'], ['suspended', '출전 정지된']], src: 'Brawls in American Baseball', nt: '읽기 ① 야구 난투', n: ['<del>in Asian</del> → in Asia · «punching and wrestling» → fight(순화, 사람이 정할 것 3)', 'brawl(난투)은 제목에서 짚기'] },
      { t: 'read', k: 'fix', img: G('hit-by-pitch'), small: 'Let\'s read', title: 'Why are there so many brawls?', paras: ['Most brawls start with a hit-by-pitch: the pitcher hits the batter with the ball.', 'If the pitcher does it on purpose, the batter wants to retaliate and charges the mound.', 'Then everyone joins in to protect their teammates.'], gloss: [['on purpose', '일부러'], ['retaliate', '보복하다']], src: 'Brawls (history)', nt: '읽기 ② 난투의 시작', n: ['«more than 100 years of history» · «the worst is aiming at the head» 는 강사가 말로', 'charge the mound = 투수에게 달려가다'] },
      { t: 'read', k: 'fix', img: G('umpire-warning'), small: 'Let\'s read', title: 'Are fights bad for the game?', paras: ['Officials changed the rules. Now, after a hit-by-pitch, the umpire can warn both teams.', 'Punishments are stricter, and managers can be punished too.'], gloss: [['stricter', '더 엄격한'], ['punishment', '처벌']], src: 'Are fights bad for the game?', nt: '읽기 ③ 새 규칙', n: ['<del>had</del> → bad · <del>new tule</del> → new rule'] },
      { t: 'read', k: 'fix', img: '19382', small: 'Let\'s read', title: 'Good or bad?', paras: ['Sportswriters say rich athletes shouldn\'t fight. It is a bad example for kids.', 'But many fans love brawls, and TV ratings go up. "Base-brawls" are not going away soon.'], gloss: [['TV ratings', '시청률'], ['go away', '사라지다']], src: 'Are fights bad for the game?', nt: '읽기 ④ 두 생각', n: ['millionaires → rich athletes(쉬운 말)'] },
      { t: 'discuss', k: 'keep', img: G('benches-clear'), title: 'Let\'s discuss', qs: ['Why do you think teams in the USA fight?', 'Why do some fans enjoy watching brawls?', 'Do you agree with the new rules? Why?'], src: 'Discussion', nt: '토론', n: ['원본 «우리나라 팀도 싸우나?»·«나쁜 본보기인가?»·«우리나라 선수가 싸우면 기분이?» 는 강사가 이어서'] },
      { t: 'fill', k: 'fix', img: '18145', title: 'Make sentences', lines: ['I am rooting ___ your team to win.', 'Diane was ___ from the game for fighting.', 'His license will be ___ for one year.'], chips: ['for', 'ejected', 'suspended', 'fired'], src: 'Make sentences', nt: '빈칸', n: ['<del>was ejected was from</del> → was ejected from · fired 는 함정', '«provoke» 예문 <del>no intentions to provoke</del> → «I had no intention of provoking my teacher.» · retaliate·punishment·warning 예문은 강사가 말로', '«purpose» 예문은 이 과 낱말이 아니라 뺐습니다'] },
      { t: 'discuss', k: 'fix', img: '20235', small: 'Role-play', title: 'Situation 1 · The penalty', qs: ['It is the soccer semifinals. The score is 1–1, and there are five minutes left.', 'The referee calls a foul. The other team gets a penalty kick and scores. Now it is 2–1.', 'You think the call was unfair. How do you feel? What is the best thing to do?'], src: 'Role-play Situation 1', nt: '롤플레이 ①', n: ['<del>what, were they like.</del> → What would you do?', '85 minutes → five minutes left(쉽게)'] },
      { t: 'discuss', k: 'fix', img: G('rough-play'), small: 'Role-play', title: 'Situation 2 · Rough play', qs: ['You are playing soccer at school. Your gym teacher is the referee.', 'The other team plays rough. They push and trip your teammates, but the teacher gives no yellow cards.', 'What do you do?'], src: 'Role-play Situation 2', nt: '롤플레이 ②' },
      { t: 'discuss', k: 'fix', img: G('bench-worried'), small: 'Role-play', title: 'Situation 3 · The new player', qs: ['You are the regular left fielder on your baseball team.', 'A new outfielder joins the team, and he is very good.', 'You are afraid the coach will bench you. What would you do?'], src: 'Role-play Situation 3', nt: '롤플레이 ③', n: ['left fielder = 좌익수 · bench = 후보로 앉히다'] },
      { t: 'yourturn', k: 'new', img: '17152', title: 'My sports sentences', lines: ['___ is a sport that needs a lot of teamwork.', 'A good sport should ___.', 'A good sport shouldn\'t ___.'], chips: ['soccer', 'shake hands', 'fight'], nt: '내 말로', n: ['원본 «use teamwork / sportsmanship in two sentences» 를 여기서'] },
      ...close(G3, { img: G('maglev'), q: 'Would you rather ride a train that floats?', ko: '떠서 달리는 기차를 타 볼래? 다음 시간엔 대중교통 이야기!' }),
    ] },
  // ───────────────────────── 010-012
  { code: '010-012', tab: '대중교통', unit: U4, title: 'Public Transportation', orig: 32,
    intro: '비용·편안함·편리함으로 교통수단을 비교하고(more … than · as … as), 기반 시설과 교통 문제를 이야기합니다. 읽기: 베이징과 로스앤젤레스의 교통, 세계의 특별한 탈것. 이야기: Yoona 와 Jay 의 지하철 견학.',
    fixed: ['글 제목 «Transportation in Seoul and Los Angeles» 인데 글은 Beijing → 제목·본문의 Seoul 두 곳을 Beijing 으로(사람이 정할 것 6)', '«What kinds of public transportations» · «do use» → public transportation · do you use', '«pick you up drop you off» → pick you up and drop you off', '«In both the places» → In both places · gloss megacities·metropolitan area 뜻풀이 정리', '«the Metro Shanghai» → the Shanghai Metro · «Before the system underwent rapid expansion since 2002, had only two lines» → Before 2002, it had only two lines', '«widely-used, commonly use» → widely used · «Less than 50 million riders» → Fewer than', '«neither one is as useful as the one in Seoul» → as the one in Beijing', '«these types of transportations» → these types of transportation · «Would you experience them» → Would you like to try them · «Why of why not» → Why or why not', '«steady dying out» → steadily dying out · «paddles» → pedals', '사진 교체: rapid transit 에 고속철 · airport rail link 에 일본 열차 · 기반 시설에 댐 사진'],
    slides: [
      { t: 'cover', k: 'new', img: G('maglev'), q: 'What is the best way to get around a big city?', story: 'Yoona and Jay take a field trip by subway! 🚇', nt: '표지 + Big Question', n: ['공중에 떠서 달리는 자기부상열차 — «Does it touch the track?» 를 먼저', '끝날 때 «The best way is ___ because it is more ___ than ___» 로 말하는 것이 목표'] },
      ...open(G4, 'Lesson Goals (Unit 4)'),
      CH4,
      { t: 'discuss', k: 'fix', img: '14160', small: 'Warm up', title: 'How do you get around?', qs: ['What kinds of public transportation do you use? Which do you use most often?', 'Does your family own a car? Why do some people drive instead of taking public transportation?', 'When you grow up, will you drive or take public transportation?'], src: 'Warm up + Starter Questions', nt: '준비 질문', n: ['<del>public transportations</del> → public transportation · <del>do use</del> → do you use'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Transportation words 🚌', words: [['public transportation', '대중교통', '12729'], ['cost', '비용', '18155'], ['comfort', '편안함', '16915'], ['convenience', '편리함', '18662'], ['infrastructure', '기반 시설', '14055'], ['improvements', '개선된 것', '21301']], src: 'Vocabulary', nt: '교통 낱말 — 뜻 가리기', n: ['원본 Review 의 «public transportation» 자동차 정체 사진 → 버스·기차 터미널 사진'] },
      { t: 'vocab', k: 'keep', title: 'Transportation words 🚌', words: [['public transportation', '대중교통', '12729'], ['cost', '비용', '18155'], ['comfort', '편안함', '16915'], ['convenience', '편리함', '18662'], ['infrastructure', '기반 시설', '14055'], ['improvements', '개선된 것', '21301']], nt: '뜻 공개' },
      { t: 'read', k: 'fix', img: '15763', small: 'Keyword', title: 'Cost, Comfort, Convenience 🚕', paras: ['Taxis are the most comfortable and convenient. They pick you up and drop you off anywhere, and you get a soft seat.', 'However, taxis cost more than other types of public transportation.', 'Subways and buses cost less, but are they as convenient?'], src: 'Keyword: Cost, Comfort, Convenience', nt: '키워드 ① 3C', n: ['<del>pick you up drop you off</del> → pick you up and drop you off'] },
      { t: 'rule', k: 'new', title: 'Compare it!', left: { h: 'more / less … than', ex: ['Taxis are **more comfortable than** buses.', 'Buses **cost less than** taxis.'] }, right: { h: 'as … as', ex: ['Is the bus **as convenient as** a taxi?', 'The subway is **not as comfortable as** a taxi.'] }, q: 'Which pattern says two things are the same? Which says they are different?', nt: '규칙 찾기 (1~7단계 문법 복습)', n: ['키워드 글의 마지막 문장 «are they as convenient?» 에서 규칙을 찾게'] },
      { t: 'discuss', k: 'keep', img: '16819', small: 'Think about it', title: 'Buses, subways and taxis', qs: ['How are buses and subways less comfortable or convenient than taxis?', 'Which type do you prefer? Why?', 'When is it worth paying more for a taxi?'], src: 'Think about it (3C)', nt: '생각 질문 ①' },
      { t: 'read', k: 'fix', img: '16330', small: 'Keyword', title: 'Infrastructure 🌉', paras: ['Infrastructure improvements make it easier to move around cities and countries.', 'Examples are roads, highways, subway lines, train tracks, bridges and tunnels.'], src: 'Keyword: Infrastructure', nt: '키워드 ② 기반 시설', n: ['원본 댐·해안 도시 사진은 교통과 거리가 멀어 다리 사진으로'] },
      { t: 'discuss', k: 'keep', img: '21301', small: 'Think about it', title: 'Infrastructure', qs: ['What infrastructure improvements are there in your city?', 'Why is good infrastructure important?', 'What happens if the infrastructure is not good enough?'], src: 'Think about it (Infrastructure)', nt: '생각 질문 ②' },
      { t: 'scramble', k: 'new', title: 'Unscramble the rides!', items: [['XIAT', '15763'], ['WUBAYS', '19962'], ['SUB', '16097'], ['DIRGEB', '16330']], nt: '단어 섞기 게임', n: ['정답: TAXI · SUBWAY · BUS · BRIDGE', '맞힌 뒤 비교 문장 하나 — «The subway is faster than the bus.»'] },
      { t: 'story', k: 'new', img: '19962', title: 'Yoona and Jay ①', lines: [['Teacher', 'Today we are going to the museum by subway.'], ['Jay', 'Why not by bus? The bus stop is closer.'], ['Yoona', 'It\'s rush hour. The subway is faster than the bus!']], nt: '이야기 ①', n: ['비교 문장 faster than · rush hour'] },
      { t: 'story', k: 'new', img: '18019', title: 'Yoona and Jay ②', lines: [['Jay', 'Wow, the train is packed!'], ['Yoona', 'Look outside. The cars are at a standstill.'], ['Jay', 'Taxis are more comfortable, but the subway is more convenient today!']], nt: '이야기 ② 러시아워', n: ['standstill 복선 · more … than'] },
      { t: 'ox', k: 'new', img: '18019', s: 'Yoona and Jay went to the museum by taxi.', nt: '⭕❌', n: ['정답 ❌ → «No. They went by subway.»'] },
      { t: 'read', k: 'fix', img: '14511', small: 'Let\'s read', title: 'Beijing and Los Angeles', paras: ['Beijing, China, and Los Angeles (LA), USA, are two huge megacities. In both places, many people commute into the city.', 'Over 20 million people live in metro Beijing, and over 15 million live in metro LA.'], gloss: [['megacity', '초대형 도시'], ['metro', '대도시권(도시와 둘레)'], ['commute', '통근하다']], src: 'Transportation in Seoul (→ Beijing) and Los Angeles', nt: '읽기 ① 두 도시', n: ['<del>Seoul</del> → Beijing(본문이 베이징) · <del>In both the places</del> → In both places', '«cars, buses, subways, trains, walk or bicycles» 는 앞 준비 질문과 이어 강사가 말로'] },
      { t: 'read', k: 'fix', img: G('packed-subway'), small: 'Let\'s read', title: 'The Beijing Subway 🚇', paras: ['The Beijing Subway has about 23 lines: rapid transit lines, airport rail links, a maglev line and a light rail line.', 'It is the second-longest subway in the world after the Shanghai Metro.', 'It opened in 1969, so it is the oldest in mainland China. Before 2002, it had only two lines!'], gloss: [['rapid transit', '도시 급행 철도'], ['airport rail link', '공항 철도'], ['maglev', '자기부상열차']], src: 'The Beijing Subway', nt: '읽기 ② 베이징 지하철', n: ['<del>the Metro Shanghai</del> → the Shanghai Metro · 원본 «Before the system underwent … since 2002, had only two lines» 정리', '수치는 2019년 무렵 자료 — «about» 을 붙임(사람이 정할 것 1)', '원본 사진 4쪽(고속철·일본 열차 등 뜻 불일치)은 한 쪽으로'] },
      { t: 'guess', k: 'new', img: G('maglev'), open: [1], q: 'What kind of train is it?', chips: ['Does it have wheels?', 'Is it very fast?', 'Does it float?'], nt: 'Guess who 타일', n: ['정답: a maglev train(자기부상열차) — 자석으로 떠서 달립니다'] },
      { t: 'read', k: 'fix', img: '17143', small: 'Let\'s read', title: 'Getting around Beijing', paras: ['Buses in Beijing are widely used. They are cheap and convenient.', 'But there are about 20 million cars, so there are traffic jams at rush hour.', 'Subway riders only worry about a packed train!'], gloss: [['widely used', '많이 쓰이는'], ['rush hour', '출퇴근 시간']], src: 'Beijing buses', nt: '읽기 ③ 베이징 버스', n: ['<del>widely-used, commonly use</del> → widely used', '«사람들이 아파트에 모여 살아서» 는 강사가 말로'] },
      { t: 'read', k: 'fix', img: '15319', small: 'Let\'s read', title: 'Los Angeles: The City of Cars 🚗', paras: ['LA grew quickly in the 1950s. There was lots of space, so people built houses.', 'The government encouraged people to buy cars to help the economy.', 'It built huge freeways and closed down trains and streetcars.'], gloss: [['encouraged', '권했다'], ['freeway', '고속도로'], ['closed down', '없앴다']], src: 'Los Angeles', nt: '읽기 ④ LA 의 시작', n: ['«very new city» · «up to 16 lanes» 는 강사가 말로'] },
      { t: 'read', k: 'fix', img: G('freeway-jam'), small: 'Let\'s read', title: 'Traffic in LA 🚦', paras: ['Not surprisingly, traffic in LA is severe.', 'Cars can be at a standstill for hours.', 'LA is also infamous for its smog.'], gloss: [['severe', '심한'], ['standstill', '꼼짝 못 하는 상태'], ['infamous', '나쁘게 유명한']], src: 'Los Angeles (traffic)', nt: '읽기 ⑤ LA 교통', n: ['smog 는 다음 쪽 사진으로'] },
      { t: 'read', k: 'fix', img: G('light-rail'), small: 'Let\'s read', title: 'Problems in LA', paras: ['LA has buses and light rail, but neither one is as useful as the one in Beijing.', 'The light rail runs on roads and stops at traffic lights. Fewer than 50 million people ride it each year.', 'There are many proposals, but there is little money. So people are still stuck in traffic.'], gloss: [['light rail', '경전철'], ['proposal', '제안']], src: 'Problems in LA', nt: '읽기 ⑤ LA 의 문제', n: ['<del>as the one in Seoul</del> → in Beijing · <del>Less than</del> → Fewer than'] },
      { t: 'discuss', k: 'fix', img: G('smog-city'), title: 'Problems and solutions', qs: ['How did LA\'s traffic problem start?', 'Why is it hard to solve?', 'Why do you think some people in Beijing still drive?', 'Would you drive if there were long traffic jams? Why?'], src: 'Problems & Solutions', nt: '토론', n: ['<del>Why do think … in Seoul</del> → Why do you think … in Beijing'] },
      { t: 'fill', k: 'fix', img: '16818', title: 'Make sentences', lines: ['Many people ___ to work by train every morning.', 'The traffic was so bad that the cars were at a ___.', 'LA is ___ for its smog.'], chips: ['commute', 'standstill', 'infamous', 'economy'], src: 'Make sentences', nt: '빈칸', n: ['원본 낱말 6개 중 3개 — economy 는 함정이자 강사가 한 문장 더 · severe·smog 는 앞 쪽 토론에서'] },
      { t: 'match', k: 'fix', title: 'Unique transportation 🌏', left: [G('rickshaw'), G('water-bus'), G('cyclo'), G('monorail')], right: ['a water bus in Tokyo', 'a cyclo in Vietnam', 'a monorail', 'a rickshaw in Japan'], src: 'Unique Transportation', nt: '짝 맞추기', n: ['정답: 1-D · 2-A · 3-B · 4-C', '원본 «Do you have these types of transportations …? Would you experience them? Why of why not» → 다음 쪽 질문으로 정리'] },
      { t: 'read', k: 'fix', img: G('rickshaw'), small: 'Let\'s read', title: 'Rides in Japan 🇯🇵', paras: ['In Asakusa, Tokyo, a man pulls a rickshaw. People first used them in the late 1800s.', 'You can also ride a water bus on the Sumida River for less than ¥1,000!'], gloss: [['rickshaw', '인력거'], ['water bus', '수상 버스']], src: 'Unique Transportation (Japan)', nt: '읽기 ⑦ 일본', n: ['모노레일 Yurikamome 로 돌아오는 길은 강사가 말로'] },
      { t: 'read', k: 'fix', img: G('cyclo'), small: 'Let\'s read', title: 'Rides in Vietnam 🇻🇳', paras: ['A cyclo is cheap and eco-friendly, but it is steadily dying out.', 'The driver pedals from behind.', 'Cyclos are banned from some streets in Hanoi and Saigon.'], gloss: [['eco-friendly', '친환경의'], ['dying out', '사라지고 있는'], ['banned', '금지된']], src: 'Unique Transportation (Vietnam)', nt: '읽기 ⑧ 베트남', n: ['<del>steady dying out</del> → steadily · <del>paddles</del> → pedals', 'xe lôi(앞에서 끄는 시클로)·«지도를 챙기세요» 는 강사가 말로'] },
      { t: 'yourturn', k: 'fix', img: G('cyclo'), title: 'My ride', lines: ['I would like to try a ___ because ___.', 'In my city, the ___ is more convenient than the ___.', 'The best way to get around my city is ___.'], chips: ['rickshaw', 'subway', 'bus'], src: 'Unique Transportation (Would you like to try them?)', nt: '내 말로', n: ['<del>Would you experience them? Why of why not</del> → Would you like to try them? Why or why not?', '표지 Big Question 으로 돌아가기'] },
      ...close(G4, { img: '19033', q: 'Are you ready for the review game?', ko: '네 단원 복습 게임, 준비됐나요?' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 33 Review', orig: 23,
    intro: '원본 복습의 낱말 40개(단원마다 10개, «이 낱말로 문장 만들기»)를 «퀴즈쇼» 4단계로. 단원마다 낱말 공개 → 사진 질문 → 게임.',
    fixed: ['사진 교체: platforms(회사원 태블릿) · strategy(퍼즐) · violent(복면에 방망이) · armies(총 든 군인) · level(건물 층) · semifinals(달리기 출발) · stand still(요가) · public transportation(자동차 정체) · infamous(실루엣) 등 뜻과 안 맞거나 아이 수업에 맞지 않는 사진', '«stand still» → standstill · «INFRASTUCTURE» → infrastructure', '앞 과에서 고친 뜻(좌절감을 주는 · 그저 그런 · 스포츠맨십 · 베이징)을 복습에도 똑같이'],
    slides: [
      { t: 'cover', k: 'new', img: '19033', q: 'Can you win the Quiz Show?', story: 'Four stages: games, music, sports and transportation! 🏆', nt: '표지', n: ['단계를 통과할 때마다 칠판에 도장 — 퀴즈쇼처럼'] },
      ...open([['I can talk about computer games.', '컴퓨터 게임을 말할 수 있어요.'], ['I can talk about music and sports.', '음악과 스포츠를 말할 수 있어요.'], ['I can compare kinds of transportation.', '교통수단을 비교할 수 있어요.']], 'Review Goals'),
      CH1,
      { t: 'vocab', k: 'fix', hide: true, small: 'Stage 1 · Computer Games', title: 'Use it in a sentence!', words: [['frustrating', '좌절감을 주는', '19420'], ['destroying', '파괴하는', '12954'], ['weapons', '무기', '20273'], ['platforms', '플랫폼', '17267'], ['strategy', '전략', '18269'], ['virtual world', '가상 세계', G('virtual-world')], ['identity', '정체성', '21013'], ['violent', '폭력적인', G('benches-clear')], ['armies', '군대', G('toy-armies')], ['level', '(게임의) 단계', '12108']], src: 'Review (Computer Games)', nt: '1단계 낱말', n: ['낱말마다 한 문장씩 — 사진을 보고 먼저', '원본 사진 교체: 태블릿 회사원·퍼즐·복면 방망이·총 든 군인·건물 층(사람이 정할 것 4)'] },
      { t: 'qa', k: 'new', img: G('esports-crowd'), small: 'Stage 1', title: 'Games', q: 'Why do you think so many people watch game tournaments?', a: 'I think they watch because ___.', nt: '1단계 질문' },
      { t: 'match', k: 'new', small: 'Stage 1', title: 'Which game?', left: ['14026', G('gaming-headset'), G('virtual-world'), '12418'], right: ['MMO', 'puzzle', 'strategy', 'FPS'], nt: '1단계 도장 — 짝 맞추기', n: ['정답: 1-C · 2-D · 3-A · 4-B'] },
      { t: 'vocab', k: 'fix', hide: true, small: 'Stage 2 · Popular Music', title: 'Use it in a sentence!', words: [['melody', '멜로디', '13123'], ['rhythm', '리듬', G('drum-kids')], ['instrument', '악기', '12470'], ['mediocre', '그저 그런', G('mediocre-song')], ['lyrics', '가사', G('writing-lyrics')], ['promotional', '홍보용의', '18763'], ['purpose', '목적', G('music-video-shoot')], ['accompany', '함께하다', '12648'], ['recording artist', '음반 가수', '17268'], ['piece of music', '음악 한 곡', '17009']], src: 'Review (Popular Music)', nt: '2단계 낱말', n: ['원본 «promotional» 세일 표지판 사진은 글자가 들어 있어 바꿨습니다'] },
      { t: 'qa', k: 'new', img: G('cover-concert'), small: 'Stage 2', title: 'Music', q: 'Would you rather listen to a song with a nice melody or a song with meaningful lyrics?', a: 'I\'d rather ___ because ___.', nt: '2단계 질문' },
      { t: 'ox', k: 'new', img: G('disco-70s'), small: 'Stage 2', s: 'A one-hit wonder is a singer with many hit songs.', nt: '2단계 도장 — ⭕❌', n: ['정답 ❌ → «No. A one-hit wonder has only one big hit.»'] },
      { t: 'vocab', k: 'fix', hide: true, small: 'Stage 3 · Professional Sports', title: 'Use it in a sentence!', words: [['teamwork', '팀워크', '12122'], ['individual', '개인', '17245'], ['achievement', '업적', '12753'], ['demonstrate', '보여 주다', '16725'], ['semifinals', '준결승', G('semifinal-win')], ['sportsmanship', '스포츠맨십', '14725'], ['foul', '반칙', '20272'], ['penalty', '벌칙', '20235'], ['coach', '코치', '12937'], ['professional athlete', '프로 선수', '12492']], src: 'Review (Professional Sports)', nt: '3단계 낱말', n: ['원본 «semifinals» 달리기 출발 사진 → 준결승 승리 사진'] },
      { t: 'qa', k: 'new', img: G('rough-play'), small: 'Stage 3', title: 'Sports', q: 'The other team plays rough. What should you do? What shouldn\'t you do?', a: 'I should ___. I shouldn\'t ___.', nt: '3단계 질문' },
      { t: 'memory', k: 'new', small: 'Stage 3', title: 'Stage 3 memory!', items: ['12122', '20272', '20235', G('help-opponent'), '12753', '12937'], q: 'Which picture was missing?', a: 'The ___ picture was missing!', nt: '3단계 도장 — 기억 게임', n: ['10초 보고 가린 뒤 하나를 빼고 다시'] },
      { t: 'vocab', k: 'fix', hide: true, small: 'Stage 4 · Public Transportation', title: 'Use it in a sentence!', words: [['standstill', '꼼짝 못 하는 상태', '15289'], ['public transportation', '대중교통', '12729'], ['economy', '경제', '21130'], ['infamous', '나쁘게 유명한', G('smog-city')], ['commute', '통근하다', '16818'], ['improvements', '개선된 것', '21301'], ['convenient', '편리한', '18662'], ['infrastructure', '기반 시설', '14055'], ['cost', '비용', '18155'], ['comfort', '편안함', '16915']], src: 'Review (Public Transportation)', nt: '4단계 낱말', n: ['<del>stand still</del> → standstill · <del>INFRASTUCTURE</del> → infrastructure', '원본 사진 교체: 요가 실루엣(standstill) · 자동차 정체(public transportation) · 실루엣(infamous)'] },
      { t: 'qa', k: 'new', img: '15763', small: 'Stage 4', title: 'Transportation', q: 'Compare taxis and buses. Which is cheaper? Which is more comfortable?', a: 'Buses cost ___ than taxis. Taxis are more ___ than buses.', nt: '4단계 질문' },
      { t: 'scramble', k: 'new', small: 'Stage 4', title: 'Stage 4 scramble!', items: [['TUMECOM', '16818'], ['GOSM', G('smog-city')], ['VELGAM', G('maglev')], ['WAKCSHIR', G('rickshaw')]], nt: '4단계 도장 — 단어 섞기', n: ['정답: COMMUTE · SMOG · MAGLEV · RICKSHAW'] },
      { t: 'guess', k: 'new', img: G('cyclo'), open: [], q: 'Boss! What is it? Where is it?', chips: ['Is it a kind of transportation?', 'Is it in Vietnam?', 'Does the driver pedal?'], nt: '보스 문제', n: ['타일을 열 때마다 Yes/No 질문 한 개 — Unit 1 문법으로 마무리', '정답: a cyclo in Vietnam'] },
      { t: 'yourturn', k: 'new', img: '12614', title: 'My favorites 🌟', lines: ['My favorite game is ___ because ___.', 'I would rather ___ than ___.', 'The best way to get around my city is ___.'], nt: '내 말로 — 네 단원 한 번씩' },
      ...close([['I can talk about computer games.', 'I play puzzle games on my smartphone.'], ['I can talk about music and sports.', 'A good sport should shake hands.'], ['I can compare kinds of transportation.', 'The subway is faster than the bus.']], { img: '12614', q: 'Are you ready for the test?', ko: '시험 볼 준비 됐나요?' }),
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 33 Unit Test', orig: 11,
    intro: '20문항 단원 시험(원본 문항 그대로). 화상수업에서 말로 보는 시험이라 한 쪽에 2~3문항씩 묶고 «이유까지 말하기» 를 기준으로 했습니다.',
    fixed: ['문항 2 «…of playing computer games?.» 끝 구두점 정리', '문항 3 «How does computer games affect the students?» → How do computer games affect students?', '문항 5 «How can puzzle games can make people smarter?» → How can puzzle games make people smarter?', '문항 8 «a nice melody and but has mediocre lyrics» → but has mediocre lyrics', '문항 9 «How Music videos help the sales of Music recordings.» → How do music videos help sell music?', '문항 17 «How are buses and subways less comfortable…» 구두점 정리', 'General Information 쪽 삭제'],
    slides: [
      { t: 'cover', k: 'new', img: '12614', q: 'Test time! You can do it! 💪', story: '20 questions · Answer and explain!', nt: '표지' },
      { t: 'discuss', k: 'fix', img: '12174', small: 'Unit 1', title: 'Questions 1–3', qs: ['1. What are the advantages of playing computer games?', '2. What are the disadvantages of playing computer games?', '3. How do computer games affect students?'], src: '문항 1–3', nt: '문항 1–3', n: ['<del>How does computer games affect the students</del> → How do computer games affect students'] },
      { t: 'discuss', k: 'fix', img: '17260', small: 'Unit 1 · Unit 2', title: 'Questions 4–6', qs: ['4. Some adults say FPS games are too violent. Do you agree?', '5. How can puzzle games make people smarter?', '6. Do you like the song or the music video more? Why?'], src: '문항 4–6', nt: '문항 4–6', n: ['<del>How can puzzle games can make</del> → How can puzzle games make'] },
      { t: 'discuss', k: 'fix', img: '13279', small: 'Unit 2', title: 'Questions 7–8', qs: ['7. Do you want to be a famous singer? Why or why not?', '8. Would you rather listen to a song with a nice melody but mediocre lyrics, or a song with a mediocre melody but meaningful lyrics?'], src: '문항 7–8', nt: '문항 7–8', n: ['<del>a nice melody and but has mediocre lyrics</del> · <del>a meaningful lyrics</del> 정리'] },
      { t: 'discuss', k: 'fix', img: G('music-video-shoot'), small: 'Unit 2', title: 'Questions 9–10', qs: ['9. How do music videos help sell music?', '10. What makes a song a hit?'], src: '문항 9–10', nt: '문항 9–10', n: ['<del>How Music videos help the sales of Music recordings.</del> → How do music videos help sell music?', '10번 «What qualifies a song as a hit?» → What makes a song a hit?(쉬운 말)'] },
      { t: 'discuss', k: 'keep', img: '12492', small: 'Unit 3', title: 'Questions 11–13', qs: ['11. Do you want to be a professional athlete? Why or why not?', '12. How do athletes get so good? Is it stressful?', '13. What does "There\'s no I in team" mean?'], src: '문항 11–13', nt: '문항 11–13' },
      { t: 'discuss', k: 'keep', img: '14725', small: 'Unit 3', title: 'Questions 14–15', qs: ['14. Some sports need more teamwork than others. Can you give examples?', '15. How do players show good sportsmanship?'], src: '문항 14–15', nt: '문항 14–15' },
      { t: 'discuss', k: 'fix', img: '15763', small: 'Unit 4', title: 'Questions 16–18', qs: ['16. Does your family own a car? Why do some people drive instead of taking public transportation?', '17. How are buses and subways less comfortable or convenient than taxis?', '18. Which types of transportation do you prefer? Why?'], src: '문항 16–18', nt: '문항 16–18' },
      { t: 'discuss', k: 'keep', img: '14055', small: 'Unit 4', title: 'Questions 19–20', qs: ['19. What happens if the infrastructure is not good enough?', '20. What infrastructure improvements are there in your city?'], src: '문항 19–20', nt: '문항 19–20' },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–7', 'Good try!', '틀린 단원(Unit 1·2·3·4)을 한 번 더 복습해요'], ['8–13', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['14–19', 'Great!', '이유를 한 문장 더 붙여 말해 봐요'], ['20 ⭐', 'Perfect!', 'BTS 34 로 출발! 🎉']], src: '점수표 (Congratulations)', nt: '점수표', n: ['20문항이라 구간을 넷으로 · 점수마다 다음에 할 일을 적어 «점수로 끝나지 않게»'] },
      ...close([['I can talk about computer games.', 'I think puzzle games make us smarter.'], ['I can talk about music and sports.', 'A song becomes a hit when everyone sings along.'], ['I can compare kinds of transportation.', 'Taxis are more comfortable than buses.']], { img: '15318', q: 'Would you jump into the lake?', ko: 'BTS 34 예고 — 용기를 내어 도전하기(Taking Risks)!' }),
    ] },
  ],
};
