// BTS 7 새 교재 설계 데이터. k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
// 사진 번호 = photo-catalog.json · 'gen:bts-07-…' = 새로 만들 사진(gen/req-bts-07.json)
import { open, close, HELLO } from '../common.mjs';
const G = s => 'gen:bts-07-' + s;
const HF = 'Unit 1', PB = 'Unit 2', MO = 'Unit 3';
const HSKT = ['Head, shoulders, knees and toes, knees and toes!', 'Head, shoulders, knees and toes, knees and toes!', 'And eyes and ears and mouth and nose.', 'Head, shoulders, knees and toes, knees and toes!'];
const TWISTER = ['Arms, legs, arms, legs,', 'Fingers, toes, arms, legs!', 'Hands, neck, chest, fingers,', 'Toes, arms, legs!'];
const GOAWAY = ['Go away, scary monster!', 'Go away, scary witch!', 'Go away, spooky vampire!', 'Go away, spooky ghost!', 'Go away! Go away!'];
void HELLO;

export const COURSE = {
  head: `<h1>BTS 7 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트에 올라가 있는 BTS 7 원본 <b>276쪽</b>(11묶음 — Head and face · Parts of the body · Monsters · Review · Test)을 한 장씩 읽어 원고로 옮긴 뒤, 한 쪽 한 목표 · 가림→공개 · 규칙 찾기 · 이어지는 이야기 · 과 끝 «I can» · 다음 시간 예고로 다시 짰습니다. 위 단추로 과를 고르세요.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>배우는 <b>낱말(얼굴·몸·괴물 묘사)과 문장(this/these/that/those · his/her/its/their · have/has · How many)</b>은 원본 그대로입니다. 교재 이름도 바꾸지 않습니다. 원본의 오타·문법 오류·어긋난 뜻·사진은 과마다 목록으로 고쳤습니다.</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 표지 + Big Question, 규칙 찾기, ⭕❌, Guess who, 기억·순서 게임, 내 말로 말하기, I can ✅, 다음 시간 예고. <b>괴물 단원은 괴물 그림을 새로 그려</b> 원본이 묻는 특징(뿔 수·눈 수·꼬리)이 그림과 정확히 맞게 했습니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>원본에 있던 <b>웃통 벗은 보디빌더(chest)·속옷 차림 사진</b>은 아이 교재에 맞지 않아 모두 바꿨습니다. 점선 상자는 새로 만들 사진 자리입니다(39장 요청).</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>고친 이야기 승인</b> — 004 해적 이야기 «한 손뿐인 아이가 갈고리를 받는» 장면은 장애를 «문제» 로 다뤄 «높은 선반에 손이 안 닿는» 이야기로 바꿨습니다. 008 «You are fat.» 대화는 몸 평가라 괴물끼리 «꼬리가 두꺼워» 로 순화했습니다. 005 May·Ariel 대화는 앞뒤가 안 맞아 다시 썼습니다.</li>
<li><b>괴물 이름</b> — 009 «Purple Devil» 은 «Purple Spike» 로 바꿨습니다(종교적 낱말 회피). 008 «Poo-bat» 은 아이들이 좋아해 그대로 뒀습니다 — 바꿀지 결정해 주세요.</li>
<li><b>노래 곡조</b> — Head, Shoulders, Knees and Toes(전래곡)·Go Away Song 곡조의 녹음 방식. 원본 QR·유튜브 주소는 화면판에서 뺐습니다.</li>
<li><b>새 문법 쪽</b> — 목표에만 있고 연습이 없던 «John's ears(소유격 's)»·«mine» 을 001·004 에 한 쪽씩 넣었습니다(TEST 가 «Whose face is this?» 를 묻기 때문). 범위를 넘는다면 빼 주세요.</li>
<li><b>새로 만들 사진 39장</b> — 괴물 그림 15장(원본 괴물 특징대로), 003 왕 이야기 5장, 판다·사자·쌍둥이 등. 원본 원고 OCR 에 007 30쪽이 비어 있어 원본 JPG 로 확인이 필요합니다.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '얼굴·this/these', unit: HF, title: 'Head and Face', orig: 31,
    intro: '얼굴 낱말(head·hair·face·eyes·nose·cheeks·chin·mouth·tongue·teeth·lips·ears·forehead)과 this/these/that/those 를 배웁니다. 이야기: 랄프 코에 흙이 묻었어요!',
    fixed: ['arms «무기» 같은 뜻 오류는 없지만 wipe «닦음» → «닦다»(동사) · earrings 를 «May I borrow <del>it</del> → them»(복수)', '«Grammar» 쪽에 목표의 소유격(John\'s ears)이 연습 없이 목표에만 → 한 쪽 추가', '«(This/These) is my nose» 처럼 동사가 이미 is 라 고르기가 무의미 → 동사까지 빈칸', 'hnic 수수께끼 «___ is my ___» 두 칸이 모두 정답을 몰라도 채워짐 → 한 칸', 'Tommy 인사 «How are you today?» 뒤 주제 안내는 강사 말로 옮김', '쉼표·물음표 앞 띄어쓰기 여러 곳'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-mirror'), q: 'What is on your face?', story: 'Ralph, Hera and Amy make funny faces in the mirror!', nt: '표지 + Big Question', n: ['얼굴에 무엇이 있을까? — 끝날 때 영어로 5개 이상 말하는 것이 목표', '화상수업: 학생도 카메라에 대고 웃긴 표정 한 번'] },
      ...open([['I can name the parts of my face.', '얼굴 부분을 영어로 말할 수 있어요.'], ['I can say "This is my nose." and "These are my eyes."', '하나는 this, 여럿은 these 로 말해요.'], ["I can say \"John's ears\".", '누구의 것인지 \'s 로 말할 수 있어요.']], 'Lesson Goals (문법 용어 나열)'),
      { t: 'song', k: 'keep', title: 'Head, Shoulders, Knees and Toes', lines: HSKT, img: G('headshoulders'), src: 'Warm Up', nt: '몸 노래', n: ['노래하며 그 부분을 손으로 짚습니다 — 두 번째는 더 빠르게', '전래곡이라 곡조 저작권 부담이 적습니다(녹음 방식은 결정 필요)'] },
      { t: 'vocab', k: 'fix', hide: true, words: [['head', '머리', '16509'], ['hair', '머리카락', '13008'], ['face', '얼굴', '12618'], ['eyes', '눈', '12953'], ['nose', '코', '15173'], ['mouth', '입', '16159']], src: 'Vocabulary', nt: '낱말 1 — 뜻 가리고 먼저', n: ['뜻을 가리고 사진만 보고 영어로 먼저 말하기', '학생이 자기 얼굴을 짚으며 말하게 합니다'] },
      { t: 'vocab', k: 'keep', words: [['head', '머리', '16509'], ['hair', '머리카락', '13008'], ['face', '얼굴', '12618'], ['eyes', '눈', '12953'], ['nose', '코', '15173'], ['mouth', '입', '16159']], title: 'Words 1', nt: '낱말 1 — 공개' },
      { t: 'vocab', k: 'fix', hide: true, words: [['cheeks', '볼', '15336'], ['chin', '턱', '18738'], ['lips', '입술', '16814'], ['teeth', '이', '16894'], ['tongue', '혀', '18744'], ['ears', '귀', '12923'], ['forehead', '이마', '16161'], ['eyebrows', '눈썹', '19070']], cols: 4, src: 'Vocabulary', nt: '낱말 2 — 뜻 가리고 먼저', n: ['eyebrows 는 원본 목표에만 있고 낱말 쪽에 없어 함께 넣었습니다'] },
      { t: 'vocab', k: 'keep', words: [['cheeks', '볼', '15336'], ['chin', '턱', '18738'], ['lips', '입술', '16814'], ['teeth', '이', '16894'], ['tongue', '혀', '18744'], ['ears', '귀', '12923'], ['forehead', '이마', '16161'], ['eyebrows', '눈썹', '19070']], cols: 4, title: 'Words 2', nt: '낱말 2 — 공개' },
      { t: 'rule', k: 'new', title: 'This or these?', left: { h: 'One', ex: ['**This** is my nose.', '**This** is my chin.'] }, right: { h: 'Two or more', ex: ['**These** are my eyes.', '**These** are my ears.'] }, q: 'When do we say "these"?', nt: '규칙 찾기 — 가까이', n: ['설명 전에 두 묶음을 보고 규칙을 먼저 말하게 합니다', '하나 → this is · 여럿 → these are'] },
      { t: 'rule', k: 'fix', title: 'That or those?', left: { h: 'One (far)', ex: ['**That** is his mouth.', '**That** is her nose.'] }, right: { h: 'Two or more (far)', ex: ['**Those** are his eyes.', '**Those** are her ears.'] }, q: 'Is it near me or far from me?', src: 'Grammar (Demonstratives)', nt: '규칙 찾기 — 멀리', n: ['원본 예문 «That is an apple / Those are apples» 는 얼굴 단원과 따로 놀아 얼굴 예문으로 바꿨습니다', '화면 속 선생님 얼굴 = 멀리(that), 내 얼굴 = 가까이(this)'] },
      { t: 'table', k: 'new', small: 'Whose?', title: "John's ears", head: ['the … of …', '= …\'s'], rows: [['the ears of John', "John's ears"], ['the nose of Hera', "Hera's nose"], ['the face of the dog', "the dog's face"]], tip: "Whose nose is this? — It's Hera's nose.", src: '목표에만 있던 소유격', nt: '누구의 것 — \'s', n: ['원본 목표에 있었지만 연습 쪽이 없었고 TEST 에 «Whose face is this?» 가 나옵니다 → 한 쪽 추가', '학생 이름으로 바꿔 말하기: «Minji\'s hair»'] },
      { t: 'scramble', k: 'keep', items: [['dhea', '16509'], ['yees', '12953'], ['oens', '15173'], ['esra', '12923'], ['hceesk', '15336'], ['mhuot', '16159']], src: 'Unscramble 쪽들', nt: '글자 섞기', n: ['원본은 한 쪽에 하나씩 10쪽 → 6개를 한 쪽에 모았습니다(나머지 넷은 다음 쪽 수수께끼로)'] },
      { t: 'qa', k: 'fix', img: '13082', label: 'Riddle', title: 'What are these?', q: 'When I listen to music, I use them.', a: '___ are my ___.', src: 'esra 쪽', nt: '수수께끼 1', n: ['사진은 음악 듣는 사람 — 답(ears)이 글로 보이지 않게'] },
      { t: 'qa', k: 'fix', img: '12131', label: 'Riddle', title: 'What are these?', q: 'I bite apples with these. What are they?', a: '___ are my ___.', src: 'hteet 쪽', nt: '수수께끼 2' },
      { t: 'qa', k: 'fix', img: '16174', label: 'Riddle', title: 'What is this?', q: 'It opens when I talk. It opens when I yawn!', a: '___ is my ___.', src: 'mhuot 쪽', nt: '수수께끼 3', n: ['«It opens when I talk» 에 하품 사진으로 재미를 더했습니다', '원본 «(This/These) is» → 동사까지 빈칸(고르기가 의미 있게)'] },
      { t: 'guess', k: 'new', img: '19697', open: [1, 4], q: 'What is he doing? Which part is it?', chips: ['These are his ears.', 'This is his mouth.', 'That is his nose.'], nt: 'Guess who 타일', n: ['귀를 움직이려는 아이 — 타일을 열며 무엇이 보이는지 this/these 로 말하기'] },
      { t: 'ox', k: 'new', img: '19070', s: 'These are his cheeks.', nt: '⭕❌', n: ['정답 ❌ → «No! These are his eyebrows.» 까지 말하면 성공'] },
      { t: 'story', k: 'fix', small: 'Story', title: "What's on your nose?", img: G('dirtnose'), lines: [['Ralph', 'Hello, Hera and Amy!'], ['Hera', "Hi, Ralph! What's on your nose?"], ['Ralph', 'Whose nose? Mine?'], ['Hera', "Yes, Ralph. There's dirt on your nose."], ['Amy', 'Let me wipe it for you.'], ['Ralph', 'Thank you, Amy!']], src: 'Role-play', nt: '이야기 1 — 코에 흙', n: ['원본은 Hera 가 «Let me wipe it» 하고 Ralph 가 «Thank you, Hera!» — 질문 «Who wiped the dirt?» 의 답이 너무 뻔해 Amy 가 닦게 바꿨습니다', '새 낱말: dirt 먼지·흙 · wipe 닦다'] },
      { t: 'story', k: 'fix', small: 'Story', title: 'Pretty earrings!', img: G('earrings'), lines: [['Hera', 'Can you see my earrings?'], ['Amy', 'Oh! They look pretty.'], ['Ralph', 'I agree!'], ['Amy', "May I borrow them for tomorrow's party?"], ['Hera', 'Sure!']], src: 'Role-play', nt: '이야기 2 — 귀걸이', n: ['<del>May I borrow it</del> → them (earrings 는 둘)', '원본은 Amy 가 «Oh!» 와 «I agree!» 를 연달아 말함 → I agree 는 Ralph 에게', '새 낱말: earrings 귀걸이 · borrow 빌리다 · party 파티'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ["Whose nose has dirt? — ___ nose has dirt.", 'Who wiped the dirt? — ___ wiped it.', 'What does Hera have? — She has pretty ___.'], chips: ["Ralph's", 'Amy', 'earrings'], src: 'Questions', nt: '이야기 질문', n: ['첫 질문은 소유격 \'s 를 쓰게 만듭니다'] },
      { t: 'memory', k: 'new', title: 'What is missing?', items: ['12953', '15173', '16159', '12923', '15336', '16161'], q: 'Look for 10 seconds. What is gone?', a: 'The ___ is gone!', nt: '기억 게임', n: ['10초 보여 준 뒤 강사가 한 장을 가리고 무엇이 없어졌는지 말하기'] },
      { t: 'yourturn', k: 'fix', img: '18738', title: 'My face', lines: ['This is my ___.', 'These are my ___.', "That is my teacher's ___."], chips: ['nose', 'eyes', 'chin', 'ears'], src: 'Game (face chart)', nt: '내 얼굴 말하기', n: ['원본 «얼굴 도표 채우기» → 자기 얼굴을 짚으며 말하기', '마지막 줄은 화면 속 선생님 얼굴(멀리 = that)'] },
      ...close([['I can name the parts of my face.', 'hair, eyes, nose, mouth, chin…'], ['I can use this and these.', 'This is my nose. These are my eyes.'], ["I can use 's.", "Whose nose? It's Ralph's nose."]], { img: G('panda'), q: 'Whose eyes are those?', ko: '저 눈은 누구의 눈일까요? (002에서 만나요)' }),
    ] },
  // ───────────────────────── 002
  { code: '002', tab: 'his·her·its·their', unit: HF, title: 'Head and Face', orig: 30,
    intro: '«It\'s his nose. / These are their cheeks.» — 누구의 얼굴인지 his·her·its·their 로 말합니다. 선생님과 학생이 얼굴 퀴즈를 주고받습니다.',
    fixed: ['«Very Good!» → Very good!', '002 첫 쪽 «Let\'s practice!» 대화의 빈칸이 앞 문장에 정답을 보여 줌(What are those? → Those are ears.) → 사진 보고 답하게', '거미 질문 «How many eyes does a spider have?» 가 판다 쪽에 붙어 있음 → 거미 사진 쪽으로', '«This ___ her ___»(tongue) 사진이 입술 사진 → 혀가 보이는 사진', '게임 상자 낱말이 문장보다 먼저 정답 순서로 나열됨 → 섞음'],
    slides: [
      { t: 'cover', k: 'new', img: G('lion'), q: 'Whose mouth is this?', story: 'Look! Big mouths, long tongues and funny cheeks!', nt: '표지 + Big Question' },
      ...open([['I can say "his", "her", "its" and "their".', '누구의 얼굴인지 말할 수 있어요.'], ['I can ask "What is that?" and "What are those?"', '멀리 있는 것을 물을 수 있어요.'], ['I can answer about a face.', 'They are its eyes.']]),
      { t: 'story', k: 'fix', small: "Let's practice!", title: 'Are you ready?', img: '12229', lines: [['Teacher', "Let's practice! Are you ready?"], ['Anne', 'Yes, teacher. I am ready!'], ['Teacher', 'What is this?'], ['Anne', "It's your ___."], ['Teacher', 'Correct! What are those?'], ['Anne', 'Those are your ___.']], src: '대화 1', nt: '선생님과 연습 1', n: ['강사가 자기 얼굴을 짚으며 묻습니다 — 빈칸은 짚은 곳에 따라', '원본 «Those are ears.» → your ears(누구의 것인지 붙이기)'] },
      { t: 'story', k: 'fix', small: "Let's practice!", title: 'Now you ask!', img: '16193', lines: [['Anne', 'Teacher, what are those?'], ['Teacher', 'These are my ___.'], ['Anne', 'I knew it! What is that?'], ['Teacher', "It's her ___."], ['Anne', 'Wow, I am smart!'], ['Teacher', "Yes, you're very smart!"]], src: '대화 2', nt: '역할 바꾸기 — 학생이 묻기', n: ['이번엔 학생이 질문자 — «Very Good!» 은 Very good! 으로', '«It\'s her ___» 는 사진 속 소녀의 턱을 가리킵니다'] },
      { t: 'rule', k: 'new', title: 'Whose face?', left: { h: 'one person / animal', ex: ["It's **his** nose. (boy)", "It's **her** chin. (girl)", 'They are **its** eyes. (panda)'] }, right: { h: 'two or more', ex: ['These are **their** cheeks.', 'Those are **their** teeth.'] }, q: 'Who has it? Look at the picture first!', nt: '규칙 찾기 — 누구의 것', n: ['사진 속 주인이 누구인지 먼저 보고 his/her/its/their 를 고르게 합니다'] },
      { t: 'qa', k: 'keep', img: '16161', q: 'What is it?', a: "It's ___ ___.", chips: ['his', 'her', 'forehead'], src: '이마 쪽', nt: 'his', n: ['덤 질문: «Can you show me your forehead?»'] },
      { t: 'qa', k: 'fix', img: '15173', q: 'Whose is it?', a: "It's ___ nose.", src: '코 쪽', nt: 'his/her' },
      { t: 'qa', k: 'fix', img: G('panda'), q: 'What are they?', a: 'They are ___ ___.', chips: ['its', 'their', 'eyes'], src: '판다 쪽', nt: 'its', n: ['동물은 its — 원본 «(its eyes)» 정답 그대로', '판다는 새 사진(눈 둘레 까만 판다 얼굴)'] },
      { t: 'count', k: 'fix', img: '16162', q: 'How many eyes does a spider have?', a: 'It has ___ eyes!', chips: ['two', 'eight'], src: '판다 쪽 덤 질문', nt: '재미 질문 — 거미 눈', n: ['원본은 판다 사진에 거미 질문 → 거미 사진으로 옮겼습니다', '정답: 대부분 eight — 학생이 놀라는 순간을 즐기세요'] },
      { t: 'qa', k: 'fix', img: G('twins'), q: 'What are these?', a: 'These are ___ ___.', chips: ['their', 'cheeks'], src: '쌍둥이 쪽', nt: 'their' },
      { t: 'qa', k: 'keep', img: '12618', q: 'What is this?', a: '___ is his ___.', src: '얼굴 쪽', nt: 'his' },
      { t: 'qa', k: 'keep', img: '19050', q: 'What are those?', a: 'Those are ___ ___.', src: '귀 쪽', nt: 'her', n: ['귀걸이를 하는 여자 — 001 이야기의 earrings 를 다시 떠올리게'] },
      { t: 'qa', k: 'fix', img: '18744', q: 'What is he catching the snow with?', a: 'This ___ his ___.', src: '혀 쪽', nt: '❗ 사진 교체', n: ['원본: 입술 사진에 «tongue» → 눈송이를 혀로 받는 아이', '원본은 her → 사진에 맞게 his'] },
      { t: 'qa', k: 'keep', img: '16894', q: 'What are these?', a: 'These are ___ ___.', src: '이 쪽', nt: 'his/her' },
      { t: 'qa', k: 'keep', img: 'c7123', q: 'What is it? What color is it?', a: '___ is ___ ___.', src: '머리카락 쪽', nt: 'her' },
      { t: 'qa', k: 'fix', img: G('lion'), q: 'What is this? Does it have a big mouth?', a: 'This is ___ mouth.', chips: ['his', 'its'], src: '사자 쪽', nt: 'its' },
      { t: 'qa', k: 'keep', img: 'c7082', q: 'What are those? What color are they?', a: '___ are ___ lips.', src: '입술 쪽', nt: 'her' },
      { t: 'guess', k: 'new', img: '16172', open: [0, 5], q: 'Whose smile is this?', chips: ["It's her mouth.", 'These are her teeth.', 'Those are her cheeks.'], nt: 'Guess who 타일', n: ['열린 칸마다 his/her/its/their 문장 하나'] },
      { t: 'ox', k: 'new', img: G('panda'), s: 'These are her eyes.', nt: '⭕❌', n: ['정답 ❌ → «No! They are its eyes.» (동물은 its)'] },
      { t: 'match', k: 'fix', left: ['16161', '12953', '12923', '16159'], right: ['These are her ears.', 'That is his forehead.', 'This is her mouth.', 'Those are his eyes.'], src: 'Game', nt: '짝 맞추기', n: ['원본 게임(낱말 상자 채우기) → 사진과 문장 잇기로', '짝이 사진 주인과 맞는지(his/her) 한 번 더 확인'] },
      { t: 'fill', k: 'fix', small: 'Game', title: 'Fill it in!', lines: ['___ are his eyes.', 'This is ___ nose. (a dog)', 'These ___ her ears.', 'That is her ___. (above the eyes)'], chips: ['forehead', 'its', 'are', 'Those'], src: 'Game', nt: '빈칸 게임', n: ['원본 상자 낱말이 정답 순서대로 → 섞었습니다'] },
      { t: 'yourturn', k: 'new', img: '16508', title: 'My friend', lines: ["These are my friend's ___.", 'His / Her ___ is big.', 'Those are my teacher\'s ___.'], nt: '내 말로', n: ['가족·친구 사진을 카메라에 비추며 말하게 하면 더 좋습니다'] },
      ...close([['I can say his, her, its and their.', "It's his nose. They are its eyes."], ['I can ask about faces.', 'What is that? What are those?'], ['I can answer about a face.', 'These are their cheeks.']], { img: G('king-film'), q: 'What does the king need?', ko: '임금님에게 무엇이 필요할까요? (003에서 만나요)' }),
    ] },
  // ───────────────────────── 003
  { code: '003', tab: '임금님 돕기', unit: HF, title: 'Head and Face', orig: 19,
    intro: '임금님을 도와요! «I want to …» 에 «I need my …» 로 답하며 얼굴 낱말을 씁니다. 끝에 선생님·친구 얼굴을 그려 말합니다.',
    fixed: ['smell «냄새» → «냄새 맡다»(동사로 쓰임) · watch «손목시계» → «보다» · film «필름» → «영화» · clear «명확한» → «(코를) 뚫다»', '«I want to watch a film» 쪽 사진이 콘서트 → 영화 보는 임금님', '«I need my ___, ___ and ___»(피자) 세 빈칸 정답 순서가 없어 채점이 흔들림 → 순서 자유를 강사 메모에', '«Let me clear my ___» 에 향수 사진 → 꽃 냄새 맡는 장면'],
    slides: [
      { t: 'cover', k: 'new', img: G('king-film'), q: 'Can you help the king?', story: 'The king wants many things today. Help him!', nt: '표지 + Big Question' },
      ...open([['I can say "I want to …".', '하고 싶은 것을 말할 수 있어요.'], ['I can say "I need my …".', '필요한 얼굴 부분을 말할 수 있어요.'], ['I can describe a face I draw.', '그린 얼굴을 설명할 수 있어요.']]),
      { t: 'vocab', k: 'fix', hide: true, title: 'New words', words: [['watch', '보다', '18156'], ['film', '영화', '13119'], ['listen', '듣다', '13082'], ['smell', '냄새 맡다', G('king-smell')], ['want', '원하다', '13031'], ['need', '필요하다', G('king-crown')]], src: 'New Words', nt: '새 낱말 — 가리고', n: ['원본 뜻 오류 네 개를 문장 속 뜻으로 고쳤습니다(smell·watch·film·clear)'] },
      { t: 'vocab', k: 'keep', title: 'New words', words: [['watch', '보다', '18156'], ['film', '영화', '13119'], ['listen', '듣다', '13082'], ['smell', '냄새 맡다', G('king-smell')], ['want', '원하다', '13031'], ['need', '필요하다', G('king-crown')]], nt: '새 낱말 — 공개' },
      { t: 'rule', k: 'new', title: 'want and need', left: { h: 'I want to …', ex: ['I want to **watch** a film.', 'I want to **listen** to music.'] }, right: { h: 'I need my …', ex: ['I need my **eyes**.', 'I need my **ears**.'] }, q: 'Which part do you need?', nt: '규칙 찾기', n: ['하고 싶은 일(want to + 동사) ↔ 필요한 몸(need my + 낱말) 짝을 찾게 합니다'] },
      { t: 'qa', k: 'fix', img: G('king-film'), label: 'King', title: '"I want to watch a film."', q: 'What does the king need?', a: 'I need my ___.', src: '1번', nt: '❗ 사진 교체', n: ['원본: 콘서트 사진 → 영화관의 임금님'] },
      { t: 'qa', k: 'fix', img: G('king-pizza'), label: 'King', title: '"I\'m hungry!"', q: 'What does the king need?', a: 'I need my ___, ___ and ___.', src: '2번', nt: '세 개', n: ['정답 mouth, teeth, tongue — 순서는 자유'] },
      { t: 'story', k: 'fix', small: 'King', title: 'Where is my crown?', img: G('king-crown'), lines: [['King', 'Where is my crown?'], ['Jay', 'Here it is, King!'], ['King', 'Thank you! Put it on my ___.'], ['Jay', 'Okay! It looks great.']], src: '3번', nt: '이야기 — 왕관', n: ['원본 한 줄 → 짧은 대화로(Jay 가 도와줌)', '빈칸 정답 head'] },
      { t: 'qa', k: 'keep', img: G('king-music'), label: 'King', title: '"I want to listen to music."', q: 'Help me wear the earphones.', a: 'Put them in my ___.', src: '4번', nt: '귀' },
      { t: 'qa', k: 'fix', img: G('king-smell'), label: 'King', title: '"I want to smell that!"', q: 'What does the king need?', a: 'Let me clear my ___.', src: '5번', nt: '❗ 사진 교체', n: ['원본: 향수병 → 꽃에 코를 대는 임금님', 'clear my nose = 코를 뚫다(킁킁)'] },
      { t: 'ox', k: 'new', img: G('king-music'), s: 'The king needs his eyes to listen to music.', nt: '⭕❌', n: ['정답 ❌ → «No! He needs his ears.»'] },
      { t: 'guess', k: 'new', img: G('king-pizza'), open: [2, 3], q: 'What does the king want to do?', chips: ['He wants to eat pizza.', 'He needs his mouth.'], nt: 'Guess who 타일' },
      { t: 'memory', k: 'new', title: 'King game', items: [G('king-film'), G('king-pizza'), G('king-crown'), G('king-music')], hidden: true, q: 'Which king needs his ears?', a: 'Number ___!', nt: '기억 게임', n: ['네 장을 보여 준 뒤 뒤집고 위치 맞히기'] },
      { t: 'yourturn', k: 'fix', img: '16271', title: 'Draw your teacher!', lines: ['That is your ___.', 'Those are your ___.', 'Your ___ is big!'], src: 'Draw your teacher', nt: '그리고 말하기 1', n: ['학생이 화면 속 선생님을 그리며 that/those + your'] },
      { t: 'yourturn', k: 'keep', img: '12434', title: 'Draw your friend!', lines: ['This is (his / her) ___.', 'These are (his / her) ___.'], src: 'Draw your friend', nt: '그리고 말하기 2' },
      ...close([['I can say "I want to …".', 'I want to listen to music.'], ['I can say "I need my …".', 'I need my ears.'], ['I can describe a face.', 'These are her eyes.']], { img: G('body-tag'), q: 'Can you touch your knees?', ko: '무릎을 짚을 수 있나요? (004 몸 단원 시작)' }),
    ] },
  // ───────────────────────── 004
  { code: '004', tab: '몸·복수', unit: PB, title: 'Parts of the Body', orig: 31,
    intro: '몸 낱말(neck·chest·tummy·arms·hands·fingers·legs·toes·elbows·hips·knees·feet)과 «He has two arms. / They are her hands.» 를 배웁니다. 이야기: 해적 잭이 멜리사를 도와요.',
    fixed: ['❗ arms «무기» → «팔» (뜻 오류)', 'feet/foot «한발/두발» → foot 발(하나) · feet 발(둘 이상)', '«They are ___ knees..» 마침표 둘', '❗ 웃통 벗은 보디빌더 chest 사진 → 달리기 뒤 가슴을 두드리는 아이', '목표의 my/mine 이 본문에 연습 없음 → 한 쪽 추가', '해적 이야기 «I only have one hand … use this hook» → 높은 선반 이야기로(장애를 문제로 다루지 않게 — 사람 결정)', '쉼표·물음표 앞 띄어쓰기 여러 곳'],
    slides: [
      { t: 'cover', k: 'new', img: G('body-tag'), q: 'How many body parts can you name?', story: 'Simon says, "Touch your knees!"', nt: '표지 + Big Question', n: ['시작하자마자 «Simon says» 한 판 — 몸을 움직이며 수업을 엽니다'] },
      ...open([['I can name the parts of my body.', '몸 부분을 영어로 말할 수 있어요.'], ['I can say "He has two arms."', '몇 개 있는지 말할 수 있어요.'], ['I can say "It\'s mine."', '내 것이라고 말할 수 있어요.']], 'Lesson Goals (대명사·소유 대명사 용어)'),
      { t: 'song', k: 'fix', title: 'Tongue Twister', lines: TWISTER, img: '17118', src: 'Warm Up', nt: '빨리 말하기', n: ['원본 «Hand, neck» → Hands, neck (다른 낱말이 모두 복수라 맞춤)', '천천히 → 보통 → 아주 빠르게 세 번'] },
      { t: 'vocab', k: 'fix', hide: true, words: [['neck', '목', '16167'], ['chest', '가슴', G('chest')], ['tummy', '배', G('tummy')], ['arms', '팔', '17118'], ['hands', '손', '16370'], ['fingers', '손가락', '16160']], src: 'Vocabulary', nt: '낱말 1 — 가리고', n: ['❗ arms 뜻 «무기» → «팔»'] },
      { t: 'vocab', k: 'keep', words: [['neck', '목', '16167'], ['chest', '가슴', G('chest')], ['tummy', '배', G('tummy')], ['arms', '팔', '17118'], ['hands', '손', '16370'], ['fingers', '손가락', '16160']], title: 'Words 1', nt: '낱말 1 — 공개' },
      { t: 'vocab', k: 'fix', hide: true, words: [['legs', '다리', '16483'], ['toes', '발가락', '13342'], ['elbows', '팔꿈치', '16188'], ['hips', '엉덩이', G('hips')], ['knees', '무릎', '13069'], ['feet', '발', '16641']], src: 'Vocabulary', nt: '낱말 2 — 가리고', n: ['feet «한발/두발» → «발»'] },
      { t: 'vocab', k: 'keep', words: [['legs', '다리', '16483'], ['toes', '발가락', '13342'], ['elbows', '팔꿈치', '16188'], ['hips', '엉덩이', G('hips')], ['knees', '무릎', '13069'], ['feet', '발', '16641']], title: 'Words 2', nt: '낱말 2 — 공개' },
      { t: 'table', k: 'keep', small: 'One or more', title: 'arm → arms, foot → feet', head: ['one', 'two or more'], rows: [['an arm', 'arms'], ['a knee', 'knees'], ['a foot', '**feet** ❗']], tip: 'foot 만 바뀌어요: two feet', src: 'Plural 표', nt: '복수 표', n: ['원본 8줄 → 규칙 확인용 3줄. foot/feet 를 따로 강조'] },
      { t: 'rule', k: 'fix', title: 'It is or they are?', left: { h: 'one', ex: ["It is his **chest**.", 'It is her **neck**.'] }, right: { h: 'two or more', ex: ['They are her **arms**.', 'They are his **knees**.'] }, q: 'When do we say "they are"?', src: 'Grammar', nt: '규칙 찾기' },
      { t: 'rule', k: 'new', title: 'my or mine?', left: { h: 'my + word', ex: ['This is **my** hand.', 'These are **my** feet.'] }, right: { h: 'mine (alone)', ex: ['This hand is **mine**.', 'Whose feet? **Mine!**'] }, q: 'Which one stands alone?', src: '목표에만 있던 mine', nt: '규칙 찾기 — mine', n: ['원본 목표에 my/mine 이 있었지만 연습 쪽이 없었습니다 → 한 쪽 추가(001 이야기의 «Mine?» 과 이어짐)'] },
      { t: 'qa', k: 'keep', img: 'c7124', q: 'What is it? Is it long?', a: "It's a ___.", src: '목 쪽', nt: 'neck' },
      { t: 'qa', k: 'fix', img: '17118', q: 'What are they? How many?', a: 'They are his ___. He has ___ ___.', src: '팔 쪽', nt: 'they + has', n: ['원본은 her → 사진(소년)에 맞게 his'] },
      { t: 'qa', k: 'keep', img: '16370', q: 'What are they? What about you?', a: 'They are ___ ___. He has ___ hands.', src: '손 쪽', nt: 'hands' },
      { t: 'count', k: 'fix', img: '16558', q: 'How many legs does it have?', a: 'It has ___ legs.', src: '강아지 쪽', nt: 'How many' },
      { t: 'count', k: 'fix', img: G('sixfeet'), q: 'How many feet can you see?', a: 'There are ___ feet.', src: '발 여섯 쪽', nt: '❗ 사진 교체', n: ['원본: 발이 가려 여섯이 안 보임 → 세 아이의 발 여섯 개가 또렷한 사진'] },
      { t: 'qa', k: 'keep', img: '16188', q: 'What is it? How many?', a: "It's an ___. He has two ___.", src: '팔꿈치 쪽', nt: 'an + 모음', n: ['an elbow — 모음 앞 an 을 짚어 줍니다'] },
      { t: 'qa', k: 'fix', img: '13069', q: 'What are they?', a: 'They are ___ knees.', src: '무릎 쪽', nt: '마침표 둘 → 하나' },
      { t: 'count', k: 'keep', img: '16160', q: 'How many fingers are there?', a: 'There are ___ fingers.', src: '손가락 쪽', nt: 'There are' },
      { t: 'story', k: 'fix', small: 'Story', title: 'Jack the pirate', img: G('pirate'), lines: [['Melissa', "Hey, Jack! Aren't you a pirate?"], ['Jack', 'I am. Why do you ask?'], ['Melissa', 'Pirates have only one leg.'], ['Jack', "Well, I'm different. I have two legs!"], ['Melissa', "Ha ha! You're unique."]], src: 'Role-play', nt: '이야기 1 — 다리 둘인 해적', n: ['새 낱말: pirate 해적 · different 다른 · unique 독특한', '«해적은 다리가 하나» 라는 고정관념을 잭이 웃으며 뒤집는 장면'] },
      { t: 'story', k: 'fix', small: 'Story', title: 'I have a problem.', img: G('hook'), lines: [['Melissa', 'I have a problem.'], ['Jack', 'What is it?'], ['Melissa', "My bag is up there. My arms can't reach it."], ['Jack', 'That\'s okay. I can use this hook!'], ['Melissa', 'Thank you, Jack!']], src: 'Role-play', nt: '❗ 이야기 2 — 갈고리', n: ['원본 «I only have one hand.» → 장애를 «문제» 로 다루지 않게 «팔이 안 닿는» 문제로 바꿨습니다(사람 결정)', '새 낱말: problem 문제 · hook 갈고리'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ['Is Jack a pirate? — Yes, he ___.', 'How many legs does Jack have? — He has ___ legs.', 'What did Jack use? — He used a ___.'], chips: ['is', 'two', 'hook'], src: 'Questions', nt: '이야기 질문' },
      { t: 'guess', k: 'new', img: '12021', open: [2, 3], q: 'What can you see?', chips: ['They are his arms.', 'They have six arms.', 'These are her hands.'], nt: 'Guess who 타일' },
      { t: 'ox', k: 'new', img: '16641', s: 'He has two foots.', nt: '⭕❌', n: ['정답 ❌ → «No! He has two feet.» (foot 의 복수)'] },
      { t: 'match', k: 'keep', left: ['16188', '13069', '13342', '16167'], right: ['knees', 'neck', 'elbow', 'toes'], src: 'Game', nt: '짝 맞추기' },
      ...close([['I can name the parts of my body.', 'neck, arms, knees, feet…'], ['I can say how many.', 'He has two arms. There are ten fingers.'], ['I can say mine.', "Whose hand? It's mine!"]], { img: G('poster'), q: 'Can you help May with her project?', ko: '메이의 숙제를 도와줄 수 있나요? (005에서 만나요)' }),
    ] },
  // ───────────────────────── 005
  { code: '005', tab: '몸 그리기', unit: PB, title: 'Parts of the Body', orig: 18,
    intro: '004 낱말로 짧은 대화를 하고, 내 몸을 그려 10문장으로 설명합니다. 이야기: 아리엘이 몸 그림 숙제를 하고, 메이가 도와요.',
    fixed: ['❗ 가슴 사진이 속옷 차림 → 체육복 입은 아이', 'May·Ariel 대화가 앞뒤가 맞지 않음(«What are these?» 에 묻는 사람이 답함, «I only have ___ fingers») → 숙제를 돕는 흐름으로 다시 씀', '복습 쪽 «hand 手» 한자 섞임 → 뺐습니다', '«That\'s unique» 뒤 «I know. Thanks!» 가 누구 말인지 모호함 → 정리'],
    slides: [
      { t: 'cover', k: 'new', img: G('poster'), q: 'How many parts can you draw?', story: 'Ariel has a school project. May helps her!', nt: '표지 + Big Question' },
      ...open([['I can ask "What are these?"', '몸 부분을 물을 수 있어요.'], ['I can say "I have …" and "You have …".', '몇 개 있는지 말해요.'], ['I can describe my body in 10 sentences.', '내 몸을 10문장으로 말할 수 있어요.']]),
      { t: 'story', k: 'fix', small: 'Story', title: 'A school project', img: G('poster'), lines: [['May', 'Hi, Ariel. Are you okay?'], ['Ariel', 'Yes, but I have a school project.'], ['Ariel', 'I need to draw and name the parts of the body.'], ['May', 'Let me help you!']], src: 'Mini conversation', nt: '이야기 1 — 숙제', n: ['원본 앞부분 그대로'] },
      { t: 'story', k: 'fix', small: 'Story', title: 'What are these?', img: '13069', lines: [['Ariel', 'May, what are these?'], ['May', 'They are my ___. I have two ___.'], ['Ariel', 'And what is this?'], ['May', 'This is my chest.'], ['Ariel', 'Correct! You have one ___.']], src: 'Mini conversation', nt: '이야기 2 — 묻고 답하기', n: ['❗ 원본은 묻는 사람이 스스로 답하는 순서 오류 → 아리엘이 묻고 메이가 답하게', '원본 가슴 사진(속옷 차림)은 뺐습니다'] },
      { t: 'story', k: 'fix', small: 'Story', title: 'Ten fingers!', img: '16160', lines: [['Ariel', 'What are those?'], ['May', 'These are my fingers. I have ___ fingers.'], ['Ariel', 'I have ten fingers, too!'], ['May', 'Now you can draw them. Good luck!'], ['Ariel', 'Thanks, May!']], src: 'Mini conversation', nt: '이야기 3 — 손가락', n: ['원본 «I only have ___ fingers. / Wow! That\'s unique.» 는 뜻이 성립하지 않아 «나도 열 개» 로'] },
      { t: 'rule', k: 'new', title: 'have or has?', left: { h: 'I / you / they', ex: ['I **have** two hands.', 'You **have** ten toes.'] }, right: { h: 'he / she / it', ex: ['She **has** two knees.', 'It **has** four legs.'] }, q: 'When do we say "has"?', nt: '규칙 찾기' },
      { t: 'fill', k: 'fix', title: "May's body", img: G('poster'), lines: ['May has two ___.', 'She ___ one chest.', 'She has ___ fingers.', 'I ___ ten fingers, too.'], chips: ['has', 'have', 'ten', 'knees'], nt: '이야기 되짚기', n: ['낱말 칩은 가리고 시작해도 됩니다'] },
      { t: 'memory', k: 'new', title: 'Body memory', items: ['16167', '16188', '13342', '16370', '16483', '13069'], q: 'Which one is gone?', a: 'The ___ are gone!', nt: '기억 게임' },
      { t: 'ox', k: 'new', img: '12885', s: 'The kitten has two legs.', nt: '⭕❌', n: ['정답 ❌ → «No! It has four legs.»'] },
      { t: 'guess', k: 'new', img: '17124', open: [1, 4], q: 'What is she touching?', chips: ['She is touching her knees.', 'They are her hands.'], nt: 'Guess who 타일', n: ['달리고 나서 무릎을 짚은 소녀 — 타일을 열며 몸 부분 말하기'] },
      { t: 'yourturn', k: 'fix', img: '16271', title: 'Draw yourself!', lines: ['This is my head. I have one head.', 'These are my ___. I have ___ ___.', 'I have ___ and ___.'], src: 'Draw yourself', nt: '나를 그리고 10문장', n: ['원본 10문장 과제 그대로 — 화면에는 틀 3개, 학생은 10문장까지'] },
      ...close([['I can ask "What are these?"', 'What are those? They are my knees.'], ['I can say have and has.', 'I have ten fingers. She has two knees.'], ['I can describe my body.', 'This is my head. I have one head.']], { img: '15593', q: 'Whose neck is so long?', ko: '누구 목이 이렇게 길까요? (006에서 만나요)' }),
    ] },
  // ───────────────────────── 006
  { code: '006', tab: '무엇이 보여?', unit: PB, title: 'Parts of the Body', orig: 22,
    intro: '사진을 보고 «I see a … / It has … / There are …» 로 말하고 몸 부분의 수를 셉니다.',
    fixed: ['❗ 보디빌더 가슴 사진(두 번째) → 뺐습니다', '«I ___ ___ dogs. ___ have ___.» 처럼 빈칸이 5개인 문장 → 한 문장 두 칸까지', '«How many heads? I see a ___ and a ___» 사진에 세 사람 → 두 사람 사진', '«(long/short)» 선택지와 빈칸이 같은 문장에 겹침 → 정리'],
    slides: [
      { t: 'cover', k: 'new', img: '15593', q: 'What do you see?', story: 'Look closely and count!', nt: '표지 + Big Question' },
      ...open([['I can say "I see a …".', '보이는 것을 말할 수 있어요.'], ['I can say "There are … legs."', '몸 부분을 세어 말할 수 있어요.'], ['I can say long and short.', '길고 짧은 것을 말할 수 있어요.']]),
      { t: 'rule', k: 'new', title: 'See, have, count!', left: { h: '1. see · 2. have', ex: ['I see a **girl**.', 'She has two **arms**.'] }, right: { h: '3. count', ex: ['I see **three** children.', 'There are **six** arms.'] }, q: 'Say it in three steps!', nt: '세 걸음 말하기', n: ['사진마다 see → have → count 세 문장. 이 과 전체의 틀입니다'] },
      { t: 'qa', k: 'keep', img: '16185', q: 'What do you see?', a: 'I see a ___. He has two ___.', src: '손목 쪽', nt: 'see + have' },
      { t: 'qa', k: 'fix', img: 'c7124', q: 'Is her neck long or short?', a: 'I see a ___. She has a ___ neck.', src: '목 쪽', nt: 'long / short' },
      { t: 'count', k: 'fix', img: '12021', q: 'How many arms and legs?', a: 'I see three ___. There are ___ arms.', src: '세 아이 쪽', nt: '셈 1' },
      { t: 'count', k: 'keep', img: '12885', q: 'How many feet?', a: 'I see a ___. It has ___ feet.', src: '고양이 쪽', nt: '셈 2' },
      { t: 'count', k: 'fix', img: G('kids-knees'), q: 'How many knees?', a: 'I see ___ children. There are ___ knees.', src: '여섯 아이 쪽', nt: '셈 3', n: ['6명 × 2 = 12 — 곱셈을 영어로 말할 기회'] },
      { t: 'count', k: 'fix', img: '16313', q: 'How many ears?', a: 'I see two ___. There are ___ ears.', src: '강아지 둘 쪽', nt: '셈 4', n: ['원본 빈칸 5개 → 2개로'] },
      { t: 'count', k: 'fix', img: '16508', q: 'How many heads?', a: 'I see two ___. There are ___ heads.', src: '머리 수 쪽', nt: '❗ 사진 교체', n: ['원본 문장은 두 사람인데 사진은 세 사람 → 두 사람 사진'] },
      { t: 'search', k: 'new', grid: ['KNEESXARM', 'NECKTOESA', 'HANDSLEGS', 'FEETHIPSQ'], words: ['knees', 'neck', 'toes', 'hands', 'legs', 'hips'], nt: '낱말 찾기', n: ['화상수업: 찾은 낱말을 말하면 강사가 동그라미'] },
      { t: 'guess', k: 'new', img: '15799', open: [0, 3], q: 'Who do you see?', chips: ['I see a man and a boy.', 'The boy has two legs.', 'There are four arms.'], nt: 'Guess who 타일' },
      { t: 'ox', k: 'new', img: '16313', s: 'I see two dogs. There are two ears.', nt: '⭕❌', n: ['정답 ❌ → «There are four ears.»'] },
      { t: 'yourturn', k: 'new', img: '16094', title: 'Look around!', lines: ['I see ___.', 'He / She has ___.', 'There are ___ ___.'], nt: '내 말로 — 세 걸음', n: ['집에 있는 사람·인형을 카메라로 보여 주며 see → have → count'] },
      ...close([['I can say "I see a …".', 'I see a kitten.'], ['I can count body parts.', 'There are twelve knees.'], ['I can say long and short.', 'She has a long neck.']], { img: G('monster-parade'), q: 'Are monsters scary or cute?', ko: '괴물은 무서울까요, 귀여울까요? (007 괴물 단원 시작)' }),
    ] },
  // ───────────────────────── 007
  { code: '007', tab: '괴물·형용사', unit: MO, title: 'Monsters', orig: 31,
    intro: '괴물을 big·small·tall·fat·skinny·thick·thin·scary·cute·silly 로 묘사하고 «The monster has three heads.» 로 말합니다. 이야기: 레슬리와 브록이 괴물 곰 영화를 봤어요.',
    fixed: ['❗ 문법 오류 «The monster have heads.» → The monster has three heads.', '❗ has 를 «linking verb(연결 동사)» 라 설명 · 제목 «Possessive Adjectives» → «have/has» 로 바로잡음', 'fat «지방» → «뚱뚱한» · tall «긴» → «키가 큰» · cute «귀엽다» → «귀여운» · silly «멍청한» → «우스꽝스러운»', '«Does it have horn?» → a horn', '«Yeah I saw it» → Yeah, I saw it. · «two yellow scary eyes» → two scary yellow eyes(형용사 순서)', '원본 괴물 그림과 질문(뿔 수·눈 수)이 맞지 않는 쪽 → 특징대로 새 그림', '⚠️ 원고 OCR 에 30쪽이 비어 있음 — 원본 JPG 확인 필요'],
    slides: [
      { t: 'cover', k: 'new', img: G('monster-parade'), q: 'What does your monster have?', story: 'Monster week! Leslie and Brock see a scary film.', nt: '표지 + Big Question' },
      ...open([['I can describe a monster.', 'big, small, scary, cute…'], ['I can say "It has three eyes."', '괴물에게 무엇이 있는지 말해요.'], ['I can say "It doesn\'t have …".', '없는 것도 말할 수 있어요.']], 'Lesson Goals («Possessive Adjectives» 오표기)'),
      { t: 'song', k: 'keep', title: 'Go Away Song', lines: GOAWAY, img: '15443', src: 'Warm Up', nt: '괴물 노래', n: ['«Go away!» 에서 두 손을 앞으로 쭉 — 무서운 것을 쫓는 몸짓'] },
      { t: 'vocab', k: 'fix', hide: true, words: [['monster', '괴물', '15565'], ['big', '큰', '12103'], ['small', '작은', '12227'], ['tall', '키가 큰', '12520'], ['scary', '무서운', '19246'], ['cute', '귀여운', '12885'], ['silly', '우스꽝스러운', '19605'], ['horn', '뿔', '15803']], cols: 4, src: 'Vocabulary', nt: '낱말 1 — 가리고', n: ['뜻 오류 고침: tall 긴→키가 큰 · cute 귀엽다→귀여운 · silly 멍청한→우스꽝스러운'] },
      { t: 'vocab', k: 'keep', words: [['monster', '괴물', '15565'], ['big', '큰', '12103'], ['small', '작은', '12227'], ['tall', '키가 큰', '12520'], ['scary', '무서운', '19246'], ['cute', '귀여운', '12885'], ['silly', '우스꽝스러운', '19605'], ['horn', '뿔', '15803']], cols: 4, title: 'Words 1', nt: '낱말 1 — 공개' },
      { t: 'rule', k: 'fix', title: 'Opposites', left: { h: 'fat · thick', ex: ['a **fat** monster', 'a **thick** tail'] }, right: { h: 'skinny · thin', ex: ['a **skinny** monster', 'a **thin** tail'] }, q: 'Which monster is skinny? Which tail is thin?', src: 'Vocabulary (fat·skinny·thick·thin)', nt: '반대말 짝', n: ['fat «지방» → «뚱뚱한» · 짝으로 보여 주면 뜻이 바로 보입니다', '사람에게 쓰지 않고 괴물·꼬리에만 씁니다(몸 평가 피하기)'] },
      { t: 'vocab', k: 'new', words: [['fat', '뚱뚱한', G('fat-skinny')], ['skinny', '마른', G('fat-skinny')], ['thick', '두꺼운', G('thick-thin')], ['thin', '가는', G('thick-thin')]], title: 'Words 2', nt: '낱말 2 — 그림으로 확인' },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'The monster has three heads.', head: ['who', 'has / is', 'what'], rows: [['The monster', 'has', 'three heads.'], ['It', 'has', 'two big horns.'], ['It', "doesn't have", 'a nose.']], tip: 'The monster **has** … ✅ (have ❌)', src: 'Grammar', nt: '❗ 문장 틀 — 문법 오류 고침', n: ['원본 «The monster have heads.» 와 «linking verb» 설명을 바로잡았습니다'] },
      { t: 'qa', k: 'fix', img: G('blue-monster'), label: 'Blue Monster', q: 'What is it? Is it scary or cute?', a: "It's a ___. It is ___.", src: 'Blue Monster 1', nt: '괴물 1' },
      { t: 'count', k: 'fix', img: G('blue-monster'), label: 'Blue Monster', q: 'How many horns does it have?', a: 'It has ___ horns.', src: 'Blue Monster 2', nt: '괴물 1 — 셈' },
      { t: 'qa', k: 'keep', img: G('red-cyclops'), label: 'Red Cyclops', q: 'How many eyes does it have?', a: 'It has ___ eye.', src: 'Red Cyclops 1', nt: '괴물 2', n: ['one eye — 단수 eye 에 주의'] },
      { t: 'qa', k: 'keep', img: G('red-cyclops'), label: 'Red Cyclops', q: 'Does it have arms and legs?', a: 'It has two ___ and two ___.', src: 'Red Cyclops 2', nt: '괴물 2 — 팔다리' },
      { t: 'qa', k: 'fix', img: G('purple-m'), label: 'Purple M', q: 'Does it have a horn?', a: "No. It ___ have a horn. It has ___ teeth.", chips: ["doesn't", 'two'], src: 'Purple M', nt: '괴물 3 — 없는 것', n: ['<del>Does it have horn?</del> → a horn'] },
      { t: 'qa', k: 'keep', img: G('blue-elephant'), label: 'Blue Elephant', q: 'How many eyes does it have? Are its ears big?', a: 'It has ___ eyes. Its ears are ___.', src: 'Blue Elephant 1', nt: '괴물 4' },
      { t: 'qa', k: 'fix', img: G('blue-elephant'), label: 'Blue Elephant', q: 'What about its tail? Does it have toes?', a: "Its tail is ___. It ___ have toes.", chips: ['long', "doesn't"], src: 'Blue Elephant 2', nt: '괴물 4 — 꼬리', n: ['원본 «It (has/doesn\'t have) toes» 그대로 — 새 그림은 발가락 없는 발'] },
      { t: 'story', k: 'fix', small: 'Story', title: 'The Monster Bear', img: G('monster-bear-film'), lines: [['Leslie', 'Hey, Brock! Have you seen the new film?'], ['Brock', 'Yeah, I saw it. It\'s called "The Monster Bear."'], ['Leslie', 'Do you think the monster is scary?'], ['Brock', 'Yes! It has a red nose, eight fingers and six toes.'], ['Brock', 'It also has two scary yellow eyes!']], src: 'Role-play', nt: '이야기 1 — 영화', n: ['<del>Yeah I saw it</del> → Yeah, I saw it. · <del>yellow scary eyes</del> → scary yellow eyes', '새 낱말: film·movie 영화 · theater 극장 · real 진짜'] },
      { t: 'story', k: 'keep', small: 'Story', title: 'Is it real?', img: '18710', lines: [['Leslie', 'Yup! I hope that monster is not real.'], ['Brock', "Don't worry. It's just a film!"]], src: 'Role-play', nt: '이야기 2 — 진짜일까?', n: ['영화관에서 놀란 아이들 사진으로 «scary» 감정을 살립니다'] },
      { t: 'fill', k: 'keep', title: 'Questions', lines: ['What is the name of the film? — "The Monster ___."', 'How many fingers does it have? — It has ___ fingers.', 'What color are its eyes? — They are ___.'], chips: ['Bear', 'eight', 'yellow'], src: 'Questions', nt: '이야기 질문' },
      { t: 'guess', k: 'new', img: G('red-cyclops'), open: [4], q: 'Which monster is it?', chips: ['It has one eye.', 'It is red.', 'It has two arms.'], nt: 'Guess who — 괴물 맞히기', n: ['한 칸씩 열며 «It has …» 로 추측. 다 맞히면 이름 말하기'] },
      { t: 'ox', k: 'new', img: G('blue-monster'), s: 'The monster have two horns.', nt: '⭕❌ — 문법', n: ['정답 ❌ → «The monster has two horns.» (원본 오류를 학생이 고치게)'] },
      { t: 'yourturn', k: 'new', img: '19246', title: 'My scary face!', lines: ['I am a ___ monster!', 'I have ___ eyes and ___ horns.', 'Go away!'], chips: ['scary', 'silly', 'cute'], nt: '내 말로 — 괴물 흉내', n: ['학생이 괴물 흉내 내며 자기소개 — 웃음이 나는 활동'] },
      ...close([['I can describe a monster.', 'It is big and scary.'], ['I can say "It has …".', 'It has three eyes.'], ["I can say \"It doesn't have …\".", "It doesn't have toes."]], { img: G('dino'), q: 'Why does the dinosaur wear glasses?', ko: '공룡은 왜 안경을 썼을까요? (008에서 만나요)' }),
    ] },
  // ───────────────────────── 008
  { code: '008', tab: '괴물 묘사', unit: MO, title: 'Monsters', orig: 26,
    intro: '괴물 친구들(Blue Elephant·Dino·Dino-clops·세 머리 Dino·Poo-bat·Furball)을 보고 has/doesn\'t have 로 묘사합니다.',
    fixed: ['❗ «I\'m skinny. / No, you are not. You are fat. / Okay. I am fat.» — 몸 평가를 받아들이는 대화 → 서로 꼬리를 칭찬하는 대화로(사람 결정)', '❗ 세 머리 Dino «How many legs?» 쪽 화살표가 뿔을 가리킴 → 질문을 뿔로', '«It ___ ___ and hands» 빈칸이 정답 없이도 채워짐 → 정리', '괴물 그림과 질문이 어긋난 쪽 → 새 그림'],
    slides: [
      { t: 'cover', k: 'new', img: G('three-head'), q: 'How many heads can a monster have?', story: 'Meet the monster friends!', nt: '표지 + Big Question' },
      ...open([['I can describe a monster.', 'It is cute. It has a long tail.'], ["I can say \"It doesn't have …\".", "It doesn't have a nose."], ['I can ask "Does it have …?"', '괴물에 대해 물을 수 있어요.']]),
      { t: 'story', k: 'fix', small: 'Story', title: 'Nice tail!', img: G('blue-elephant'), lines: [['Blue Elephant', 'Look at my tail!'], ['Dino', 'Wow! Your tail is long and thick.'], ['Blue Elephant', 'Thank you! Your tail is thick, too.'], ['Dino', 'We are tail friends!']], src: 'Mini conversation', nt: '❗ 이야기 — 꼬리 친구', n: ['원본 «You are fat. / Okay. I am fat.» 는 몸 평가라 바꿨습니다(사람 결정)', 'thick/long 을 칭찬 말로 씁니다'] },
      { t: 'qa', k: 'fix', img: G('blue-elephant'), label: 'Blue Elephant', q: 'Is the blue elephant fat or skinny?', a: 'The ___ elephant is ___.', src: 'Blue Elephant', nt: '괴물 1' },
      { t: 'qa', k: 'keep', img: G('dino'), label: 'Dino', q: 'Does it have a big nose?', a: 'It ___ a ___ nose.', src: 'Dino 1', nt: '괴물 2 — 코' },
      { t: 'qa', k: 'keep', img: G('dino'), label: 'Dino', q: 'Is its tongue long or short? Do you have a tail?', a: 'Dino has a ___ tongue.', src: 'Dino 2', nt: '괴물 2 — 혀' },
      { t: 'qa', k: 'keep', img: G('dinoclops'), label: 'Dino-clops', q: 'Does it have a nose?', a: "No. It ___ ___ a nose.", src: 'Dino-clops 1', nt: '괴물 3 — 없는 것' },
      { t: 'qa', k: 'keep', img: G('dinoclops'), label: 'Dino-clops', q: 'Does it have long legs?', a: "No, it ___. It has ___ legs.", src: 'Dino-clops 2', nt: '괴물 3 — 다리' },
      { t: 'count', k: 'fix', img: G('three-head'), label: '3-Headed Dino', q: 'How many horns does it have?', a: 'It has ___ horns, three ___ and one tail.', src: '세 머리 Dino 1', nt: '❗ 질문 고침', n: ['원본 «How many legs?» 인데 화살표가 뿔 → 뿔을 묻게'] },
      { t: 'qa', k: 'keep', img: G('three-head'), label: '3-Headed Dino', q: 'Is it cute or scary?', a: 'It is ___.', src: '세 머리 Dino 2', nt: '의견 말하기', n: ['정답이 없는 질문 — «I think it is cute because …» 로 이유까지'] },
      { t: 'qa', k: 'fix', img: G('poobat'), label: 'Poo-bat', q: 'Does it have arms and hands?', a: "No. It ___ have arms or hands. It has a big ___.", chips: ["doesn't", 'tongue'], src: 'Poo-bat 1', nt: '괴물 5', n: ['부정문에서는 and → or'] },
      { t: 'qa', k: 'keep', img: G('poobat'), label: 'Poo-bat', q: 'Does it have shoes? What color are they?', a: 'Yes, it ___. It has ___ shoes.', src: 'Poo-bat 2', nt: '괴물 5 — 신발' },
      { t: 'qa', k: 'keep', img: G('furball'), label: 'Furball', q: 'What does it have?', a: 'It has ___ eyes, ___ horns and four ___.', src: 'Furball', nt: '괴물 6' },
      { t: 'memory', k: 'new', title: 'Monster memory', items: [G('dino'), G('dinoclops'), G('three-head'), G('poobat'), G('furball'), G('blue-elephant')], hidden: true, q: 'Where is Poo-bat?', a: 'Number ___!', nt: '기억 게임' },
      { t: 'guess', k: 'new', img: G('furball'), open: [0, 2], q: 'Which monster is it?', chips: ['Does it have horns?', 'Does it have a tail?', "It's Furball!"], nt: 'Guess who — 질문으로', n: ['학생이 «Does it have …?» 로 질문해야 칸을 엽니다'] },
      { t: 'ox', k: 'new', img: G('dinoclops'), s: 'Dino-clops has two eyes.', nt: '⭕❌', n: ['정답 ❌ → «No! It has one eye.»'] },
      { t: 'yourturn', k: 'new', img: G('poobat'), title: 'Which is your favorite?', lines: ['My favorite monster is ___.', 'It has ___.', "It doesn't have ___."], nt: '내 말로' },
      ...close([['I can describe a monster.', 'It has a long tail.'], ["I can say \"It doesn't have …\".", "It doesn't have a nose."], ['I can ask "Does it have …?"', 'Does it have horns?']], { img: G('draw-monster'), q: 'What will your monster look like?', ko: '내 괴물은 어떤 모습일까요? (009에서 만들어요)' }),
    ] },
  // ───────────────────────── 009
  { code: '009', tab: '괴물 만들기', unit: MO, title: 'Monsters', orig: 25,
    intro: '괴물을 보고 설명하고, 낱말 순서를 맞춰 문장을 만들고, 끝으로 나만의 괴물을 그려 소개합니다.',
    fixed: ['❗ «It doesn\'t have arms and fingers» → arms or fingers (부정문)', '«It is a circle monster» 어색함 → It is a round monster', '괴물 이름 «Purple Devil» → «Purple Spike»(사람 결정)', '«Do I have ears? It is (skinny/fat)» 처럼 질문과 답이 다른 쪽 → 짝을 맞춤'],
    slides: [
      { t: 'cover', k: 'new', img: G('draw-monster'), q: "Let's make some MONSTERS!", story: 'Draw it, name it and tell your friends!', nt: '표지 + Big Question' },
      ...open([['I can describe a monster.', 'It has two red horns.'], ['I can make sentences in order.', '낱말을 순서대로 놓아 문장을 만들어요.'], ['I can draw and present my monster.', '내 괴물을 그리고 소개해요.']]),
      { t: 'story', k: 'fix', small: 'Monster talk', title: 'Hello there! I am Blue.', img: G('blue-dragon'), lines: [['Blue', 'Hello there! I am Blue.'], ['Blue', 'I have ___ horns.'], ['Blue', 'Is my tail thick?'], ['Mango', 'Yes! It has a ___ ___.']], src: 'Blue', nt: '괴물 1 — 자기소개', n: ['괴물이 1인칭으로 말하고 학생이 3인칭으로 답합니다(I have ↔ It has)'] },
      { t: 'qa', k: 'keep', img: G('green-horn'), label: 'Green Horn', q: 'Does it have a nose?', a: "It ___ have a ___. The monster has two ___.", src: 'Green Horn', nt: '괴물 2' },
      { t: 'qa', k: 'fix', img: G('blue-egg'), label: 'Blue Egg', q: 'Do I have fingers and toes?', a: "It ___ have ___ or ___.", src: 'Blue Egg 1', nt: '괴물 3 — 없는 것', n: ['부정문은 or'] },
      { t: 'qa', k: 'keep', img: G('blue-egg'), label: 'Blue Egg', q: 'What color is my tongue?', a: 'It ___ a ___ tongue.', src: 'Blue Egg 2', nt: '괴물 3 — 혀' },
      { t: 'qa', k: 'fix', img: G('purple-spike'), label: 'Purple Spike', q: 'Do I have ears? Am I skinny or fat?', a: "It ___ have ears. It is ___.", src: 'Purple Devil 1', nt: '괴물 4 — 짝 맞춤', n: ['원본은 «Do I have ears?» 에 «It is (skinny/fat)» 만 → 두 질문으로'] },
      { t: 'qa', k: 'keep', img: G('purple-spike'), label: 'Purple Spike', q: 'Do I have a tail?', a: 'It has ___ fingers and ___ legs.', src: 'Purple Devil 2', nt: '괴물 4 — 손가락' },
      { t: 'order', k: 'keep', img: G('purple-m'), words: ['horns', 'It', 'red', 'has', 'two'], src: 'Rearrange 1', nt: '순서 맞추기 1', n: ['정답: It has two red horns. (수 → 색 → 낱말 순서)'] },
      { t: 'order', k: 'fix', img: G('blue-egg'), words: ['or', 'arms', "doesn't", 'fingers', 'It', 'have'], src: 'Rearrange 2', nt: '순서 맞추기 2', n: ['정답: It doesn\'t have arms or fingers. (원본 and → or)'] },
      { t: 'order', k: 'fix', img: G('blue-egg'), words: ['round', 'is', 'a', 'It', 'monster'], src: 'Rearrange 3', nt: '순서 맞추기 3', n: ['원본 «circle monster» → round monster'] },
      { t: 'order', k: 'keep', img: G('purple-spike'), words: ['legs', 'has', 'thin', 'It'], src: 'Rearrange 4', nt: '순서 맞추기 4' },
      { t: 'guess', k: 'new', img: G('blue-dragon'), open: [1, 5], q: 'Which monster is it?', chips: ['It has a thick tail.', 'It has two horns.', "It's Blue!"], nt: 'Guess who' },
      { t: 'ox', k: 'new', img: G('green-horn'), s: 'Green Horn has a big nose.', nt: '⭕❌', n: ["정답 ❌ → «No! It doesn't have a nose.»"] },
      { t: 'yourturn', k: 'keep', img: '15197', title: 'Draw it!', lines: ['Draw a monster with one head and four big eyes.', 'Draw a monster with four arms, two legs and ten fingers.'], src: 'Draw 1·2', nt: '듣고 그리기', n: ['강사가 읽어 주면 학생이 그리고 화면에 보여 줍니다'] },
      { t: 'yourturn', k: 'keep', img: G('draw-monster'), title: 'My monster!', lines: ['This is ___.', 'It has ___ and ___.', "It doesn't have ___.", 'It is ___!'], chips: ['scary', 'cute', 'silly'], src: 'Draw your monster', nt: '나만의 괴물 발표', n: ['이 권의 마지막 말하기 — 얼굴·몸·형용사를 모두 씁니다'] },
      ...close([['I can describe a monster.', 'It has two red horns.'], ['I can make sentences in order.', 'It has thin legs.'], ['I can present my monster.', 'This is Spiky. It has four eyes.']], { img: '15565', q: 'Review time! Are you ready?', ko: '다음 시간은 BTS 7 복습 — 준비됐나요?' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 7 Review', orig: 21,
    intro: 'BTS 7 전체 복습. 얼굴 → 몸 → 괴물 세 단계를 깨고 보스 괴물을 맞힙니다.',
    fixed: ['❗ 보디빌더 가슴 사진(세 번째) → 뺐습니다', '«This is my head» 인데 사진은 다른 사람 → «This is his head»', '«What are they? … It\'s a ___ (tail)» 질문과 답의 수가 안 맞음 → 짝 맞춤', '«They ___ their ___»(발) 두 빈칸 → 하나로'],
    slides: [
      { t: 'cover', k: 'new', img: '15565', q: 'How much do you remember?', story: '3 stages and a boss monster. Can you win? ⭐', nt: '표지' },
      { t: 'song', k: 'keep', title: 'Go Away Song', lines: GOAWAY, img: '15684', src: 'Warm Up', nt: '노래로 시작' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 1 · Face 🔒', words: [['hair', '머리카락', '13008'], ['forehead', '이마', '16161'], ['cheeks', '볼', '15417'], ['chin', '턱', '16193'], ['lips', '입술', 'c7082'], ['tongue', '혀', '18744']], nt: '1단계 — 얼굴(001~003)', n: ['복습은 일부러 다른 사진'] },
      { t: 'qa', k: 'fix', img: '16509', q: 'What is this?', a: 'This is ___ head.', src: '머리 쪽', nt: '❗ his', n: ['원본 «This is my head» 인데 사진은 다른 아이 → his'] },
      { t: 'qa', k: 'keep', img: '12885', q: 'What are those?', a: 'Those are ___ ___.', src: '고양이 눈 쪽', nt: 'its' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 2 · Body 🔒', words: [['neck', '목', '15593'], ['arms', '팔', '19293'], ['elbow', '팔꿈치', '16188'], ['knees', '무릎', '17124'], ['toes', '발가락', '13342'], ['feet', '발', '15413']], nt: '2단계 — 몸(004~006)' },
      { t: 'count', k: 'fix', img: '16641', q: 'Whose feet are they?', a: 'They are ___ feet.', src: '발 쪽', nt: '빈칸 하나로' },
      { t: 'count', k: 'keep', img: '16160', q: 'How many fingers can you see?', a: 'I see ___ fingers.', src: '손가락 쪽', nt: 'How many' },
      { t: 'count', k: 'keep', img: '16558', q: 'How many legs does the dog have?', a: 'It has ___ legs.', src: '강아지 쪽', nt: 'has' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 3 · Monsters 🔒', words: [['horns', '뿔', G('blue-monster')], ['tail', '꼬리', G('blue-elephant')], ['fat', '뚱뚱한', G('fat-skinny')], ['thin', '가는', G('thick-thin')], ['scary', '무서운', '19246'], ['cute', '귀여운', G('furball')]], nt: '3단계 — 괴물(007~009)' },
      { t: 'qa', k: 'fix', img: G('three-head'), q: 'How many heads does Dino have? What are these?', a: 'It has ___ heads. They are ___.', src: '세 머리 Dino 쪽', nt: '짝 맞춤', n: ['원본 «What are they? → It\'s a ___» 수 불일치 → They are horns'] },
      { t: 'qa', k: 'keep', img: G('purple-m'), q: 'Does it have a horn?', a: "No, it ___. It ___ have a horn.", src: 'Purple M 쪽', nt: "doesn't" },
      { t: 'qa', k: 'keep', img: G('dinoclops'), q: 'Does it have long legs?', a: 'No, it ___. It has ___ legs.', src: 'Dino-clops 쪽', nt: '반대말' },
      { t: 'guess', k: 'new', img: G('furball'), open: [], q: 'Boss! Which monster is it?', chips: ['Does it have horns?', 'How many eyes does it have?', 'Is it scary?'], nt: '보스 문제', n: ['칸을 열 때마다 질문 하나 — 이 권의 질문을 모두 쓰게 됩니다'] },
      { t: 'ican', k: 'new', items: [['I can talk about faces.', 'These are her eyes. That is his nose.'], ['I can talk about bodies.', 'He has two arms. There are ten toes.'], ['I can describe monsters.', "It has three heads. It doesn't have a nose."]], nt: 'BTS 7 전체 I can' },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 7 Unit Test', orig: 21,
    intro: '14문항 단원 시험. 화상수업에서 말로 보는 시험이라 문항마다 «말로 답하기» 를 기준으로 했습니다.',
    fixed: ['❗ 문항 10 보디빌더 가슴 사진 → 체육복 입은 아이', '문항 1 사진(남자 턱) → 턱이 또렷한 소녀(she) · 문항 8 «Whose arms» 인데 사진은 팔 하나 → arm', '문항 13 «What does the monster not have?» → What doesn\'t the monster have?', 'General Information 쪽 때문에 쪽 번호가 어긋남 → 시험지에서 뺐음', '문항 4 «Whose face is this?» 는 소유격(\'s) — 001 에 연습 쪽을 새로 넣어 대비'],
    slides: [
      { t: 'cover', k: 'new', img: '17395', q: 'Test time! You can do it! 💪', story: '14 questions', nt: '표지' },
      { t: 'qa', k: 'keep', img: '18738', title: '1.', q: 'What does she have?', a: 'She has a ___.', src: '문항 1', nt: '문항 1', n: ['원본 사진은 남자 → 턱이 또렷한 사진(she)'] },
      { t: 'count', k: 'keep', img: '12953', title: '2.', q: 'How many eyes does she have?', a: 'She has ___ eyes.', src: '문항 2', nt: '문항 2' },
      { t: 'qa', k: 'keep', img: '12923', title: '3.', q: 'What are these?', a: 'These are ___.', src: '문항 3', nt: '문항 3' },
      { t: 'qa', k: 'keep', img: '12037', title: '4.', q: 'Whose face is this?', a: "It's the ___ face.", src: '문항 4', nt: '문항 4 — \'s', n: ["정답 the rabbit's face"] },
      { t: 'qa', k: 'keep', img: G('twins'), title: '5.', q: 'Whose cheeks are those?', a: 'Those are ___ cheeks.', src: '문항 5', nt: '문항 5' },
      { t: 'qa', k: 'keep', img: '16188', title: '6.', q: 'What is it? How many do you have?', a: "It's an ___. I have ___.", src: '문항 6', nt: '문항 6' },
      { t: 'count', k: 'keep', img: '16160', title: '7.', q: 'How many fingers does she have?', a: 'She has ___ fingers.', src: '문항 7', nt: '문항 7' },
      { t: 'qa', k: 'keep', img: '19293', title: '8.', q: 'Whose arm is it?', a: "It's ___ arm.", src: '문항 8', nt: '문항 8', n: ['원본은 «arms» 인데 사진은 팔 하나 → arm'] },
      { t: 'count', k: 'keep', img: '16370', title: '9.', q: 'What are these? How many are there?', a: 'They are ___. There are ___.', src: '문항 9', nt: '문항 9' },
      { t: 'qa', k: 'fix', img: G('chest'), title: '10.', q: 'How many chests does he have?', a: 'He has ___ chest.', src: '문항 10', nt: '❗ 사진 교체', n: ['원본: 웃통 벗은 보디빌더 → 체육복 입은 아이'] },
      { t: 'qa', k: 'keep', img: G('purple-spike'), title: '11.', q: 'What does the monster have?', a: 'It has ___ ___.', src: '문항 11', nt: '문항 11' },
      { t: 'qa', k: 'keep', img: G('blue-elephant'), title: '12.', q: 'What does the monster have? Is it scary?', a: 'It has ___ eyes. It is ___.', src: '문항 12', nt: '문항 12' },
      { t: 'qa', k: 'fix', img: G('purple-m'), title: '13.', q: "What doesn't the monster have?", a: "It doesn't have ___.", src: '문항 13', nt: '문항 13', n: ['<del>What does the monster not have?</del> → What doesn\'t the monster have?'] },
      { t: 'yourturn', k: 'keep', img: G('draw-monster'), title: '14.', lines: ['Draw your own monster.', 'Tell your teacher about it.', 'It has ___. It doesn\'t have ___.'], src: '문항 14', nt: '문항 14 — 자유 답' },
      { t: 'table', k: 'new', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–5', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['6–9', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['10–13', 'Great!', '거의 다 왔어요'], ['14 ⭐', 'Perfect!', 'BTS 8 로 출발! ⚽']], nt: '점수표', n: ['점수마다 다음 할 일을 함께 적었습니다'] },
      { t: 'next', k: 'new', img: '15515', q: "What is he doing? He's kicking the ball!", ko: 'BTS 8 — 지금 무엇을 하고 있나요? (I\'m kicking the ball)', nt: '다음 권 예고', n: ['BTS 8 은 «지금 하고 있는 일»(-ing) — 몸 낱말(foot·leg)을 그대로 씁니다'] },
    ] },
  ],
};
