// BTS 6 새 교재 설계 데이터 — 집 안(침실·거실·부엌·욕실) + 위치 전치사
// k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
import { open, close, HELLO } from '../common.mjs';
const USONG_2 = { t: 'song', k: 'new', small: "Let's sing! ♪ Here We Go Round the Mulberry Bush", title: "Living Room Places 🛋️", img: "gen:bts-06-song-living-room", nt: "거실 위치 노래(새로 지음)", n: ["곡조: Here We Go Round the Mulberry Bush (저작권 만료 곡) — 가사는 이 단원 낱말로 새로 지었습니다","next to·in front of·behind·between에 맞춰 손 하나를 다른 손의 옆·앞·뒤·사이로 옮겨요."], src: '새로 지음', lines: ["The lamp is next to the sofa,","Next to the sofa, next to the sofa,","The table's in front of the sofa","In the living room at home!","The dog is between the curtains,","Between the curtains, between the curtains,","The cat is behind the sofa","In the living room at home!"] };

const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3';
const G = k => 'gen:bts-06-' + k;

export const COURSE = {
  head: `<h1>BTS 6 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트에 올라가 있는 BTS 6 원본 <b>240쪽</b>(11묶음)을 한 장씩 읽고, BTS 1 과 같은 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · 과 끝 «I can» · 다음 시간 예고)으로 다시 짰습니다. 이 권의 주제는 <b>집 안 물건과 «어디에 있나»</b>(in·on·under → next to·in front of·behind·between → above·below)입니다.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>배우는 <b>낱말·문장·전치사 범위는 원본 그대로</b>입니다(침실·거실·부엌·욕실 낱말, stand·sit·lie down). 원본의 이야기 인물(Mia·Miss Ava / Emily·Uncle Dan·Ella / Zoey·Aunt Leah)도 그대로 두고 과를 넘어 다시 등장시켰습니다.</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>, <b>⭕❌</b>, <b>Guess who 타일</b>, <b>기억 게임</b>, <b>내 방·내 집 말하기(Your turn)</b>, <b>I can ✅</b>, <b>다음 시간 예고</b>. 위치 문장은 «숨은 동물 찾기» 사진으로 바꿔 맞히는 재미를 살렸습니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>점선 상자(«새 사진 생성 중»)는 맞는 사진이 없어 새로 만드는 자리입니다(이 권 40장 요청). 원본에는 합성 사진·로고가 보이는 사진(«GONE GIRL» 영화 포스터가 뜬 TV, «Free» 글자 풍선)이 있어 교체했습니다.</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>고친 뜻 승인</b> — 원본 한국어 뜻이 틀린 곳이 많습니다: closet «보관함»→옷장, dresser «옷장»→서랍장, in «에서»→안에, between «중에서»→사이에, toilet «화장실»→변기, cabinet «장식장/보관장»→찬장·수납장, stove «난로»→가스레인지. 특히 <b>dresser·closet</b> 은 원본끼리 뜻이 뒤바뀌어 있었습니다.</li>
<li><b>빠진 낱말</b> — 008 목표에 있는 <b>shampoo</b> 가 낱말 쪽에 없고, 004 목표의 <b>behind·between</b> 은 005에서야 나옵니다. 시안은 shampoo 를 008 낱말에 넣고, behind·between 은 원본대로 005에서 배우게 했습니다(004 목표에서는 뺌).</li>
<li><b>001 이야기의 논리</b> — «고양이 3마리» 중 두 번째를 «The other cat» 이라고 해 셋째가 없게 됩니다 → «Another cat» 으로 고쳤습니다.</li>
<li><b>003 잰말놀이</b> — 침실 과에 «Six socks sit in a sink…»(부엌·욕실 낱말). 008로 옮길지, 침실 잰말놀이를 새로 넣을지.</li>
<li><b>뱀·도마뱀 사진</b> — 006·009 원본에 뱀(소파 뒤)·도마뱀(냉장고 위)이 나옵니다. 어린 학생이 무서워할 수 있어 시안은 <b>장난감 뱀</b>으로 바꿨고 도마뱀은 작은 도마뱀 그대로 두었습니다.</li>
<li><b>새로 만들 사진 40장</b> — 힉스필드 크레딧 사용 승인.</li>
<li><b>새 단원 노래 1곡</b> — 노래가 없던 단원에 새로 지은 노래를 Hello Song 바로 뒤에 넣었습니다: Unit 2 «Living Room Places»(Here We Go Round the Mulberry Bush). 곡조는 모두 저작권이 끝난 동요(또는 손뼉·랩 챈트)이고 가사는 그 단원 낱말로 새로 썼습니다. <b>가사 승인</b>과 <b>녹음(반주·노래)</b>이 필요합니다 — 지금은 줄마다 🔊(기계 음성)로만 들을 수 있습니다.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '침실·in on under', unit: U1, title: 'Bedroom', orig: 27,
    intro: '침실 물건(bed·pillow·blanket·chair·armchair·closet·dresser·lamp·desk)과 in·on·under 를 배웁니다. 이야기: 미아가 에이바 선생님께 자기 방을 보여 주는데, 고양이 세 마리가 어디 숨었을까요?',
    fixed: ['closet «보관함»→옷장 · dresser «옷장»→서랍장(두 낱말 뜻이 뒤섞여 있었음)', 'in «에서»→안에 · on «에»→위에', '«Let\'s talk about bedroom» → about <b>the</b> bedroom', '«my 3 cats» → three cats · «Oh here!» → Oh, here! · «Thank you Mia.» → Thank you, Mia.', '❗ 이야기 논리: 세 마리 중 둘째를 «The other cat» → «Another cat»(the other 는 «남은 하나»라서 셋째가 없어짐)', 'Role-play 역할 이름이 Mia / Miss Ava 인데 쪽마다 Mia·A·B 로 섞임 → 이름으로 통일'],
    slides: [
      { t: 'cover', k: 'new', img: G('cover-bed'), q: 'What is in your bedroom?', story: 'Mia shows Miss Ava her room. Where are her three cats?', nt: '표지 + Big Question', n: ['«네 방에는 뭐가 있어?» 로 엽니다 — 끝날 때 학생이 자기 방을 영어로 소개하는 것이 목표', '이야기 예고: 고양이 세 마리는 이 과의 이야기 쪽에서 찾습니다'] },
      ...open([['I can name things in my bedroom.', '내 방 물건 이름을 말할 수 있어요 — bed, pillow, lamp'], ['I can use in, on and under.', 'in·on·under 로 어디 있는지 말할 수 있어요.'], ['I can ask "Where is the cat?"', '«Where is …?» 로 어디 있는지 물을 수 있어요.']]),
      { t: 'song', k: 'fix', title: 'Where Is It? Song', img: 'c5006', lines: ["Where's the monkey? Where is it?", 'In the box. In the box.', "Where's the book? Where is it?", 'On the desk. On the desk.', "Where's the ruler? Where is it?", 'Under the chair. Under the chair.'], src: '4쪽 Where is it Song', nt: '전치사 노래', n: ['원본 9절 중 in·on·under 가 한 번씩 나오는 3절만 골랐습니다(나머지 6절과 «On, in and under. Great!» 후렴은 강사가 이어 부름)', '«Where is it? Where is it?» 반복은 한 번으로 줄여 화면에 맞췄습니다(부를 때는 두 번)', '«Under the   rock» 띄어쓰기·«On, In and Under» 대문자 정리', 'QR·유튜브 주소는 화면판에서 뺐습니다'] },
      { t: 'vocab', k: 'fix', hide: true, cols: 4, words: [['bed', '침대', '16560'], ['pillow', '베개', '13178'], ['blanket', '담요', '16147'], ['chair', '의자', '16149'], ['armchair', '안락의자', '16153'], ['closet', '옷장', '12855'], ['dresser', '서랍장', G('dresser')], ['lamp', '램프, 스탠드', '16595']], src: 'Vocabulary 6·7쪽', nt: '낱말 — 뜻 가리고 먼저', n: ['사진만 보고 영어로 먼저 말하기 → 다음 쪽에서 뜻 공개', 'desk 는 BTS 1 에서 배운 낱말이라 공개 쪽에서만 복습합니다'] },
      { t: 'vocab', k: 'fix', cols: 4, words: [['bed', '침대', '16560'], ['pillow', '베개', '13178'], ['blanket', '담요', '16147'], ['chair', '의자', '16149'], ['armchair', '안락의자', '16153'], ['closet', '옷장', '12855'], ['dresser', '서랍장', G('dresser')], ['desk', '책상', '16369']], title: 'Words', src: '6·7쪽', nt: '낱말 — 뜻 공개', n: ['<del>closet 보관함 · dresser 옷장</del> → closet 옷장 · dresser 서랍장', '따라 말하기 2번 → 강사가 사진을 가리키면 학생이 말하기'] },
      { t: 'rule', k: 'new', title: 'In, on or under?', left: { h: 'in / on', ex: ['The girl is **in** the bed. (이불 속)', 'The girl is **on** the bed. (이불 위)'] }, right: { h: 'under', ex: ['The pillow is **under** the bed.', 'The cat is **under** the chair.'] }, q: 'In the bed or on the bed? What is different?', nt: '규칙 찾기', n: ['원본 강사 설명 «In bed: under the cover» 를 학생이 먼저 찾게 바꿨습니다', '«in the bed = 이불 속, on the bed = 이불 위» 를 학생 말로 정리하게 합니다'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'The pillow is on the bed.', head: ['what', 'is', 'where'], rows: [['The bed', 'is', 'in the bedroom.'], ['The girl', 'is', 'in the bed. / on the bed.'], ['The pillow', 'is', 'on the bed. / under the bed.'], ['The man', 'is', 'in the armchair. / on the chair.']], src: 'Grammar 8·9쪽', nt: '문장 틀', n: ['원본 문장 8개를 한 표로 모았습니다', 'armchair(감싸는 의자)는 in, 그냥 chair 는 on — 원본 강사 설명 «In a chair: for armchair»', '«The grandmother is in the rocking chair» 는 다음 쪽 사진 질문으로 옮겼습니다'] },
      { t: 'qa', k: 'fix', img: '12800', title: "Let's talk about the bedroom!", q: 'What color is your bedroom?', a: 'My bedroom is ___.', chips: ['white', 'blue', 'pink', 'yellow'], src: '10쪽', nt: '내 방 이야기', n: ['<del>about bedroom</del> → about the bedroom', '«How many bedrooms do you have at home?» 도 이어서 묻습니다'] },
      { t: 'count', k: 'keep', img: '18010', q: 'How many pillows do you have?', a: 'I have ___ pillows.', chips: ['one', 'two', 'three'], src: '12쪽', nt: '세어 보기', n: ['원본 «What are they?» 다음 쪽 → 이 사진은 베개가 많아 세기 좋습니다'] },
      { t: 'qa', k: 'keep', img: '18658', q: 'Where is the dog?', a: 'The dog is ___ the bed.', chips: ['in', 'on', 'under'], src: '13쪽', nt: 'in', n: ['베개에 파묻힌 강아지 — 이불·베개 속이면 in'] },
      { t: 'qa', k: 'fix', img: G('dresser'), q: 'Where is the lamp?', a: 'The lamp is ___ the dresser.', chips: ['in', 'on', 'under'], src: '14쪽', nt: 'on', n: ['원본은 답이 이미 적혀 있었음(The lamp is on the dresser.) → 빈칸으로'] },
      { t: 'qa', k: 'keep', img: G('closet-bear'), q: 'Where is the bear?', a: 'The bear is ___ the closet.', chips: ['in', 'on', 'under'], src: '15쪽', nt: 'in' },
      { t: 'qa', k: 'fix', img: '12048', q: 'Where is the grandmother?', a: 'The grandmother is ___ the armchair.', chips: ['in', 'on', 'under'], src: '16쪽 · 9쪽', nt: 'in the armchair', n: ['원본 16쪽 «Where is the man?» 과 9쪽 «The grandmother is in the rocking chair» 를 한 쪽으로 — 할머니 사진이 있어 이쪽으로'] },
      { t: 'qa', k: 'fix', img: '18772', q: 'Where are the women?', a: 'The women are ___ the sofa.', chips: ['in', 'on', 'under'], src: '17쪽', nt: 'on', n: ['원본은 의자에 앉은 두 여자 → 소파에 나란히 앉은 할머니·엄마 사진으로(sofa 는 004 예습)', '복수 are 를 한 번 짚고 갑니다'] },
      { t: 'ox', k: 'new', img: '15685', s: 'The cat is on the chair.', nt: '⭕❌ 몸으로 답하기', n: ['정답 ❌ → «No! The cat is under the chair.» 까지 말하면 성공', '원본 18쪽 «The cat is under the chair.» 를 고치게 하는 문제로 바꿨습니다'] },
      { t: 'guess', k: 'new', img: '16695', open: [2, 3], q: 'Who is under the bed?', chips: ['Is it a cat?', 'Is it a dog?', 'It is under the bed.'], nt: 'Guess who 타일', n: ['타일을 열 때마다 영어 질문 한 개 — «Is it a dog?»', '정답을 말할 때 «The cat is under the bed.» 문장으로'] },
      { t: 'vocab', k: 'keep', cols: 3, title: 'Story words', words: [['welcome', '환영해요, 어서 와요', '12040'], ['third', '세 번째(의)', G('third-cat')], ['clean', '깨끗한', '12800']], src: '19쪽', nt: '이야기 낱말', n: ['<del>welcome 환영</del> → «어서 와요»(인사말로 쓰임)'] },
      { t: 'story', k: 'fix', small: 'Story ①', title: "Mia's Bedroom", img: G('mia-cats'), lines: [['Mia', 'Hello, Miss Ava. Welcome to our house. This is my bedroom.'], ['Miss Ava', 'Thank you, Mia. Your bedroom is so clean.'], ['Mia', 'Miss Ava, do you see my three cats?']], src: '20·21쪽 Role-play', nt: '이야기 ① 역할놀이', n: ['<del>Thank you Mia.</del> → Thank you, Mia. · <del>my 3 cats</del> → three cats · <del>Oh here!</del> → Oh, here!', '강사=Miss Ava, 학생=Mia → 두 번째는 바꿔 읽기'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: "Mia's Bedroom", img: G('third-cat'), lines: [['Miss Ava', 'Oh, here! One cat is on the chair.'], ['Mia', 'Another cat is under the desk.'], ['Miss Ava', 'They are cute! Where is the third cat?'], ['Mia', 'Here! It is in the bed.'], ['Miss Ava', 'Haha! Wow! It is sleeping!']], src: '22쪽', nt: '이야기 ②', n: ['❗ <del>The other cat</del> → Another cat — «the other» 는 «남은 하나» 라 셋째 고양이가 없어집니다', '읽기 전에 «세 번째 고양이는 어디 있을까?» 먼저 맞히기'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ['Who is Mia? — She is a ___.', 'Where is one cat? — It is ___ the chair.', 'Where is another cat? — It is ___ the desk.', 'Where is the third cat? — It is ___ the bed.'], chips: ['girl', 'on', 'under', 'in'], src: '23~25쪽', nt: '이야기 질문', n: ['원본 «Who is she?» → 이름을 넣어 «Who is Mia?»'] },
      { t: 'match', k: 'new', title: 'Match it!', left: ['16560', '13178', '12855', '16147'], right: ['closet', 'blanket', 'bed', 'pillow'], nt: '짝짓기', n: ['사진과 낱말 짝 — 짝을 지은 뒤 «The pillow is on the bed.» 처럼 문장 하나씩'] },
      { t: 'yourturn', k: 'new', img: 'c7102', title: 'My bedroom', lines: ['This is my bedroom.', 'My ___ is on the bed.', 'My ___ is under the desk.'], chips: ['pillow', 'blanket', 'bag', 'cat'], nt: '내 방 말하기', n: ['화상수업이면 학생이 카메라로 자기 방 물건을 보여 주며 말합니다', 'in·on·under 를 하나씩 다 쓰면 보너스'] },
      ...close([['I can name things in my bedroom.', 'bed, pillow, blanket, closet, dresser'], ['I can use in, on and under.', 'The pillow is on the bed.'], ['I can ask "Where is the cat?"', 'Where is the cat? — It is under the chair.']], { img: G('pillow-fight'), q: 'Are they on the bed or in the bed?', ko: '이 아이들은 침대 위에서 무엇을 할까요? (다음 시간 — sit, stand, lie down)' }),
    ] },
  // ───────────────────────── 002
  { code: '002', tab: '침실·sit stand lie', unit: U1, title: 'Bedroom', orig: 19,
    intro: 'floor(바닥)와 동작 sit(앉다)·stand(서다)·lie down(눕다)을 in·on·under 와 함께 씁니다. 이야기: 미아네 집에 친구들이 놀러 와 방이 떠들썩해집니다.',
    fixed: ['stand «서다, 대» → 서다, 서 있다(«대» 는 뜻이 아님)', '«The baby lies down __ the bed» 빈칸 길이 불일치 → ___', '«Where are they?» 한 쪽에 질문 두 개 → 한 쪽 한 질문', '문장 끝 마침표·물음표 누락 여러 곳'],
    slides: [
      { t: 'cover', k: 'new', img: G('pillow-fight'), q: 'Do you stand on your bed?', story: "Mia's friends are here. Who is standing? Who is lying down?", nt: '표지 + Big Question', n: ['지난 시간 예고 사진으로 엽니다 — 짝이 맞아 기억이 이어집니다'] },
      ...open([['I can say sit, stand and lie down.', 'sit·stand·lie down 을 말할 수 있어요.'], ['I can say where people sit.', 'The man sits on the chair.'], ['I can talk about the floor.', 'They sit on the floor.']]),
      { t: 'vocab', k: 'fix', hide: true, cols: 4, words: [['floor', '바닥', '19389'], ['sit', '앉다', '16149'], ['stand', '서다, 서 있다', G('pillow-fight')], ['lie down', '눕다', '13276']], src: 'Vocabulary 6·7쪽', nt: '낱말 — 뜻 가리고 먼저', n: ['동작 낱말은 학생이 직접 몸으로 해 보게 합니다(앉기·서기·눕는 흉내)'] },
      { t: 'vocab', k: 'fix', cols: 4, words: [['floor', '바닥', '19389'], ['sit', '앉다', '16149'], ['stand', '서다, 서 있다', G('pillow-fight')], ['lie down', '눕다', '13276']], title: 'Words', src: '6·7쪽', nt: '낱말 — 뜻 공개', n: ['<del>stand 서다, 대</del> → 서다, 서 있다'] },
      { t: 'rule', k: 'new', title: 'sits or sit?', left: { h: 'one', ex: ['The man **sits** on the chair.', 'The cat **lies down** on the bed.'] }, right: { h: 'two or more', ex: ['They **sit** on the floor.', 'They **lie down** on the bed.'] }, q: 'When do we say "sits"? When do we say "sit"?', nt: '규칙 찾기 — 3인칭 -s', n: ['한 명(he·she·the man)이면 sits·stands·lies, 여럿(they)이면 sit·stand·lie', '원본은 이 규칙을 설명 없이 섞어 써서 학생들이 자주 틀립니다'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'The man sits on the chair.', head: ['who', 'does', 'where'], rows: [['The man', 'sits / stands', 'on the chair. / on the floor.'], ['The baby', 'sits', 'in the chair.'], ['The cat', 'lies down', 'on the bed.'], ['The girl', 'lies down', 'in the bed.']], src: 'Grammar 8·9쪽', nt: '문장 틀', n: ['원본 문장 5개(The man sits on the chair. / The man stands on the floor. 은 한 줄로 묶음)'] },
      { t: 'qa', k: 'keep', img: '19389', title: "Let's talk!", q: 'What color is the floor? What about your floor?', a: 'My floor is ___.', chips: ['brown', 'white', 'gray'], src: '10쪽', nt: '내 방 바닥' },
      { t: 'qa', k: 'keep', img: G('girls-floor'), q: 'Where do they sit?', a: 'They ___ on the floor.', chips: ['sit', 'sits'], src: '11쪽', nt: 'they sit' },
      { t: 'qa', k: 'keep', img: '16127', q: 'Where is the baby?', a: 'The baby lies down ___ the bed.', chips: ['on', 'under'], src: '12쪽', nt: 'lie down on' },
      { t: 'qa', k: 'keep', img: G('cat-stand-bed'), q: 'Where is the cat?', a: 'The cat stands ___ the bed.', chips: ['on', 'under'], src: '13쪽', nt: 'stand on' },
      { t: 'qa', k: 'keep', img: G('dog-under-table'), q: 'Where is the dog?', a: 'The dog stands ___ the table.', chips: ['in', 'on', 'under'], src: '14쪽', nt: 'stand under' },
      { t: 'ox', k: 'new', img: G('third-cat'), s: 'The cat sits on the bed.', nt: '⭕❌', n: ['정답 ❌ → «No! It lies down in the bed.»', '원본 15쪽 «The woman ___ in the bed.»(lies down)를 고치는 문제로 — 001 이야기의 잠자는 고양이'] },
      { t: 'qa', k: 'keep', img: G('pillow-fight'), q: 'Where are they?', a: 'They ___ on the bed.', chips: ['stand', 'stands'], src: '16쪽', nt: 'they stand', n: ['베개 싸움 사진 — 학생도 «서기» 동작을 함께'] },
      { t: 'story', k: 'new', small: 'Story', title: 'A Noisy Room', img: G('pillow-fight'), lines: [['Mia', 'Look, Mom! My friends are here.'], ['Mom', 'Oh no! They stand on the bed!'], ['Mia', 'Haha! Now they lie down on the bed.'], ['Mom', 'Good. And where do you sit?'], ['Mia', 'I sit on the floor!']], nt: '이어지는 이야기', n: ['001 의 미아 이야기를 이어 새로 만든 짧은 대화 — 이 과 동사를 모두 씁니다', '강사=Mom, 학생=Mia'] },
      { t: 'memory', k: 'new', items: ['16127', G('girls-floor'), G('cat-stand-bed'), '12075'], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ①', n: ['5초 보여 주고 넘깁니다'] },
      { t: 'memory', k: 'new', hidden: true, items: ['16127', G('girls-floor'), G('cat-stand-bed'), '12075'], q: 'Who sits? Who stands? Who lies down?', a: 'The baby ___ on the bed.', nt: '기억 게임 ②', n: ['«The girls sit on the floor.» 처럼 문장으로 말해야 점수'] },
      { t: 'yourturn', k: 'new', img: '16659', title: 'Where do you sit?', lines: ['I sit ___ the chair.', 'I lie down ___ my bed.', 'My toys are ___ the floor.'], chips: ['on', 'in', 'under'], nt: '내 말로', n: ['지금 앉아 있는 곳을 카메라로 보여 주며 말하기'] },
      ...close([['I can say sit, stand and lie down.', 'sit · stand · lie down'], ['I can say where people sit.', 'The man sits on the chair.'], ['I can talk about the floor.', 'They sit on the floor.']], { img: G('pineapple-bed'), q: 'Why is there a pineapple on the bed?', ko: '침대 위에 파인애플이 왜 있을까요? (다음 시간 첫 문제)' }),
    ] },
  // ───────────────────────── 003
  { code: '003', tab: '침실·복습 문장', unit: U1, title: 'Bedroom', orig: 24,
    intro: '침실 낱말·동작을 문장으로 조립하고 사진을 보고 설명합니다. «Where does …?» 로 묻고 답합니다.',
    fixed: ['순서 맞추기 조각 «/sits» 앞에 빗금이 붙어 있음 → 정리', '침실 과에 «Six socks sit in a sink, soaking in a soapsuds»(부엌·욕실 낱말) → 008 로 옮김(사람이 정할 것), <del>in a soapsuds</del> → in soapsuds', '«Where does she lie down?» 답칸에 주어가 없어 문장이 안 됨 → She lies down ___ the bed.', '물음표 앞 띄어쓰기 정리'],
    slides: [
      { t: 'cover', k: 'new', img: G('pineapple-bed'), q: 'Where does the pineapple lie down?', story: 'Funny things are in the bedroom today!', nt: '표지 + Big Question', n: ['지난 시간 예고 사진 — 첫 질문으로 씁니다: «It lies down on the bed.»'] },
      ...open([['I can make sentences with sit, stand and lie down.', '동작 낱말로 문장을 만들 수 있어요.'], ['I can ask "Where does she sit?"', '«Where does …?» 로 물을 수 있어요.'], ['I can talk about a picture.', '사진을 보고 설명할 수 있어요.']]),
      { t: 'vocab', k: 'new', hide: true, cols: 4, title: 'Remember? 🔒', words: [['bed', '침대', '12245'], ['pillow', '베개', '18010'], ['closet', '옷장', '12855'], ['dresser', '서랍장', G('dresser')], ['lamp', '램프, 스탠드', '12075'], ['armchair', '안락의자', '15030'], ['blanket', '담요', '16643'], ['floor', '바닥', '16659']], nt: '지난 낱말 떠올리기', n: ['001·002 낱말을 다른 사진으로 — 같은 사진이면 사진만 외웁니다'] },
      { t: 'rule', k: 'new', title: 'Where is / Where does', left: { h: 'Where is …?', ex: ['Where **is** the cat?', 'The cat **is** under the chair.'] }, right: { h: 'Where does … sit?', ex: ['Where **does** she **sit**?', 'She **sits** on the floor.'] }, q: 'Which question has "sit" or "lie down" in it?', nt: '규칙 찾기', n: ['동작 낱말이 있으면 does, 없으면 is', '답할 때 does 는 사라지고 sits 로 바뀐다는 것도 학생이 찾게'] },
      { t: 'order', k: 'keep', img: G('mia-cats'), words: ['sits', 'The', 'on', 'cat', 'the chair'], src: '7쪽 Rearrange', nt: '순서 맞추기', n: ['정답: The cat sits on the chair.'] },
      { t: 'order', k: 'keep', img: '16174', words: ['lies down', 'He', 'the bed', 'on'], src: '8쪽', nt: '순서 맞추기', n: ['정답: He lies down on the bed.'] },
      { t: 'order', k: 'keep', img: G('pillow-fight'), words: ['lie down', 'They', 'on', 'the bed'], src: '9쪽', nt: '순서 맞추기', n: ['정답: They lie down on the bed. — they 라서 lie(‑s 없음)'] },
      { t: 'order', k: 'keep', img: '15685', words: ['stands', 'The cat', 'the chair', 'under'], src: '10쪽', nt: '순서 맞추기' },
      { t: 'order', k: 'fix', img: '12048', words: ['sits', 'She', 'the armchair', 'in'], src: '11쪽', nt: '순서 맞추기', n: ['<del>/sits</del> 조각의 빗금 정리', '원본은 매달린 둥근 의자 사진 → 안락의자(감싸는 의자라 in — 001 규칙과 같음)'] },
      { t: 'qa', k: 'keep', img: G('girls-floor'), q: 'Where do the girls sit?', a: 'They sit on the ___.', chips: ['floor', 'bed'], src: '12쪽', nt: 'Where do …?', n: ['원본 «Where does the woman sit?»(여자 한 명 사진) → 여러 명 사진이라 do / they 로', '다음 쪽에서 한 명(does / she)과 비교합니다'] },
      { t: 'qa', k: 'fix', img: '15828', q: 'Where does she lie down?', a: 'She lies down ___ the bed.', chips: ['in', 'under'], src: '13쪽', nt: 'Where does …?', n: ['원본 답칸 «___ the bed» → 주어를 넣어 문장으로'] },
      { t: 'qa', k: 'keep', img: '17154', q: 'Where do they lie down?', a: 'They lie down ___ the bed.', chips: ['in', 'on'], src: '14쪽', nt: 'Where do …?' },
      { t: 'qa', k: 'keep', img: 'c7169', q: 'Where are the pillows?', a: 'The pillows are ___ the bed.', chips: ['on', 'under'], src: '15쪽', nt: 'Where are …?' },
      { t: 'qa', k: 'keep', img: G('pineapple-bed'), q: 'Where is the pineapple?', a: 'The pineapple is ___ the bed.', chips: ['on', 'under'], src: '17쪽', nt: '재미 문제', n: ['선글라스 쓴 파인애플 — 학생이 웃으면서 문장을 말하게 하는 쪽'] },
      { t: 'guess', k: 'new', img: '18820', open: [0], q: 'What is under the sofa?', chips: ['Is it a cat?', 'Is it a bag?', 'It is under the sofa.'], nt: 'Guess who 타일', n: ['손전등에 비친 고양이 — 다음 과(거실)의 sofa 를 미리 보여 줍니다'] },
      { t: 'story', k: 'new', small: 'Story', title: 'Good Night, Mia!', img: '12075', lines: [['Mom', 'Mia, where are your cats?'], ['Mia', 'One cat lies down on my pillow.'], ['Mia', 'Another cat sits under my desk.'], ['Mom', 'And the third cat?'], ['Mia', "It's in my bed! Good night, cats!"]], nt: '이어지는 이야기', n: ['001 고양이 세 마리가 다시 등장 — 이 과의 동사로 다시 말합니다'] },
      { t: 'yourturn', k: 'keep', img: '12245', title: 'Your turn!', lines: ['Where do you sit right now?', 'I sit ___ the ___.', 'Where do you sleep at night?', 'I sleep ___ my bed.'], chips: ['on', 'in', 'chair', 'floor'], src: '18·19쪽', nt: '내 말로', n: ['원본 두 쪽 질문을 한 쪽에'] },
      ...close([['I can make sentences with sit, stand and lie down.', 'The cat sits on the chair.'], ['I can ask "Where does she sit?"', 'Where does she sit? — She sits on the floor.'], ['I can talk about a picture.', 'The pineapple is on the bed.']], { img: '15546', q: 'Who is in the living room?', ko: '거실에서 슈퍼히어로가 뭘 할까요? (다음 시간 — 거실)' }),
    ] },
  // ───────────────────────── 004
  { code: '004', tab: '거실·next to in front of', unit: U2, title: 'Living Room', orig: 23,
    intro: '거실 낱말(sofa·table·television·armchair·window·curtains·lamp)과 next to·in front of 를 배웁니다. 이야기: 에밀리가 새 의상을 입고 댄 삼촌과 거실에서 놉니다.',
    fixed: ['«She saw Sherriff\'s shoes» → the sheriff\'s shoes(철자·관사)', '«In front of» 대문자 → in front of · costume «복장» → 의상 · amazing «놀랄 만한» → 멋진', '«You look amazing Emily!» → You look amazing, Emily! · «hahahah» → Haha!', '목표에 behind·between 이 있지만 이 과에는 안 나옴 → 목표에서 빼고 005 로(원본 005 가 가르침)', 'TV 화면 사진이 게임 화면 → 만화를 보는 사진으로'],
    slides: [
      { t: 'cover', k: 'new', img: '15546', q: 'What do you do in the living room?', story: 'Emily has a new costume. Uncle Dan is here!', nt: '표지 + Big Question' },
      ...open([['I can name things in the living room.', '거실 물건 이름을 말할 수 있어요 — sofa, table, TV'], ['I can use next to and in front of.', 'next to·in front of 로 위치를 말할 수 있어요.'], ['I can ask "How many … do you have?"', '«How many …?» 로 집에 몇 개 있는지 물을 수 있어요.']], 'Lesson Goals (behind·between 은 005 로)'),
      USONG_2,
      { t: 'song', k: 'fix', title: 'Tongue Twister', img: '16150', lines: ["She saw the sheriff's shoes on the sofa.", "She saw the sheriff's shoes on the sofa.", '(5x — faster and faster!)'], src: '4쪽 Warm Up', nt: '잰말놀이', n: ["<del>Sherriff's</del> → the sheriff's (철자·관사)", '점점 빠르게 — 틀리면 웃으며 다시'] },
      { t: 'vocab', k: 'fix', hide: true, cols: 4, words: [['sofa', '소파', '16150'], ['table', '탁자', '12721'], ['television', '텔레비전', '13358'], ['armchair', '안락의자', '16153'], ['window', '창문', '12738'], ['curtains', '커튼', '18737'], ['lamp', '램프, 스탠드', '13072'], ['in front of', '~ 앞에', G('cat-front-baby')]], src: 'Vocabulary 6·7쪽', nt: '낱말 — 뜻 가리고 먼저', n: ['lamp 는 001 과 같은 낱말 — 원본은 여기서만 «등» 이라 적어 뜻을 맞췄습니다'] },
      { t: 'vocab', k: 'fix', cols: 4, words: [['sofa', '소파', '16150'], ['table', '탁자', '12721'], ['television', '텔레비전', '13358'], ['armchair', '안락의자', '16153'], ['window', '창문', '12738'], ['curtains', '커튼', '18737'], ['next to', '~ 옆에', 'c7327'], ['in front of', '~ 앞에', G('cat-front-baby')]], title: 'Words', src: '6·7쪽', nt: '낱말 — 뜻 공개', n: ['<del>In front of</del> → in front of (소문자)'] },
      { t: 'rule', k: 'new', title: 'next to or in front of?', left: { h: 'next to', ex: ['The lamp is **next to** the sofa.', '(옆에 나란히)'] }, right: { h: 'in front of', ex: ['The table is **in front of** the sofa.', '(앞에 마주 보고)'] }, q: 'Stand next to your chair. Now stand in front of it!', nt: '규칙 찾기 + 몸으로', n: ['학생이 의자 옆·앞에 서 보며 차이를 몸으로 익힙니다'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'The table is in front of the sofa.', head: ['what', 'is', 'where'], rows: [['The lamp', 'is', 'next to the sofa.'], ['The table', 'is', 'in front of the sofa.']], tip: 'next to = 옆 · in front of = 앞', src: 'Grammar 8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'keep', img: '16150', title: "Let's talk!", q: 'Do you have a sofa at home? What color is it?', a: 'Yes, I do. It is ___.', chips: ['gray', 'brown', 'white'], src: '9쪽', nt: '우리 집 소파' },
      { t: 'count', k: 'keep', img: '12738', q: 'How many windows do you have in your living room?', a: 'I have ___ windows.', chips: ['two', 'three', 'four'], src: '10쪽', nt: '세어 보기' },
      { t: 'qa', k: 'keep', img: '18737', q: 'What color are your curtains in the living room?', a: 'My curtains are ___.', chips: ['red', 'white', 'blue'], src: '11쪽', nt: 'curtains' },
      { t: 'count', k: 'fix', img: '18881', q: 'How many TVs do you have at home?', a: 'I have ___.', chips: ['one TV', 'two TVs'], src: '12쪽', nt: 'TV', n: ['원본 사진은 게임 화면 → 만화를 보며 웃는 아이 사진으로', 'one 이면 TV, two 이상이면 TVs — 학생이 알아채면 칭찬'] },
      { t: 'qa', k: 'keep', img: G('cat-front-baby'), q: 'Where is the cat?', a: 'The cat is ___ the baby.', chips: ['next to', 'in front of'], src: '14쪽', nt: 'in front of' },
      { t: 'qa', k: 'keep', img: G('girl-next-dog'), q: 'Where is the girl?', a: 'The girl is ___ the dog.', chips: ['next to', 'in front of'], src: '15쪽', nt: 'next to' },
      { t: 'ox', k: 'new', img: '15030', s: 'The lamp is next to the armchair.', nt: '⭕❌', n: ['정답 ⭕ — 램프가 안락의자 옆에 있습니다', '⭕ 문제도 섞어야 학생이 «늘 ❌» 로 찍지 않습니다'] },
      { t: 'guess', k: 'new', img: '15204', open: [1, 4], q: 'Who is in front of the TV?', chips: ['Is it a girl?', 'Is it a boy?', 'It is in front of the TV.'], nt: 'Guess who 타일', n: ['타일을 열며 맞히기 — 정답은 «The child is in front of the TV.»', '이야기 속 Ella 도 TV 앞에 있어요 — 다음 쪽 이야기로 이어집니다'] },
      { t: 'match', k: 'new', title: 'Match it!', left: ['16150', '18737', '12738', '13358'], right: ['window', 'television', 'sofa', 'curtains'], nt: '짝짓기', n: ['낱말을 말한 뒤 «How many ___ do you have?» 로 서로 묻기'] },
      { t: 'vocab', k: 'fix', cols: 3, title: 'Story words', words: [['costume', '의상, 분장 옷', '16287'], ['amazing', '멋진', '15546'], ['stay', '머물다, 있다', '18881']], src: '17쪽', nt: '이야기 낱말', n: ['<del>costume 복장 · amazing 놀랄 만한</del> → 의상 · 멋진'] },
      { t: 'story', k: 'fix', small: 'Story ①', title: "Emily's New Costume", img: '15546', lines: [['Emily', "Uncle Dan, let's play in the living room! I have a new costume!"], ['Uncle Dan', 'Sure! You look amazing, Emily!']], src: '18쪽 Role-play', nt: '이야기 ① 역할놀이', n: ['<del>amazing Emily!</del> → amazing, Emily!', '강사=Uncle Dan, 학생=Emily'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: "Emily's New Costume", img: G('emily-story'), lines: [['Uncle Dan', 'Your sister Ella is here.'], ['Emily', 'Yes! She likes to stay in front of the TV.'], ['Uncle Dan', 'Your new dog is cute!'], ['Emily', 'My dog likes to stay next to my sister. Haha!']], src: '19쪽', nt: '이야기 ②', n: ['<del>hahahah</del> → Haha!', '읽기 전에 사진에서 Ella 와 강아지를 먼저 찾게 합니다'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ['Where are they? — They are in the ___.', 'Where is Ella? — She is ___ the TV.', 'Where is the dog? — It is ___ Ella.'], chips: ['living room', 'in front of', 'next to'], src: '20·21쪽', nt: '이야기 질문', n: ['원본 «Who are they?» 는 강사가 말로 묻습니다(이름 두 개)'] },
      { t: 'yourturn', k: 'new', img: '12483', title: 'My living room', lines: ['In my living room, I have a ___.', 'The ___ is next to the sofa.', 'The table is in front of the ___.'], chips: ['sofa', 'TV', 'lamp', 'table'], nt: '내 말로', n: ['집 거실을 떠올리며(또는 사진을 보여 주며) 세 문장'] },
      ...close([['I can name things in the living room.', 'sofa, table, television, curtains'], ['I can use next to and in front of.', 'The table is in front of the sofa.'], ['I can ask "How many … do you have?"', 'How many TVs do you have?']], { img: G('dog-behind-curtain'), q: 'Who is behind the curtain?', ko: '커튼 뒤에 누가 숨었을까요? (다음 시간 — behind)' }),
    ] },
  // ───────────────────────── 005
  { code: '005', tab: '거실·behind between', unit: U2, title: 'Living Room', orig: 18,
    intro: 'wall(벽)·light switch(전등 스위치)와 behind·between 을 배웁니다. 거실 곳곳에 숨은 동물을 찾아 말합니다.',
    fixed: ['between «중에서» → 사이에 · behind «뒤에» 그대로', '«Light switch» 대문자 → light switch', '마지막 사진(곰 인형 사이 강아지·고양이)에 질문 두 개 → Guess who 로 바꿈'],
    slides: [
      { t: 'cover', k: 'new', img: G('dog-behind-curtain'), q: 'Who is hiding in the living room?', story: 'Hide and seek! Can you find them all?', nt: '표지 + Big Question', n: ['지난 시간 예고 사진 — «The dog is behind the curtain.»'] },
      ...open([['I can use behind and between.', 'behind·between 으로 위치를 말할 수 있어요.'], ['I can name wall and light switch.', 'wall·light switch 를 말할 수 있어요.'], ['I can find hiding animals.', '숨은 동물이 어디 있는지 말할 수 있어요.']]),
      USONG_2,
      { t: 'vocab', k: 'fix', hide: true, cols: 4, words: [['wall', '벽', '18736'], ['light switch', '전등 스위치', '19366'], ['behind', '~ 뒤에', G('man-behind-sofa')], ['between', '~ 사이에', G('hamster-cats')]], src: 'Vocabulary 6·7쪽', nt: '낱말 — 뜻 가리고 먼저' },
      { t: 'vocab', k: 'fix', cols: 4, words: [['wall', '벽', '18736'], ['light switch', '전등 스위치', '19366'], ['behind', '~ 뒤에', G('man-behind-sofa')], ['between', '~ 사이에', G('hamster-cats')]], title: 'Words', src: '6·7쪽', nt: '낱말 — 뜻 공개', n: ['<del>between 중에서</del> → ~ 사이에 · <del>Light switch</del> → light switch'] },
      { t: 'rule', k: 'new', title: 'behind or between?', left: { h: 'behind', ex: ['The windows are **behind** the sofa.', '(뒤에 하나)'] }, right: { h: 'between', ex: ['The sofa is **between** the lamp **and** the armchair.', '(둘 사이)'] }, q: 'How many things do we need for "between"?', nt: '규칙 찾기', n: ['between 은 늘 두 개(A and B)가 필요하다는 것을 학생이 찾게'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'The sofa is between the lamp and the armchair.', head: ['what', 'is / are', 'where'], rows: [['The windows', 'are', 'behind the sofa.'], ['The sofa', 'is', 'between the lamp and the armchair.']], src: 'Grammar 8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'keep', img: '18736', title: "Let's talk!", q: 'What color is your wall?', a: 'My wall is ___.', chips: ['white', 'blue', 'yellow'], src: '9쪽', nt: '우리 집 벽' },
      { t: 'qa', k: 'keep', img: G('pillows-between'), q: 'Where is the yellow pillow?', a: 'The yellow pillow is ___ the blue pillows.', chips: ['behind', 'between'], src: '10쪽', nt: 'between', n: ['이어서 «Do you have pillows in the living room?»'] },
      { t: 'qa', k: 'keep', img: G('man-behind-sofa'), q: 'Where is the man?', a: 'The man is ___ the sofa.', chips: ['behind', 'between'], src: '11쪽', nt: 'behind' },
      { t: 'qa', k: 'keep', img: G('bulldog-pillows'), q: 'Where is the dog?', a: 'The dog is ___ the pillows.', chips: ['behind', 'between'], src: '12쪽', nt: 'between' },
      { t: 'qa', k: 'keep', img: G('hamster-cats'), q: 'Where is the hamster?', a: 'The hamster is ___ the two cats.', chips: ['behind', 'between'], src: '13쪽', nt: 'between' },
      { t: 'qa', k: 'keep', img: G('cats-behind-tv'), q: 'Where are the gray cats?', a: 'The gray cats are ___ the TV.', chips: ['behind', 'between'], src: '14쪽', nt: 'behind', n: ['사진에 주황 고양이가 TV 옆에 한 마리 더 — 006 순서 맞추기에서 다시 씁니다'] },
      { t: 'order', k: 'new', img: G('man-behind-sofa'), words: ['is', 'The man', 'behind', 'the sofa'], nt: '순서 맞추기', n: ['정답: The man is behind the sofa.'] },
      { t: 'ox', k: 'new', img: G('dog-behind-curtain'), s: 'The dog is between the curtains.', nt: '⭕❌', n: ['정답 ❌ → «No! The dog is behind the curtain.»', '원본 15쪽 문제를 고치는 문제로'] },
      { t: 'guess', k: 'new', img: G('couple-pets'), open: [1], q: 'Where is the cat? Where is the dog?', chips: ['behind the sofa', 'between the pillows', 'next to the woman'], nt: 'Guess who 타일', n: ['원본 16쪽 곰 인형 소파 사진(한 쪽 질문 두 개) → 타일을 열며 찾기', '원본은 곰 인형 합성 사진 → 소파 위 반려동물 사진으로(006 그림 설명과 같은 장면)'] },
      { t: 'story', k: 'new', small: 'Story', title: 'Hide and Seek', img: G('man-behind-sofa'), lines: [['Emily', 'Uncle Dan, where are you?'], ['Ella', 'Is he behind the curtain?'], ['Emily', 'No. The dog is behind the curtain!'], ['Uncle Dan', "Here I am! I'm behind the sofa!"]], nt: '이어지는 이야기', n: ['004 인물(에밀리·엘라·댄 삼촌)로 숨바꼭질 — behind 를 여러 번 말합니다'] },
      { t: 'yourturn', k: 'new', img: '12483', title: 'Hide and seek at home', lines: ['I can hide behind the ___.', 'The ___ is between the sofa and the lamp.'], chips: ['sofa', 'curtain', 'door', 'table'], nt: '내 말로', n: ['«우리 집에서 숨는다면?» — 학생 대답이 가장 길게 나오는 질문'] },
      ...close([['I can use behind and between.', 'The dog is between the pillows.'], ['I can name wall and light switch.', 'wall · light switch'], ['I can find hiding animals.', 'The cats are behind the TV.']], { img: G('toy-snake'), q: 'What is behind the sofa?!', ko: '소파 뒤에 뭐가 있을까요? 😱 (다음 시간)' }),
    ] },
  // ───────────────────────── 006
  { code: '006', tab: '거실·네 전치사', unit: U2, title: 'Living Room', orig: 20,
    intro: 'next to·in front of·behind·between 네 가지를 섞어 쓰고, 문장을 조립하고, 그림을 설명합니다.',
    fixed: ['순서 맞추기 조각 «Is» 대문자(문장 첫 낱말이 아님) → is', 'TV 화면의 영화 포스터(«GONE GIRL» 글자) 사진 → 교체', '«The lamp is ___ the mice» → 쥐 인형 둘 사이 램프, 사진 교체 후 유지', '진짜 뱀 사진 → 장난감 뱀(사람이 정할 것)'],
    slides: [
      { t: 'cover', k: 'new', img: G('toy-snake'), q: 'Is it a real snake?', story: "Emily's living room is full of surprises!", nt: '표지 + Big Question', n: ['지난 예고의 답 — «It is a toy snake! It is behind the sofa.»'] },
      ...open([['I can use four place words.', 'next to·in front of·behind·between 을 골라 쓸 수 있어요.'], ['I can make a sentence in the right order.', '낱말을 순서대로 놓아 문장을 만들 수 있어요.'], ['I can talk about a picture.', '그림을 보고 두 문장 이상 말할 수 있어요.']]),
      USONG_2,
      { t: 'vocab', k: 'new', hide: true, cols: 4, title: 'Where? 🔒', words: [['next to', '~ 옆에', 'c7327'], ['in front of', '~ 앞에', G('cat-front-baby')], ['behind', '~ 뒤에', G('dog-behind-curtain')], ['between', '~ 사이에', G('bulldog-pillows')]], src: 'Vocabulary 6·7쪽', nt: '네 전치사 한 번에', n: ['원본 낱말 쪽의 가구 낱말은 004·005 와 같아 전치사만 모았습니다'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'Four places', head: ['what', 'is', 'where'], rows: [['The lamp', 'is', 'next to the sofa.'], ['The table', 'is', 'in front of the sofa.'], ['The windows', 'are', 'behind the sofa.'], ['The sofa', 'is', 'between the lamp and the armchair.']], src: 'Grammar 8쪽', nt: '문장 틀 — 넷 한눈에' },
      { t: 'qa', k: 'keep', img: G('bird-flowers'), q: 'Where is the bird?', a: 'The bird is ___ the flowers.', chips: ['next to', 'in front of', 'behind', 'between'], src: '9쪽', nt: 'between' },
      { t: 'qa', k: 'keep', img: G('rabbits'), q: 'Where is the white rabbit?', a: 'The white rabbit is ___ the brown rabbit.', chips: ['next to', 'behind', 'between'], src: '10쪽', nt: 'next to' },
      { t: 'qa', k: 'fix', img: G('toy-snake'), q: 'Where is the snake?', a: 'The snake is ___ the sofa.', chips: ['next to', 'in front of', 'behind', 'between'], src: '11쪽', nt: 'behind', n: ['진짜 뱀 → 장난감 뱀 사진(무서움 줄이기)'] },
      { t: 'qa', k: 'fix', img: '15030', q: 'Where is the lamp?', a: 'The lamp is ___ the armchair.', chips: ['next to', 'in front of', 'behind', 'between'], src: '12쪽', nt: 'next to', n: ['원본: 쥐 인형 둘 사이 램프(합성 사진, 처음 보는 mice) → 거실 안락의자 옆 램프 사진으로', 'between 은 앞 쪽 새·꽃 문제에서 이미 연습'] },
      { t: 'order', k: 'keep', img: G('pillows-between'), words: ['is', 'The man', 'between', 'the pillows'], src: '13쪽 Rearrange', nt: '순서 맞추기', n: ['정답: The man is between the pillows.'] },
      { t: 'order', k: 'keep', img: G('dog-behind-curtain'), words: ['behind', 'The woman', 'is', 'the curtain'], src: '14쪽', nt: '순서 맞추기' },
      { t: 'order', k: 'keep', img: G('piglets-girl'), words: ['are', 'The pigs', 'the girl', 'in front of'], src: '15쪽', nt: '순서 맞추기', n: ['pigs 는 복수 → are'] },
      { t: 'order', k: 'fix', img: G('cats-behind-tv'), words: ['is', 'the TV', 'The orange cat', 'next to'], src: '16쪽', nt: '순서 맞추기', n: ['<del>Is</del> → is (조각 대문자 정리) · 영화 포스터(«GONE GIRL» 글자)가 뜬 TV 사진 교체', '005 의 TV 사진을 다시 씀 — 거기서는 «뒤», 여기서는 «옆» 고양이를 봅니다'] },
      { t: 'ox', k: 'new', img: G('rabbits'), s: 'The brown rabbit is behind the white rabbit.', nt: '⭕❌', n: ['정답 ❌ → «No! It is next to the white rabbit.»'] },
      { t: 'match', k: 'new', title: 'Match it!', left: [G('hamster-cats'), G('cats-behind-tv'), G('girl-next-dog'), G('cat-front-baby')], right: ['behind', 'in front of', 'between', 'next to'], nt: '짝짓기', n: ['사진마다 전치사 하나 — 짝을 지은 뒤 문장으로 말하기'] },
      { t: 'guess', k: 'new', img: G('couple-pets'), open: [0, 5], q: 'Talk about the picture!', chips: ['The cat is next to …', 'The dog is between …', '… is behind the sofa.'], src: '17·18쪽 Talk about the picture', nt: '그림 설명하기', n: ['원본 두 쪽(«Talk about the picture») → 타일을 열 때마다 한 문장', '두 문장 이상 말하면 성공'] },
      { t: 'yourturn', k: 'new', img: '12989', title: 'Draw and tell', lines: ['Draw your living room!', 'The sofa is ___ the table.', 'The lamp is ___ the sofa.'], chips: ['next to', 'in front of', 'behind', 'between'], nt: '그리고 말하기', n: ['30초 그리기 → 그림을 보여 주며 두 문장'] },
      ...close([['I can use four place words.', 'next to · in front of · behind · between'], ['I can make a sentence in the right order.', 'The cat is next to the TV.'], ['I can talk about a picture.', 'The dog is between the pillows.']], { img: G('kitchen-cover'), q: 'Who is in the kitchen?', ko: '부엌에서 새끼 고양이가 뭘 할까요? (다음 시간 — 부엌)' }),
    ] },
  // ───────────────────────── 007
  { code: '007', tab: '부엌·above below', unit: U3, title: 'Kitchen', orig: 22,
    intro: '부엌 낱말(stove·microwave·refrigerator·sink·cabinet·faucet·dishes·spoon·fork·chopsticks)과 above·below 를 배웁니다. 이야기: 조이가 리아 이모에게 부엌을 보여 주는데 아기 동생이…',
    fixed: ['stove «난로» → 가스레인지 · cabinet «장식장» → 찬장 · lollipop «사탕 과자» → 막대사탕 · looks like «닮다» → ~처럼 보이다', '«do you want lollipop?» → do you want <b>a</b> lollipop?', '«No, thank you Zoey.» → No, thank you, Zoey. · «Hahha!» → Haha!', '«I have coffee but it is cold.» → I have coffee, but it is cold.'],
    slides: [
      { t: 'cover', k: 'new', img: G('kitchen-cover'), q: 'What is in your kitchen?', story: 'Aunt Leah visits Zoey. Where is Zoey\'s baby brother?', nt: '표지 + Big Question' },
      ...open([['I can name things in the kitchen.', '부엌 물건 이름을 말할 수 있어요.'], ['I can use above and below.', 'above·below 로 위아래를 말할 수 있어요.'], ['I can say what I use when I eat.', '먹을 때 쓰는 것을 말할 수 있어요.']]),
      { t: 'song', k: 'keep', title: 'Tongue Twister', img: G('kitchen-cover'), lines: ['I saw a kitten eating a chicken in the kitchen.', 'I saw a kitten eating a chicken in the kitchen.', '(5x — faster and faster!)'], src: '4쪽 Warm Up', nt: '잰말놀이', n: ['kitten·chicken·kitchen 세 낱말 구분이 핵심'] },
      { t: 'vocab', k: 'fix', hide: true, cols: 4, words: [['stove', '가스레인지', '12237'], ['microwave', '전자레인지', '15552'], ['refrigerator', '냉장고', '16853'], ['sink', '싱크대', 'c7099'], ['cabinet', '찬장', G('cabinet-fridge')], ['faucet', '수도꼭지', 'c7296'], ['dishes', '그릇', '12602'], ['clock', '시계', '12580']], src: 'Vocabulary 6·7쪽', nt: '낱말 ① — 뜻 가리고 먼저' },
      { t: 'vocab', k: 'fix', cols: 4, words: [['stove', '가스레인지', '12237'], ['microwave', '전자레인지', '15552'], ['refrigerator', '냉장고', '16853'], ['sink', '싱크대', 'c7099'], ['cabinet', '찬장', G('cabinet-fridge')], ['faucet', '수도꼭지', 'c7296'], ['dishes', '그릇', '12602'], ['clock', '시계', '12580']], title: 'Words ①', src: '6·7쪽', nt: '낱말 ① — 뜻 공개', n: ['<del>stove 난로 · cabinet 장식장</del> → 가스레인지 · 찬장'] },
      { t: 'vocab', k: 'keep', cols: 3, title: 'Words ② — When we eat', words: [['spoon', '숟가락', '12003'], ['fork', '포크', 'c7134'], ['chopsticks', '젓가락', '15097']], src: '7쪽', nt: '낱말 ② — 먹을 때 쓰는 것', n: ['한 화면에 11개는 많아 먹을 때 쓰는 것 셋을 따로'] },
      { t: 'rule', k: 'new', title: 'above or below?', left: { h: 'above ⬆️', ex: ['The cabinet is **above** the refrigerator.'] }, right: { h: 'below ⬇️', ex: ['The stove is **below** the microwave.'] }, q: 'Point up! Point down! Which one is above?', nt: '규칙 찾기 + 몸으로', n: ['강사가 «above!» 하면 손을 위로, «below!» 하면 아래로 — 30초 게임'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'The cabinet is above the refrigerator.', head: ['what', 'is', 'where'], rows: [['The cabinet', 'is', 'above the refrigerator.'], ['The stove', 'is', 'below the microwave.'], ['The refrigerator', 'is', 'next to the cabinet.']], src: 'Grammar 8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'keep', img: '15097', title: "Let's talk!", q: 'What do you use when you eat?', a: 'I use ___.', chips: ['a spoon', 'a fork', 'chopsticks'], src: '9쪽', nt: '먹을 때 쓰는 것' },
      { t: 'qa', k: 'keep', img: '12602', q: 'What color are your dishes?', a: 'My dishes are ___.', chips: ['white', 'blue', 'green'], src: '10쪽', nt: 'dishes' },
      { t: 'qa', k: 'keep', img: '16853', q: 'What do you have in your refrigerator?', a: 'I have ___ in my refrigerator.', chips: ['milk', 'eggs', 'fruit'], src: '11쪽', nt: '냉장고 안' },
      { t: 'qa', k: 'keep', img: G('kitchen-cover'), q: 'Where are the lamps?', a: 'The lamps are ___ the table.', chips: ['above', 'below'], src: '13쪽', nt: 'above' },
      { t: 'qa', k: 'keep', img: G('cabinet-fridge'), q: 'Where is the refrigerator?', a: 'The refrigerator is ___ the cabinet.', chips: ['above', 'below', 'next to'], src: '14쪽', nt: 'below', n: ['원본 «The refrigerator is below the clock.» → 시계 대신 찬장(같은 below 연습, 사진 한 장으로 above·below 둘 다)'] },
      { t: 'match', k: 'new', title: 'Match it!', left: ['12237', '15552', '16853', 'c7296'], right: ['microwave', 'faucet', 'stove', 'refrigerator'], nt: '짝짓기', n: ['stove·microwave 가 헷갈리는 짝 — 사진으로 구분'] },
      { t: 'guess', k: 'new', img: '17203', open: [0, 2], q: 'Who is waiting in the kitchen?', chips: ['Is it a boy?', 'Is it a girl?', 'It is next to the microwave.'], nt: 'Guess who 타일', n: ['전자레인지 앞에서 기다리는 아이 — 타일을 열 때마다 영어 질문 한 개'] },
      { t: 'ox', k: 'new', img: G('cabinet-fridge'), s: 'The cabinet is below the refrigerator.', nt: '⭕❌', n: ['정답 ❌ → «No! The cabinet is above the refrigerator.»'] },
      { t: 'vocab', k: 'fix', cols: 3, title: 'Story words', words: [['lollipop', '막대사탕', G('zoey-story')], ['looks like', '~처럼 보이다', G('zoey-story')], ['chef', '요리사', '16722']], src: '16쪽', nt: '이야기 낱말', n: ['<del>lollipop 사탕 과자 · looks like 닮다</del> → 막대사탕 · ~처럼 보이다'] },
      { t: 'story', k: 'fix', small: 'Story ①', title: "Zoey's Kitchen", img: '15552', lines: [['Zoey', 'Aunt Leah, do you want a lollipop? I have lollipops in the kitchen.'], ['Aunt Leah', 'No, thank you, Zoey. I have coffee, but it is cold. Where is your microwave?'], ['Zoey', 'The microwave is above the refrigerator.']], src: '17쪽 Role-play', nt: '이야기 ①', n: ['<del>want lollipop</del> → want a lollipop · <del>thank you Zoey</del> → thank you, Zoey · 쉼표 추가'] },
      { t: 'story', k: 'fix', small: 'Story ②', title: "Zoey's Kitchen", img: G('zoey-story'), lines: [['Aunt Leah', 'Oh! Your brother is here. He is next to the refrigerator.'], ['Zoey', 'Oh yes! He is below the cabinet. Haha!'], ['Aunt Leah', 'Haha! He looks like a chef.']], src: '18쪽', nt: '이야기 ②', n: ['<del>Hahha!</del> → Haha! · <del>cabinet haha.</del> → cabinet. Haha!', '요리사 모자를 쓴 아기 사진으로 «looks like a chef» 가 한눈에'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ['Where are they? — They are in the ___.', 'Where is the microwave? — It is ___ the refrigerator.', 'Where is the baby? — He is ___ the refrigerator.'], chips: ['kitchen', 'above', 'next to'], src: '19·20쪽', nt: '이야기 질문', n: ['«Who are they?» 는 말로 — Zoey and Aunt Leah'] },
      { t: 'yourturn', k: 'new', img: 'c5003', title: 'My kitchen', lines: ['In my kitchen, the microwave is ___ the ___.', 'I eat with ___.'], chips: ['above', 'below', 'next to', 'chopsticks'], nt: '내 말로', n: ['실제로 부엌이 보이면 카메라를 돌려 보여 주기'] },
      ...close([['I can name things in the kitchen.', 'stove, sink, cabinet, faucet'], ['I can use above and below.', 'The cabinet is above the refrigerator.'], ['I can say what I use when I eat.', 'I use chopsticks.']], { img: 'c7294', q: 'Do you sing in the bathroom?', ko: '샤워하면서 노래해 본 적 있나요? (다음 시간 — 욕실)' }),
    ] },
  // ───────────────────────── 008
  { code: '008', tab: '욕실', unit: U3, title: 'Bathroom', orig: 20,
    intro: '욕실 낱말(toilet·bathtub·shower·sink·mirror·soap·towel·cabinet·shampoo)과 above·below·next to 를 씁니다.',
    fixed: ['toilet «화장실» → 변기 · bathtub «욕탕» → 욕조 · shower «샤워» → 샤워기 · towel «타월» → 수건 · cabinet «장식장» → 수납장', '욕실의 sink 는 «세면대»(부엌은 싱크대) → 뜻 구분', '목표의 shampoo 가 낱말 쪽에 없음 → 넣음', '웜업 «wash~brush~floss~flush» 물결표 → 쉼표로'],
    slides: [
      { t: 'cover', k: 'new', img: 'c7294', q: 'What is in your bathroom?', story: 'Splash! Where is everything in the bathroom?', nt: '표지 + Big Question' },
      ...open([['I can name things in the bathroom.', '욕실 물건 이름을 말할 수 있어요.'], ['I can use above, below and next to.', '세 가지로 위치를 말할 수 있어요.'], ['I can say my bathroom rules.', '욕실 약속을 말할 수 있어요 — wash, brush, floss, flush']]),
      { t: 'song', k: 'fix', title: 'Bathroom Rules', img: '12131', lines: ['Wash your hands.', 'Brush your teeth.', 'Floss your teeth.', 'Flush the toilet.', 'Wash, brush, floss, flush!'], src: '4쪽 Warm Up', nt: '욕실 약속', n: ['원본은 «wash~brush~floss~flush» 네 낱말만 → 문장으로 늘려 동작과 함께', '강사가 동작을 하면 학생이 낱말을 말하기'] },
      { t: 'vocab', k: 'fix', hide: true, cols: 4, words: [['toilet', '변기', G('toilet')], ['bathtub', '욕조', G('bathtub')], ['shower', '샤워기', '12704'], ['sink', '세면대', '18015'], ['mirror', '거울', '13112'], ['soap', '비누', '13195'], ['towel', '수건', '16870'], ['shampoo', '샴푸', 'c7294']], src: 'Vocabulary 6·7쪽', nt: '낱말 — 뜻 가리고 먼저', n: ['cabinet 은 007 에서 배워 공개 쪽에서만'] },
      { t: 'vocab', k: 'fix', cols: 4, words: [['toilet', '변기', G('toilet')], ['bathtub', '욕조', G('bathtub')], ['shower', '샤워기', '12704'], ['sink', '세면대', '18015'], ['mirror', '거울', '13112'], ['soap', '비누', '13195'], ['towel', '수건', '16870'], ['cabinet', '수납장', G('bath-cabinet')]], title: 'Words', src: '6·7쪽', nt: '낱말 — 뜻 공개', n: ['<del>toilet 화장실 · bathtub 욕탕 · towel 타월</del> → 변기 · 욕조 · 수건', 'sink: 부엌은 싱크대, 욕실은 세면대'] },
      { t: 'table', k: 'keep', small: 'Pattern', title: 'The shower is above the bathtub.', head: ['what', 'is', 'where'], rows: [['The shower', 'is', 'above the bathtub.'], ['The sink', 'is', 'below the mirror.'], ['The toilet', 'is', 'next to the bathtub.']], src: 'Grammar 8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'keep', img: G('bathtub'), title: "Let's talk!", q: 'Do you have a bathtub in your bathroom?', a: 'Yes, I do. / No, I don\'t.', src: '9쪽', nt: '우리 집 욕실' },
      { t: 'count', k: 'keep', img: G('toilet'), q: 'How many toilets do you have at home?', a: 'I have ___.', chips: ['one toilet', 'two toilets'], src: '10쪽', nt: '세어 보기', n: ['one 이면 toilet(‑s 없음)'] },
      { t: 'qa', k: 'keep', img: G('bath-cabinet'), q: 'Where is the shampoo?', a: 'The shampoo is ___ the soaps.', chips: ['above', 'below', 'next to'], src: '11쪽', nt: 'next to' },
      { t: 'qa', k: 'keep', img: G('bath-cabinet'), q: 'Where is the mirror?', a: 'The mirror is ___ the sink.', chips: ['above', 'below', 'next to'], src: '13쪽', nt: 'above' },
      { t: 'qa', k: 'keep', img: G('toilet'), q: 'Where is the sink?', a: 'The sink is ___ the toilet.', chips: ['above', 'below', 'next to'], src: '14쪽', nt: 'next to' },
      { t: 'qa', k: 'keep', img: G('bathtub'), q: 'Where are the towels?', a: 'The towels are ___ the bathtub.', chips: ['above', 'below', 'next to'], src: '16쪽', nt: 'next to' },
      { t: 'match', k: 'new', title: 'Match it!', left: ['13112', '16870', '12704', '13195'], right: ['towel', 'soap', 'mirror', 'shower'], nt: '짝짓기', n: ['짝을 지은 뒤 «Where is the towel?» 처럼 서로 묻기'] },
      { t: 'ox', k: 'new', img: G('baby-sink'), s: 'The babies are above the sink.', nt: '⭕❌', n: ['정답 ❌ → «No! The babies are below the sink.» (원본 17쪽 «The baby is ___ the sink.» — 009·REVIEW 와 같은 사진이라 복수로)'] },
      { t: 'guess', k: 'new', img: G('bird-bathtub'), open: [0, 1], q: 'Who is above the bathtub?', chips: ['Is it a cat?', 'Is it a bird?', 'It is above the bathtub.'], src: '18쪽', nt: 'Guess who 타일', n: ['원본 18쪽 «The bird is ___ the bathtub.» 를 맞히기 게임으로', '위쪽 타일부터 열면 쉽게 맞힙니다 — 아래쪽부터 여세요'] },
      { t: 'story', k: 'new', small: 'Story', title: 'Bath Time!', img: G('bathtub'), lines: [['Zoey', 'Mom, where is my towel?'], ['Mom', 'It is next to the bathtub.'], ['Zoey', 'And where is the shampoo?'], ['Mom', 'It is on the sink, next to the soap.']], nt: '이어지는 이야기', n: ['007 조이가 이어서 등장 — 이 과 낱말·전치사를 모두 씁니다'] },
      { t: 'yourturn', k: 'new', img: '17126', title: 'My bathroom', lines: ['In my bathroom, the mirror is ___ the sink.', 'The towel is ___ the ___.'], chips: ['above', 'below', 'next to', 'shower'], nt: '내 말로' },
      ...close([['I can name things in the bathroom.', 'toilet, bathtub, mirror, towel'], ['I can use above, below and next to.', 'The mirror is above the sink.'], ['I can say my bathroom rules.', 'Wash, brush, floss, flush!']], { img: G('balloon-baby'), q: 'What is above the baby?', ko: '아기 위에 떠 있는 것은 뭘까요? (다음 시간 — 부엌과 욕실)' }),
    ] },
  // ───────────────────────── 009
  { code: '009', tab: '부엌+욕실', unit: U3, title: 'Kitchen and Bathroom', orig: 22,
    intro: '부엌과 욕실 낱말을 모두 쓰고, above·below·next to 로 숨은 동물을 찾습니다.',
    fixed: ['쪽 머리글이 틀림(부엌 쪽에 «Bathroom», 15~17쪽에 «Living Room») → 바로잡음', '«Let\'s talk about kitchen and bathroom» → about the kitchen and the bathroom', 'cabinet «보관장»(007 은 장식장) → 찬장·수납장으로 통일', '풍선 사진에 «Free» 글자 → 글자 없는 사진'],
    slides: [
      { t: 'cover', k: 'new', img: G('balloon-baby'), q: 'Kitchen or bathroom? Where are they?', story: 'Animals are hiding in the kitchen and the bathroom!', nt: '표지 + Big Question' },
      ...open([['I can name things in the kitchen and bathroom.', '부엌과 욕실 물건을 구분해 말할 수 있어요.'], ['I can use above, below and next to.', 'above·below·next to 로 위치를 말할 수 있어요.'], ['I can find hiding animals.', '숨은 동물을 찾아 문장으로 말할 수 있어요.']]),
      { t: 'rule', k: 'new', title: 'Kitchen or bathroom?', left: { h: '🍳 Kitchen', ex: ['stove · microwave', 'refrigerator · dishes'] }, right: { h: '🛁 Bathroom', ex: ['toilet · bathtub', 'shower · towel'] }, q: 'Sink, cabinet, mirror — kitchen, bathroom or both?', nt: '낱말 가르기', n: ['sink·cabinet 은 둘 다 있다는 것을 학생이 찾게', '원본 낱말 두 쪽(5·6쪽)을 한 쪽으로 묶었습니다'] },
      { t: 'vocab', k: 'fix', hide: true, cols: 4, title: 'Remember? 🔒', words: [['faucet', '수도꼭지', 'c7296'], ['cabinet', '찬장, 수납장', G('cabinet-fridge')], ['dishes', '그릇', 'c7099'], ['stove', '가스레인지', '12874'], ['mirror', '거울', '13118'], ['towel', '수건', '17145'], ['soap', '비누', 'c5022'], ['shower', '샤워기', '17126']], src: '5·6쪽', nt: '지난 낱말 떠올리기', n: ['007·008 과 다른 사진으로 — 사진만 외우지 않게'] },
      { t: 'qa', k: 'fix', img: '17145', title: "Let's talk about the kitchen and the bathroom!", q: 'Who washes the dishes at your house?', a: '___ washes the dishes.', chips: ['My mom', 'My dad', 'My brother'], nt: '우리 집 이야기', n: ['<del>about kitchen and bathroom</del> → about the kitchen and the bathroom', '학생이 «I wash the dishes!» 라고 하면 칭찬 — I 뒤에는 ‑es 가 없어요'] },
      { t: 'qa', k: 'fix', img: G('balloon-baby'), q: 'Where is the balloon?', a: 'The balloon is ___ the baby.', chips: ['above', 'below', 'next to'], src: '9쪽', nt: 'above', n: ['«Free» 글자 풍선 → 글자 없는 사진'] },
      { t: 'qa', k: 'keep', img: G('babies-table'), q: 'Where are the babies?', a: 'The babies are ___ the table.', chips: ['above', 'below', 'next to'], src: '10쪽', nt: 'below' },
      { t: 'qa', k: 'keep', img: G('clock-microwave'), q: 'Where is the clock?', a: 'The clock is ___ the microwave.', chips: ['above', 'below', 'next to'], src: '11쪽', nt: 'above' },
      { t: 'qa', k: 'keep', img: G('cat-sink'), q: 'Where is the cat?', a: 'The cat is ___ the sink.', chips: ['above', 'below', 'next to'], src: '13쪽', nt: 'below' },
      { t: 'qa', k: 'keep', img: G('dog-toilet'), q: 'Where is the dog?', a: 'The dog is ___ the toilet.', chips: ['above', 'below', 'next to'], src: '15쪽', nt: 'next to' },
      { t: 'order', k: 'keep', img: G('lizard-fridge'), words: ['above', 'The lizard', 'is', 'the refrigerator'], src: '16쪽 Rearrange', nt: '순서 맞추기' },
      { t: 'order', k: 'keep', img: G('baby-sink'), words: ['are', 'The babies', 'the sink', 'below'], src: '17쪽', nt: '순서 맞추기', n: ['babies 는 복수 → are'] },
      { t: 'guess', k: 'new', img: G('cat-sink'), open: [3], q: 'Who is below the sink?', chips: ['Is it a mouse?', 'Is it a cat?', 'It is below the sink.'], src: '18쪽', nt: 'Guess who 타일', n: ['원본 18쪽 «Where is the mouse? (above the bathtub)» 는 합성 사진 → 앞 쪽 고양이 사진을 타일로 가려 다시 맞히기', '앞에서 본 사진이라 «기억해 맞히기» 가 됩니다'] },
      { t: 'ox', k: 'new', img: G('dog-toilet'), s: 'The dog is above the toilet.', nt: '⭕❌', n: ['정답 ❌ → «No! The dog is next to the toilet.»'] },
      { t: 'memory', k: 'new', items: [G('cat-sink'), G('lizard-fridge'), G('dog-toilet'), G('balloon-baby')], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ①' },
      { t: 'memory', k: 'new', hidden: true, items: [G('cat-sink'), G('lizard-fridge'), G('dog-toilet'), G('balloon-baby')], q: 'Where is the lizard? Where is the dog?', a: 'The lizard is ___ the refrigerator.', nt: '기억 게임 ②', n: ['사진 없이 기억만으로 위치 말하기 — 이 권 전치사를 모두 씁니다'] },
      { t: 'fill', k: 'keep', title: 'Say it!', lines: ['The shower is ___ the bathtub.', 'The toilet is ___ the bathtub.', 'The sink is ___ the mirror.'], chips: ['above', 'below', 'next to'], src: '20쪽', nt: '문장 복습', n: ['원본 마지막 문법 쪽을 빈칸으로'] },
      { t: 'yourturn', k: 'new', img: '12032', title: 'My house tour', lines: ['Welcome to my house!', 'This is my ___.', 'The ___ is next to the ___.'], chips: ['kitchen', 'bathroom', 'bedroom', 'living room'], nt: '우리 집 소개', n: ['001 미아처럼 «Welcome to my house!» 로 시작 — 이 권 전체를 묶는 말하기'] },
      ...close([['I can name things in the kitchen and bathroom.', 'stove, sink, toilet, towel'], ['I can use above, below and next to.', 'The balloon is above the baby.'], ['I can find hiding animals.', 'The cat is below the sink.']], { img: '12032', q: 'Can you show me your house?', ko: '다음 시간은 BTS 6 전체 복습 — 우리 집을 영어로 소개해요!' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 6 Review', orig: 28,
    intro: 'BTS 6 전체 복습. 침실 → 거실 → 부엌·욕실 방을 하나씩 «열며» 넘어갑니다.',
    fixed: ['잰말놀이 «An ice house is not a nice house 4x» 그대로 · 표기 정리', '002·003 의 같은 사진·같은 문제가 그대로 반복(개가 침대에…) → 같은 문장을 다른 사진으로', '«sink/towel/is/the/next to/The» 조각에 the 두 개 → 정답이 하나가 되게 정리'],
    slides: [
      { t: 'cover', k: 'new', img: '13025', q: 'Can you open every room?', story: '4 rooms. Can you find everything? 🔑', nt: '표지' },
      { t: 'song', k: 'keep', title: 'Tongue Twister', img: '12820', lines: ['An ice house is not a nice house.', 'An ice house is not a nice house.', '(4x — faster and faster!)'], src: '4쪽 Warm Up', nt: '잰말놀이', n: ['ice house / a nice house — 띄어 읽기 차이를 즐기는 문장'] },
      { t: 'vocab', k: 'new', hide: true, cols: 4, title: 'Room 1 · Bedroom 🔒', words: [['bed', '침대', '12245'], ['pillow', '베개', '18010'], ['closet', '옷장', '12855'], ['dresser', '서랍장', G('dresser')]], nt: '1번 방 — 침실(001~003)' },
      { t: 'qa', k: 'fix', img: '18658', q: 'Where is the dog?', a: 'The dog is ___ the bed.', chips: ['in', 'on', 'under'], src: '6·7쪽', nt: 'in', n: ['원본 6·7쪽이 같은 문제 두 번 → 한 번으로'] },
      { t: 'qa', k: 'keep', img: '15685', q: 'Where is the cat?', a: 'The cat is ___ the chair.', chips: ['in', 'on', 'under'], src: '10쪽', nt: 'under' },
      { t: 'qa', k: 'keep', img: G('girls-floor'), q: 'Where do they sit?', a: 'They ___ on the floor.', chips: ['sit', 'sits'], src: '11쪽', nt: 'sit' },
      { t: 'qa', k: 'keep', img: G('dog-under-table'), q: 'Where is the dog?', a: 'The dog ___ under the table.', chips: ['stand', 'stands'], src: '13쪽', nt: 'stands' },
      { t: 'order', k: 'keep', img: G('mia-cats'), words: ['sits', 'The cat', 'on', 'the chair'], src: '15쪽', nt: '순서 맞추기' },
      { t: 'vocab', k: 'new', hide: true, cols: 4, title: 'Room 2 · Living room 🔒', words: [['sofa', '소파', '18010'], ['curtains', '커튼', 'c7154'], ['television', '텔레비전', '18881'], ['light switch', '전등 스위치', '19366']], nt: '2번 방 — 거실(004~006)' },
      { t: 'qa', k: 'keep', img: G('cat-front-baby'), q: 'Where is the cat?', a: 'The cat is ___ the baby.', chips: ['next to', 'in front of', 'behind', 'between'], src: '19쪽', nt: 'in front of' },
      { t: 'qa', k: 'keep', img: G('hamster-cats'), q: 'Where is the hamster?', a: 'The hamster is ___ the two cats.', chips: ['next to', 'in front of', 'behind', 'between'], src: '20쪽', nt: 'between' },
      { t: 'qa', k: 'keep', img: G('dog-behind-curtain'), q: 'Where is the dog?', a: 'The dog is ___ the curtain.', chips: ['next to', 'in front of', 'behind', 'between'], src: '21쪽', nt: 'behind' },
      { t: 'qa', k: 'keep', img: G('bird-flowers'), q: 'Where is the bird?', a: 'The bird is ___ the flowers.', chips: ['next to', 'in front of', 'behind', 'between'], src: '22쪽', nt: 'between' },
      { t: 'ox', k: 'new', img: G('toy-snake'), s: 'The snake is in front of the sofa.', src: '23쪽', nt: '⭕❌', n: ['정답 ❌ → «No! It is behind the sofa.»'] },
      { t: 'vocab', k: 'new', hide: true, cols: 4, title: 'Room 3 · Kitchen and bathroom 🔒', words: [['refrigerator', '냉장고', '16853'], ['sink', '세면대', 'c5009'], ['toilet', '변기', G('toilet')], ['bathtub', '욕조', G('bathtub')]], nt: '3번 방 — 부엌·욕실(007~009)' },
      { t: 'qa', k: 'keep', img: G('dog-toilet'), q: 'Where is the dog?', a: 'The dog is ___ the toilet.', chips: ['above', 'below', 'next to'], src: '24쪽', nt: 'next to' },
      { t: 'order', k: 'keep', img: '12704', words: ['above', 'The shower', 'is', 'the bathtub'], src: '25쪽', nt: '순서 맞추기' },
      { t: 'order', k: 'fix', img: '17145', words: ['is', 'The towel', 'next to', 'the sink'], src: '26쪽', nt: '순서 맞추기', n: ['원본 조각 «the/The» 가 둘이라 답이 두 개 → 주어를 한 조각으로'] },
      { t: 'order', k: 'keep', img: G('baby-sink'), words: ['below', 'The babies', 'are', 'the sink'], src: '27쪽', nt: '순서 맞추기' },
      { t: 'memory', k: 'new', items: [G('pineapple-bed'), G('bulldog-pillows'), G('lizard-fridge'), G('bird-bathtub')], q: 'Room 4 · Boss! 5 seconds! 👀', nt: '4번 방 — 보스 기억 게임', n: ['각 과의 재미있는 사진을 한 판에 — 5초 뒤 넘깁니다'] },
      { t: 'memory', k: 'new', hidden: true, items: [G('pineapple-bed'), G('bulldog-pillows'), G('lizard-fridge'), G('bird-bathtub')], q: 'Where is the pineapple? Where is the bird?', a: 'The pineapple is ___ the bed.', nt: '보스 기억 게임 ②', n: ['네 개를 모두 문장으로 말하면 BTS 6 클리어! 🎉'] },
      { t: 'ican', k: 'new', items: [['I can talk about my bedroom.', 'The pillow is on the bed.'], ['I can talk about my living room.', 'The table is in front of the sofa.'], ['I can talk about my kitchen and bathroom.', 'The mirror is above the sink.']], nt: 'BTS 6 전체 I can' },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 6 Unit Test', orig: 17,
    intro: '10문항 말하기 시험. 사진을 보고 «어디에 있나» 를 한 문장으로 답합니다.',
    fixed: ['문항 3: 길 한복판 의자에 만화 고양이를 붙인 합성 사진 → 진짜 사진', '문항 7: TV 앞 만화 쥐 합성 사진 → 사진으로 · «Where does the mouse stand?» 그대로', '문항 8: 곰 인형 사이 고양이·강아지 합성 사진(답이 둘) → 답이 하나인 사진', '사진마다 붙어 있던 출처 글자(«Cover photo created by freepik…») → 뺌', '답칸이 빈 줄뿐 → 문장 틀을 줘 말로 답하기 쉽게'],
    slides: [
      { t: 'cover', k: 'new', img: '15546', q: 'Test time! You can do it! 💪', story: '10 questions · 1 point each', nt: '표지' },
      { t: 'qa', k: 'fix', img: G('cat-stand-bed'), title: '1.', q: 'Where is the cat?', a: 'The cat is ___ the bed.', src: '문항 1', nt: '문항 1', n: ['침대 위 고양이(002 와 같은 사진 — 본 제작 때 누운 고양이 사진으로)'] },
      { t: 'qa', k: 'fix', img: G('third-cat'), title: '2.', q: 'Where is the cat?', a: 'The cat is ___ the bed.', src: '문항 2', nt: '문항 2', n: ['이불 속 고양이 → in (1번 on 과 짝)'] },
      { t: 'qa', k: 'fix', img: '15685', title: '3.', q: 'Where is the cat?', a: 'The cat is ___ the chair.', src: '문항 3', nt: '문항 3', n: ['원본: 길 한복판 안락의자 밑 만화 고양이 둘(합성) → 의자 밑 고양이 사진 · 한 마리라 is'] },
      { t: 'qa', k: 'keep', img: G('baby-highchair'), title: '4.', q: 'Where does the baby sit?', a: 'The baby sits ___ the chair.', src: '문항 4', nt: '문항 4' },
      { t: 'qa', k: 'keep', img: G('girls-floor'), title: '5.', q: 'Where do the girls sit?', a: 'The girls ___ on the ___.', src: '문항 5', nt: '문항 5', n: ['원본 아기 둘 사진(출처 글자 박힘) → 바닥에 앉은 아이들 · sit(‑s 없음)과 floor 둘을 확인'] },
      { t: 'qa', k: 'keep', img: '16127', title: '6.', q: 'Where is the baby?', a: 'The baby lies down ___ the ___.', src: '문항 6', nt: '문항 6' },
      { t: 'qa', k: 'fix', img: '16311', title: '7.', q: 'Where does the mouse stand?', a: 'The mouse stands ___ the ___.', src: '문항 7', nt: '문항 7', n: ['원본: TV 앞 만화 쥐(합성) → 바닥의 진짜 쥐 사진 · 답 on the floor(002 낱말)'] },
      { t: 'qa', k: 'fix', img: '18820', title: '8.', q: 'Where is the cat?', a: 'The cat is ___ the sofa.', src: '문항 8', nt: '문항 8', n: ['원본은 고양이·강아지 둘을 한 번에 물어 답이 두 문장 → 한 문장으로'] },
      { t: 'qa', k: 'keep', img: G('butterfly-lamp'), title: '9.', q: 'Where is the butterfly?', a: 'The butterfly is ___ the lamp.', src: '문항 9', nt: '문항 9' },
      { t: 'qa', k: 'keep', img: G('bath-cabinet'), title: '10.', q: 'Where is the sink?', a: 'The sink is ___ the mirror.', src: '문항 10', nt: '문항 10', n: ['원본은 노란 화살표로 가리킴 — 사진에서 세면대를 손가락으로 짚게'] },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–3', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['4–6', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['7–9', 'Great!', '거의 다 왔어요 — 하나만 더'], ['10 ⭐', 'Perfect!', 'BTS 7 로 출발! 🎉']], src: '점수표', nt: '점수표', n: ['원본 «You did a great job!» 시상대 그림 → 점수마다 다음 할 일을 적은 표로'] },
      { t: 'next', k: 'new', img: '19697', q: 'Can you move your ears?', ko: 'BTS 7 예고 — 얼굴과 몸(head, face, body)을 배워요! 귀를 움직일 수 있나요? 😜', nt: '다음 권 예고', n: ['BTS 7 은 «Head and face → Parts of the body → Monsters»', '답은 말하지 않고 다음 권 첫 수업의 질문으로'] },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
    ] },
  ],
};
