// BTS 11 새 교재 설계 데이터. k: 'keep'(원본 내용) | 'fix'(원본을 고침) | 'new'(새 활동)
// 사진 번호 = cloudflare-deploy/public/img/scene-words/<번호>.webp · 'gen:' = 새로 만들 사진($T/gen/req-bts-11.json)
import { open, close } from '../common.mjs';
const USONG_2 = { t: 'song', k: 'new', small: "Let's sing! ♪ Muffin Man", title: "Where Can You Buy It? 🛍️", img: "gen:bts-11-song-stores", nt: "가게 노래(새로 지음)", n: ["곡조: The Muffin Man (저작권 만료 곡) — 가사는 이 단원 낱말로 새로 지었습니다","질문 줄에서는 손을 이마에 대고 두리번거리고, 대답 줄에서는 가게 쪽을 손가락으로 가리켜요. 다른 물건·가게로 바꿔 불러도 좋아요."], src: '새로 지음', lines: ["Where can you buy a teddy bear,","a teddy bear, a teddy bear?","You can buy a teddy bear","at the toy store in town!","I need to buy some medicine,","some medicine, some medicine.","You can buy some medicine","at the pharmacy in town!"] };
const USONG_3 = { t: 'song', k: 'new', small: "Let's sing! ♪ Yankee Doodle", title: "Cheap or Expensive? 🖊️", img: "gen:bts-11-song-stationery", nt: "문구점 노래(새로 지음)", n: ["곡조: Yankee Doodle (저작권 만료 곡) — 가사는 이 단원 낱말로 새로 지었습니다","'cheap'에서는 엄지 척, 'expensive'에서는 두 손으로 볼을 감싸며 깜짝 놀라는 표정을 지어요."], src: '새로 지음', lines: ["I need school supplies today,","a pen and lots of crayons.","How much is the little pen?","It's cheap, so I can buy it!","How much is the fountain pen?","Oh no! It's so expensive!","I want it, but I can't buy it.","I'm happy with my cheap one!"] };
const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3';

export const COURSE = {
  head: `<h1>BTS 11 새 교재 — 쇼핑·가게·가격 (전 과 설계 시안)</h1>
<p class="lead">사이트의 BTS 11 원본 <b>287쪽</b>(11묶음)을 읽고 원고로 옮긴 뒤, BTS 1 시안과 같은 원칙(한 쪽 한 목표 · 가림→공개 · 따라→바꿔→내 말 · 규칙 찾기 · 이어지는 이야기 · 과 끝 «I can» · 다음 시간 예고)으로 다시 짰습니다. 위 단추로 과를 고르세요.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>배우는 <b>낱말(돈·옷·가게·학용품)·문장(can / want to / need to / It's ___ dollars)·범위는 원본 그대로</b>입니다. 원본 인물(Tony·Natasha·Sally·Vicky·Tommy·John·Julie·Tessa·James·Fred·Lea·Derek)도 그대로 두었습니다. 원본의 오타·문법 오류·어긋난 뜻풀이·비현실적인 가격은 고쳤습니다(과마다 목록).</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 <b>표지 + Big Question</b>, <b>규칙 찾기</b>, <b>⭕❌</b>, <b>Guess who 타일</b>, <b>기억·순서·짝 게임</b>, <b>내 말로(Your turn)</b>, <b>I can ✅</b>, <b>다음 시간 예고</b>를 넣었습니다. 가격 쪽은 «숫자 읽기 → 문장으로 말하기 → 살 수 있나 판단하기» 순서로 올라갑니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진에 대해</b><br>지금 사이트에 있는 사진을 쓰고, 맞는 장면이 없는 자리(표지·이야기·예고·Guess who 등 39장)는 <b>새로 만드는 사진</b>으로 요청했습니다(점선 상자 = 생성 중). 원본의 가짜 지폐 사진($5,000·$50,000 지폐 등)은 실제로 없는 돈이라 쓰지 않았습니다.</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>고친 문장 승인</b> — 과마다 «이 과에서 고친 것». 특히 007 의 need/want 예문(«The king needs a crown» 등 → 생활 예문), 004 의 gadget store 뜻(«공구점» → 전자기기 가게), 003 의 «add ___ in my cart» → «to my cart».</li>
<li><b>가격</b> — 008 Lea 의 «컴퓨터 $7,000·휴대폰 $5,500» 이 비현실적이라 노트북 $2,000·휴대폰 $800 으로 바꿨습니다. 002 의 가짜 지폐($5,000·$50,000·$1,000,000 지폐)는 «큰 수 읽기» 표로 바꿨습니다. 그대로 둘지 정해 주세요.</li>
<li><b>BTS 10 에서 넘어온 내용</b> — 001·004·005 복습 쪽에 BTS 10 의 «feel» 문법이 섞여 있어 뺐습니다.</li>
<li><b>006 쇼핑 목록 번호</b> — 원본은 6번이 빠져 있습니다(1~5, 7, 8). 1~7 로 다시 매겼습니다. 리코더를 «music store» 에서 산다고 정리했습니다.</li>
<li><b>노래</b> — 원본 «Let's Go Shopping» 노래는 가사를 옮기지 않고 자체 챈트로 바꿨습니다. 원곡을 쓸지(저작권 확인), 새로 녹음할지.</li>
<li><b>새로 만들 사진 39장</b> — 요청 목록은 gen/req-bts-11.json.</li>
<li><b>새 단원 노래 2곡</b> — 노래가 없던 단원에 새로 지은 노래를 Hello Song 바로 뒤에 넣었습니다: Unit 2 «Where Can You Buy It?»(The Muffin Man) · Unit 3 «Cheap or Expensive?»(Yankee Doodle). 곡조는 모두 저작권이 끝난 동요(또는 손뼉·랩 챈트)이고 가사는 그 단원 낱말로 새로 썼습니다. <b>가사 승인</b>과 <b>녹음(반주·노래)</b>이 필요합니다 — 지금은 줄마다 🔊(기계 음성)로만 들을 수 있습니다.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '옷가게', unit: U1, title: 'Clothing Store', orig: 36,
    intro: '돈(US dollars)·쇼핑·옷가게 낱말과 «can / want to» 를 배웁니다. 이야기: 토니와 나타샤가 겨울옷을 사러 옷가게에 갑니다.',
    fixed: ['can 뜻 «할 수 있다, 양철통» → 이 과에서는 «~할 수 있다» 만(양철통은 다른 낱말)', 'on my way 뜻 «내 길에» → «가는 길에» · rich 뜻 «풍부한» → «부자인»', '«Where are you going ?» 물음표 앞 띄어쓰기', 'clerk «She assists people» → She helps people(아이 수준 동사)', '이야기 대사를 누가 말하는지 섞여 있음 → 말하는 사람을 정리하고 이야기 질문도 내용과 맞춤', '복습 쪽에 섞인 BTS 10 «feel» 문법 삭제', '원본 노래 가사는 옮기지 않고 자체 챈트로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c001', q: 'What do you want to buy?', story: 'Tony and Natasha are going shopping. Winter is coming!', nt: '표지 + Big Question', n: ['«무엇을 사고 싶니?» — 이 권 전체의 질문입니다', '사진 속 우스꽝스러운 옷을 보며 «Is it big? Is it funny?» 로 가볍게 시작'] },
      ...open([['I can talk about money and shopping.', '돈과 쇼핑에 대해 말해요.'], ['I can say what I want to buy.', '사고 싶은 것을 말해요.'], ['I can say what I can do.', '할 수 있는 것을 말해요.']]),
      { t: 'vocab', k: 'fix', hide: true, title: 'What are you wearing now?', words: [['gloves', '장갑', '16357'], ['jeans', '청바지', '16076'], ['jacket', '재킷', '16228'], ['swimsuit', '수영복', '18119'], ['hoodie', '후드티', 'c7263'], ['boots', '부츠', 'gen:bts-11-boots']], src: 'Warm Up 5쪽', nt: '몸풀기 — 옷 낱말', n: ['«What are you wearing now?» 를 먼저 묻고, 학생이 입은 옷을 가리키며 시작', '원본의 shorts 는 사진이 흐려 빼고 boots 로 대신(다음 이야기의 겨울옷과 이어짐)'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'New words ①', words: [['US dollars', '미국 달러', '12916'], ['currency', '통화(나라마다 다른 돈)', '12338'], ['shopping', '쇼핑', '12506'], ['buy', '사다', '19315'], ['sell', '팔다', '13260']], src: 'Vocabulary 7쪽', nt: '낱말 ① — 가리고 먼저', n: ['뜻을 가린 채 사진만 보고 영어로 먼저 말하게 합니다(인출 연습)', 'buy ↔ sell 은 손동작(받기 ↔ 주기)으로 짝지어 기억'] },
      { t: 'vocab', k: 'fix', title: 'New words ①', words: [['US dollars', '미국 달러', '12916'], ['currency', '통화(나라마다 다른 돈)', '12338'], ['shopping', '쇼핑', '12506'], ['buy', '사다', '19315'], ['sell', '팔다', '13260']], src: 'Vocabulary 7쪽', nt: '낱말 ① — 공개', n: ['뜻을 공개하고 한 번씩 따라 말하기'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'New words ②', words: [['online shopping', '인터넷 쇼핑', '12213'], ['clothes', '옷', '12373'], ['clothing store', '옷가게', '12856'], ['clerk', '점원', '14301'], ['brand', '상표, 브랜드', '18748']], src: 'Vocabulary 8쪽', nt: '낱말 ② — 가리고 먼저', n: ['원본 10개를 한 쪽에 몰지 않고 5개씩 두 쪽 — 화상수업에서 글자가 너무 작아지지 않게'] },
      { t: 'vocab', k: 'fix', title: 'New words ②', words: [['online shopping', '인터넷 쇼핑', '12213'], ['clothes', '옷', '12373'], ['clothing store', '옷가게', '12856'], ['clerk', '점원', '14301'], ['brand', '상표, 브랜드', '18748']], src: 'Vocabulary 8쪽', nt: '낱말 ② — 공개' },
      { t: 'rule', k: 'new', title: 'can or want to?', left: { h: 'can', ex: ['She **can** have a snowball fight.', 'I **can** buy a hat.'] }, right: { h: 'want to', ex: ['I **want to** buy that dress.', "I **don't want to** buy that jacket."] }, q: 'What comes after "can" and "want to"?', src: 'Grammar 9쪽', nt: '규칙 찾기', n: ['두 줄을 보고 «뒤에 오는 말(buy, have)이 모양이 안 바뀐다» 를 학생이 먼저 찾게 합니다', '원본 예문 세 개를 그대로 살렸습니다'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'He wants to buy clothes.', head: ['who', 'want to', '+ word'], rows: [['I / You', 'want to', 'buy clothes.'], ['He / She', '**wants** to', 'buy clothes.'], ['They', 'want to', 'buy clothes.']], tip: 'he·she 뒤에서만 wants — can 은 누구든 can 그대로', src: 'Sentence Pattern 10쪽', nt: '문장 틀', n: ['원본의 주어·동사 용어는 강사 메모로 옮기고 학생 화면은 틀만 남겼습니다'] },
      { t: 'qa', k: 'fix', img: '14620', title: 'Who is she?', q: 'Who is she? What does she do?', a: 'She is a ___. She helps people in the store.', chips: ['clerk'], src: '11쪽', nt: '점원', n: ['원본 «assists» → helps(아이 수준 동사)'] },
      { t: 'qa', k: 'keep', img: '12792', q: 'What are they doing?', a: 'They are ___.', chips: ['shopping'], src: '12쪽', nt: '쇼핑' },
      { t: 'qa', k: 'keep', img: '16244', q: 'What does he have?', a: 'He has ___.', chips: ['money', 'a wallet'], src: '13쪽', nt: '돈' },
      { t: 'fill', k: 'keep', img: '17135', title: 'Does she like shopping?', lines: ['Does she like to go shopping? — Yes, she ___.', "Does he like to go shopping? — No, he ___."], chips: ['does', "doesn't"], src: '14쪽', nt: '예/아니오', n: ['does / doesn\'t 로 짧게 답하는 연습'] },
      { t: 'yourturn', k: 'keep', img: '12506', title: 'Your family', lines: ['Who likes to go shopping in your family?', 'My ___ likes to go shopping.'], chips: ['mom', 'dad', 'sister', 'brother'], src: '15쪽', nt: '내 이야기' },
      { t: 'qa', k: 'fix', img: 'gen:bts-11-usa', q: 'Where is he? What does he have?', a: 'He is in the ___. He has US ___.', chips: ['USA', 'dollars'], src: '16쪽', nt: '미국 달러', n: ['원본 사진은 지폐만 있어 «어디에 있나» 를 알 수 없었음 → 미국 국기 앞 사람 사진으로'] },
      { t: 'qa', k: 'keep', img: '13300', q: 'What are they?', a: 'They are ___.', chips: ['stores'], src: '17쪽', nt: '가게들' },
      { t: 'qa', k: 'keep', img: '12856', q: 'What store is it?', a: "It's a ___ ___.", chips: ['clothing store'], src: '18쪽', nt: '옷가게' },
      { t: 'qa', k: 'keep', img: '13260', q: 'What does it sell?', a: 'It sells ___.', chips: ['shoes'], src: '19쪽', nt: '파는 것' },
      { t: 'fill', k: 'fix', img: '12373', title: "What's in the clothing store?", lines: ['Shirts and ___ are in the clothing store.', 'A dress and ___ are in the clothing store.', 'Shoes and ___ are in the clothing store.'], chips: ['pants', 'jackets', 'boots'], src: '20·21쪽', nt: '옷가게 안', n: ['원본 세 쪽을 한 쪽으로 — 사진 속 옷을 가리키며 채우기'] },
      { t: 'memory', k: 'new', items: ['16357', '16227', '15722', '12304'], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ① 보기', n: ['5초 보여 주고 다음 쪽으로 넘깁니다'] },
      { t: 'memory', k: 'new', hidden: true, items: ['16357', '16227', '15722', '12304'], q: 'What does the store sell?', a: 'It sells ___, ___ …', nt: '기억 게임 ② 말하기', n: ['«It sells gloves, a hat…» — sells 를 여러 번 쓰게 됩니다'] },
      { t: 'guess', k: 'new', img: 'gen:bts-11-guess-dog', open: [0, 4], q: 'Who is it? What is it wearing?', chips: ["It's a dog!", "It's wearing a scarf.", "It's wearing a hat."], nt: 'Guess who 타일', n: ['타일을 하나씩 열며 맞히기 — 모자·목도리를 한 강아지라 아이들이 웃습니다', '맞힐 때마다 옷 낱말 문장으로'] },
      { t: 'ox', k: 'new', img: '12856', s: 'A clothing store sells bread.', nt: '⭕❌', n: ['정답 ❌ → «No! It sells clothes.» 까지 말하면 성공'] },
      { t: 'vocab', k: 'fix', title: 'Story words', words: [['on my way', '가는 길에', '12081'], ['rich', '부자인', '15822'], ['winter', '겨울', '12537']], src: 'New Words 22쪽', nt: '이야기 낱말', n: ['원본 «내 길에»·«풍부한» 을 이야기 속 뜻으로 고쳤습니다'] },
      { t: 'story', k: 'fix', img: 'gen:bts-11-tony-nat', title: 'Going shopping ①', lines: [['Tony', 'Hey, Nat!'], ['Natasha', "What's up, Tony? Where are you going?"], ['Tony', "I'm going to the clothing store."], ['Natasha', "I'm on my way there, too! Let's go together."]], src: 'Role Play 23쪽', nt: '이야기 ①', n: ['학생과 역할을 나눠 읽기 — 한 번은 강사가 Tony, 한 번은 학생이 Tony', '물음표 앞 띄어쓰기 정리'] },
      { t: 'story', k: 'fix', img: 'gen:bts-11-winter-set', title: 'Going shopping ②', lines: [['Tony', 'Sure! What will you buy?'], ['Natasha', 'I will buy a jacket. Winter is coming.'], ['Tony', 'Alright! I need a winter hat, a scarf and gloves.']], src: '24쪽', nt: '이야기 ②', n: ['원본은 누가 무엇을 사는지 대사 순서가 헷갈림 → 문장 뜻에 맞게 말하는 사람을 정리했습니다(jacket = Natasha, 모자·목도리·장갑 = Tony)'] },
      { t: 'story', k: 'keep', img: 'gen:bts-11-800', title: 'Going shopping ③', lines: [['Natasha', 'How much money do you have?'], ['Tony', 'I have 100 dollars here.'], ['Natasha', 'Well, I have 800 dollars!'], ['Tony', 'Wow! You are rich!']], src: '25쪽', nt: '이야기 ③', n: ['«Wow!» 는 크게, 표정까지 — 가장 웃음이 나는 대목입니다'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ['Where will Tony and Natasha go? — They will go to the ___ ___.', 'What will Natasha buy? — She will buy a ___.', 'What does Tony need? — He needs a hat, a ___ and ___.', 'How much money does Natasha have? — She has ___ dollars.'], chips: ['clothing store', 'jacket', 'scarf', 'gloves', '800'], src: '26쪽', nt: '이야기 질문', n: ['원본 질문을 이야기 내용과 맞췄습니다'] },
      { t: 'yourturn', k: 'keep', img: '18746', title: 'Your turn!', lines: ['I want to buy ___ at the clothing store.', "I don't want to buy ___."], chips: ['a jacket', 'boots', 'a hoodie'], src: '27쪽', nt: '내 말로', n: ['want to / don\'t want to 둘 다 말하기'] },
      { t: 'yourturn', k: 'fix', img: 'c7186', title: 'Draw it! Guess it!', lines: ['Draw clothes in 30 seconds.', 'Friend: Is it a ___?', 'You: Yes! I want to buy a ___.'], src: 'Game 28쪽', nt: '그리기 게임', n: ['원본 그리기 게임을 «맞히면 want to 문장» 으로 — 화상수업에서는 화이트보드 사용'] },
      { t: 'song', k: 'fix', title: "Let's Go Shopping!", lines: ["Let's go shopping, you and me!", 'Hats and scarves, what do we see?', 'I want to buy a jacket, too.', 'Red or blue? Red or blue?'], img: '13092', src: 'Song 29쪽', nt: '챈트', n: ['원본 노래: Let\'s Go Shopping — 가사는 옮기지 않고 이 과 낱말로 지은 챈트', '박수 두 번에 한 줄씩'] },
      ...close([['I can talk about money and shopping.', 'They are shopping. He has US dollars.'], ['I can say what I want to buy.', 'I want to buy a jacket.'], ['I can say what I can do.', 'I can buy a hat.']], { img: 'gen:bts-11-c002', q: 'How much money is it?', ko: '돈이 얼마일까?' }),
    ] },
  // ───────────────────────── 002
  { code: '002', tab: '돈·가격', unit: U1, title: 'Money and Prices', orig: 29,
    intro: '큰 수(hundred·thousand·million)와 가격 말하기(It\'s ___ dollars / They\'re ___ dollars)를 배웁니다. 점원이 옷가게 가격표를 보여 줍니다.',
    fixed: ['clerk 뜻 «서기» → «점원»', '«They are ___» (돈 한 묶음) → It\'s money from different countries', '«Do you have 100$?» 등 $ 뒤 표기 → $100($는 숫자 앞)', '가짜 지폐 사진($5,000·$50,000·$1,000,000 지폐) → «큰 수 읽기» 표와 실제 사진으로', '«I\'m the clerk remember?» 쉼표 → I\'m the clerk, remember?', '«The ___ dress is … the other dress is …» 두 벌 비교 문장 정리'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c002', q: 'How much money is it?', story: 'Big numbers, big money! Can you read them?', nt: '표지 + Big Question', n: ['사진 속 돈을 보며 «Is it a lot?» — 큰 수에 대한 호기심으로 시작'] },
      ...open([['I can read big numbers.', '큰 수를 읽어요.'], ['I can say how much it is.', '가격을 말해요.'], ["I can ask 'How much is it?'", '가격을 물어요.']]),
      { t: 'vocab', k: 'fix', hide: true, title: 'Do you remember?', words: [['US dollars', '미국 달러', '12916'], ['currency', '통화', '12338'], ['clerk', '점원', '19438'], ['customer', '손님', '12883'], ['clothing store', '옷가게', '14620'], ['brand', '상표', '18748']], src: 'Vocabulary 5쪽', nt: '지난 시간 낱말', n: ['지난 시간과 일부러 다른 사진 — 같은 낱말을 새 장면에서 떠올리기', 'clerk 뜻 «서기» → «점원»'] },
      { t: 'numbers', k: 'fix', title: 'Big numbers', nums: [[1, 'one'], [15, 'fifteen'], [20, 'twenty'], [50, 'fifty'], [90, 'ninety'], [100, 'one hundred'], ['1,000', 'one thousand'], ['5,000', 'five thousand'], ['100,000', 'one hundred thousand'], ['1,000,000', 'one million']], src: 'Vocabulary 6쪽', nt: '큰 수', n: ['강사가 수를 가리키면 학생이 읽기 → 거꾸로 학생이 가리키고 강사가 읽기', 'hundred(백)·thousand(천)·million(백만) — 쉼표 세 자리마다 이름이 바뀝니다'] },
      { t: 'rule', k: 'new', title: 'is or are?', left: { h: 'one thing', ex: ['The scarf **is** $20.', 'It **is** twenty dollars.'] }, right: { h: 'two or more', ex: ['The gloves **are** $50.', 'They **are** fifty dollars.'] }, q: 'When do we say "is"? When do we say "are"?', nt: '규칙 찾기', n: ['gloves·jeans·socks 처럼 짝으로 된 옷은 are — 학생이 먼저 찾게'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'How do we say it?', head: ['We write', 'We say'], rows: [['$1', 'one dollar'], ['$100', 'one hundred dollars'], ['$5,000', 'five thousand dollars'], ['$1,000,000', 'one million dollars']], src: 'Grammar 7쪽', nt: '가격 읽기', n: ['1달러만 dollar, 나머지는 dollars · $ 는 숫자 앞에 — $15·$50 도 강사가 더 불러 줍니다', '원본에 «100$» 처럼 $ 가 뒤에 붙은 곳이 여럿 → 모두 $100 로'] },
      { t: 'qa', k: 'fix', img: '12338', q: 'What is it?', a: "It's ___ from different countries.", chips: ['money'], src: '8쪽', nt: '여러 나라 돈', n: ['원본 «They are ___» → 돈(셀 수 없음)은 It\'s money'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-11-onedollar', q: 'How much is it?', a: "It's one ___.", chips: ['dollar'], src: '9쪽', nt: '1달러' },
      { t: 'qa', k: 'fix', img: '12916', q: 'Do you have $100?', a: "Yes, I do. / No, I ___.", chips: ["don't"], src: '10쪽', nt: '100달러', n: ['«100$» → $100'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-11-bigmoney', q: 'How much money does he have?', a: 'He has five ___ dollars. He is ___!', chips: ['thousand', 'rich'], src: '11쪽', nt: '5천 달러', n: ['원본 가짜 지폐 사진 → 돈다발을 든 아이 사진. 금액은 강사가 말해 줍니다'] },
      { t: 'fill', k: 'fix', img: '18068', title: 'Wow! Big money!', lines: ['$50,000 — fifty ___ dollars', '$100,000 — one ___ ___ dollars', '$1,000,000 — one ___ dollars'], chips: ['thousand', 'hundred', 'million'], src: '12~14쪽', nt: '더 큰 수', n: ['원본 세 쪽(가짜 지폐) → 한 쪽. 사진은 «백만 달러 수표» 를 든 아이', '«Wow! She is rich!» 로 마무리'] },
      { t: 'qa', k: 'keep', img: '19799', q: 'What is it? When do you wear it?', a: "It's a ___. I wear it when it's ___.", chips: ['cap', 'sunny'], src: '15쪽', nt: '모자' },
      { t: 'qa', k: 'keep', img: '15722', q: 'What color are your socks?', a: 'My socks are ___.', src: '16쪽', nt: '양말', n: ['학생이 실제로 신은 양말 색으로 — 발을 카메라에 보여 주면 웃음'] },
      { t: 'story', k: 'fix', img: '14301', title: 'Come in!', lines: [['Clerk', "Hi, student! I'm the clerk, remember?"], ['Clerk', "We're in the clothing store. Come in!"], ['Clerk', 'Look at the price tags!']], src: '17·18쪽', nt: '점원 등장', n: ['«remember» 앞 쉼표 · «COME IN!» 대문자 → Come in!'] },
      { t: 'fill', k: 'fix', img: '18879', title: 'How much is it? ①', lines: ['The T-shirt is $15. — It is ___ dollars.', 'The jeans are $90. — They are ___ dollars.', 'The scarf is $20. — It is ___ dollars.'], chips: ['fifteen', 'ninety', 'twenty'], src: '19~21쪽', nt: '가격 ①', n: ['«15$» → $15'] },
      { t: 'fill', k: 'fix', img: '16357', title: 'How much is it? ②', lines: ['The gloves are $50. — They are ___ ___.', 'The raincoat is $30. — It is ___ ___.', 'The red dress is $100, and the blue dress is $120.'], chips: ['fifty dollars', 'thirty dollars'], src: '22~24쪽', nt: '가격 ②', n: ['두 드레스 비교 문장을 정리했습니다(원본 «The ___ dress is … and the other dress is …»)'] },
      { t: 'ox', k: 'new', img: '16398', s: 'How much is the jackets?', nt: '⭕❌ 문장 고치기', n: ['정답 ❌ → «How much are the jackets?»', '규칙 찾기(is/are)를 몸으로 확인'] },
      { t: 'guess', k: 'new', img: '15649', open: [1, 3], q: 'What is it? How much is it?', chips: ["It's a raincoat.", "It's thirty dollars."], nt: 'Guess who 타일', n: ['빗물을 튀기는 노란 비옷 — 타일이 열릴 때마다 «Is it a hat? Is it a raincoat?»'] },
      { t: 'count', k: 'new', img: '16833', q: 'How many dresses are there?', a: 'There are ___ dresses.', nt: '세어 보기', n: ['세고 나서 «Which dress do you want?» 로 이어 가기'] },
      { t: 'memory', k: 'new', items: ['19799', '15722', '12304', '16357'], q: 'Look at the price tags! 5 seconds! 👀', nt: '기억 게임 ① 보기', n: ['강사가 물건마다 가격을 말해 줍니다(모자 $10, 양말 $5, 목도리 $20, 장갑 $50)'] },
      { t: 'memory', k: 'new', hidden: true, items: ['19799', '15722', '12304', '16357'], q: 'How much is the scarf?', a: "It's ___ dollars.", nt: '기억 게임 ② 말하기', n: ['가격까지 기억해 문장으로 — It\'s / They\'re 를 고르게'] },
      { t: 'yourturn', k: 'new', img: '14620', title: 'Be the clerk!', lines: ['Clerk: Welcome! How can I help you?', 'You: I want to buy ___.', "Clerk: It's ___ dollars. / They're ___ dollars."], nt: '역할 놀이', n: ['학생이 점원이 되어 강사에게 가격을 말합니다 — 역할을 바꿔 한 번 더'] },
      ...close([['I can read big numbers.', 'one thousand, one million'], ['I can say how much it is.', "It's twenty dollars. They're fifty dollars."], ["I can ask 'How much is it?'", 'How much are the gloves?']], { img: 'gen:bts-11-c003', q: 'Which scarf do you want?', ko: '어느 목도리가 좋아?' }),
    ] },
  // ───────────────────────── 003
  { code: '003', tab: '쇼핑하기', unit: U1, title: 'Going Shopping', orig: 30,
    intro: '샐리와 함께 옷가게에서 목도리를 사고, 남은 돈을 계산한 뒤 인터넷 쇼핑으로 $500 장바구니를 채웁니다.',
    fixed: ['«forty two»·«seventy five» → forty-two·seventy-five(붙임표)', '«Hmm.. They are all nice» → Hmm… They are all nice', '«Take the money.» → Here is the money.(손님이 점원에게 돈을 줄 때)', '«We have nice sweaters too?» 물음표 → too!', '«add ___ in your cart» → add ___ to your cart', '가격 표기 «$» 위치 통일'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c003', q: 'Which scarf do you want?', story: 'Sally has 100 dollars. What will she buy?', nt: '표지 + Big Question', n: ['색색의 목도리 앞에서 고민하는 사람 — «Red? Blue? Black?» 로 시작'] },
      ...open([['I can buy things in a store.', '가게에서 물건을 사요.'], ['I can say how much money I have.', '가진 돈이 얼마인지 말해요.'], ['I can shop online.', '인터넷으로 쇼핑해요.']]),
      { t: 'vocab', k: 'new', hide: true, title: 'Clothes 🔒', words: [['scarf', '목도리', '12304'], ['sweater', '스웨터', '18112'], ['jacket', '재킷', '16228'], ['pants', '바지', '13160'], ['shoes', '신발', '12702'], ['hat', '모자', '16227']], nt: '옷 낱말 복습', n: ['뜻을 가리고 사진만 보고 먼저 말하기 — 오늘 가게에서 살 물건들'] },
      { t: 'rule', k: 'new', title: 'want to or can?', left: { h: 'want to', ex: ['I **want to** buy a scarf.', 'She **wants to** go shopping.'] }, right: { h: 'can', ex: ['I **can** buy a scarf.', 'She **can** go shopping.'] }, q: 'Which one changes with "she": want or can?', nt: '규칙 찾기', n: ['she 뒤에서 want 는 wants 가 되지만 can 은 그대로 — 학생이 찾게 합니다'] },
      { t: 'story', k: 'keep', img: 'gen:bts-11-sally', title: "Hi, I'm Sally!", lines: [['Sally', "Hello, student! I'm Sally."], ['Sally', "I'm going to go shopping."], ['Sally', 'Do you want to come with me?']], src: '5·6쪽', nt: '샐리 등장' },
      { t: 'fill', k: 'keep', img: '12916', title: "Let's go!", lines: ["Let's go to the ___ ___!", 'I have ___ ___.'], chips: ['clothing store', '100 dollars'], src: '7쪽', nt: '어디로? 얼마?' },
      { t: 'story', k: 'keep', img: '14301', title: 'In the store', lines: [['Clerk', 'Welcome to the store. How can I help you?'], ['Sally', 'Hello! I want to buy a scarf.'], ['Clerk', 'Okay. We have so many scarves. What do you like?']], src: '8·9쪽', nt: '점원과 대화', n: ['scarf → scarves(f 가 ves 로) 강사가 짚어 줍니다'] },
      { t: 'numbers', k: 'fix', title: 'Scarf prices', nums: [[42, 'forty-two'], [20, 'twenty'], [80, 'eighty'], [75, 'seventy-five'], [60, 'sixty']], src: '10쪽', nt: '목도리 가격', n: ['«forty two»·«seventy five» → 붙임표를 넣었습니다'] },
      { t: 'fill', k: 'keep', img: '12304', title: 'How much is it?', lines: ['The red scarf is ___ dollars.', 'The blue scarf is ___ dollars.', 'The black scarf is ___ dollars.', 'The orange scarf is ___ dollars.', 'The green scarf is ___ dollars.'], src: '10·11쪽', nt: '가격 말하기', n: ['앞 쪽 숫자를 가린 채 기억으로 채우면 한 단계 위'] },
      { t: 'story', k: 'fix', img: 'gen:bts-11-black-scarf', title: 'Good choice!', lines: [['Sally', 'Hmm… They are all nice, but I want the black scarf.'], ['Clerk', 'Good choice! Are you sure?'], ['Sally', "Yes! I'm going to buy it. Here is the money."], ['Clerk', 'Thank you!']], src: '12·13쪽', nt: '목도리를 사요', n: ['«Take the money» → Here is the money(돈을 건넬 때 쓰는 말)'] },
      { t: 'qa', k: 'keep', img: '16245', q: 'Sally paid 80 dollars. How much money does she have now?', a: 'She has ___ dollars.', chips: ['twenty'], src: '14쪽', nt: '남은 돈', n: ['100 − 80 = 20 — 손가락으로 계산해도 됩니다'] },
      { t: 'yourturn', k: 'keep', img: '12593', title: 'What should Sally buy?', lines: ['Sally has 20 dollars.', 'She can buy ___.', 'She wants to buy ___.'], chips: ['ice cream', 'a T-shirt', 'a hat'], src: '15쪽', nt: '내 생각 말하기' },
      { t: 'ox', k: 'new', img: '12304', s: 'Sally wants the red scarf.', nt: '⭕❌', n: ['정답 ❌ → «No! She wants the black scarf.»'] },
      { t: 'guess', k: 'new', img: '16833', open: [2, 5], q: 'What are they?', chips: ["They're dresses.", 'I want to buy the ___ dress.'], nt: 'Guess who 타일', n: ['타일을 열며 옷을 맞히고, 다 열리면 «어느 드레스를 사고 싶니?»'] },
      { t: 'yourturn', k: 'fix', img: 'gen:bts-11-online', title: "Let's go online shopping!", lines: ['Shop till you drop!', 'Imagine you have $500.', 'What do you want to buy?'], src: '16쪽', nt: '인터넷 쇼핑', n: ['«$500» 를 가진 것처럼 — 오늘 끝까지 장바구니를 채웁니다'] },
      { t: 'story', k: 'fix', img: '12213', title: 'Online store', lines: [['Clerk', 'Welcome to our online store!'], ['Clerk', 'We have T-shirts for $20.'], ['Clerk', 'We have nice sweaters, too!']], src: '17·18쪽', nt: '인터넷 점원', n: ['«sweaters too?» → too!'] },
      { t: 'table', k: 'keep', small: 'Online store', title: 'Sweaters', head: ['sweater', 'price'], rows: [['red', '$50'], ['blue', '$36'], ['yellow', '$28'], ['green', '$44']], src: '19쪽', nt: '스웨터 가격', n: ['다 읽으면 «Which sweater do you want? — I want the ___ sweater.»', '원본은 사진 번호로만 구분 → 색 이름으로 말하게 바꿨습니다'] },
      { t: 'table', k: 'keep', small: 'Online store', title: 'Jackets and pants', head: ['item', 'price'], rows: [['jacket A', '$70'], ['jacket B', '$80'], ['pants A', '$98'], ['pants B', '$100']], src: '20·21쪽', nt: '재킷·바지 가격', n: ['고를 때마다 «I want to add ___ to my cart.»'] },
      { t: 'table', k: 'keep', small: 'Online store', title: 'Shoes', head: ['item', 'price'], rows: [['shoes', '$120'], ['boots', '$89'], ['sneakers', '$110'], ['high heels', '$107']], src: '22·23쪽', nt: '신발 가격' },
      { t: 'fill', k: 'fix', title: 'Add to cart 🛒', lines: ['I want to add a ___ to my cart.', 'It is ___ dollars.', 'I want to add ___ to my cart, too.'], chips: ['sweater', 'cart'], src: '24쪽', nt: '장바구니에 넣기', n: ['«in my cart» → to my cart'] },
      { t: 'yourturn', k: 'fix', img: 'c7423', title: 'Check your cart!', lines: ['My cart: ___, ___ and ___.', 'The total is ___ dollars.', 'Is it under $500?'], src: '25~27쪽 Checkout', nt: '계산하기', n: ['학생이 고른 물건 가격을 함께 더하기 — $500 을 넘으면 하나 빼기'] },
      { t: 'order', k: 'new', img: '17135', words: ['She', 'wants', 'to', 'buy', 'a', 'jacket'], nt: '순서 맞추기', n: ['wants to 의 자리를 확인'] },
      ...close([['I can buy things in a store.', 'I want to buy a scarf. Here is the money.'], ['I can say how much money I have.', 'I have 20 dollars.'], ['I can shop online.', 'I want to add a sweater to my cart.']], { img: 'gen:bts-11-c004', q: 'What stores are in your town?', ko: '우리 동네에는 어떤 가게가 있을까?' }),
    ] },
  // ───────────────────────── 004
  { code: '004', tab: '가게들', unit: U2, title: 'Stores and Items', orig: 35,
    intro: '가게 이름 10개(toy store·flower shop·pharmacy…)와 «It sells ___ / I can buy ___ at the ___» 를 배웁니다. 이야기: 비키와 토미가 가게를 돌아다닙니다.',
    fixed: ['목표에 «sell» 이 두 번 · «music instruments» → musical instruments', 'pet shop 뜻 «애완동물 가게» → «반려동물 가게» · music store «음반 가게» → «악기 가게»(사진이 악기)', 'gadget store 뜻 «공구점»(틀림) → «전자기기 가게»', '문장 틀 머리글 «want + infinitive» 아래에 «can buy the» 예문 → can 틀로 정리', '«I need to buy medicines» → medicine · «smart phones and etc.» → smartphones', 'available 뜻 «유효한» → «살 수 있는, 파는»', '«they are available at the bakery»(bread) → it\'s available', '복습 쪽 오타 «I can but that T-shirt» → buy · BTS 10 «feel» 문법 삭제'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c004', q: 'What stores are in your town?', story: 'Toys, flowers, bread, puppies… Where can you buy them?', nt: '표지 + Big Question', n: ['가게가 늘어선 거리 사진 — 창문마다 무엇을 파는지 먼저 짐작하게'] },
      ...open([['I can name 10 stores.', '가게 이름 10개를 말해요.'], ['I can say what a store sells.', '가게가 무엇을 파는지 말해요.'], ['I can say where I can buy things.', '어디서 살 수 있는지 말해요.']]),
      USONG_2,
      { t: 'story', k: 'keep', img: '14301', title: 'Mini role-play', lines: [['Clerk', 'Hello! How can I help you?'], ['Jay', 'I want to buy a jacket.'], ['Clerk', "Here you are. It's 80 dollars."]], src: 'Warm Up 5쪽', nt: '몸풀기 역할 놀이', n: ['지난 과 복습 — 학생이 손님, 강사가 점원'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Stores ① 🔒', words: [['clothing store', '옷가게', '12856'], ['toy store', '장난감 가게', 'gen:bts-11-toystore'], ['flower shop', '꽃집', '16335'], ['supermarket', '슈퍼마켓', '15258'], ['pharmacy', '약국', '14701']], src: 'Vocabulary 6쪽', nt: '가게 ① — 가리고 먼저' },
      { t: 'vocab', k: 'fix', title: 'Stores ①', words: [['clothing store', '옷가게', '12856'], ['toy store', '장난감 가게', 'gen:bts-11-toystore'], ['flower shop', '꽃집', '16335'], ['supermarket', '슈퍼마켓', '15258'], ['pharmacy', '약국(= drugstore)', '14701']], src: 'Vocabulary 6쪽', nt: '가게 ① — 공개' },
      { t: 'vocab', k: 'fix', hide: true, title: 'Stores ② 🔒', words: [['bakery', '빵집', '12794'], ['pet shop', '반려동물 가게', 'gen:bts-11-petshop'], ['music store', '악기 가게', 'gen:bts-11-musicstore'], ['gadget store', '전자기기 가게', 'gen:bts-11-gadget'], ['bookstore', '서점', '18018']], src: 'Vocabulary 7쪽', nt: '가게 ② — 가리고 먼저' },
      { t: 'vocab', k: 'fix', title: 'Stores ②', words: [['bakery', '빵집', '12794'], ['pet shop', '반려동물 가게', 'gen:bts-11-petshop'], ['music store', '악기 가게', 'gen:bts-11-musicstore'], ['gadget store', '전자기기 가게', 'gen:bts-11-gadget'], ['bookstore', '서점', '18018']], src: 'Vocabulary 7쪽', nt: '가게 ② — 공개', n: ['원본 뜻풀이 셋을 고쳤습니다: 애완동물→반려동물 · 음반 가게→악기 가게 · 공구점→전자기기 가게'] },
      { t: 'rule', k: 'new', title: 'sells or can buy?', left: { h: 'The store', ex: ['The bakery **sells** bread.', 'The bookstore **sells** books.'] }, right: { h: 'You', ex: ['You **can buy** bread at the bakery.', 'I **can buy** books at the bookstore.'] }, q: 'Who sells? Who buys?', nt: '규칙 찾기', n: ['가게는 sells(팔다), 사람은 can buy(살 수 있다) — 같은 장면을 두 방향으로'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'I can buy flowers at the flower shop.', head: ['who', 'can buy', 'what', 'where'], rows: [['I', 'can buy', 'flowers', 'at the flower shop.'], ['She', 'can buy', 'toys', 'at the toy store.'], ['They', 'can buy', 'medicine', 'at the pharmacy.']], tip: 'can 뒤는 언제나 buy 그대로(can buys ❌)', src: 'Sentence Pattern 8쪽', nt: '문장 틀', n: ['원본은 «want + infinitive» 머리글 아래 can 예문이 섞여 있었음 → can 틀로 정리'] },
      { t: 'qa', k: 'fix', img: '14620', q: 'What does the clerk do?', a: 'The clerk (sell / sells) clothes in the ___ ___.', chips: ['clothing store'], src: '9쪽', nt: '점원은 판다' },
      { t: 'qa', k: 'keep', img: '17135', q: 'What does she do?', a: 'She ___ clothes in the clothing store.', chips: ['buys'], src: '10쪽', nt: '손님은 산다' },
      { t: 'qa', k: 'fix', img: '15258', q: 'What does the supermarket sell?', a: 'It sells fruit, vegetables and other kinds of ___.', chips: ['food'], src: '11쪽', nt: '슈퍼마켓', n: ['«fruits» → fruit(여러 과일을 통틀어 말할 때)'] },
      { t: 'yourturn', k: 'keep', img: '12376', title: 'At the supermarket', lines: ['What can you buy at the supermarket?', 'I can buy ___ and ___ at the supermarket.'], src: '12쪽', nt: '내 말로' },
      { t: 'qa', k: 'keep', img: '12794', q: 'What does the bakery sell?', a: 'It sells ___ and ___.', chips: ['bread', 'cakes'], src: '13쪽', nt: '빵집' },
      { t: 'qa', k: 'keep', img: '18018', q: 'What store is it?', a: "It's a ___.", chips: ['bookstore'], src: '14쪽', nt: '서점' },
      { t: 'qa', k: 'keep', img: 'gen:bts-11-toystore', q: 'What does the toy store sell?', a: 'It sells ___.', chips: ['toys'], src: '15쪽', nt: '장난감 가게' },
      { t: 'qa', k: 'keep', img: '16335', q: 'Where is she?', a: 'She is in the ___ ___.', chips: ['flower shop'], src: '16쪽', nt: '꽃집' },
      { t: 'qa', k: 'fix', img: 'gen:bts-11-pharmacy', q: 'I am sick. I need to buy medicine. Where am I?', a: "It's a ___ or a ___.", chips: ['pharmacy', 'drugstore'], src: '17쪽', nt: '약국', n: ['«medicines» → medicine'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-11-musicstore', q: 'What can you buy at the music store?', a: 'I can buy musical ___.', chips: ['instruments'], src: '18쪽', nt: '악기 가게', n: ['«music instruments» → musical instruments'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-11-petshop', q: 'What can you buy at the pet shop?', a: 'I can buy a ___.', chips: ['puppy', 'rabbit', 'goldfish'], src: '19쪽', nt: '반려동물 가게' },
      { t: 'qa', k: 'fix', img: 'gen:bts-11-gadget', q: 'What does the gadget store sell?', a: 'It sells ___, ___ and smartphones.', chips: ['laptops', 'tablets'], src: '20쪽', nt: '전자기기 가게', n: ['«smart phones and etc.» → smartphones(and 와 etc. 를 함께 쓰지 않음)'] },
      { t: 'vocab', k: 'fix', title: 'Story words', words: [['available', '살 수 있는, 파는', 'c7276'], ['kidding', '농담하는', '15842'], ['forgot', '잊어버렸다', '18992']], src: 'New Words 21쪽', nt: '이야기 낱말', n: ['available 뜻 «유효한» → 이야기 속 뜻 «(가게에서) 살 수 있는»'] },
      { t: 'story', k: 'keep', img: 'gen:bts-11-vicky-tommy', title: 'Vicky and Tommy ①', lines: [['Vicky', 'Tommy, where are you going?'], ['Tommy', "I'm going to the supermarket."], ['Vicky', 'What will you buy there?'], ['Tommy', 'I will buy rice, eggs and meat.']], src: 'Role Play 22쪽', nt: '이야기 ①' },
      { t: 'story', k: 'fix', img: '12794', title: 'Vicky and Tommy ②', lines: [['Vicky', 'Can I buy bread there?'], ['Tommy', "I'm not sure, but it's available at the bakery."], ['Vicky', 'Alright. I need to go to the pet shop, too.']], src: '23쪽', nt: '이야기 ②', n: ['bread 를 받는 말 «they are» → it\'s'] },
      { t: 'story', k: 'keep', img: 'gen:bts-11-snake', title: 'Vicky and Tommy ③', lines: [['Tommy', 'Can you buy a snake there?'], ['Vicky', "I think so, but that's too scary!"], ['Tommy', "I'm just kidding!"]], src: '24쪽', nt: '이야기 ③', n: ['뱀 앞에서 펄쩍 뛰는 사진 — «too scary!» 는 몸짓과 함께'] },
      { t: 'story', k: 'keep', img: '19886', title: 'Vicky and Tommy ④', lines: [['Tommy', 'Oh, I almost forgot…'], ['Vicky', 'What is it?'], ['Tommy', 'I have to go to the gadget store!'], ['Vicky', 'Okay. See you around!']], src: '25쪽', nt: '이야기 ④' },
      { t: 'fill', k: 'keep', title: 'Questions', lines: ['Where is Tommy going? — He is going to the ___.', 'What will Tommy buy? — He will buy rice, ___ and ___.', 'Where can Vicky buy bread? — She can buy it at the ___.'], chips: ['supermarket', 'eggs', 'meat', 'bakery'], src: '26쪽', nt: '이야기 질문' },
      { t: 'guess', k: 'new', img: 'c7380', open: [0, 5], q: 'What is it? Which store sells it?', chips: ["It's a parrot!", 'The pet shop sells it.'], nt: 'Guess who 타일', n: ['알록달록한 앵무새 — 깃털 색이 보이면 금방 맞힙니다'] },
      { t: 'match', k: 'new', left: ['12794', '14701', '16335', '18018'], right: ['flower shop', 'bakery', 'bookstore', 'pharmacy'], nt: '짝 맞추기', n: ['맞힐 때마다 «It sells ___.» 한 문장'] },
      { t: 'ox', k: 'new', img: '14701', s: 'You can buy bread at the pharmacy.', nt: '⭕❌', n: ['정답 ❌ → «No! You can buy medicine at the pharmacy.»'] },
      { t: 'yourturn', k: 'fix', img: '13300', title: 'Name that store in 5 seconds!', lines: ['Teacher shows a picture.', "You: It's a ___!", 'It sells ___.'], src: 'Game 27쪽', nt: '5초 게임', n: ['원본 게임 — 강사가 가게 사진을 빠르게 보여 주고 5초 안에 두 문장'] },
      ...close([['I can name 10 stores.', 'bakery, pharmacy, pet shop…'], ['I can say what a store sells.', 'The bakery sells bread.'], ['I can say where I can buy things.', 'I can buy flowers at the flower shop.']], { img: 'gen:bts-11-c005', q: 'Where can you buy a teddy bear?', ko: '곰 인형은 어디서 살 수 있을까?' }),
    ] },
  // ───────────────────────── 005
  { code: '005', tab: '어디서 사요?', unit: U2, title: 'What Can I Buy?', orig: 23,
    intro: '가게마다 살 수 있는 물건을 말합니다(I can buy ___ at the ___). 짝짓기·기억 게임으로 가게와 물건을 연결합니다.',
    fixed: ['«smart phones» → smartphones', '복습 쪽 오타 «I can but» → I can buy', '«It ___ food» 빈칸이 앞 문장 정답을 알려 줌 → 순서 조정', 'BTS 10 «feel» 문법 복습 삭제'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c005', q: 'Where can you buy a teddy bear?', story: 'So many stores! What can you buy there?', nt: '표지 + Big Question', n: ['장난감 가게 창문에 코를 붙인 아이들 — «What do they want?»'] },
      ...open([['I can say what I can buy.', '살 수 있는 것을 말해요.'], ['I can say where I can buy it.', '어디서 살 수 있는지 말해요.']]),
      USONG_2,
      { t: 'story', k: 'new', img: '16436', title: 'Tommy at the gadget store', lines: [['Tommy', "I'm at the gadget store now!"], ['Clerk', 'Hello! How can I help you?'], ['Tommy', 'I want to buy a new laptop.'], ['Clerk', 'We have many laptops. Look!']], nt: '이야기 이어 가기', n: ['004 이야기 끝(토미가 gadget store 로 감)을 이어 받습니다', '학생이 Clerk 역할 — 이어서 «It\'s ___ dollars.» 로 가격까지 말하면 보너스'] },
      { t: 'vocab', k: 'new', hide: true, title: 'Stores 🔒', words: [['supermarket', '슈퍼마켓', 'c7303'], ['flower shop', '꽃집', '16336'], ['bakery', '빵집', '18047'], ['toy store', '장난감 가게', '16659'], ['pharmacy', '약국', '14113'], ['pet shop', '반려동물 가게', '16313']], nt: '가게 복습', n: ['지난 과와 다른 사진 — 가게 안의 물건을 보고 가게 이름을 떠올리기'] },
      { t: 'qa', k: 'fix', img: '15265', q: 'What store is it? What does it sell?', a: "It's a ___. It ___ food.", chips: ['supermarket', 'sells'], src: '5쪽', nt: '슈퍼마켓' },
      { t: 'fill', k: 'keep', img: '12376', title: 'At the supermarket', lines: ['I can buy ___, ___ and ___ at the supermarket.', 'I can buy ___, ___ and ___, too!'], chips: ['rice', 'meat', 'tomatoes', 'milk', 'eggs', 'fish'], src: '6쪽', nt: '여섯 가지', n: ['원본 «6가지 말하기» — 다 말하면 박수'] },
      { t: 'qa', k: 'keep', img: '12459', q: 'Where can you buy them?', a: 'I can buy ___ at the ___ ___.', chips: ['flowers', 'flower shop'], src: '7쪽', nt: '꽃' },
      { t: 'qa', k: 'keep', img: '18047', q: 'What can you buy at the bakery?', a: 'I ___ buy cakes, cookies and doughnuts at the ___.', chips: ['can', 'bakery'], src: '8쪽', nt: '빵집' },
      { t: 'qa', k: 'keep', img: '16659', q: 'What can you buy at the toy store?', a: 'I can buy teddy bears, blocks and ___ ___ at the ___ ___.', src: '9쪽', nt: '장난감' },
      { t: 'qa', k: 'fix', img: '12356', q: 'What can you buy at the gadget store?', a: 'I can ___ a tablet, a ___ and smartphones at the ___ store.', src: '10쪽', nt: '전자기기', n: ['«smart phones» → smartphones'] },
      { t: 'qa', k: 'keep', img: '16313', q: 'What can you buy at the pet shop?', a: 'I can buy ___ at the ___ ___.', chips: ['puppies', 'pet shop'], src: '11쪽', nt: '반려동물' },
      { t: 'qa', k: 'keep', img: '13005', q: 'Where can you buy a guitar?', a: 'I can buy a guitar at the ___ ___.', chips: ['music store'], src: '12쪽', nt: '악기' },
      { t: 'qa', k: 'keep', img: '12404', q: 'Where can you buy medicine?', a: 'I can buy medicine at the ___.', chips: ['pharmacy'], src: '13쪽', nt: '약' },
      { t: 'match', k: 'fix', title: 'Where can you buy them?', left: ['16273', '16436', '12557', '16592'], right: ['toy store', 'supermarket', 'music store', 'gadget store'], src: '14~16쪽', nt: '짝 맞추기', n: ['원본 6개(토마토·노트북·블록·도넛·바이올린·알약) → 4개(도넛·알약은 앞에서 연습)', '맞힐 때마다 «I can buy ___ at the ___.»'] },
      { t: 'memory', k: 'new', items: ['16273', '12557', '16592', '12404', '16052', '12459'], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ① 보기' },
      { t: 'memory', k: 'new', hidden: true, items: ['16273', '12557', '16592', '12404', '16052', '12459'], q: 'What can you buy? Where?', a: 'I can buy ___ at the ___.', nt: '기억 게임 ② 말하기', n: ['물건 이름 + 가게 이름을 한 문장으로 — 여섯 개 다 말하면 만점'] },
      { t: 'ox', k: 'new', img: '16592', s: 'You can buy a violin at the bakery.', nt: '⭕❌', n: ['정답 ❌ → «No! You can buy a violin at the music store.»'] },
      { t: 'guess', k: 'new', img: '18024', open: [1, 4], q: 'Where is he? What can he buy?', chips: ['He is at the supermarket.', 'He can buy ___.'], nt: 'Guess who 타일', n: ['카트를 밀며 달리는 아이 — 카트 안 물건을 하나씩 맞히기'] },
      { t: 'order', k: 'new', img: '12459', words: ['I', 'can', 'buy', 'flowers', 'at', 'the', 'flower', 'shop'], nt: '순서 맞추기' },
      { t: 'yourturn', k: 'new', img: '13092', title: 'My favorite store', lines: ['My favorite store is the ___.', 'It sells ___.', 'I can buy ___ there.'], nt: '내 말로', n: ['세 문장을 이어 말하면 성공 — 좋아하는 이유를 한 문장 더 말하면 보너스'] },
      ...close([['I can say what I can buy.', 'I can buy toy cars.'], ['I can say where I can buy it.', 'I can buy a guitar at the music store.']], { img: 'gen:bts-11-c006', q: 'What is on the shopping list?', ko: '쇼핑 목록에는 무엇이 있을까?' }),
    ] },
  // ───────────────────────── 006
  { code: '006', tab: '쇼핑 목록', unit: U2, title: 'The Shopping List', orig: 21,
    intro: '존과 줄리가 엄마의 쇼핑 목록을 들고 여러 가게를 돕니다. «need to buy / need to go to» 를 배웁니다.',
    fixed: ['쇼핑 목록 번호 6이 빠짐(1~5, 7, 8) → 1~7 로 다시 매김', 'recorder 를 사는 곳이 gadget store 로 읽히는 쪽 → music store', '«And you need to go to the ___, ___, ___, and ___» 쉼표 정리'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c006', q: 'What is on the shopping list?', story: 'John and Julie have a long list. Can they buy everything?', nt: '표지 + Big Question', n: ['공원에서 기다란 목록을 펼치고 놀란 남매 — «So long!»'] },
      ...open([['I can say what I need to buy.', '사야 하는 것을 말해요.'], ['I can say where I need to go.', '가야 하는 가게를 말해요.']]),
      USONG_2,
      { t: 'story', k: 'keep', img: '19313', title: "Mom's list", lines: [['John', 'Our mom asked us to go shopping.'], ['John', 'Julie, do you have our shopping list?'], ['Julie', "Yes, I have it. Let's go shopping now!"]], src: '5·6쪽', nt: '존과 줄리', n: ['Julie 는 John 의 여동생 — 원본 인물 그대로'] },
      { t: 'table', k: 'fix', small: 'Shopping list', title: 'What do we need?', rows: [['1. rice', '2. beef'], ['3. flowers', '4. a recorder'], ['5. medicine', '6. a goldfish'], ['7. a teddy bear', '🛒']], tip: '물건마다 어느 가게에서 살지는 오늘 수업 끝에 말해요', src: '7쪽', nt: '쇼핑 목록', n: ['원본 번호 6이 빠져 있어 1~7 로 다시 매겼습니다'] },
      { t: 'fill', k: 'keep', img: 'gen:bts-11-list-cart', title: 'Today, we need to buy…', lines: ['Today, we need to buy ___, ___ and ___.', 'We need to buy ___ and ___, too.'], src: '8쪽', nt: '목록 말하기' },
      { t: 'rule', k: 'new', title: 'need to or needs to?', left: { h: 'I / We', ex: ['I **need to** buy rice.', 'We **need to** go to the pharmacy.'] }, right: { h: 'He / She', ex: ['Julie **needs to** buy flowers.', 'John **needs to** buy a recorder.'] }, q: 'When do we say "needs to"?', nt: '규칙 찾기', n: ['want to 와 같은 규칙(he·she 뒤에 -s) — 001 규칙을 떠올리게'] },
      { t: 'qa', k: 'keep', img: '21284', q: 'Julie, what do you need to buy?', a: 'I need to buy a ___ and a ___.', chips: ['goldfish', 'teddy bear'], src: '9쪽', nt: '줄리의 물건' },
      { t: 'qa', k: 'keep', img: 'c7207', q: 'John, where do I need to go?', a: 'You need to go to the ___ ___ and the ___ ___.', chips: ['pet shop', 'toy store'], src: '10쪽', nt: '줄리가 갈 곳' },
      { t: 'qa', k: 'fix', img: '16128', label: 'rice · beef · flowers · medicine · a recorder', q: 'Where does John need to go?', a: 'He needs to go to the ___, the ___ ___, the ___ and the ___ ___.', src: '11쪽', nt: '존이 갈 곳', n: ['리코더는 music store — 원본에서 gadget store 로 읽히던 쪽을 고쳤습니다'] },
      { t: 'match', k: 'new', left: ['12003', '16106', '12404', '16107'], right: ['pharmacy', 'toy store', 'supermarket', 'flower shop'], nt: '짝 맞추기', n: ['목록의 물건 ↔ 가게 — 맞힐 때마다 «We need to go to the ___.»'] },
      { t: 'ox', k: 'new', img: '16128', s: 'John can buy beef at the pet shop.', nt: '⭕❌', n: ['정답 ❌ → «No! He can buy beef at the supermarket.»'] },
      { t: 'guess', k: 'new', img: '20253', open: [0, 3], q: 'What is it? Where can you buy it?', chips: ["It's a goldfish.", 'I can buy it at the pet shop.'], nt: 'Guess who 타일', n: ['작은 어항 속 금붕어 — 타일 사이로 꼬리가 보이면 금방 맞힙니다'] },
      { t: 'memory', k: 'new', items: ['12003', '16128', '16106', '12404', '21284', '16107'], q: 'Look at the list! 5 seconds! 👀', nt: '기억 게임 ① 보기' },
      { t: 'memory', k: 'new', hidden: true, items: ['12003', '16128', '16106', '12404', '21284', '16107'], q: "What's on the list?", a: 'We need to buy ___, …', nt: '기억 게임 ② 말하기', n: ['목록을 안 보고 몇 개 기억하나 — need to 를 계속 쓰게 됩니다'] },
      { t: 'fill', k: 'keep', title: 'I need to go to the…', lines: ['I need to buy bread. — I need to go to the ___.', 'I need to buy a book. — I need to go to the ___.', 'I need to buy a smartphone. — I need to go to the ___ ___.'], chips: ['bakery', 'bookstore', 'gadget store'], src: '12·13쪽', nt: '어디로 가야 할까' },
      { t: 'yourturn', k: 'keep', img: 'c7303', title: 'Make your shopping list!', lines: ['My shopping list: 1. ___ 2. ___ 3. ___', 'I need to buy ___.', 'I need to go to the ___.'], src: '14쪽', nt: '내 쇼핑 목록', n: ['화면에 직접 써 보게 합니다 — 세 개면 충분'] },
      { t: 'order', k: 'new', img: '12404', words: ['We', 'need', 'to', 'go', 'to', 'the', 'pharmacy'], nt: '순서 맞추기' },
      ...close([['I can say what I need to buy.', 'I need to buy rice and beef.'], ['I can say where I need to go.', 'I need to go to the supermarket.']], { img: 'gen:bts-11-c007', q: 'What can you buy at a stationery store?', ko: '문구점에서는 무엇을 살 수 있을까?' }),
    ] },
  // ───────────────────────── 007
  { code: '007', tab: '문구점', unit: U3, title: 'Stationery Store', orig: 29,
    intro: '문구점과 학용품, cheap·expensive, need 와 want 의 차이를 배웁니다. 이야기: 테사와 제임스가 개학 준비를 합니다.',
    fixed: ['머리글 오타 «Stationary store» → Stationery store', '예문 «want juice/a cake/a car..» 마침표 두 개 → 하나', 'need/want 예문 «The king needs a crown / The queen needs a big house / The student needs a chocolate» → 생활 예문으로', '«pencils, papers, erasers» → paper', '«It\'s okay. Tessa.» → It\'s okay, Tessa. · «Why are you late?.» → Why are you late?', '«did you buy» 첫 글자 → Did · «I will buy later» → I will buy them later', '«I think you don\'t need that» → I don\'t think you need one'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c007', q: 'What can you buy at a stationery store?', story: 'Tomorrow is the first day of school!', nt: '표지 + Big Question', n: ['연필을 한 아름 안은 아이 — «What does he need?»'] },
      ...open([['I can talk about school supplies.', '학용품에 대해 말해요.'], ['I can say "cheap" or "expensive".', '싸다·비싸다를 말해요.'], ['I can say what I need and what I want.', '필요한 것과 갖고 싶은 것을 말해요.']]),
      USONG_3,
      { t: 'yourturn', k: 'keep', img: '16098', title: 'Give me 5!', lines: ['Name 5 things for school!', '1. ___ 2. ___ 3. ___ 4. ___ 5. ___'], src: 'Warm Up 5쪽', nt: '몸풀기', n: ['손가락 다섯 개를 펴며 하나씩 — 30초 안에'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'New words 🔒', words: [['stationery store', '문구점', 'gen:bts-11-stationery'], ['school supplies', '학용품', '16723'], ['cheap', '싼', '21124'], ['expensive', '비싼', '12455'], ['need', '필요하다', '12123'], ['want', '갖고 싶다', '15820']], src: 'Vocabulary 6쪽', nt: '낱말 — 가리고 먼저' },
      { t: 'vocab', k: 'fix', title: 'New words', words: [['stationery store', '문구점', 'gen:bts-11-stationery'], ['school supplies', '학용품', '16723'], ['cheap', '싼', '21124'], ['expensive', '비싼', '12455'], ['need', '필요하다', '12123'], ['want', '갖고 싶다', '15820']], src: 'Vocabulary 6쪽', nt: '낱말 — 공개', n: ['머리글 «Stationary» → Stationery(stationary 는 «멈춰 있는»)'] },
      { t: 'rule', k: 'fix', title: 'need or want?', left: { h: 'need', ex: ['I **need** water.', 'I **need** food.', 'I **need** a house.'] }, right: { h: 'want', ex: ['I **want** juice.', 'I **want** a cake.', 'I **want** a car.'] }, q: 'Which ones do we need to live?', src: 'Grammar 7쪽', nt: '규칙 찾기', n: ['«살려면 꼭 있어야 하는 것» = need, «있으면 좋은 것» = want — 학생이 먼저 가르게', '«a car..» 마침표 두 개 정리'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'The student needs a pencil.', head: ['need', 'want'], rows: [['The student **needs** a pencil.', 'The student **wants** a chocolate bar.'], ['The baby **needs** milk.', 'The baby **wants** a toy.']], tip: 'he·she 뒤에는 needs · wants', src: '8쪽', nt: '문장 틀', n: ['원본 «The king needs a crown / The queen needs a big house» 는 need/want 구분이 헷갈려 생활 예문으로 바꿨습니다(결정 필요)'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-11-stationery', q: 'What does the stationery store sell?', a: 'It sells pencils, ___, erasers and other school ___.', src: '9쪽', nt: '문구점', n: ['«papers» → paper'] },
      { t: 'qa', k: 'keep', img: '13167', q: 'How much is the pen?', a: "It's one dollar. It's ___!", chips: ['cheap'], src: '10쪽', nt: '싼 펜' },
      { t: 'rule', k: 'new', title: 'cheap or expensive?', left: { h: 'cheap 💰', ex: ['The pen is **cheap**.', 'It is one dollar.'] }, right: { h: 'expensive 💎', ex: ['The fountain pen is **expensive**.', 'It is fifty dollars.'] }, q: 'Is $1 cheap or expensive? What about $50?', nt: '규칙 찾기' },
      { t: 'qa', k: 'keep', img: 'gen:bts-11-fountain-pen', q: 'Wow! How much is the fountain pen?', a: "It's fifty dollars. It's ___!", chips: ['expensive'], src: '11쪽', nt: '비싼 만년필', n: ['유리장 속 만년필에 깜짝 놀란 표정 — «Fifty dollars?!» 를 과장해서'] },
      { t: 'fill', k: 'keep', img: '15375', title: 'Cheap or expensive?', lines: ['The eraser is $2. It is ___.', 'The backpack is $200. It is ___.', 'The ruler is $5. It is ___.', 'The notebook is $40. It is ___.'], chips: ['cheap', 'expensive'], src: '12·13쪽', nt: '가격 판단' },
      { t: 'qa', k: 'new', img: '21124', q: 'Which one is cheap?', a: 'The ___ is cheap. The dress is ___.', chips: ['T-shirt', 'expensive'], nt: '둘 중 무엇이 싸요?' },
      { t: 'ox', k: 'new', img: '12565', s: 'A car is cheap.', nt: '⭕❌', n: ['정답 ❌ → «No! A car is expensive.»'] },
      { t: 'guess', k: 'new', img: '12455', open: [2, 4], q: 'What is it? Is it cheap or expensive?', chips: ["It's a ring.", "It's expensive!"], nt: 'Guess who 타일', n: ['반짝이는 다이아몬드 반지 — 다 열리면 «How much is it?» 로 가격 맞히기 놀이'] },
      { t: 'vocab', k: 'new', title: 'Story words', words: [['late', '늦은', 'gen:bts-11-tessa-late'], ['first day of school', '개학 날', '18996'], ['bring', '가져오다', '12071']], nt: '이야기 낱말' },
      { t: 'story', k: 'fix', img: 'gen:bts-11-tessa-late', title: 'Tessa and James ①', lines: [['Tessa', "Hi, James! Sorry I'm late."], ['James', "It's okay, Tessa. Why are you late?"], ['Tessa', 'I went to the stationery store.']], src: 'Role Play 14쪽', nt: '이야기 ①', n: ['쉼표·마침표 두 곳 정리(«It\'s okay. Tessa.» · «late?.»)'] },
      { t: 'story', k: 'fix', img: '18996', title: 'Tessa and James ②', lines: [['James', 'Oh, tomorrow is the first day of school.'], ['Tessa', 'Yes! Did you buy school supplies already?'], ['James', "No, I didn't. I will buy them later."]], src: '15쪽', nt: '이야기 ②', n: ['«did» → Did · «buy later» → buy them later'] },
      { t: 'story', k: 'fix', img: '16092', title: 'Tessa and James ③', lines: [['Tessa', 'Can you buy a ruler for me? I forgot to buy one.'], ['James', "Sure, but I don't think you need one."]], src: '16쪽', nt: '이야기 ③', n: ['«I think you don\'t need that» → I don\'t think you need one(자연스러운 영어)'] },
      { t: 'story', k: 'keep', img: '16091', title: 'Tessa and James ④', lines: [['Tessa', 'What should I bring tomorrow?'], ['James', 'Just bring your pen and notebook.']], src: '16쪽', nt: '이야기 ④', n: ['펜과 공책을 카메라에 보여 주며 따라 말하기'] },
      { t: 'fill', k: 'keep', title: 'Questions', lines: ['Why is Tessa late? — She went to the ___ ___.', 'What is tomorrow? — It is the ___ day of school.', 'What does Tessa want James to buy? — A ___.', 'What should Tessa bring? — Her ___ and ___.'], chips: ['stationery store', 'first', 'ruler', 'pen', 'notebook'], src: '17쪽', nt: '이야기 질문' },
      { t: 'table', k: 'keep', small: 'Game', title: 'Name that PRICE!', head: ['item', 'cheap or expensive?'], rows: [['a notebook', '___'], ['a house', '___'], ['a laptop', '___'], ['scissors', '___']], src: 'Game 18·19쪽', nt: '가격 게임', n: ['강사가 물건을 말하면 3초 안에 «It\'s cheap!» / «It\'s expensive!»'] },
      { t: 'yourturn', k: 'new', img: '16013', title: 'Need or want?', lines: ['For school, I need ___.', 'I want ___, too!'], chips: ['a pencil case', 'a ruler', 'new sneakers'], nt: '내 말로', n: ['need 와 want 를 한 문장씩 — 구분이 되면 성공'] },
      { t: 'order', k: 'new', img: '12455', words: ['The', 'ring', 'is', 'very', 'expensive'], nt: '순서 맞추기' },
      ...close([['I can talk about school supplies.', 'It sells pencils, paper and erasers.'], ['I can say "cheap" or "expensive".', 'The pen is cheap. The ring is expensive.'], ['I can say what I need and what I want.', 'I need a pencil. I want a cake.']], { img: 'gen:bts-11-c008', q: 'How much is it? Wow!', ko: '얼마일까? 우와!' }),
    ] },
  // ───────────────────────── 008
  { code: '008', tab: '살 수 있을까?', unit: U3, title: 'Can I Buy It?', orig: 24,
    intro: '프레드와 레아가 여러 가게의 가격표를 보고 «I can buy / I can\'t buy» 를 판단합니다. believe·amazing·worth 를 배웁니다.',
    fixed: ['worth 뜻 «가치» → «~의 값어치가 있는»', '«Wow! this book» · «Amazing! this cake» → This(문장 첫 글자)', '«What does Fred need?»(기타) → want(악기는 필요가 아니라 갖고 싶은 것)', 'Lea 의 «컴퓨터 $7,000·휴대폰 $5,500» → 노트북 $2,000·휴대폰 $800(결정 필요)'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c008', q: 'How much is it? Wow!', story: 'Fred and Lea look at the price tags. Can they buy them?', nt: '표지 + Big Question', n: ['가격표를 보고 입을 떡 벌린 친구들 — «Is it cheap or expensive?»'] },
      ...open([["I can say 'I can buy it' or 'I can't buy it'.", '살 수 있는지 없는지 말해요.'], ['I can say how I feel about a price.', '가격을 보고 느낌을 말해요(Wow! Amazing!).']]),
      USONG_3,
      { t: 'vocab', k: 'fix', hide: true, title: 'New words 🔒', words: [['believe', '믿다', '18403'], ['amazing', '놀라운', '15829'], ['worth', '~의 값어치가 있는', '19209']], src: 'Vocabulary 5쪽', nt: '낱말 — 가리고 먼저' },
      { t: 'vocab', k: 'fix', title: 'New words', words: [['believe', '믿다', '18403'], ['amazing', '놀라운', '15829'], ['worth', '~의 값어치가 있는', '19209']], src: 'Vocabulary 5쪽', nt: '낱말 — 공개', n: ['worth 뜻 «가치» → «~의 값어치가 있는»(The crayons are worth $100.)'] },
      { t: 'story', k: 'keep', img: 'gen:bts-11-fred-lea', title: 'Fred and Lea', lines: [['Fred', 'Wait! Are we at the stationery store?'], ['Lea', "Nope! We're not. Let's check other stores, too!"], ['Fred', "Great idea. Let's go!"]], src: '6쪽', nt: '프레드와 레아' },
      { t: 'qa', k: 'fix', img: '18018', q: 'How much is this book?', a: 'Wow! This book is ___ dollars!', chips: ['fifty'], src: '7쪽', nt: '책', n: ['«this» → This'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-11-trumpet', q: 'How much is the trumpet?', a: "I can't believe this trumpet is just ___ ___!", chips: ['ten dollars'], src: '8쪽', nt: '트럼펫' },
      { t: 'qa', k: 'fix', img: '12062', q: 'How much is the cake?', a: 'Amazing! This cake is just ___ ___!', chips: ['five dollars'], src: '9쪽', nt: '케이크', n: ['«this» → This'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-11-crayon-box', q: 'How much are the crayons?', a: 'Oh no! The crayons are worth ___ ___ ___!', chips: ['one hundred dollars'], src: '10쪽', nt: '크레용', n: ['«Oh no!» 는 머리를 감싸며 — 크레용이 100달러라니!'] },
      { t: 'rule', k: 'new', title: "can or can't?", left: { h: 'can buy ✅', ex: ['Fred has $50.', 'The bread is $50.', 'He **can** buy the bread.'] }, right: { h: "can't buy ❌", ex: ['Fred has $50.', 'The cake is $60.', "He **can't** buy the cake."] }, q: 'When can he buy it?', nt: '규칙 찾기', n: ['가진 돈 ≥ 가격이면 can — 학생이 규칙을 먼저 말하게'] },
      { t: 'qa', k: 'keep', img: '12366', label: 'Fred $50 · bread $50 · cake $60', q: 'Can Fred buy them?', a: "He ___ buy the bread. He ___ buy the cake.", src: '11쪽', nt: '프레드 ①' },
      { t: 'qa', k: 'keep', img: '15320', label: 'Lea $100 · comics $50 · book $150', q: 'Can Lea buy them?', a: "She ___ buy the comics. She ___ buy the book.", src: '12쪽', nt: '레아 ①' },
      { t: 'qa', k: 'keep', img: '16107', label: 'Fred $200 · teddy $150 · blocks $260', q: 'Can Fred buy them?', a: "He ___ buy the teddy bear. He ___ buy the blocks.", src: '13쪽', nt: '프레드 ②' },
      { t: 'qa', k: 'keep', img: '16643', label: 'Lea $1,000 · puppy $2,000 · parrot $1,000', q: 'Can Lea buy them?', a: "She ___ buy the puppy. She ___ buy the parrot.", src: '14쪽', nt: '레아 ②' },
      { t: 'qa', k: 'fix', img: '13005', label: 'Fred $700 · guitar $500 · violin $800', q: 'Fred wants an instrument. What can he buy?', a: "He can buy the ___. He can't buy the ___.", src: '15쪽', nt: '프레드 ③', n: ['원본 «What does Fred need?» → wants(악기는 갖고 싶은 것)'] },
      { t: 'qa', k: 'fix', img: '16436', label: 'Lea $1,000 · laptop $2,000 · phone $800', q: 'Can Lea buy them?', a: "She ___ buy the laptop. She ___ buy the phone.", src: '16쪽', nt: '레아 ③', n: ['원본 «Lea $6,000 · 컴퓨터 $7,000 · 휴대폰 $5,500» → 현실적인 가격으로(결정 필요)'] },
      { t: 'ox', k: 'new', img: '15320', s: 'Lea has $100. She can buy a $150 book.', nt: '⭕❌', n: ['정답 ❌ → «No! She can\'t buy it. It\'s too expensive.»'] },
      { t: 'guess', k: 'new', img: '15820', open: [1, 4], q: 'What does he want? Can he buy it?', chips: ['He wants the cake.', 'He can buy it!', "He can't buy it."], nt: 'Guess who 타일', n: ['빵집 창문의 케이크를 가리키는 아이 — 다 열리면 강사가 «He has $10. The cake is $20.» 라고 말해 주고 판단하게'] },
      { t: 'yourturn', k: 'new', img: '16245', title: 'You have $100!', lines: ['I have $100.', 'I can buy ___.', "I can't buy ___. It's too expensive!"], nt: '내 말로', n: ['can / can\'t 한 문장씩 — 이유(too expensive)까지 말하면 보너스'] },
      { t: 'order', k: 'new', img: '16436', words: ['I', "can't", 'buy', 'the', 'laptop'], nt: '순서 맞추기' },
      ...close([["I can say 'I can buy it' or 'I can't buy it'.", "He can buy the bread. He can't buy the cake."], ['I can say how I feel about a price.', "Wow! I can't believe it!"]], { img: 'gen:bts-11-c009', q: 'Derek has $500. What will he buy?', ko: '데릭에게 500달러가 있어. 무엇을 살까?' }),
    ] },
  // ───────────────────────── 009
  { code: '009', tab: '데릭의 쇼핑', unit: U3, title: "Derek's Shopping Day", orig: 24,
    intro: '데릭이 $500 로 학용품·음식·선물을 삽니다. need 와 want, 가게 이름, 돈 계산을 모두 씁니다.',
    fixed: ['이름 «Dereck» → Derek(흔한 철자로 통일)', '«Tomorrow is the first day of school so I need» → 쉼표', '«What store it is?» → What store is it?', '«What do you need to buy”» 짝 없는 따옴표 → 물음표'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-c009', q: 'Derek has $500. What will he buy?', story: "It's Derek's big shopping day!", nt: '표지 + Big Question', n: ['돼지저금통을 깨고 신난 아이 — «How much money does he have?»'] },
      ...open([['I can plan my shopping.', '쇼핑 계획을 세워요.'], ['I can say what I need and what I want.', '필요한 것과 갖고 싶은 것을 말해요.'], ['I can say where I need to go.', '가야 할 가게를 말해요.']]),
      USONG_3,
      { t: 'story', k: 'fix', img: '18138', title: "Hi, I'm Derek!", lines: [['Derek', "Hi! I'm Derek!"], ['Derek', "I'm going to go shopping today!"], ['Derek', 'I have $500.']], src: '5쪽', nt: '데릭 등장', n: ['«Dereck» → Derek'] },
      { t: 'qa', k: 'fix', img: '12071', label: 'School starts tomorrow!', q: 'I need school supplies. Where do I need to go?', a: 'I need to go to the ___ ___.', src: '6쪽', nt: '학용품', n: ['«school so» 쉼표'] },
      { t: 'qa', k: 'keep', img: '16098', label: 'pencils $2 · notebooks $5 · backpack $20', q: 'Derek has $500. Can he buy them?', a: 'Yes! I can buy them ___!', chips: ['all'], src: '7쪽', nt: '학용품 가격' },
      { t: 'qa', k: 'keep', img: '15549', label: 'meat $10 · rice $5', q: 'Mom told me to buy food.', a: 'I need to buy ___ and ___ at the ___.', src: '8쪽', nt: '음식' },
      { t: 'qa', k: 'keep', img: '16228', label: 'jacket for my brother · $100', q: "Oh no! It's expensive! Should I buy it?", a: 'Yes, you should. / No, you ___.', src: '9쪽', nt: '형의 재킷', n: ['정답은 없습니다 — 학생 의견을 한 문장으로(«It\'s too expensive.»)'] },
      { t: 'qa', k: 'fix', img: '12366', q: 'What store is it? Do you need it or want it?', a: "It's a ___. I ___ bread.", chips: ['bakery', 'need'], src: '10쪽', nt: '빵집', n: ['«What store it is?» → What store is it?'] },
      { t: 'qa', k: 'fix', img: '12885', q: 'What store is it? Do you need it or want it?', a: "It's a ___ ___. I ___ a kitten.", chips: ['pet shop', 'want'], src: '11쪽', nt: '반려동물 가게' },
      { t: 'qa', k: 'fix', img: '12261', q: 'What store is it? Do you need it or want it?', a: "It's a ___ store. I ___ a new phone.", chips: ['gadget', 'want'], src: '12쪽', nt: '전자기기 가게' },
      { t: 'ox', k: 'new', img: '12885', s: 'Derek needs a kitten for school.', nt: '⭕❌', n: ['정답 ❌ → «No! He needs school supplies. He wants a kitten.»'] },
      { t: 'guess', k: 'new', img: 'gen:bts-11-birthday-gift', open: [0, 5], q: "It's my friend's birthday! What is in the box?", chips: ['Is it a toy?', 'Is it a book?', 'Is it a ___?'], nt: 'Guess who 타일', n: ['리본 달린 상자에서 강아지 얼굴이 쏙 — 질문으로만 맞히기(Is it…?)'] },
      { t: 'yourturn', k: 'keep', img: '12216', title: "My friend's birthday", lines: ["It's my friend's birthday.", 'I want to buy ___ for my friend.', 'I need to go to the ___.'], src: '13·14쪽', nt: '생일 선물' },
      { t: 'fill', k: 'fix', img: 'c7303', title: 'What do you need to buy?', lines: ['1. I need to buy ___.', '2. I need to buy ___.', '3. I want to buy ___.'], src: '15·16쪽', nt: '내 목록', n: ['짝 없는 따옴표 «buy”» → 물음표', '원본 5개 → 3개(need 둘 + want 하나로 구분 연습)'] },
      { t: 'match', k: 'new', left: ['16091', '12003', '13176', '12234'], right: ['bakery', 'music store', 'stationery store', 'supermarket'], nt: '짝 맞추기', n: ['맞힐 때마다 «Derek needs to go to the ___.»'] },
      { t: 'yourturn', k: 'keep', img: 'gen:bts-11-christmas', title: "It's Christmas!", lines: ["It's Christmas!", 'I want to buy ___ for my family.', 'I need to go to the ___ and the ___.'], src: '17·18쪽', nt: '크리스마스 쇼핑', n: ['가족 한 명씩 선물과 가게를 짝지어 말하기'] },
      { t: 'order', k: 'new', img: '18138', words: ['Derek', 'has', 'five', 'hundred', 'dollars'], nt: '순서 맞추기' },
      ...close([['I can plan my shopping.', 'I need pencils, meat and rice.'], ['I can say what I need and what I want.', 'I need bread. I want a kitten.'], ['I can say where I need to go.', 'I need to go to the stationery store.']], { img: 'gen:bts-11-review', q: 'Review time! Are you ready?', ko: '복습 시간! 준비됐니?' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 11 Review', orig: 20,
    intro: 'BTS 11 전체 복습. 게임판처럼 «스테이지» 를 깨며 넘어갑니다.',
    fixed: ['«USA dollars» → US dollars', '복습 쪽에 섞인 «feel» 문법(BTS 10) 삭제', 'cookies vs car 쪽 «need or want» 질문 정리'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-review', q: 'How much do you remember?', story: '4 stages. Can you clear them all? ⭐', nt: '표지', n: ['쇼핑백을 들고 쇼핑몰을 달리는 아이들 — «Ready, set, go!»'] },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 1 · Money & clothes 🔒', words: [['money', '돈', '16245'], ['million', '백만', '18068'], ['clothes', '옷', '12373'], ['clerk', '점원', '19438'], ['customer', '손님', '12883'], ['dresses', '드레스', '16833']], nt: '1단계 — 돈·옷(001~003)' },
      { t: 'qa', k: 'fix', img: '12916', q: 'What money do they use in the USA?', a: 'They use US ___.', chips: ['dollars'], src: '5쪽', nt: '미국 달러', n: ['«USA dollars» → US dollars'] },
      { t: 'qa', k: 'keep', img: '12856', q: 'What does a clothing store sell?', a: 'It sells ___.', chips: ['clothes'], src: '6쪽', nt: '옷가게' },
      { t: 'qa', k: 'keep', img: '19438', q: 'Who is he?', a: 'He is a ___. He helps customers.', chips: ['clerk'], src: '7쪽', nt: '점원' },
      { t: 'qa', k: 'keep', img: '12883', q: 'Who is she? What does she do?', a: 'She is a ___. She ___ things.', chips: ['customer', 'buys'], src: '8쪽', nt: '손님' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 2 · Stores 🔒', words: [['supermarket', '슈퍼마켓', '15265'], ['toy store', '장난감 가게', '16659'], ['flower shop', '꽃집', '16336'], ['pharmacy', '약국', '14701'], ['gadget store', '전자기기 가게', '12356'], ['bakery', '빵집', '12041']], nt: '2단계 — 가게(004~006)' },
      { t: 'qa', k: 'keep', img: '16335', q: 'What can you buy at the flower shop?', a: 'I can buy ___ at the flower shop.', chips: ['flowers'], src: '9·10쪽', nt: '꽃집' },
      { t: 'match', k: 'new', left: ['12062', '16659', '12404', '12261'], right: ['pharmacy', 'gadget store', 'bakery', 'toy store'], nt: '짝 맞추기', n: ['원본 11~14쪽의 «Where can you buy it?» 네 쪽을 한 게임으로'] },
      { t: 'table', k: 'fix', small: 'Stage 3', title: 'Need or want?', head: ['need', 'want'], rows: [['water', 'cookies'], ['food', 'a car'], ['a pencil', 'a new phone']], tip: '강사가 하나를 가리키면 «I need ___.» / «I want ___.»', src: '15쪽', nt: '3단계 — need / want(007~009)' },
      { t: 'ox', k: 'new', img: '12455', s: 'The ring is cheap.', nt: '⭕❌', n: ['정답 ❌ → «No! It\'s expensive.»'] },
      { t: 'guess', k: 'new', img: '19715', open: [], q: 'Stage 4 · Boss! Where are they?', chips: ['Are they in a store?', 'What do they want?', 'Can they buy it?'], nt: '4단계 — 보스 문제', n: ['타일을 하나씩 열 때마다 질문 한 개 — 이 권의 질문 문장을 모두 쓰게 됩니다'] },
      { t: 'yourturn', k: 'new', img: '13092', title: 'Your shopping day!', lines: ['I have $1,000!', 'I want to buy ___ at the ___.', 'I need to buy ___ at the ___.', "I can't buy ___. It's too expensive!"], nt: '마지막 말하기', n: ['want·need·can\'t 를 한꺼번에 — 이 권의 문장을 모두 모은 쪽'] },
      { t: 'ican', k: 'new', items: [['I can talk about money and prices.', "It's twenty dollars. They're fifty dollars."], ['I can talk about stores.', 'The bakery sells bread.'], ['I can say what I need and want.', 'I need a pencil. I want a kitten.']], nt: 'BTS 11 전체 I can' },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 11 Unit Test', orig: 16,
    intro: '12문항 단원 시험. 화상수업에서 말로 보는 시험이라 문항마다 «말로 답하기» 를 기준으로 했습니다.',
    fixed: ['문항 5: 한 쪽에 가게 사진 두 장 → 두 문장 빈칸으로', '문항 10·11: «He has 1 dollar left» 등 가격 계산 문장 정리', '문항 8 «What does she need?»(스마트폰) → 무엇이고 어디서 사는지 묻기'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-11-test', q: 'Test time! You can do it! 💪', story: '12 questions · 1 point each', nt: '표지', n: ['돋보기로 가격표를 살피는 꼬마 탐정 — 긴장을 풀어 줍니다'] },
      { t: 'qa', k: 'keep', img: '14301', title: '1.', q: 'What store is it? Who is he?', a: "It's a ___ ___. He is a ___.", src: '문항 1', nt: '문항 1' },
      { t: 'yourturn', k: 'keep', img: '12373', title: '2.', lines: ['What can you buy at the clothing store?', 'I can buy ___, ___ and ___.'], src: '문항 2', nt: '문항 2' },
      { t: 'qa', k: 'keep', img: '12304', title: '3.', q: 'The scarf is $10. How much is it?', a: "It's ___ dollars.", src: '문항 3', nt: '문항 3' },
      { t: 'qa', k: 'keep', img: '16357', title: '4.', q: 'The gloves are $17. How much are they?', a: "They're ___ dollars.", src: '문항 4', nt: '문항 4', n: ['is/are 를 가르는 문항 — 답의 They\'re 까지 확인'] },
      { t: 'fill', k: 'fix', title: '5.', lines: ['I am sick. I need to go to the ___.', 'I want roses. I need to go to the ___ ___.'], src: '문항 5', nt: '문항 5', n: ['원본: 한 쪽에 사진 두 장 → 상황 두 문장'] },
      { t: 'qa', k: 'keep', img: '12356', title: '6.', q: 'Which store sells these?', a: 'The ___ store sells them.', src: '문항 6', nt: '문항 6' },
      { t: 'yourturn', k: 'keep', img: '12376', title: '7.', lines: ['Your family is at the supermarket.', 'What do they buy? Name 5 things.', 'They buy ___, ___, ___, ___ and ___.'], src: '문항 7', nt: '문항 7 — 자유 답' },
      { t: 'qa', k: 'fix', img: '12261', title: '8.', q: 'What is it? Where can you buy it?', a: "It's a ___. I can buy it at the ___ store.", src: '문항 8', nt: '문항 8' },
      { t: 'qa', k: 'keep', img: 'c7205', title: '9.', q: 'What does the child want?', a: 'The child wants a ___.', src: '문항 9', nt: '문항 9' },
      { t: 'qa', k: 'fix', img: '12071', title: '10.', q: 'Jimmy has $157. The backpack is $156. Can he buy it?', a: 'Yes, he ___. He will have ___ dollar left.', src: '문항 10', nt: '문항 10' },
      { t: 'qa', k: 'fix', img: '16091', title: '11.', q: 'The notebook is $11. She has $10. Can she buy it?', a: "No, she ___. She needs ___ more dollar.", src: '문항 11', nt: '문항 11' },
      { t: 'yourturn', k: 'keep', img: '12133', title: '12.', lines: ["It's Christmas! You have one million dollars.", 'What do you want to buy? Name 5 things.', 'I want to buy ___.'], src: '문항 12', nt: '문항 12 — 자유 답' },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–4', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['5–8', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['9–11', 'Great!', '거의 다 왔어요 — 하나만 더'], ['12 ⭐', 'Perfect!', 'BTS 12 로 출발! 🎉']], src: '점수표', nt: '점수표', n: ['점수마다 다음에 할 일을 함께 적었습니다(점수로 끝나지 않게)'] },
      { t: 'next', k: 'new', img: 'gen:bts-11-next12', q: 'What do you want to be?', ko: '너는 커서 무엇이 되고 싶니?', nt: 'BTS 12 예고', n: ['다음 권(Jobs · Going to Work)의 첫 질문 — 소방관·의사·요리사 옷을 입은 아이들', '«I want to be…» 는 이 권의 «I want to buy…» 와 같은 틀이라 바로 이어집니다'] },
    ] },
  ],
};
