// BTS 4 새 교재 설계 데이터 — Unit 1 Food · Unit 2 I Like Food · Unit 3 Meals
import { open, close } from '../common.mjs';
const U1 = 'Unit 1', U2 = 'Unit 2', U3 = 'Unit 3';

const SONG1 = { t: 'song', k: 'new', title: 'Eat and Drink Chant', img: 'gen:bts-04-song-broccoli', nt: '음식 챈트(새로 지음)', n: ['원본 노래: «Do You Like Broccoli Ice Cream? Song» — 저작권 확인 전이라 이 과 낱말로 새 4줄 챈트를 지었습니다', '손뼉 박자에 맞춰 두 번 — 두 번째는 먹는 흉내·마시는 흉내를 함께'] };
const SONG2 = { t: 'song', k: 'new', title: 'I Like Food Chant', img: 'gen:bts-04-song-colors', nt: '좋아하는 음식 챈트(새로 지음)', n: ['원본 노래: «I Like Food Song» — 이 과 낱말로 새 4줄 챈트를 지었습니다', '낱말이 나올 때 그 음식을 가리키거나 그림 카드를 듭니다'] };
const SONG3 = { t: 'song', k: 'new', title: 'Meal Time Chant', img: 'gen:bts-04-song-meal', nt: '식사 챈트(새로 지음)', n: ["원본 노래: «Thank's for the Meal!»(제목 오타 Thank's → Thanks) — 이 과 낱말로 새 4줄 챈트를 지었습니다", '«munch» 에서 씹는 흉내를 크게'] };

export const COURSE = {
  head: `<h1>BTS 4 새 교재 — 전 과 설계 시안</h1>
<p class="lead">사이트의 BTS 4 원본 <b>261쪽</b>(11묶음: Food 001~003 · I Like Food 004~006 · Meals 007~009 · Review · Test)을 한 장씩 읽고, BTS 1 시안과 같은 원칙(한 쪽 한 목표 · 가림→공개 · 규칙 찾기 · 이어지는 이야기 · ⭕❌ · Guess who · I can · 다음 시간 예고)으로 다시 짰습니다.</p>
<div class="grid2">
<div class="box ok"><b>✅ 무엇을 지켰나</b><br>배우는 <b>음식·음료·식사 낱말과 eat / drink · like / doesn't like · for breakfast 문장</b>은 원본 그대로입니다. 원본 이야기(토니와 리사 · 티나와 줄리 · 베카와 브랜든 · 로이드와 루이즈)도 그대로 살렸습니다.</div>
<div class="box"><b>🆕 무엇을 더했나</b><br>과마다 표지 질문, 규칙 찾기, ⭕❌, Guess who, 기억 게임, 내 이야기(Your turn), I can ✅, 다음 시간 예고. 사진은 «먹는 표정» 이 살아 있는 장면(한입 크게 베어 물기 · 매운 고추에 놀란 얼굴 · 쓴 커피에 찡그린 얼굴)을 골랐습니다.</div>
</div>
<div class="box warn"><b>⚠️ 사진</b><br>점선 상자는 새로 만들 사진 자리입니다(요청 목록 gen/req-bts-04.json).</div>`,
  foot: `<h2>사람이 정할 것</h2><div class="box"><ol>
<li><b>생선(fish)을 «고기(Meat)» 로 분류</b> — 원본 004·005 낱말표와 004 19쪽 «Is fish meat? Yes» 가 그렇습니다. 영어권에서는 보통 fish 를 meat 와 따로 봅니다. 시안은 낱말표 분류는 두고 «Is fish meat?» 질문은 «Is chicken meat?» 로 바꿨습니다 — 분류표까지 고칠지 결정해 주세요.</li>
<li><b>001 이야기의 현재완료</b> — «Have you seen a green apple? / I haven't seen that yet.» 은 BTS 4 수준을 넘습니다. 원문 그대로 두었습니다(따라 읽기만). 쉬운 말로 바꿀지.</li>
<li><b>시험 7번 «bacon»</b> — 원본 사진은 달걀+베이컨인데 bacon 은 배우지 않은 낱말 → 시안은 «eggs and bread» 로 답이 되게 바꿨습니다.</li>
<li><b>인물 이름</b> — 과마다 대화 인물이 다릅니다(Tony·Lisa / Tina·Julie / Becca·Brandon / Lloyd·Louise). 원본대로 두고 망고가 진행을 맡게 했습니다. 한 반 친구들로 묶을지.</li>
<li><b>노래 곡조·QR</b> — 세 노래의 원곡 저작권 확인, 새 사진(점선 자리) 제작 승인.</li></ol></div>`,
  lessons: [
  // ───────────────────────── 001
  { code: '001', tab: '먹다·마시다', unit: U1, title: 'Food', orig: 31,
    intro: '음식·음료 낱말 15개와 «She eats an apple. / He drinks milk.». 이야기: 리사가 초록 사과를 가져왔어요!',
    fixed: ['목표 «현재진행형(present progressive)» → 본문은 현재형 → 목표를 실제 내용으로', 'drink 뜻 «음주» → «마시다»', "«It's an ice cream» → «It's ice cream.»(셀 수 없는 말)", '«Oh, alright!» → «Oh, all right!»', 'General Information 쪽·QR 코드는 화면판에서 뺐습니다'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-food-party', q: 'What do you like to eat?', story: 'Tony and Lisa talk about food. Lisa has a surprise!', nt: '표지 + Big Question', n: ['좋아하는 음식을 한국어로 말해도 좋습니다 — 오늘 끝에는 영어로 말합니다'] },
      ...open([['I can name foods and drinks.', '음식과 음료를 영어로 말할 수 있어요.'], ['I can say "It\'s an apple."', 'a / an 을 붙여 말해요.'], ['I can say "She eats an apple. He drinks milk."', '먹는 것과 마시는 것을 구별해요.']], 'Lesson Goals (현재진행형이라 적혀 있었음)'),
      { ...SONG1, src: 'Warm Up 4쪽', lines: ["Apple, rice and noodles, too!", "Pizza, soup — I eat with you!", "Milk and water, tea for me!", "Eat and drink — one, two, three!"] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Food 🔒', words: [['apple', '사과', '12058'], ['orange', '오렌지', '13147'], ['rice', '밥', '12003'], ['noodles', '국수', '16704'], ['soup', '수프', '12116'], ['pizza', '피자', '12668'], ['sandwich', '샌드위치', '13248'], ['hamburger', '햄버거', '18045']], src: 'Vocabulary 5쪽', nt: '낱말 ① — 가림', n: ['뜻을 가리고 사진만 보고 영어로 먼저 말하기'] },
      { t: 'vocab', k: 'keep', title: 'Food', words: [['apple', '사과', '12058'], ['orange', '오렌지', '13147'], ['rice', '밥', '12003'], ['noodles', '국수', '16704'], ['soup', '수프', '12116'], ['pizza', '피자', '12668'], ['sandwich', '샌드위치', '13248'], ['hamburger', '햄버거', '18045']], nt: '낱말 ① — 공개', n: ['따라 말하기 2번 → 강사가 가리키면 학생이 말하기'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Drinks & more 🔒', words: [['milk', '우유', '16520'], ['water', '물', '12123'], ['tea', '차', '12723'], ['coffee', '커피', 'c7064'], ['ice cream', '아이스크림', '12593'], ['cookies', '쿠키', '16052'], ['vegetables', '채소', '12268']], src: 'Vocabulary 5쪽', nt: '낱말 ② — 가림' },
      { t: 'vocab', k: 'fix', title: 'Drinks & more', words: [['milk', '우유', '16520'], ['water', '물', '12123'], ['tea', '차', '12723'], ['coffee', '커피', 'c7064'], ['ice cream', '아이스크림', '12593'], ['cookies', '쿠키', '16052'], ['vegetables', '채소', '12268']], nt: '낱말 ② — 공개', n: ['<del>drink 음주</del> → 마시다 (다음 쪽 규칙에서)'] },
      { t: 'rule', k: 'fix', title: 'Eat or drink?', left: { h: 'eat 🍽 먹다', ex: ['an **apple**, **rice**', '**pizza**, **noodles**'] }, right: { h: 'drink 🥤 마시다', ex: ['**milk**, **water**', '**juice**, **soda**'] }, q: 'Can you drink an apple? 😆', src: 'Grammar 6쪽', nt: '규칙 찾기 — 씹는 것 · 마시는 것', n: ['원본 정의(To swallow or chew / To consume liquid)는 강사 메모로 — 학생은 두 묶음을 보고 차이를 먼저 말합니다'] },
      { t: 'table', k: 'fix', small: 'Pattern', title: 'She eats an apple.', head: ['who', 'eats / drinks', 'what'], rows: [['She', 'eats', 'an apple.'], ['He', 'drinks', 'milk.'], ['I / You / They', 'eat / drink', 'pizza. / water.']], tip: 'a + 자음으로 시작(a pizza) · an + 모음으로 시작(an apple, an orange)', src: 'Grammar 7·8쪽', nt: '문장 틀', n: ['transitive verb / direct object 용어는 강사 메모로 옮겼습니다'] },
      { t: 'qa', k: 'keep', img: '12058', title: 'What is it?', q: 'What is it?', a: "It's an ___.", chips: ['apple', 'orange'], src: '11쪽', nt: 'a / an ①' },
      { t: 'qa', k: 'fix', img: '18045', q: 'Do you like it? What is it?', a: "It's (a / an) ___.", src: '13쪽', nt: 'a / an ②' },
      { t: 'qa', k: 'keep', img: '12003', q: 'What do you like to eat with rice?', a: "It's ___.", chips: ['rice', 'meat'], src: '14쪽', nt: '셀 수 없는 것', n: ['rice 앞에는 a / an 을 붙이지 않는다는 것을 짚습니다'] },
      { t: 'qa', k: 'fix', img: '16052', q: 'What are they? I like them!', a: 'They (are / is) ___.', chips: ['cookies', 'vegetables'], src: '15·17쪽', nt: '여러 개 — They are', n: ['원본 15·17쪽을 한 쪽으로'] },
      { t: 'qa', k: 'fix', img: '12593', q: 'Do you like ice cream?', a: "It's ___.", chips: ['coffee', 'ice cream'], src: '16쪽', nt: '❗ an 을 뺌', n: ["원본 «It's an ___ (ice cream)» → ice cream 은 셀 수 없어 «It's ice cream.»"] },
      { t: 'guess', k: 'new', img: '12047', open: [1, 6], q: 'What does he do?', chips: ['He drinks milk.', 'He eats an apple.'], nt: 'Guess who — 뭘 하고 있을까?', n: ['타일을 열 때마다 «He eats… / He drinks…» 로 추측'] },
      { t: 'qa', k: 'keep', img: '13401', q: 'What does she do?', a: 'She (drinks / eats) ___.', chips: ['noodles', 'rice'], src: '21쪽', nt: 'eats' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-big-burger', label: 'Ben', q: 'What does Ben do?', a: 'He (eats / drinks) a big ___.', chips: ['cookie', 'hamburger'], src: '22쪽', nt: 'eats', n: ['입을 크게 벌린 사진 — 학생도 따라서 «앙!»'] },
      { t: 'qa', k: 'fix', img: '15230', label: 'Andy', q: 'What does Andy eat?', a: 'Andy (drinks / eats) an ___.', src: '23쪽', nt: 'an' },
      { t: 'ox', k: 'new', img: '12384', s: 'She drinks ice cream.', nt: '⭕❌', n: ['정답 ❌ → «No! She eats ice cream.»'] },
      { t: 'table', k: 'keep', small: 'New words', title: 'Before the story', head: ['word', '뜻'], rows: [['start · bite', '시작하다 · 한 입'], ['delicious', '맛있는'], ['Australia', '호주'], ['bring / brought', '가져오다 / 가져왔다']], src: '24쪽', nt: '이야기 새 낱말' },
      { t: 'story', k: 'fix', img: 'gen:bts-04-green-apple', title: 'Can I have a bite?', lines: [['Tony', 'Lisa, what do you have?'], ['Lisa', "I have an apple. Can't you see it?"], ['Tony', 'Oh, all right! Can I have a bite?'], ['Lisa', 'Sure! Is it delicious?'], ['Tony', 'Yes, it is! Apples are delicious.']], src: '25쪽 Role-play', nt: '이야기 ①', n: ['<del>alright</del> → all right', '강사·학생이 역할을 나눠 읽고 두 번째는 바꿉니다'] },
      { t: 'story', k: 'keep', img: 'gen:bts-04-green-apple', title: 'A green apple!', lines: [['Lisa', 'Have you seen a green apple?'], ['Tony', "I haven't seen that yet. Do you have one?"], ['Lisa', 'Yes! My dad brought green apples from Australia.']], src: '26쪽', nt: '이야기 ②', n: ['⚠️ Have you seen 은 수준 밖 — 따라 읽기만(사람이 정할 것)'] },
      { t: 'story', k: 'fix', img: '12058', title: "Let's go!", lines: [['Tony', 'I will come with you!'], ['Lisa', "Okay. Let's start walking."]], src: '26쪽', nt: '이야기 ③', n: ['원본 마지막 두 줄 — 읽고 나서 «초록 사과는 어디 있을까?» 를 한국어로 상상해 말해도 좋습니다'] },
      { t: 'fill', k: 'keep', title: 'Questions', lines: ['What does Lisa have? — She has an ___.', "What did Lisa's dad bring? — He brought green ___.", 'Where are the green apples from? — They are from ___.'], src: '27쪽', nt: '이야기 질문' },
      { t: 'memory', k: 'fix', items: ['12668', '13248', '16052', '16704'], q: 'Look! 5 seconds! 👀', src: '28쪽 GAME', nt: '기억 게임 ① — Name that Food' },
      { t: 'memory', k: 'fix', hidden: true, items: ['12668', '13248', '16052', '16704'], q: 'What food did you see?', a: 'I saw ___, ___ …', nt: '기억 게임 ②', n: ['원본 «Name that Food» 를 기억 게임으로 — 본 것을 하나씩 말할 때마다 1점'] },
      { t: 'yourturn', k: 'fix', img: '12268', title: 'What vegetable do you like?', lines: ['I like ___.', 'I eat ___ every day.', 'I drink ___ every day.'], chips: ['rice', 'noodles', 'milk', 'water'], src: '20쪽', nt: '내 이야기' },
      ...close([['I can name foods and drinks.', 'pizza, noodles, milk, tea …'], ['I can say "It\'s an apple."', "It's a hamburger. It's an orange."], ['I can say "She eats an apple. He drinks milk."', 'She eats noodles. He drinks milk.']], { img: '15723', q: 'What do you like to drink?', ko: '무엇을 마시는 걸 좋아하나요? (다음 시간 — 음료)' }),
    ] },
  // ───────────────────────── 002
  { code: '002', tab: '음료', unit: U1, title: 'Food', orig: 20,
    intro: '음료 이야기: water · milk · juice · soda · coffee · tea. «He has tea.» 가 맞는지 틀렸는지 골라요.',
    fixed: ['«everyday» → «every day»(부사)', '13쪽 «Does she have mango juice?» — 사진은 오렌지 주스 → 오렌지 주스로', '16쪽 사진(햄버거)과 문장(cookies)이 다른 «Wrong» 문제 — 의도는 살리고 ⭕❌ 로', '17쪽 «What do the girls have?» — 사진 속 사람이 소녀들이 아님 → «What do they have?»', '매칭 쪽 가족 낱말은 «내 가족» 말하기로 옮김'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-cheers', q: 'What do you like to drink?', story: 'Cheers! Milk, juice or water?', nt: '표지 + Big Question' },
      ...open([['I can name drinks.', '음료 이름을 말할 수 있어요.'], ['I can say "She has a glass of juice."', '누가 무엇을 가졌는지 말해요.'], ['I can find a wrong sentence.', '틀린 문장을 찾아 고쳐 말해요.']]),
      { ...SONG1, src: 'Warm Up 4쪽', lines: ["Water, water, drink it up!", "Milk and juice are in my cup!", "Tea for Mom and coffee for Dad.", "Drink, drink, drink — and I am glad!"] },
      { t: 'vocab', k: 'new', hide: true, title: 'Drinks 🔒', words: [['water', '물', '12920'], ['milk', '우유', '12047'], ['juice', '주스', '16823'], ['soda', '탄산음료', '15723'], ['tea', '차', 'c7365'], ['coffee', '커피', '16715']], nt: '음료 낱말 — 가림', n: ['001과 다른 사진으로 — 사진이 아니라 뜻을 떠올리게'] },
      { t: 'vocab', k: 'new', title: 'Drinks', words: [['water', '물', '12920'], ['milk', '우유', '12047'], ['juice', '주스', '16823'], ['soda', '탄산음료', '15723'], ['tea', '차', 'c7365'], ['coffee', '커피', '16715']], nt: '음료 낱말 — 공개' },
      { t: 'rule', k: 'fix', title: 'has or have?', left: { h: 'he / she', ex: ['He **has** tea.', 'She **has** a glass of juice.'] }, right: { h: 'I / you / they', ex: ['I **have** milk.', 'They **have** pizza.'] }, q: 'When do we say "has"?', src: 'Grammar 6~8쪽', nt: '규칙 찾기' },
      { t: 'qa', k: 'fix', img: '12123', q: 'What do you see?', a: 'I see ___.', chips: ['water', 'soda'], src: '11쪽', nt: '무엇이 보여?', n: ['<del>everyday</del> → every day', '원본 질문 «How many glasses of water do you drink every day?» 는 끝의 Your turn 에서 답합니다'] },
      { t: 'qa', k: 'fix', img: '16520', q: 'Do you drink milk in the morning? What do you see?', a: 'I see ___.', chips: ['milk', 'soda'], src: '12쪽', nt: '무엇이 보여?' },
      { t: 'qa', k: 'fix', img: '16823', label: 'Jenny', q: 'What does Jenny have?', a: '(He / She) has a glass of ___.', src: '13쪽', nt: '❗ 사진에 맞춤', n: ['원본 «mango juice» 질문인데 사진은 오렌지 주스 → 사진대로'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-mr-lee-coffee', label: 'Mr. Lee', q: 'Do you like coffee? What does Mr. Lee have?', a: '(He / She) has ___.', chips: ['coffee', 'cola'], src: '14쪽', nt: 'has', n: ['쓴 커피에 찡그린 얼굴 — «Do you like coffee?» 에 다 같이 «No!» 가 나옵니다'] },
      { t: 'ox', k: 'fix', img: '12723', s: 'It is coffee.', src: '15쪽', nt: '⭕❌ — Correct or wrong?', n: ['원본 «He has tea. Correct / Wrong» → 몸으로 답하기. 정답 ❌ → «No! It is tea.»'] },
      { t: 'ox', k: 'fix', img: 'gen:bts-04-girl-burger', s: 'She eats cookies.', src: '16쪽', nt: '⭕❌ — 틀린 문장 고치기', n: ['원본 16쪽 의도(사진과 다른 문장 = Wrong)를 그대로 — 정답 ❌ → «She eats a hamburger.»', '<del>She (eats/eat)</del> 선택은 규칙 쪽에서 했으므로 뺐습니다'] },
      { t: 'qa', k: 'fix', img: 'c7046', q: 'What do they have?', a: 'They (have / has) ___.', src: '17쪽', nt: '❗ they', n: ['원본 «What do the girls have?» — 사진 속 인물이 소녀들이 아니어서 «they» 로'] },
      { t: 'guess', k: 'new', img: '19048', open: [2, 7], q: 'What does he drink?', chips: ['He drinks juice.', 'He drinks milk.'], nt: 'Guess who' },
      { t: 'match', k: 'fix', title: 'Match it!', left: ['12723', '16520', '16823', '15723'], right: ['juice', 'soda', 'tea', 'milk'], src: '18쪽 Match it', nt: '짝 맞추기' },
      { t: 'yourturn', k: 'fix', img: '14712', title: 'What does your family like to drink?', lines: ['My mother likes to drink ___.', 'My father likes to drink ___.', 'My ___ likes to drink ___.'], chips: ['grandmother', 'grandfather', 'brother', 'sister', 'coffee', 'water'], src: '18쪽', nt: '내 가족 이야기', n: ['원본 매칭(할머니·아버지…↔음료)을 «우리 가족» 말하기로'] },
      { t: 'yourturn', k: 'new', img: '12920', title: 'Water time!', lines: ['I drink ___ glasses of water every day.', 'I drink milk in the ___.', 'I like to drink ___.'], nt: '내 이야기' },
      ...close([['I can name drinks.', 'water, milk, juice, soda, tea, coffee'], ['I can say "She has a glass of juice."', 'Mr. Lee has coffee.'], ['I can find a wrong sentence.', 'No! She eats a hamburger.']], { img: 'gen:bts-04-drink-rice', q: 'Can you drink rice?', ko: '밥을 마실 수 있을까요? (다음 시간)' }),
    ] },
  // ───────────────────────── 003
  { code: '003', tab: '고쳐 말하기', unit: U1, title: 'Food', orig: 22,
    intro: 'eat / eats · drink / drinks 를 골라 쓰고, 틀린 문장을 고쳐 말합니다. 이야기: 누가 «밥을 마셔?» 하고 물었어요!',
    fixed: ['«Ooops…» → «Oops…»', '«We eat apple.» → «We eat apples.»', '14쪽 «They eat sandwiches» — 사진은 빵 롤 → 샌드위치 사진', '«I drink an apple → I eat an apple» 예시는 고쳐 쓰기 첫 줄로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-drink-rice', q: 'Can you drink rice?', story: 'Oops! Jane asks Bob a funny question.', nt: '표지 + Big Question' },
      ...open([['I can say "We eat …. We drink …."', '먹는 것과 마시는 것을 나눠 말해요.'], ['I can use eat and eats.', 'she 다음에는 eats 를 써요.'], ['I can fix a wrong sentence.', '틀린 문장을 바르게 고쳐요.']]),
      { ...SONG1, src: 'Warm Up 4쪽', lines: ["I eat rice. I drink tea.", "She eats apples. Look at me!", "He drinks milk. We eat soup.", "Eat or drink? Say it, group!"] },
      { t: 'story', k: 'fix', img: '12003', title: 'Do you drink rice?', lines: [['Jane', 'Hi, Bob! Do you drink rice?'], ['Bob', "No, I don't! I eat rice."], ['Bob', 'Your question is not right.'], ['Jane', 'Oops… Sorry!']], src: '10쪽', nt: '이야기 — 뭐가 틀렸을까?', n: ['<del>Ooops</del> → Oops', '읽기 전에 «제인의 질문이 왜 이상할까?» 를 먼저'] },
      { t: 'table', k: 'fix', title: 'We eat … We drink …', head: ['We eat …', 'We drink …'], rows: [['apples', 'water'], ['noodles', 'milk'], ['soup', 'juice']], tip: '사과처럼 셀 수 있는 것은 여러 개 → apples', src: '11쪽', nt: '문장 틀', n: ['<del>We eat apple.</del> → We eat apples.'] },
      { t: 'rule', k: 'new', title: 'eat or eats?', left: { h: 'I / you / we / they', ex: ['They **eat** rice.', 'We **drink** milk.'] }, right: { h: 'he / she', ex: ['She **eats** rice.', 'He **drinks** milk.'] }, q: 'When do we add -s?', nt: '규칙 찾기' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-girl-rice', q: 'What does she do?', a: 'She (eat / eats) ___.', src: '12쪽', nt: 'eats' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-girl-water', q: 'What does she do?', a: 'She (drinks / drink) ___.', src: '13쪽', nt: 'drinks' },
      { t: 'qa', k: 'fix', img: '16650', q: 'What do they eat?', a: 'They (eat / eats) ___.', src: '14쪽', nt: '❗ 사진 교체', n: ['원본 사진은 빵 롤 → 샌드위치 사진'] },
      { t: 'qa', k: 'keep', img: 'c7064', q: 'What do they drink?', a: 'They ___ ___.', src: '15쪽', nt: 'they drink' },
      { t: 'qa', k: 'keep', img: '12046', q: 'What do you eat for dinner?', a: 'I ___ ___ for dinner.', chips: ['eat', 'rice'], src: '16쪽', nt: '나는 …' },
      { t: 'qa', k: 'keep', img: 'c7133', q: 'What do you eat for lunch?', a: 'I ___ a ___ for lunch.', src: '17쪽', nt: '나는 …' },
      { t: 'qa', k: 'keep', img: '12047', q: 'Do you like to drink milk?', a: "Yes, I do! / No, I don't! I like to drink ___.", src: '18쪽', nt: '예 / 아니오' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-ice-cream-kids', q: 'Who do you see?', a: 'I see a ___ and a ___. They ___ ___.', chips: ['boy', 'girl', 'eat', 'ice cream'], src: '19쪽', nt: '두 사람' },
      { t: 'ox', k: 'new', img: '16704', s: 'We drink noodles.', nt: '⭕❌', n: ['정답 ❌ → «No! We eat noodles.»'] },
      { t: 'fill', k: 'fix', title: 'Correct the sentences!', lines: ['I drink an apple. → I ___ an apple.', 'They eat coffee. → They ___ coffee.', 'She drinks soup. → She ___ soup.', 'Jen eats juice. → Jen ___ juice.'], chips: ['eat', 'eats', 'drink', 'drinks'], src: '20쪽', nt: '고쳐 쓰기', n: ['원본 예시(Ex)를 첫 줄로 — 네 줄 모두 학생이 직접 고칩니다'] },
      { t: 'guess', k: 'new', img: '17027', open: [0, 8], q: 'What does he eat?', chips: ['He eats a carrot.', 'He drinks juice.'], nt: 'Guess who' },
      { t: 'yourturn', k: 'new', img: '13031', title: 'Your turn!', lines: ['I eat ___ for lunch.', 'I drink ___ every day.', "I don't drink ___!"], nt: '내 이야기' },
      ...close([['I can say "We eat …. We drink …."', 'We eat soup. We drink water.'], ['I can use eat and eats.', 'She eats rice.'], ['I can fix a wrong sentence.', 'They drink coffee.']], { img: 'gen:bts-04-veggie-faces', q: 'Is a tomato a fruit or a vegetable?', ko: '토마토는 과일일까 채소일까? (다음 단원 I Like Food)' }),
    ] },
  // ───────────────────────── 004
  { code: '004', tab: '과일·채소·고기', unit: U2, title: 'I Like Food', orig: 28,
    intro: '과일·채소·고기를 나누고 «I like … / She doesn\'t like …». 이야기: 티나와 줄리는 좋아하는 음식이 달라요.',
    fixed: ['«He likes tomato.» → «He likes tomatoes.»', '«Is banana meat? Is apple vegetable?» → a / an 넣기', '«Is fish meat? Yes» — 영어권 분류와 다름 → «Is chicken meat?» 로(사람이 정할 것)', "이야기 «all-day» → «all day»", "질문 «What vegetables Tina doesn't like?» → «What vegetables doesn't Tina like?» · «Does Julie like banana?» → bananas", 'Vegetable(단수) 상자 제목 → Vegetables'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-veggie-faces', q: 'Is a tomato a fruit or a vegetable?', story: "Tina and Julie talk about food they like — and food they don't!", nt: '표지 + Big Question' },
      ...open([['I can sort food: fruit, vegetables, meat.', '과일·채소·고기로 나눠요.'], ['I can say "I like bananas."', '좋아하는 음식을 말해요.'], ['I can say "She doesn\'t like broccoli."', '싫어하는 음식을 말해요.']]),
      { ...SONG2, src: 'Warm Up 4쪽', lines: ["Fruits are sweet. Yum, yum, yum!", "Vegetables — here they come!", "Beef and chicken, pork and fish.", "What do you like? Pick a dish!"] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Fruits & vegetables 🔒', cols: 5, words: [['orange', '오렌지', '13147'], ['banana', '바나나', '17005'], ['strawberry', '딸기', '16135'], ['apple', '사과', 'c7097'], ['mango', '망고', '18699'], ['carrot', '당근', '16129'], ['potato', '감자', '16131'], ['tomato', '토마토', '16273'], ['broccoli', '브로콜리', '16130'], ['pumpkin', '호박', '16680']], src: 'Vocabulary 5쪽', nt: '낱말 — 가림' },
      { t: 'vocab', k: 'keep', title: 'Fruits & vegetables', cols: 5, words: [['orange', '오렌지', '13147'], ['banana', '바나나', '17005'], ['strawberry', '딸기', '16135'], ['apple', '사과', 'c7097'], ['mango', '망고', '18699'], ['carrot', '당근', '16129'], ['potato', '감자', '16131'], ['tomato', '토마토', '16273'], ['broccoli', '브로콜리', '16130'], ['pumpkin', '호박', '16680']], nt: '낱말 — 공개', n: ['윗줄 과일, 아랫줄 채소 — 줄을 먼저 알아채게'] },
      { t: 'vocab', k: 'keep', hide: true, title: 'Meat 🔒', words: [['beef', '소고기', '16128'], ['chicken', '닭고기', '12574'], ['fish', '생선', '12974'], ['pork', '돼지고기', '15629']], src: 'Vocabulary 5쪽', nt: '고기 — 가림', n: ['⚠️ 원본은 fish 를 Meat 칸에 둠 — 사람이 정할 것'] },
      { t: 'rule', k: 'new', title: 'like or likes?', left: { h: 'I / you / they', ex: ['I **like** bananas.', "They **don't like** fish."] }, right: { h: 'he / she', ex: ['Jane **likes** apples.', "Jane **doesn't like** bananas."] }, q: "When do we say doesn't?", src: 'Grammar 6·7쪽', nt: '규칙 찾기' },
      { t: 'table', k: 'fix', title: 'He likes tomatoes.', head: ['who', 'yes ✔', 'no ✘'], rows: [['He / She / It', 'likes tomatoes.', "doesn't like tomatoes."], ['I / You / We / They', 'like tomatoes.', "don't like tomatoes."]], tip: "doesn't / don't 다음에는 언제나 like", src: 'Grammar 7쪽', nt: '문장 틀', n: ['<del>He likes tomato.</del> → He likes tomatoes.'] },
      { t: 'ox', k: 'fix', img: '17005', s: 'A banana is meat.', src: '9쪽', nt: '⭕❌ ①', n: ['<del>Is banana meat?</del> → a banana · 정답 ❌ → «No! A banana is a fruit.»'] },
      { t: 'ox', k: 'fix', img: '12574', s: 'Chicken is fruit.', src: '9쪽', nt: '⭕❌ ②', n: ['정답 ❌ → «No! Chicken is meat.»'] },
      { t: 'qa', k: 'fix', img: '12058', q: 'What is it?', a: 'It is an ___. An apple is a ___.', chips: ['vegetable', 'fruit'], src: '10쪽', nt: '과일? 채소?' },
      { t: 'qa', k: 'fix', img: '16131', q: 'What are they?', a: 'They are ___. Potatoes are ___.', chips: ['vegetables', 'fruit'], src: '11쪽', nt: '과일? 채소?' },
      { t: 'qa', k: 'fix', img: 'c7494', q: 'What does she have?', a: 'She has an ___ and a ___.', src: '12·13쪽', nt: '누가 무엇을', n: ['원본 12·13쪽(오렌지·바나나 한 장씩)을 한 쪽으로'] },
      { t: 'qa', k: 'fix', img: '15441', q: 'What does it eat?', a: 'It eats a ___.', src: '14쪽', nt: '동물이 먹는 것', n: ['원본은 토끼 — 당근을 먹는 기니피그 사진'] },
      { t: 'guess', k: 'new', img: 'c7134', open: [3, 4], q: 'What is it? 🌳', chips: ["It's broccoli!", "It's a tree!"], nt: 'Guess what', n: ['원본 15쪽(broccoli)을 게임으로 — «나무?» 하는 웃음 포인트'] },
      { t: 'memory', k: 'fix', items: ['16135', '18699', '15686', '16273'], q: 'Look! 5 seconds! 👀', src: '16·17쪽', nt: '기억 게임 ①' },
      { t: 'memory', k: 'fix', hidden: true, items: ['16135', '18699', '15686', '16273'], q: 'What are they?', a: 'They are strawberries, ___ …', nt: '기억 게임 ②', n: ['원본 «They are ___ and ___» 두 쪽을 기억 게임으로'] },
      { t: 'table', k: 'fix', small: 'Meat', title: 'Where does it come from?', head: ['meat', 'animal'], rows: [['Beef', 'comes from cows. 🐄'], ['Pork', 'comes from pigs. 🐖'], ['Chicken', 'comes from chickens. 🐔']], src: '18~20쪽', nt: '고기 이야기', n: ['원본 19쪽 «Is fish meat? Yes» 는 뺐습니다(사람이 정할 것)'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-farm', q: 'Is chicken meat?', a: 'Yes, it ___!', src: '19쪽', nt: '예', n: ['«Is chicken meat? Yes, it is!»'] },
      { t: 'table', k: 'fix', small: 'New words', title: 'Before the story', head: ['word', '뜻'], rows: [['agree', '같은 생각이다'], ['yummy', '맛있는'], ['picky', '입맛이 까다로운'], ['all day', '하루 종일']], src: '21쪽', nt: '이야기 새 낱말', n: ['<del>picky 까다롭다</del> → 입맛이 까다로운 · <del>all-day</del> → all day'] },
      { t: 'story', k: 'fix', img: '18740', title: 'Bananas are bad?', lines: [['Tina', 'Julie, my brother told me that bananas are bad.'], ['Julie', "I agree with him. I don't like bananas."], ['Tina', 'Really? I think bananas are yummy.'], ['Julie', "Uh. Okay. What fruit don't you like?"], ['Tina', "I like all of them. But there are vegetables I don't like."]], src: '22쪽 Role-play', nt: '이야기 ①' },
      { t: 'story', k: 'fix', img: 'gen:bts-04-meat-lover', title: 'You are picky!', lines: [['Julie', 'What are they?'], ['Tina', "I don't like broccoli and potatoes."], ['Julie', "Oh no! I don't like vegetables!"], ['Tina', 'You are picky, Julie!'], ['Julie', "That's okay. I like meat. I can eat it all day!"]], src: '23쪽', nt: '이야기 ②', n: ['<del>all-day</del> → all day'] },
      { t: 'fill', k: 'fix', title: 'Questions', lines: ['Does Julie like bananas? — No, she ___.', "What vegetables doesn't Tina like? — She doesn't like ___ and ___.", 'What food does Julie like? — She likes ___.'], src: '24쪽', nt: '이야기 질문', n: ['질문 문법 두 곳을 고쳤습니다(banana → bananas, 어순)'] },
      { t: 'fill', k: 'fix', title: 'Fruit, vegetable or meat?', lines: ['A strawberry is a ___.', 'Pork is ___.', 'A pumpkin is a ___.', 'A mango is a ___.'], chips: ['fruit', 'vegetable', 'meat'], src: '25쪽 GAME', nt: '상자에 넣기 게임', n: ['원본 «상자에 넣기»(Fruits / Vegetables / Meat) — 말로 답하게'] },
      { t: 'yourturn', k: 'new', img: '12988', title: 'Your turn!', lines: ['I like ___.', "I don't like ___.", 'My friend likes ___.'], nt: '내 이야기' },
      ...close([['I can sort food: fruit, vegetables, meat.', 'A banana is a fruit.'], ['I can say "I like bananas."', 'I like strawberries.'], ['I can say "She doesn\'t like broccoli."', "Julie doesn't like vegetables."]], { img: 'gen:bts-04-pizza-making', q: 'What is on your pizza?', ko: '내 피자에는 뭐가 올라갈까요? (다음 시간)' }),
    ] },
  // ───────────────────────── 005
  { code: '005', tab: '더 많은 음식', unit: U2, title: 'I Like Food', orig: 22,
    intro: '샐러드·빵·스파게티·치즈·고추·소시지. «He doesn\'t like chili peppers.» 이야기: 베카와 브랜든의 점심 이야기.',
    fixed: ['«But my favorite is sandwich.» → «…is sandwiches.»', '«It\'s ___ salad» → «It\'s a ___ salad.»', '«He (don\'t / doesn\'t) like ___» 빈칸 두 개가 같은 답 → 한 곳으로', '원본 노래는 새 챈트로 바꿈(저작권 확인 전)'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-pizza-making', q: 'What is on your pizza?', story: 'Becca and Brandon talk about their favorite food.', nt: '표지 + Big Question' },
      ...open([['I can name more foods.', '샐러드·빵·치즈·소시지를 말해요.'], ['I can ask "What food do you like?"', '좋아하는 음식을 물어요.'], ['I can say "He doesn\'t like chili peppers."', '싫어하는 것을 말해요.']]),
      { ...SONG2, src: 'Warm Up 4쪽', lines: ["Salad, bread and cheese for me.", "Spaghetti, sausage — one, two, three!", "Chili peppers? Too hot for me!", "I like pizza. Yum, yippee!"] },
      { t: 'vocab', k: 'new', hide: true, title: 'More food 🔒', words: [['salad', '샐러드', '12199'], ['bread', '빵', '12366'], ['spaghetti', '스파게티', '13286'], ['cheese', '치즈', '16139'], ['chili pepper', '고추', 'gen:bts-04-chili'], ['sausage', '소시지', '18325']], src: 'Vocabulary 5쪽', nt: '새 낱말 — 가림' },
      { t: 'vocab', k: 'keep', title: 'More food', words: [['salad', '샐러드', '12199'], ['bread', '빵', '12366'], ['spaghetti', '스파게티', '13286'], ['cheese', '치즈', '16139'], ['chili pepper', '고추', 'gen:bts-04-chili'], ['sausage', '소시지', '18325']], nt: '새 낱말 — 공개' },
      { t: 'story', k: 'fix', img: 'gen:bts-04-becca-brandon', title: 'What food do you like?', lines: [['Becca', 'What food do you like?'], ['Brandon', 'I like many kinds of food. My favorite is spaghetti!'], ['Becca', 'I like that, too! But my favorite is sandwiches.'], ['Brandon', "That's yummy!"]], src: '9·10쪽 Mini Conversation', nt: '짧은 대화', n: ['<del>my favorite is sandwich</del> → sandwiches'] },
      { t: 'qa', k: 'keep', img: '16139', q: 'What is it? Do you like it?', a: 'It is ___. I ___ it.', chips: ['like', "don't like"], src: '11쪽', nt: '좋아해?' },
      { t: 'qa', k: 'fix', img: '13248', q: 'What is it? What does it have?', a: 'It is a ___. It has bread and ___.', chips: ['sandwich', 'cheese'], src: '12쪽', nt: '무엇이 들었나' },
      { t: 'qa', k: 'keep', img: '14092', q: 'What kind of bread do you like?', a: 'I like ___.', src: '13쪽', nt: '내 생각' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-chicken-salad', q: 'What is it? What does it have?', a: "It's a ___ salad. It has ___.", chips: ['chicken', 'tomatoes'], src: '14쪽', nt: '샐러드', n: ["<del>It's ___ salad</del> → It's a ___ salad."] },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-chili-face', q: 'What does he have?', a: "He has a ___. He (don't / doesn't) like it.", src: '15쪽', nt: "doesn't", n: ['놀란 얼굴 사진 — «매워!» 를 함께 흉내'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-meatball-spaghetti', q: 'What does it have? It looks yummy!', a: 'The spaghetti (has / have) ___ and ___.', chips: ['meatballs', 'cheese'], src: '17쪽', nt: 'has' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-sausage-kids', q: 'Do they like sausage?', a: "Yes, they ___ sausage. It's yummy!", src: '18·19쪽', nt: '그들은?', n: ['원본 18쪽 «Do you like sausage?» 는 끝의 Your turn 으로'] },
      { t: 'ox', k: 'new', img: '12366', s: 'It is cheese.', nt: '⭕❌', n: ['정답 ❌ → «No! It is bread.»'] },
      { t: 'fill', k: 'fix', title: 'Make sentences!', lines: ['Ex) 👧 ✔ spaghetti → She likes spaghetti.', "👧 ✘ chili peppers → She ___ ___ chili peppers.", "👨 ✘ cheese → He ___ ___ cheese.", '👦👧 ✔ salad → They ___ salad.'], chips: ['like', 'likes', "doesn't", "don't"], src: '20쪽 GAME', nt: '얼굴 + ✔✘ 로 문장 만들기' },
      { t: 'guess', k: 'new', img: '13286', open: [2, 6], q: 'What is it?', chips: ["It's spaghetti!", "It's bread!"], nt: 'Guess what' },
      { t: 'memory', k: 'new', items: ['12199', '12366', '16139', '18325'], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ①' },
      { t: 'memory', k: 'new', hidden: true, items: ['12199', '12366', '16139', '18325'], q: 'What food did you see?', a: 'I saw ___ …', nt: '기억 게임 ②' },
      { t: 'yourturn', k: 'new', img: '13401', title: 'What food do you like?', lines: ['I like ___.', 'My favorite is ___!', "I don't like ___.", 'Do you like sausage? Yes, I do. / No, I don\'t.'], nt: '내 이야기', n: ['원본 18쪽 «Do you like sausage?» 를 여기서'] },
      ...close([['I can name more foods.', 'salad, bread, cheese, sausage …'], ['I can ask "What food do you like?"', 'What food do you like?'], ['I can say "He doesn\'t like chili peppers."', "He doesn't like chili peppers."]], { img: 'gen:bts-04-cheeseburger', q: 'Do you like cheeseburgers?', ko: '치즈버거 좋아해요? (다음 시간)' }),
    ] },
  // ───────────────────────── 006
  { code: '006', tab: '좋아해?', unit: U2, title: 'I Like Food', orig: 23,
    intro: '«Do you like …?» «Does she like …?» 로 묻고 답합니다. 이야기: 브랜든은 치즈 들어간 햄버거를 싫어해요.',
    fixed: ['9쪽 머리글 «MES 4» → BTS 4', '14쪽 아기가 고추를 깨무는 사진 → 어른 사진으로(아이에게 위험한 장면)', '«Favorite 인기 있는 말» → «가장 좋아하는»', '«spaghetti, ice cream and orange» → oranges', '18쪽 문장의 tomatoes 가 사진에 없음 → 사진에 맞게'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-cheeseburger', q: 'Do you like cheeseburgers?', story: "Brandon doesn't like hamburgers with cheese. Becca does!", nt: '표지 + Big Question' },
      ...open([['I can ask "Do you like …?"', '좋아하는지 물어요.'], ['I can say "Yes, she likes …"', '그 사람이 좋아하는 것을 말해요.'], ['I can say my favorite food.', '가장 좋아하는 음식을 말해요.']]),
      { ...SONG2, src: 'Warm Up 4쪽', lines: ["Do you like it? Yes, I do!", "Does she like it? Yes, she does, too!", "Do you like it? No, I don't!", "My favorite food is pizza. How about you?"] },
      { t: 'vocab', k: 'new', hide: true, title: 'Remember? 🔒', words: [['banana', '바나나', '16133'], ['strawberry', '딸기', '12516'], ['carrot', '당근', '17027'], ['tomato', '토마토', '12682'], ['chicken', '닭고기', 'c7052'], ['beef', '소고기', 'c7111'], ['cheese', '치즈', '16139'], ['salad', '샐러드', 'gen:bts-04-chicken-salad']], nt: '지난 낱말 떠올리기', n: ['004·005 낱말을 다른 사진으로 다시'] },
      { t: 'table', k: 'new', title: 'Do you like it?', head: ['question', 'yes', 'no'], rows: [['Do you like cheese?', 'Yes, I do.', "No, I don't."], ['Does she like cheese?', 'Yes, she does.', "No, she doesn't."], ['Do they like cheese?', 'Yes, they do.', "No, they don't."]], tip: 'Does 로 물으면 does / doesn\'t 로 답해요', nt: '문장 틀' },
      { t: 'story', k: 'fix', img: 'gen:bts-04-becca-brandon', title: 'Cheeseburgers!', lines: [['Becca', 'Do you like cheeseburgers?'], ['Brandon', "No, I don't like hamburgers with cheese."], ['Becca', "That's yummy for me!"]], src: '9·10쪽 Mini Conversation', nt: '짧은 대화', n: ['머리글 오타 «MES 4» 고침'] },
      { t: 'qa', k: 'keep', img: '18045', q: 'What about you? Do you like cheeseburgers?', a: 'I ___ cheeseburgers.', chips: ['like', "don't like"], src: '11쪽', nt: '나는?' },
      { t: 'qa', k: 'keep', img: '13286', q: 'Do you like spaghetti with cheese?', a: "Yes, I do. / No, I don't.", src: '12쪽', nt: '나는?' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-chicken-salad', q: 'Do you like chicken salad?', a: "Yes, I do. / No, I don't.", src: '13쪽', nt: '나는?' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-chili-woman', q: 'Does she like chili peppers?', a: 'Yes, she ___ chili peppers.', chips: ['like', 'likes'], src: '14쪽', nt: '❗ 사진 교체', n: ['원본: 아기가 고추를 깨무는 사진 → 어른이 즐겁게 먹는 사진'] },
      { t: 'qa', k: 'keep', img: '15404', q: 'Do you like meat with chili peppers?', a: "Yes, I do. / No, I don't.", src: '15쪽', nt: '나는?' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-mango-juice', q: 'Do you like mango juice?', a: "Yes, I do. / No, I don't.", src: '16쪽', nt: '나는?' },
      { t: 'qa', k: 'fix', img: '18740', q: "What vegetable doesn't she like?", a: "She doesn't ___ ___.", src: '18쪽', nt: '❗ 사진에 맞춤', n: ['원본 «broccoli and tomatoes» — 사진에는 브로콜리만 → 한 가지로'] },
      { t: 'qa', k: 'fix', img: '17158', q: 'What food does she like?', a: 'She likes spaghetti and ___. Her ___ food is ice cream.', chips: ['oranges', 'favorite'], src: '19쪽', nt: 'favorite', n: ['<del>Favorite 인기 있는 말</del> → 가장 좋아하는 · orange → oranges', '사진(아이스크림 고르는 소녀)에 맞게 «가장 좋아하는 것» 을 ice cream 으로'] },
      { t: 'ox', k: 'fix', img: '15723', s: 'They are glasses of milk.', src: '20쪽', nt: '⭕❌', n: ['원본 «They ___ cola.» → 몸으로 답하기. 정답 ❌ → «No! They are sodas.»'] },
      { t: 'guess', k: 'new', img: '18699', open: [1, 5], q: 'Does she like mangoes?', chips: ['Yes, she does.', "No, she doesn't."], nt: 'Guess who', n: ['다 열면 레몬도 보입니다 — «She doesn\'t like lemons!» 는 보너스'] },
      { t: 'yourturn', k: 'fix', img: '12110', title: 'Give me 3!', lines: ['FOOD: I like ___, ___ and ___.', 'DRINKS: I like ___, ___ and ___.', 'FRUITS: I like ___, ___ and ___.', "VEGETABLES: I don't like ___."], src: '21쪽 Give me 3!', nt: '셋 말하기 게임' },
      { t: 'yourturn', k: 'new', img: '12384', title: 'My favorite food', lines: ['My favorite food is ___.', 'I like it very much!', "I don't like ___."], nt: '내 이야기' },
      ...close([['I can ask "Do you like …?"', 'Do you like mango juice?'], ['I can say "Yes, she likes …"', 'Yes, she likes chili peppers.'], ['I can say my favorite food.', 'My favorite food is spaghetti.']], { img: 'gen:bts-04-breakfast-cover', q: 'What do you eat for breakfast?', ko: '아침에 뭘 먹나요? (다음 단원 Meals)' }),
    ] },
  // ───────────────────────── 007
  { code: '007', tab: '아침·점심·저녁', unit: U3, title: 'Meals', orig: 35,
    intro: 'breakfast · lunch · dinner · snacks 와 «He eats eggs for breakfast.». 이야기: 루이즈는 배가 고파요!',
    fixed: ['«dinner 공식 만찬» → «저녁 식사» · «afternoon 대낮» → «오후»', '현재형 설명 «지금 일어나고 있는 일» → 현재진행형과 헷갈림 → «늘·자주 하는 일, 사실»', '«everyday» → «every day»', '«hotdogs» → «hot dogs» · «cereals» → «cereal»', '원본 노래(제목 오타 «Thank\'s») → 새 챈트로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-breakfast-cover', q: 'What do you eat for breakfast?', story: 'Louise is hungry. What did she eat this morning?', nt: '표지 + Big Question' },
      ...open([['I can name meals.', '아침·점심·저녁·간식을 말해요.'], ['I can say "We eat lunch at noon."', '언제 먹는지 말해요.'], ['I can say "He eats eggs for breakfast."', '누가 무엇을 언제 먹는지 말해요.']]),
      { ...SONG3, src: 'Warm Up 4쪽', lines: ["Breakfast in the morning. Yum, yum, yum!", "Lunch at noon. Here we come!", "Snacks in the afternoon. One, two, three!", "Dinner in the evening with my family!"] },
      { t: 'vocab', k: 'fix', hide: true, title: 'Meals 🔒', words: [['breakfast', '아침 식사', 'c5004'], ['lunch', '점심', '16649'], ['dinner', '저녁 식사', 'c7176'], ['meal', '식사', '12110'], ['cereal', '시리얼', '16884'], ['eggs', '달걀', '16714'], ['biscuits', '비스킷', 'c7193'], ['snacks', '간식', '12228']], src: 'Vocabulary 5쪽', nt: '낱말 — 가림' },
      { t: 'vocab', k: 'fix', title: 'Meals', words: [['breakfast', '아침 식사', 'c5004'], ['lunch', '점심', '16649'], ['dinner', '저녁 식사', 'c7176'], ['meal', '식사', '12110'], ['cereal', '시리얼', '16884'], ['eggs', '달걀', '16714'], ['biscuits', '비스킷', 'c7193'], ['snacks', '간식', '12228']], nt: '낱말 — 공개', n: ['<del>공식 만찬</del> → 저녁 식사'] },
      { t: 'vocab', k: 'fix', hide: true, title: 'When? 🔒', words: [['morning', '아침', '12245'], ['noon', '정오(낮 12시)', '12531'], ['afternoon', '오후', '18904'], ['evening', '저녁', '12242']], src: 'Vocabulary 5쪽', nt: '때 — 가림', n: ['<del>대낮</del> → 오후'] },
      { t: 'table', k: 'new', title: 'When do we eat?', head: ['when', 'meal'], rows: [['in the morning 🌅', 'breakfast'], ['at noon 🕛', 'lunch'], ['in the afternoon 🕒', 'snacks'], ['in the evening 🌇', 'dinner']], nt: '때 — 공개 + 짝', n: ['in the morning · at noon · in the evening — 전치사를 짚어 줍니다'] },
      { t: 'rule', k: 'fix', title: "eats or doesn't eat?", left: { h: 'yes ✔', ex: ['The man **eats** rice for breakfast.', 'Jane **drinks** coffee every day.'] }, right: { h: 'no ✘', ex: ["The man **doesn't eat** rice for breakfast.", "Gina **doesn't like** bananas."] }, q: "After doesn't, is it eat or eats?", src: 'Grammar 6~8쪽', nt: '규칙 찾기', n: ['원본 현재형 설명 «지금 일어나는 일» 은 틀린 설명 → 강사 메모: 현재형은 «늘 하는 일·사실»', '<del>everyday</del> → every day'] },
      { t: 'qa', k: 'fix', img: '16265', q: 'What is it?', a: "It's ___. We eat it in the morning.", src: '11쪽', nt: 'breakfast', n: ["원본 «It's break___. We eat breakfast in the morning.» — 뒷문장이 답을 알려 줌 → «it» 으로"] },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-egg-boy', q: 'What does he eat?', a: 'He ___ eggs for ___.', src: '12쪽', nt: 'for breakfast' },
      { t: 'qa', k: 'keep', img: '12531', q: "It's lunch. When do we eat lunch?", a: 'We eat lunch at (noon / morning).', src: '13쪽', nt: 'at noon' },
      { t: 'qa', k: 'keep', img: '21346', label: 'Anna', q: 'What does Anna eat for lunch?', a: '___ eats a ___ for lunch.', src: '14쪽', nt: 'for lunch' },
      { t: 'qa', k: 'keep', img: '12228', q: 'What are they?', a: 'They are (chickens / snacks). We eat snacks in the afternoon.', src: '15쪽', nt: 'snacks' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-cookie-boy', label: 'Jimmy', q: 'What does Jimmy eat?', a: 'He eats a ___.', src: '16쪽', nt: '간식' },
      { t: 'qa', k: 'keep', img: 'c7176', q: "It's dinner. When do we eat dinner?", a: 'We eat dinner in the (morning / evening).', src: '17쪽', nt: 'in the evening' },
      { t: 'qa', k: 'fix', img: '18517', q: 'What does he eat for dinner?', a: 'He ___ meat for ___.', src: '18쪽', nt: 'for dinner', n: ['원본은 여자(she) — 고기를 먹는 사진에 맞춰 he'] },
      { t: 'qa', k: 'fix', img: 'c5004', q: 'What does the child eat for breakfast?', a: 'The child eats ___ and drinks ___.', chips: ['cereal', 'milk'], src: '19쪽', nt: 'cereal' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-girl-burger', label: 'Mia', q: "What is Mia's snack?", a: "She has a ___. It's her (lunch / snack).", src: '22쪽', nt: '간식' },
      { t: 'ox', k: 'fix', img: '12047', s: 'He drinks juice for breakfast.', src: '23쪽', nt: '⭕❌', n: ['원본 «They (drinks/drink) milk for breakfast» → 정답 ❌ → «No! He drinks milk.»'] },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-mr-lee-coffee', label: 'Bobby', q: 'What does Bobby drink for lunch?', a: 'He ___ ___ for lunch.', src: '24쪽', nt: 'drinks' },
      { t: 'guess', k: 'new', img: '19642', open: [4], q: 'Does he eat breakfast?', chips: ['Yes, he does.', "No, he doesn't!"], nt: 'Guess who', n: ['다 열면 시리얼을 두고 뛰어나가는 소년 — «He doesn\'t eat breakfast!»'] },
      { t: 'table', k: 'fix', small: 'New words', title: 'Before the story', head: ['word', '뜻'], rows: [['hungry', '배고픈'], ['usually', '보통, 대개'], ['hot dogs', '핫도그'], ['cereal', '시리얼']], src: '26쪽', nt: '이야기 새 낱말', n: ['<del>hotdogs</del> → hot dogs'] },
      { t: 'story', k: 'keep', img: 'gen:bts-04-hungry-girl', title: 'Are you hungry?', lines: [['Lloyd', 'Hi, Louise! Are you okay?'], ['Louise', "No, I'm not."], ['Lloyd', 'Are you hungry?'], ['Louise', 'Yes. I did not like our breakfast.'], ['Lloyd', 'What did you eat?']], src: '27쪽 Role-play', nt: '이야기 ①' },
      { t: 'story', k: 'fix', img: '12468', title: "Let's eat lunch!", lines: [['Louise', 'I ate hot dogs, eggs and rice.'], ['Lloyd', "That's delicious!"], ['Louise', 'Not for me. I usually eat cereal for breakfast.'], ['Lloyd', "Okay, let's eat lunch together!"], ['Louise', "Let's eat a lot!"]], src: '28쪽', nt: '이야기 ②', n: ['<del>hotdogs</del> → hot dogs · <del>cereals</del> → cereal'] },
      { t: 'fill', k: 'keep', title: 'Questions', lines: ['Is Louise hungry? — Yes, she ___.', 'What did Louise eat for breakfast? — She ate ___, ___ and ___.', 'What does Louise usually eat for breakfast? — She usually eats ___.'], src: '29쪽', nt: '이야기 질문' },
      { t: 'memory', k: 'new', items: ['16714', '16649', 'c7176', '12228'], q: 'Look! 5 seconds! 👀', nt: '기억 게임 ①' },
      { t: 'memory', k: 'new', hidden: true, items: ['16714', '16649', 'c7176', '12228'], q: 'What meals did you see?', a: 'I saw breakfast, ___ …', nt: '기억 게임 ②' },
      { t: 'yourturn', k: 'fix', img: '12925', title: 'I like to eat and drink…', lines: ['I like to eat ___ and drink ___.', 'I eat ___ for breakfast.', 'I eat ___ for dinner.'], chips: ['noodles', 'hamburgers', 'bread', 'chicken', 'tea', 'milk', 'juice'], src: '30쪽 Match', nt: '내 이야기', n: ['원본 짝짓기(음식 ↔ 음료)를 «내가 좋아하는 짝» 말하기로'] },
      ...close([['I can name meals.', 'breakfast, lunch, dinner, snacks'], ['I can say "We eat lunch at noon."', 'We eat dinner in the evening.'], ['I can say "He eats eggs for breakfast."', 'He eats eggs for breakfast.']], { img: 'gen:bts-04-lunch-trade', q: 'When do you drink milk?', ko: '우유는 언제 마시나요? (다음 시간)' }),
    ] },
  // ───────────────────────── 008
  { code: '008', tab: '언제 먹어?', unit: U3, title: 'Meals', orig: 22,
    intro: '«When does Anna drink milk? — She drinks milk for breakfast.» 때와 식사를 이어 말합니다.',
    fixed: ['현재형 설명 오류(007과 같은 쪽) → 강사 메모로', '14쪽 «He ___ ___ for ___» 빈칸의 답이 사진으로 정해지지 않음 → «He doesn\'t like his lunch.»', '17쪽 «She ___ ___ for ___» 에 시계만 있어 답이 여럿 → 보기에 식사 셋을 둠'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-lunch-trade', q: 'When do you drink milk?', story: 'Breakfast, lunch or dinner? Let\'s find out!', nt: '표지 + Big Question' },
      ...open([['I can ask "When do you eat …?"', '언제 먹는지 물어요.'], ['I can say "She drinks milk for breakfast."', '언제 먹고 마시는지 말해요.'], ['I can say "No, he doesn\'t."', '좋아하지 않는다고 답해요.']]),
      { ...SONG3, src: 'Warm Up 4쪽', lines: ["When do you drink milk? For breakfast!", "When do you eat apples? For lunch!", "When do you eat chicken? For dinner!", "Crunch, crunch, munch, munch, munch!"] },
      { t: 'scramble', k: 'keep', title: 'What is it?', items: [['teabkasrf', '16265'], ['chlun', '16649'], ['nrdine', '12046']], src: '9쪽', nt: '글자 섞기', n: ['원본 그대로 — 사진이 힌트입니다'] },
      { t: 'table', k: 'fix', title: 'When does she drink milk?', head: ['question', 'answer'], rows: [['When does she drink milk?', 'She drinks milk for breakfast.'], ['When do they eat chicken?', 'They eat chicken for dinner.'], ['Does he like his lunch?', "No, he doesn't."]], tip: 'for + breakfast / lunch / dinner (a, the 없이)', src: 'Grammar 6~8쪽', nt: '문장 틀' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-happy-breakfast', q: 'What does she eat for breakfast?', a: 'She (eats / eat) ___ and ___ for breakfast.', src: '10쪽', nt: 'for breakfast' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-happy-breakfast', q: 'Does she like her breakfast?', a: 'Yes, she does. She ___ eggs and rice for ___.', chips: ['likes', 'breakfast'], src: '11쪽', nt: 'likes' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-big-lunch', q: 'What does he eat for lunch?', a: 'He eats ___, ___ and a ___.', chips: ['spaghetti', 'chicken', 'hamburger'], src: '12쪽', nt: 'for lunch' },
      { t: 'qa', k: 'fix', img: 'gen:bts-04-lunch-frown', q: 'Does he like his lunch?', a: "No, he doesn't. He doesn't ___ his ___.", src: '13쪽', nt: "doesn't" },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-noodle-family', q: 'What do they eat for dinner?', a: 'They eat ___ for ___. They drink ___.', src: '14쪽', nt: 'for dinner' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-noodle-family', q: 'Do they like it?', a: 'Yes, they do. They like ___ for ___.', src: '15쪽', nt: 'like' },
      { t: 'qa', k: 'fix', img: '12245', label: 'Anna', q: 'When does Anna drink milk?', a: 'She ___ ___ for ___.', chips: ['breakfast', 'lunch', 'dinner'], src: '16쪽', nt: 'When ①' },
      { t: 'qa', k: 'keep', img: '12531', label: 'Sally', q: 'When does Sally eat apples? When do you eat apples?', a: 'She eats apples for ___.', src: '17쪽', nt: 'When ②' },
      { t: 'qa', k: 'keep', img: '12242', q: 'When do they eat chicken? When do you eat chicken?', a: '___ eat ___ for ___.', src: '18쪽', nt: 'When ③' },
      { t: 'ox', k: 'new', img: '12531', s: 'We eat dinner at noon.', nt: '⭕❌', n: ['정답 ❌ → «No! We eat lunch at noon.»'] },
      { t: 'match', k: 'new', title: 'Match it!', left: ['12245', '12531', '12242'], right: ['dinner', 'breakfast', 'lunch'], nt: '때 ↔ 식사' },
      { t: 'guess', k: 'new', img: '12925', open: [2, 6], q: 'When do they eat?', chips: ['They eat dinner in the evening.', 'They eat breakfast.'], nt: 'Guess who' },
      { t: 'yourturn', k: 'fix', img: '12383', title: 'When do you eat or drink them?', lines: ['I eat ___ for breakfast.', 'I drink ___ for lunch.', 'I eat ___ for dinner.'], chips: ['vegetables', 'oranges', 'coffee', 'juice', 'meat', 'broccoli', 'pizza', 'rice', 'cookies', 'tea'], src: '19쪽', nt: '내 이야기' },
      ...close([['I can ask "When do you eat …?"', 'When do you eat apples?'], ['I can say "She drinks milk for breakfast."', 'She drinks milk for breakfast.'], ['I can say "No, he doesn\'t."', "No, he doesn't."]], { img: 'gen:bts-04-fav-food', q: 'What food do you like best?', ko: '제일 좋아하는 음식은? (다음 시간)' }),
    ] },
  // ───────────────────────── 009
  { code: '009', tab: '내 음식 이야기', unit: U3, title: 'Meals', orig: 23,
    intro: '좋아하는 음식·싫어하는 음식·식사별로 좋아하는 것을 말합니다. 단원 마무리.',
    fixed: ['«What food do you see?» 그림(9개 음식)을 낱말 찾기 게임으로', '«I don\'t like sandwich» → sandwiches', 'Your turn 쪽 빈 번호(1~4)를 문장 틀로'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-fav-food', q: 'What food do you like best?', story: 'Show us your favorite food!', nt: '표지 + Big Question' },
      ...open([['I can say what I like to eat.', '좋아하는 음식을 말해요.'], ['I can say what I don\'t like.', '싫어하는 음식·음료를 말해요.'], ['I can talk about my meals.', '아침·점심·저녁에 좋아하는 것을 말해요.']]),
      { ...SONG3, src: 'Warm Up 4쪽', lines: ["I like spaghetti. I like rice.", "I don't like soda. It's not nice!", "Cereal for breakfast, soup for lunch.", "My favorite meal? Munch, munch, munch!"] },
      { t: 'search', k: 'fix', title: 'What food do you see?', grid: ['broccolim', 'xchickenq', 'potatozsw', 'ktomatorj', 'bananaeyv', 'soupwzkqa'], words: ['broccoli', 'chicken', 'potato', 'tomato', 'banana', 'soup'], src: '9쪽', nt: '낱말 찾기', n: ['원본 그림 속 음식(broccoli·potato·tomato·banana·soup·eggs·chicken…)을 찾기 게임으로', '찾을 때마다 «I like … / I don\'t like …» 한 문장'] },
      { t: 'qa', k: 'keep', img: '13286', q: 'What food do you like?', a: 'I like ___.', chips: ['spaghetti', 'oranges', 'cookies'], src: '10쪽', nt: '좋아해 ①' },
      { t: 'qa', k: 'keep', img: '16130', q: 'What food do you like?', a: 'I like ___.', chips: ['broccoli', 'rice', 'noodles'], src: '11쪽', nt: '좋아해 ②' },
      { t: 'qa', k: 'fix', img: '12668', q: "What food don't you like?", a: "I don't like ___.", chips: ['pizza', 'apples', 'sandwiches'], src: '12쪽', nt: '싫어해', n: ['<del>sandwich</del> → sandwiches'] },
      { t: 'qa', k: 'keep', img: '16520', q: 'What do you like to drink?', a: 'I like to drink ___.', chips: ['milk', 'coffee'], src: '13쪽', nt: '마실 것' },
      { t: 'qa', k: 'keep', img: 'c7252', q: "What don't you like to drink?", a: "I don't like to drink ___.", chips: ['tea', 'soda', 'coffee'], src: '14쪽', nt: '싫은 음료', n: ['쓴 커피에 찡그린 얼굴 — 따라 해 보기'] },
      { t: 'qa', k: 'keep', img: '16265', q: 'What do you like for breakfast?', a: 'I like ___ for breakfast.', chips: ['cereal', 'rice and meat'], src: '15쪽', nt: '아침' },
      { t: 'qa', k: 'keep', img: 'c7309', q: 'What do you like for lunch?', a: 'I like ___ for lunch.', chips: ['hamburgers', 'sandwiches'], src: '16쪽', nt: '점심' },
      { t: 'qa', k: 'keep', img: 'c7193', q: 'What snack do you like?', a: 'I like ___.', chips: ['cookies', 'noodles'], src: '17쪽', nt: '간식' },
      { t: 'qa', k: 'keep', img: 'c7111', q: 'What do you like for dinner?', a: 'I like ___ for dinner.', chips: ['beef', 'pizza'], src: '18쪽', nt: '저녁' },
      { t: 'ox', k: 'new', img: '12259', s: 'They drink popcorn.', nt: '⭕❌', n: ['정답 ❌ → «No! They eat popcorn.»'] },
      { t: 'guess', k: 'new', img: '17158', open: [0, 7], q: 'What does she like?', chips: ['She likes ice cream!', 'She likes soup.'], nt: 'Guess who' },
      { t: 'yourturn', k: 'fix', img: '13031', title: 'FOOD I like to eat!', lines: ['I like ___.', 'I like ___.', 'I like ___ for breakfast.', 'My favorite food is ___!'], src: '19쪽 Your turn', nt: '내 이야기 ①' },
      { t: 'yourturn', k: 'fix', img: '18740', title: "FOOD I don't like to eat!", lines: ["I don't like ___.", "I don't like ___.", "I don't like to drink ___."], src: '20쪽 Your turn', nt: '내 이야기 ②' },
      ...close([['I can say what I like to eat.', 'I like spaghetti.'], ["I can say what I don't like.", "I don't like to drink coffee."], ['I can talk about my meals.', 'I like cereal for breakfast.']], { img: 'gen:bts-04-quiz-show', q: 'Review time! Are you ready?', ko: '다음 시간은 BTS 4 복습 — 준비됐나요?' }),
    ] },
  // ───────────────────────── REVIEW
  { code: 'REVIEW', tab: '복습', unit: 'Review', title: 'BTS 4 Review', orig: 16,
    intro: 'BTS 4 전체 복습. 세 스테이지(Food · I Like Food · Meals)를 깨며 넘어갑니다.',
    fixed: ["«It's an ice cream» → «It's ice cream.»", '«Is apple a fruit? / Is banana a vegetable?» → an apple / a banana', '«Apple is a ___» → «An apple is a ___»'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-quiz-show', q: 'How much do you remember?', story: '3 stages. Can you clear them all? ⭐', nt: '표지' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 1 · Food 🔒', words: [['ice cream', '아이스크림', '13302'], ['vegetables', '채소', 'c7002'], ['rice', '밥', '12003'], ['soup', '수프', '12013'], ['milk', '우유', '16520'], ['juice', '주스', 'c7233'], ['hamburger', '햄버거', '15241'], ['cookies', '쿠키', '14989']], nt: '1단계 — 음식(001~003)' },
      { t: 'qa', k: 'fix', img: '13302', q: 'What is it?', a: "It's ___.", src: '6쪽', nt: 'ice cream', n: ["<del>It's an ___</del> → It's ___ (ice cream)"] },
      { t: 'qa', k: 'keep', img: 'c7002', q: 'What are they?', a: 'They are ___.', src: '7쪽', nt: 'vegetables' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-girl-rice', q: 'What does she do?', a: 'She (eat / eats) rice.', src: '8쪽', nt: 'eats' },
      { t: 'qa', k: 'keep', img: '21346', q: 'What does she eat for lunch?', a: '___ eats a ___ for lunch.', src: '9쪽', nt: 'for lunch' },
      { t: 'vocab', k: 'new', hide: true, title: 'Stage 2 · I like food 🔒', words: [['strawberry', '딸기', '16135'], ['mango', '망고', '18699'], ['potato', '감자', '16132'], ['pumpkin', '호박', '15686'], ['pork', '돼지고기', 'c7087'], ['spaghetti', '스파게티', '18418']], nt: '2단계 — 좋아하는 음식(004~006)' },
      { t: 'qa', k: 'fix', img: '12058', q: 'Is an apple a fruit?', a: 'Yes, it is. An apple is a ___.', src: '10쪽', nt: '과일', n: ['<del>Is apple</del> → Is an apple'] },
      { t: 'qa', k: 'fix', img: '16133', q: 'Is a banana a vegetable?', a: "No, it isn't. A banana is a ___.", src: '11쪽', nt: '과일', n: ['<del>Is banana</del> → Is a banana'] },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-sausage-kids', q: 'What is it? Do they like it?', a: "It's sausage. Yes, they ___ it.", src: '12쪽', nt: 'like' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-mango-juice', q: 'What is it? Does she like it?', a: "It's mango ___. Yes, she ___ it.", src: '13쪽', nt: 'likes' },
      { t: 'qa', k: 'keep', img: '12245', label: 'Anna', q: 'Stage 3 · When does Anna drink milk?', a: 'She ___ milk for ___.', src: '14쪽', nt: '3단계 — 식사(007~009)' },
      { t: 'qa', k: 'keep', img: 'c7052', q: 'When do they eat chicken?', a: '___ eat ___ for ___.', src: '15쪽', nt: 'for dinner' },
      { t: 'guess', k: 'new', img: '12925', open: [], q: 'Boss! What do they do?', chips: ['Do they eat …?', 'When do they eat?', 'Do they like it?'], nt: '보스 문제', n: ['타일을 열 때마다 질문 하나 — 마지막 정답: «They eat dinner in the evening.»'] },
      { t: 'ican', k: 'new', items: [['I can talk about food and drinks.', 'She eats rice. He drinks milk.'], ['I can say what I like.', "I like mangoes. I don't like pork."], ['I can talk about meals.', 'I eat eggs for breakfast.']], nt: 'BTS 4 전체 I can' },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
    ] },
  // ───────────────────────── TEST
  { code: 'TEST', tab: '시험', unit: 'Test', title: 'BTS 4 Unit Test', orig: 19,
    intro: '12문항 단원 시험. 화상수업에서 말로 보는 시험입니다.',
    fixed: ['7번 사진의 bacon 은 배우지 않은 낱말 → «eggs and bread» 로 답이 되게', '6번 «No, ___» — 사진 속 소녀는 망고를 좋아하는 표정 → «Yes»', '3번 사진을 한 사람이 먹고 마시는 사진으로', 'General Information 쪽은 뺐습니다'],
    slides: [
      { t: 'cover', k: 'new', img: 'gen:bts-04-test-cover', q: 'Test time! You can do it! 💪', story: '12 questions · 1 point each', nt: '표지' },
      { t: 'qa', k: 'fix', img: '12516', title: '1.', q: 'What are they?', a: 'They are ___.', src: '문항 1', nt: '문항 1', n: ['원본 «What is it?» — 사진은 딸기 여러 개 → What are they?'] },
      { t: 'qa', k: 'keep', img: '16131', title: '2.', q: 'What are they?', a: 'They are ___.', src: '문항 2', nt: '문항 2' },
      { t: 'qa', k: 'fix', img: 'c5013', title: '3.', q: 'What does the student do?', a: 'The student ___ a sandwich and ___ orange juice.', src: '문항 3', nt: '문항 3' },
      { t: 'qa', k: 'keep', img: 'gen:bts-04-mr-lee-coffee', title: '4.', q: 'What does he do?', a: 'He ___ coffee.', src: '문항 4', nt: '문항 4' },
      { t: 'qa', k: 'fix', img: 'c7407', title: '5.', q: 'What is it? Do you like it?', a: "It's ___. Yes, I ___. / No, I ___.", src: '문항 5', nt: '문항 5' },
      { t: 'qa', k: 'fix', img: '18699', title: '6.', q: 'Does she like mangoes?', a: '___, she ___.', src: '문항 6', nt: '문항 6', n: ['원본 «No» → 사진 속 소녀는 망고에 웃는 얼굴 → Yes, she does.'] },
      { t: 'qa', k: 'fix', img: '16714', label: 'Sam', title: '7.', q: 'What does Sam eat for breakfast?', a: 'He eats ___ and ___ for ___.', src: '문항 7', nt: '문항 7', n: ['원본 bacon(배우지 않은 낱말) → eggs and bread'] },
      { t: 'qa', k: 'keep', img: '12531', label: 'John', title: '8.', q: 'When does John drink tea?', a: 'He drinks ___ for ___.', src: '문항 8', nt: '문항 8' },
      { t: 'qa', k: 'keep', img: '12110', title: '9.', q: 'When do they eat fish and rice?', a: 'They eat fish and rice for ___.', src: '문항 9', nt: '문항 9' },
      { t: 'yourturn', k: 'keep', img: '13401', title: '10–11.', lines: ['What food do you like? — I like ___.', 'What drink do you like? — I like to drink ___.'], src: '문항 10·11', nt: '문항 10·11 — 자유 답' },
      { t: 'yourturn', k: 'keep', img: '18740', title: '12.', lines: ["What food don't you like?", "I don't like ___."], src: '문항 12', nt: '문항 12 — 자유 답' },
      { t: 'table', k: 'fix', small: 'My score', title: 'How did I do?', head: ['Score', 'Message', '다음 할 일'], rows: [['1–4', 'Good try!', '틀린 과를 한 번 더 복습해요'], ['5–8', 'Good job!', '틀린 문제만 다시 말해 봐요'], ['9–11', 'Great!', '거의 다 왔어요 — 하나만 더'], ['12 ⭐', 'Perfect!', 'BTS 5 로 출발! 🎉']], src: '점수표', nt: '점수표' },
      { t: 'goodbye', k: 'fix', src: 'Goodbye Song', nt: '작별 노래' },
      { t: 'next', k: 'new', img: 'gen:bts-04-bts5-days', q: 'What day is it today?', ko: '오늘은 무슨 요일일까요? (BTS 5 — Days of the Week)', nt: '다음 권 예고', n: ['BTS 5 첫 단원 «Days of the Week» 를 미리 보여 줍니다'] },
    ] },
  ],
};
