const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const { stripTypeScriptTypes } = require('node:module');
const { DatabaseSync } = require('node:sqlite');
(async () => {
 const sql = new DatabaseSync(':memory:');
 sql.exec("CREATE TABLE students_erp(user_id TEXT); INSERT INTO students_erp VALUES ('student');");
 const DB = {exec:async s=>sql.exec(s),prepare(s){return {bind(...values){return {first:async()=>sql.prepare(s).get(...values),run:async()=>({meta:sql.prepare(s).run(...values)})}}}}};
 let phone='01012345678', calls=0, mode='real', success=true;
 const context = vm.createContext({crypto:globalThis.crypto,TextEncoder,console,phonesForStudent:async()=>({parent:phone,student:''}),getSolapiMode:()=>mode,sendPlainSms:async(env,to,text,opts)=>{calls++;assert.equal(to,phone);assert.equal(opts.from,'16440561');assert.equal(text,'안녕하세요');return {ok:success,mode,messageId:'mock-provider-id'}}});
 const source=fs.readFileSync('cloudflare-deploy/src/counseling-send.ts','utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'');
 vm.runInContext(stripTypeScriptTypes(source),context);
 const env={DB}, base={user_id:'student',message:'안녕하세요',request_id:'12345678-12345678',confirmed:true,expected_phone:phone};
 const send=b=>context.sendCounselingSms(env,b,'manager');
 assert.equal((await send({...base,confirmed:false})).error,'invalid_request');
 assert.equal((await send({...base,message:'가'.repeat(1001)})).error,'invalid_request');
 assert.equal((await send({...base,user_id:'missing'})).error,'missing_phone');
 assert.equal((await send({...base,expected_phone:'01099999999'})).error,'recipient_changed');
 mode='mock';assert.equal((await send(base)).error,'delivery_not_ready');mode='real';assert.equal(calls,0);
 assert.equal((await send(base)).status,'accepted');assert.equal(calls,1);
 assert.equal((await send(base)).error,'duplicate_request');
 assert.equal((await send({...base,request_id:'22345678-12345678'})).error,'duplicate_request');assert.equal(calls,1);
 phone='';assert.equal((await send(base)).error,'missing_phone');
 phone='01087654321';success=false;
 assert.equal((await send({...base,expected_phone:phone,request_id:'32345678-12345678'})).error,'delivery_failed_or_unknown');
 assert.equal(calls,2);
 const route=fs.readFileSync('cloudflare-deploy/src/api-admin.ts','utf8');
 const area=route.slice(route.indexOf("if (path === '/api/admin/forecast/revenue'"),route.indexOf('// [Phase FAM]'));
 for(const guard of ['getAdminActor','actor.isTeacher','orgScopeDenyResponse',"request.headers.get('Origin') !== url.origin"])assert(area.includes(guard));
 console.log('PASS: no send without confirmation; recipient changes, missing contacts, test mode, long text rejected; exact sender/message; atomic duplicate protection; failed provider reported; admin/org/origin guards.');
})().catch(e=>{console.error(e);process.exit(1)});
