// Execute the API against isolated SQLite, never production D1.
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import vm from 'node:vm';
const require=createRequire(import.meta.url);
const ts=require('../cloudflare-deploy/node_modules/typescript');
const source=readFileSync('cloudflare-deploy/src/daily-handover.ts','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const db=new DatabaseSync(':memory:');
db.exec(`CREATE TABLE admin_account(username TEXT PRIMARY KEY,name TEXT); CREATE TABLE admin_scope(username TEXT,scope_type TEXT);
CREATE TABLE push_subscriptions(endpoint TEXT,user_id TEXT,enabled INTEGER);
CREATE TABLE push_queue(endpoint TEXT,title TEXT,body TEXT,url TEXT,icon TEXT,badge TEXT,tag TEXT,queued_at INTEGER);
INSERT INTO admin_account VALUES('alice','Alice'),('bob','Bob'),('carol','Carol'),('admin','Admin');
INSERT INTO admin_scope SELECT username,'hq' FROM admin_account;`);
function statement(sql){let args=[];return{bind(...a){args=a;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return{results:db.prepare(sql).all(...args)};},async run(){const r=db.prepare(sql).run(...args);return{meta:{changes:Number(r.changes)}};}};}
const env={DB:{prepare:statement,async batch(items){db.exec('BEGIN');try{const out=[];for(const s of items)out.push(await s.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}}};
let now=Date.parse('2026-09-28T10:00:00Z');
class TestDate extends Date{static now(){return now;}}
const module={exports:{}};
const context={module,exports:module.exports,console,Date:TestDate,Request,Response,URL,setTimeout,clearTimeout,require:(name)=>{
 if(name==='./approval-policy')return{isHqStaff:a=>!!a.ok&&!a.isTeacher&&['hq','staff'].includes(a.role),isExec:a=>a.username==='admin'};
 if(name==='./once-per-isolate')return{oncePerIsolate:f=>f};
 if(name==='./web-push')return{broadcastWebPush:async eps=>({sent:eps.length})};
 throw new Error(name);
}};
vm.runInNewContext(code,context);
const {handleDailyHandover:handle,checkHandover,normalizeHandover,reminderStage,runDailyHandoverSweep}=module.exports;
const actor=u=>({ok:true,username:u,name:u,role:'hq'});
async function api(route,body,u='alice',headers={}){const url=new URL('https://mangoi.ai/api/approval/handover'+route);const req=new Request(url,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});const res=await handle(req,url,env,typeof u==='string'?actor(u):u);return{status:res.status,...await res.json()};}
const draft={report_date:'2026-09-28',recipient:'bob',payload:{work:'Answered a Kakao inquiry.',no_issue:true,no_open:true},version:0,request_key:'daily_test_request_0001'};
assert.equal((await api('/home')).ok,true);
assert.equal((await api('/home',null,{ok:true,username:'teacher',isTeacher:true,role:'hq'})).status,403);
assert.equal((await api('/save',draft,'alice',{'Origin':'https://evil.test'})).status,403);
assert.equal((await api('/save',{...draft,submit:true})).status,400,'confirmation required');
assert.equal((await api('/save',{...draft,payload:{...draft.payload,work:''},submit:true,confirmed:true})).status,400);
assert.equal((await api('/save',{...draft,recipient:'missing'})).status,400);
assert.equal((await api('/save',draft)).row.version,1);
assert.equal((await api('/home',null,'bob')).reports.length,0,'draft is not delivered');
assert.equal((await api('/home',null,'admin')).reports.length,0,'draft remains private even in overview');
assert.equal((await api('/save',draft)).duplicate,true,'retry idempotent');
assert.equal((await api('/save',{...draft,request_key:'daily_test_request_other'})).status,409,'stale tab rejected');
const sent=await api('/save',{...draft,version:1,request_key:'daily_test_request_0002',submit:true,confirmed:true});
assert.equal(sent.row.status,'submitted');
assert.equal((await api('/home',null,'carol')).reports.length,0,'unrelated staff cannot read');
assert.equal((await api('/home',null,'bob')).reports.length,1);
assert.equal((await api('/ack',{id:sent.row.id,version:2},'alice')).status,403,'no self acknowledgement');
assert.equal((await api('/ack',{id:sent.row.id,version:2},'carol')).status,404);
assert.equal((await api('/ack',{id:sent.row.id,version:1},'bob')).status,409);
assert.equal((await api('/ack',{id:sent.row.id,version:2},'bob')).ok,true);
assert.equal((await api('/home')).own.status,'acknowledged');
assert.equal((await api('/return',{id:sent.row.id,version:3,feedback:'Confirm the result'},'bob')).ok,true);
assert.equal((await api('/home')).own.status,'changes_requested');
assert.equal(db.prepare('SELECT count(*) AS n FROM daily_handover_history').get().n,3);
const open=normalizeHandover({work:'Checked',no_issue:true,no_open:false,open:'Follow up',owner:'bob',deadline:'2026-09-29T10:00'});
assert.equal(checkHandover(open,'2026-09-28').ready,true);
assert.equal(checkHandover({...open,deadline:'2026-09-29T25:00'},'2026-09-28').ready,false);
const review=await api('/review',{...draft,use_ai:true});assert.equal(review.ai_state,'unavailable');assert.equal(review.check.ready,true);
env.AI={run:async()=>({response:JSON.stringify({work:'Answered inquiry.',issue:'Invented',open:'Invented',tips:['Confirm details.']})})};
const ai=await api('/review',{...draft,use_ai:true});assert.equal(ai.suggestion.issue,'');assert.equal(ai.suggestion.open,'');
assert.equal(reminderStage({enabled:1,weekdays:'1,2,3,4,5',due_time:'19:00',exempt_date:''},'2026-09-28',now),'due');
assert.equal(reminderStage({enabled:1,weekdays:'1',due_time:'19:00',exempt_date:'2026-09-28'},'2026-09-28',now),null);
assert.equal(reminderStage({enabled:1,weekdays:'0',due_time:'19:00'},'2026-09-28',now),null);
for(const user of ['alice','carol'])assert.equal((await api('/schedule',{enabled:true,weekdays:[1,2,3,4,5],due_time:'19:00',exempt_date:''},user)).ok,true);
await runDailyHandoverSweep(env);await runDailyHandoverSweep(env);
assert.equal(db.prepare('SELECT count(*) AS n FROM daily_handover_notices').get().n,1,'no duplicates and submitted report suppresses alert');
assert.equal(db.prepare('SELECT username FROM daily_handover_notices').get().username,'carol');
db.close();
console.log('PASS daily handover: authorization, real SQLite saves/history, retries/conflicts, review/ack/return, AI fallback, deadlines, workday/leave/duplicate reminder handling');
