// Isolated regressions for PR1371 review races. Real source, synthetic accounts, no network.
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
const root=resolve(process.env.PREFERENCE_SOURCE_ROOT||'.');
const source=readFileSync(resolve(root,'cloudflare-deploy/public/js/speech-preferences.js'),'utf8');
const html=readFileSync(resolve(root,'cloudflare-deploy/public/warmup.html'),'utf8');
const require=createRequire(import.meta.url),ts=require(resolve('cloudflare-deploy/node_modules/typescript'));
const scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)].filter(m=>!(/\bsrc=|application\/ld\+json/.test(m[1]))).map((m,i)=>ts.createSourceFile('inline'+i+'.js',m[2],ts.ScriptTarget.Latest,true,ts.ScriptKind.JS));
function fn(name){for(const f of scripts){let found;function walk(n){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)found=n.getText(f);if(!found)ts.forEachChild(n,walk);}walk(f);if(found)return found;}throw Error(name);}
async function flush(){for(let i=0;i<30;i++)await Promise.resolve();}
function storage(){const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};}
let pass=0,fail=0;const failures=[];async function test(name,f){try{await f();pass++;console.log('PASS '+name);}catch(e){fail++;failures.push({name,error:e.message});console.log('FAIL '+name+': '+e.message);}}
function preferences(app){const local=storage(),events={},requests=[],changes=[];local.setItem('mango_token',btoa(JSON.stringify({uid:'SyntheticStudent'}))+'.fixture');const window={addEventListener:(n,f)=>events[n]=f};vm.runInNewContext(source,{window,localStorage:local,sessionStorage:storage(),atob,AbortController,setTimeout:()=>1,clearTimeout(){},fetch:(_,opts)=>new Promise(resolve=>requests.push({method:opts.method,resolve}))});const pref=window.MangoiSpeechPreferences.create(app,3,v=>changes.push(v));return {pref,events,requests,changes,reply(i,level){requests[i].resolve({ok:true,json:async()=>({ok:true,level})});}};}
for(const app of ['warmup','friend'])for(const order of ['new-first','old-first'])await test(app+' concurrent restore '+order+' keeps newer server snapshot',async()=>{const p=preferences(app);await flush();p.events.online();await flush();assert.equal(p.requests.length,2);if(order==='new-first'){p.reply(1,5);await flush();assert.equal(p.pref.level,5);p.reply(0,1);}else{p.reply(0,1);await flush();p.reply(1,5);}await p.pref.ready;await flush();assert.equal(p.pref.level,5);assert.equal(p.changes.at(-1),5);});
function greeting(){let release,shown=0;const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{open:false,textContent:'',disabled:false});return nodes.get(id)};
 const s={console,URLSearchParams,setTimeout:()=>1,clearTimeout(){},clearInterval(){},_warmEpoch:0,_warmVoiceEpoch:0,_speakSeq:0,_warmPaused:false,_warmStarted:true,_warmGreetingPending:false,_warmGreetingEpoch:-1,_warmControllers:[],_fixRepeatTimers:[],_warmMicCancel:null,_idleTimer:null,_ansTimer:null,_recog:null,_whisperOn:false,_lastAiSpeak:null,_speechEverStarted:false,sending:false,document:{getElementById:node,querySelectorAll:()=>[]},MangoiVoice:{cancel(){}},setMicState(){},_stopSpeak(){s._speakSeq++},wuT:x=>x,getLoginId:()=>'',SESSION_ID:'synthetic-session',_warmLevel:3,_warmAge:'child',_warmLang:'en',WCTX:{textbook:'',level:'',sentences:[]},API_BASE:'',isZh:()=>false,updateTopicChip(){},fallbackGreeting(){shown++},warmupRatePreference:{loaded:false,ready:new Promise(r=>release=r)}};s.window=s;vm.createContext(s);vm.runInContext(['pauseWarmup','resumeWarmup','initGreeting'].map(fn).join('\n'),s);return {s,node,get shown(){return shown},resolve(){s.warmupRatePreference.loaded=true;release()}};}
for(const scenario of ['visible-before-ready','ready-while-hidden','several-hide-resume-cycles'])await test('initial greeting resumes once: '+scenario,async()=>{const g=greeting(),first=g.s.initGreeting();g.s.pauseWarmup();if(scenario==='visible-before-ready')g.s.resumeWarmup();if(scenario==='several-hide-resume-cycles')for(let i=0;i<5;i++){g.s.resumeWarmup();g.s.pauseWarmup();}g.resolve();await first;await flush();if(scenario!=='visible-before-ready'){assert.equal(g.shown,0);g.s.resumeWarmup();await flush();}assert.equal(g.shown,1);g.s.resumeWarmup();g.s.resumeWarmup();await flush();assert.equal(g.shown,1);});
await test('ordinary initial greeting completes once and later visibility does not repeat it',async()=>{const g=greeting(),first=g.s.initGreeting();g.resolve();await first;assert.equal(g.shown,1);g.s.pauseWarmup();g.s.resumeWarmup();await flush();assert.equal(g.shown,1);});
await test('open ending summary keeps the pending greeting paused',async()=>{const g=greeting(),first=g.s.initGreeting();g.s.pauseWarmup();g.node('wgSummary').open=true;g.resolve();await first;g.s.resumeWarmup();await flush();assert.equal(g.shown,0);assert.equal(g.s._warmPaused,true);});
console.log(`speech_preferences_lifecycle_harness: PASS ${pass} / FAIL ${fail}`);if(process.env.RESULT_PATH)writeFileSync(process.env.RESULT_PATH,JSON.stringify({source:'real source, synthetic local account and lifecycle fixtures',pass,fail,failures},null,2));process.exitCode=fail?1:0;
